insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (96593, 359297, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying E.T. the Extra-Terrestrial makes War of the Worlds a worthwhile recommendation.', null);  # E.T. the Extra-Terrestrial -> War of the Worlds
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (303564, 297761, 8, 'EliLevey', 'Both movies use suspense, atmosphere, and memorable genre moments, so Se7en should appeal to someone who liked Sixth Sense, The.', null);  # Sixth Sense, The -> Se7en
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (13978, 112290, 9, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying American History X makes Fight Club a worthwhile recommendation.', null);  # American History X -> Fight Club
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (109093, 37178, 9, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Fargo makes Big Lebowski, The a worthwhile recommendation.', null);  # Fargo -> Big Lebowski, The
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (134672, 362808, 8, 'EliLevey', 'Both movies mix romance, charm, and very watchable character moments, making When Harry Met Sally a sensible recommendation after Groundhog Day.', null);  # Groundhog Day -> When Harry Met Sally
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (46322, 111442, 9, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Breakfast Club, The makes Ferris Bueller''s Day Off a worthwhile recommendation.', null);  # Breakfast Club, The -> Ferris Bueller's Day Off
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (111442, 46322, 9, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Ferris Bueller''s Day Off makes Breakfast Club, The a worthwhile recommendation.', null);  # Ferris Bueller's Day Off -> Breakfast Club, The
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (328285, 328277, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Terminator, The makes Terminator 2: Judgment Day a natural recommendation.', null);  # Terminator, The -> Terminator 2: Judgment Day
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (10920, 10830, 8, 'EliLevey', 'Both movies use suspense, atmosphere, and memorable genre moments, so Alien should appeal to someone who liked Aliens.', null);  # Aliens -> Alien
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (224842, 134077, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Mystic River makes Green Mile, The a worthwhile recommendation.', null);  # Mystic River -> Green Mile, The
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (173933, 280270, 8, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Karate Kid, The makes Rocky a natural recommendation.', null);  # Karate Kid, The -> Rocky
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (272644, 113504, 9, 'EliLevey', 'Both movies are animated crowd-pleasers with strong humor, memorable characters, and emotional moments, so Finding Nemo fits well after Ratatouille.', null);  # Ratatouille -> Finding Nemo
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (276085, 14145, 9, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Requiem for a Dream makes American Psycho a worthwhile recommendation.', null);  # Requiem for a Dream -> American Psycho
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (235790, 263360, 8, 'EliLevey', 'Both movies mix romance, charm, and very watchable character moments, making Pretty Woman a sensible recommendation after Notting Hill.', null);  # Notting Hill -> Pretty Woman
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (210739, 112205, 9, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Men in Black makes Fifth Element, The a worthwhile recommendation.', null);  # Men in Black -> Fifth Element, The
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (207992, 336458, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Matrix, The makes Total Recall a worthwhile recommendation.', null);  # Matrix, The -> Total Recall
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (363780, 226939, 8, 'EliLevey', 'Both movies lean on broad comedy, quotable scenes, and easy rewatch value, making Naked Gun a strong comedy recommendation after White Chicks.', null);  # White Chicks -> Naked Gun
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (26064, 199255, 8, 'EliLevey', 'Both movies are animated crowd-pleasers with strong humor, memorable characters, and emotional moments, so Madagascar fits well after Babe.', null);  # Babe -> Madagascar
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (97727, 59578, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Edward Scissorhands makes Charlie and the Chocolate Factory a worthwhile recommendation.', null);  # Edward Scissorhands -> Charlie and the Chocolate Factory
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (158927, 337166, 8, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Incredibles, The makes Toy Story a natural recommendation.', null);  # Incredibles, The -> Toy Story
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (134077, 297838, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Green Mile, The makes Shawshank Redemption, The a worthwhile recommendation.', null);  # Green Mile, The -> Shawshank Redemption, The
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (189403, 117314, 8, 'EliLevey', 'Both movies offer stylish spy adventure, memorable action, and classic franchise appeal, so fans of Licence to Kill are likely to enjoy For Your Eyes Only as well.', null);  # Licence to Kill -> For Your Eyes Only
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (368418, 335336, 9, 'EliLevey', 'Both movies offer stylish spy adventure, memorable action, and classic franchise appeal, so fans of World Is Not Enough, The are likely to enjoy Tomorrow Never Dies as well.', null);  # World Is Not Enough, The -> Tomorrow Never Dies
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (359297, 96593, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying War of the Worlds makes E.T. the Extra-Terrestrial a worthwhile recommendation.', null);  # War of the Worlds -> E.T. the Extra-Terrestrial
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (222339, 256632, 8, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Mummy, The makes Pirates of the Caribbean: The Curse of the Black Pearl a natural recommendation.', null);  # Mummy, The -> Pirates of the Caribbean: The Curse of the Black Pearl
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (46169, 129185, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Braveheart makes Gladiator a worthwhile recommendation.', null);  # Braveheart -> Gladiator
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (166917, 131665, 9, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Jerry Maguire makes Good Will Hunting a worthwhile recommendation.', null);  # Jerry Maguire -> Good Will Hunting
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (123849, 56304, 8, 'EliLevey', 'Both films focus on crime, tension, sharp characters, and memorable dialogue, making Casino a strong recommendation for someone who enjoyed Gangs of New York.', null);  # Gangs of New York -> Casino
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (66194, 209133, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Clueless makes Mean Girls a worthwhile recommendation.', null);  # Clueless -> Mean Girls
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (312151, 312150, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Spy Kids 2: Island of Lost Dreams makes Spy Kids a natural recommendation.', null);  # Spy Kids 2: Island of Lost Dreams -> Spy Kids
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (151616, 644, 8, 'EliLevey', 'Both movies mix romance, charm, and very watchable character moments, making 10 Things I Hate About You a sensible recommendation after How to Lose a Guy in 10 Days.', null);  # How to Lose a Guy in 10 Days -> 10 Things I Hate About You
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (328277, 328285, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Terminator 2: Judgment Day makes Terminator, The a natural recommendation.', null);  # Terminator 2: Judgment Day -> Terminator, The
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (311037, 311038, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Spider-Man makes Spider-Man 2 a natural recommendation.', null);  # Spider-Man -> Spider-Man 2
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (45129, 45128, 9, 'EliLevey', 'Both movies rely on tense action, strong momentum, and memorable set pieces, so Bourne Identity, The is a good follow-up to Bourne Supremacy, The.', null);  # Bourne Supremacy, The -> Bourne Identity, The
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (104699, 9125, 8, 'EliLevey', 'Both movies lean on broad comedy, quotable scenes, and easy rewatch value, making Airplane! a strong comedy recommendation after Eurotrip.', null);  # Eurotrip -> Airplane!
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (215880, 215876, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Mission: Impossible III makes Mission Impossible a natural recommendation.', null);  # Mission: Impossible III -> Mission Impossible
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (336458, 207992, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Total Recall makes Matrix, The a worthwhile recommendation.', null);  # Total Recall -> Matrix, The
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (130121, 131780, 9, 'EliLevey', 'Both films focus on crime, tension, sharp characters, and memorable dialogue, making Goodfellas a strong recommendation for someone who enjoyed Godfather.', null);  # Godfather -> Goodfellas
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (270971, 326155, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Raging Bull makes Taxi Driver a worthwhile recommendation.', null);  # Raging Bull -> Taxi Driver
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (297802, 289666, 8, 'EliLevey', 'Both movies use suspense, atmosphere, and memorable genre moments, so Scary Movie should appeal to someone who liked Shaun of the Dead.', null);  # Shaun of the Dead -> Scary Movie
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (90772, 215670, 9, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Donnie Darko makes Memento a worthwhile recommendation.', null);  # Donnie Darko -> Memento
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (177328, 178103, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying King Kong makes Jurassic Park a worthwhile recommendation.', null);  # King Kong -> Jurassic Park
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (337814, 141544, 8, 'EliLevey', 'Both films focus on crime, tension, sharp characters, and memorable dialogue, making Heat a strong recommendation for someone who enjoyed Training Day.', null);  # Training Day -> Heat
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (375827, 16006, 9, 'EliLevey', 'Both movies lean on broad comedy, quotable scenes, and easy rewatch value, making Anchorman: The Legend of Ron Burgundy a strong comedy recommendation after Zoolander.', null);  # Zoolander -> Anchorman: The Legend of Ron Burgundy
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (264146, 9795, 8, 'EliLevey', 'Both movies are animated crowd-pleasers with strong humor, memorable characters, and emotional moments, so Aladdin fits well after Princess Bride, The.', null);  # Princess Bride, The -> Aladdin
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (160524, 257756, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Insomnia makes Prestige, The a worthwhile recommendation.', null);  # Insomnia -> Prestige, The
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (112290, 215670, 9, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Fight Club makes Memento a worthwhile recommendation.', null);  # Fight Club -> Memento
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (223799, 969, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying My Cousin Vinny makes 12 Angry Men a worthwhile recommendation.', null);  # My Cousin Vinny -> 12 Angry Men
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (80583, 131665, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Dead Poets Society makes Good Will Hunting a worthwhile recommendation.', null);  # Dead Poets Society -> Good Will Hunting
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (55727, 337166, 8, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Cars makes Toy Story a natural recommendation.', null);  # Cars -> Toy Story
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (300229, 300230, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Shrek makes Shrek 2 a natural recommendation.', null);  # Shrek -> Shrek 2
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (37178, 267038, 8, 'EliLevey', 'Both films focus on crime, tension, sharp characters, and memorable dialogue, making Pulp Fiction a strong recommendation for someone who enjoyed Big Lebowski, The.', null);  # Big Lebowski, The -> Pulp Fiction
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (2709, 138797, 8, 'EliLevey', 'Both movies mix romance, charm, and very watchable character moments, making Happy Gilmore a sensible recommendation after 50 First Dates.', null);  # 50 First Dates -> Happy Gilmore
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (131665, 80583, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Good Will Hunting makes Dead Poets Society a worthwhile recommendation.', null);  # Good Will Hunting -> Dead Poets Society
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (335336, 368418, 9, 'EliLevey', 'Both movies offer stylish spy adventure, memorable action, and classic franchise appeal, so fans of Tomorrow Never Dies are likely to enjoy World Is Not Enough, The as well.', null);  # Tomorrow Never Dies -> World Is Not Enough, The
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (333856, 117874, 9, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Titanic makes Forrest Gump a worthwhile recommendation.', null);  # Titanic -> Forrest Gump
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (139657, 139650, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Harry Potter and the Sorcerer''s Stone makes Harry Potter and the Chamber of Secrets a natural recommendation.', null);  # Harry Potter and the Sorcerer's Stone -> Harry Potter and the Chamber of Secrets
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (26847, 26846, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Back to the Future Part III makes Back to the Future Part II a natural recommendation.', null);  # Back to the Future Part III -> Back to the Future Part II
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (256632, 256631, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Pirates of the Caribbean: The Curse of the Black Pearl makes Pirates of the Caribbean 2 a natural recommendation.', null);  # Pirates of the Caribbean: The Curse of the Black Pearl -> Pirates of the Caribbean 2
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (199255, 155213, 9, 'EliLevey', 'Both movies are animated crowd-pleasers with strong humor, memorable characters, and emotional moments, so Ice Age fits well after Madagascar.', null);  # Madagascar -> Ice Age
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (14132, 289666, 9, 'EliLevey', 'Both movies use suspense, atmosphere, and memorable genre moments, so Scary Movie should appeal to someone who liked American Pie 2.', null);  # American Pie 2 -> Scary Movie
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (158999, 79716, 8, 'EliLevey', 'Both movies offer stylish spy adventure, memorable action, and classic franchise appeal, so fans of Independence Day are likely to enjoy Day After Tomorrow, The as well.', null);  # Independence Day -> Day After Tomorrow, The
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (301540, 297761, 8, 'EliLevey', 'Both movies use suspense, atmosphere, and memorable genre moments, so Se7en should appeal to someone who liked Silence of the Lambs, The.', null);  # Silence of the Lambs, The -> Se7en
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (26844, 26846, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Back to the Future makes Back to the Future Part II a natural recommendation.', null);  # Back to the Future -> Back to the Future Part II
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (112205, 210739, 9, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Fifth Element, The makes Men in Black a worthwhile recommendation.', null);  # Fifth Element, The -> Men in Black
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (1529, 109421, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying 2 Fast 2 Furious makes Fast and the Furious, The a natural recommendation.', null);  # 2 Fast 2 Furious -> Fast and the Furious, The
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (9795, 191246, 9, 'EliLevey', 'Both movies are animated crowd-pleasers with strong humor, memorable characters, and emotional moments, so Lion King, The fits well after Aladdin.', null);  # Aladdin -> Lion King, The
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (279841, 40199, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying RoboCop makes Blade Runner a worthwhile recommendation.', null);  # RoboCop -> Blade Runner
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (312152, 312151, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Spy Kids 3-D: Game Over makes Spy Kids 2: Island of Lost Dreams a natural recommendation.', null);  # Spy Kids 3-D: Game Over -> Spy Kids 2: Island of Lost Dreams
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (155213, 199255, 9, 'EliLevey', 'Both movies are animated crowd-pleasers with strong humor, memorable characters, and emotional moments, so Madagascar fits well after Ice Age.', null);  # Ice Age -> Madagascar
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (162380, 158927, 9, 'EliLevey', 'Both movies are animated crowd-pleasers with strong humor, memorable characters, and emotional moments, so Incredibles, The fits well after Iron Man.', null);  # Iron Man -> Incredibles, The
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (238072, 238073, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Ocean''s Eleven makes Ocean''s Twelve a natural recommendation.', null);  # Ocean's Eleven -> Ocean's Twelve
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (195300, 362808, 8, 'EliLevey', 'Both movies mix romance, charm, and very watchable character moments, making When Harry Met Sally a sensible recommendation after Love Actually.', null);  # Love Actually -> When Harry Met Sally
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (50639, 215670, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Butterfly Effect, The makes Memento a worthwhile recommendation.', null);  # Butterfly Effect, The -> Memento
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (138797, 37002, 9, 'EliLevey', 'Both movies lean on broad comedy, quotable scenes, and easy rewatch value, making Big Daddy a strong comedy recommendation after Happy Gilmore.', null);  # Happy Gilmore -> Big Daddy
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (155070, 279841, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying I, Robot makes RoboCop a worthwhile recommendation.', null);  # I, Robot -> RoboCop
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (9125, 226939, 8, 'EliLevey', 'Both movies lean on broad comedy, quotable scenes, and easy rewatch value, making Naked Gun a strong comedy recommendation after Airplane!.', null);  # Airplane! -> Naked Gun
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (131885, 148200, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Goonies, The makes Home Alone a worthwhile recommendation.', null);  # Goonies, The -> Home Alone
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (289558, 56304, 8, 'EliLevey', 'Both films focus on crime, tension, sharp characters, and memorable dialogue, making Casino a strong recommendation for someone who enjoyed Scarface.', null);  # Scarface -> Casino
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (235541, 195300, 9, 'EliLevey', 'Both movies mix romance, charm, and very watchable character moments, making Love Actually a sensible recommendation after Notebook, The.', null);  # Notebook, The -> Love Actually
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (39551, 289109, 9, 'EliLevey', 'Both movies rely on tense action, strong momentum, and memorable set pieces, so Saving Private Ryan is a good follow-up to Black Hawk Down.', null);  # Black Hawk Down -> Saving Private Ryan
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (299073, 165961, 8, 'EliLevey', 'Both movies use suspense, atmosphere, and memorable genre moments, so Jaws should appeal to someone who liked Shining, The.', null);  # Shining, The -> Jaws
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (79716, 158999, 8, 'EliLevey', 'Both movies offer stylish spy adventure, memorable action, and classic franchise appeal, so fans of Day After Tomorrow, The are likely to enjoy Independence Day as well.', null);  # Day After Tomorrow, The -> Independence Day
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (289787, 32114, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Scent of a Woman makes Beautiful Mind, A a worthwhile recommendation.', null);  # Scent of a Woman -> Beautiful Mind, A
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (14145, 112290, 9, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying American Psycho makes Fight Club a worthwhile recommendation.', null);  # American Psycho -> Fight Club
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313476, 313477, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Star Wars: Episode II - Attack of the Clones makes Star Wars Episode III a natural recommendation.', null);  # Star Wars: Episode II - Attack of the Clones -> Star Wars Episode III
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (267038, 276217, 9, 'EliLevey', 'Both films focus on crime, tension, sharp characters, and memorable dialogue, making Reservoir Dogs a strong recommendation for someone who enjoyed Pulp Fiction.', null);  # Pulp Fiction -> Reservoir Dogs
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (32114, 131665, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Beautiful Mind, A makes Good Will Hunting a worthwhile recommendation.', null);  # Beautiful Mind, A -> Good Will Hunting
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (291221, 289666, 8, 'EliLevey', 'Both movies use suspense, atmosphere, and memorable genre moments, so Scary Movie should appeal to someone who liked Scream.', null);  # Scream -> Scary Movie
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (194502, 194500, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Lord of the Rings: The Two Towers, The makes Lord of the Rings: The Return of the King, The a natural recommendation.', null);  # Lord of the Rings: The Two Towers, The -> Lord of the Rings: The Return of the King, The
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (191246, 32178, 9, 'EliLevey', 'Both movies are animated crowd-pleasers with strong humor, memorable characters, and emotional moments, so Beauty and the Beast fits well after Lion King, The.', null);  # Lion King, The -> Beauty and the Beast
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (275453, 66286, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Remember the Titans makes Coach Carter a worthwhile recommendation.', null);  # Remember the Titans -> Coach Carter
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (32178, 191246, 9, 'EliLevey', 'Both movies are animated crowd-pleasers with strong humor, memorable characters, and emotional moments, so Lion King, The fits well after Beauty and the Beast.', null);  # Beauty and the Beast -> Lion King, The
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (370017, 1529, 9, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying XXX makes 2 Fast 2 Furious a worthwhile recommendation.', null);  # XXX -> 2 Fast 2 Furious
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (139654, 139653, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Harry Potter and the Order of the Phoenix makes Harry Potter and the Half-Blood Prince a natural recommendation.', null);  # Harry Potter and the Order of the Phoenix -> Harry Potter and the Half-Blood Prince
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (290070, 254986, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Schindler''s List makes Pianist, The a worthwhile recommendation.', null);  # Schindler's List -> Pianist, The
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (37002, 138797, 9, 'EliLevey', 'Both movies lean on broad comedy, quotable scenes, and easy rewatch value, making Happy Gilmore a strong comedy recommendation after Big Daddy.', null);  # Big Daddy -> Happy Gilmore
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (337166, 337168, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Toy Story makes Toy Story 2 a natural recommendation.', null);  # Toy Story -> Toy Story 2
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (280284, 280282, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Rocky IV makes Rocky III a natural recommendation.', null);  # Rocky IV -> Rocky III
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (117314, 189403, 8, 'EliLevey', 'Both movies offer stylish spy adventure, memorable action, and classic franchise appeal, so fans of For Your Eyes Only are likely to enjoy Licence to Kill as well.', null);  # For Your Eyes Only -> Licence to Kill
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (109421, 1529, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Fast and the Furious, The makes 2 Fast 2 Furious a natural recommendation.', null);  # Fast and the Furious, The -> 2 Fast 2 Furious
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (238073, 238072, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Ocean''s Twelve makes Ocean''s Eleven a natural recommendation.', null);  # Ocean's Twelve -> Ocean's Eleven
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (86274, 310726, 8, 'EliLevey', 'Both movies rely on tense action, strong momentum, and memorable set pieces, so Speed is a good follow-up to Die Hard.', null);  # Die Hard -> Speed
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (340901, 90772, 9, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Truman Show, The makes Donnie Darko a worthwhile recommendation.', null);  # Truman Show, The -> Donnie Darko
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (87280, 195300, 8, 'EliLevey', 'Both movies mix romance, charm, and very watchable character moments, making Love Actually a sensible recommendation after Dirty Dancing.', null);  # Dirty Dancing -> Love Actually
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (131780, 56304, 8, 'EliLevey', 'Both films focus on crime, tension, sharp characters, and memorable dialogue, making Casino a strong recommendation for someone who enjoyed Goodfellas.', null);  # Goodfellas -> Casino
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (121538, 18960, 8, 'EliLevey', 'Both movies rely on tense action, strong momentum, and memorable set pieces, so Apocalypse Now is a good follow-up to Full Metal Jacket.', null);  # Full Metal Jacket -> Apocalypse Now
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (159175, 159172, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Indiana Jones and the Temple of Doom makes Indiana Jones and the Last Crusade a worthwhile recommendation.', null);  # Indiana Jones and the Temple of Doom -> Indiana Jones and the Last Crusade
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (163715, 238072, 9, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Italian Job, The makes Ocean''s Eleven a natural recommendation.', null);  # Italian Job, The -> Ocean's Eleven
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (16006, 375827, 9, 'EliLevey', 'Both movies lean on broad comedy, quotable scenes, and easy rewatch value, making Zoolander a strong comedy recommendation after Anchorman: The Legend of Ron Burgundy.', null);  # Anchorman: The Legend of Ron Burgundy -> Zoolander
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (56304, 131780, 8, 'EliLevey', 'Both films focus on crime, tension, sharp characters, and memorable dialogue, making Goodfellas a strong recommendation for someone who enjoyed Casino.', null);  # Casino -> Goodfellas
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313474, 313476, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Star Wars: Episode I - The Phantom Menace makes Star Wars: Episode II - Attack of the Clones a natural recommendation.', null);  # Star Wars: Episode I - The Phantom Menace -> Star Wars: Episode II - Attack of the Clones
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (340652, 2238, 9, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Troy makes 300 a worthwhile recommendation.', null);  # Troy -> 300
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (113504, 218415, 9, 'EliLevey', 'Both movies are animated crowd-pleasers with strong humor, memorable characters, and emotional moments, so Monsters Inc fits well after Finding Nemo.', null);  # Finding Nemo -> Monsters Inc
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (139653, 139654, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Harry Potter and the Half-Blood Prince makes Harry Potter and the Order of the Phoenix a natural recommendation.', null);  # Harry Potter and the Half-Blood Prince -> Harry Potter and the Order of the Phoenix
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (129185, 340652, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Gladiator makes Troy a worthwhile recommendation.', null);  # Gladiator -> Troy
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (66286, 275453, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Coach Carter makes Remember the Titans a worthwhile recommendation.', null);  # Coach Carter -> Remember the Titans
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (348944, 297761, 9, 'EliLevey', 'Both films focus on crime, tension, sharp characters, and memorable dialogue, making Se7en a strong recommendation for someone who enjoyed Usual Suspects, The.', null);  # Usual Suspects, The -> Se7en
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (194497, 194502, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Lord of the Rings: The Fellowship of the Ring, The makes Lord of the Rings: The Two Towers, The a natural recommendation.', null);  # Lord of the Rings: The Fellowship of the Ring, The -> Lord of the Rings: The Two Towers, The
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (248878, 119358, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Parent Trap, The makes Freaky Friday a worthwhile recommendation.', null);  # Parent Trap, The -> Freaky Friday
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (254986, 290070, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Pianist, The makes Schindler''s List a worthwhile recommendation.', null);  # Pianist, The -> Schindler's List
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (194500, 194502, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Lord of the Rings: The Return of the King, The makes Lord of the Rings: The Two Towers, The a natural recommendation.', null);  # Lord of the Rings: The Return of the King, The -> Lord of the Rings: The Two Towers, The
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (644, 209133, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying 10 Things I Hate About You makes Mean Girls a worthwhile recommendation.', null);  # 10 Things I Hate About You -> Mean Girls
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313479, 313478, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Star Wars: Episode VI - Return of the Jedi makes Star Wars: Episode V - The Empire Strikes Back a natural recommendation.', null);  # Star Wars: Episode VI - Return of the Jedi -> Star Wars: Episode V - The Empire Strikes Back
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (119358, 248878, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Freaky Friday makes Parent Trap, The a worthwhile recommendation.', null);  # Freaky Friday -> Parent Trap, The
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (40187, 142491, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Blade makes Hellboy a worthwhile recommendation.', null);  # Blade -> Hellboy
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (276217, 267038, 9, 'EliLevey', 'Both films focus on crime, tension, sharp characters, and memorable dialogue, making Pulp Fiction a strong recommendation for someone who enjoyed Reservoir Dogs.', null);  # Reservoir Dogs -> Pulp Fiction
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (302329, 40187, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Sin City makes Blade a worthwhile recommendation.', null);  # Sin City -> Blade
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (194123, 66286, 9, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Longest Yard, The makes Coach Carter a worthwhile recommendation.', null);  # Longest Yard, The -> Coach Carter
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (256631, 256632, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Pirates of the Caribbean 2 makes Pirates of the Caribbean: The Curse of the Black Pearl a natural recommendation.', null);  # Pirates of the Caribbean 2 -> Pirates of the Caribbean: The Curse of the Black Pearl
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (207157, 138797, 9, 'EliLevey', 'Both movies lean on broad comedy, quotable scenes, and easy rewatch value, making Happy Gilmore a strong comedy recommendation after Mask, The.', null);  # Mask, The -> Happy Gilmore
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30955, 30967, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Batman makes Batman Returns a natural recommendation.', null);  # Batman -> Batman Returns
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (328272, 18979, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Terminal, The makes Apollo 13 a worthwhile recommendation.', null);  # Terminal, The -> Apollo 13
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (209133, 66194, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Mean Girls makes Clueless a worthwhile recommendation.', null);  # Mean Girls -> Clueless
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (280305, 280284, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Rocky V makes Rocky IV a natural recommendation.', null);  # Rocky V -> Rocky IV
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (271095, 159172, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Raiders of the Lost Ark makes Indiana Jones and the Last Crusade a worthwhile recommendation.', null);  # Raiders of the Lost Ark -> Indiana Jones and the Last Crusade
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (139652, 139655, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Harry Potter and the Goblet of Fire makes Harry Potter and the Prisoner of Azkaban a natural recommendation.', null);  # Harry Potter and the Goblet of Fire -> Harry Potter and the Prisoner of Azkaban
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30967, 30955, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Batman Returns makes Batman a natural recommendation.', null);  # Batman Returns -> Batman
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (34077, 113277, 9, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Benjamin Button makes Finding Neverland a worthwhile recommendation.', null);  # Benjamin Button -> Finding Neverland
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (310726, 86274, 8, 'EliLevey', 'Both movies rely on tense action, strong momentum, and memorable set pieces, so Die Hard is a good follow-up to Speed.', null);  # Speed -> Die Hard
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (312150, 312151, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Spy Kids makes Spy Kids 2: Island of Lost Dreams a natural recommendation.', null);  # Spy Kids -> Spy Kids 2: Island of Lost Dreams
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (139650, 139657, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Harry Potter and the Chamber of Secrets makes Harry Potter and the Sorcerer''s Stone a natural recommendation.', null);  # Harry Potter and the Chamber of Secrets -> Harry Potter and the Sorcerer's Stone
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (209591, 235541, 8, 'EliLevey', 'Both movies mix romance, charm, and very watchable character moments, making Notebook, The a sensible recommendation after Meet Joe Black.', null);  # Meet Joe Black -> Notebook, The
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (337168, 337166, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Toy Story 2 makes Toy Story a natural recommendation.', null);  # Toy Story 2 -> Toy Story
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (139655, 139652, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Harry Potter and the Prisoner of Azkaban makes Harry Potter and the Goblet of Fire a natural recommendation.', null);  # Harry Potter and the Prisoner of Azkaban -> Harry Potter and the Goblet of Fire
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (176711, 176712, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Kill Bill: Vol. 1 makes Kill Bill Vol. 2 a natural recommendation.', null);  # Kill Bill: Vol. 1 -> Kill Bill Vol. 2
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (280282, 280284, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Rocky III makes Rocky IV a natural recommendation.', null);  # Rocky III -> Rocky IV
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (297838, 134077, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Shawshank Redemption, The makes Green Mile, The a worthwhile recommendation.', null);  # Shawshank Redemption, The -> Green Mile, The
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313478, 313479, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Star Wars: Episode V - The Empire Strikes Back makes Star Wars: Episode VI - Return of the Jedi a natural recommendation.', null);  # Star Wars: Episode V - The Empire Strikes Back -> Star Wars: Episode VI - Return of the Jedi
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30965, 30967, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Batman Forever makes Batman Returns a natural recommendation.', null);  # Batman Forever -> Batman Returns
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (142491, 40187, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Hellboy makes Blade a worthwhile recommendation.', null);  # Hellboy -> Blade
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (289666, 291221, 8, 'EliLevey', 'Both movies use suspense, atmosphere, and memorable genre moments, so Scream should appeal to someone who liked Scary Movie.', null);  # Scary Movie -> Scream
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (297761, 301540, 8, 'EliLevey', 'Both movies use suspense, atmosphere, and memorable genre moments, so Silence of the Lambs, The should appeal to someone who liked Se7en.', null);  # Se7en -> Silence of the Lambs, The
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (134979, 30959, 9, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Dark Knight, The makes Batman Begins a natural recommendation.', null);  # Dark Knight, The -> Batman Begins
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (178103, 165961, 8, 'EliLevey', 'Both movies use suspense, atmosphere, and memorable genre moments, so Jaws should appeal to someone who liked Jurassic Park.', null);  # Jurassic Park -> Jaws
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (113277, 34077, 9, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Finding Neverland makes Benjamin Button a worthwhile recommendation.', null);  # Finding Neverland -> Benjamin Button
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (257756, 160524, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Prestige, The makes Insomnia a worthwhile recommendation.', null);  # Prestige, The -> Insomnia
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (190590, 276217, 9, 'EliLevey', 'Both films focus on crime, tension, sharp characters, and memorable dialogue, making Reservoir Dogs a strong recommendation for someone who enjoyed Leon: The Professional.', null);  # Leon: The Professional -> Reservoir Dogs
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (215670, 257756, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Memento makes Prestige, The a worthwhile recommendation.', null);  # Memento -> Prestige, The
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (330566, 141544, 8, 'EliLevey', 'Both films focus on crime, tension, sharp characters, and memorable dialogue, making Heat a strong recommendation for someone who enjoyed The Departed.', null);  # The Departed -> Heat
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (10830, 10920, 8, 'EliLevey', 'Both movies use suspense, atmosphere, and memorable genre moments, so Aliens should appeal to someone who liked Alien.', null);  # Alien -> Aliens
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30959, 134979, 9, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Batman Begins makes Dark Knight, The a natural recommendation.', null);  # Batman Begins -> Dark Knight, The
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (40199, 65764, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Blade Runner makes Clockwork Orange, A a worthwhile recommendation.', null);  # Blade Runner -> Clockwork Orange, A
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (56871, 166917, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Catch Me If You Can makes Jerry Maguire a worthwhile recommendation.', null);  # Catch Me If You Can -> Jerry Maguire
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (59578, 97727, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Charlie and the Chocolate Factory makes Edward Scissorhands a worthwhile recommendation.', null);  # Charlie and the Chocolate Factory -> Edward Scissorhands
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (92573, 120574, 9, 'EliLevey', 'Both movies offer stylish spy adventure, memorable action, and classic franchise appeal, so fans of Dr. No are likely to enjoy From Russia with Love as well.', null);  # Dr. No -> From Russia with Love
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (130953, 332065, 9, 'EliLevey', 'Both movies offer stylish spy adventure, memorable action, and classic franchise appeal, so fans of Goldfinger are likely to enjoy Thunderball as well.', null);  # Goldfinger -> Thunderball
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (159172, 271095, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Indiana Jones and the Last Crusade makes Raiders of the Lost Ark a worthwhile recommendation.', null);  # Indiana Jones and the Last Crusade -> Raiders of the Lost Ark
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (159665, 176711, 9, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Inglorious Bastards makes Kill Bill: Vol. 1 a natural recommendation.', null);  # Inglorious Bastards -> Kill Bill: Vol. 1
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (165961, 10830, 8, 'EliLevey', 'Both movies use suspense, atmosphere, and memorable genre moments, so Alien should appeal to someone who liked Jaws.', null);  # Jaws -> Alien
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (176712, 176711, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Kill Bill Vol. 2 makes Kill Bill: Vol. 1 a natural recommendation.', null);  # Kill Bill Vol. 2 -> Kill Bill: Vol. 1
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (185628, 45128, 9, 'EliLevey', 'Both movies rely on tense action, strong momentum, and memorable set pieces, so Bourne Identity, The is a good follow-up to Last Samurai, The.', null);  # Last Samurai, The -> Bourne Identity, The
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (215876, 215879, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Mission Impossible makes Mission Impossible II a natural recommendation.', null);  # Mission Impossible -> Mission Impossible II
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (215879, 215876, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Mission Impossible II makes Mission Impossible a natural recommendation.', null);  # Mission Impossible II -> Mission Impossible
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (220805, 163715, 9, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Mr. and Mrs. Smith makes Italian Job, The a worthwhile recommendation.', null);  # Mr. and Mrs. Smith -> Italian Job, The
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (263360, 235790, 8, 'EliLevey', 'Both movies mix romance, charm, and very watchable character moments, making Notting Hill a sensible recommendation after Pretty Woman.', null);  # Pretty Woman -> Notting Hill
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (280270, 280281, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Rocky makes Rocky II a natural recommendation.', null);  # Rocky -> Rocky II
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (280281, 280270, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Rocky II makes Rocky a natural recommendation.', null);  # Rocky II -> Rocky
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (289109, 39551, 9, 'EliLevey', 'Both movies rely on tense action, strong momentum, and memorable set pieces, so Black Hawk Down is a good follow-up to Saving Private Ryan.', null);  # Saving Private Ryan -> Black Hawk Down
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (300230, 300229, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Shrek 2 makes Shrek a natural recommendation.', null);  # Shrek 2 -> Shrek
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (311038, 311037, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Spider-Man 2 makes Spider-Man a natural recommendation.', null);  # Spider-Man 2 -> Spider-Man
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313477, 313476, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Star Wars Episode III makes Star Wars: Episode II - Attack of the Clones a natural recommendation.', null);  # Star Wars Episode III -> Star Wars: Episode II - Attack of the Clones
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (326155, 65764, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Taxi Driver makes Clockwork Orange, A a worthwhile recommendation.', null);  # Taxi Driver -> Clockwork Orange, A
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (335835, 86274, 9, 'EliLevey', 'Both movies rely on tense action, strong momentum, and memorable set pieces, so Die Hard is a good follow-up to Top Gun.', null);  # Top Gun -> Die Hard
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (45128, 45129, 9, 'EliLevey', 'Both movies rely on tense action, strong momentum, and memorable set pieces, so Bourne Supremacy, The is a good follow-up to Bourne Identity, The.', null);  # Bourne Identity, The -> Bourne Supremacy, The
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (18960, 121538, 8, 'EliLevey', 'Both movies rely on tense action, strong momentum, and memorable set pieces, so Full Metal Jacket is a good follow-up to Apocalypse Now.', null);  # Apocalypse Now -> Full Metal Jacket
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (65764, 326155, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Clockwork Orange, A makes Taxi Driver a worthwhile recommendation.', null);  # Clockwork Orange, A -> Taxi Driver
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (141544, 330566, 8, 'EliLevey', 'Both films focus on crime, tension, sharp characters, and memorable dialogue, making The Departed a strong recommendation for someone who enjoyed Heat.', null);  # Heat -> The Departed
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (969, 223799, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying 12 Angry Men makes My Cousin Vinny a worthwhile recommendation.', null);  # 12 Angry Men -> My Cousin Vinny
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (2238, 340652, 9, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying 300 makes Troy a worthwhile recommendation.', null);  # 300 -> Troy
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (148200, 131885, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Home Alone makes Goonies, The a worthwhile recommendation.', null);  # Home Alone -> Goonies, The
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (369458, 142491, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying X-Men makes Hellboy a worthwhile recommendation.', null);  # X-Men -> Hellboy
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (218415, 113504, 9, 'EliLevey', 'Both movies are animated crowd-pleasers with strong humor, memorable characters, and emotional moments, so Finding Nemo fits well after Monsters Inc.', null);  # Monsters Inc -> Finding Nemo
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (26846, 26844, 10, 'EliLevey', 'Both movies belong to the same kind of franchise-driven storytelling, with connected themes, familiar energy, and clear audience overlap, so enjoying Back to the Future Part II makes Back to the Future a natural recommendation.', null);  # Back to the Future Part II -> Back to the Future
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (362808, 235790, 8, 'EliLevey', 'Both movies mix romance, charm, and very watchable character moments, making Notting Hill a sensible recommendation after When Harry Met Sally.', null);  # When Harry Met Sally -> Notting Hill
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (18979, 328272, 8, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Apollo 13 makes Terminal, The a worthwhile recommendation.', null);  # Apollo 13 -> Terminal, The
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (120574, 92573, 9, 'EliLevey', 'Both movies offer stylish spy adventure, memorable action, and classic franchise appeal, so fans of From Russia with Love are likely to enjoy Dr. No as well.', null);  # From Russia with Love -> Dr. No
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (332065, 130953, 9, 'EliLevey', 'Both movies offer stylish spy adventure, memorable action, and classic franchise appeal, so fans of Thunderball are likely to enjoy Goldfinger as well.', null);  # Thunderball -> Goldfinger
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (117874, 297838, 9, 'EliLevey', 'Both movies have strong storytelling, memorable performances, and lasting rewatch value, so enjoying Forrest Gump makes Shawshank Redemption, The a worthwhile recommendation.', null);  # Forrest Gump -> Shawshank Redemption, The
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (226939, 9125, 8, 'EliLevey', 'Both movies lean on broad comedy, quotable scenes, and easy rewatch value, making Airplane! a strong comedy recommendation after Naked Gun.', null);  # Naked Gun -> Airplane!