
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (77,9,'orizehavi','A highly entertaining cat-and-mouse chase showcasing social engineering and check fraud brilliance.',NULL); # 77 'Catch Me If You Can': Behind the Camera 2003	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (644,8,'orizehavi','A fantastic high school adaptation of Shakespeare. The comedic timing and soundtrack are iconic.',NULL); # 644 10 Things I Hate About You 1999	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (1374,9,'orizehavi','The one-shot technique creates unparalleled immersion in the trench warfare environment.',NULL); # 1374 1917 1970	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (1501,9,'orizehavi','The Nightcrawler White House infiltration scene alone makes this a masterpiece.',NULL); # 1501 1X2 1963	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (3591,9,'orizehavi','A brutal and iconic rise-and-fall story of the American dream gone completely wrong.',NULL); # 3591 A&E Biography: Al Capone - Scarface 1987	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (5929,8,'orizehavi','The mountain climbing and brutal winter survival elements make this action movie incredibly tense from the first scene.',NULL); # 5929 Action Heroes of the Cliffhanger Serials 1992	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (9023,8,'orizehavi','A great 90s political action thriller. The confined space of the plane makes for great tension.',NULL); # 9023 Air Force One 1997	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (9125,9,'orizehavi','The ultimate parody movie. The rapid-fire visual gags and deadpan delivery are unmatched.',NULL); # 9125 Airplane! 1980	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (11022,9,'orizehavi','A harrowing true story of extreme mountain survival. The sheer willpower required in those freezing conditions is unimaginable.',NULL); # 11022 Alive 1993	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (11540,8,'orizehavi','Fascinating look at the early aerospace programs and the psychological profiles required to push human limits.',NULL); # 11540 All the Right Stuff 1997	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (12231,9,'orizehavi','The ultimate chaotic Christmas movie. The booby traps sequence is cinematic perfection.',NULL); # 12231 Almost Home Alone 1993	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (12937,9,'orizehavi','A brilliant and highly engaging biographical drama focusing on musical genius and jealousy.',NULL); # 12937 Amadeus 1984	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (14033,9,'orizehavi','A brilliant mob movie focusing on loyalty, undercover work, and the psychological toll of betrayal.',NULL); # 14033 American Justice: Donnie Brasco 2000	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (17047,8,'orizehavi','The snowy landscapes and prehistoric survival elements make this a very cozy and funny family film.',NULL); # 17047 Angst and the Ice Age 1998	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (18441,7,'orizehavi','An interesting, slightly darker take on animated insect societies and collective action.',NULL); # 18441 Antz 1998	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (18544,8,'orizehavi','Incredible pacing and editing. A masterful, intense look at the business of modern sports.',NULL); # 18544 Any Given Sunday 1999	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (18979,9,'orizehavi','A brilliant space survival drama showcasing incredible problem-solving and engineering under extreme pressure.',NULL); # 18979 Apollo 13 1995	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (20368,7,'orizehavi','The drilling logistics and orbital mechanics are complete nonsense, but the action is undeniably entertaining.',NULL); # 20368 Armageddon 1923	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (20754,9,'orizehavi','A beautiful, intelligent sci-fi film focused on linguistics and communication.',NULL); # 20754 Arrival 1957	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (21553,10,'orizehavi','A perfect blend of fantasy, romance, and comedy. Highly quotable and timeless.',NULL); # 21553 As You Wish: The Story of 'The Princess Bride' 2001	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (24430,8,'orizehavi','A perfect satire of the spy genre. The cultural clashes and villains are hilarious.',NULL); # 24430 Austin Powers: International Man of Mystery 1997	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (24977,9,'orizehavi','Redefined the modern blockbuster. The team dynamics and final battle in New York are spectacular.',NULL); # 24977 Avenging the Avengers 2000	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (27167,8,'orizehavi','A highly chaotic and fun buddy-cop dynamic that set the standard for modern action aesthetics.',NULL); # 27167 Bad Boys 1983	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (30955,8,'orizehavi','The Burton gothic aesthetic is perfect. A beautifully dark take on the caped crusader.',NULL); # 30955 Batman 1989	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (30967,7,'orizehavi','Even darker and weirder than the first one, but the villains are highly memorable.',NULL); # 30967 Batman Returns 1992	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (32114,9,'orizehavi','A complex look at game theory, probability, and the psychological toll of genius.',NULL); # 32114 Beautiful Mind, A 2001	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (32391,8,'orizehavi','The grand finale of a decade of storytelling. The portal scene is pure cinematic joy.',NULL); # 32391 Beckett Directs Beckett: Endgame by Samuel Beckett 1992	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (33044,9,'orizehavi','Masterclass in making the audience feel the absolute isolation of being stranded. The physical transformation is crazy.',NULL); # 33044 Behind the Scenes: Cast Away 2000	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (33067,9,'orizehavi','A legendary portrayal of the ultimate bluff. The game logic and multi-layered deception are incredibly satisfying.',NULL); # 33067 Behind the Sting 1999	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (37178,9,'orizehavi','A surreal, chaotic, and incredibly quotable movie. The bowling alley scenes are iconic.',NULL); # 37178 Big Lebowski, The 1998	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (39551,10,'orizehavi','Incredible tactical accuracy and a gritty, uncompromising portrayal of elite military operations.',NULL); # 39551 Black Hawk Down 2001	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (40187,7,'orizehavi','A dark, highly stylized, and violent vampire action movie that paved the way for Marvel.',NULL); # 40187 Blade 1998	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (40191,8,'orizehavi','Guillermo del Toro brought fantastic creature design and kinetic action to this vampire sequel.',NULL); # 40191 Blade II 2002	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (40199,9,'orizehavi','The atmosphere and visuals defined the cyberpunk aesthetic for decades. A moody, philosophical masterpiece.',NULL); # 40199 Blade Runner 1982	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (40226,7,'orizehavi','Pioneered the found-footage genre. The marketing and raw aesthetic were revolutionary.',NULL); # 40226 Blair Witch Project, The 1999	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (41739,7,'orizehavi','A gritty look at the illegal side of college basketball recruitment and fixing games.',NULL); # 41739 Blue Chips 1994	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (42982,8,'orizehavi','A raw look at aggressive sales tactics and the ethical lines crossed in wealth management.',NULL); # 42982 Boiler Room 1992	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (46168,9,'orizehavi','An epic historical drama with massive, visceral battle sequences and a great story of rebellion.',NULL); # 46168 Braveheart 1925	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (46877,8,'orizehavi','A sharp and funny look at relationships and self-improvement. The diary format works perfectly.',NULL); # 46877 Bridget Jones's Diary 2001	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (48792,9,'orizehavi','Mind-bending psychological thriller. The twist is legendary and completely changes how you view the film on rewatch.',NULL); # 48792 Buena Vista Fight Club 2000	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (50760,10,'orizehavi','A perfect, emotionally satisfying conclusion to the greatest cinematic trilogy of all time.',NULL); # 50760 Buttsizer 3: Return of the King of Rears 1995	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (56304,9,'orizehavi','A brilliant, chaotic look at the micromanagement and inevitable downfall of a massive casino empire.',NULL); # 56304 Casino 1995	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (58250,10,'orizehavi','Iconic dialogues, unforgettable non-linear storytelling, and a soundtrack that perfectly matches the vibe.',NULL); # 58250 Cesk Pulp Fiction a Blair Witch 2000	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (59470,8,'orizehavi','A classic story of discipline, training, and the pure drive required for long-distance running.',NULL); # 59470 Chariots of Fire 1981	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (61291,8,'orizehavi','A brilliant stop-motion homage to classic prison escape movies. Highly creative and funny.',NULL); # 61291 Chicken Run 2000	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (64018,7,'orizehavi','Solid poker movie. The final hands are well constructed even if the drama is a bit heavy.',NULL); # 64018 Cincinnati Kid Plays According to Hoyle, The 1965	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (65501,8,'orizehavi','A sharp intelligence thriller focusing on cartel operations, political strategy, and covert deployment.',NULL); # 65501 Clear and Present Danger 1994	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (66286,8,'orizehavi','Great focus on discipline and accountability on the basketball court.',NULL); # 66286 Coach Carter 2005	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (68940,8,'orizehavi','Completely absurd premise executed with maximum 90s action chaos. Extremely fun.',NULL); # 68940 Con Air 1997	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (69892,8,'orizehavi','A deeply philosophical and scientifically grounded approach to first contact with aliens.',NULL); # 69892 Contact 1975	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (70415,8,'orizehavi','The ultimate feel-good underdog winter sports movie. Endlessly rewatchable.',NULL); # 70415 Cool Runnings 1993	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (72823,9,'orizehavi','A brilliant parody of classic fairytales. The humor is layered perfectly for both kids and adults.',NULL); # 72823 Creating a Fairy Tale World: The Making of 'Shrek' 2001	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (73436,9,'orizehavi','A brilliant tension-filled examination of chain of command and high-stakes decision making on a nuclear submarine.',NULL); # 73436 Crimson Tide 1995	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (73913,7,'orizehavi','A very grounded look at casino floor operations, dealer statistics, and the cold reality of gambling.',NULL); # 73913 Croupier 1998	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (78530,7,'orizehavi','Great logistics surrounding geological data collection and extreme weather evacuation procedures.',NULL); # 78530 Dante's Peak 1997	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (78993,8,'orizehavi','A gripping financial drama looking into corporate accountability and legal battles.',NULL); # 78993 Dark Waters 1944	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (80583,9,'orizehavi','A deeply inspiring drama about education, poetry, and challenging the status quo.',NULL); # 80583 Dead Poets Society 1989	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (81650,9,'orizehavi','The concepts of predictive analytics and complex data visualization here were years ahead of their time.',NULL); # 81650 Deconstructing Minority Report: Precog Visions 2002	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (83145,8,'orizehavi','Blue Steel! A hilarious, absurd, and highly quotable satire of the male modeling industry.',NULL); # 83145 Derek Zoolander University 1997	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (86274,10,'orizehavi','The ultimate action movie. The claustrophobic setting and tactical improvisation are perfect.',NULL); # 86274 Die Hard 1988	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (86279,7,'orizehavi','A solid airport-based tactical action film, even if it feels a bit repetitive compared to the first.',NULL); # 86279 Die Hard 2 1990	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (95255,8,'orizehavi','Masterful use of sound and tension to convey the stress of survival and evacuation.',NULL); # 95255 Dunkirk 1958	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (96593,9,'orizehavi','A magical and emotional sci-fi classic that defined childhood wonder in the 80s.',NULL); # 96593 E.T. the Extra-Terrestrial 1982	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (100094,9,'orizehavi','Incredibly fast-paced and witty humor. The comedic timing of the voice cast is absolute perfection.',NULL); # 100094 Emperor's New Groove 2001	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (101055,9,'orizehavi','Showcases the intense cat-and-mouse game of sniper warfare, focusing on patience, cover, and ballistics.',NULL); # 101055 Enemy at the Gates 2001	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (101455,8,'orizehavi','A great historical thriller focused on cryptography, early computing algorithms, and decoding enemy intelligence.',NULL); # 101455 Enigma 1925	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (101704,10,'orizehavi','A pioneer in sci-fi action that questioned reality and introduced bullet time. Completely changed cinema.',NULL); # 101704 Enter the Matrix 2003	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (109092,9,'orizehavi','A dark, quirky, and highly suspenseful crime thriller set in the snowy Midwest.',NULL); # 109092 Fargo 1952	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (111442,9,'orizehavi','The best fourth-wall-breaking comedy of the 80s. Pure joy and teenage rebellion.',NULL); # 111442 Ferris Bueller's Day Off 1986	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (112205,8,'orizehavi','A highly colorful, weird, and imaginative sci-fi action ride.',NULL); # 112205 Fifth Element, The 1997	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (113504,9,'orizehavi','Beautifully animated underwater world with a highly touching and relatable story about parenthood.',NULL); # 113504 Finding Nemo 2003	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (114067,8,'orizehavi','A surprisingly deep and tragic story about a traumatized veteran, before the franchise became pure action.',NULL); # 114067 First Blood 1982	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (117874,9,'orizehavi','Running across the country for no reason is an absolute vibe. An incredible journey through modern history.',NULL); # 117874 Forrest Gump 1994	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (118393,8,'orizehavi','A very funny and slightly dark romantic comedy with an unforgettable wedding sequence.',NULL); # 118393 Four Weddings and a Funeral 1994	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (121538,9,'orizehavi','The boot camp segment is terrifying, unforgettable, and a masterclass in psychological breakdown.',NULL); # 121538 Full Metal Jacket 1987	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (122657,8,'orizehavi','A brutal and inspiring look at the extreme physical and mental demands of special forces training.',NULL); # 122657 G.I. Jane 1951	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (126693,10,'orizehavi','The definitive mob movie. The pacing is absolutely flawless and the voiceover work is legendary.',NULL); # 126693 Getting Made: The Making of 'GoodFellas' 2004	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (128100,8,'orizehavi','A fantastic action thriller based on a classic TV show. The manhunt logistics are fascinating.',NULL); # 128100 Girl and the Fugitive, The 1910	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (129369,9,'orizehavi','An intense masterclass in high-pressure sales and the brutal reality of real estate management.',NULL); # 129369 Glengarry Glen Ross 1992	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (129591,8,'orizehavi','Great historical basketball drama focusing on integration and overcoming severe prejudice.',NULL); # 129591 Glory Road 2005	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (130945,9,'orizehavi','Brought Bond into the modern era. The opening facility infiltration is incredible.',NULL); # 130945 GoldenEye 1997	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (131665,9,'orizehavi','The math and intellect here are portrayed perfectly. A brilliant, emotionally charged script.',NULL); # 131665 Good Will Hunting 1997	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (134193,8,'orizehavi','A brilliant mix of horror and comedy. The practical creature designs are incredibly creative.',NULL); # 134193 Gremlins 1984	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (134672,9,'orizehavi','An incredibly smart and unconventional romance that plays heavily on the time-loop concept.',NULL); # 134672 Groundhog Day 1993	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (138797,8,'orizehavi','A great mix of sports parody and pure slapstick humor. Endlessly rewatchable.',NULL); # 138797 Happy Gilmore 1996	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (139650,8,'orizehavi','A darker mystery than the first, with great world-building and practical creature effects.',NULL); # 139650 Harry Potter and the Chamber of Secrets 2002	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (139655,9,'orizehavi','Alfonso Cuarֳ³n brought a much needed dark, mature tone to the series. The time travel mechanics are great.',NULL); # 139655 Harry Potter and the Prisoner of Azkaban 2004	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (139657,8,'orizehavi','A magical and deeply nostalgic introduction to a massive cinematic universe.',NULL); # 139657 Harry Potter and the Sorcerer's Stone 2001	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (140783,8,'orizehavi','A deeply personal look at the pressures of high school basketball recruitment and family expectations.',NULL); # 140783 He Got Game 1998	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (143524,8,'orizehavi','Very funny, energetic, and features a perfectly sassy, memorable villain.',NULL); # 143524 Hercules 1964	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (147545,9,'orizehavi','Non-linear storytelling at its absolute finest. Forces the audience to experience the protagonist''s confusion.',NULL); # 147545 Holiday Memento, A 2002	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (149156,8,'orizehavi','Fascinating deep dive into risk management, corporate law, and the ethical compromises required to survive.',NULL); # 149156 Honor of the Firm, The 1912	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (149388,9,'orizehavi','The quintessential underdog basketball story. Great focus on fundamentals, discipline, and team play.',NULL); # 149388 Hoosiers 1986	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (156295,10,'orizehavi','The ultimate Spaghetti Western. The standoff scenes and the musical score are legendary.',NULL); # 156295 Il Maestro: Ennio Morricone and 'The Good, the Bad and the Ugly' 2004	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (158996,9,'orizehavi','The gold standard for alien invasion movies. Huge scale, great tension, and iconic speeches.',NULL); # 158996 Independence Day 1975	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (166917,8,'orizehavi','Show me the money! A classic look at sports management, agents, and contract negotiations.',NULL); # 166917 Jerry Maguire 1996	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (176711,9,'orizehavi','Amazing fight choreography and incredibly stylish action sequences. Pure visual entertainment.',NULL); # 176711 Kill Bill: Vol. 1 2003	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (188507,8,'orizehavi','The blueprint for the buddy-cop action genre. Great chemistry and explosive sequences.',NULL); # 188507 Lethal Weapon 1987	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (188509,8,'orizehavi','A fantastic action sequel that amps up the stakes and deepens the bond between the lead detectives.',NULL); # 188509 Lethal Weapon 2 1989	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (189233,9,'orizehavi','A brilliant premise executed flawlessly. The boardroom scenes are comedic gold.',NULL); # 189233 Liar Liar 1997	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (194497,10,'orizehavi','The definitive fantasy epic. The world-building and attention to detail in Middle Earth are unmatched.',NULL); # 194497 Lord of the Rings: The Fellowship of the Ring, The 2001	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (194502,10,'orizehavi','The Battle of Helm''s Deep remains the greatest large-scale combat sequence ever put on film.',NULL); # 194502 Lord of the Rings: The Two Towers, The 2002	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (194511,7,'orizehavi','Fascinating breakdown of the legal and ethical gray areas in the arms trade business.',NULL); # 194511 Lord of War 2005	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (194529,8,'orizehavi','A fantastic and gritty look at the origins of extreme skate and surf culture.',NULL); # 194529 Lords of Dogtown 2005	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (195300,9,'orizehavi','One of the best holiday rom-coms ever made. The multiple interwoven storylines are managed brilliantly.',NULL); # 195300 Love Actually 2003	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (199211,9,'orizehavi','Incredible practical effects and non-stop vehicular action in a dystopian desert.',NULL); # 199211 Mad Max: Fury Road 2005	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (201789,9,'orizehavi','Goonies never say die! The absolute perfect kids treasure-hunting adventure movie.',NULL); # 201789 Making of 'The Goonies', The 1985	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (201791,9,'orizehavi','Incredibly emotional and beautifully animated. The relationship between the boy and the machine is perfect.',NULL); # 201791 Making of 'The Iron Giant', The 1999	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (201792,8,'orizehavi','A masterclass in logistical planning and executing a complex heist with precise data and timing.',NULL); # 201792 Making of 'The Italian Job', The 2003	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (201794,10,'orizehavi','The animation, the legendary soundtrack, and the Shakespearean story represent absolute peak Disney.',NULL); # 201794 Making of 'The Lion King', The 1994	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (201822,9,'orizehavi','A timeless classic that revolutionized 3D animation and delivered a perfectly written buddy comedy.',NULL); # 201822 Making of 'Toy Story', The 1995	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (207390,8,'orizehavi','A masterclass in naval combat tactics and the sheer grit required to manage a crew in open waters.',NULL); # 207390 Master and Commander: The Far Side of the World 2003	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (207989,7,'orizehavi','The highway chase scene is a logistical masterpiece of practical and digital effects.',NULL); # 207989 Matrix Reloaded, The 2003	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (208245,8,'orizehavi','The final poker tournament scenes are brilliant. A great mix of calculating odds and reading the opponents.',NULL); # 208245 Maverick 1994	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (209133,9,'orizehavi','One of the smartest high school comedies ever written. The social dynamics are spot on.',NULL); # 209133 Mean Girls 2004	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (209657,8,'orizehavi','Awkward family dynamics turned up to the maximum. The lie detector scene is legendary.',NULL); # 209657 Meet the Parents 1992	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (214946,9,'orizehavi','A deeply emotional adaptation of a Stephen King novel with fantastic character work and tension.',NULL); # 214946 Miracle of 'The Green Mile', The 1999	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (215346,9,'orizehavi','A terrifying, claustrophobic psychological thriller about obsession and toxic fandom.',NULL); # 215346 Misery 1990	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (218415,9,'orizehavi','So creative and heartwarming. The concept of harvesting screams is brilliant.',NULL); # 218415 Monsters, Inc. 2001	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (218599,10,'orizehavi','Absolute comedy perfection. The absurd situations and dialogue have never been matched.',NULL); # 218599 Monty Python and the Holy Grail 1975	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (221259,9,'orizehavi','A masterpiece of voice acting and physical comedy disguised as a family movie.',NULL); # 221259 Mrs. Doubtfire 1993	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (222112,9,'orizehavi','Let''s get down to business! The songs are absolute bangers and the story is highly inspiring.',NULL); # 222112 Mulan 1998	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (226936,8,'orizehavi','Leslie Nielsen is a genius. A masterclass in slapstick comedy and background jokes.',NULL); # 226936 Naked Gun 1956	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (235617,10,'orizehavi','The greatest plot twist in cinematic history. The interrogation room scenes are masterful.',NULL); # 235617 Nothing Is What It Seems: The Making of 'The Usual Suspects' 1998	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (235790,8,'orizehavi','The British humor balances the romance perfectly. A very feel-good and well-written movie.',NULL); # 235790 Notting Hill 1999	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (238694,8,'orizehavi','A sharp satirical look at corporate culture, office politics, and sheer managerial incompetence.',NULL); # 238694 Office Space 1991	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (238977,8,'orizehavi','The ultimate 90s rom-com. The dynamic between the leads is completely charming and timeless.',NULL); # 238977 Oh! Pretty Woman 1991	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (245007,8,'orizehavi','A hilarious, classic 90s comedy about the vibe and chaos of snowboard culture.',NULL); # 245007 Out Cold 1989	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (245275,8,'orizehavi','A tense look at managing a bio-crisis, viral containment protocols, and rapid emergency response.',NULL); # 245275 Outbreak 1995	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (248706,9,'orizehavi','Masterful storytelling about class divide, with incredible pacing and tension.',NULL); # 248706 Parasite 1982	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (254943,7,'orizehavi','Extremely tense and dark. Shows the extreme obsession with finding patterns in raw data.',NULL); # 254943 Pi 1998	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (256341,8,'orizehavi','Darker than most Disney movies, a classic morality tale with beautiful animation.',NULL); # 256341 Pinocchio 1911	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (256627,9,'orizehavi','Brilliant portrayal of the early tech industry rivalry. The strategy and negotiations are incredibly engaging.',NULL); # 256627 Pirates of Silicon Valley 1999	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (257459,9,'orizehavi','A brutal and realistic look at the Vietnam war through the eyes of a young recruit. Very intense.',NULL); # 257459 Platoon 1986	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (258860,8,'orizehavi','Incredible surfing sequences and extreme sports action mixed perfectly with a highly tense bank heist plot.',NULL); # 258860 Point Break 1991	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (262645,9,'orizehavi','A masterclass in building tension. The jungle warfare and alien tracking are phenomenal.',NULL); # 262645 Predator 1987	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (262704,9,'orizehavi','Brilliant and highly emotional true story about the physical and mental toll of endurance running.',NULL); # 262704 Prefontaine 1997	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (271826,7,'orizehavi','Pure 80s action cheese. The jungle warfare tactics are completely over the top but very fun to watch.',NULL); # 271826 Rambo: First Blood Part II 1985	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (274594,8,'orizehavi','Gross-out comedy mixed with actual heart. It completely pushed the boundaries of the genre.',NULL); # 274594 Reel Comedy: Something About Mary 1998	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (275453,9,'orizehavi','A powerful true story about overcoming racial divides through the discipline of high school football.',NULL); # 275453 Remember the Titans 2000	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (276217,9,'orizehavi','A masterclass in building tension through dialogue. A fantastic independent crime thriller.',NULL); # 276217 Reservoir Dogs 1992	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (279841,7,'orizehavi','Violent, satirical, and strangely thought-provoking commentary on corporate greed.',NULL); # 279841 RoboCop 1987	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (280269,8,'orizehavi','A classic boxing story emphasizing sheer willpower, endurance, and going the distance.',NULL); # 280269 Rocky 1948	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (280281,7,'orizehavi','A solid sequel that continues the underdog story, though it lacks the raw grit of the original.',NULL); # 280281 Rocky II 1979	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (280282,7,'orizehavi','The introduction of Mr. T as Clubber Lang brings fantastic energy to the boxing franchise.',NULL); # 280282 Rocky III 1982	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (280478,7,'orizehavi','A raw depiction of extreme financial risk-taking and the systems failures that lead to massive market collapses.',NULL); # 280478 Rogue Trader 1999	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (281334,8,'orizehavi','Great execution of covert operations tradecraft. The ambushes and vehicle extractions are incredibly realistic.',NULL); # 281334 Ronin 1998	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (282452,10,'orizehavi','The absolute best cinematic representation of Texas Hold em and calculating odds under pressure.',NULL); # 282452 Rounders 1998	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (283712,8,'orizehavi','The buddy-cop dynamic is flawless. Fast-paced, action-packed, and very funny.',NULL); # 283712 Rush Hour 1998	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (291221,8,'orizehavi','A brilliant meta-commentary on the slasher genre. It completely revitalized horror in the 90s.',NULL); # 291221 Scream 1996	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (291874,9,'orizehavi','Denzel Washington delivers a powerhouse performance as a corrupt, manipulative narcotics detective.',NULL); # 291874 Seamen Training Day 2002	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (292035,9,'orizehavi','An excellent political thriller disguised as a superhero movie. The hand-to-hand combat choreography is top tier.',NULL); # 292035 Seasoned Veteran: Journey of a Winter Soldier 2002	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (300230,10,'orizehavi','The rare comedy sequel that is actually funnier and more expansive than the original.',NULL); # 300230 Shrek 2 2004	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (300827,9,'orizehavi','A gripping and extremely tense thriller regarding cartel violence and moral ambiguity.',NULL); # 300827 Sicario 1994	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (301391,8,'orizehavi','Masterful slow-burn tension. The alien invasion is handled in a very intimate, claustrophobic way.',NULL); # 301391 Signs 2002	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (304829,8,'orizehavi','A highly nostalgic romantic comedy. The radio talk show concept works perfectly to build the tension.',NULL); # 304829 Sleepless in Seattle 1993	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (306051,8,'orizehavi','A smart, tech-driven heist movie focusing on cryptography, data security, and social engineering.',NULL); # 306051 Sneakers 1992	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (310130,9,'orizehavi','A highly entertaining blend of live-action and animation. Pure 90s basketball nostalgia.',NULL); # 310130 Space Jam 1996	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (310184,8,'orizehavi','May the Schwartz be with you! A hilarious and highly nostalgic sci-fi parody.',NULL); # 310184 Spaceballs 1987	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (310718,9,'orizehavi','A highly stressful and fast-paced premise. The logistics of the bus situation are gripping.',NULL); # 310718 Speed 1917	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (311037,8,'orizehavi','The definitive and classic modern superhero origin story that started the craze.',NULL); # 311037 Spider-Man 2002	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (311038,9,'orizehavi','Incredible villain arc with Doc Ock. One of the best comic book sequels ever made.',NULL); # 311038 Spider-Man 2 2004	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (313059,9,'orizehavi','A beautiful and nostalgic coming-of-age story based on Stephen King. The chemistry is fantastic.',NULL); # 313059 Stand by Me 1986	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (313600,7,'orizehavi','A solid foundational sci-fi adventure that launched an entire television universe.',NULL); # 313600 Stargate 1981	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (314597,8,'orizehavi','Great showcase of the ruthless strategic decisions needed in early tech scaling.',NULL); # 314597 Steve Jobs & ODI 1993	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (325096,8,'orizehavi','An absolutely amazing and iconic drum-heavy soundtrack by Phil Collins.',NULL); # 325096 Tarzan 1984	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (326243,8,'orizehavi','Excellent! A classic 90s comedy that captured the rock and roll public access TV vibe perfectly.',NULL); # 326243 Taylor Wayne's World 1992	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (331427,8,'orizehavi','A gritty look at the chaos and moral ambiguity of modern warfare and the pursuit of gold in a combat zone.',NULL); # 331427 Three Kings 1999	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (333849,9,'orizehavi','An incredible feat of filmmaking. The scale of the disaster and the practical effects remain stunning.',NULL); # 333849 Titanic 1915	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (335245,8,'orizehavi','A strategic Western shootout movie. The positioning and pacing of the gunfights are iconic.',NULL); # 335245 Tombstone 1993	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (335834,9,'orizehavi','The pure adrenaline and tactical maneuvering in the aerial dogfights make this a timeless military classic.',NULL); # 335834 Top Gun 1955	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (337168,9,'orizehavi','A rare sequel that expands the universe and hits right in the feels.',NULL); # 337168 Toy Story 2 1999	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (337830,9,'orizehavi','A kinetic and wildly energetic dive into addiction. Visually striking and highly memorable.',NULL); # 337830 Trainspotting 1996	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (340799,8,'orizehavi','A highly entertaining mix of action and comedy. The practical stunts are top notch.',NULL); # 340799 True Lies 1994	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (345690,8,'orizehavi','A brilliant and highly grounded, realistic take on the superhero origin story genre.',NULL); # 345690 Unbreakable 2000	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (346949,9,'orizehavi','A brilliant deconstruction of the Western myth. Beautifully shot and highly dramatic.',NULL); # 346949 Unforgiven 1992	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (348339,9,'orizehavi','A highly realistic and stressful look at corporate downsizing and management on the road.',NULL); # 348339 Up in the Air 1918	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (360100,6,'orizehavi','An ambitious post-apocalyptic concept focusing on oceanic survival, though the execution gets a bit messy.',NULL); # 360100 Waterworld 1995	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (360480,9,'orizehavi','A visceral look at battlefield leadership and the immense burden of commanding a frontline unit under extreme fire.',NULL); # 360480 We Were Soldiers 2002	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (362808,9,'orizehavi','Brilliant dialogue and pacing. A fantastic exploration of modern relationships and comedic timing.',NULL); # 362808 When Harry Met Sally... 1989	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (363599,10,'orizehavi','An intense and exhausting exploration of perfectionism and abusive mentorship.',NULL); # 363599 Whiplash 1948	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (363927,8,'orizehavi','Great court hustle and street basketball dynamics. The trash talk and psychological games are legendary.',NULL); # 363927 White Men Can't Jump 1992	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (369458,8,'orizehavi','Introduced a grounded, serious tone to ensemble superhero movies. Great casting.',NULL); # 369458 X-Men 2000	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (370017,8,'orizehavi','High-octane extreme sports mixed with espionage. The stunts and snowboarding sequences are ridiculous but fun.',NULL); # 370017 XXX 2002	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (372372,7,'orizehavi','A great mix of early internet culture and classic romance. Very fun and lighthearted.',NULL); # 372372 You've Got Mail 1998	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (376969,8,'orizehavi','Fascinating look at artificial intelligence and NLP. The way the AI develops conversational nuance is mind-blowing.',NULL); # 376969  la manire de Sherlock Holmes 1956	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (379168,8,'orizehavi','Incredible energy and physical acting. Defined 90s comedy single-handedly.',NULL); # 379168 Ace Ventura: Pet Detective" 1996"	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (379567,9,'orizehavi','The Robin Williams voice performance is untouchable. A masterclass in comedic timing and energy.',NULL); # 379567 Aladdin" 1975"	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (380029,7,'orizehavi','Defined an entire generation of teen comedies. A bit dated, but the blueprint is there.',NULL); # 380029 American Pie" 1989"	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (380706,9,'orizehavi','Fantastic character development. A great blend of drama, romance, and psychological barriers.',NULL); # 380706 As Good as It Gets" 2003"	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (380936,9,'orizehavi','Groundbreaking CGI and an epic soundtrack. It completely changed the way we view sci-fi world-building.',NULL); # 380936 Avatar" 2004"	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (381462,9,'orizehavi','One of the best surfing documentaries ever made. The pursuit of the perfect wave is hypnotic.',NULL); # 381462 Beach Boys: Endless Summer" 1988"	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (381512,9,'orizehavi','A tale as old as time. Visually stunning with beautiful, timeless music.',NULL); # 381512 Beauty and the Beast" 1964"	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (384442,8,'orizehavi','A brilliant, low-budget indie comedy that perfectly captures the mundane reality of retail work.',NULL); # 384442 Clerks" 2000"	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (384531,8,'orizehavi','A highly quotable and incredibly smart satire of high school life and consumer culture.',NULL); # 384531 Clueless" 1996"	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (387105,9,'orizehavi','Physical comedy at its absolute peak. Every single line is quotable and hilarious.',NULL); # 387105 Dumb and Dumber" 1995"	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (387605,8,'orizehavi','Fascinating look at surveillance, data privacy, and intelligence gathering years before it became the norm.',NULL); # 387605 Enemy of the State	 An" 1965"
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (388108,9,'orizehavi','Who you gonna call? A perfect blend of sci-fi, horror, and classic comedy.',NULL); # 388108 Extreme Ghostbusters" 1997"	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (392398,7,'orizehavi','A classic wedding sabotage plot with really fun and chaotic execution.',NULL); # 392398 I Do Diaries: My Best Friend's Wedding	 The" 2003"
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (392864,9,'orizehavi','A highly unique and emotionally devastating concept. Managing the control room of a human mind is genius.',NULL); # 392864 Inside Out" 2002"	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (395649,8,'orizehavi','A highly nostalgic, beautifully animated movie about unconventional family dynamics.',NULL); # 395649 Lilo & Stitch: The Series" 2003"	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (396041,9,'orizehavi','Greed is good. A classic and timeless look at corporate raiding, investing, and high-stakes finance.',NULL); # 396041 Louis Rukeyser's Wall Street" 2002"	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (397422,9,'orizehavi','A perfect blend of sci-fi and action-comedy. The practical effects and creature designs are great.',NULL); # 397422 Men in Black: The Series" 1997"	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (397916,8,'orizehavi','The wire-drop sequence is legendary. Redefined modern espionage and covert operations on film.',NULL); # 397916 Mission: Impossible" 1966"	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (403812,9,'orizehavi','Would you like to know more? A brilliant, bloody, and highly misunderstood political satire.',NULL); # 403812 Roughnecks: The Starship Troopers Chronicles" 1999"	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (406273,8,'orizehavi','Exceptional spy thriller that highlights the complexity of extraction operations and intelligence analysis.',NULL); # 406273 Spy Game" 1997"	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (407314,8,'orizehavi','Incredibly creepy and atmospheric. The visual style influenced a decade of horror films.',NULL); # 407314 T-Bag and the Rings of Olympus" 1989"	
INSERT IGNORE INTO  personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (408609,8,'orizehavi','Mind-bending action classic. The practical effects are grotesque but highly creative.',NULL); # 408609 Total Recall 2070" 1999"	
