insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (267038, 131780, 10, 'Liam', 'Both are Scorsese-adjacent crime films with sharp dialogue and morally complex characters', null);  # Pulp Fiction -> Goodfellas
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (131780, 267038, 10, 'Liam', 'Both dissect organized crime through stylized storytelling and iconic ensemble casts', null);  # Goodfellas -> Pulp Fiction
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (267038, 276217, 9, 'Liam', 'Same director, same sharp dialogue-driven tension with a criminal setting', null);  # Pulp Fiction -> Reservoir Dogs
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (276217, 176711, 9, 'Liam', 'Both are Tarantino films built on slow-burn tension that explodes into violence', null);  # Reservoir Dogs -> Kill Bill Vol 1
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (291698, 267038, 9, 'Liam', 'Both are dark thrillers with shocking twists and morally driven detectives', null);  # Se7en -> Pulp Fiction
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (56304, 131780, 9, 'Liam', 'Both are Scorsese crime epics with De Niro and Pesci at their peak', null);  # Casino -> Goodfellas
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (289558, 131780, 9, 'Liam', 'Both follow the rise and fall of a powerful criminal figure with operatic intensity', null);  # Scarface -> Goodfellas
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (141544, 56304, 9, 'Liam', 'Both are Scorsese-style crime films where two elite figures face off in a tense game', null);  # Heat -> Casino
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (130128, 131780, 10, 'Liam', 'Both are definitive crime epics that redefined the gangster genre', null);  # Godfather -> Goodfellas
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (337814, 291698, 9, 'Liam', 'Both are dark cop thrillers where the line between hero and villain blurs completely', null);  # Training Day -> Se7en
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (45128, 45129, 10, 'Liam', 'Direct sequel with even stronger action and a more desperate Bourne on the run', null);  # Bourne Identity -> Bourne Supremacy
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (45129, 215880, 8, 'Liam', 'Both are grounded spy thrillers that trade gadgets for raw physicality and stakes', null);  # Bourne Supremacy -> MI3
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (92573, 130953, 10, 'Liam', 'Both are classic Connery Bond films that defined the spy genre', null);  # Dr No -> Goldfinger
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (130953, 120574, 9, 'Liam', 'Both are top-tier Connery Bond entries with iconic action and cold war tension', null);  # Goldfinger -> From Russia with Love
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (120574, 332065, 9, 'Liam', 'Both are early Connery Bond films with tight plotting and memorable set pieces', null);  # From Russia with Love -> Thunderball
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (86274, 310726, 9, 'Liam', 'Both are high-stakes action films built entirely around a single location and ticking clock', null);  # Die Hard -> Speed
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (109421, 1529, 9, 'Liam', 'Direct sequel in the same franchise with the same street racing energy', null);  # Fast and Furious -> 2 Fast 2 Furious
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (238072, 163715, 10, 'Liam', 'Both are slick ensemble heist films where the plan and the team are equally enjoyable', null);  # Oceans Eleven -> Italian Job
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (335835, 39551, 8, 'Liam', 'Both are intense military action films that put duty and brotherhood at the center', null);  # Top Gun -> Black Hawk Down
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (40187, 310726, 8, 'Liam', 'Both are high-energy 90s action films with a cool protagonist against impossible odds', null);  # Blade -> Speed
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (275453, 66286, 10, 'Liam', 'Both are inspirational sports films where a coach transforms a divided team into champions', null);  # Remember the Titans -> Coach Carter
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (66286, 280270, 9, 'Liam', 'Both follow an underdog who overcomes the odds through discipline and belief', null);  # Coach Carter -> Rocky
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (280270, 280284, 9, 'Liam', 'Both Rocky entries follow the same underdog spirit with increasingly epic training sequences', null);  # Rocky -> Rocky IV
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (166917, 131665, 9, 'Liam', 'Both are emotional character studies about a man rediscovering what truly matters in life', null);  # Jerry Maguire -> Good Will Hunting
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (18979, 289109, 9, 'Liam', 'Both are true-story survival films where teamwork and leadership determine life or death', null);  # Apollo 13 -> Saving Private Ryan
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (32114, 131665, 9, 'Liam', 'Both center on a brilliant but troubled man who needs human connection to heal', null);  # Beautiful Mind -> Good Will Hunting
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (173933, 275453, 9, 'Liam', 'Both are feel-good films about a mentor who transforms a young person through discipline', null);  # Karate Kid -> Remember the Titans
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (80583, 131665, 10, 'Liam', 'Both are about an unconventional mentor who unlocks a student potential through real connection', null);  # Dead Poets Society -> Good Will Hunting
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (254986, 289109, 9, 'Liam', 'Both are devastating war-era films that document survival with quiet, restrained power', null);  # The Pianist -> Saving Private Ryan
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (46169, 129185, 9, 'Liam', 'Both are epic historical action films with a lone warrior fighting against impossible odds', null);  # Braveheart -> Gladiator
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (397121, 210511, 10, 'Liam', 'Both are mind-bending films that question the nature of reality with cerebral storytelling', null);  # Matrix -> Memento
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (210511, 90772, 9, 'Liam', 'Both are psychological films that withhold key information and reward patient viewers', null);  # Memento -> Donnie Darko
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (90772, 50639, 8, 'Liam', 'Both are dark sci-fi films that use time as a source of dread and confusion', null);  # Donnie Darko -> Butterfly Effect
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (40199, 397121, 9, 'Liam', 'Both are dystopian sci-fi films that ask what it means to be human in a machine world', null);  # Blade Runner -> Matrix
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (336458, 397121, 8, 'Liam', 'Both are mind-bending action sci-fi films where reality is not what it seems', null);  # Total Recall -> Matrix
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (155070, 397121, 8, 'Liam', 'Both are sci-fi action films starring a lone hero who questions the system around him', null);  # I Robot -> Matrix
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (9125, 226939, 10, 'Liam', 'Both are deadpan parody comedies that commit fully to absurdist humor', null);  # Airplane -> Naked Gun
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (226939, 289666, 8, 'Liam', 'Both are self-aware comedies that mock genre conventions with consistent energy', null);  # Naked Gun -> Scary Movie
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (16006, 375827, 9, 'Liam', 'Both are Will Ferrell and Ben Stiller era comedies built on one committed absurd premise', null);  # Anchorman -> Zoolander
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (138797, 2709, 8, 'Liam', 'Both are Adam Sandler comedies that mix slapstick with unexpected emotional warmth', null);  # Happy Gilmore -> 50 First Dates
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (111813, 969, 9, 'Liam', 'Both are dialogue-driven films set in a single room where the spoken word is the action', null);  # Few Good Men -> 12 Angry Men
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (337166, 113504, 10, 'Liam', 'Both are Pixar masterpieces with emotional depth that works for every age', null);  # Toy Story -> Finding Nemo
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (113504, 158927, 9, 'Liam', 'Both are Pixar films where love and family are tested under extreme circumstances', null);  # Finding Nemo -> Incredibles
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (191246, 337166, 10, 'Liam', 'Both are animated classics that combine stunning visuals with timeless emotional storytelling', null);  # Lion King -> Toy Story
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (218415, 272644, 9, 'Liam', 'Both are Pixar films with an unlikely protagonist who defies expectations in their world', null);  # Monsters Inc -> Ratatouille
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (155213, 300229, 8, 'Liam', 'Both are animated comedies with a comedic trio dynamic that carries the whole film', null);  # Ice Age -> Shrek
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (300229, 300230, 9, 'Liam', 'Direct sequel that expands the world while keeping the same comedic charm', null);  # Shrek -> Shrek 2
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (337166, 337168, 9, 'Liam', 'Both Toy Story films follow the same characters with genuine emotional continuity', null);  # Toy Story -> Toy Story 2
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (297838, 134077, 10, 'Liam', 'Both are emotionally devastating prison dramas adapted from Stephen King with Frank Darabont directing', null);  # Shawshank -> Green Mile
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (289109, 39551, 9, 'Liam', 'Both are Spielberg-produced war films that capture combat with brutal realism', null);  # Saving Private Ryan -> Black Hawk Down
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (121538, 289109, 9, 'Liam', 'Both use war as a lens for examining the psychological cost paid by ordinary men', null);  # Full Metal Jacket -> Saving Private Ryan
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (18960, 121538, 9, 'Liam', 'Both are anti-war masterpieces that portray the moral disintegration caused by combat', null);  # Apocalypse Now -> Full Metal Jacket
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (117874, 297838, 10, 'Liam', 'Both are emotionally rich American dramas built around a performance of extraordinary warmth', null);  # Forrest Gump -> Shawshank
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (34077, 117874, 8, 'Liam', 'Both follow a protagonist through decades of American history with emotional sweep', null);  # Benjamin Button -> Forrest Gump
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (301540, 291698, 10, 'Liam', 'Both are dark psychological thrillers where a brilliant investigator faces a terrifying mind', null);  # Silence of the Lambs -> Se7en
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (112290, 14145, 9, 'Liam', 'Both are psychological dramas with unreliable narrators that critique modern masculinity', null);  # Fight Club -> American Psycho
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (340901, 210511, 9, 'Liam', 'Both are films built around a singular mind-bending premise that reframes everything at the end', null);  # Truman Show -> Memento
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (323813, 238072, 8, 'Liam', 'Both follow a charming and manipulative protagonist who deceives everyone around him', null);  # Talented Mr Ripley -> Oceans Eleven
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (160524, 210511, 8, 'Liam', 'Both are Nolan psychological thrillers where perception and memory cannot be trusted', null);  # Insomnia -> Memento
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (194500, 129185, 10, 'Liam', 'Both are epic films with massive battle sequences and a hero who sacrifices everything', null);  # LOTR Return of King -> Gladiator
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (194497, 194502, 10, 'Liam', 'Direct continuation of the same trilogy with seamless world and character building', null);  # LOTR Fellowship -> Two Towers
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (271095, 159172, 9, 'Liam', 'Both are Spielberg adventure films starring Harrison Ford with perfect action-comedy balance', null);  # Raiders -> Last Crusade
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (256632, 238072, 9, 'Liam', 'Both are ensemble adventure films with charismatic leads and a heist-like structure', null);  # Pirates -> Oceans Eleven
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (340652, 129185, 9, 'Liam', 'Both are sword-and-sandal epics with muscular leads and spectacular battle sequences', null);  # Troy -> Gladiator
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (63208, 194497, 8, 'Liam', 'Both are fantasy epics about a young hero entering a magical world to fight an ancient evil', null);  # Narnia -> LOTR Fellowship
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (267038, 370017, 3, 'Liam', 'Both are action-heavy films but XXX trades all narrative depth for pure spectacle', null);  # Pulp Fiction -> XXX
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (131780, 108760, 2, 'Liam', 'Both involve criminal or anti-hero figures but Fantastic Four lacks any real edge or complexity', null);  # Goodfellas -> Fantastic Four
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (297838, 276085, 3, 'Liam', 'Both are dark prison-adjacent dramas but Requiem offers no hope and is deliberately punishing', null);  # Shawshank -> Requiem for a Dream
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (129185, 2238, 3, 'Liam', 'Both are ancient warrior epics but 300 sacrifices story depth for pure visual style', null);  # Gladiator -> 300
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (45128, 215879, 3, 'Liam', 'Both are spy action films but MI2 trades coherence for John Woo slow motion excess', null);  # Bourne Identity -> MI2
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (280270, 280305, 3, 'Liam', 'Same franchise but Rocky V abandons everything that made the original emotionally resonant', null);  # Rocky -> Rocky V
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (238072, 238073, 3, 'Liam', 'Same franchise but Oceans Twelve loses the tight focus that made the original so satisfying', null);  # Oceans Eleven -> Oceans Twelve
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (397121, 218808, 2, 'Liam', 'Both involve sci-fi action but Moonraker puts Bond in space with zero dramatic tension', null);  # Matrix -> Moonraker
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (271095, 159167, 3, 'Liam', 'Same franchise but Indiana Jones 4 is a pale shadow of what made the originals great', null);  # Raiders -> Indy 4
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (176711, 370017, 2, 'Liam', 'Both feature extreme action and a cool protagonist but XXX has none of Kill Bill depth', null);  # Kill Bill -> XXX
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (112290, 276085, 3, 'Liam', 'Both are dark films that confront addiction and self-destruction but Requiem is far more punishing', null);  # Fight Club -> Requiem for a Dream
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (337166, 264158, 2, 'Liam', 'Both are feel-good films about growing up but Princess Diaries lacks Toy Story depth and creativity', null);  # Toy Story -> Princess Diaries
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (289109, 359297, 3, 'Liam', 'Both involve large-scale survival threats but War of the Worlds is far thinner on character', null);  # Saving Private Ryan -> War of the Worlds
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (301540, 291221, 3, 'Liam', 'Both are thrillers with a killer antagonist but Scream is self-aware horror rather than true dread', null);  # Silence of Lambs -> Scream
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (56871, 248878, 2, 'Liam', 'Both involve deception as a core plot device but Parent Trap is a shallow family comedy', null);  # Catch Me If You Can -> Parent Trap
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (340901, 248878, 2, 'Liam', 'Both involve a constructed false reality but Parent Trap has none of Truman Show philosophical weight', null);  # Truman Show -> Parent Trap
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (326155, 79716, 3, 'Liam', 'Both show a world in crisis threatening ordinary life but Day After Tomorrow is pure disaster spectacle', null);  # Taxi Driver -> Day After Tomorrow
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (18960, 159167, 2, 'Liam', 'Both involve military missions gone wrong but Indy 4 turns serious adventure into CGI-heavy farce', null);  # Apocalypse Now -> Indy 4
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (130128, 41849, 2, 'Liam', 'Both have strong familial tension but Blue Lagoon replaces drama with shallow romantic fantasy', null);  # Godfather -> Blue Lagoon
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (969, 209133, 3, 'Liam', 'Both are set largely in one location with social group dynamics but Mean Girls is pure teen comedy', null);  # 12 Angry Men -> Mean Girls
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313478, 313474, 3, 'Liam', 'Same universe but Episode I replaces the original trilogy gravitas with midichlorians and Jar Jar', null);  # Empire Strikes Back -> Phantom Menace
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313478, 313476, 3, 'Liam', 'Same universe but Episode II has painfully weak romance dialogue that undermines the drama', null);  # Empire Strikes Back -> Attack of the Clones
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (194500, 222339, 3, 'Liam', 'Both involve ancient supernatural threats but The Mummy is a light adventure with little real tension', null);  # LOTR Return of King -> The Mummy
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30959, 30965, 3, 'Liam', 'Same Batman franchise but Forever is campy and unfocused compared to Nolan dark vision', null);  # Batman Begins -> Batman Forever
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (311038, 108760, 2, 'Liam', 'Both are superhero films but Fantastic Four has none of Spider-Man 2 emotional depth or craft', null);  # Spider-Man 2 -> Fantastic Four
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (297838, 56373, 3, 'Liam', 'Both are set in unusual closed environments but Casper is a lightweight kids film with no real stakes', null);  # Shawshank -> Casper
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (112290, 37002, 3, 'Liam', 'Both explore what a man is willing to do for identity but Big Daddy has no depth below the surface', null);  # Fight Club -> Big Daddy
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (267038, 187191, 2, 'Liam', 'Both feature a protagonist who crafts a persona but Legally Blonde stays entirely surface-level', null);  # Pulp Fiction -> Legally Blonde
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (291698, 291221, 3, 'Liam', 'Both feature a serial killer antagonist but Scream parodies the formula Se7en perfects', null);  # Se7en -> Scream
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (289109, 158999, 3, 'Liam', 'Both involve massive combat on a grand scale but Independence Day trades realism for pure spectacle', null);  # Saving Private Ryan -> Independence Day
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (131665, 195300, 3, 'Liam', 'Both explore romantic love and human connection but Love Actually is shallow by comparison', null);  # Good Will Hunting -> Love Actually
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (46169, 222339, 3, 'Liam', 'Both involve ancient battles and quests but The Mummy lacks the emotional weight of Braveheart', null);  # Braveheart -> The Mummy
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (56871, 119358, 2, 'Liam', 'Both involve identity switching but Freaky Friday is a lightweight teen comedy with no real stakes', null);  # Catch Me If You Can -> Freaky Friday
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (340901, 119358, 2, 'Liam', 'Both involve a character living as someone else but Freaky Friday is pure family comedy with no depth', null);  # Truman Show -> Freaky Friday
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (289787, 195300, 3, 'Liam', 'Both are romantic dramas but Love Actually spreads itself too thin across too many storylines', null);  # Scent of a Woman -> Love Actually
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (254986, 41849, 2, 'Liam', 'Both are set in isolated environments but Blue Lagoon replaces historical tragedy with fantasy romance', null);  # The Pianist -> Blue Lagoon
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (297838, 248878, 2, 'Liam', 'Both involve long-term loyalty but Parent Trap is a breezy kids comedy with no emotional weight', null);  # Shawshank -> Parent Trap
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (32114, 79716, 2, 'Liam', 'Both involve a single person facing an overwhelming force but Day After Tomorrow lacks all human depth', null);  # Beautiful Mind -> Day After Tomorrow
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (80583, 187191, 3, 'Liam', 'Both feature an institution that tries to suppress an individual but Legally Blonde is too light', null);  # Dead Poets Society -> Legally Blonde
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (969, 66194, 3, 'Liam', 'Both involve a group dynamic in a confined space but Clueless swaps moral weight for teen comedy', null);  # 12 Angry Men -> Clueless
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (92573, 218808, 2, 'Liam', 'Same Bond franchise but Moonraker abandons the grounded spy formula for ridiculous space opera', null);  # Dr No -> Moonraker
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (130953, 85871, 3, 'Liam', 'Same Bond franchise but Diamonds Are Forever feels lazy and low-energy after Goldfinger', null);  # Goldfinger -> Diamonds Are Forever
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (130953, 203649, 3, 'Liam', 'Both are Bond films but Man with the Golden Gun wastes a great villain concept on a weak plot', null);  # Goldfinger -> Man with Golden Gun
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (45128, 370017, 2, 'Liam', 'Both feature a skilled protagonist taking on a criminal organization but XXX has no real depth', null);  # Bourne Identity -> XXX
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (238072, 220805, 3, 'Liam', 'Both involve elaborate deception but Mr and Mrs Smith trades heist intelligence for action comedy', null);  # Oceans Eleven -> Mr and Mrs Smith
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (191246, 264158, 2, 'Liam', 'Both involve royalty and transformation but Princess Diaries lacks Lion King emotional scope', null);  # Lion King -> Princess Diaries
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (337166, 41849, 2, 'Liam', 'Both involve friendship and survival in a new environment but Blue Lagoon has no heart or craft', null);  # Toy Story -> Blue Lagoon
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (300229, 264158, 2, 'Liam', 'Both are feel-good films with a fish-out-of-water premise but Princess Diaries lacks Shrek wit', null);  # Shrek -> Princess Diaries
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (113504, 56373, 3, 'Liam', 'Both are family films about a lonely protagonist finding belonging but Casper has little emotional pull', null);  # Finding Nemo -> Casper
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (155213, 849, 2, 'Liam', 'Both are animated sequels but 101 Dalmatians II is a direct-to-video product with no ambition', null);  # Ice Age -> 101 Dalmatians II
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (9125, 363780, 2, 'Liam', 'Both are comedies built on a single absurd premise but White Chicks runs out of ideas in minutes', null);  # Airplane -> White Chicks
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (16006, 187191, 3, 'Liam', 'Both are comedies about a character out of their depth but Legally Blonde never goes beyond the obvious', null);  # Anchorman -> Legally Blonde
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (226939, 363780, 2, 'Liam', 'Both are broad comedies but White Chicks relies on a single joke stretched impossibly thin', null);  # Naked Gun -> White Chicks
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (375827, 363780, 2, 'Liam', 'Both are committed to a single absurd disguise premise but White Chicks has none of Zoolander wit', null);  # Zoolander -> White Chicks
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (138797, 370017, 3, 'Liam', 'Both follow a rebellious protagonist proving doubters wrong but XXX lacks all of Happy Gilmore charm', null);  # Happy Gilmore -> XXX
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (254986, 79716, 2, 'Liam', 'Both involve survival against a catastrophic external threat but Day After Tomorrow is empty spectacle', null);  # The Pianist -> Day After Tomorrow
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (134077, 56373, 3, 'Liam', 'Both involve supernatural elements in a human drama but Casper lacks all emotional seriousness', null);  # Green Mile -> Casper
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (32114, 108760, 2, 'Liam', 'Both feature a protagonist with extraordinary abilities but Fantastic Four has zero character depth', null);  # Beautiful Mind -> Fantastic Four
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (131665, 37002, 3, 'Liam', 'Both involve an unlikely mentorship but Big Daddy stays entirely on the surface comedically', null);  # Good Will Hunting -> Big Daddy
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (46169, 2238, 3, 'Liam', 'Both are ancient battle films but 300 sacrifices all narrative substance for visual excess', null);  # Braveheart -> 300
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (289109, 222339, 3, 'Liam', 'Both involve a group on a dangerous mission but The Mummy turns it into lightweight entertainment', null);  # Saving Private Ryan -> The Mummy
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (291698, 108760, 2, 'Liam', 'Both involve tracking down a threat but Fantastic Four has none of Se7en relentless dread', null);  # Se7en -> Fantastic Four
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (301540, 264158, 2, 'Liam', 'Both feature a woman navigating a world that underestimates her but Princess Diaries is entirely fluffy', null);  # Silence of Lambs -> Princess Diaries
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (56304, 370017, 2, 'Liam', 'Both involve dangerous criminal worlds but XXX reduces everything to mindless action with no stakes', null);  # Casino -> XXX
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (117874, 41849, 2, 'Liam', 'Both span a long period of a character life but Blue Lagoon has none of Forrest Gump warmth', null);  # Forrest Gump -> Blue Lagoon
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (340901, 79716, 3, 'Liam', 'Both involve a world built on a lie being exposed but Day After Tomorrow has no human story', null);  # Truman Show -> Day After Tomorrow
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (80583, 209133, 3, 'Liam', 'Both are set in schools with social hierarchies but Mean Girls lacks Dead Poets intellectual depth', null);  # Dead Poets -> Mean Girls
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (326155, 363780, 2, 'Liam', 'Both involve a protagonist operating outside societal norms but White Chicks has zero artistic intent', null);  # Taxi Driver -> White Chicks
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (14145, 363780, 2, 'Liam', 'Both involve characters maintaining a false identity but White Chicks has none of American Psycho edge', null);  # American Psycho -> White Chicks
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (112290, 187191, 2, 'Liam', 'Both follow a protagonist reinventing themselves but Legally Blonde has no darkness or depth to explore', null);  # Fight Club -> Legally Blonde
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (176712, 267038, 9, 'Liam', 'Both are Tarantino films where revenge is the engine driving a stylized non-linear narrative', null);  # Kill Bill 2 -> Pulp Fiction
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (159665, 276217, 9, 'Liam', 'Both are Tarantino films where dialogue builds unbearable tension before violence erupts', null);  # Inglorious Bastards -> Reservoir Dogs
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (56871, 238072, 9, 'Liam', 'Both follow a charming con artist who outsmarts everyone through wit and improvisation', null);  # Catch Me If You Can -> Oceans Eleven
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (333856, 34077, 8, 'Liam', 'Both are sweeping romantic epics that follow a love story across decades with visual grandeur', null);  # Titanic -> Benjamin Button
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (299073, 301540, 9, 'Liam', 'Both are psychological horror films where an intelligent monster terrorizes from a position of control', null);  # The Shining -> Silence of the Lambs
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (65764, 14145, 9, 'Liam', 'Both are confrontational films that use extreme violence to critique modern society', null);  # Clockwork Orange -> American Psycho
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (37178, 16006, 8, 'Liam', 'Both are deadpan comedies built around a loveable idiot who refuses to take anything seriously', null);  # Big Lebowski -> Anchorman
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (223799, 111813, 9, 'Liam', 'Both are sharp courtroom comedies where an underdog lawyer outsmarts the establishment', null);  # My Cousin Vinny -> Few Good Men
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (258860, 109421, 8, 'Liam', 'Both are adrenaline-fueled action films built around fast vehicles and masculine bravado', null);  # Point Break -> Fast and Furious
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (302329, 40199, 9, 'Liam', 'Both are visually groundbreaking neo-noir films with a dark city and morally complex heroes', null);  # Sin City -> Blade Runner
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (279841, 14145, 8, 'Liam', 'Both use dark satire to expose the violence lurking beneath civilized corporate structures', null);  # Robocop -> American Psycho
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (10830, 301540, 9, 'Liam', 'Both are films where a terrifying creature hunts in a confined space with relentless dread', null);  # Alien -> Silence of the Lambs
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (148200, 312150, 8, 'Liam', 'Both are family action comedies where a kid outsmarts dangerous adults with resourcefulness', null);  # Home Alone -> Spy Kids
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (26844, 26846, 9, 'Liam', 'Direct sequel with clever time-within-time storytelling that expands on the original', null);  # Back to the Future -> Back to the Future 2
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (26846, 26847, 8, 'Liam', 'Same trilogy with a fresh western setting that breathes new life into the time travel concept', null);  # Back to the Future 2 -> Back to the Future 3
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (289558, 56304, 10, 'Liam', 'Both are crime epics about a powerful man whose empire collapses under its own corruption', null);  # Scarface -> Casino
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (87280, 133401, 9, 'Liam', 'Both are iconic romance films built around transformative dancing and unforgettable music', null);  # Dirty Dancing -> Grease
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (207157, 375827, 8, 'Liam', 'Both are 90s comedies where the lead uses an outrageous persona to navigate a social world', null);  # The Mask -> Zoolander
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (362808, 235541, 9, 'Liam', 'Both are romantic films where the protagonists fight their feelings before an emotional resolution', null);  # When Harry Met Sally -> The Notebook
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (235541, 333856, 9, 'Liam', 'Both are sweeping love stories told across time with an emotional final act', null);  # Notebook -> Titanic
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (185628, 340652, 8, 'Liam', 'Both are epic historical films where a westerner fights in an ancient warrior culture', null);  # Last Samurai -> Troy
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (97727, 59578, 8, 'Liam', 'Both are Tim Burton films with a visually unique protagonist who struggles to fit into society', null);  # Edward Scissorhands -> Charlie and Chocolate Factory
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (270971, 280270, 9, 'Liam', 'Both are boxing films that use the ring as a lens for deeper human struggle and identity', null);  # Raging Bull -> Rocky
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (104699, 138797, 8, 'Liam', 'Both are irreverent comedies where young men cause chaos abroad with complete disregard for rules', null);  # Eurotrip -> Happy Gilmore
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (272644, 113504, 9, 'Liam', 'Both are Pixar films about an outsider with a hidden talent who finds their place in the world', null);  # Ratatouille -> Finding Nemo
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (194123, 275453, 8, 'Liam', 'Both are sports films where a ragtag team is transformed by a no-nonsense leader', null);  # Longest Yard -> Remember the Titans
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (66194, 1038, 8, 'Liam', 'Both are sharp female-led comedies about navigating social expectations with wit', null);  # Clueless -> 13 Going on 30
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (323813, 56871, 9, 'Liam', 'Both follow a brilliant con artist who constructs an elaborate false identity with charismatic ease', null);  # Talented Mr Ripley -> Catch Me If You Can
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (209591, 235541, 8, 'Liam', 'Both are romantic dramas where love is complicated by an extraordinary and bittersweet circumstance', null);  # Meet Joe Black -> The Notebook
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (155070, 112205, 8, 'Liam', 'Both are fun sci-fi action films with a charismatic lead navigating a world of intelligent machines', null);  # I Robot -> Fifth Element
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (112205, 336458, 8, 'Liam', 'Both are wild sci-fi films that throw a lone hero into a bizarre future with relentless energy', null);  # Fifth Element -> Total Recall
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (63208, 139655, 9, 'Liam', 'Both are fantasy films about a young protagonist discovering a magical world and their destiny within it', null);  # Narnia -> Harry Potter Prisoner of Azkaban
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (139655, 139652, 9, 'Liam', 'Both are Harry Potter entries where the stakes and tone shift significantly darker', null);  # Prisoner of Azkaban -> Goblet of Fire
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30959, 311038, 9, 'Liam', 'Both are superhero films that ground the genre in real emotion and character development', null);  # Batman Begins -> Spider-Man 2
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (267038, 849, 2, 'Liam', 'Both are sequels but 101 Dalmatians II is a direct-to-video product with no craft or ambition', null);  # Pulp Fiction -> 101 Dalmatians II
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (194500, 849, 2, 'Liam', 'Both involve ensemble casts on a journey but 101 Dalmatians II is aimed at toddlers', null);  # LOTR -> 101 Dalmatians II
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (131780, 363780, 2, 'Liam', 'Both involve characters operating outside social norms but White Chicks has zero artistic merit', null);  # Goodfellas -> White Chicks
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (289109, 108760, 2, 'Liam', 'Both involve a group facing a powerful enemy but Fantastic Four has no tension or emotional weight', null);  # Saving Private Ryan -> Fantastic Four
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (297838, 370017, 2, 'Liam', 'Both involve a protagonist fighting for survival but XXX replaces all depth with mindless action', null);  # Shawshank -> XXX
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (130128, 370017, 2, 'Liam', 'Both involve power and criminal organizations but XXX has no complexity or dramatic weight', null);  # Godfather -> XXX
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (111813, 363780, 2, 'Liam', 'Both involve confrontation and power dynamics but White Chicks is completely void of any tension', null);  # Few Good Men -> White Chicks
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (969, 849, 2, 'Liam', 'Both involve a group dynamic but 101 Dalmatians II has none of 12 Angry Men moral urgency', null);  # 12 Angry Men -> 101 Dalmatians II
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (46169, 108760, 2, 'Liam', 'Both involve warriors with special abilities but Fantastic Four has no historical or emotional weight', null);  # Braveheart -> Fantastic Four
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (18960, 363780, 2, 'Liam', 'Both involve characters deep in a world that has lost all moral order but White Chicks is pure nonsense', null);  # Apocalypse Now -> White Chicks
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (301540, 849, 2, 'Liam', 'Both involve pursuit but 101 Dalmatians II replaces all psychological dread with puppy comedy', null);  # Silence of Lambs -> 101 Dalmatians II
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (121538, 370017, 3, 'Liam', 'Both involve elite soldiers on a mission but XXX strips out all the psychological complexity', null);  # Full Metal Jacket -> XXX
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (65764, 363780, 2, 'Liam', 'Both are provocative in their premise but White Chicks has no artistic intention behind its shock', null);  # Clockwork Orange -> White Chicks
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (326155, 187191, 2, 'Liam', 'Both feature a protagonist who feels alienated from society but Legally Blonde stays entirely cheerful', null);  # Taxi Driver -> Legally Blonde
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (270971, 108760, 2, 'Liam', 'Both involve physical combat as identity but Fantastic Four turns it into weightless CGI spectacle', null);  # Raging Bull -> Fantastic Four
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (112290, 849, 2, 'Liam', 'Both involve characters escaping a confined existence but 101 Dalmatians II has no philosophical depth', null);  # Fight Club -> 101 Dalmatians II
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (254986, 363780, 2, 'Liam', 'Both involve characters hiding their true identity but White Chicks trivializes what The Pianist dignifies', null);  # The Pianist -> White Chicks
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (56304, 108760, 2, 'Liam', 'Both involve powerful figures in conflict but Fantastic Four has no weight, menace, or drama', null);  # Casino -> Fantastic Four
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (117874, 363780, 2, 'Liam', 'Both follow a character navigating a world they do not fully understand but White Chicks has no soul', null);  # Forrest Gump -> White Chicks
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (340901, 108760, 2, 'Liam', 'Both involve a protagonist discovering the world around them is not what it seems but FF lacks all depth', null);  # Truman Show -> Fantastic Four
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (130128, 849, 2, 'Liam', 'Both involve family loyalty as a core theme but 101 Dalmatians II operates on a completely different level', null);  # Godfather -> 101 Dalmatians II
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (289787, 41849, 2, 'Liam', 'Both are set in beautiful locations with emotional undercurrents but Blue Lagoon has no real story', null);  # Scent of a Woman -> Blue Lagoon
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (32114, 41849, 2, 'Liam', 'Both isolate two characters in an unusual environment but Blue Lagoon has no intellectual dimension', null);  # Beautiful Mind -> Blue Lagoon
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (134077, 370017, 2, 'Liam', 'Both involve a powerful and dangerous individual but XXX reduces all tension to pure spectacle', null);  # Green Mile -> XXX
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (80583, 849, 2, 'Liam', 'Both involve young people learning important life lessons but 101 Dalmatians II stays entirely surface level', null);  # Dead Poets Society -> 101 Dalmatians II
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (97727, 41849, 3, 'Liam', 'Both involve social outcasts in isolation but Blue Lagoon lacks the emotional poetry of Scissorhands', null);  # Edward Scissorhands -> Blue Lagoon
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (37178, 363780, 2, 'Liam', 'Both are comedies about characters who refuse to conform but White Chicks has no wit or originality', null);  # Big Lebowski -> White Chicks
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (275453, 108760, 2, 'Liam', 'Both involve a team learning to work together but Fantastic Four completely fails at the character level', null);  # Remember the Titans -> Fantastic Four
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (158927, 108760, 3, 'Liam', 'Both are superhero ensemble films but Fantastic Four fails where Incredibles succeeds at every level', null);  # Incredibles -> Fantastic Four
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (333856, 41849, 2, 'Liam', 'Both are romantic films set in isolated natural environments but Blue Lagoon has no emotional craft', null);  # Titanic -> Blue Lagoon
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (270971, 166917, 8, 'Liam', 'Both are intense character studies about a man whose identity is entirely built around physical performance', null);  # Raging Bull -> Jerry Maguire
