insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (139657, 139650, 10, 'Noam-Barkai', 'Both early HP, magical and fun in the same way.', null);  # 139657 Harry Potter and the Sorcerer's Stone 2001 -> 139650 Harry Potter and the Chamber of Secrets 2002
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (139650, 139655, 10, 'Noam-Barkai', 'Natural next step, both early HP at their peak.', null);  # 139650 Harry Potter and the Chamber of Secrets -> 139655 Harry Potter and the Prisoner of Azkaban
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (139657, 139655, 10, 'Noam-Barkai', 'Both early HP, both classics of the series.', null);  # 139657 Harry Potter and the Sorcerer's Stone -> 139655 Harry Potter and the Prisoner of Azkaban
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (139655, 139652, 8, 'Noam-Barkai', 'Same series moving into a slightly more mature tone.', null);  # 139655 Harry Potter and the Prisoner of Azkaban -> 139652 Harry Potter and the Goblet of Fire
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (139652, 139654, 8, 'Noam-Barkai', 'Same later-HP feel, both with strong villains.', null);  # 139652 Harry Potter and the Goblet of Fire -> 139654 Harry Potter and the Order of the Phoenix
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (139654, 139653, 8, 'Noam-Barkai', 'Both later HP with the same darker tone.', null);  # 139654 Harry Potter and the Order of the Phoenix -> 139653 Harry Potter and the Half-Blood Prince
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (256632, 256631, 9, 'Noam-Barkai', 'Same world, same lead character, same adventure energy.', null);  # 256632 Pirates of the Caribbean -> 256631 Pirates of the Caribbean 2
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (300229, 300230, 10, 'Noam-Barkai', 'Sequel is even better, same humor and great soundtrack choices.', null);  # 300229 Shrek -> 300230 Shrek 2
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (159172, 271095, 10, 'Noam-Barkai', 'Peak adventure cinema, both Indy classics.', null);  # 159172 Indiana Jones and the Last Crusade -> 271095 Raiders of the Lost Ark
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (311037, 311038, 9, 'Noam-Barkai', 'Same hero, the sequel is even stronger.', null);  # 311037 Spider-Man -> 311038 Spider-Man 2
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (14132, 14157, 9, 'Noam-Barkai', 'Same cast back together, nostalgia carries it well.', null);  # 14132 American Pie 2 -> 14157 American Reunion
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (280270, 280281, 8, 'Noam-Barkai', 'Same underdog story continued, the sequel keeps the formula working.', null);  # 280270 Rocky -> 280281 Rocky II
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (188507, 188509, 9, 'Noam-Barkai', 'Best buddy cop pairing, the sequel is even tighter.', null);  # 188507 Lethal Weapon -> 188509 Lethal Weapon 2
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313478, 313479, 8, 'Noam-Barkai', 'Same original trilogy, both have iconic scenes.', null);  # 313478 Star Wars: Episode V - The Empire Strikes Back -> 313479 Star Wars: Episode VI - Return of the Jedi
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (312150, 312151, 9, 'Noam-Barkai', 'Same family spy adventure, sequel is just as fun.', null);  # 312150 Spy Kids -> 312151 Spy Kids 2
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (142491, 142492, 9, 'Noam-Barkai', 'Same world, Del Toro''s creature design only gets more imaginative.', null);  # 142491 Hellboy -> 142492 Hellboy 2
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30959, 30976, 8, 'Noam-Barkai', 'Both grounded Batman entries, both underseen highlights.', null);  # 30959 Batman Begins -> 30976 Batman: Mask of the Phantasm
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (215876, 215880, 6, 'Noam-Barkai', 'Same franchise, MI3 returns to a strong villain story.', null);  # 215876 Mission: Impossible -> 215880 Mission: Impossible III
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (97727, 304862, 9, 'Noam-Barkai', 'Both Burton plus Depp gothic fairy tales.', null);  # 97727 Edward Scissorhands -> 304862 Sleepy Hollow
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (97727, 70959, 9, 'Noam-Barkai', 'Both Burton at his gentle, dark fairy tale best.', null);  # 97727 Edward Scissorhands -> 70959 Corpse Bride
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (304862, 70959, 9, 'Noam-Barkai', 'Burton''s gothic mood translates well between live action and animation.', null);  # 304862 Sleepy Hollow -> 70959 Corpse Bride
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (70959, 59578, 8, 'Noam-Barkai', 'Both Burton, both have a strong whimsical musical streak.', null);  # 70959 Corpse Bride -> 59578 Charlie and the Chocolate Factory
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (59578, 97727, 9, 'Noam-Barkai', 'Burton plus Depp, both touched with a strange kind of tenderness.', null);  # 59578 Charlie and the Chocolate Factory -> 97727 Edward Scissorhands
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (174953, 218219, 10, 'Noam-Barkai', 'Peak Miyazaki, both with strong environmental themes.', null);  # 174953 Nausicaa -> 218219 Mononoke
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (96593, 271095, 8, 'Noam-Barkai', 'Peak Spielberg wonder era, both iconic for a reason.', null);  # 96593 E.T. -> 271095 Raiders of the Lost Ark
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (271095, 165961, 8, 'Noam-Barkai', 'Same Spielberg masterful tension, both built around restraint.', null);  # 271095 Raiders of the Lost Ark -> 165961 Jaws
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (96593, 149287, 8, 'Noam-Barkai', 'Both Spielberg-touched childhood wonder films that hit the same emotional notes.', null);  # 96593 E.T. -> 149287 Hook
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (263360, 283410, 9, 'Noam-Barkai', 'Same leads, same director, same romantic chemistry.', null);  # 263360 Pretty Woman -> 283410 Runaway Bride
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (256632, 97727, 8, 'Noam-Barkai', 'Both Depp at his most committed to a character.', null);  # 256632 Pirates of the Caribbean -> 97727 Edward Scissorhands
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (256632, 304862, 8, 'Noam-Barkai', 'Both Depp adventure with a gothic edge.', null);  # 256632 Pirates of the Caribbean -> 304862 Sleepy Hollow
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (97727, 34104, 9, 'Noam-Barkai', 'Both Depp playing gentle outsiders in tender romances.', null);  # 97727 Edward Scissorhands -> 34104 Benny & Joon
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (113506, 97727, 8, 'Noam-Barkai', 'Both Depp at his most tender and understated.', null);  # 113506 Finding Neverland -> 97727 Edward Scissorhands
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (113506, 34104, 8, 'Noam-Barkai', 'Both Depp in quieter, more emotional roles.', null);  # 113506 Finding Neverland -> 34104 Benny & Joon
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (56871, 328272, 8, 'Noam-Barkai', 'Same Spielberg plus Hanks, both warm-hearted stories.', null);  # 56871 Catch Me If You Can -> 328272 The Terminal
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (263360, 151616, 9, 'Noam-Barkai', 'Both classic romcoms with strong leads and rewatch value.', null);  # 263360 Pretty Woman -> 151616 How to Lose a Guy in 10 Days
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (151616, 644, 9, 'Noam-Barkai', 'Both smart, funny early 2000s romcoms.', null);  # 151616 How to Lose a Guy in 10 Days -> 644 10 Things I Hate About You
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (644, 66194, 10, 'Noam-Barkai', 'Both smart teen comedies that hold up over time.', null);  # 644 10 Things I Hate About You -> 66194 Clueless
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (1038, 66194, 9, 'Noam-Barkai', 'Both fun comedies anchored by a strong female lead.', null);  # 1038 13 Going on 30 -> 66194 Clueless
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (263360, 200864, 9, 'Noam-Barkai', 'Same Cinderella formula, both lovely.', null);  # 263360 Pretty Woman -> 200864 Maid in Manhattan
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (200864, 264157, 8, 'Noam-Barkai', 'Both modern fairy tale princess stories.', null);  # 200864 Maid in Manhattan -> 264157 Princess Diaries 2
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (46878, 151616, 8, 'Noam-Barkai', 'Both messy female lead romcoms with real laughs.', null);  # 46878 Bridget Jones -> 151616 How to Lose a Guy in 10 Days
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (46878, 1038, 8, 'Noam-Barkai', 'Both feel-good female-led comedies.', null);  # 46878 Bridget Jones -> 1038 13 Going on 30
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (264157, 263360, 8, 'Noam-Barkai', 'Same warm romance formula with a Cinderella-style lead and great chemistry.', null);  # 264157 Princess Diaries 2 -> 263360 Pretty Woman
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (283410, 151616, 8, 'Noam-Barkai', 'Both light romcoms with great chemistry between the leads.', null);  # 283410 Runaway Bride -> 151616 How to Lose a Guy in 10 Days
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (283410, 200864, 8, 'Noam-Barkai', 'Both romantic comedies in the same warm Garry Marshall vein.', null);  # 283410 Runaway Bride -> 200864 Maid in Manhattan
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (1038, 644, 9, 'Noam-Barkai', 'Both fun 2000s comedies with great female leads.', null);  # 1038 13 Going on 30 -> 644 10 Things I Hate About You
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (1038, 151616, 10, 'Noam-Barkai', 'Peak 2000s romcoms, both endlessly rewatchable.', null);  # 1038 13 Going on 30 -> 151616 How to Lose a Guy in 10 Days
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (337166, 300229, 8, 'Noam-Barkai', 'Both animated family comedies that work on multiple levels.', null);  # 337166 Toy Story -> 300229 Shrek
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (337166, 190869, 8, 'Noam-Barkai', 'Both animated family stories with heart.', null);  # 337166 Toy Story -> 190869 Lilo & Stitch
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (190869, 300229, 8, 'Noam-Barkai', 'Both animated comedies with surprising emotional depth under the jokes.', null);  # 190869 Lilo & Stitch -> 300229 Shrek
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (32180, 97727, 8, 'Noam-Barkai', 'Both outsider romance retellings of fairy tales.', null);  # 32180 Beauty and the Beast 2003 -> 97727 Edward Scissorhands
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (32180, 70959, 8, 'Noam-Barkai', 'Both gothic romance retellings.', null);  # 32180 Beauty and the Beast 2003 -> 70959 Corpse Bride
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (32180, 304862, 6, 'Noam-Barkai', 'Both have a similar gothic atmospheric feel.', null);  # 32180 Beauty and the Beast 2003 -> 304862 Sleepy Hollow
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (256632, 271095, 9, 'Noam-Barkai', 'Both peak swashbuckling adventure.', null);  # 256632 Pirates of the Caribbean -> 271095 Raiders of the Lost Ark
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (256632, 159172, 9, 'Noam-Barkai', 'Same swashbuckling energy, same charismatic lead.', null);  # 256632 Pirates of the Caribbean -> 159172 Indiana Jones and the Last Crusade
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (256632, 149287, 8, 'Noam-Barkai', 'Both fun, swashbuckling, slightly magical adventures.', null);  # 256632 Pirates of the Caribbean -> 149287 Hook
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (149287, 271095, 8, 'Noam-Barkai', 'Both adventure films with the same childlike sense of wonder.', null);  # 149287 Hook -> 271095 Raiders of the Lost Ark
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (271095, 131885, 8, 'Noam-Barkai', 'Both have classic treasure hunt energy.', null);  # 271095 Raiders of the Lost Ark -> 131885 Goonies
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (159172, 131885, 8, 'Noam-Barkai', 'Both adventure with strong kid appeal.', null);  # 159172 Indiana Jones and the Last Crusade -> 131885 Goonies
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (159172, 149287, 8, 'Noam-Barkai', 'Both adventure with the same big-hearted sense of wonder.', null);  # 159172 Indiana Jones and the Last Crusade -> 149287 Hook
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (113506, 31715, 8, 'Noam-Barkai', 'Both earn their tears in honest, different ways.', null);  # 113506 Finding Neverland -> 31715 Beaches
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (31715, 67395, 7, 'Noam-Barkai', 'Both deal with strong female bonds and the weight of long friendships.', null);  # 31715 Beaches -> 67395 The Color Purple
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (244421, 34104, 8, 'Noam-Barkai', 'Both about neurodivergent characters handled with real heart.', null);  # 244421 The Other Sister -> 34104 Benny & Joon
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (271344, 264157, 8, 'Noam-Barkai', 'Both have the same warm family Garry Marshall touch.', null);  # 271344 Raising Helen -> 264157 Princess Diaries 2
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (271344, 151616, 7, 'Noam-Barkai', 'Same Kate Hudson romantic energy and same kind of light, funny vibe.', null);  # 271344 Raising Helen -> 151616 How to Lose a Guy in 10 Days
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (220276, 62460, 8, 'Noam-Barkai', 'Both rich and romantic, set in beautifully shot worlds.', null);  # 220276 Moulin Rouge -> 62460 Chocolat
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (62460, 33492, 9, 'Noam-Barkai', 'Both quiet European films about food, love and grief.', null);  # 62460 Chocolat -> 33492 Bella Martha
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (33492, 183370, 7, 'Noam-Barkai', 'Both small, quiet European dramas with strong leads.', null);  # 33492 Bella Martha -> 183370 Ladies in Lavender
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (183370, 62460, 7, 'Noam-Barkai', 'Both quiet European dramas with warm performances.', null);  # 183370 Ladies in Lavender -> 62460 Chocolat
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (238072, 56871, 8, 'Noam-Barkai', 'Both stylish caper energy with charming leads.', null);  # 238072 Ocean's Eleven -> 56871 Catch Me If You Can
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (220805, 56871, 6, 'Noam-Barkai', 'Both lighthearted, stylish action-comedy.', null);  # 220805 Mr. and Mrs. Smith -> 56871 Catch Me If You Can
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (220805, 238072, 6, 'Noam-Barkai', 'Both glossy, fun ensemble action films.', null);  # 220805 Mr. and Mrs. Smith -> 238072 Ocean's Eleven
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (220805, 215876, 6, 'Noam-Barkai', 'Both action-spy films with strong set pieces.', null);  # 220805 Mr. and Mrs. Smith -> 215876 Mission: Impossible
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (220276, 220805, 6, 'Noam-Barkai', 'Both lean into a stylized, glossy energy.', null);  # 220276 Moulin Rouge -> 220805 Mr. and Mrs. Smith
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (304862, 120506, 6, 'Noam-Barkai', 'Both atmospheric Depp historical mysteries.', null);  # 304862 Sleepy Hollow -> 120506 From Hell
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (149287, 131885, 8, 'Noam-Barkai', 'Both kid-led adventures with the same 80s warmth.', null);  # 149287 Hook -> 131885 Goonies
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (96593, 131885, 8, 'Noam-Barkai', 'Both kid adventure classics with heart.', null);  # 96593 E.T. -> 131885 Goonies
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (174953, 70959, 6, 'Noam-Barkai', 'Both fantasy animation with strong tonal moods.', null);  # 174953 Nausicaa -> 70959 Corpse Bride
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (218219, 304862, 7, 'Noam-Barkai', 'Both have darker fantasy atmospheres and that same haunting visual mood.', null);  # 218219 Mononoke -> 304862 Sleepy Hollow
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (218219, 70959, 6, 'Noam-Barkai', 'Both animated fantasy with the same darker pull.', null);  # 218219 Mononoke -> 70959 Corpse Bride
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (264157, 1038, 8, 'Noam-Barkai', 'Both fun female-led growing-up stories.', null);  # 264157 Princess Diaries 2 -> 1038 13 Going on 30
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (257744, 62460, 7, 'Noam-Barkai', 'Multiple love stories handled with care, similar warmth.', null);  # 257744 Playing by Heart -> 62460 Chocolat
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (271344, 200864, 8, 'Noam-Barkai', 'Both warm family-and-romance films with a Cinderella-style hopeful streak.', null);  # 271344 Raising Helen -> 200864 Maid in Manhattan
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (290070, 289109, 7, 'Noam-Barkai', 'Both Spielberg''s serious historical work, made in the same era and register.', null);  # 290070 Schindler's List -> 289109 Saving Private Ryan
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (66194, 46878, 7, 'Noam-Barkai', 'Both about a messy female lead navigating life with humor.', null);  # 66194 Clueless -> 46878 Bridget Jones
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (139657, 194502, 4, 'Noam-Barkai', 'Though both are big fantasy series, LOTR''s pacing drags compared to HP''s brisker rhythm.', null);  # 139657 Harry Potter and the Sorcerer's Stone -> 194502 Lord of the Rings: The Two Towers
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (300229, 300233, 3, 'Noam-Barkai', 'Though both are Shrek, 4-D is a theme park gimmick rather than a real film.', null);  # 300229 Shrek -> 300233 Shrek 4-D
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (300230, 300233, 3, 'Noam-Barkai', 'Though both are Shrek, 4-D is a major step down.', null);  # 300230 Shrek 2 -> 300233 Shrek 4-D
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (280270, 280305, 2, 'Noam-Barkai', 'Though both are Rocky, V is the clear franchise low.', null);  # 280270 Rocky -> 280305 Rocky V
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (280281, 280305, 2, 'Noam-Barkai', 'Same series but Rocky V kills the momentum entirely.', null);  # 280281 Rocky II -> 280305 Rocky V
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (188507, 188511, 4, 'Noam-Barkai', 'Same series but LW4 feels tired by the end of the franchise.', null);  # 188507 Lethal Weapon -> 188511 Lethal Weapon 4
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (188509, 188511, 4, 'Noam-Barkai', 'Same buddy cop pair but the spark is gone by the fourth film.', null);  # 188509 Lethal Weapon 2 -> 188511 Lethal Weapon 4
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (271095, 159167, 3, 'Noam-Barkai', 'Though both are Indy, the fourth film is the clear franchise low.', null);  # 271095 Raiders of the Lost Ark -> 159167 Indiana Jones 4
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (159172, 159167, 3, 'Noam-Barkai', 'Same series but Indy 4 strains belief in every scene.', null);  # 159172 Indiana Jones and the Last Crusade -> 159167 Indiana Jones 4
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (159172, 159175, 4, 'Noam-Barkai', 'Same series but Temple of Doom is tonally off from the rest.', null);  # 159172 Indiana Jones and the Last Crusade -> 159175 Indiana Jones and the Temple of Doom
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (311037, 311040, 4, 'Noam-Barkai', 'Same hero but Spider-Man 3 collapses under too many villains.', null);  # 311037 Spider-Man -> 311040 Spider-Man 3
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (311038, 311040, 4, 'Noam-Barkai', 'Same series but the third entry is the clear weak link.', null);  # 311038 Spider-Man 2 -> 311040 Spider-Man 3
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (312151, 312152, 4, 'Noam-Barkai', 'Same family franchise but the 3D gimmick weighs it down.', null);  # 312151 Spy Kids 2 -> 312152 Spy Kids 3-D
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313478, 313476, 3, 'Noam-Barkai', 'Same saga but Attack of the Clones has painful romance dialogue.', null);  # 313478 Star Wars: Episode V - The Empire Strikes Back -> 313476 Star Wars: Episode II - Attack of the Clones
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313479, 313474, 3, 'Noam-Barkai', 'Same saga but Phantom Menace is mostly a slog.', null);  # 313479 Star Wars: Episode VI - Return of the Jedi -> 313474 Star Wars: Episode I - The Phantom Menace
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313478, 313477, 5, 'Noam-Barkai', 'Same saga but moving from original trilogy to prequels is a clear quality drop.', null);  # 313478 Star Wars: Episode V - The Empire Strikes Back -> 313477 Star Wars: Episode III - Revenge of the Sith
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (130945, 354178, 3, 'Noam-Barkai', 'Same Bond series but View to a Kill is a real franchise low.', null);  # 130945 GoldenEye -> 354178 A View to a Kill
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (130945, 218808, 3, 'Noam-Barkai', 'Same Bond but sending him to space is silly.', null);  # 130945 GoldenEye -> 218808 Moonraker
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (130945, 86263, 3, 'Noam-Barkai', 'Same era Bond but Die Another Day is hard to take seriously.', null);  # 130945 GoldenEye -> 86263 Die Another Day
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (130953, 354178, 3, 'Noam-Barkai', 'Same series but View to a Kill is one of the weakest entries.', null);  # 130953 Goldfinger -> 354178 A View to a Kill
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (130953, 218808, 3, 'Noam-Barkai', 'Same Bond but Moonraker is by far the silliest entry.', null);  # 130953 Goldfinger -> 218808 Moonraker
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (240521, 354178, 3, 'Noam-Barkai', 'Same series but View to a Kill is a real low point.', null);  # 240521 On Her Majesty's Secret Service -> 354178 A View to a Kill
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (130953, 85871, 4, 'Noam-Barkai', 'Same era Bond but Diamonds is very dated even by 70s standards.', null);  # 130953 Goldfinger -> 85871 Diamonds Are Forever
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (92573, 218808, 3, 'Noam-Barkai', 'Same Bond but Moonraker is just too silly.', null);  # 92573 Dr. No -> 218808 Moonraker
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (130953, 192514, 4, 'Noam-Barkai', 'Same series but Live and Let Die is one of the weaker entries.', null);  # 130953 Goldfinger -> 192514 Live and Let Die
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (267038, 276217, 5, 'Noam-Barkai', 'Both Tarantino crime films, but back to back is too much violence.', null);  # 267038 Pulp Fiction -> 276217 Reservoir Dogs
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (267038, 176711, 4, 'Noam-Barkai', 'Both Tarantino but Kill Bill is much more relentlessly violent.', null);  # 267038 Pulp Fiction -> 176711 Kill Bill: Vol. 1
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (276217, 176711, 4, 'Noam-Barkai', 'Both Tarantino crime stories but Kill Bill takes the violence to a different level.', null);  # 276217 Reservoir Dogs -> 176711 Kill Bill: Vol. 1
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (176711, 176712, 5, 'Noam-Barkai', 'Same film really, splitting it into two felt pointless.', null);  # 176711 Kill Bill: Vol. 1 -> 176712 Kill Bill: Vol. 2
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (267038, 164572, 5, 'Noam-Barkai', 'Same director but Jackie Brown''s pacing is much slower.', null);  # 267038 Pulp Fiction -> 164572 Jackie Brown
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (131780, 56304, 4, 'Noam-Barkai', 'Both Scorsese mob films, watching them back to back is repetitive.', null);  # 131780 Goodfellas -> 56304 Casino
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (270971, 131780, 4, 'Noam-Barkai', 'Both Scorsese and both very heavy on the violence I do not enjoy.', null);  # 270971 Raging Bull -> 131780 Goodfellas
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (326155, 177369, 4, 'Noam-Barkai', 'Both Scorsese plus De Niro studies of obsession.', null);  # 326155 Taxi Driver -> 177369 The King of Comedy
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (54209, 326155, 3, 'Noam-Barkai', 'Both Scorsese plus De Niro intense, neither one I want to revisit.', null);  # 54209 Cape Fear -> 326155 Taxi Driver
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (25192, 56304, 4, 'Noam-Barkai', 'Both long Scorsese dramas, watching both is exhausting.', null);  # 25192 The Aviator -> 56304 Casino
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (8183, 131780, 3, 'Noam-Barkai', 'Same director but the worlds and registers could not be more apart.', null);  # 8183 The Age of Innocence -> 131780 Goodfellas
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (25192, 270971, 4, 'Noam-Barkai', 'Both Scorsese biopic-style heavies, with the same long slow descent.', null);  # 25192 The Aviator -> 270971 Raging Bull
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (7842, 56304, 3, 'Noam-Barkai', 'Same Scorsese but tonally a long way apart, dark comedy versus mob epic.', null);  # 7842 After Hours -> 56304 Casino
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (112290, 291698, 4, 'Noam-Barkai', 'Both Fincher and both heavy bleak, watching them back to back is draining.', null);  # 112290 Fight Club -> 291698 Se7en
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (112290, 210511, 5, 'Noam-Barkai', 'Both clever twist films, watching both at once is overload.', null);  # 112290 Fight Club -> 210511 Memento
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (247579, 291698, 4, 'Noam-Barkai', 'Same Fincher but Se7en is much darker and heavier.', null);  # 247579 Panic Room -> 291698 Se7en
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (123435, 247579, 5, 'Noam-Barkai', 'Both Fincher thrillers, similar but not memorable as a pair.', null);  # 123435 The Game -> 247579 Panic Room
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (96593, 290070, 3, 'Noam-Barkai', 'Same director but completely opposite tones.', null);  # 96593 E.T. -> 290070 Schindler's List
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (96593, 21213, 4, 'Noam-Barkai', 'Both Spielberg sci-fi with a child but AI is much heavier.', null);  # 96593 E.T. -> 21213 Artificial Intelligence: AI
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (271095, 290070, 3, 'Noam-Barkai', 'Same director but very different in scale and weight.', null);  # 271095 Raiders of the Lost Ark -> 290070 Schindler's List
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (165961, 290070, 3, 'Noam-Barkai', 'Same Spielberg but the stories and stakes are nowhere near each other.', null);  # 165961 Jaws -> 290070 Schindler's List
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (149287, 289109, 2, 'Noam-Barkai', 'Same Spielberg but adventure for kids and a grim war film sit on opposite ends.', null);  # 149287 Hook -> 289109 Saving Private Ryan
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (21213, 359297, 4, 'Noam-Barkai', 'Both Spielberg sci-fi but both have endings that fall flat.', null);  # 21213 Artificial Intelligence: AI -> 359297 War of the Worlds
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (21213, 65811, 4, 'Noam-Barkai', 'Both Spielberg sci-fi but both are very slowly paced.', null);  # 21213 Artificial Intelligence: AI -> 65811 Close Encounters of the Third Kind
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (96593, 100130, 4, 'Noam-Barkai', 'Both Spielberg with a child lead but Empire is much heavier.', null);  # 96593 E.T. -> 100130 Empire of the Sun
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (97727, 97360, 4, 'Noam-Barkai', 'Same Burton plus Depp but Ed Wood is much slower and quieter.', null);  # 97727 Edward Scissorhands -> 97360 Ed Wood
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (304862, 97360, 4, 'Noam-Barkai', 'Same Burton plus Depp but Ed Wood lands in a much sleepier register.', null);  # 304862 Sleepy Hollow -> 97360 Ed Wood
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (256632, 97360, 4, 'Noam-Barkai', 'Both Depp but the energy could not be more different.', null);  # 256632 Pirates of the Caribbean -> 97360 Ed Wood
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (70959, 97360, 4, 'Noam-Barkai', 'Both Burton but Ed Wood is the slowest of his work.', null);  # 70959 Corpse Bride -> 97360 Ed Wood
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (113506, 97360, 4, 'Noam-Barkai', 'Same Depp era but the two films have very different rhythms.', null);  # 113506 Finding Neverland -> 97360 Ed Wood
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (39551, 10830, 4, 'Noam-Barkai', 'Same director but war film versus sci-fi horror is too jarring.', null);  # 39551 Black Hawk Down -> 10830 Alien
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (39551, 39829, 4, 'Noam-Barkai', 'Same director but neither film is one I rewatch.', null);  # 39551 Black Hawk Down -> 39829 Black Rain
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (39829, 10830, 4, 'Noam-Barkai', 'Same director but the two pull from very different genre playbooks.', null);  # 39829 Black Rain -> 10830 Alien
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (39551, 129185, 5, 'Noam-Barkai', 'Both Ridley Scott action but very different scales.', null);  # 39551 Black Hawk Down -> 129185 Gladiator
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (129185, 10830, 4, 'Noam-Barkai', 'Same director but very different genres and eras, epic versus claustrophobic horror.', null);  # 129185 Gladiator -> 10830 Alien
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (56871, 25192, 5, 'Noam-Barkai', 'Both DiCaprio biopic-ish stories but Aviator is much heavier and longer.', null);  # 56871 Catch Me If You Can -> 25192 The Aviator
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (56871, 30686, 4, 'Noam-Barkai', 'Both DiCaprio but Basketball Diaries is a dark addiction story.', null);  # 56871 Catch Me If You Can -> 30686 The Basketball Diaries
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (25192, 336445, 3, 'Noam-Barkai', 'Both DiCaprio dramas but Total Eclipse is much bleaker.', null);  # 25192 The Aviator -> 336445 Total Eclipse
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30686, 336445, 4, 'Noam-Barkai', 'Both DiCaprio dark dramas about ruin.', null);  # 30686 The Basketball Diaries -> 336445 Total Eclipse
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (330670, 336445, 4, 'Noam-Barkai', 'Both DiCaprio in difficult, dark roles.', null);  # 330670 This Boy's Life -> 336445 Total Eclipse
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (25192, 123849, 4, 'Noam-Barkai', 'Both Scorsese plus DiCaprio but very different periods and tones.', null);  # 25192 The Aviator -> 123849 Gangs of New York
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30686, 25192, 4, 'Noam-Barkai', 'Both DiCaprio darker dramas, neither is easy to sit through.', null);  # 30686 The Basketball Diaries -> 25192 The Aviator
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (335835, 215876, 5, 'Noam-Barkai', 'Both Cruise action but very different styles, one is fighter pilots and one is spies.', null);  # 335835 Top Gun -> 215876 Mission: Impossible
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (335835, 350424, 4, 'Noam-Barkai', 'Same actor but Vanilla Sky is a divisive mind-bender.', null);  # 335835 Top Gun -> 350424 Vanilla Sky
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (335835, 359297, 5, 'Noam-Barkai', 'Both Cruise but the tones pull in different directions.', null);  # 335835 Top Gun -> 359297 War of the Worlds
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (335835, 214755, 5, 'Noam-Barkai', 'Both Cruise but one is action fun and the other is sci-fi mystery.', null);  # 335835 Top Gun -> 214755 Minority Report
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (350424, 214755, 4, 'Noam-Barkai', 'Both Cruise sci-fi but very different tones, dream-logic versus precrime procedural.', null);  # 350424 Vanilla Sky -> 214755 Minority Report
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (263360, 336445, 2, 'Noam-Barkai', 'Though both have romantic elements, Total Eclipse is bleak and depressing.', null);  # 263360 Pretty Woman -> 336445 Total Eclipse
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (66194, 200521, 2, 'Noam-Barkai', 'Light teen comedy followed by a sprawling three-hour ensemble drama is a strange jump.', null);  # 66194 Clueless -> 200521 Magnolia
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (1038, 200521, 2, 'Noam-Barkai', 'Fun comedy followed by a heavy ensemble drama is a strange transition for one night.', null);  # 1038 13 Going on 30 -> 200521 Magnolia
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (263360, 267038, 2, 'Noam-Barkai', 'Romcom and violent crime are far enough apart that I would not pair them.', null);  # 263360 Pretty Woman -> 267038 Pulp Fiction
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (109421, 1038, 2, 'Noam-Barkai', 'Loud action versus light romcom, very different audiences.', null);  # 109421 The Fast and the Furious -> 1038 13 Going on 30
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (40199, 66194, 2, 'Noam-Barkai', 'Slow heavy sci-fi and a light teen comedy aim at different audiences.', null);  # 40199 Blade Runner -> 66194 Clueless
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (10830, 190869, 2, 'Noam-Barkai', 'Horror sci-fi and family animation aim at very different audiences.', null);  # 10830 Alien -> 190869 Lilo & Stitch
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (10920, 66194, 2, 'Noam-Barkai', 'Tense action sci-fi and teen comedy are pulling in opposite directions.', null);  # 10920 Aliens -> 66194 Clueless
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (200521, 200864, 2, 'Noam-Barkai', 'Sprawling weird drama followed by a light romance feels off.', null);  # 200521 Magnolia -> 200864 Maid in Manhattan
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (160524, 264157, 2, 'Noam-Barkai', 'Atmospheric thriller and family romance are a hard sell together.', null);  # 160524 Insomnia -> 264157 Princess Diaries 2
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (120506, 200864, 2, 'Noam-Barkai', 'Victorian murder mystery does not lead naturally to a modern romance.', null);  # 120506 From Hell -> 200864 Maid in Manhattan
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (233058, 59578, 4, 'Noam-Barkai', 'Both Depp, but dark occult mystery and a family musical are a strange jump.', null);  # 233058 The Ninth Gate -> 59578 Charlie and the Chocolate Factory
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (263360, 245699, 8, 'Noam-Barkai', 'Both feel-good romcoms with the same warm tone.', null);  # 263360 Pretty Woman -> 245699 Overboard
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (263360, 311428, 8, 'Noam-Barkai', 'Both light, comforting romances easy to put on any night.', null);  # 263360 Pretty Woman -> 311428 Splash
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (311428, 245699, 7, 'Noam-Barkai', 'Both mismatched-romance comedies of the 80s.', null);  # 311428 Splash -> 245699 Overboard
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30959, 311037, 8, 'Noam-Barkai', 'Both grounded superhero origin films, both played straight rather than campy.', null);  # 30959 Batman Begins -> 311037 Spider-Man
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30959, 311038, 8, 'Noam-Barkai', 'Both well-made, character-driven superhero films that earn their emotional beats.', null);  # 30959 Batman Begins -> 311038 Spider-Man 2
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (130953, 130945, 8, 'Noam-Barkai', 'Both Bond at his most iconic, decades apart but equally classic.', null);  # 130953 Goldfinger -> 130945 GoldenEye
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (271344, 1038, 7, 'Noam-Barkai', 'Both warm, fun, female-led stories about figuring life out.', null);  # 271344 Raising Helen -> 1038 13 Going on 30
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (271344, 46878, 7, 'Noam-Barkai', 'Both messy, lovable female leads with real heart.', null);  # 271344 Raising Helen -> 46878 Bridget Jones
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (244421, 113506, 7, 'Noam-Barkai', 'Both gentle dramas that carry quiet emotional weight without going melodramatic.', null);  # 244421 The Other Sister -> 113506 Finding Neverland
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (244421, 31715, 7, 'Noam-Barkai', 'Both about deep emotional bonds and family connection.', null);  # 244421 The Other Sister -> 31715 Beaches
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (257744, 31715, 7, 'Noam-Barkai', 'Both about emotional connections that span lifetimes.', null);  # 257744 Playing by Heart -> 31715 Beaches
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (379331, 372733, 8, 'Noam-Barkai', 'Both Sherlock takes that get the character right.', null);  # 379331 The Adventures of Sherlock Holmes -> 372733 Young Sherlock Holmes
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30962, 30961, 8, 'Noam-Barkai', 'Same animated continuity, both well done and worth seeing in sequence.', null);  # 30962 Batman Beyond: The Movie -> 30961 Batman Beyond: Return of the Joker
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (381392, 30961, 8, 'Noam-Barkai', 'Same world, both worth watching for the future Gotham aesthetic.', null);  # 381392 Batman Beyond -> 30961 Batman Beyond: Return of the Joker
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (256631, 271095, 7, 'Noam-Barkai', 'Both swashbuckling adventures with a charismatic lead.', null);  # 256631 Pirates of the Caribbean 2 -> 271095 Raiders of the Lost Ark
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (271095, 12744, 4, 'Noam-Barkai', 'Same Spielberg but Always is much quieter and far less memorable.', null);  # 271095 Raiders of the Lost Ark -> 12744 Always
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (96593, 12744, 4, 'Noam-Barkai', 'Spielberg again, but Always feels like a much lesser side project.', null);  # 96593 E.T. -> 12744 Always
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (328272, 289109, 4, 'Noam-Barkai', 'Same lead and same director, but the tonal jump between them is too sharp.', null);  # 328272 The Terminal -> 289109 Saving Private Ryan
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (337166, 70959, 4, 'Noam-Barkai', 'Animated both, but Pixar''s bright energy is a world from Burton''s gothic mood.', null);  # 337166 Toy Story -> 70959 Corpse Bride
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (190869, 70959, 4, 'Noam-Barkai', 'Family animation paired with a darker stop-motion piece, the moods clash.', null);  # 190869 Lilo & Stitch -> 70959 Corpse Bride
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (337166, 174953, 5, 'Noam-Barkai', 'Both animated but Pixar kids and Miyazaki epic are very different watches.', null);  # 337166 Toy Story -> 174953 Nausicaa
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (190869, 218219, 5, 'Noam-Barkai', 'Family animation followed by a much heavier Miyazaki epic is an odd jump.', null);  # 190869 Lilo & Stitch -> 218219 Mononoke
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (151616, 220276, 5, 'Noam-Barkai', 'Both have romance but the registers are nowhere alike.', null);  # 151616 How to Lose a Guy in 10 Days -> 220276 Moulin Rouge
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (66194, 220276, 5, 'Noam-Barkai', 'Both romance-adjacent, but Moulin Rouge is far more stylized and demanding.', null);  # 66194 Clueless -> 220276 Moulin Rouge
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (188510, 188511, 4, 'Noam-Barkai', 'Same series, both feel like the franchise running on fumes.', null);  # 188510 Lethal Weapon 3 -> 188511 Lethal Weapon 4
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (280282, 280305, 3, 'Noam-Barkai', 'Same series, but Rocky V kills the momentum III had.', null);  # 280282 Rocky III -> 280305 Rocky V
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (280284, 280305, 3, 'Noam-Barkai', 'After the silly fun of IV, Rocky V is a real drop.', null);  # 280284 Rocky IV -> 280305 Rocky V
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (188507, 188510, 5, 'Noam-Barkai', 'LW3 keeps the formula but loses the snap the first one had.', null);  # 188507 Lethal Weapon -> 188510 Lethal Weapon 3
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (256632, 233058, 5, 'Noam-Barkai', 'Both Depp but pirate adventure and dark occult mystery do not really fit.', null);  # 256632 Pirates of the Caribbean -> 233058 The Ninth Gate
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (123435, 112290, 5, 'Noam-Barkai', 'Both Fincher mind-benders, watching them in a row is overkill.', null);  # 123435 The Game -> 112290 Fight Club
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (39551, 335835, 4, 'Noam-Barkai', 'Same military setting but very different tones, one is grim and one is glossy fun.', null);  # 39551 Black Hawk Down -> 335835 Top Gun
