
-- ==========================================
-- 100 GOOD RECOMMENDATIONS (Scores 8-10)
-- ==========================================

-- Sci-Fi & Space Synergies
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (1711, 40199, 10, 'Good Match: Both pioneer immersive sci-fi environments, transitioning the terrifying silence of space you loved in 2001 into the dirty, neon future of Blade Runner.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (10830, 10920, 10, 'Good Match: Perfectly shifts the ultimate haunted house in space from the original into a high-octane military action masterpiece without losing tension.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (124554, 78787, 9, 'Good Match: If you appreciated the beautifully shot, ambitious dystopia of Gattaca, this bizarre and original sci-fi concept delivers a similarly excellent visual design.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (214755, 40199, 9, 'Good Match: The precrime concepts and interface design pair perfectly with the visually breathtaking dive into what it means to be human in a cyberpunk future.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (201516, 78787, 8, 'Good Match: Before the bullet-time effects of The Matrix rewrote cinema, Dark City utilized a similarly dark, reality-bending aesthetic.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (336458, 10920, 8, 'Good Match: Both rely on heavily stylized, hyper-violent sci-fi settings. If you liked the practical gore of Mars, you will love the chest-bursters.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (1711, 18979, 9, 'Good Match: Connects the pioneering realistic space travel of 2001 with the intense, nail-biting orbital mechanics of Apollo 13.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (10830, 214755, 8, 'Good Match: Translates the unforgettable claustrophobic dread of the Nostromo into a fascinating, high-stakes futuristic mystery.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (124554, 1711, 9, 'Good Match: Both share a sweeping, ambitious scale that uses stunning visual effects to tell deeply philosophical stories about humanity.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (336458, 40199, 8, 'Good Match: Pairs a deeply weird, action-heavy trip to Mars with the definitive, melancholic exploration of a dirty neon future.', 'orizehavi-tech');

-- Crime & Mob Synergies
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (130128, 131780, 10, 'Good Match: The operatic, sprawling tragedy of The Godfather flows perfectly into the frantic editing and killer soundtrack of Goodfellas.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (131780, 56304, 10, 'Good Match: Both plunge you directly into the mafia lifestyle, moving from street-level hustle to the meticulously organized mechanics of Vegas corruption.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (289558, 56304, 9, 'Good Match: An unapologetic, violently explosive look at ambition that aligns perfectly with the sweeping, violent epic of Casino.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (182955, 90771, 9, 'Good Match: Both are masterclasses in tension, swapping the tight neo-noir mystery of police corruption for the severe psychological toll of undercover work.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (279420, 130128, 9, 'Good Match: Explores the exact same beautifully shot, grim mobster themes of fathers, sons, and vengeance on a slightly more intimate scale.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (337404, 182955, 9, 'Good Match: Expands the interconnected narrative of devastating corruption from the drug trade into a tightly wound 1950s police conspiracy.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (193253, 238072, 9, 'Good Match: Both are breezy, highly stylized crime capers filled with unforgettable characters who ooze cool from every frame.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (90771, 131780, 9, 'Good Match: The deep undercover psychological toll pairs brilliantly with the authentic, fast-paced look into the mob lifestyle.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (289558, 130128, 8, 'Good Match: Two different sides of the organized crime coin: one an explosive look at unchecked greed, the other a sprawling classical tragedy.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (56304, 279420, 8, 'Good Match: Takes the violent mechanics of mafia corruption and distills them into a grim, beautifully shot tale of vengeance.', 'orizehavi-tech');

-- Action, Cops & Spies Synergies
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (86274, 310726, 10, 'Good Match: Both take an ordinary cop in an extraordinary situation and execute a brilliant high-concept premise that literally never slows down.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (27132, 188507, 9, 'Good Match: If you loved the stylish, loud buddy-cop formula of Bad Boys, Lethal Weapon is the film that set the absolute standard for the genre.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (107166, 68940, 9, 'Good Match: Both feature completely absurd premises held together by highly entertaining, chaotic set pieces and non-stop action.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (258860, 310726, 9, 'Good Match: Swaps the adrenaline-fueled surfing culture and tight bank heist plot for a relentless vehicular thrill ride.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (281334, 105723, 8, 'Good Match: The sharp, precise mercenary car chases map perfectly to the tense hijacking scenario that keeps the suspense tight throughout.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (65627, 139169, 8, 'Good Match: Both utilize incredibly creative practical stunts, moving from dizzying climbing heights to a highly stylized manhunt.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (337814, 188507, 9, 'Good Match: A fascinating contrast between a tense, claustrophobic ride through corrupt policing and a classic, loose-cannon veteran dynamic.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (262645, 10920, 9, 'Good Match: An invisible enemy in the jungle builds the same incredible dread and explosive payoff as the high-octane space marines.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (9023, 86274, 9, 'Good Match: Both use highly claustrophobic settings perfectly to deliver some of the tightest action scripts of their respective decades.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (158999, 9023, 8, 'Good Match: If you enjoy highly patriotic 90s action films with iconic set pieces, these two deliver pure popcorn entertainment.', 'orizehavi-tech');

-- Comedy & Satire Synergies
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (9125, 24430, 9, 'Good Match: Both are relentless barrages of visual gags, with one spoofing disaster films and the other perfectly nailing 60s spy movies.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (37178, 16006, 9, 'Good Match: A surreal, weed-fueled mystery driven by bizarre character interactions transitions perfectly into a brilliant satirical take on local news.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (238695, 37178, 9, 'Good Match: A painfully accurate, hilarious takedown of corporate bureaucracy that shares the same laid-back, anti-establishment tone as The Dude.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (644, 209133, 9, 'Good Match: Both offer a surprisingly sharp and clever deconstruction of high school cliques and toxic teenage social dynamics.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (111442, 644, 9, 'Good Match: Captures the pure chaos and fun of high school escapism, matching the sharp adaptation style of 10 Things I Hate About You.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (134672, 340901, 10, 'Good Match: Both brilliantly force you to experience a crushing artificial reality, balancing deep philosophical ideas with touching personal comedy.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (5573, 375827, 8, 'Good Match: Peak physical comedy that is ridiculous, over-the-top, and endlessly quotable, whether solving pet crimes or breaking down the modeling industry.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (291221, 9125, 9, 'Good Match: A brilliant, self-aware dissection of slasher tropes that shares the same manic parody energy as the ultimate aviation spoof.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (46877, 362808, 9, 'Good Match: Both feature dialogue that truly shines, perfectly capturing the awkwardness and hilarious struggles of modern dating over long periods.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (209133, 111442, 9, 'Good Match: The ultimate pairing of razor-sharp teenage social dynamics and iconic high school rebellion.', 'orizehavi-tech');

-- Animation & Family Synergies
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (32166, 9795, 10, 'Good Match: Both are flawless, magical romances that feature timeless musical numbers and capture the absolute peak of 90s animation.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (9795, 192013, 9, 'Good Match: The manic energy and unforgettable music of Aladdin pairs beautifully with the film that kickstarted that entire era of animation.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (218415, 113504, 9, 'Good Match: Turns childhood fears and corporate satire into the same visually stunning, emotionally touching journey found in Nemo.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (300229, 9795, 9, 'Good Match: A hilarious deconstruction of fairy tales packed with jokes for adults that perfectly mirrors the fast-paced wit of the Genie.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (48950, 18441, 8, 'Good Match: A charming, miniature epic that uses the exact same insect perspective to great comedic and adventurous effect.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (61291, 48950, 8, 'Good Match: Brilliantly executed animation homages, whether adapting POW escape films or classic samurai epics for family audiences.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (96590, 190869, 8, 'Good Match: Both are wonderfully weird and sweet stories about finding family and friendship with an alien in the most unlikely of places.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (192013, 32166, 9, 'Good Match: The timeless, perfect musical numbers of the sea transition seamlessly into the perfect, magical romance of the Beast''s castle.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (113504, 218415, 9, 'Good Match: A beautifully nostalgic adventure about overcoming fear that matches the huge amounts of heart found in Monsters, Inc.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (847, 20218, 8, 'Good Match: A fun, fast-paced London rescue mission that shares the cozy, lighthearted animal adventure vibes of the Aristocats.', 'orizehavi-tech');

-- War & Historical Epic Synergies
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (161481, 39551, 10, 'Good Match: The harrowing beach landing sequence prepares you perfectly for the visceral, documentary-style descent into modern urban warfare.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (39551, 101055, 9, 'Good Match: Swaps the absolute chaos of urban firefights for a raw, patient depiction of sniper warfare relying on deception and geometry.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (44450, 161481, 9, 'Good Match: A harrowing, powerful look at the aftermath of war that deepens the emotional impact of the intense battlefield sacrifices.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (290070, 44450, 10, 'Good Match: Both are monumental achievements in drama, offering deeply emotional and uncomfortable explorations of tragedy and survival.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (129185, 194497, 10, 'Good Match: The epic scope and tragic betrayal of Rome scales up flawlessly into the massive, emotionally grounded world of Middle-earth.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (194497, 194502, 10, 'Good Match: Perfectly continues the staggering scale of the fantasy epic, escalating directly into the gripping, massive Rohan battles.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (207390, 129185, 9, 'Good Match: A historically meticulous portrayal of naval strategy that perfectly matches the engaging, grand-scale combat of the gladiatorial arena.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (333856, 207390, 8, 'Good Match: If you loved the unmatched production scale and maritime disaster spectacle, this meticulous naval warfare epic is a must-watch.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (101055, 161481, 9, 'Good Match: Both deliver raw, unapologetic depictions of warfare that focus intensely on strategy, sacrifice, and survival.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (290070, 101462, 9, 'Good Match: The devastating black-and-white cinematography of survival pairs well with the fascinating, obsessive world of wartime code-breaking.', 'orizehavi-tech');

-- Drama & Underdog Synergies
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (280270, 149388, 9, 'Good Match: A gritty, deeply moving character study that perfectly aligns with the ultimate sports underdog movie focused on teamwork.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (149388, 275453, 9, 'Good Match: Both use the fundamentals of sports to tell incredibly uplifting stories about breaking down barriers and unlocking true potential.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (166917, 280270, 8, 'Good Match: Genuine emotional stakes elevate the sports agency drama just as they ground the iconic boxing underdog narrative.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (297838, 131665, 10, 'Good Match: Both are quiet, powerful testaments to the human spirit, dealing deeply with trauma, defense mechanisms, and ultimate triumph.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (131665, 271192, 9, 'Good Match: A very sensitive and moving exploration of brotherhood and patience that echoes the brilliant character work of Will Hunting.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (104338, 210509, 9, 'Good Match: A visually inventive exploration of memory and heartbreak that pairs beautifully with the genius reverse storytelling of an amnesiac.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (210509, 254943, 9, 'Good Match: Forces the audience into a frantic, paranoid dive into obsession, mathematical patterns, and deeply unreliable narration.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (271192, 313059, 9, 'Good Match: A beautifully nostalgic cross-country journey that perfectly captures the fleeting innocence of friendship and brotherhood.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (313059, 297838, 9, 'Good Match: Both Stephen King adaptations bypass horror to deliver touching, beautifully nostalgic adventures about the triumph of the human spirit.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (358708, 42983, 9, 'Good Match: A definitive, cold-blooded examination of 80s corporate greed that flows perfectly into a high-energy critique of toxic finance bros.', 'orizehavi-tech');

-- Thriller & Suspense Synergies
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (2000, 262645, 9, 'Good Match: Revitalizes tension by using terrifying, fast-moving threats to build incredible dread before the explosive finale.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (215346, 109608, 9, 'Good Match: A horrifyingly grounded psychological thriller that perfectly complements this intensely uncomfortable look at extreme obsession.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (109608, 91763, 8, 'Good Match: Shifts from the extreme consequence of an affair to a highly satisfying thriller revolving around revenge and legal loopholes.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (91763, 215346, 8, 'Good Match: Both feature smart, desperately gripping scenarios where protagonists must outwit their captors or betrayers.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (155634, 210509, 9, 'Good Match: A highly atmospheric whodunit with a genuinely surprising twist that will appeal directly to fans of non-linear memory puzzles.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (306051, 251979, 8, 'Good Match: An early tech thriller focusing on espionage that keeps the paranoia high, just like this dark dive into political assassinations.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (251979, 312138, 8, 'Good Match: Both unravel massive corporate and political cover-ups through stylish espionage, agency politics, and high-stakes extraction.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (312138, 281334, 8, 'Good Match: A sharp, realistic look at mercenary logistics and agency politics that thrives on tight suspense and precise planning.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (254943, 104338, 9, 'Good Match: A frantic, black-and-white dive into paranoia that shares the same visually inventive, emotionally crushing indie aesthetic.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (194204, 65764, 9, 'Good Match: A masterful psychological horror that slowly builds dread, pairing well with this highly disturbing exploration of dystopia.', 'orizehavi-tech');

-- Cross-Genre & Thematic Synergies
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (340901, 214755, 9, 'Good Match: Both present deeply unsettling predictions of reality and surveillance, wrapped in a high-concept mystery with huge emotional stakes.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (182955, 337814, 9, 'Good Match: A brilliant, tightly wound neo-noir mystery that matches perfectly with this intense, claustrophobic ride through corrupt policing.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (282452, 73913, 8, 'Good Match: Explores the underground grind of poker bluffs, making it a fantastic companion to this cold, calculating look at a casino dealer.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (73913, 56304, 8, 'Good Match: Moves from the detached perspective of the casino floor directly into the sweeping, violent epic of Vegas corruption.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (65764, 13978, 9, 'Good Match: A bizarre, highly disturbing exploration of conditioning that pairs brilliantly with a blistering look at the cycle of racial violence.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (13978, 48792, 9, 'Good Match: Both deliver scathing, visceral attacks on modern masculinity, using incredibly uncomfortable themes and jaw-dropping twists.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (48792, 238695, 9, 'Good Match: Swaps the violent, jaw-dropping twist of Fight Club for a hilarious, painfully accurate takedown of soul-crushing cubicles.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (345690, 311038, 9, 'Good Match: A grounded, melancholic look at the superhero genre that perfectly complements the painful struggle between a personal life and duty.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (311038, 30955, 9, 'Good Match: Both define their respective eras of comic book cinema, anchored by phenomenal dark, gothic architecture and character struggles.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (30955, 97727, 9, 'Good Match: Tim Burton''s dark, gothic architecture of Gotham shines just as brightly in this beautifully tragic gothic fairytale with incredible makeup.', 'orizehavi-tech');

-- Adventure & Fantasy Synergies
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (133725, 313601, 9, 'Good Match: The benchmark for adventure cinema packed with traps pairs wonderfully with this fun mix of Egyptian mythology and sci-fi.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (313601, 102108, 8, 'Good Match: Both successfully launched massive franchises by blending grand mythology with a perfect swashbuckling comedy adventure.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (102108, 170522, 8, 'Good Match: The brilliant mix of pirate lore and comedy matches the wildly entertaining, chaotic board game adventure with fantastic practical effects.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (170522, 133725, 9, 'Good Match: Takes the chaotic, jungle-themed practical effects of Jumanji and grounds them in the non-stop pacing of the ultimate treasure hunt.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (139657, 139655, 9, 'Good Match: Captures the childish wonder of discovering magic, preparing you for the fantastic shift to a darker, more mature tone in the sequel.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (139655, 100447, 9, 'Good Match: A brilliant fantasy that uses practical effects and amazing costume design, echoing the darker, brilliant time travel mechanics of Azkaban.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (100447, 169393, 8, 'Good Match: A highly unique fantasy with stunning costumes that shares the laid-back, magical journey vibe of traversing a magical forest.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (335245, 208245, 8, 'Good Match: Both are highly stylized westerns, blending iconic shootouts and infinitely quotable dialogue with poker bluffs and charm.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (208245, 297382, 8, 'Good Match: A highly entertaining western comedy that seamlessly flows into this very fun blending of classic tropes and martial arts choreography.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (297382, 335245, 8, 'Good Match: While one leans on martial arts comedy, both successfully execute classic western tropes with incredibly entertaining set pieces.', 'orizehavi-tech');

-- ==========================================
-- 100 FALSE POSITIVES / TRAPS (Scores 1-3)
-- ==========================================

-- Terrible Sequels & Franchise Drops
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (27132, 27171, 2, 'False Positive: While you enjoyed the stylish buddy-cop formula of the first, the sequel is bloated and prioritizes explosions over character.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (30955, 30952, 1, 'Trap: The dark gothic architecture of 89 is entirely replaced by a neon-soaked disaster with painful dialogue and bizarre costumes.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (210739, 210741, 2, 'False Positive: The crisp, fast-paced extraterrestrial wit of the original is abandoned for a loud, flashy, and ultimately hollow spectacle.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (100138, 313474, 2, 'Trap: Swaps the bleak, character-driven masterpiece featuring the most shocking reveal for sleep-inducing political trade disputes.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (201516, 207989, 3, 'False Positive: The bullet-time effects that rewrote action cinema are still here, but the exhausting philosophical dialogue drags the sequel down.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (291221, 289666, 2, 'Misleading Match: Scream is a brilliant, self-aware dissection of slasher tropes, while Scary Movie relies entirely on crude humor that loses appeal quickly.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (310726, 7048, 1, 'Genre Clash: Speed is a brilliant high-concept action thriller; Mary-Kate & Ashley''s volcano mystery is a cheesy, scientifically ridiculous kids film.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (161481, 19054, 1, 'Trap: The harrowing beach landings and sheer cinematic achievement of Saving Private Ryan have absolutely nothing in common with this vocal-driven curiosity.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (113504, 81954, 2, 'False Positive: Both feature heavy water themes, but Nemo is a stunning emotional road-trip while Waterworld is a wildly ambitious but struggling epic.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (188507, 188511, 3, 'Trap: The chemistry that set the standard for the genre in the original starts to show serious age and fatigue by the fourth installment.', 'orizehavi-tech');

-- Same Actor/Director, Awful Match
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (32166, 30952, 1, 'False Positive: Both feature sweeping castle/gothic aesthetics, but a magical flawless romance is ruined by unbearable ice puns and neon suits.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (166917, 214755, 3, 'Trap: Both star Tom Cruise, but the genuine emotional stakes of a sports agency clash horribly with a dark, precrime futuristic mystery.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (131665, 238072, 3, 'False Positive: Matt Damon stars in both, but the deeply moving script exploring trauma does not fit the breezy, cool heist tone of Ocean''s.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (313059, 194204, 2, 'Genre Clash: You enjoyed the beautifully nostalgic childhood friendships of Stand By Me; pivoting to a masterful but horrifying demonic pregnancy is a bad idea.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (130128, 37178, 2, 'Trap: Both are classics, but the operatic tragedy of the organized crime genre doesn''t mix with a surreal, weed-fueled bowling comedy.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (289558, 170522, 1, 'False Positive: Recommending a chaotic kids board game adventure to someone who just enjoyed an unapologetic, violently explosive mob film is absurd.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (134672, 262645, 1, 'Genre Clash: A brilliant time loop comedy philosophically exploring reality is the complete opposite of an invisible enemy hunting commandos in the jungle.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (9125, 18979, 2, 'Trap: Aviation themes don''t equal similarity. A relentless barrage of visual gags is totally at odds with the intense engineering crises of Apollo 13.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (13789, 158999, 2, 'False Positive: The melancholic masterpiece highlighting the quiet desperation of suburban life is utterly destroyed by iconic global destruction sequences.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (48792, 195300, 1, 'Genre Clash: A scathing, visceral attack on consumerism and masculinity cannot be followed by a warm, genuinely funny holiday rom-com.', 'orizehavi-tech');

-- Genre Trap (Looks similar, entirely different)
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (1711, 310184, 2, 'Trap: Just because both are in space doesn''t make them a match. You praised 2001 for realistic terror, which Spaceballs lovingly spoofs into silliness.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (2000, 300229, 1, 'False Positive: Both feature isolation and survival, but terrifying, fast-moving infected zombies do not pair with a hilarious deconstruction of fairy tales.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (129185, 24430, 1, 'Genre Clash: The epic scope and tragic betrayal of Rome has absolutely zero crossover with a colorful, ridiculous spoof of 60s spy movies.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (333856, 81954, 2, 'Trap: Epic water disasters are here, but Titanic''s unmatched production scale and romance overshadows the bloated, struggling post-apocalyptic setting.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (290070, 245008, 1, 'False Positive: An absolute tonal disaster to pair a monumental achievement in historical Holocaust drama with a surprisingly sweet snowboarding teen comedy.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (44450, 335834, 3, 'Trap: Both are military films, but the harrowing emotional aftermath of war heavily clashes with the high-energy, unapologetic love letter to fighter pilots.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (56304, 208245, 3, 'False Positive: Gambling is the link, but the meticulously organized violent mechanics of Vegas don''t gel with a highly entertaining western poker comedy.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (42983, 280478, 3, 'Trap: Both tackle toxic finance bro culture, but Boiler Room is a crisp, high-energy critique while Rogue Trader is a dark, fascinating but flawed exploration.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (111442, 13978, 1, 'Genre Clash: The pure chaos and fun of cutting class in high school is the tonal antithesis of a blistering, uncomfortable look at the cycle of racism.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (104338, 107166, 2, 'Trap: Identity is the theme, but a visually inventive exploration of heartbreak cannot be paired with a bizarre concept driven by non-stop ridiculous action.', 'orizehavi-tech');

-- Superficial Connections
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (97727, 40187, 2, 'False Positive: Blades and gothic tones are shared, but a beautifully tragic fairytale with incredible makeup clashes with a slick, stylized vampire hunter.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (847, 281334, 1, 'Genre Clash: A fun, fast-paced London dog rescue mission has nothing to do with a sharp, realistic thriller focusing on precise mercenary car chases.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (18441, 10830, 2, 'Trap: Bugs and hives link them, but a cynical animated take on conformity is a terrible match for the ultimate haunted house movie set in space.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (61291, 39551, 1, 'False Positive: A brilliantly executed claymation homage to POW escapes does not prepare you for a visceral, documentary-style descent into urban warfare.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (96590, 262645, 2, 'Trap: Alien visitors are in both, but the brilliant suburban sci-fi magic of the bicycle scene does not map to an invisible enemy ripping spines in the jungle.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (32166, 215346, 1, 'Genre Clash: Captivity is the core, but a flawless, magical romance is the polar opposite of a horrifyingly grounded psychological thriller about fandom.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (258860, 113504, 2, 'False Positive: Ocean environments don''t make them similar. Adrenaline-fueled surfing heist action clashes with a visually stunning animated road-trip.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (209133, 124554, 2, 'Trap: Social stratification links them, but a razor-sharp teen clique comedy is completely different from a sweeping, ambitious genetic sci-fi epic.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (375827, 101462, 1, 'Genre Clash: A meta-comedy breaking down the absurdity of the modeling industry shares zero DNA with a fascinating historical look at code-breaking.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (345690, 30952, 2, 'False Positive: The grounded, melancholic look at the superhero genre is ruined by transitioning to a campy, neon-soaked disaster with unbearable ice puns.', 'orizehavi-tech');

-- Pacing & Style Clashes
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (210509, 274589, 1, 'Trap: The genius reverse storytelling of an amnesiac requires patience, which is totally lost in an escalated, banter-heavy comedy action sequel.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (78787, 115106, 1, 'Genre Clash: A bizarre, highly original sci-fi concept with dark humor has nothing in common with a highly energetic dance movie reliant on musical sequences.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (254943, 169393, 1, 'False Positive: A frantic, black-and-white dive into paranoia is the worst possible follow-up to a laid-back, jazzy journey through the forest.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (129369, 300229, 1, 'Trap: The dark, foul-mouthed masterclass exposing the desperation of salesmen shares no audience with a hilarious deconstruction of fairy tales.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (271192, 41409, 1, 'Genre Clash: A sensitive, moving cross-country journey about brotherhood is completely incompatible with the ultimate tournament fighting movie choreography.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (337404, 310184, 1, 'False Positive: A sprawling narrative exploring the devastating impact of the drug trade cannot be paired with a lovingly silly spoof of space operas.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (182955, 274594, 1, 'Trap: A tightly wound neo-noir mystery exploring 1950s police corruption does not match the boundary-pushing gross-out humor of a sweet comedy.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (90771, 644, 2, 'Genre Clash: The severe psychological toll of deep undercover mafia work is a jarring shift to a sharp and clever high school Shakespeare adaptation.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (131780, 32166, 1, 'False Positive: The frantic editing and violent reality of the mafia lifestyle is the polar opposite of a flawless, magical animated romance.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (297838, 48950, 2, 'Trap: A quiet, powerful testament to the triumph of the human spirit in prison does not translate to a charming, miniature epic about an insect colony.', 'orizehavi-tech');

-- Setting Match, Tone Completely Off
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (101055, 313474, 2, 'False Positive: Both feature large-scale wars, but raw sniper deception and patience is a far cry from the visual effects and boring trade disputes of Naboo.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (161481, 24430, 1, 'Trap: The harrowing beach landing sequence and sheer cinematic trauma has zero overlap with a colorful, ridiculous spoof of 60s spy movies.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (335245, 289666, 1, 'Genre Clash: A highly stylized western with infinitely quotable dialogue shouldn''t be paired with a parody that relies entirely on crude shock value.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (208245, 65764, 1, 'False Positive: A highly entertaining western comedy built on poker bluffs clashes violently with a bizarre, highly disturbing exploration of free will.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (133725, 27171, 2, 'Trap: The benchmark for adventure cinema packed with traps is vastly superior to an overly long, bloated sequel that prioritizes explosions over character.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (207390, 176711, 2, 'Genre Clash: The meticulous historical naval warfare strategy is completely at odds with a visually stunning, hyper-violent technical achievement in revenge.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (313601, 13978, 1, 'False Positive: A fun mix of Egyptian mythology and sci-fi is a terrible segue into a blistering, uncomfortable look at the roots of racism.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (336458, 362808, 1, 'Trap: A hyper-violent, deeply weird trip to Mars relying on practical gore has absolutely nothing in common with the iconic dialogue of a romantic comedy.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (158999, 279420, 1, 'Genre Clash: The global destruction sequences and popcorn entertainment of aliens clash horribly with a beautifully shot, grim mobster tale of fathers and sons.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (73436, 218415, 1, 'False Positive: A masterclass in terrifying nuclear launch protocol tension should never be paired with a corporate satire about monsters collecting screams.', 'orizehavi-tech');

-- Plot Similarities, Executed Poorly
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (194497, 7048, 1, 'Trap: Both involve journeys to volcanoes, but an emotionally exhausting fantasy epic is insulted by being paired with a cheesy, scientifically ridiculous kids mystery.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (340799, 312138, 3, 'False Positive: Both are spy films, but the brilliant, explosive domestic comedy is completely tonally different from the slow-burn extraction politics of Spy Game.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (86274, 72430, 3, 'Genre Clash: You praised the tightest action script ever written in Die Hard; the battleship knockoff is decent, but lacks the same masterful pacing.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (111813, 94958, 1, 'Trap: The explosive courtroom scenes and razor-sharp dialogue of a military trial have zero connection to literal explosions in a video game adaptation.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (238695, 358708, 3, 'False Positive: Both dissect the workplace, but a hilarious takedown of soul-crushing cubicles doesn''t fit the cold-blooded examination of 80s insider trading.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (149388, 140783, 3, 'Genre Clash: Basketball connects them, but the pure teamwork of an underdog story clashes with a powerful exploration of the intense exploitation of prodigies.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (280270, 41739, 3, 'Trap: Sports films, yes, but a deeply moving character study about an underdog boxer feels entirely different from a gritty look at corrupt college recruitment.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (282452, 73913, 3, 'False Positive: Both center on casinos and cards, but the underground passion of Texas Hold em is completely contrary to the detached, calculating look of a dealer.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (68940, 105723, 3, 'Genre Clash: Plane hijackings unify them, but absurd practical fun and chaotic set pieces are very different from a tense, slow-burn bureaucratic thriller.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (310726, 131223, 3, 'Trap: Vehicular action is the draw, but a brilliant high-concept premise that never slows down is superior to a fun but slightly mindless fast car chase.', 'orizehavi-tech');

-- Forced Connections
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (313059, 90772, 2, 'False Positive: Coming of age stories, but the touching, nostalgic innocence of childhood friendships is ruined by a moody, complex dive into time-travel angst.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (333393, 104338, 2, 'Trap: Memory and time manipulation link them, but fun sci-fi action fight scenes are completely detached from a visually inventive exploration of heartbreak.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (155634, 210741, 1, 'Genre Clash: A highly atmospheric whodunit with a genuinely surprising psychological twist shares nothing with a loud, flashy, and ultimately hollow spectacle.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (118393, 109608, 1, 'False Positive: Romance is central, but a sharp episodic comedy that nails social gatherings is the opposite of an intensely uncomfortable look at obsession.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (87280, 48792, 1, 'Trap: The choreography of classic romance and dancing doesn''t align with a visceral, violent attack on consumerism and modern masculinity.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (210739, 10830, 2, 'Genre Clash: Aliens exist in both, but the crisp extraterrestrial bureaucracy of one is entirely incompatible with the terrifying chest-bursters of the other.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (102108, 333856, 3, 'False Positive: Boats are involved, but a perfect swashbuckling comedy adventure clashes with a sweeping historical drama balancing epic romance and disaster.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (194502, 100447, 3, 'Trap: Fantasy epics, but the sheer massive scale of the Rohan battles makes a highly unique but much smaller-scale practical effects fantasy feel out of place.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (122658, 10920, 3, 'Genre Clash: Military women in focus, but a gritty exploration of extreme psychological abuse in training doesn''t match a high-octane sci-fi action masterpiece.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (91763, 65501, 3, 'False Positive: Both are thrillers, but a highly satisfying revenge story revolving around legal loopholes is very different from slow-burn bureaucratic backstabbing.', 'orizehavi-tech');

-- Complete Opposites & Final Mixed Bag Traps
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (195300, 65764, 1, 'Trap: Weaving together storylines into a warm holiday classic is the exact opposite of a bizarre, highly disturbing exploration of behavioral conditioning.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (192013, 289558, 1, 'Genre Clash: Timeless, perfect animated musical numbers of a mermaid share zero demographic overlap with an unapologetic, violently explosive look at the drug trade.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (300229, 131780, 1, 'False Positive: A hilarious deconstruction of fairy tales packed with jokes has absolutely nothing to do with the frantic editing and terrifying reality of the mafia.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (173930, 254943, 1, 'Trap: The ultimate underdog martial arts story with a fantastic mentor dynamic clashes entirely with a frantic, black-and-white dive into obsessive paranoia.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (9795, 215346, 1, 'Genre Clash: The manic, magical energy of the Genie elevates animation, which makes for a terrible pairing with a horrifyingly grounded psychological thriller.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (218415, 129369, 1, 'False Positive: Turning childhood fears into a brilliant corporate satire with huge heart doesn''t map to a foul-mouthed masterclass exposing desperate salesmen.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (113504, 337404, 1, 'Trap: A visually stunning underwater road-trip about letting go of fear is horribly mismatched with a sprawling narrative exploring the devastating drug trade.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (32166, 340799, 1, 'Genre Clash: A flawless, magical romance that truly earns its classic status has nothing in common with a brilliant, explosive blend of domestic comedy and espionage.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (190869, 182955, 1, 'False Positive: A wonderfully weird animated film about finding family completely clashes with a tightly wound neo-noir mystery exploring 1950s police corruption.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (847, 210509, 1, 'Trap: The sketchy art style of a fun, fast-paced London rescue mission is totally at odds with forcing the audience into the shoes of an amnesiac.', 'orizehavi-tech');
-- ==========================================
-- 10 MISSING FALSE POSITIVES / TRAPS (Scores 1-3)
-- ==========================================

INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (340901, 358708, 2, 'Trap: Both deal with systems manipulating people, but the touching personal drama of Truman completely clashes with the cold-blooded corporate greed of Wall Street.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (362808, 2000, 1, 'Genre Clash: The slow-burn iconic romantic comedy spanning a decade has absolutely nothing in common with terrifying fast-moving infected zombies.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (345690, 847, 1, 'False Positive: A grounded melancholic superhero origin story is a terrible follow-up to a fun, fast-paced animated dog rescue mission.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (1711, 1029, 1, 'Trap: A cinematic masterpiece of realistic space exploration should never be paired with a bizarre supernatural ghosts romance.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (2000, 644, 1, 'Genre Clash: You praised the clever high school Shakespeare adaptation, which shares zero demographic overlap with a terrifying infection thriller.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (340799, 362808, 2, 'False Positive: Romance and comedy are the only links, but explosive high-stakes espionage drastically clashes with a slow-burn dialogue-driven romantic comedy.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (358708, 847, 1, 'Trap: A cold-blooded examination of 80s insider trading is completely inappropriate for someone looking for a fun London animal rescue adventure.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (345690, 1029, 2, 'Genre Clash: Melancholic comic book themes of duty and family do not mix well at all with a supernatural romance atmosphere.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (1711, 644, 1, 'False Positive: The pioneering realism and terrifying silence of space travel has zero crossover with sharp and clever teen high school dynamics.', 'orizehavi-tech');
INSERT INTO recommendations (movie1_id, movie2_id, recommendation_score, justification, suggested_by) VALUES (340901, 2000, 2, 'Trap: The unsettling prediction of reality TV culture is a deeply touching personal drama, completely at odds with the sheer adrenaline and terror of a zombie apocalypse.', 'orizehavi-tech');