insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (383749, 10, 'talh2000', 'This movie is so upsetting and it really shocks your soul.', null); # 383749 Requiem for a Dream
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (389016, 10, 'talh2000', 'The soundtrack is amazing and fits the fast driving scenes.', null); # 389016 Baby Driver
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (426661, 10, 'talh2000', 'The drum music makes the whole movie feel so tense and exciting.', null); # 426661 Whiplash
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300230, 10, 'talh2000', 'I love this sequel. The funny songs make it a joy to watch.', null); # 300230 Shrek 2
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300229, 7, 'talh2000', 'A very funny movie that makes fun of old stories in a cool way.', null); # 300229 Shrek 1
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30959, 8, 'talh2000', 'The best way to show how Batman started. It feels real.', null); # 30959 Batman Begins
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (396440, 9, 'talh2000', 'The techno music fits the digital world and action perfectly.', null); # 396440 The Matrix
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (402221, 10, 'talh2000', 'The loud brass music makes every dream scene feel so heavy.', null); # 402221 Inception
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (333856, 8, 'talh2000', 'A very sad love story. The moving flute music made me sad.', null); # 333856 Titanic
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210511, 8, 'talh2000', 'The story moves backwards and it is very smart and unique.', null); # 210511 Memento
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (112290, 8, 'talh2000', 'A wild movie with a big surprise that makes you think.', null); # 112290 Fight Club
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (267038, 10, 'talh2000', 'The retro songs fit the cool vibe of the movie perfectly, most iconic Tarantino film.', null); # 267038 Pulp Fiction
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131780, 9, 'talh2000', 'A great look at mob life. The period songs fit the era well.', null); # 131780 Goodfellas
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (81669, 10, 'talh2000', 'The organ music is so huge and epic for the space scenes.', null); # 81669 Interstellar
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (290070, 10, 'talh2000', 'A very sad story. The violin music is truly heartbreaking.', null); # 290070 Schindler\'s List
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (337166, 9, 'talh2000', 'A classic that I loved as a kid and still enjoy today.', null); # 337166 Toy Story
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10830, 8, 'talh2000', 'A scary space movie. The silence makes it feel very lonely.', null); # 10830 Alien
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (201538, 9, 'talh2000', 'All the old pop songs make this hero story so much fun.', null); # 201538 Guardians of the Galaxy
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10920, 8, 'talh2000', 'Action at its best and more exciting than the first one.', null); # 10920 Aliens
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (297838, 10, 'talh2000', 'A beautiful story about having a real friend in prison.', null); # 297838 Shawshank Redemption
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (40199, 7, 'talh2000', 'The dark synth music fits this future city vibe perfectly.', null); # 40199 Blade Runner
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46169, 9, 'talh2000', 'Big battles and a strong story about fighting for freedom.', null); # 46169 Braveheart
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335835, 8, 'talh2000', 'Fast planes and cool rock songs that make you feel the speed.', null); # 335835 Top Gun
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (326155, 7, 'talh2000', 'A dark story about a lonely man. The city feels very dirty.', null); # 326155 Taxi Driver
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159172, 9, 'talh2000', 'The adventure music and the jokes make this a perfect movie.', null); # 159172 Indiana Jones Last Crusade
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (271095, 8, 'talh2000', 'The trumpet theme is famous and makes scenes feel exciting.', null); # 271095 Raiders of the Lost Ark
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313478, 9, 'talh2000', 'A great sequel with a big secret and iconic hero music.', null); # 313478 Star Wars: Empire Strikes Back
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313479, 8, 'talh2000', 'A satisfying ending to the original story with a lot of heart.', null); # 313479 Star Wars: Return of the Jedi
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (413882, 9, 'talh2000', 'The whistling music in the desert makes this feel so cool.', null); # 413882 Good Bad Ugly
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188507, 8, 'talh2000', 'The saxophone music really fits the cool cop vibe of the eighties.', null); # 188507 Lethal Weapon
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188509, 8, 'talh2000', 'A great action sequel that keeps the same high energy.', null); # 188509 Lethal Weapon 2
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (110352, 10, 'talh2000', 'A stylish hitman story. The sad song at the end is perfect.', null); # 110352 Leon: The Professional
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139657, 7, 'talh2000', 'The magical music theme makes you feel like you are there.', null); # 139657 Harry Potter 1
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (405551, 8, 'talh2000', 'The simple piano notes are so scary and iconic for horror.', null); # 405551 Halloween
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139655, 8, 'talh2000', 'My favorite in the series. The style and the music are cool.', null); # 139655 Harry Potter 3
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (411661, 10, 'talh2000', 'The opening song is one of the best moments in any cartoon.', null); # 411661 The Lion King
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (319602, 8, 'talh2000', 'The classic hero music makes you believe he can really fly.', null); # 319602 Superman
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (97727, 9, 'talh2000', 'A beautiful but sad story. The pretty music fits it well.', null); # 97727 Edward Scissorhands
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30955, 8, 'talh2000', 'A dark and cool Batman. The music by Danny Elfman is great.', null); # 30955 Batman 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (406661, 9, 'talh2000', 'A very dark story. The slow cello sounds so sad and deep.', null); # 406661 Joker
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311038, 9, 'talh2000', 'The best Spider-Man movie. It shows the hard hero life.', null); # 311038 Spider-Man 2
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (397441, 9, 'talh2000', 'The classic slow music makes the whole story feel grand.', null); # 397441 The Godfather
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (423881, 8, 'talh2000', 'The drum beat in the back sounds just like a heartbeat.', null); # 423881 Birdman
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215876, 8, 'talh2000', 'A cool spy movie with a theme song that everyone knows.', null); # 215876 Mission: Impossible
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256632, 9, 'talh2000', 'The pirate music is fun and makes the adventure better.', null); # 256632 Pirates of Caribbean
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (420551, 10, 'talh2000', 'The bagpipes in the soundtrack make the battles feel huge.', null); # 420551 Braveheart
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (123435, 9, 'talh2000', 'A clever movie that keeps you guessing. Very tense and cool.', null); # 123435 Game, The
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56304, 9, 'talh2000', 'A fast look at the bad side of Vegas with a cool soundtrack.', null); # 56304 Casino
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (428882, 9, 'talh2000', 'A very sad story. The quiet music makes it feel more real.', null); # 428882 Manchester by Sea
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (430551, 8, 'talh2000', 'The fast Irish rock music fits the city action perfectly.', null); # 430551 The Departed
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (65811, 10, 'talh2000', 'The five music notes are so famous and work perfectly.', null); # 65811 Close Encounters
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (427221, 10, 'talh2000', 'The piano songs are beautiful and make the story sad.', null); # 427221 The Pianist
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (385449, 9, 'talh2000', 'The loud drum music makes the car chases feel intense.', null); # 385449 Mad Max: Fury Road
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (387221, 10, 'talh2000', 'The desert theme music is grand and sounds amazing.', null); # 387221 Lawrence of Arabia
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (413331, 9, 'talh2000', 'The rhythmic songs in the army scenes feel strong.', null); # 413331 Full Metal Jacket
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (70959, 8, 'talh2000', 'A dark but sweet story. The songs fit the style well.', null); # 70959 Corpse Bride
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (74259, 8, 'talh2000', 'A funny take on old movies. The music is high energy.', null); # 74259 Cry-Baby
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (389801, 9, 'talh2000', 'The slow violin soundtrack is beautiful and very sad.', null); # 389801 In the Mood for Love
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (66194, 8, 'talh2000', 'A smart and funny look at school life. The songs are great.', null); # 66194 Clueless
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (644, 8, 'talh2000', 'A fresh and fun version of an old story with good music.', null); # 644 10 Things I Hate About You
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (402771, 10, 'talh2000', 'The ticking clock sound in the music makes it very tense.', null); # 402771 Interstellar
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (67395, 9, 'talh2000', 'The gospel songs make the story feel very emotional.', null); # 67395 Color Purple
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (414441, 9, 'talh2000', 'The weird high noises in the music make this movie creepy.', null); # 414441 The Shining
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (426112, 8, 'talh2000', 'The hero theme music is light and fun, just like the movie.', null); # 426112 Ant-Man
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313504, 9, 'talh2000', 'The Imperial March is so cool and very scary for a movie.', null); # 313504 Star Wars 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (424991, 10, 'talh2000', 'A dark look at a future world with very moody music.', null); # 424991 Blade Runner 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (431111, 9, 'talh2000', 'A long mob story. The songs help show the time passing.', null); # 431111 The Irishman
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311040, 5, 'talh2000', 'Too many bad guys and the story felt a bit messy to me.', null); # 311040 Spider-Man 3
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30952, 2, 'talh2000', 'This was just a bad movie. It felt like a joke gone wrong.', null); # 30952 Batman & Robin
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238073, 5, 'talh2000', 'It was okay but felt a bit too messy compared to the first.', null); # 238073 Oceans Twelve
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (220805, 5, 'talh2000', 'Lots of action and shooting but the story was very simple.', null); # 220805 Mr. and Mrs. Smith
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188511, 6, 'talh2000', 'Still okay but there was too much going on in the story.', null); # 188511 Lethal Weapon 4
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (149287, 6, 'talh2000', 'A different take on Peter Pan. It was a nice family movie.', null); # 149287 Hook
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (379290, 8, 'talh2000', 'A cool old Batman cartoon. It sounds just like the 60s.', null); # 379290 Batman 1969
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (383236, 9, 'talh2000', 'A story told with no words. The music is very important.', null); # 383236 Quest for Fire
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (403881, 9, 'talh2000', 'A wild look at greed. The party songs are high energy.', null); # 403881 Wolf Wall Street
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (419442, 8, 'talh2000', 'A cool and stylish take on spy stories. Fun pop songs.', null); # 419442 Kingsman
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (113506, 9, 'talh2000', 'A very pretty movie about dreams and the Peter Pan creator.', null); # 113506 Finding Neverland
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (123849, 9, 'talh2000', 'The old city sounds and music make it feel very real.', null); # 123849 Gangs of New York
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185628, 9, 'talh2000', 'The Japanese flute music makes the battles look epic.', null); # 185628 The Last Samurai
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (220276, 9, 'talh2000', 'The songs are amazing. It is a very pretty movie to see.', null); # 220276 Moulin Rouge!
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280270, 10, 'talh2000', 'The trumpet music in the training is very famous and good.', null); # 280270 Rocky 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (359297, 9, 'talh2000', 'The scary horn sound in the movie is very terrifying.', null); # 359297 War of the Worlds
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (372233, 8, 'talh2000', 'Bond in Japan. The soundtrack is actually very pretty.', null); # 372233 You Only Live Twice
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (406411, 8, 'talh2000', 'The war sounds in the cartoons are very well done.', null); # 406411 Star Wars Clone Wars
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (450, 7, 'talh2000', 'The sound of the clock is very tense in this one.', null); # 450 ...tick...tick...tick...
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (1038, 9, 'talh2000', 'The 80s songs are amazing in this very fun comedy.', null); # 1038 13 Going On 30
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (1121, 8, 'talh2000', 'The epic Vangelis music is just incredible to hear.', null); # 1121 1492: Conquest of Paradise
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280281, 9, 'talh2000', 'The trumpet theme is still so strong and good here.', null); # 280281 Rocky II
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280282, 8, 'talh2000', 'The Eye of the Tiger song is just perfect for this.', null); # 280282 Rocky III
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (401111, 9, 'talh2000', 'A big finish for the hero. The drums are very powerful.', null); # 401111 Dark Knight Rises
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311037, 8, 'talh2000', 'A good start for Spider-Man. It felt just like the comics.', null); # 92. 311037 Spider-Man 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (160524, 8, 'talh2000', 'A tense thriller where the sun never goes down. Cool.', null); # 160524 Insomnia
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (123435, 9, 'talh2000', 'A clever movie that keeps you guessing. Very tense.', null); # 123435 Game, The
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (209158, 9, 'talh2000', 'A raw story about guys in a rough city. Good acting.', null); # 209158 Mean Streets
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (65811, 10, 'talh2000', 'The simple five music notes are so famous and work.', null); # 65811 Close Encounters
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (34104, 8, 'talh2000', 'A sweet and odd story about love. It has heart.', null); # 34104 Benny & Joon
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (304862, 8, 'talh2000', 'A dark scary story. The music makes it feel spooky.', null); # 304862 Sleepy Hollow
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (59578, 7, 'talh2000', 'A colorful candy factory. The songs are fun for kids.', null); # 59578 Charlie Chocolate Factory
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139650, 8, 'talh2000', 'Darker and more exciting. The magic world looks great.', null); # 139650 Harry Potter 2
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (350424, 7, 'talh2000', 'A strange story about dreams. The songs are very moody.', null); # 350424 Vanilla Sky
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (66194, 8, 'talh2000', 'A smart and funny look at school life. The songs are great.', null); # 66194 Clueless
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (137523, 9, 'talh2000', 'The gritty rock songs in the background fit the vibe.', null); # 137523 Fight Club (Alt ID)
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120506, 8, 'talh2000', 'A dark mystery set in old London. Very tense vibe.', null); # 120506 From Hell
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (247579, 8, 'talh2000', 'A tense thriller in one house. The sound design is good.', null); # 247579 Panic Room
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (69812, 7, 'talh2000', 'A fun movie about secret plots and mystery. Exciting.', null); # 69812 Conspiracy Theory
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (181766, 8, 'talh2000', 'A very pretty movie that takes its time to tell the story.', null); # 181766 Kundun
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185704, 8, 'talh2000', 'A bold story that really makes you think about things.', null); # 185704 Last Temptation of Christ
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (328272, 8, 'talh2000', 'A nice story about a man stuck in an airport. Sweet.', null); # 328272 Terminal, The
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (318388, 8, 'talh2000', 'A fast road movie with a lot of soul and heart.', null); # 318388 Sugarland Express
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (183873, 8, 'talh2000', 'A nice magic story from long ago. The vibe was good.', null); # 183873 Ladyhawke
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311428, 8, 'talh2000', 'A funny story with a lot of charm. The music is light.', null); # 311428 Splash
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (114955, 8, 'talh2000', 'A good story about growing up. It has a summer feeling.', null); # 114955 Flamingo Kid
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (235615, 8, 'talh2000', 'A serious look at a family. The dialogue is well written.', null); # 235615 Nothing in Common
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (31715, 8, 'talh2000', 'A sad and beautiful story about friends over years.', null); # 31715 Beaches
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (308025, 8, 'talh2000', 'A cool look for the city. It has a very tense feeling.', null); # 308025 Someone to Watch Over Me
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210739, 9, 'talh2000', 'Fun with cool aliens. The music makes it high energy.', null); # 210739 Men in Black
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (158999, 8, 'talh2000', 'A huge movie about aliens. The action is very big.', null); # 158999 Independence Day
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (14477, 8, 'talh2000', 'A tough and important story. The acting is powerful.', null); # 14477 Amistad
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (330670, 8, 'talh2000', 'A real story with great acting. It feels grounded.', null); # 330670 This Boys Life
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (118980, 8, 'talh2000', 'A sweet story with stars. The music is very nice.', null); # 118980 Frankie and Johnny
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (208245, 8, 'talh2000', 'A fast and fun western trip. The music is upbeat.', null); # 208245 Maverick
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (379327, 9, 'talh2000', 'A classic adventure with very bright and fun colors.', null); # 123. 379327 Robin Hood 1955
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311036, 7, 'talh2000', 'A cool hero cartoon. I liked the funny sound effects.', null); # 311036 Spider-Man 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (333849, 7, 'talh2000', 'A very old version of the sad ship story. Classic.', null); # 333849 Titanic 1915
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (370017, 8, 'talh2000', 'High energy action. The rock music is very loud.', null); # 370017 XXX 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (375745, 7, 'talh2000', 'A funny story from Ireland. I liked the fun vibe.', null); # 375745 Zonad 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (399427, 8, 'talh2000', 'Spooky stories. The opening music is very creepy.', null); # 399427 Night Gallery 1970
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (406759, 8, 'talh2000', 'A nice look at art. The music was very soft.', null); # 406759 Strokes of Genius 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (2, 8, 'talh2000', 'A cool old action movie. The music is very 70s.', null); # 2 $ 1971
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (12, 7, 'talh2000', 'A very old mystery. It is interesting to see now.', null); # 12 $20,000 Carat
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (15, 6, 'talh2000', 'A small movie from the 90s. I liked the vibe.', null); # 15 $30 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (18, 6, 'talh2000', 'A classic story. It was fun to watch once.', null); # 18 $40,000 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (33, 6, 'talh2000', 'A robbery movie that was okay for its time.', null); # 33 $windle 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (51, 6, 'talh2000', 'A strange art movie. It looks very unique.', null); # 51 \'A\' 1965
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (121, 7, 'talh2000', 'A very old silent comedy. It is very funny.', null); # 121 High Sign 1921
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (315, 6, 'talh2000', 'A very short movie about life in the 70s.', null); # 315 (Now) 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (589, 7, 'talh2000', 'A fun old movie about kids having a trip.', null); # 589 1-2-3 Go! 1941
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (628, 8, 'talh2000', 'A very short story about a big war event.', null); # 139. 628 10 minuta 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (661, 7, 'talh2000', 'A music movie that I liked as a 90s fan.', null); # 140. 661 10,000 Maniacs
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (672, 8, 'talh2000', 'A tough story from South America. Very real.', null); # 141. 672 100 aos de perdn
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (724, 7, 'talh2000', 'A cool look at old scary movies and monsters.', null); # 142. 724 100 Years of Horror
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (850, 8, 'talh2000', 'I loved these songs when I was a small kid.', null); # 143. 850 101 Dalmatians Sing Along
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (870, 7, 'talh2000', 'A strange movie from Europe. I liked the music.', null); # 144. 870 101 Reykjavk
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (923, 8, 'talh2000', 'A sad documentary about a very famous day.', null); # 145. 923 11-22-63
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (1018, 7, 'talh2000', 'A smart story about the same day over again.', null); # 146. 1018 12:01 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (1390, 7, 'talh2000', 'A very loud and funny war movie. Crazy stuff.', null); # 147. 1390 1941 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (2986, 8, 'talh2000', 'A cool action movie with great fighting scenes.', null); # 148. 2986 7 jin gong 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (7842, 9, 'talh2000', 'A wild night in the city. The jazz is cool.', null); # 149. 7842 After Hours 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (9813, 8, 'talh2000', 'A fun game and movie story for the family.', null); # 150. 9813 Aladdin 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10945, 7, 'talh2000', 'The metallic sounds make it feel modern.', null); # 151. 10945 Alien 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280305, 5, 'talh2000', 'Not a great one. The music was okay though.', null); # 152. 280305 Rocky V 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (37, 7, 'talh2000', 'A cool mystery from Europe. I liked the vibe.', null); # 153. 37 \'24-25\' ne vozvrashchayetsya
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (47, 6, 'talh2000', 'A simple story about a car. It was okay.', null); # 154. 47 \'88 Dodge Aries
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (53, 9, 'talh2000', 'A very fast and fun action movie from Asia.', null); # 155. 53 \'A\' gai waak juk jaap
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (74, 6, 'talh2000', 'A decent movie about a single word. Okay.', null); # 156. 74 \'C\' Word, The
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (81, 5, 'talh2000', 'A very old race movie. A bit too slow for me.', null); # 157. 81 \'Columbia\' and \'Shamrock II\'
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (100, 6, 'talh2000', 'A strange art movie. The sounds were good.', null); # 158. 100 \'E\' 1981
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (152, 6, 'talh2000', 'A small 90s movie. I liked the urban feel.', null); # 159. 152 \'M\' Word
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (153, 7, 'talh2000', 'A nice story about music and life. Decent.', null); # 160. 153 \'Mad\' Boy
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (154, 5, 'talh2000', 'A very old silent short. Good for history.', null); # 161. 154 \'Make-Up\' Thief
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (167, 7, 'talh2000', 'A dark crime story. The music was very cool.', null); # 162. 167 \'Minagoroshi no uta\'
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (168, 6, 'talh2000', 'A standard action movie. It was fun to see.', null); # 163. 168 \'Ming wang xing\'
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (178, 6, 'talh2000', 'A pop music special. Good for the fans.', null); # 164. 178 \'N Sync Holiday
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (179, 7, 'talh2000', 'Great concert footage. The music was high energy.', null); # 165. 179 \'N Sync Live
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (180, 6, 'talh2000', 'A look at the band on tour. Fun for music fans.', null); # 166. 180 \'N Sync Making Tour
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (181, 6, 'talh2000', 'More band music. I liked the pop vibe of it.', null); # 167. 181 \'N Sync No Strings
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (182, 6, 'talh2000', 'Another music special. It was fun and bright.', null); # 168. 182 \'N Sync PopOdyssey
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (183, 6, 'talh2000', 'A concert in a cool place. Good pop songs.', null); # 169. 183 \'N Sync Atlantis
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (184, 7, 'talh2000', 'A funny story from Europe. I liked the humor.', null); # 170. 184 \'Ne gnstige Gelegenheit
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (244, 5, 'talh2000', 'A very short documentary. Good for history.', null); # 171. 244 \'Sloboda\' - Kula
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (253, 6, 'talh2000', 'A dark story from long ago. It was okay.', null); # 172. 253 \'t Is wreed in de wereld
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (254, 7, 'talh2000', 'A nice old romance. The music was very light.', null); # 173. 254 \'t Was een April
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (263, 6, 'talh2000', 'A standard love story from the 90s. Fine.', null); # 174. 263 \'Til There Was You
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (275, 7, 'talh2000', 'A funny comedy about three dads. Fun.', null); # 175. 275 \'Tong tatlong tatay
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (316, 6, 'talh2000', 'A strange art movie. The sounds were odd.', null); # 176. 316 (Ohne Titel)
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (318, 6, 'talh2000', 'A nice documentary about life and time.', null); # 177. 318 (Past Present Future)
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (321, 6, 'talh2000', 'A collection of short stories. Some good.', null); # 178. 321 (Stories from)
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (322, 5, 'talh2000', 'A very short movie. It was okay to watch.', null); # 179. 322 (T) 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (323, 6, 'talh2000', 'Another short story. The music was nice.', null); # 180. 323 (Un) 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (330, 5, 'talh2000', 'A math story. A bit hard to follow at first.', null); # 181. 330 +1 -1 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (338, 7, 'talh2000', 'A pretty look at a city by the sea. Nice.', null); # 182. 338 ...A Valparaso
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (365, 6, 'talh2000', 'A strange old short story. Very visual.', null); # 183. 365 ...borgnes sont rois
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (370, 8, 'talh2000', 'A very funny western movie. I liked it.', null); # 184. 370 Continuavano Trinità
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (387, 7, 'talh2000', 'A long story about life passing by. Deep.', null); # 185. 387 ...e la vita continua
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (411, 6, 'talh2000', 'A movie about politics. The talk was okay.', null); # 186. 411 Nice to Be Privileged
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (413, 6, 'talh2000', 'A strange animated story. Good music.', null); # 187. 413 Ja teeb trikke
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (494, 6, 'talh2000', 'A very old drama. It was okay for its time.', null); # 188. 494 Y los sueos pasan
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (499, 5, 'talh2000', 'A small movie from Spain. It was okay.', null); # 189. 499 ya no puede caminar
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (517, 7, 'talh2000', 'A cool future world. The music was techy.', null); # 190. 517 .hack//Quarantine
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (523, 6, 'talh2000', 'A romantic story with a lot of phone talk.', null); # 191. 523 0-600-Amor ya
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (576, 7, 'talh2000', 'A nice drama from Europe. Good acting.', null); # 192. 576 1 s a semmi
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (599, 5, 'talh2000', 'A historical documentary. A bit slow.', null); # 193. 599 1. maj 1960
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (618, 7, 'talh2000', 'Very funny sketches from old television.', null); # 194. 618 10 from Your Show
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (632, 6, 'talh2000', 'A travel story between cities. Nice music.', null); # 195. 632 10 Minuten Hamburg
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (641, 6, 'talh2000', 'A very short story about time. It was okay.', null); # 196. 641 10 Seconds
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (660, 6, 'talh2000', 'A nice old story about a cop. Very real.', null); # 197. 660 10,000 Kids and a Cop
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (671, 5, 'talh2000', 'A strange art performance. Not for me.', null); # 198. 671 Selbstverstmmelung
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (673, 6, 'talh2000', 'A cool crime movie. The action was fun.', null); # 199. 673 100 Bullets 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (674, 6, 'talh2000', 'A documentary about making a movie. Tense.', null); # 200. 674 100 Cameras Vision