INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (9795,32178,10,'galsasson4',NULL,'Both are iconic animated musicals from the same magical renaissance era.'); # Beauty and the Beast -> The Little Mermaid
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (9795,143526,9,'galsasson4',NULL,'Excellent pairing of classic hero-journey animations with great musical numbers.'); # Beauty and the Beast -> Hercules
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (9795,191246,10,'galsasson4',NULL,'The absolute peak of 90s animation, sharing similar themes of finding oneself.'); # Beauty and the Beast -> The Lion King
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (32178,191246,9,'galsasson4',NULL,'Two masterpieces of family entertainment with deep emotional resonance.'); # The Little Mermaid -> The Lion King
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (48950,113504,9,'galsasson4',NULL,'Both are brilliant early CGI films exploring vibrant secret worlds.'); # A Bug's Life -> Finding Nemo
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (48950,218415,8,'galsasson4',NULL,'Highly recommended for fans of imaginative, world-building animation.'); # A Bug's Life -> Monsters, Inc.
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (48950,337166,10,'galsasson4',NULL,'Perfect match; both pioneered 3D animation and focus on tiny, unseen communities.'); # A Bug's Life -> Toy Story
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (113504,158927,10,'galsasson4',NULL,'Representing the absolute golden age of their animation studio, blending action and heart.'); # Finding Nemo -> The Incredibles
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (113504,218415,9,'galsasson4',NULL,'Both center on unexpected bonds between unlikely caretakers and dependents.'); # Finding Nemo -> Monsters, Inc.
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (337166,337168,10,'galsasson4',NULL,'A flawless continuation of a beloved story with the exact same heart and humor.'); # Toy Story -> Toy Story 2
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (10916,10920,10,'galsasson4',NULL,'The perfect double feature of claustrophobic sci-fi horror and action.'); # Alien -> Aliens
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (10920,262645,9,'galsasson4',NULL,'Both are masterclasses in 80s sci-fi featuring elite squads hunted by deadly aliens.'); # Aliens -> Predator
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (10920,328277,10,'galsasson4',NULL,'Two of the greatest action sequels ever made by the same legendary director.'); # Aliens -> Terminator 2: Judgment Day
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (20371,79716,8,'galsasson4',NULL,'Both are massive, highly entertaining global disaster spectacles.'); # Armageddon -> The Day After Tomorrow
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (20371,155070,9,'galsasson4',NULL,'Iconic popcorn blockbusters where humanity fights total annihilation.'); # Armageddon -> Independence Day
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (79716,155070,8,'galsasson4',NULL,'Perfect for fans of extreme, large-scale cinematic destruction.'); # The Day After Tomorrow -> Independence Day
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (207992,207989,9,'galsasson4',NULL,'A direct, ambitious expansion of a groundbreaking cyberpunk universe.'); # The Matrix -> The Matrix Reloaded
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (207989,207991,8,'galsasson4',NULL,'The epic, action-packed conclusion to a sprawling sci-fi saga.'); # The Matrix Reloaded -> The Matrix Revolutions
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (214755,101070,9,'galsasson4',NULL,'Both are propulsive, paranoid thrillers about innocents hunted by surveillance systems.'); # Minority Report -> Enemy of the State
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (311037,311038,10,'galsasson4',NULL,'An incredible comic-book duology that defines modern superhero cinema.'); # Spider-Man -> Spider-Man 2
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (39551,289109,10,'galsasson4',NULL,'Both are visceral, highly realistic portrayals of intense, unrelenting combat.'); # Black Hawk Down -> Saving Private Ryan
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (39551,360480,9,'galsasson4',NULL,'Outstanding tactical depictions of soldiers trapped in brutal military scenarios.'); # Black Hawk Down -> We Were Soldiers
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (289109,360480,8,'galsasson4',NULL,'Both deliver sweeping, emotionally charged visions of modern warfare.'); # Saving Private Ryan -> We Were Soldiers
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (250746,46169,9,'galsasson4',NULL,'Massive historical epics featuring brutal combat and themes of righteous rebellion.'); # The Patriot -> Braveheart
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (250746,289109,8,'galsasson4',NULL,'Both highlight the agonizing personal cost of war amidst sweeping battles.'); # The Patriot -> Saving Private Ryan
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (46169,340652,8,'galsasson4',NULL,'Epic swords-and-sandals style battles with immense, awe-inspiring scale.'); # Braveheart -> Troy
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (340652,250746,8,'galsasson4',NULL,'Both feature charismatic leaders engaging in massive, era-defining conflicts.'); # Troy -> The Patriot
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (185628,46169,9,'galsasson4',NULL,'Sweeping historical dramas centered around honor, resistance, and epic warfare.'); # The Last Samurai -> Braveheart
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (185628,340652,8,'galsasson4',NULL,'Highly romanticized, large-scale cinematic battles set in the distant past.'); # The Last Samurai -> Troy
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (112290,210511,10,'galsasson4',NULL,'Both are dark, mind-bending thrillers featuring entirely unreliable narrators.'); # Fight Club -> Memento
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (112290,348944,9,'galsasson4',NULL,'Gritty 90s classics heavily reliant on iconic, reality-altering twist endings.'); # Fight Club -> The Usual Suspects
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (210511,350424,8,'galsasson4',NULL,'Fascinating explorations of fractured memory and subjective reality.'); # Memento -> Vanilla Sky
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (112290,350424,8,'galsasson4',NULL,'Both feature protagonists who slowly realize their reality is a psychological illusion.'); # Fight Club -> Vanilla Sky
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (182955,109093,8,'galsasson4',NULL,'Masterful crime films focusing on botched investigations and dark human nature.'); # L.A. Confidential -> Fargo
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (182955,164572,9,'galsasson4',NULL,'Both are highly stylized, slick crime thrillers featuring intricate double-crosses.'); # L.A. Confidential -> Jackie Brown
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (109093,164572,8,'galsasson4',NULL,'Phenomenal 90s crime stories driven by sharp dialogue and desperate characters.'); # Fargo -> Jackie Brown
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (63823,337404,9,'galsasson4',NULL,'Sprawling, documentary-style looks at the devastating street-level effects of drugs and crime.'); # City of God -> Traffic
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (224842,337404,8,'galsasson4',NULL,'Incredibly bleak, grounded explorations of trauma and societal decay.'); # Mystic River -> Traffic
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (348944,182955,9,'galsasson4',NULL,'Top-tier mysteries centered around complex criminal conspiracies and legendary twists.'); # The Usual Suspects -> L.A. Confidential
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (40226,278498,9,'galsasson4',NULL,'Both are highly influential, dread-inducing horrors reliant on atmosphere over gore.'); # The Blair Witch Project -> The Ring
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (40226,291221,8,'galsasson4',NULL,'Revolutionized 90s horror by breaking conventions and terrifying a generation.'); # The Blair Witch Project -> Scream
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (113305,154309,9,'galsasson4',NULL,'Textbook late-90s slashers where attractive teens try to outrun their gruesome fates.'); # Final Destination -> I Know What You Did Last Summer
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (113305,291221,8,'galsasson4',NULL,'Both rely on extremely clever meta-rules and inventive deaths to thrill the audience.'); # Final Destination -> Scream
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (278498,303564,8,'galsasson4',NULL,'Masterpieces of quiet, creeping supernatural dread and brilliant storytelling.'); # The Ring -> The Sixth Sense
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (154309,291221,9,'galsasson4',NULL,'The absolute peak of self-aware, fun teen slasher cinema of the era.'); # I Know What You Did Last Summer -> Scream
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (278498,40226,9,'galsasson4',NULL,'Relentless, slow-burn psychological horror where escape is seemingly impossible.'); # The Ring -> The Blair Witch Project
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (303564,278498,8,'galsasson4',NULL,'Both deal heavily with restless spirits and deeply unsettling mysteries.'); # The Sixth Sense -> The Ring
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (291221,113305,8,'galsasson4',NULL,'Highly entertaining popcorn horrors with massive cult followings.'); # Scream -> Final Destination
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (303564,90772,9,'galsasson4',NULL,'Moody, atmospheric films dealing with troubled youths and the supernatural.'); # The Sixth Sense -> Donnie Darko
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (139657,139650,10,'galsasson4',NULL,'A flawless sequential recommendation, maintaining the exact same whimsical magical tone.'); # Harry Potter 1 -> Harry Potter 2
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (139650,139655,9,'galsasson4',NULL,'The perfect evolution from childhood whimsy to darker, more mature fantasy.'); # Harry Potter 2 -> Harry Potter 3
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (139655,139652,9,'galsasson4',NULL,'Both entries mark a significant shift into darker, scarier territory for the series.'); # Harry Potter 3 -> Harry Potter 4
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (139652,139654,10,'galsasson4',NULL,'Deals directly with the traumatizing fallout and darker political themes of the franchise.'); # Harry Potter 4 -> Harry Potter 5
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (139654,139653,9,'galsasson4',NULL,'Both focus heavily on the agonizing personal sacrifices required to fight evil.'); # Harry Potter 5 -> Harry Potter 6
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (139657,194500,9,'galsasson4',NULL,'The best possible starting points for the two greatest fantasy franchises of the decade.'); # Harry Potter 1 -> The Lord of the Rings
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (139650,194500,8,'galsasson4',NULL,'Massive, highly detailed magical worlds brought perfectly to life.'); # Harry Potter 2 -> The Lord of the Rings
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (139655,194500,9,'galsasson4',NULL,'Both balance awe-inspiring magic with genuine, palpable danger.'); # Harry Potter 3 -> The Lord of the Rings
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (139652,194500,8,'galsasson4',NULL,'Epic scale, huge set pieces, and a deep sense of an impending dark war.'); # Harry Potter 4 -> The Lord of the Rings
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (139654,194500,9,'galsasson4',NULL,'Grand, emotionally heavy epics about the burden of resisting tyranny.'); # Harry Potter 5 -> The Lord of the Rings
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (45128,45129,10,'galsasson4',NULL,'A direct sequel that perfectly maintains the kinetic, gritty espionage style.'); # The Bourne Identity -> The Bourne Supremacy
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (45128,101070,9,'galsasson4',NULL,'Intense thrillers about highly capable men outsmarting massive government surveillance.'); # The Bourne Identity -> Enemy of the State
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (45129,101070,8,'galsasson4',NULL,'Fast-paced, intelligent action movies focusing on paranoia and survival.'); # The Bourne Supremacy -> Enemy of the State
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (107166,280115,10,'galsasson4',NULL,'The absolute zenith of 90s action cinema, featuring unbelievable stunts and star power.'); # Face/Off -> The Rock
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (107166,45128,8,'galsasson4',NULL,'Both involve deep-cover identities and highly choreographed shootouts.'); # Face/Off -> The Bourne Identity
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (280115,101070,9,'galsasson4',NULL,'High-octane blockbusters full of massive explosions and government conspiracies.'); # The Rock -> Enemy of the State
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (27168,340799,9,'galsasson4',NULL,'Perfect pairing of hilarious, high-energy 90s buddy-cop action movies.'); # Bad Boys -> Rush Hour
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (27168,280115,8,'galsasson4',NULL,'Glossy, stylish, explosion-heavy action directed with incredible flair.'); # Bad Boys -> The Rock
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (340799,107166,8,'galsasson4',NULL,'Both balance massive action set pieces with highly charismatic lead performances.'); # Rush Hour -> Face/Off
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (45129,280115,8,'galsasson4',NULL,'Extremely competent action heroes dismantling armies of bad guys.'); # The Bourne Supremacy -> The Rock
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (1038,235790,9,'galsasson4',NULL,'Beloved romantic comedies that perfectly balance humor with genuine sweetness.'); # Sweet Home Alabama -> Notting Hill
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (1038,321213,8,'galsasson4',NULL,'Great pairing of early 2000s rom-coms about women reassessing their lives.'); # Sweet Home Alabama -> Hope Floats
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (235790,321213,8,'galsasson4',NULL,'Both are quintessential, feel-good romantic hits with fantastic leads.'); # Notting Hill -> Hope Floats
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (104338,106988,9,'galsasson4',NULL,'Incredibly inventive, visually unique indie films dealing with love and introversion.'); # Eternal Sunshine of the Spotless Mind -> Amélie
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (104338,350424,9,'galsasson4',NULL,'Mind-bending explorations of love, regret, and the manipulation of memory.'); # Eternal Sunshine of the Spotless Mind -> Vanilla Sky
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (106988,328272,8,'galsasson4',NULL,'Deeply charming films about kind outsiders finding magic in enclosed worlds.'); # Amélie -> The Terminal
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (328272,1038,8,'galsasson4',NULL,'Both are uplifting, sweet mid-2000s movies focused on personal discovery.'); # The Terminal -> Sweet Home Alabama
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (48075,1038,9,'galsasson4',NULL,'Lighthearted 2000s comedies that use magical realism to explore relationships.'); # 13 Going on 30 -> Sweet Home Alabama
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (48075,235790,8,'galsasson4',NULL,'Both are crowd-pleasing, romantic escapist fun.'); # 13 Going on 30 -> Notting Hill
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (104338,90772,9,'galsasson4',NULL,'Surreal, slightly melancholic indie films that reward multiple viewings.'); # Eternal Sunshine of the Spotless Mind -> Donnie Darko
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (96593,313478,10,'galsasson4',NULL,'The undisputed kings of cinematic space opera and sequel perfection.'); # E.T. -> The Empire Strikes Back
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (96593,313479,9,'galsasson4',NULL,'An incredible continuation of the greatest heroic journey in film history.'); # E.T. -> Return of the Jedi
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (313478,313479,10,'galsasson4',NULL,'The thrilling, emotional climax of the legendary original sci-fi trilogy.'); # The Empire Strikes Back -> Return of the Jedi
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (96593,313459,9,'galsasson4',NULL,'Foundational John Williams-scored masterpieces of late 70s/early 80s movie magic.'); # E.T. -> Star Wars: Episode IV
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (313459,311037,8,'galsasson4',NULL,'Both defined their respective eras of massive, optimistic blockbuster entertainment.'); # Star Wars: Episode IV -> Spider-Man
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (313459,311038,8,'galsasson4',NULL,'Spectacles with deep emotional cores focused on discovering newfound powers.'); # Star Wars: Episode IV -> Spider-Man 2
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (311037,313479,8,'galsasson4',NULL,'Both feature classic battles between simple good and complex, masked evil.'); # Spider-Man -> Return of the Jedi
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (155070,96593,9,'galsasson4',NULL,'Huge, crowd-pleasing sci-fi adventures featuring daring pilots and massive explosions.'); # Independence Day -> E.T.
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (155070,313478,8,'galsasson4',NULL,'Massive scale battles against technologically superior hostile forces.'); # Independence Day -> The Empire Strikes Back
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (155070,313479,8,'galsasson4',NULL,'Both culminate in spectacular aerial dogfights to save the galaxy/world.'); # Independence Day -> Return of the Jedi
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (300229,300230,10,'galsasson4',NULL,'A rare comedy sequel that perfectly matches and elevates the original satire.'); # Shrek -> Shrek 2
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (300229,158927,8,'galsasson4',NULL,'Both are wildly successful, genre-parodying animated features with great action.'); # Shrek -> The Incredibles
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (300230,158927,8,'galsasson4',NULL,'Incredibly smart, funny animations that appeal equally to adults and kids.'); # Shrek 2 -> The Incredibles
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (199255,300229,8,'galsasson4',NULL,'Loud, colorful, hyperactive mid-2000s comedies aimed at entertaining the whole family.'); # Madagascar -> Shrek
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (199255,300230,8,'galsasson4',NULL,'Both rely heavily on catchy pop songs and sarcastic talking animals.'); # Madagascar -> Shrek 2
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (300229,218415,8,'galsasson4',NULL,'Titans of early 2000s animation featuring lovable misfits navigating strange worlds.'); # Shrek -> Monsters, Inc.
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (300230,218415,8,'galsasson4',NULL,'Both deliver massive laughs through extremely clever writing and sight gags.'); # Shrek 2 -> Monsters, Inc.
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (158927,199255,7,'galsasson4',NULL,'Highly entertaining animated adventures focusing on teamwork and escape.'); # The Incredibles -> Madagascar
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (312150,290939,8,'galsasson4',NULL,'Bizarre, highly stylized, hyperactive early 2000s kids movies with weird CGI.'); # Spy Kids -> Scooby-Doo
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (290939,56729,8,'galsasson4',NULL,'Both are chaotic live-action adaptations of beloved cartoons relying on crude humor.'); # Scooby-Doo -> The Cat in the Hat
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (207992,214755,7,'galsasson4',NULL,'Both are early 2000s sci-fi thrillers, but The Matrix is action-heavy while Minority Report is a neo-noir mystery.'); # The Matrix -> Minority Report
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (20371,342685,6,'galsasson4',NULL,'Both are 90s disaster movies, but one is a global space threat and the other is localized weather tracking.'); # Armageddon -> Twister
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (10916,155070,5,'galsasson4',NULL,'Hostile aliens, but Alien is claustrophobic horror while ID4 is an upbeat blockbuster.'); # Alien -> Independence Day
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (79716,81776,7,'galsasson4',NULL,'Both are massive apocalyptic disaster films, though the threats (weather vs comet) differ in pacing.'); # The Day After Tomorrow -> Deep Impact
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (10920,207991,6,'galsasson4',NULL,'Both feature humans in mech suits fighting massive swarms, but totally different lore and eras.'); # Aliens -> The Matrix Revolutions
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (214755,81776,5,'galsasson4',NULL,'Sci-fi films from the turn of the millennium, but one is a personal chase and the other an ensemble disaster.'); # Minority Report -> Deep Impact
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (328277,207992,7,'galsasson4',NULL,'Both involve saving humanity from AI and feature incredible action, but their tones and settings differ.'); # Terminator 2: Judgment Day -> The Matrix
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (311037,207992,6,'galsasson4',NULL,'Early 2000s ground-breaking visual effects blockbusters, but superhero vs cyberpunk.'); # Spider-Man -> The Matrix
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (155070,101070,5,'galsasson4',NULL,'Both feature Will Smith in late 90s blockbusters, but alien invasion vs spy thriller.'); # Independence Day -> Enemy of the State
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (20371,81776,7,'galsasson4',NULL,'The classic 1998 space-rock rivalry. Same premise, but Armageddon is pure action and Deep Impact is a drama.'); # Armageddon -> Deep Impact
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (337166,300229,6,'galsasson4',NULL,'Both are seminal CGI movies, but Shrek\'s crude pop-culture satire contrasts Toy Story\'s earnest heart.'); # Toy Story -> Shrek
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (113504,199255,5,'galsasson4',NULL,'CGI animal adventures, but Nemo is deeply emotional while Madagascar is slapstick comedy.'); # Finding Nemo -> Madagascar
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (191246,300229,5,'galsasson4',NULL,'Huge animated hits, but Shrek actively mocks the classic Disney tropes that The Lion King perfects.'); # The Lion King -> Shrek
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (9795,300230,6,'galsasson4',NULL,'Both deal with true love and monstrous appearances, but wildly different tones.'); # Beauty and the Beast -> Shrek 2
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (218415,199255,6,'galsasson4',NULL,'Both feature unlikely groups navigating human-adjacent worlds, but Pixar\'s depth outshines Dreamworks\' chaos.'); # Monsters, Inc. -> Madagascar
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (158927,300230,7,'galsasson4',NULL,'Both are brilliant 2004 animated features balancing action and adult humor, but different genres entirely.'); # The Incredibles -> Shrek 2
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (48950,199255,5,'galsasson4',NULL,'CGI animals leaving their homes, but the pacing and humor style are completely different.'); # A Bug's Life -> Madagascar
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (143526,300229,7,'galsasson4',NULL,'Both take mythological/fairy-tale concepts and inject them with modern humor and pop culture references.'); # Hercules -> Shrek
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (337168,158927,7,'galsasson4',NULL,'Both are top-tier Pixar, but toys trying to get home vs a family of superheroes fighting a villain.'); # Toy Story 2 -> The Incredibles
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (32178,113504,6,'galsasson4',NULL,'Both are animated underwater classics, but Disney musical vs Pixar parental journey.'); # The Little Mermaid -> Finding Nemo
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (46169,185628,7,'galsasson4',NULL,'Both feature epic, romanticized historical battles led by charismatic men, though the cultures differ wildly.'); # Braveheart -> The Last Samurai
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (289109,250746,6,'galsasson4',NULL,'Intense war films, but SPR is gritty modern realism while The Patriot leans into melodrama.'); # Saving Private Ryan -> The Patriot
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (39551,330388,5,'galsasson4',NULL,'Both are war films, but Black Hawk Down is non-stop action while Thin Red Line is a slow philosophical poem.'); # Black Hawk Down -> The Thin Red Line
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (340652,46169,7,'galsasson4',NULL,'Massive swords-and-sandals/medieval epics, but Troy lacks the emotional core of Braveheart.'); # Troy -> Braveheart
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (360480,250746,6,'galsasson4',NULL,'Both star Mel Gibson leading troops, but the Vietnam setting feels very different from the Revolutionary War.'); # We Were Soldiers -> The Patriot
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (330388,289109,7,'galsasson4',NULL,'The two massive 1998 WWII films, but they tackle the subject matter with completely opposite cinematic languages.'); # The Thin Red Line -> Saving Private Ryan
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (39551,101070,5,'galsasson4',NULL,'Tony Scott vs Ridley Scott late 90s/early 00s thrillers; tactical combat vs surveillance thriller.'); # Black Hawk Down -> Enemy of the State
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (46169,330388,5,'galsasson4',NULL,'Both have sweeping landscapes and battles, but the pacing and heroism are entirely disconnected.'); # Braveheart -> The Thin Red Line
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (112290,337404,5,'galsasson4',NULL,'Gritty 90s/00s classics, but Fight Club is stylized satire and Traffic is a grounded docu-drama.'); # Fight Club -> Traffic
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (210511,182955,6,'galsasson4',NULL,'Both are intricate, acclaimed neo-noirs, but Memento\'s reverse structure is vastly different from a classic 50s ensemble.'); # Memento -> L.A. Confidential
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (348944,109093,6,'galsasson4',NULL,'Both are 90s crime staples with twists, but Suspects is slick and serious while Fargo is a quirky black comedy.'); # The Usual Suspects -> Fargo
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (350424,210511,7,'galsasson4',NULL,'Both feature protagonists confused about reality and memory, though Vanilla Sky leans heavy into romance.'); # Vanilla Sky -> Memento
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (182955,224842,6,'galsasson4',NULL,'Excellent crime/mystery films, but 50s glossy noir vs early 2000s grim, bleak tragedy.'); # L.A. Confidential -> Mystic River
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (63823,112290,5,'galsasson4',NULL,'High-energy, visceral films about violent men, but favela realism vs consumerist satire.'); # City of God -> Fight Club
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (337404,182955,6,'galsasson4',NULL,'Sprawling epics about corrupt systems and law enforcement, but entirely different eras and visual styles.'); # Traffic -> L.A. Confidential
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (224842,348944,6,'galsasson4',NULL,'Dark mysteries dealing with a group of friends with a criminal past, but Mystic River is much more emotionally devastating.'); # Mystic River -> The Usual Suspects
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (164572,348944,6,'galsasson4',NULL,'90s crime capers relying on outsmarting the cops, but Tarantino\'s pacing is much slower and character-focused.'); # Jackie Brown -> The Usual Suspects
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (291221,278498,5,'galsasson4',NULL,'Massive 90s/00s horror hits, but meta-slasher humor is the opposite of slow-burn J-horror dread.'); # Scream -> The Ring
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (113305,303564,5,'galsasson4',NULL,'Both deal with escaping death and the supernatural, but one is gory popcorn fun and the other is a somber drama.'); # Final Destination -> The Sixth Sense
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (154309,113305,7,'galsasson4',NULL,'Both are fun, slightly campy teen horror films about escaping a predetermined fate.'); # I Know What You Did Last Summer -> Final Destination
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (113305,278498,6,'galsasson4',NULL,'Both involve a cursed timeline with a strict set of rules to survive, though the execution differs wildly.'); # Final Destination -> The Ring
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (291221,154309,7,'galsasson4',NULL,'The two defining teen slashers of the late 90s, though Scream is far smarter and more satirical.'); # Scream -> I Know What You Did Last Summer
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (90772,350424,6,'galsasson4',NULL,'Early 2000s surreal, psychological mind-benders, though Donnie Darko is indie grunge vs Vanilla Sky\'s Hollywood gloss.'); # Donnie Darko -> Vanilla Sky
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (303564,348944,6,'galsasson4',NULL,'Both rely entirely on legendary, narrative-redefining twist endings, despite being in different genres.'); # The Sixth Sense -> The Usual Suspects
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (139655,90772,5,'galsasson4',NULL,'Both feature dark, moody aesthetics, time travel, and troubled teens, but different genres entirely.'); # Harry Potter 3 -> Donnie Darko
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (194500,340652,7,'galsasson4',NULL,'Sweeping, massive cinematic epics with incredible battles, though one is fantasy and the other is myth/history.'); # Lord of the Rings -> Troy
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (139650,300229,6,'galsasson4',NULL,'Both are early 2000s fantasy hits, but Shrek mocks the tropes that Potter plays straight.'); # Harry Potter 2 -> Shrek
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (139654,313478,6,'galsasson4',NULL,'Both are darker franchise entries focusing on rebellion against an evil empire and a corrupted mentor figure.'); # Harry Potter 5 -> The Empire Strikes Back
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (139653,303564,5,'galsasson4',NULL,'Both involve dark secrets, ghosts/memories, and a shocking death, but very different scales.'); # Harry Potter 6 -> The Sixth Sense
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (194500,46169,7,'galsasson4',NULL,'Massive, sweeping epics focusing on a fellowship of warriors fighting against a tyrannical, overwhelming force.'); # Lord of the Rings -> Braveheart
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (139657,96593,7,'galsasson4',NULL,'Both are seminal, John Williams-scored movies about children discovering a magical secret world.'); # Harry Potter 1 -> E.T.
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (139655,207992,5,'galsasson4',NULL,'Highly stylized, darker entries in their respective genres from the same era, but magic vs sci-fi.'); # Harry Potter 3 -> The Matrix
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (45128,27168,5,'galsasson4',NULL,'Both are action movies, but Bourne is a cold, gritty spy thriller and Bad Boys is a loud, funny buddy-cop movie.'); # The Bourne Identity -> Bad Boys
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (107166,207992,6,'galsasson4',NULL,'Late 90s action classics, but Face/Off is absurd camp while The Matrix is philosophical cyberpunk.'); # Face/Off -> The Matrix
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (45129,214755,7,'galsasson4',NULL,'Fast-paced thrillers about framed men on the run from an omniscient tracking system.'); # The Bourne Supremacy -> Minority Report
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (280115,20371,7,'galsasson4',NULL,'Both are peak Michael Bay 90s spectacles, filled with explosions, heroism, and ensemble casts.'); # The Rock -> Armageddon
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (45128,182955,6,'galsasson4',NULL,'Both are smart, tightly written thrillers, but gritty modern espionage vs 1950s police corruption.'); # The Bourne Identity -> L.A. Confidential
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (101070,27168,6,'galsasson4',NULL,'Both star Will Smith in 90s action roles, but a paranoid thriller vs a loud buddy-cop comedy.'); # Enemy of the State -> Bad Boys
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (235790,106988,6,'galsasson4',NULL,'Both are beloved European-set romances, but commercial British rom-com vs quirky French arthouse.'); # Notting Hill -> Amélie
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (104338,328272,5,'galsasson4',NULL,'2004 films dealing with romance and isolation, but one is a heartbreaking mind-bender and the other is uplifting fluff.'); # Eternal Sunshine -> The Terminal
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (106988,350424,5,'galsasson4',NULL,'Both involve dreamlike sequences and romance, but Amelie is charming and Vanilla Sky is a surreal nightmare.'); # Amélie -> Vanilla Sky
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (328272,321213,6,'galsasson4',NULL,'Both are slow-paced, gentle mid-2000s dramedies about people trying to rebuild their lives.'); # The Terminal -> Hope Floats
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (235790,48075,7,'galsasson4',NULL,'Extremely solid, rewatchable romantic comedies that balance humor and heart perfectly.'); # Notting Hill -> 13 Going on 30
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (104338,112290,5,'galsasson4',NULL,'Both feature unreliable narrators and reality-bending twists, but romantic tragedy vs toxic masculinity satire.'); # Eternal Sunshine -> Fight Club
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (312150,158927,6,'galsasson4',NULL,'Both are about families of secret agents/superheroes coming out of retirement, but Pixar\'s quality is far superior.'); # Spy Kids -> The Incredibles
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (290939,300229,6,'galsasson4',NULL,'Both are early 2000s adaptations relying on crude humor and pop-music soundtracks.'); # Scooby-Doo -> Shrek
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (124160,199255,6,'galsasson4',NULL,'Both feature sarcastic CGI animals in the mid-2000s, though Madagascar is much better executed.'); # Garfield -> Madagascar
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (56729,300230,5,'galsasson4',NULL,'Both try to balance kid appeal with adult jokes, but Shrek 2 is a masterpiece and Cat in the Hat is a mess.'); # The Cat in the Hat -> Shrek 2
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (312150,139657,6,'galsasson4',NULL,'Both are 2001 kid-centric blockbusters where children discover a secret world, but vastly different tones.'); # Spy Kids -> Harry Potter 1
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (290939,139650,5,'galsasson4',NULL,'Both involve teens solving a monster mystery in 2002, but goofy CGI cartoon vs serious magical franchise.'); # Scooby-Doo -> Harry Potter 2
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (199255,312150,6,'galsasson4',NULL,'Hyperactive, brightly colored early-to-mid 2000s comedies aimed squarely at easily distracted children.'); # Madagascar -> Spy Kids
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (124160,290939,7,'galsasson4',NULL,'Both are critically panned but nostalgic live-action adaptations of beloved cartoons from the early 2000s.'); # Garfield -> Scooby-Doo
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (158927,311037,7,'galsasson4',NULL,'Both are fantastic superhero origin/return stories that balance deep character development with great action.'); # The Incredibles -> Spider-Man
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (300229,56729,5,'galsasson4',NULL,'Both are cynical takes on classic children\'s stories, but Mike Myers\' vocal performance in Shrek is much better.'); # Shrek -> The Cat in the Hat
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (96593,155070,5,'galsasson4',NULL,'Both are iconic alien encounter films, but a boy and his gentle alien vs a global war for survival.'); # E.T. -> Independence Day
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (328277,214755,6,'galsasson4',NULL,'Both deal with changing a predetermined future through intense sci-fi action, though the vibes differ.'); # Terminator 2 -> Minority Report
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (313459,207992,7,'galsasson4',NULL,'The classic hero\'s journey where a young man is mentored to use a mystical power to defeat an empire.'); # Star Wars IV -> The Matrix
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (342685,311037,5,'galsasson4',NULL,'Both are massive, effects-driven popcorn blockbusters, but weather disaster vs superhero origin.'); # Twister -> Spider-Man
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (81776,337404,5,'galsasson4',NULL,'Both use a sprawling, ensemble, multi-narrative structure to show the societal effects of a massive crisis.'); # Deep Impact -> Traffic
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (303564,106988,5,'galsasson4',NULL,'Both focus on quiet, observant individuals who see things others don\'t and try to fix people\'s lives.'); # The Sixth Sense -> Amélie
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (101070,207992,6,'galsasson4',NULL,'Late 90s films heavily focused on paranoia, surveillance, and escaping a system of control.'); # Enemy of the State -> The Matrix
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (210511,45128,7,'galsasson4',NULL,'Both center on amnesiac protagonists trying to piece together their violent pasts through clues.'); # Memento -> The Bourne Identity
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (182955,250746,5,'galsasson4',NULL,'Both are highly stylized period pieces dealing with corruption and violence, but completely different centuries.'); # L.A. Confidential -> The Patriot
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (313479,194500,7,'galsasson4',NULL,'Both represent the epic, sweeping conclusions to massive cinematic trilogies focusing on the defeat of ultimate evil.'); # Star Wars VI -> Lord of the Rings
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (112290,185628,6,'galsasson4',NULL,'Both feature intense struggles involving ancient/underground warrior codes, but Fight Club is modern satire while Last Samurai is a historical drama.'); # Fight Club -> The Last Samurai
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (210511,109093,6,'galsasson4',NULL,'Both are highly acclaimed crime thrillers with unique pacing, but Memento is a tense puzzle while Fargo relies on quirky dark humor.'); # Memento -> Fargo
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (348944,164572,6,'galsasson4',NULL,'Both are smart 90s crime films driven by criminal ensembles, but Suspects is a dark mystery while Jackie Brown is a slow-burn character piece.'); # The Usual Suspects -> Jackie Brown
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (40226,303564,5,'galsasson4',NULL,'Both deal with terrifying supernatural elements and unseen entities, but Blair Witch is raw found-footage horror while Sixth Sense is a polished drama.'); # The Blair Witch Project -> The Sixth Sense
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (291221,112290,6,'galsasson4',NULL,'Both are generation-defining late 90s hits with meta undertones, but slasher horror appeals to a different mood than anti-consumerist satire.'); # Scream -> Fight Club
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (303564,210511,6,'galsasson4',NULL,'Both feature non-linear elements or heavy psychological twists regarding the protagonist\'s reality, but ghost drama vs memory puzzle.'); # The Sixth Sense -> Memento
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (278498,113305,6,'galsasson4',NULL,'Both revolve around a terrifying supernatural force that hunts a specific group of people based on a strict timeline.'); # The Ring -> Final Destination
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (139657,313479,7,'galsasson4',NULL,'Both are major family-friendly fantasy adventures introducing iconic magical universes, though space opera vs wizarding world.'); # Harry Potter 1 -> Return of the Jedi
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (139652,313459,6,'galsasson4',NULL,'Both feature young heroes being thrust into grand magical/cosmic conflicts under wise mentors, but different fantasy genres.'); # Harry Potter 4 -> Star Wars IV
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (280115,27168,7,'galsasson4',NULL,'Both are action-packed 90s blockbusters set in vibrant coastal cities, though one is a prison siege and the other a buddy-cop comedy.'); # The Rock -> Bad Boys
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (27168,107166,6,'galsasson4',NULL,'High-energy 90s action with stylized shootouts, but Bad Boys balances it with comedy while Face/Off leans into sci-fi camp.'); # Bad Boys -> Face/Off
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (340799,280115,6,'galsasson4',NULL,'Both are fast-paced, star-driven 90s action hits, but martial arts comedy contrasts with a deadly military standoff.'); # Rush Hour -> The Rock
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (291221,250746,3,'galsasson4',NULL,'Meta-humor and jump scares have no place next to a melodramatic revolutionary war tale.'); # Scream -> The Patriot
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (1038,104338,5,'galsasson4',NULL,'Both are 2000s films dealing with romance and past relationships, but a bubbly southern rom-com doesn\'t match surreal melancholy.'); # Sweet Home Alabama -> Eternal Sunshine
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (48075,106988,6,'galsasson4',NULL,'Both are inventive 2000s lighthearted features about unique women, but mainstream American comedy vs quirky French arthouse.'); # 13 Going on 30 -> Amélie
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (106988,235790,6,'galsasson4',NULL,'Both are heartwarming European romances, but Amelie\'s stylized indie approach is very different from Notting Hill\'s traditional formula.'); # Amélie -> Notting Hill
INSERT INTO movies_recommendations (`base_movie_id`,`recommended_movie_id`,`recommendation`,`suggested_by`,`comment`,`justification`) VALUES (328272,235790,6,'galsasson4',NULL,'Uplifting mid-2000s commercial hits with romantic subplots, but an airport drama vs a British celebrity rom-com.'); # The Terminal -> Notting Hill