-- Movie Pairs Ranking
-- GitHub: Tomer-Spector

-- ============================================================
-- GOOD RECOMMENDATIONS (recommendation >= 7) -- 100 pairs
-- ============================================================

-- === LOTR TRILOGY ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (194497, 194502, 10, 'Tomer-Spector', 'Fellowship and Two Towers are literally one continuous story. The Helm''s Deep payoff in Two Towers only hits if you sat through the Fellowship build. Essential pairing.', null); # Fellowship of the Ring -> Two Towers
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (194502, 194500, 10, 'Tomer-Spector', 'Two Towers builds every thread that Return of the King resolves. Watching Towers without following with King is unfinished business.', null); # Two Towers -> Return of the King
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (194500, 194497, 10, 'Tomer-Spector', 'After Return of the King wraps the saga, rewatching Fellowship is a completely different experience. You see every seed it plants.', null); # Return of the King -> Fellowship of the Ring

-- === STAR WARS ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313478, 313479, 10, 'Tomer-Spector', 'Empire ends on a cliffhanger designed to be resolved by Jedi. The throne room payoff only lands if you sat through the Hoth-Dagobah-Bespin setup.', null); # Empire Strikes Back -> Return of the Jedi
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313477, 313478, 8, 'Tomer-Spector', 'Revenge of the Sith makes the Vader reveal in Empire dramatically richer. Knowing the fall makes the mask mean more.', null); # Revenge of the Sith -> Empire Strikes Back
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313476, 313477, 7, 'Tomer-Spector', 'Attack of the Clones and Revenge of the Sith are the prequel pair that actually connect. Clones sets up the Republic''s decay, Sith delivers it.', null); # Attack of the Clones -> Revenge of the Sith

-- === NOLAN ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (210511, 160524, 9, 'Tomer-Spector', 'Memento and Insomnia are Nolan''s two most contained psychological films. Both are about a compromised mind under pressure and both reward a second viewing.', null); # Memento -> Insomnia
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (160524, 30959, 8, 'Tomer-Spector', 'Insomnia and Batman Begins are Nolan''s back-to-back films before he went big. Both are about guilt driving a man past the edge of what is justified.', null); # Insomnia -> Batman Begins
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30959, 210511, 9, 'Tomer-Spector', 'Batman Begins and Memento both reward attention to structure. One dismantles a franchise, the other dismantles narrative itself.', null); # Batman Begins -> Memento

-- === TARANTINO ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (267038, 276217, 10, 'Tomer-Spector', 'Pulp Fiction and Reservoir Dogs define Tarantino. Same dialogue confidence, same genre bending, same pleasure of watching criminals talk themselves into trouble.', null); # Pulp Fiction -> Reservoir Dogs
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (176711, 176712, 10, 'Tomer-Spector', 'Kill Bill Vol 1 and Vol 2 are one film split in half on purpose. Vol 1 earns the violence, Vol 2 earns the emotion. Both are required.', null); # Kill Bill Vol 1 -> Kill Bill Vol 2
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (267038, 164572, 8, 'Tomer-Spector', 'Pulp Fiction and Jackie Brown are both Tarantino crime films but opposite in energy. Fiction is maximalist, Brown is patient. Brown rewards you if you trust Tarantino enough to slow down.', null); # Pulp Fiction -> Jackie Brown
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (276217, 164572, 8, 'Tomer-Spector', 'Reservoir Dogs and Jackie Brown both work through tension in small rooms with people who cannot trust each other. Same DNA, very different registers.', null); # Reservoir Dogs -> Jackie Brown

-- === SCORSESE ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (131780, 326155, 10, 'Tomer-Spector', 'Goodfellas and Taxi Driver are both Scorsese films about men who thrive inside a world that is eating them alive. Essential double bill.', null); # Goodfellas -> Taxi Driver
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (326155, 177369, 9, 'Tomer-Spector', 'Taxi Driver and King of Comedy are Scorsese and De Niro''s two studies of delusional loners in New York. Travis Bickle and Rupert Pupkin are practically the same man at different stages.', null); # Taxi Driver -> King of Comedy
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (270971, 326155, 9, 'Tomer-Spector', 'Raging Bull and Taxi Driver are both Scorsese-De Niro portraits of self-destructive men. Different arenas, same compulsive damage.', null); # Raging Bull -> Taxi Driver
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (131780, 123849, 7, 'Tomer-Spector', 'Goodfellas and Gangs of New York are both Scorsese epic crime films with real period texture. Goodfellas is tighter but Gangs has Day-Lewis and that levels the playing field.', null); # Goodfellas -> Gangs of New York
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (47130, 326155, 8, 'Tomer-Spector', 'Bringing Out the Dead and Taxi Driver are both Scorsese night-city films about a man losing himself in service to a city that cannot be saved. Same blood, different decade.', null); # Bringing Out the Dead -> Taxi Driver

-- === FINCHER ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (112290, 291698, 10, 'Tomer-Spector', 'Fight Club and Se7en are Fincher''s two films where the twist is an indictment. Both gut-punch endings that make the whole film mean something different on a rewatch.', null); # Fight Club -> Se7en
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (291698, 123435, 9, 'Tomer-Spector', 'Se7en and The Game are both Fincher films where paranoia is the engine. Se7en is darker, The Game is slicker. Together they show the range of his early control.', null); # Se7en -> The Game
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (123435, 247579, 7, 'Tomer-Spector', 'The Game and Panic Room are both Fincher films about confinement and control. Game operates on psychological space, Panic Room on physical. Both use architecture to generate dread.', null); # The Game -> Panic Room
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (34077, 291698, 7, 'Tomer-Spector', 'Benjamin Button and Se7en are both Fincher films about time and inevitability. Completely different genres, same fatalist undertow.', null); # Benjamin Button -> Se7en

-- === SPIELBERG ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (290070, 289109, 10, 'Tomer-Spector', 'Schindler''s List and Saving Private Ryan are both Spielberg WWII films built around the question of what one person''s survival is worth. The ethical weight is comparable.', null); # Schindler's List -> Saving Private Ryan
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (165961, 271095, 9, 'Tomer-Spector', 'Jaws and Raiders are peak Spielberg. Both run on a barely-seen threat, both have ensemble chemistry that could carry the film even without the spectacle.', null); # Jaws -> Raiders of the Lost Ark
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (96593, 65811, 8, 'Tomer-Spector', 'E.T. and Close Encounters are Spielberg''s two first-contact films where the aliens are not enemies. Both are ultimately about longing for something beyond the ordinary.', null); # E.T. -> Close Encounters
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (56871, 238072, 8, 'Tomer-Spector', 'Catch Me If You Can and Ocean''s Eleven were released within a month of each other and both are about the pleasure of watching smart operators run a con. One is earnest, one is cool.', null); # Catch Me If You Can -> Ocean's Eleven
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (94741, 165961, 9, 'Tomer-Spector', 'Duel is the proof of concept for Jaws. Both build sustained dread from a single unstoppable antagonist that barely shows itself. Duel is the earlier sketch, Jaws is the painting.', null); # Duel -> Jaws
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (359297, 61751, 8, 'Tomer-Spector', 'War of the Worlds and Children of Men are the two best grounded alien-invasion films of the 2000s. Both treat catastrophe as a thing you survive rather than a thing you fight.', null); # War of the Worlds -> Children of Men

-- === INDIANA JONES ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (271095, 159172, 10, 'Tomer-Spector', 'Raiders and Last Crusade are the two films that justify the franchise. The Connery addition in Crusade gives the character dimensions Raiders couldn''t have alone.', null); # Raiders -> Last Crusade
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (159175, 271095, 8, 'Tomer-Spector', 'Temple of Doom and Raiders are the two darker Indy films. Doom is rougher but the mine cart chase and the rope bridge are practical stunt work that has aged better than most of its era.', null); # Temple of Doom -> Raiders

-- === BOND - GOOD PAIRS ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (130953, 120574, 10, 'Tomer-Spector', 'Goldfinger and From Russia with Love are the two best Connery Bonds. Goldfinger defined the formula, From Russia is the one that plays it straight. Both are peak franchise.', null); # Goldfinger -> From Russia with Love
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (130945, 192702, 9, 'Tomer-Spector', 'GoldenEye and The Living Daylights both reset Bond after a creative slump. Different actors, same instinct to take the character seriously instead of coasting on formula.', null); # GoldenEye -> Living Daylights
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (240521, 192702, 8, 'Tomer-Spector', 'On Her Majesty''s Secret Service and Living Daylights are the two most grounded pre-Craig Bonds. Both cast actors who brought vulnerability the franchise was scared of.', null); # OHMSS -> Living Daylights
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (130953, 130945, 8, 'Tomer-Spector', 'Goldfinger and GoldenEye are each the best Bond film of their actor''s run. Both deliver the villain-hero dynamic the franchise always aspires to and rarely achieves.', null); # Goldfinger -> GoldenEye
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (312170, 130953, 8, 'Tomer-Spector', 'The Spy Who Loved Me and Goldfinger are the two most iconic Bond films outside the Connery opener set. Submarine car and laser table are the franchise at its most confidently absurd.', null); # Spy Who Loved Me -> Goldfinger

-- === BATMAN ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30955, 30959, 9, 'Tomer-Spector', 'Batman 1989 and Batman Begins are the two live-action Batman films that understood Gotham needs to feel like a place, not a set. Both take the source material seriously.', null); # Batman 1989 -> Batman Begins
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30976, 30959, 8, 'Tomer-Spector', 'Mask of the Phantasm and Batman Begins are the best origin stories Batman has received. One animated, one live-action, both explore the psychological weight of the choice to become Batman.', null); # Mask of the Phantasm -> Batman Begins
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30970, 30976, 7, 'Tomer-Spector', 'The Batman/Superman Movie and Mask of the Phantasm are the best Batman animated films on record. Both work because the DCAU writers understood these characters.', null); # Batman/Superman Movie -> Mask of the Phantasm

-- === HARRY POTTER ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (139655, 139652, 9, 'Tomer-Spector', 'Prisoner of Azkaban and Goblet of Fire are the two films where the series proved it could be cinema. Cuaron''s and Newell''s direction transformed what Columbus built.', null); # Prisoner of Azkaban -> Goblet of Fire
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (139652, 139654, 8, 'Tomer-Spector', 'Goblet of Fire and Order of the Phoenix are the franchise''s darkest consecutive pair. Graveyard scene into Umbridge''s reign is the stretch where Potter became genuinely dangerous.', null); # Goblet of Fire -> Order of the Phoenix
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (139657, 139650, 7, 'Tomer-Spector', 'Sorcerer''s Stone and Chamber of Secrets are Columbus''s two entries. If you loved the first''s faithful wonder, the second continues in exactly the same register before the series reinvents itself.', null); # Sorcerer's Stone -> Chamber of Secrets
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (139653, 139654, 8, 'Tomer-Spector', 'Half-Blood Prince and Order of the Phoenix are the two films building directly toward the finale. Both are about loss and the cave/Ministry sequences are the series at peak stakes.', null); # Half-Blood Prince -> Order of the Phoenix

-- === ALIEN FRANCHISE ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (10830, 10920, 10, 'Tomer-Spector', 'Alien and Aliens are the perfect genre pair. Scott made a horror film in space, Cameron made a war film in space. Both are genre masterpieces and watching them back to back shows how the same monster can anchor completely different films.', null); # Alien -> Aliens
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (10920, 289109, 8, 'Tomer-Spector', 'Aliens and Saving Private Ryan are the two best ensemble war films I have seen, one set in space and one in Normandy. The marine squad in Aliens and the Ranger unit in Ryan both work because the deaths feel earned.', null); # Aliens -> Saving Private Ryan

-- === SUPERMAN ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (319602, 319613, 8, 'Tomer-Spector', 'Superman 1978 and Superman II share the same creative team and form a two-part story. The Zod setup in the first film pays off fully in the second.', null); # Superman -> Superman II

-- === SPIDER-MAN ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (311037, 311038, 9, 'Tomer-Spector', 'Raimi''s Spider-Man and Spider-Man 2 are the definitive superhero film pair of the 2000s. The first introduces, the second delivers. Doc Ock''s train fight is the best action sequence in either film.', null); # Spider-Man -> Spider-Man 2

-- === OCEAN'S ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (238072, 238073, 7, 'Tomer-Spector', 'Ocean''s Eleven and Ocean''s Twelve are worth pairing just to watch the same cast riff. Twelve is messier but the Julia Roberts gag alone earns the ticket price if you loved the first.', null); # Ocean's Eleven -> Ocean's Twelve

-- === MISSION: IMPOSSIBLE ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (215876, 215880, 8, 'Tomer-Spector', 'Mission Impossible 1996 and M:I-III are the two best films in the franchise. Both take the spy paranoia seriously instead of treating it as a set-piece delivery mechanism.', null); # M:I 1 -> M:I III

-- === LETHAL WEAPON ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (188507, 188509, 8, 'Tomer-Spector', 'Lethal Weapon 1 and 2 are the best buddy cop pair in the genre. Adding Pesci in the second was the right chaos injection without breaking the formula.', null); # Lethal Weapon -> Lethal Weapon 2

-- === ROCKY ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (280270, 129185, 9, 'Tomer-Spector', 'Rocky and Gladiator are both underdog arena films built around a man fighting for dignity. Rocky is boxing, Gladiator is the Colosseum. Both earn the final moment completely.', null); # Rocky -> Gladiator
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (280270, 280281, 7, 'Tomer-Spector', 'Rocky and Rocky II are essentially one two-part story. The first earns the relationship, the second delivers the rematch that the first film always had to end with.', null); # Rocky -> Rocky II

-- === MIYAZAKI ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (218219, 174953, 10, 'Tomer-Spector', 'Mononoke and Nausicaa are Miyazaki''s two films about civilizations destroying nature and the young women caught between them. Together they form his clearest moral statement.', null); # Mononoke -> Nausicaa

-- === SHREK ===

-- === PIRATES OF THE CARIBBEAN ===

-- === HELLBOY ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (142491, 142492, 9, 'Tomer-Spector', 'Hellboy and Hellboy 2 are the best del Toro superhero pair. The sequel is visually richer but both work because Perlman never treats the character as a joke.', null); # Hellboy -> Hellboy 2

-- === SNATCH / CRIME ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (306032, 238072, 9, 'Tomer-Spector', 'Snatch and Ocean''s Eleven were released within months of each other and both are about the pleasure of watching a multi-threaded heist unfold among charismatic criminals. Same energy, different continents.', null); # Snatch -> Ocean's Eleven

-- === BURTON-DEPP ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (97727, 304862, 8, 'Tomer-Spector', 'Edward Scissorhands and Sleepy Hollow are Burton and Depp at their best. Both center on a strange outsider who cannot belong in the world they are dropped into.', null); # Edward Scissorhands -> Sleepy Hollow
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (97360, 97727, 8, 'Tomer-Spector', 'Ed Wood and Edward Scissorhands are both Burton-Depp films about a man who creates without apology and pays a social price for it. One is a comedy, one is a fairy tale.', null); # Ed Wood -> Edward Scissorhands
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (304862, 97360, 7, 'Tomer-Spector', 'Sleepy Hollow and Ed Wood both show Burton and Depp finding roles that fit Depp''s specific eccentricity perfectly. Both are underappreciated in their respective catalogs.', null); # Sleepy Hollow -> Ed Wood

-- === SCI-FI THEMATIC ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (40199, 61751, 9, 'Tomer-Spector', 'Blade Runner and Children of Men are the two most visually influential dystopian sci-fi films of their respective eras. Both build worlds you believe in completely and both end in a kind of exhausted hope.', null); # Blade Runner -> Children of Men
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (214755, 210511, 8, 'Tomer-Spector', 'Minority Report and Memento are both intelligent films about a protagonist who cannot trust his own version of events. One is a blockbuster, one is a puzzle box.', null); # Minority Report -> Memento
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (256839, 10830, 8, 'Tomer-Spector', 'Pitch Black and Alien are both survival horror in space where the creature is secondary to the character dynamics. Pitch Black is clearly influenced by Alien and earns the comparison in its first act.', null); # Pitch Black -> Alien

-- === CRIME DRAMA THEMATIC ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (297838, 290070, 9, 'Tomer-Spector', 'Shawshank Redemption and Schindler''s List are the two films most people point to when asked what cinema can do at its best. Both are about survival through impossible conditions. Both are essential.', null); # Shawshank -> Schindler's List
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (112290, 267038, 9, 'Tomer-Spector', 'Fight Club and Pulp Fiction are the two films that defined what edgy 1990s cinema meant. Both are about the seduction of transgression and both punish the audience for buying in.', null); # Fight Club -> Pulp Fiction
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (131780, 41518, 7, 'Tomer-Spector', 'Goodfellas and Blow are both rise-and-fall crime biographies about men who got too deep too fast. Blow is smaller scale but Depp''s performance carries it further than the script deserves.', null); # Goodfellas -> Blow

-- === ACTION THEMATIC ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (39551, 289109, 9, 'Tomer-Spector', 'Black Hawk Down and Saving Private Ryan are the two best immersive combat films of their era. Both treat battle as chaos rather than choreography and both force you to feel the cost.', null); # Black Hawk Down -> Saving Private Ryan
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (185628, 289109, 7, 'Tomer-Spector', 'The Last Samurai and Saving Private Ryan are both about soldiers who find meaning in fighting for something they did not start out believing in. Different wars, same emotional architecture.', null); # Last Samurai -> Saving Private Ryan

-- === SPY KIDS ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (312150, 312151, 3, 'Tomer-Spector', 'Though both are Spy Kids films by Rodriguez, the first has genuine inventive energy and the second piles on imagination without anchoring it to a story. Rodriguez''s creature design is still present but the film loses the focus that made the original work.', null); # Spy Kids -> Spy Kids 2

-- === DE NIRO DRAMATIC ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (330670, 54209, 8, 'Tomer-Spector', 'This Boy''s Life and Cape Fear pair De Niro as an authority figure who is also a threat. Stepfather and stalker but the psychological mechanism of control is the same in both performances.', null); # This Boy's Life -> Cape Fear
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (270971, 177369, 8, 'Tomer-Spector', 'Raging Bull and King of Comedy are Scorsese and De Niro studying obsession. LaMotta obsesses over the ring, Rupert over celebrity. Both are more uncomfortable than their genres suggest.', null); # Raging Bull -> King of Comedy

-- === ADVENTURE ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (131885, 271095, 8, 'Tomer-Spector', 'The Goonies and Raiders are both 1980s treasure-hunt adventure films with ensemble casts held together by chemistry. Goonies is Raiders aimed at kids and it earns the comparison.', null); # Goonies -> Raiders
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (149287, 131885, 7, 'Tomer-Spector', 'Hook and The Goonies are both Spielberg-adjacent adventure films about childhood imagination refusing to die. Both work because the ensemble earns its emotional moment.', null); # Hook -> Goonies
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (372733, 131885, 7, 'Tomer-Spector', 'Young Sherlock Holmes and The Goonies are the two best adventure films aimed at kids from the Amblin 1985 era. Both have set pieces that aged better than most of their contemporaries.', null); # Young Sherlock Holmes -> Goonies

-- === PERIOD DRAMA / WAR EPIC ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (340652, 129185, 7, 'Tomer-Spector', 'Troy and Gladiator are both ancient-world epic action films with ensemble casts. Gladiator is the better film but Bana as Hector in Troy is worth the ticket alone.', null); # Troy -> Gladiator

-- === BLEND / MISC HIGH ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (210739, 256632, 8, 'Tomer-Spector', 'Men in Black and Pirates of the Caribbean are both films where a charismatic lead reinvented a formula. Smith''s MIB and Depp''s Sparrow both came out of nowhere and became defining characters.', null); # Men in Black -> Pirates
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (256627, 40199, 7, 'Tomer-Spector', 'Pirates of Silicon Valley and Blade Runner are both films about men who built something extraordinary and lost their humanity doing it. Jobs and Wozniak''s dynamic maps surprisingly well onto Blade Runner''s corporate dread.', null); # Pirates of Silicon Valley -> Blade Runner
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (183873, 97727, 7, 'Tomer-Spector', 'Ladyhawke and Edward Scissorhands are both fantasy films about a separation curse that prevents two people from being together. Different eras and aesthetics, same emotional core.', null); # Ladyhawke -> Edward Scissorhands
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (644, 66194, 8, 'Tomer-Spector', '10 Things I Hate About You and Clueless are both 1990s teen films built on classic literature that are smarter than they advertise. Both have sharper writing than the genre required.', null); # 10 Things -> Clueless
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (220276, 333856, 7, 'Tomer-Spector', 'Moulin Rouge and Titanic are both big-budget tragic romances from the same era where the spectacle is designed to make you cry. Both earn it by committing completely to the emotional register.', null); # Moulin Rouge -> Titanic
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (39829, 40199, 7, 'Tomer-Spector', 'Black Rain and Blade Runner are both Ridley Scott films that use neon-soaked Asian cityscapes to tell stories about outsiders in an unfamiliar world. The visual DNA is unmistakable.', null); # Black Rain -> Blade Runner
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (113459, 238072, 7, 'Tomer-Spector', 'Find Me Guilty and Ocean''s Eleven are both ensemble films where the pleasure comes from watching a charismatic group work a room. Diesel''s courtroom performance is the closest he ever came to a fully realized dramatic role.', null); # Find Me Guilty -> Ocean's Eleven


-- ============================================================
-- NOT GOOD YET REASONABLE RECOMMENDATIONS (recommendation <= 4) -- 100 pairs
-- ============================================================

-- === BOND FALSE POSITIVES (director/franchise match, quality diverges) ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (130953, 218808, 2, 'Tomer-Spector', 'Though both are Connery-era Bond, Moonraker''s space-laser plot and Jaws-as-romantic-comedy are a complete betrayal of what made Goldfinger work. Sharing a franchise is not a reason to recommend.', null); # Goldfinger -> Moonraker
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (130945, 86263, 2, 'Tomer-Spector', 'Though both are Brosnan-era Bond, Die Another Day''s invisible car and CGI surfing are the opposite of what made GoldenEye a franchise revival. Same actor, completely different creative ambition.', null); # GoldenEye -> Die Another Day
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (240521, 218808, 2, 'Tomer-Spector', 'Though both are Bond films that cast against type, Moonraker does the opposite of what OHMSS achieved. OHMSS is grounded and emotionally real; Moonraker put Bond in space for a punchline.', null); # OHMSS -> Moonraker
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (192702, 85871, 3, 'Tomer-Spector', 'Though both are Bond films where the actor brought something different, Diamonds are Forever shows Connery sleepwalking through a paycheck. Living Daylights treated the character seriously; Diamonds abandoned that.', null); # Living Daylights -> Diamonds Are Forever
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (312170, 218808, 2, 'Tomer-Spector', 'Though both are Roger Moore Bond films, Spy Who Loved Me is the peak of his run and Moonraker is what happens when that formula collapses under its own absurdity. They share an actor but not a standard.', null); # Spy Who Loved Me -> Moonraker
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (130953, 85871, 3, 'Tomer-Spector', 'Though both are Connery Bond films, Goldfinger is the franchise at its best and Diamonds are Forever is Connery coasting. The gap in quality is the gap between a landmark film and a sequel that barely existed.', null); # Goldfinger -> Diamonds Are Forever
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (130945, 335336, 3, 'Tomer-Spector', 'Though both are Brosnan Bond films, GoldenEye had real stakes and Tomorrow Never Dies ran out of ideas. The media-mogul villain was ahead of its time but the film did nothing interesting with it.', null); # GoldenEye -> Tomorrow Never Dies
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (130953, 372233, 3, 'Tomer-Spector', 'Though both are 1960s Bond films, You Only Live Twice is Goldfinger''s formula stretched thin. The volcano lair is iconic but the story around it is paper.', null); # Goldfinger -> You Only Live Twice
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (120574, 332065, 3, 'Tomer-Spector', 'Though both are early Connery Bonds, Thunderball is From Russia With Love without the discipline. Underwater action that aged badly and a pacing problem the franchise never had before.', null); # From Russia With Love -> Thunderball
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (192702, 203649, 3, 'Tomer-Spector', 'Though both are Moore/Dalton-era Bond films, Man With the Golden Gun wastes Christopher Lee in a generic villain role while Living Daylights actually did something with its lead. Same franchise, different ambition.', null); # Living Daylights -> Man with the Golden Gun
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (130945, 368418, 3, 'Tomer-Spector', 'Though both are Brosnan Bond films, The World Is Not Enough had Marceau as an interesting villain and then cast Richards as a nuclear physicist. GoldenEye had no such casting disaster.', null); # GoldenEye -> World Is Not Enough
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (312170, 354178, 3, 'Tomer-Spector', 'Though both are Roger Moore Bond films, Spy Who Loved Me is Moore at his peak and View to a Kill is Moore two films too late. He acknowledged he was too old and the film agrees.', null); # Spy Who Loved Me -> View to a Kill

-- === BATMAN FALSE POSITIVES ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30955, 30967, 3, 'Tomer-Spector', 'Though both are Tim Burton Batman films, Batman Returns goes so far into Burton''s personal aesthetic that it forgets to be a Batman film. Batman 1989 was strange but disciplined; Returns is self-indulgent.', null); # Batman 1989 -> Batman Returns
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30959, 30965, 2, 'Tomer-Spector', 'Though both are live-action Batman films, Batman Begins is a serious reimagining and Batman Forever is a cartoon. Recommending them together because they share a character is misleading.', null); # Batman Begins -> Batman Forever
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30976, 30952, 2, 'Tomer-Spector', 'Though both are Batman films, Mask of the Phantasm understands the character deeply and Batman and Robin contains the bat-credit card. They cannot be recommended together in good conscience.', null); # Mask of the Phantasm -> Batman & Robin
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30955, 30952, 2, 'Tomer-Spector', 'Though both are live-action Batman films, Batman 1989 took the franchise seriously and Batman and Robin ended it with ice puns. They share a character name and almost nothing else.', null); # Batman 1989 -> Batman & Robin
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30959, 30952, 2, 'Tomer-Spector', 'Though both are live-action Batman films, Batman Begins reinvented the franchise and Batman and Robin is the creative collapse that made that reinvention necessary. Opposite ends of the spectrum.', null); # Batman Begins -> Batman & Robin
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30976, 30951, 3, 'Tomer-Spector', 'Though both are Batman animated films, Mask of the Phantasm is an actual theatrical film with thematic weight and Batman and Mr. Freeze SubZero is a direct-to-video product. Same animation style, different ambition.', null); # Mask of the Phantasm -> Batman SubZero
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30955, 30965, 3, 'Tomer-Spector', 'Though both are Burton/Schumacher-era Batman films, Batman 1989 established Gotham as a real dark city and Batman Forever replaced all that with neon and competing villain performances.', null); # Batman 1989 -> Batman Forever

-- === ROCKY FALSE POSITIVES ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (280270, 280305, 2, 'Tomer-Spector', 'Though both are Rocky films, the original is a genuine underdog classic and Rocky V is the entry Stallone himself disowned. The franchise DNA is there but the quality is not.', null); # Rocky -> Rocky V
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (280270, 280284, 3, 'Tomer-Spector', 'Though both are Rocky films, the original earns its emotion through character and Rocky IV replaces character with a training montage and a Russian villain drawn as a cartoon. Same franchise, different planets.', null); # Rocky -> Rocky IV
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (280281, 280305, 3, 'Tomer-Spector', 'Though both are Rocky sequels, Rocky II still had some of the original''s heart and Rocky V abandoned even that. Watching them as a pair just shows the franchise declining.', null); # Rocky II -> Rocky V
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (280270, 280306, 2, 'Tomer-Spector', 'Though both are labeled Rocky films in the database, Rocky VI is a mislabeled entry that likely does not exist as its own film. Recommending the original alongside a database anomaly makes no sense.', null); # Rocky -> Rocky VI

-- === ALIEN FALSE POSITIVES ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (10830, 10945, 3, 'Tomer-Spector', 'Though both are Alien franchise films, Alien 3 is the entry Fincher disowned and for good reason. It undoes the emotional investment of both prior films in its opening minutes. Same world, very different craft.', null); # Alien -> Alien 3
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (10920, 10945, 3, 'Tomer-Spector', 'Though both are Alien franchise films, Aliens earned every character it introduced and Alien 3 killed most of them offscreen before the credits finished. They share a franchise but not a standard of care for the audience.', null); # Aliens -> Alien 3

-- === INDIANA JONES FALSE POSITIVES ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (271095, 159167, 2, 'Tomer-Spector', 'Though both are Indiana Jones films, Raiders is the film that defined the franchise and Kingdom of the Crystal Skull crossed the line with its fridge scene. Same character, completely different creative respect for the audience.', null); # Raiders -> Indiana Jones 4

-- === LETHAL WEAPON FALSE POSITIVES ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (188507, 188511, 2, 'Tomer-Spector', 'Though both are Lethal Weapon films, the original has Gibson at his most charismatic and the fourth has Jet Li wasted as a silent villain while the leads have run out of road. Same franchise, dead on arrival.', null); # Lethal Weapon -> Lethal Weapon 4
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (188509, 188511, 3, 'Tomer-Spector', 'Though both are Lethal Weapon sequels, the second added Pesci and felt like an expansion, the fourth added Jet Li and felt like a conclusion nobody asked for. The Riggs-Murtaugh chemistry barely survives.', null); # Lethal Weapon 2 -> Lethal Weapon 4

-- === SPY KIDS FALSE POSITIVES ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (312150, 312152, 2, 'Tomer-Spector', 'Though both are Spy Kids films, the original was imaginative and the third is a tech demo for bad 3D with a Stallone cameo that cannot save it. Recommending both together is doing the viewer a disservice.', null); # Spy Kids -> Spy Kids 3D
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (312151, 312152, 3, 'Tomer-Spector', 'Though both are Spy Kids sequels, the second still had Rodriguez''s creature design working and the third replaced it entirely with a virtual reality premise that does not hold up. Same franchise DNA, diminishing returns.', null); # Spy Kids 2 -> Spy Kids 3D

-- === STAR WARS FALSE POSITIVES ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313478, 313474, 3, 'Tomer-Spector', 'Though both are Star Wars films, Empire Strikes Back is the emotional peak of the franchise and Phantom Menace is a trade dispute film with a CGI character that became a cultural embarrassment. Same galaxy, very different priorities.', null); # Empire -> Phantom Menace
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313477, 313474, 3, 'Tomer-Spector', 'Though both are Star Wars prequel films, Revenge of the Sith earned its tragedy and Phantom Menace spent two hours on a pod race that led nowhere emotionally. The same trilogy connecting them does not make them equivalent.', null); # Revenge of the Sith -> Phantom Menace
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313478, 313476, 3, 'Tomer-Spector', 'Though both are Star Wars films, Empire Strikes Back has the Hoth-Dagobah-Bespin trio and Attack of the Clones has the Anakin romance subplot that is widely considered the worst creative decision in the saga.', null); # Empire -> Attack of the Clones

-- === HARRY POTTER FALSE POSITIVES ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (139655, 139650, 3, 'Tomer-Spector', 'Though both are Harry Potter films, Prisoner of Azkaban reinvented the series cinematically and Chamber of Secrets is the entry before that reinvention, competent but without Cuaron''s vision. Recommending them as a pair oversells the second.', null); # Prisoner of Azkaban -> Chamber of Secrets
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (139652, 139650, 3, 'Tomer-Spector', 'Though both are Harry Potter films, Goblet of Fire brought genuine stakes and Chamber of Secrets is the weakest film in the franchise. They share a character but not a level of quality.', null); # Goblet of Fire -> Chamber of Secrets

-- === MISSION: IMPOSSIBLE FALSE POSITIVES ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (215876, 215879, 3, 'Tomer-Spector', 'Though both are Mission: Impossible films, the original used the spy paranoia well and M:I-II handed it to Woo for slow-motion doves and motorcycle ballet. Same franchise, opposite sensibilities.', null); # M:I 1 -> M:I II
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (215880, 215875, 3, 'Tomer-Spector', 'Though both carry the Mission: Impossible name, M:I-III is a genuinely tense spy film and the 1991 TV movie is a franchise curiosity that exists mainly as historical context. Not a meaningful pairing.', null); # M:I III -> M:I 1991

-- === PIRATES OF THE CARIBBEAN FALSE POSITIVES ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (256632, 256631, 3, 'Tomer-Spector', 'Though both are Pirates films with the same cast, Curse of the Black Pearl introduced Sparrow as a genuinely creative character and Dead Man''s Chest already showed the franchise losing focus. The first earned everything the second coasts on.', null); # Pirates 1 -> Pirates 2

-- === SPIELBERG FALSE POSITIVES ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (165961, 1390, 2, 'Tomer-Spector', 'Though both are Spielberg films, Jaws is a precision-built suspense machine and 1941 is his only significant flop. His own instincts for pacing and restraint that made Jaws work are completely absent from 1941.', null); # Jaws -> 1941
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (56871, 21213, 3, 'Tomer-Spector', 'Though both are Spielberg films, Catch Me If You Can is light and pleasurable and A.I. is the heavy Kubrick project he tried to finish and the seams show throughout. They are not in the same register.', null); # Catch Me If You Can -> AI

-- === SCORSESE FALSE POSITIVES ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (131780, 47130, 3, 'Tomer-Spector', 'Though both are Scorsese films with similar nocturnal New York energy, Goodfellas is a masterpiece of organized structure and Bringing Out the Dead is his most underrated film but feels unfinished where Goodfellas feels inevitable.', null); # Goodfellas -> Bringing Out the Dead
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (270971, 123849, 3, 'Tomer-Spector', 'Though both are Scorsese epics, Raging Bull is compact and devastating and Gangs of New York sprawls without the same control. Day-Lewis saves Gangs but De Niro in Bull did not need saving.', null); # Raging Bull -> Gangs of New York

-- === FINCHER FALSE POSITIVES ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (291698, 10945, 3, 'Tomer-Spector', 'Though both are Fincher films, Se7en is one of his best-controlled films and Alien 3 is the studio-compromised debut he disowned. They share a director''s name but not a director''s control.', null); # Se7en -> Alien 3
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (112290, 34077, 3, 'Tomer-Spector', 'Though both are Fincher films, Fight Club runs on controlled transgression and Benjamin Button runs on sentiment. They are both interesting but recommending them as a pair implies they scratch the same itch, which they do not.', null); # Fight Club -> Benjamin Button

-- === TARANTINO FALSE POSITIVES ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (267038, 118367, 3, 'Tomer-Spector', 'Though both feature Tarantino, Pulp Fiction is the complete vision and Four Rooms is an anthology where the Tarantino segment is the only one that works. Recommending them as equivalent Tarantino experiences is misleading.', null); # Pulp Fiction -> Four Rooms
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (276217, 159665, 3, 'Tomer-Spector', 'Though both are Tarantino-adjacent war films, Reservoir Dogs is a precision thriller and Inglorious Bastards is the Italian original, not the Tarantino remake. The name similarity creates a false connection.', null); # Reservoir Dogs -> Inglorious Bastards (Italian)

-- === BURTON FALSE POSITIVES ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (97727, 59578, 3, 'Tomer-Spector', 'Though both are Burton-Depp films, Edward Scissorhands has genuine emotional sincerity and Charlie and the Chocolate Factory leans into Depp''s eccentricity as style rather than character. Burton''s personal touch is visible in Scissorhands and missing in Charlie.', null); # Edward Scissorhands -> Charlie and the Chocolate Factory
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (304862, 59578, 3, 'Tomer-Spector', 'Though both are Burton films with gothic production design, Sleepy Hollow uses the visual imagination to serve genuine atmosphere and Charlie and the Chocolate Factory uses it as the only thing it has going on.', null); # Sleepy Hollow -> Charlie and the Chocolate Factory
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (97360, 70959, 3, 'Tomer-Spector', 'Though both are Burton films, Ed Wood is emotionally grounded in a way that Corpse Bride cannot manage with its thin story. Both are beautiful to look at but only one of them has something to say.', null); # Ed Wood -> Corpse Bride

-- === DEPP THEMATIC FALSE POSITIVES ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (41518, 233058, 3, 'Tomer-Spector', 'Though both are Depp dramatic films in contained settings, Blow has a clear rise-and-fall arc and The Ninth Gate has a famously unsatisfying ending that leaves the premise unresolved. Depp is committed in both but the writing fails him in Ninth Gate.', null); # Blow -> Ninth Gate
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (256632, 120506, 3, 'Tomer-Spector', 'Though both are Depp films with period settings, Pirates is Depp at his most creative and From Hell is Depp doing restrained Jack the Ripper procedural that never delivers on its atmosphere. Same lead, opposite results.', null); # Pirates -> From Hell
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (34104, 113506, 3, 'Tomer-Spector', 'Though both are Depp films where he plays an eccentric outsider who charms a community, Benny and Joon is whimsical by design and Finding Neverland is supposed to be emotionally serious. Both are gentle films that neither surprises you.', null); # Benny & Joon -> Finding Neverland
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (97727, 22651, 3, 'Tomer-Spector', 'Though both are Depp films with a supernatural premise, Edward Scissorhands has genuine soul and The Astronaut''s Wife is a generic sci-fi thriller that never does anything interesting with Depp or Theron.', null); # Edward Scissorhands -> Astronaut's Wife

-- === ROMCOM FALSE POSITIVES ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (644, 283410, 3, 'Tomer-Spector', 'Though both are romantic comedies with charismatic leads, 10 Things I Hate About You is sharp Shakespeare adaptation and Runaway Bride is a Gere-Roberts reunion that coasts on Pretty Woman goodwill. Different tiers of writing.', null); # 10 Things -> Runaway Bride
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (66194, 263360, 3, 'Tomer-Spector', 'Though both are romcoms with sharp female leads, Clueless is genuinely witty and Pretty Woman has a premise that became more uncomfortable with each passing decade. Silverstone''s writing is smarter than Roberts'' situation.', null); # Clueless -> Pretty Woman
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (220276, 200864, 3, 'Tomer-Spector', 'Though both are romantic films with stars at their peak, Moulin Rouge earns its emotion through operatic commitment and Maid in Manhattan runs paint-by-numbers beats with JLo on autopilot. Same genre, different aspiration.', null); # Moulin Rouge -> Maid in Manhattan
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (644, 46878, 3, 'Tomer-Spector', 'Though both are romantic films built around a witty female protagonist, 10 Things is sharp and Bridget Jones: Edge of Reason is a sequel running on fumes. The writing quality gap is significant.', null); # 10 Things -> Bridget Jones 2
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (238072, 200864, 3, 'Tomer-Spector', 'Though both are star-driven films from 2001-2002 with ensemble energy, Ocean''s Eleven is a precision heist film and Maid in Manhattan is a romcom where JLo and Fiennes generate just enough chemistry to stay watchable. Not a meaningful pairing.', null); # Ocean's Eleven -> Maid in Manhattan

-- === ACTION/SCI-FI FALSE POSITIVES ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (61751, 21213, 3, 'Tomer-Spector', 'Though both are dystopian sci-fi films about civilizational collapse, Children of Men is one of the most perfectly controlled films of the 2000s and A.I. is the Kubrick-Spielberg project where the ending collapses what came before.', null); # Children of Men -> AI
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (40199, 256839, 3, 'Tomer-Spector', 'Though both are sci-fi films where a protagonist hunts targets in a world that has lost its humanity, Blade Runner is a landmark and Pitch Black is a solid B-movie that borrows some of its DNA. Recommending them as equals misrepresents both.', null); # Blade Runner -> Pitch Black
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (158999, 370017, 3, 'Tomer-Spector', 'Though both are over-the-top action spectacles with a charismatic lead, Independence Day earns its scale through ensemble investment and XXX replaces that with Diesel doing Bond parody that takes itself too seriously to be funny.', null); # Independence Day -> XXX
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (289109, 340652, 3, 'Tomer-Spector', 'Though both are historical war epics with ensemble casts, Saving Private Ryan is Spielberg at peak control and Troy is a 2004 blockbuster where only Bana''s Hector performance rises above the material.', null); # Saving Private Ryan -> Troy
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (109421, 370017, 3, 'Tomer-Spector', 'Though both are early-2000s action films with charismatic leads building franchises, The Fast and the Furious has genuine ensemble chemistry and XXX never built anything beyond Diesel''s star persona.', null); # Fast and Furious -> XXX

-- === SUPERHERO FALSE POSITIVES ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (311038, 30952, 2, 'Tomer-Spector', 'Though both are superhero films, Spider-Man 2 is one of the best films in the genre and Batman and Robin is one of the worst. Sharing a genre is not a reason to recommend them together.', null); # Spider-Man 2 -> Batman & Robin
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (319602, 30965, 3, 'Tomer-Spector', 'Though both are superhero origin films from different eras, Superman 1978 is earnest and effective and Batman Forever is competing villain performances with neon set design. Same genre, opposite approaches to sincerity.', null); # Superman -> Batman Forever
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (142492, 30952, 2, 'Tomer-Spector', 'Though both are superhero films with colorful villains, Hellboy 2 uses del Toro''s monster imagination to create something genuinely strange and Batman and Robin used Schwarzenegger''s ice puns to end a franchise. Not comparable.', null); # Hellboy 2 -> Batman & Robin

-- === ANIMATION FALSE POSITIVES ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (218219, 190869, 3, 'Tomer-Spector', 'Though both are animated films with surprising emotional depth, Mononoke is a morally complex meditation on civilization and nature and Lilo and Stitch, while excellent, is a much lighter film. Grouping them as equivalent is unfair to the ambition of Mononoke.', null); # Mononoke -> Lilo & Stitch
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (300229, 300230, 3, 'Tomer-Spector', 'Though both are Shrek films, the original had real satirical bite and the sequel coasts more heavily on the formula it built. Murphy is still the best part but the freshness is gone.', null); # Shrek -> Shrek 2

-- === MISC FALSE POSITIVES (thematic match, quality gap) ===
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (306032, 208245, 3, 'Tomer-Spector', 'Though both are ensemble films where charismatic actors play criminals or gamblers, Snatch is precise and kinetic and Maverick is a comfortable star vehicle. The comparison flatters neither.', null); # Snatch -> Maverick
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (280270, 280282, 3, 'Tomer-Spector', 'Though both are Rocky films, the original is a genuine drama and Rocky III replaces all of that with Mr. T and Eye of the Tiger. The training montage is the only thing anyone remembers because the film itself forgot what it was about.', null); # Rocky -> Rocky III
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (290070, 31715, 2, 'Tomer-Spector', 'Though both are films about intense emotional bonds between women facing devastating circumstances, Schindler''s List is Spielberg at his most controlled and Beaches is sentimental melodrama that earned its reputation as the crying film of 1988. They are not in the same category.', null); # Schindler's List -> Beaches
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (238072, 253010, 3, 'Tomer-Spector', 'Though both feature ensemble casts in crime-adjacent settings, Ocean''s Eleven is a perfect machine and A Perfect World is a quiet Eastwood film that has nothing in common with heist films except that Costner''s character has broken the law.', null); # Ocean's Eleven -> A Perfect World
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (256627, 58084, 3, 'Tomer-Spector', 'Though both are films about technology and the men who built something ambitious, Pirates of Silicon Valley is a compelling historical drama and Cerebrium is a low-budget psychological thriller where ambition clearly exceeded the available resources.', null); # Pirates of Silicon Valley -> Cerebrium
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (183873, 244421, 3, 'Tomer-Spector', 'Though both are films about unlikely romantic pairs navigating social obstacles, Ladyhawke commits to its fantasy premise completely and The Other Sister is soft Garry Marshall sentiment that never challenges either character.', null); # Ladyhawke -> The Other Sister
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (335835, 215879, 3, 'Tomer-Spector', 'Though both are action films about elite operatives with Cruise in a central role, Top Gun has immortal vibes and Mission Impossible II replaced spy craft with John Woo slow-motion and motorcycles. Same lead, opposite tones.', null); # Top Gun -> M:I II
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (177369, 73574, 2, 'Tomer-Spector', 'Though both feature early performances from actors who became major stars, King of Comedy shows De Niro at peak creative control and Critters 3 is a direct-to-video horror that exists because DiCaprio happened to be in it. Recommending them together is absurd.', null); # King of Comedy -> Critters 3
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (164572, 200864, 3, 'Tomer-Spector', 'Though both are films where a charismatic Black lead navigates a complicated social situation with style, Jackie Brown is Tarantino at his most patient and mature and Maid in Manhattan is a paint-by-numbers romcom. Pam Grier''s performance has nothing in common with JLo''s.', null); # Jackie Brown -> Maid in Manhattan
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (291698, 258948, 3, 'Tomer-Spector', 'Though both are thriller films where a disturbing individual manipulates those around them, Se7en uses its villain to interrogate society and Poison Ivy is a B-thriller where Barrymore is the most interesting element in an otherwise routine film.', null); # Se7en -> Poison Ivy
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (210511, 350424, 3, 'Tomer-Spector', 'Though both are psychological films where the protagonist cannot trust his own perception, Memento is architecturally precise and Vanilla Sky is a glossier remake of a Spanish film that works better in its original form.', null); # Memento -> Vanilla Sky
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (123435, 292671, 3, 'Tomer-Spector', 'Though both are psychological thrillers about a man being gaslit by his environment, The Game is Fincher with full control and Secret Window is a King adaptation where you see the twist coming forty minutes out. Same premise, very different execution.', null); # The Game -> Secret Window
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (39551, 1121, 3, 'Tomer-Spector', 'Though both are historical war or expedition films about extraordinary events under extreme conditions, Black Hawk Down is immersive and intense and 1492 has Vangelis doing most of the storytelling because the film itself wanders. The comparison is not flattering to 1492.', null); # Black Hawk Down -> 1492
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (174953, 350189, 3, 'Tomer-Spector', 'Though both are animated fantasy films set in worlds where humans and non-humans coexist uneasily, Nausicaa is Miyazaki at his world-building peak and Vampire Hunter D 2000 is a stylish anime that does not reach the same moral depth. Worth pairing only if you have exhausted Miyazaki.', null); # Nausicaa -> Vampire Hunter D
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (112290, 270628, 2, 'Tomer-Spector', 'Though both are films about men confronting their own sense of powerlessness, Fight Club builds to a philosophically coherent statement and Radio Flyer leans on sentiment where the subject matter demanded more restraint. They are not comparable in ambition or execution.', null); # Fight Club -> Radio Flyer
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (159172, 208245, 3, 'Tomer-Spector', 'Though both are adventure films that run on the chemistry between two leads with different temperaments, Last Crusade has Connery and Ford at their absolute best and Maverick has Gibson and Foster being charming for two hours in a film that goes nowhere especially interesting.', null); # Last Crusade -> Maverick
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (297838, 271344, 2, 'Tomer-Spector', 'Though both are films where a protagonist rebuilds their life through an unexpected connection, Shawshank earns its emotion across a decade of storytelling and Raising Helen is a romcom premise where Hudson is on autopilot. The comparison is not kind to either film.', null); # Shawshank -> Raising Helen

-- ============================================================
-- ADDITIONAL GOOD RECOMMENDATIONS TO REACH 100 -- 19 more
-- ============================================================

insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (267038, 306032, 9, 'Tomer-Spector', 'Pulp Fiction and Snatch are both ensemble crime films that run on interlocking plotlines and people who are very bad at the things they are supposed to be good at. If you love the structure of one you will love the other.', null); # Pulp Fiction -> Snatch
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (40199, 214755, 8, 'Tomer-Spector', 'Blade Runner and Minority Report are both films where a law enforcement officer in a dystopian future questions whether the system he serves is just. Both hold up because the visual world is built well enough that you believe in it.', null); # Blade Runner -> Minority Report
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (271095, 256632, 8, 'Tomer-Spector', 'Raiders and Pirates of the Caribbean are both adventure films built around a charismatic rogue who improvises through impossible situations. Depp''s Sparrow is the closest anyone came to matching Ford''s Indy in that specific register.', null); # Raiders -> Pirates
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (297838, 112290, 8, 'Tomer-Spector', 'Shawshank and Fight Club are both films about men who create a second life inside a system designed to break them. One is about survival through hope, the other is about survival through destruction. They are mirror images.', null); # Shawshank -> Fight Club
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (176712, 164572, 8, 'Tomer-Spector', 'Kill Bill Vol 2 and Jackie Brown are both Tarantino films where the violence steps back and the conversation takes over. Both show he is a better director when he is not trying to be the most stylish person in the room.', null); # Kill Bill Vol 2 -> Jackie Brown
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (256627, 297838, 7, 'Tomer-Spector', 'Pirates of Silicon Valley and Shawshank are both films about what institutional power does to individuals who built something extraordinary inside it. Jobs and Wozniak''s dynamic has more in common with Andy Dufresne than it first appears.', null); # Pirates of Silicon Valley -> Shawshank
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (335835, 109421, 7, 'Tomer-Spector', 'Top Gun and The Fast and the Furious are both films where the plot barely matters because the real film is about belonging to a group of people who are very good at a dangerous thing. Both work entirely because of cast chemistry.', null); # Top Gun -> Fast and Furious
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (40199, 10830, 9, 'Tomer-Spector', 'Blade Runner and Alien are both Ridley Scott films that built worlds convincing enough to sustain entire franchise universes. Both run on atmosphere and dread rather than plot momentum. Watching them together is the best argument for trusting a director with a vision.', null); # Blade Runner -> Alien
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (247579, 291698, 7, 'Tomer-Spector', 'Panic Room and Se7en are both films where Fincher uses the physical architecture of a single location to generate sustained dread. Panic Room is the lighter version but both show his obsession with space as a psychological weapon.', null); # Panic Room -> Se7en

-- ============================================================
-- ADDITIONAL BAD RECOMMENDATIONS TO REACH 100 -- 14 more
-- ============================================================

insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (267038, 200521, 3, 'Tomer-Spector', 'Though both are films where multiple storylines collide in morally complicated ways, Pulp Fiction controls its chaos with precision and Magnolia lets its three hours wander without the same discipline. Cruise''s monologue is great; the rest is more self-important than it earns.', null); # Pulp Fiction -> Magnolia
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (131780, 200521, 3, 'Tomer-Spector', 'Though both are ambitious ensemble films about people whose lives intersect in unexpected ways, Goodfellas is controlled and Magnolia sprawls. Anderson wants Altman''s scale and Scorsese''s intensity and achieves neither fully.', null); # Goodfellas -> Magnolia
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (210511, 350189, 3, 'Tomer-Spector', 'Though both are films about identity and what it means to be human in a world where that line has blurred, Memento uses its structure to force you to experience the protagonist''s disorientation and Vampire Hunter D 2000 is a stylish anime that gestures at those themes without committing.', null); # Memento -> Vampire Hunter D
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (306032, 41518, 3, 'Tomer-Spector', 'Though both are films about charismatic criminals whose success is their downfall, Snatch is relentlessly kinetic and Blow has a more conventional rise-and-fall arc. Snatch rewards repeat viewing; Blow is a one-time watch that does not linger.', null); # Snatch -> Blow
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (238072, 215879, 3, 'Tomer-Spector', 'Though both are glossy films about professionals executing a mission with style, Ocean''s Eleven is a perfectly tuned ensemble piece and Mission Impossible II handed the same format to John Woo who replaced all the elegance with motorcycle ballet.', null); # Ocean's Eleven -> M:I II
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (159172, 159167, 2, 'Tomer-Spector', 'Though both are Indiana Jones films with the same lead, Last Crusade is Spielberg and Ford firing on all cylinders and Kingdom of the Crystal Skull is a film where a fridge and CGI prairie dogs tell you the franchise is over.', null); # Last Crusade -> Indiana Jones 4
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (97727, 34104, 3, 'Tomer-Spector', 'Though both are films about a gentle eccentric who brings charm to a community that does not understand him, Edward Scissorhands has genuine emotional weight behind the fairy tale and Benny and Joon is pleasant without ever reaching for something more.', null); # Edward Scissorhands -> Benny & Joon
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (61751, 214755, 3, 'Tomer-Spector', 'Though both are sci-fi films about a broken future society, Children of Men refuses to offer comfortable solutions and Minority Report resolves its premise with the kind of plot mechanics that undercut the philosophy it set up. Cuaron trusts the audience more.', null); # Children of Men -> Minority Report
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (176711, 118367, 3, 'Tomer-Spector', 'Though both are films featuring Tarantino''s sensibility, Kill Bill Vol 1 is one of his most controlled achievements and Four Rooms is an anthology where the Tarantino segment is surrounded by weaker material. Recommending them together oversells Four Rooms.', null); # Kill Bill Vol 1 -> Four Rooms
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (130953, 354178, 3, 'Tomer-Spector', 'Though both are Bond films, Goldfinger is the franchise at its most confident and A View to a Kill is Moore two films past his expiration date. Walken and Grace Jones are interesting choices who cannot compensate for a lead the film itself knows is too old.', null); # Goldfinger -> View to a Kill
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (129185, 280305, 3, 'Tomer-Spector', 'Though both are films about a champion who loses everything and must rebuild, Gladiator earns its emotional weight through Crowe''s physicality and the scale of what Maximus has lost and Rocky V replaces that weight with a protege plotline nobody asked for.', null); # Gladiator -> Rocky V
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (256632, 370017, 3, 'Tomer-Spector', 'Though both are early-2000s adventure films about a rogue who refuses to follow the rules, Pirates of the Caribbean created a genuinely original character in Jack Sparrow and XXX is Diesel doing Bond parody that never commits to being funny or being serious.', null); # Pirates -> XXX
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (40199, 350189, 3, 'Tomer-Spector', 'Though both are films about synthetic beings navigating a world that is not sure they belong in it, Blade Runner asks the question with the full weight of Philip K Dick and Ridley Scott behind it and Vampire Hunter D 2000 is a stylish anime that raises the same theme as atmosphere rather than argument.', null); # Blade Runner -> Vampire Hunter D
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (159175, 159172, 8, 'Tomer-Spector', 'Temple of Doom and Last Crusade are the two Indiana Jones films that work best as a pair: Doom shows Indy at his darkest and Crusade brings Connery in to give him someone to be vulnerable around. The contrast in tone is why both are worth watching.', null); # Temple of Doom -> Last Crusade
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (280282, 280305, 3, 'Tomer-Spector', 'Though both are Rocky sequels, Rocky III has Mr. T and the Eye of the Tiger and Rocky V has a protege storyline that Stallone himself admitted was the wrong direction. Both are diminishing returns but III at least has one iconic element.', null); # Rocky III -> Rocky V

-- ============================================================
-- REPLACEMENT PAIRS (replacing removed bidirectional duplicates)
-- 12 new unique good recommendations
-- ============================================================

insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (297838, 267038, 9, 'Tomer-Spector', 'Shawshank and Pulp Fiction are the two films from 1994 that people point to when asked what decade-defining cinema looks like. Both are about the gap between how the world is and how it should be, arrived at from completely opposite directions.', null); # Shawshank -> Pulp Fiction
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (131780, 267038, 9, 'Tomer-Spector', 'Goodfellas and Pulp Fiction are the two films that redefined what crime cinema could do. Scorsese''s is a decade-long immersion, Tarantino''s is a single chaotic day. Both reward every rewatch differently.', null); # Goodfellas -> Pulp Fiction
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (40199, 291698, 9, 'Tomer-Spector', 'Blade Runner and Se7en are both films about a detective operating in a city that has already lost. Both use rain, neon and moral exhaustion as their primary visual language. Watching them back to back is a masterclass in atmospheric world-building.', null); # Blade Runner -> Se7en
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (176711, 267038, 8, 'Tomer-Spector', 'Kill Bill Vol 1 and Pulp Fiction are both Tarantino films where genre is just the frame. Both run on dialogue, style and a complete refusal to follow conventional structure. Vol 1 is his most disciplined action film, Fiction is his most disciplined crime film.', null); # Kill Bill Vol 1 -> Pulp Fiction
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (210739, 158999, 8, 'Tomer-Spector', 'Men in Black and Independence Day are both Will Smith films from the 1990s where he anchors a summer blockbuster through pure charisma. Both films would be far less watchable without him and both understand that the spectacle only works if you like the person at the center of it.', null); # Men in Black -> Independence Day
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (276217, 291698, 9, 'Tomer-Spector', 'Reservoir Dogs and Se7en are both films that spend most of their runtime building dread toward a conclusion you cannot stop. Dogs is a single location, Se7en is an entire city. Both understand that what you do not show is more terrifying than what you do.', null); # Reservoir Dogs -> Se7en
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (220276, 256632, 7, 'Tomer-Spector', 'Moulin Rouge and Pirates of the Caribbean both ran on a charismatic lead fully committed to a maximalist performance that should have been embarrassing. McGregor and Depp both swing for it completely and both land. Films with that energy are rare.', null); # Moulin Rouge -> Pirates
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (280270, 39551, 8, 'Tomer-Spector', 'Rocky and Black Hawk Down are both films about what it takes to walk into a fight you might not survive and keep moving. One is a boxing drama, one is a war film, but the emotional engine is the same: you fight because stopping is worse.', null); # Rocky -> Black Hawk Down
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30955, 311037, 8, 'Tomer-Spector', 'Batman 1989 and Spider-Man 2002 are the two superhero films that proved the genre could sustain a serious lead performance. Keaton and Maguire both committed without irony and both films built lasting franchises on that foundation.', null); # Batman 1989 -> Spider-Man
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (164572, 130945, 7, 'Tomer-Spector', 'Jackie Brown and GoldenEye both came out within months of each other in 1997 and both are about a franchise reset through patience. Tarantino slowed Pulp Fiction down, Campbell grounded Bond after a long absence. Both are underappreciated as turning points.', null); # Jackie Brown -> GoldenEye
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (56871, 306032, 8, 'Tomer-Spector', 'Catch Me If You Can and Snatch are both films about a con that runs so well you almost forget to root against the person running it. DiCaprio and Pitt''s Mickey are both so watchable that the mechanics become secondary to the pleasure of watching them work.', null); # Catch Me If You Can -> Snatch

insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (113459, 306032, 7, 'Tomer-Spector', 'Find Me Guilty and Snatch are both ensemble films where a charismatic protagonist holds together a group of criminals through force of personality alone. Diesel''s courtroom performance and Pitt''s Mickey operate on the same principle: be so watchable that the legal situation becomes secondary.', null); # Find Me Guilty -> Snatch


