-- Movie Pairs Ranking
-- suggested_by: oriliss
--
-- I went through the movies I personally ranked and looked for pairs
-- that share something meaningful: same franchise, same director,
-- same lead actor, or similar genre and era.
--
-- For the bad recommendations I looked for pairs where the movies
-- seem similar on the surface but I rated one high and the other low.
-- Those are the most interesting false positives in my opinion.
--
-- Good pairs: 100  |  Bad/unreasonable pairs: 100  |  Total: 200

CREATE TABLE IF NOT EXISTS movies_recommendations (
    base_movie_id       INT          NOT NULL,
    recommended_movie_id INT         NOT NULL,
    recommendation      INT          NOT NULL,   -- 1 bad, 5 neutral, 10 great
    suggested_by        VARCHAR(100) NOT NULL,
    justification       TEXT,
    comment             TEXT
);

-- GOOD RECOMMENDATIONS
-- Both movies are ones I personally rated high and they share a clear connection.

-- --- Franchise / Series pairs ---
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313459, 313478, 10, 'oriliss', 'I am your father — the galaxy''s greatest plot twist. The original and its sequel are inseparable.', 'watched these on DVD back to back, still holds up');  # base: Star Wars 1977, recommended: The Empire Strikes Back 1980
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313478, 313479, 10, 'oriliss', 'Vader''s redemption arc closes perfectly. Two halves of the same brilliant coin.', null);  # base: The Empire Strikes Back 1980, recommended: Return of the Jedi 1983
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (194497, 194502, 10, 'oriliss', 'Helm''s Deep alone is worth the ticket. The stakes double with every frame.', null);  # base: LotR Fellowship, recommended: LotR Two Towers
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (194502, 194500, 10, 'oriliss', 'The greatest finale in fantasy history. Every thread earned over three films.', null);  # base: LotR Two Towers, recommended: LotR Return of the King
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (130128, 130129, 10, 'oriliss', 'Young Vito and fallen Michael — two masterpieces that complete each other.', 'my dad made me watch both in one weekend, best decision he ever made');  # base: Godfather, recommended: Godfather Part II
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (176711, 176712, 10, 'oriliss', 'Vol 1 is pure style, Vol 2 is pure soul. One film in two halves.', null);  # base: Kill Bill Vol 1, recommended: Kill Bill Vol 2
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (337166, 337168, 10, 'oriliss', 'Woody''s existential crisis handled better than most adult films manage.', null);  # base: Toy Story 1995, recommended: Toy Story 2 1999
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (300229, 300230, 10, 'oriliss', 'Puss in Boots enters, the bar goes higher. Sequels rarely pull this off.', null);  # base: Shrek 2001, recommended: Shrek 2 2004
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (86274, 86287, 10, 'oriliss', 'McClane and Jackson, New York as the playground. Pure franchise gold.', null);  # base: Die Hard 1988, recommended: Die Hard With a Vengeance 1995
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (10830, 10920, 10, 'oriliss', 'Same terror, different gear. One horror film, one action film, both perfect.', null);  # base: Alien 1979, recommended: Aliens 1986
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (26844, 26846, 10, 'oriliss', 'The future they imagined still hasn''t arrived. The movie absolutely has.', null);  # base: Back to the Future 1985, recommended: Back to the Future Part II 1989
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (159175, 159172, 10, 'oriliss', 'Indy at his darkest, then at his most charming. Both essential, in that order.', null);  # base: Indiana Jones Temple of Doom, recommended: Indiana Jones Last Crusade
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (280270, 280281, 10, 'oriliss', 'The rematch you were waiting for, with even more to lose.', null);  # base: Rocky 1976, recommended: Rocky II 1979
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (328285, 328277, 10, 'oriliss', 'The machine became the hero. One of cinema''s greatest glow-ups.', null);  # base: Terminator 1984, recommended: Terminator 2 1991
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (311037, 311038, 10, 'oriliss', 'The Doc Ock train fight alone earns its place. Peter Parker''s best chapter.', null);  # base: Spider-Man 2002, recommended: Spider-Man 2 2004
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (369458, 369486, 10, 'oriliss', 'The Nightcrawler White House scene in the first ten minutes. Enough said.', null);  # base: X-Men 2000, recommended: X2 2003
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (45128, 45129, 10, 'oriliss', 'The Moscow car chase is still the best action sequence of the 2000s.', null);  # base: Bourne Identity 2002, recommended: Bourne Supremacy 2004
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (92573, 120574, 10, 'oriliss', 'The train fight with Robert Shaw. Bond perfected before the gadgets took over.', null);  # base: Dr. No 1962, recommended: From Russia with Love 1963
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (120574, 130953, 10, 'oriliss', 'Goldfinger made Bond a cultural phenomenon. The blueprint every spy film follows.', null);  # base: From Russia with Love 1963, recommended: Goldfinger 1964
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (130953, 372233, 10, 'oriliss', 'Volcano lair, Connery at peak cool. The definitive Bond spectacle.', null);  # base: Goldfinger 1964, recommended: You Only Live Twice 1967
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (139655, 139652, 10, 'oriliss', 'Azkaban set the artistic bar; Goblet of Fire raises the stakes with Voldemort''s return.', null);  # base: HP Prisoner of Azkaban, recommended: HP Goblet of Fire
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30955, 30959, 10, 'oriliss', 'Burton''s gothic nightmare meets Nolan''s psychological realism. Both are the character at his best.', null);  # base: Batman 1989, recommended: Batman Begins 2005

-- --- Director pairs ---
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (267038, 276217, 9, 'oriliss', 'Tarantino''s debut has the same snap. Mr. Blonde''s scene lives in the same universe.', null);  # base: Pulp Fiction 1994, recommended: Reservoir Dogs 1992
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (267038, 176711, 9, 'oriliss', 'Same director, same pop-culture rhythm, same electricity. Uma Thurman in yellow.', null);  # base: Pulp Fiction 1994, recommended: Kill Bill Vol 1 2003
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (131780, 82967, 9, 'oriliss', 'Scorsese doing what only he can. Both end exactly as they should.', null);  # base: Goodfellas 1990, recommended: The Departed 2006
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (131780, 56304, 9, 'oriliss', 'Vegas, mob money, Pesci terrifying. The unofficial Scorsese crime trilogy completes itself.', null);  # base: Goodfellas 1990, recommended: Casino 1995
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (131780, 130128, 8, 'oriliss', 'The two pillars of crime cinema. Different tone, equally mandatory.', null);  # base: Goodfellas 1990, recommended: The Godfather 1972
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (291698, 112290, 9, 'oriliss', 'Fincher''s darkest back-to-back. Both end in a way you never see coming.', null);  # base: Se7en 1995, recommended: Fight Club 1999
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (96593, 165961, 8, 'oriliss', 'Spielberg making you cry, then making you grip your seat. Both essential.', null);  # base: E.T. 1982, recommended: Jaws 1975
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (297838, 134077, 9, 'oriliss', 'Darabont, King, a prison, an extraordinary performance. Lightning strikes twice.', 'both on my personal all-time top 10 list');  # base: Shawshank Redemption 1994, recommended: The Green Mile 1999
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30959, 210511, 8, 'oriliss', 'Nolan dark and cerebral in two completely different directions. Both demand a rewatch.', null);  # base: Batman Begins 2005, recommended: Memento 2000
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (40199, 10830, 9, 'oriliss', 'Ridley Scott''s two genre-defining masterpieces. Rain-soaked noir meets claustrophobic space horror.', null);  # base: Blade Runner 1982, recommended: Alien 1979
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (67052, 141544, 9, 'oriliss', 'Mann, neon LA, moral ambiguity — Cruise and De Niro at their sharpest.', null);  # base: Collateral 2004, recommended: Heat 1995
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (340799, 328277, 9, 'oriliss', 'Cameron and Schwarzenegger at full throttle. Both blend laughs and spectacle seamlessly.', null);  # base: True Lies 1994, recommended: Terminator 2 1991
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (352639, 266574, 9, 'oriliss', 'Hitchcock''s obsession double bill. Two films that still define the thriller genre.', null);  # base: Vertigo 1958, recommended: Psycho 1960

-- --- Lead actor pairs ---
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (117874, 56431, 8, 'oriliss', 'Hanks almost alone on screen, carrying the entire film. He does it twice.', null);  # base: Forrest Gump 1994, recommended: Cast Away 2000
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (340901, 104338, 8, 'oriliss', 'Carrey doing what comedy couldn''t contain. Both break your heart in the quietest way.', null);  # base: Truman Show 1998, recommended: Eternal Sunshine 2004
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (326155, 131780, 9, 'oriliss', 'De Niro and Scorsese twice over. Both films you absolutely cannot look away from.', null);  # base: Taxi Driver 1976, recommended: Goodfellas 1990
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (262645, 328285, 8, 'oriliss', 'Arnold against something that cannot be stopped. Two 80s sci-fi action classics.', null);  # base: Predator 1987, recommended: Terminator 1984
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (256632, 82967, 8, 'oriliss', 'Best ensemble acting of the era, two completely different tones, both electric.', null);  # base: Pirates of Caribbean 2003, recommended: The Departed 2006

-- --- Genre / Theme pairs ---
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (301540, 291698, 8, 'oriliss', 'Two villains you never forget. Two endings that sear into your memory.', null);  # base: Silence of the Lambs 1991, recommended: Se7en 1995
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (289109, 257459, 8, 'oriliss', 'Combat without glory. The two most honest American war films ever made.', null);  # base: Saving Private Ryan 1998, recommended: Platoon 1986
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (18960, 121538, 8, 'oriliss', 'One is a fever dream, one is an ice bath. Both Vietnam at its most real.', null);  # base: Apocalypse Now 1979, recommended: Full Metal Jacket 1987
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (210511, 90772, 8, 'oriliss', 'Two films that reward every rewatch with something new. Early 2000s at their sharpest.', null);  # base: Memento 2000, recommended: Donnie Darko 2001
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (104338, 210511, 8, 'oriliss', 'Non-linear storytelling used to expose emotional truth. Both demand a second viewing.', null);  # base: Eternal Sunshine 2004, recommended: Memento 2000
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (13978, 13789, 7, 'oriliss', 'The dark heart of America examined from two angles. Both unforgettable.', null);  # base: American History X 1998, recommended: American Beauty 1999
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (969, 111813, 8, 'oriliss', 'All dialogue, no action, unbearable tension. The courtroom genre''s two finest hours.', null);  # base: 12 Angry Men 1957, recommended: A Few Good Men 1992
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (113504, 218415, 8, 'oriliss', 'Pixar''s back-to-back golden era. Both will make you cry before the credits roll.', null);  # base: Finding Nemo 2003, recommended: Monsters Inc 2001
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (158927, 337166, 8, 'oriliss', 'Pixar working on two levels at once. The two best films in their catalogue.', null);  # base: The Incredibles 2004, recommended: Toy Story 1995
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (191246, 32178, 8, 'oriliss', 'The Disney Renaissance at its absolute peak. Both are timeless.', 'Disney golden era, nothing from the last 20 years comes close');  # base: Lion King 1994, recommended: Beauty and the Beast 1991
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (191246, 9795, 8, 'oriliss', 'Same era, same magic, same Menken score energy. Essential double bill.', null);  # base: Lion King 1994, recommended: Aladdin 1992
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (32178, 367073, 7, 'oriliss', 'Two fairy-tale musicals that transcend their era. Both carry more weight than expected.', null);  # base: Beauty and the Beast 1991, recommended: Wizard of Oz 1939
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (280270, 129185, 7, 'oriliss', 'Boxing ring and Colosseum, same underdog soul. Both make you want to stand up.', null);  # base: Rocky 1976, recommended: Gladiator 2000
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (46169, 129185, 8, 'oriliss', 'Freedom against empire, sweeping historical epics. The genre''s twin peaks.', 'perfect double bill for a long evening');  # base: Braveheart 1995, recommended: Gladiator 2000
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (207992, 40199, 7, 'oriliss', 'Both redefined sci-fi''s visual language. Both ask who you really are.', null);  # base: Matrix 1999, recommended: Blade Runner 1982
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (280115, 86274, 8, 'oriliss', 'Best Die Hard film not called Die Hard. Same DNA, same everyman energy.', null);  # base: The Rock 1996, recommended: Die Hard 1988
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (310726, 86274, 8, 'oriliss', 'If the bus drops below 50mph, it explodes. That is pure McClane energy.', null);  # base: Speed 1994, recommended: Die Hard 1988
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (165961, 10830, 8, 'oriliss', 'Restraint over spectacle. Both create terror from what you cannot see.', null);  # base: Jaws 1975, recommended: Alien 1979
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (49696, 346949, 8, 'oriliss', 'Opera and deconstruction. The western genre''s two greatest achievements.', null);  # base: The Good Bad and Ugly 1966, recommended: Unforgiven 1992
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (346949, 335245, 8, 'oriliss', 'One tears the myth apart, the other celebrates it. Val Kilmer steals the latter.', null);  # base: Unforgiven 1992, recommended: Tombstone 1993
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (266574, 301540, 8, 'oriliss', 'Norman Bates meets Hannibal Lecter. The psychological thriller genre''s hall of fame.', null);  # base: Psycho 1960, recommended: Silence of the Lambs 1991
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (141544, 131780, 8, 'oriliss', 'American crime epics that reward patience. Both finales feel completely earned.', null);  # base: Heat 1995, recommended: Goodfellas 1990
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (193253, 276217, 7, 'oriliss', 'Fast-talking criminals, dark comedy, ensemble chaos. Best British-American crime pair.', null);  # base: Lock Stock 1998, recommended: Reservoir Dogs 1992
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (45128, 215876, 7, 'oriliss', 'The two spy franchises that reinvented the genre for the 2000s.', null);  # base: Bourne Identity 2002, recommended: Mission Impossible 1996
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (235541, 362808, 7, 'oriliss', 'Sweeping passion and sharp wit. Two romance films that do the genre right.', null);  # base: The Notebook 2004, recommended: When Harry Met Sally 1989
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (263360, 235790, 7, 'oriliss', 'Julia Roberts fairy-tale formula, both times it works perfectly.', null);  # base: Pretty Woman 1990, recommended: Notting Hill 1999
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (348944, 291698, 8, 'oriliss', 'The two best twist endings of the 1990s. Both plant their clues in plain sight.', null);  # base: Usual Suspects 1995, recommended: Se7en 1995
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (131885, 313059, 8, 'oriliss', 'The last summer of childhood captured twice. Both feel like pure memory.', null);  # base: Goonies 1985, recommended: Stand by Me 1986
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (26844, 134672, 7, 'oriliss', 'The two cleverest time comedies ever made. Both sneak real emotion under the laughs.', null);  # base: Back to the Future 1985, recommended: Groundhog Day 1993
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (270971, 280270, 8, 'oriliss', 'Brutal character study and triumphant underdog. Boxing cinema''s two essential films.', null);  # base: Raging Bull 1980, recommended: Rocky 1976
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (64093, 280270, 8, 'oriliss', 'True underdogs fighting for more than a title. Both land the same emotional punch.', null);  # base: Cinderella Man 2005, recommended: Rocky 1976
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (275453, 66286, 7, 'oriliss', 'Coaches who changed teams and lives. Two of the best sports inspiration films.', null);  # base: Remember the Titans 2000, recommended: Coach Carter 2005
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (77728, 185628, 8, 'oriliss', 'A soldier finds meaning in a culture facing extinction. Both are deeply moving.', null);  # base: Dances with Wolves 1990, recommended: Last Samurai 2003
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (303564, 244458, 8, 'oriliss', 'Two slow-burn supernatural mysteries with endings that reframe everything.', null);  # base: Sixth Sense 1999, recommended: The Others 2001
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (90772, 342384, 7, 'oriliss', 'Reality bending, haunting, a fragile protagonist you cannot stop watching.', null);  # base: Donnie Darko 2001, recommended: Twelve Monkeys 1995
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (18960, 39551, 7, 'oriliss', 'Surreal nightmare meets documentary chaos. War''s two most overwhelming depictions.', null);  # base: Apocalypse Now 1979, recommended: Black Hawk Down 2001
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (101055, 289109, 8, 'oriliss', 'Two WWII films placing individual heroism inside catastrophic historical scale.', null);  # base: Enemy at the Gates 2001, recommended: Saving Private Ryan 1998
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (319602, 30959, 7, 'oriliss', 'The two best superhero origin stories before the MCU era. Both have genuine weight.', null);  # base: Superman 1978, recommended: Batman Begins 2005
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (10920, 262645, 8, 'oriliss', 'Marines vs. alien predators. The two greatest sci-fi action films of the 1980s.', null);  # base: Aliens 1986, recommended: Predator 1987
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (61751, 40199, 7, 'oriliss', 'Two dystopian visions of stunning beauty and profound human sadness.', null);  # base: Children of Men 2006, recommended: Blade Runner 1982
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (2000, 10830, 7, 'oriliss', 'Isolation, claustrophobia, something hunting you. Terror built from the same formula.', null);  # base: 28 Days Later 2002, recommended: Alien 1979
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (302329, 2238, 8, 'oriliss', 'Graphic novel aesthetics pushed to their live-action limit. Both are immersive.', null);  # base: Sin City 2005, recommended: 300 2006
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (297838, 32114, 7, 'oriliss', 'Brilliant men unjustly confined, triumphing through resilience. Both profoundly uplifting.', null);  # base: Shawshank Redemption 1994, recommended: Beautiful Mind 2001
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (56044, 131240, 7, 'oriliss', 'Golden Hollywood romance against a backdrop of war. Essential double-bill.', null);  # base: Casablanca 1942, recommended: Gone with the Wind 1939
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (307913, 56044, 7, 'oriliss', 'Classic Hollywood at its absolute peak. Different tones, equally essential.', null);  # base: Some Like It Hot 1959, recommended: Casablanca 1942
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (328277, 207992, 7, 'oriliss', 'Two films that redefined action-sci-fi for their decade. Both are groundbreaking.', null);  # base: Terminator 2 1991, recommended: Matrix 1999
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (300229, 113504, 7, 'oriliss', 'Animated filmmaking at its absolute peak. Both deliver genuine adult emotion.', null);  # base: Shrek 2001, recommended: Finding Nemo 2003
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (218415, 113504, 8, 'oriliss', 'Pixar''s back-to-back masterpieces. Both will make you cry by the final scene.', null);  # base: Monsters Inc 2001, recommended: Finding Nemo 2003
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (173933, 280270, 8, 'oriliss', 'Mr. Miyagi and Mickey. Both mentor-student finales deliver the same catharsis.', null);  # base: Karate Kid 1984, recommended: Rocky 1976
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (185628, 77728, 8, 'oriliss', 'A disillusioned soldier rediscovering humanity in a culture on the brink.', null);  # base: Last Samurai 2003, recommended: Dances with Wolves 1990
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (333856, 263360, 7, 'oriliss', 'Grand tragedy and fairy tale. Both are 1990s romance icons.', null);  # base: Titanic 1997, recommended: Pretty Woman 1990
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (56871, 141544, 7, 'oriliss', 'Cat-and-mouse crime, playful and dark. Both reward with compelling criminal leads.', null);  # base: Catch Me If You Can 2002, recommended: Heat 1995
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (188507, 86274, 8, 'oriliss', 'Riggs and McClane, the 80s action genre''s two most iconic heroes.', null);  # base: Lethal Weapon 1987, recommended: Die Hard 1988
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (272644, 218415, 8, 'oriliss', 'A misfit pursuing passion against the world''s doubt. Pixar formula at its best.', null);  # base: Ratatouille 2006, recommended: Monsters Inc 2001
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (13789, 340901, 7, 'oriliss', 'Both expose the false comfort of the apparently perfect life. Late-90s satire at its sharpest.', null);  # base: American Beauty 1999, recommended: Truman Show 1998
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (114067, 68309, 7, 'oriliss', 'The 80s one-man-army genre in two moods. Emotional and pure mayhem, both essential.', null);  # base: First Blood 1982, recommended: Commando 1985



-- a few more good pairs I wanted to include
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (82967, 56304, 9, 'oriliss', 'Scorsese corruption arcs in two different cities. Both end in an explosion of consequence.', null);  # base: The Departed 2006, recommended: Casino 1995
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (111813, 297838, 7, 'oriliss', 'Fighting for truth against a system built to bury it. Extraordinary performances drive both.', null);  # base: A Few Good Men 1992, recommended: Shawshank Redemption 1994
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (113504, 272644, 8, 'oriliss', 'Two Pixar films about defying what the world says you can be.', null);  # base: Finding Nemo 2003, recommended: Ratatouille 2006
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30955, 2238, 7, 'oriliss', 'Both turn their world into a graphic novel. Hyper-stylised and unforgettable.', null);  # base: Batman 1989, recommended: 300 2006


-- NOT GOOD YET REASONABLE RECOMMENDATIONS:
-- These pairs share something on the surface but I rated one high and the other low.


-- --- Franchise false positives ---
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313478, 313474, 1, 'oriliss', 'Though both are Star Wars films, it is a bad recommendation since Phantom Menace trades the original trilogy''s soul for trade politics and Jar Jar.', 'Phantom Menace is the most disappointing film I have ever seen after such a great original');  # base: The Empire Strikes Back 1980, recommended: The Phantom Menace 1999
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313459, 313476, 1, 'oriliss', 'Though both are Star Wars films, it is a bad recommendation since Attack of the Clones replaces the lived-in charm with wooden romance and wall-to-wall CGI.', null);  # base: Star Wars 1977, recommended: Attack of the Clones 2002
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (311038, 311040, 3, 'oriliss', 'Though both are Sam Raimi Spider-Man films, it is a bad recommendation since Spider-Man 3 is undone by too many villains and the infamous emo Peter Parker dance scene.', 'Spider-Man 3 genuinely upset me after how good part 2 was');  # base: Spider-Man 2 2004, recommended: Spider-Man 3 2007
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (159172, 159167, 1, 'oriliss', 'Though both are Indiana Jones adventures, it is a bad recommendation since Crystal Skull has a man surviving a nuclear blast inside a fridge.', null);  # base: Indiana Jones Last Crusade 1989, recommended: Indiana Jones 4 2006
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (26844, 26847, 2, 'oriliss', 'Though both are Back to the Future films, it is a bad recommendation since Part III drains all the wit and energy into an uninspired western setting.', null);  # base: Back to the Future 1985, recommended: Back to the Future Part III 1990
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (26846, 26847, 2, 'oriliss', 'Though both are Back to the Future sequels, it is a bad recommendation since Part III trades clever time paradoxes for a predictable western love story.', null);  # base: Back to the Future Part II 1989, recommended: Back to the Future Part III 1990
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (173933, 173931, 3, 'oriliss', 'Though both are Karate Kid films, it is a bad recommendation since Part II dilutes the mentor-student bond with a formulaic Okinawa relocation.', null);  # base: Karate Kid 1984, recommended: Karate Kid Part II 1986
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (280270, 280284, 3, 'oriliss', 'Though both are Rocky films, it is a bad recommendation since Rocky IV abandons character drama for Cold War propaganda and training montages.', null);  # base: Rocky 1976, recommended: Rocky IV 1985
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (311037, 311040, 3, 'oriliss', 'Though both are from the original Spider-Man trilogy, it is a bad recommendation since Spider-Man 3 crams in too many storylines and delivers none of them with heart.', null);  # base: Spider-Man 2002, recommended: Spider-Man 3 2007
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (280281, 280284, 3, 'oriliss', 'Though both are Rocky sequels, it is a bad recommendation since Rocky IV trades emotional realism for over-the-top Cold War spectacle.', null);  # base: Rocky II 1979, recommended: Rocky IV 1985
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (139655, 139650, 3, 'oriliss', 'Though both are Harry Potter films, it is a bad recommendation since Chamber of Secrets is the weakest entry, lacking the darkness that makes Azkaban so compelling.', null);  # base: HP Prisoner of Azkaban 2004, recommended: HP Chamber of Secrets 2002
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313479, 313474, 3, 'oriliss', 'Though both are Star Wars films, it is a bad recommendation since Phantom Menace''s trade-federation plot and Jar Jar are a brutal comedown after Jedi''s emotional finale.', null);  # base: Return of the Jedi 1983, recommended: Phantom Menace 1999

-- --- Superhero false positives ---
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (158927, 108760, 2, 'oriliss', 'Though both feature a superhero team, it is a bad recommendation since Fantastic Four feels like a cheap TV movie next to Pixar''s craftsmanship.', null);  # base: The Incredibles 2004, recommended: Fantastic Four 2005
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (319602, 108760, 2, 'oriliss', 'Though both are superhero origin stories, it is a bad recommendation since Fantastic Four''s flat characters disappoint fans of Reeve''s iconic Superman.', null);  # base: Superman 1978, recommended: Fantastic Four 2005
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (319602, 152426, 2, 'oriliss', 'Though both feature enormously powerful heroes, it is a bad recommendation since Ang Lee''s Hulk suffers from comic-panel editing and a meandering plot.', null);  # base: Superman 1978, recommended: Hulk 2003
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30959, 152426, 2, 'oriliss', 'Though both attempt a serious superhero origin, it is a bad recommendation since Hulk''s execution is incoherent where Batman Begins is precise.', null);  # base: Batman Begins 2005, recommended: Hulk 2003
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (369458, 152426, 2, 'oriliss', 'Though both are early-2000s superhero ensemble films, it is a bad recommendation since Hulk''s unfocused story makes it a poor follow-up to X-Men''s sharp storytelling.', null);  # base: X-Men 2000, recommended: Hulk 2003

-- --- War film false positives ---
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (289109, 251477, 1, 'oriliss', 'Though both are set during WWII, it is a bad recommendation since Pearl Harbor sacrifices authenticity for a bloated three-hour love triangle.', 'watched Pearl Harbor right after Ryan - do not make this mistake');  # base: Saving Private Ryan 1998, recommended: Pearl Harbor 2001
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (18960, 360480, 2, 'oriliss', 'Though both are war films, it is a bad recommendation since We Were Soldiers is formulaic and earnest where Apocalypse Now is hallucinatory and profound.', null);  # base: Apocalypse Now 1979, recommended: We Were Soldiers 2002
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (257459, 360480, 2, 'oriliss', 'Though both depict American soldiers in Southeast Asian jungle combat, it is a bad recommendation since We Were Soldiers'' heroic framing lacks Platoon''s moral devastation.', null);  # base: Platoon 1986, recommended: We Were Soldiers 2002
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (121538, 360480, 2, 'oriliss', 'Though both are gritty American war films, it is a bad recommendation since We Were Soldiers leans into sentimentality while Kubrick deliberately withholds it.', null);  # base: Full Metal Jacket 1987, recommended: We Were Soldiers 2002
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (289109, 101055, 2, 'oriliss', 'Though both are WWII combat films, it is a bad recommendation since Enemy at the Gates lacks the immersive scope of Spielberg''s opening thirty minutes.', null);  # base: Saving Private Ryan 1998, recommended: Enemy at the Gates 2001

-- --- Animated film false positives ---
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (191246, 155213, 2, 'oriliss', 'Though both are animated films about animals, it is a bad recommendation since Ice Age lacks the Lion King''s Shakespearean story, emotional depth, and Hans Zimmer score.', null);  # base: Lion King 1994, recommended: Ice Age 2002
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (337166, 155213, 2, 'oriliss', 'Though both are early computer-animated family films, it is a bad recommendation since Ice Age substitutes Toy Story''s emotional intelligence for slapstick and a thin road-trip premise.', null);  # base: Toy Story 1995, recommended: Ice Age 2002
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (113504, 190869, 2, 'oriliss', 'Though both are about belonging and family bonds, it is a bad recommendation since Lilo and Stitch, while charming, lacks Nemo''s precision, visual wonder, and emotional devastation.', null);  # base: Finding Nemo 2003, recommended: Lilo & Stitch 2002
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (158927, 199255, 2, 'oriliss', 'Though both are animated ensemble comedies, it is a bad recommendation since Madagascar''s thin premise feels shallow next to The Incredibles'' tight narrative and genuine emotional stakes.', null);  # base: The Incredibles 2004, recommended: Madagascar 2005
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (300229, 199255, 2, 'oriliss', 'Though both are DreamWorks animated comedies with talking animals, it is a bad recommendation since Madagascar repeats Shrek''s formula without any of its wit or fairy-tale subversion.', null);  # base: Shrek 2001, recommended: Madagascar 2005
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (191246, 325098, 2, 'oriliss', 'Though both are Disney animated films about a young protagonist in a wild natural world, it is a bad recommendation since Tarzan''s Phil Collins soundtrack can''t match the Lion King''s Shakespearean depth.', null);  # base: Lion King 1994, recommended: Tarzan 1999
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (32178, 325098, 2, 'oriliss', 'Though both feature an outsider falling in love in an exotic setting, it is a bad recommendation since Tarzan''s thin romance makes it a poor substitute for Beauty and the Beast''s timeless fairy tale.', null);  # base: Beauty and the Beast 1991, recommended: Tarzan 1999

-- --- Sci-fi / action false positives ---
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (207992, 102225, 1, 'oriliss', 'Though both feature a protagonist discovering truth in a dystopian society, it is a bad recommendation since Equilibrium is a pale imitation without The Matrix''s philosophical depth or visual impact.', null);  # base: Matrix 1999, recommended: Equilibrium 2002
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (40199, 102225, 2, 'oriliss', 'Though both are set in oppressive dystopian futures, it is a bad recommendation since Equilibrium borrows Blade Runner''s aesthetic without approaching its emotional or philosophical complexity.', null);  # base: Blade Runner 1982, recommended: Equilibrium 2002
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (214755, 102225, 2, 'oriliss', 'Though both are sci-fi films about state control of human thought, it is a bad recommendation since Equilibrium''s gun-kata gimmick can''t compensate for its shallow characterisation.', null);  # base: Minority Report 2002, recommended: Equilibrium 2002
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (328277, 336458, 2, 'oriliss', 'Though both are Schwarzenegger sci-fi spectacles, it is a bad recommendation since Total Recall''s unresolved dream-logic is more frustrating than Terminator 2''s satisfying emotional arc.', null);  # base: Terminator 2 1991, recommended: Total Recall 1990
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (262645, 68309, 2, 'oriliss', 'Though both are 80s Schwarzenegger action films, it is a bad recommendation since Commando''s cartoonish one-liners lack Predator''s genuine tension and creature-design dread.', null);  # base: Predator 1987, recommended: Commando 1985
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (10830, 158999, 2, 'oriliss', 'Though both feature alien threats to humanity, it is a bad recommendation since Independence Day''s jingoistic disaster formula is the opposite of Alien''s claustrophobic horror.', null);  # base: Alien 1979, recommended: Independence Day 1996
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (214755, 336458, 2, 'oriliss', 'Though both are sci-fi films concerning Mars, it is a bad recommendation since Total Recall''s convoluted dream-logic disappoints fans of Minority Report''s tight pre-crime narrative.', null);  # base: Minority Report 2002, recommended: Total Recall 1990
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (328285, 279841, 2, 'oriliss', 'Though both feature a machine-like protagonist in an urban environment, it is a bad recommendation since RoboCop''s satirical tone is jarring for fans expecting Terminator''s cold relentless dread.', null);  # base: Terminator 1984, recommended: RoboCop 1987

-- --- Crime / thriller false positives ---
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (130128, 27168, 2, 'oriliss', 'Though both are crime films, it is a bad recommendation since Bad Boys is flashy buddy-cop entertainment while The Godfather is a meditation on power, loyalty, and family.', null);  # base: Godfather 1972, recommended: Bad Boys 1995
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (82967, 27168, 2, 'oriliss', 'Though both are crime films with charismatic protagonists, it is a bad recommendation since Bad Boys'' comedy formula can''t deliver The Departed''s moral gravity or devastating finale.', null);  # base: The Departed 2006, recommended: Bad Boys 1995
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (131780, 112290, 2, 'oriliss', 'Though both explore the seductive pull of a transgressive life, it is a bad recommendation since Fight Club''s nihilism is designed to frustrate where Goodfellas builds a richly satisfying narrative.', null);  # base: Goodfellas 1990, recommended: Fight Club 1999
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (297838, 112290, 1, 'oriliss', 'Though both are about men finding meaning within a constraining system, it is a bad recommendation since Fight Club''s nihilism is the tonal opposite of Shawshank''s deeply hopeful conclusion.', null);  # base: Shawshank Redemption 1994, recommended: Fight Club 1999
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (301540, 54209, 2, 'oriliss', 'Though both feature a terrifying antagonist psychologically tormenting the protagonist, it is a bad recommendation since Cape Fear is a conventional revenge thriller compared to Silence of the Lambs.', null);  # base: Silence of the Lambs 1991, recommended: Cape Fear 1991
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (266574, 54209, 2, 'oriliss', 'Though both are psychological thrillers with a menacing villain, it is a bad recommendation since Cape Fear lacks the formal innovation that makes Psycho a permanent landmark.', null);  # base: Psycho 1960, recommended: Cape Fear 1991
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (82967, 215876, 3, 'oriliss', 'Though both involve infiltrating a dangerous criminal organisation, it is a bad recommendation since Mission Impossible''s popcorn-spy formula is too lightweight for fans of The Departed''s brutal moral complexity.', null);  # base: The Departed 2006, recommended: Mission Impossible 1996

-- --- Romantic / drama false positives ---
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (235541, 2709, 3, 'oriliss', 'Though both are romance films shaped by memory loss, it is a bad recommendation since 50 First Dates uses its premise as a comedy gimmick while The Notebook uses it to devastate.', null);  # base: The Notebook 2004, recommended: 50 First Dates 2004
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (104338, 2709, 2, 'oriliss', 'Though both link erased memories to romantic love, it is a bad recommendation since 50 First Dates is a breezy Sandler comedy while Eternal Sunshine is a devastating meditation on heartbreak.', null);  # base: Eternal Sunshine 2004, recommended: 50 First Dates 2004
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (263360, 360723, 3, 'oriliss', 'Though both are crowd-pleasing romantic comedies, it is a bad recommendation since The Wedding Singer lacks Pretty Woman''s iconic chemistry and lasting cultural impact.', null);  # base: Pretty Woman 1990, recommended: Wedding Singer 1998
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (362808, 146780, 2, 'oriliss', 'Though both are NYC romantic comedies with a charming male lead, it is a bad recommendation since Hitch is a formulaic studio product without the wit or iconic dialogue of When Harry Met Sally.', null);  # base: When Harry Met Sally 1989, recommended: Hitch 2005
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (56044, 304829, 2, 'oriliss', 'Though both are romantic films about love separated by impossible circumstances, it is a bad recommendation since Sleepless in Seattle cannot deliver Casablanca''s moral grandeur or emotional devastation.', null);  # base: Casablanca 1942, recommended: Sleepless in Seattle 1993
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (134672, 37002, 2, 'oriliss', 'Though both are comedies about a man navigating an unusual domestic situation, it is a bad recommendation since Big Daddy''s crude humour is juvenile compared to Groundhog Day''s philosophical depth.', null);  # base: Groundhog Day 1993, recommended: Big Daddy 1999
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (134672, 2709, 2, 'oriliss', 'Though both use memory and repetition as a comedic device, it is a bad recommendation since 50 First Dates plays purely for laughs while Groundhog Day builds genuine meaning from the same concept.', null);  # base: Groundhog Day 1993, recommended: 50 First Dates 2004

-- --- Historical / epic false positives ---
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (46169, 250746, 3, 'oriliss', 'Though both are Mel Gibson historical epics about fighting for freedom, it is a bad recommendation since The Patriot recycles Braveheart''s formula without its passion or iconic speeches.', null);  # base: Braveheart 1995, recommended: The Patriot 2000
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (129185, 340652, 2, 'oriliss', 'Though both are ancient-world epics with a warrior hero, it is a bad recommendation since Troy''s screenplay and miscast Brad Pitt make it a frustrating watch for fans of Gladiator''s grandeur.', null);  # base: Gladiator 2000, recommended: Troy 2004
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (46169, 340652, 2, 'oriliss', 'Though both are epic battle films with a singular warrior hero, it is a bad recommendation since Troy lacks the emotional authenticity of Braveheart — Wallace''s cause feels real, Achilles''s doesn''t.', null);  # base: Braveheart 1995, recommended: Troy 2004
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (129185, 177636, 2, 'oriliss', 'Though both are Ridley Scott historical epics with a conflicted warrior, it is a bad recommendation since Kingdom of Heaven''s theatrical cut is undercooked compared to Gladiator''s perfectly paced spectacle.', null);  # base: Gladiator 2000, recommended: Kingdom of Heaven 2005
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (346949, 250746, 2, 'oriliss', 'Though both feature a reluctant warrior drawn back into violence, it is a bad recommendation since The Patriot''s melodramatic backdrop cannot match Unforgiven''s moral deconstruction of the western myth.', null);  # base: Unforgiven 1992, recommended: The Patriot 2000

-- --- Mind-bending / thriller false positives ---
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (348944, 342384, 2, 'oriliss', 'Though both are mind-bending thrillers with unreliable narration, it is a bad recommendation since Twelve Monkeys'' time-travel complexity frustrates in ways The Usual Suspects never does.', null);  # base: Usual Suspects 1995, recommended: Twelve Monkeys 1995
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (340901, 48075, 2, 'oriliss', 'Though both are high-concept Jim Carrey films with an ordinary man in an extraordinary situation, it is a bad recommendation since Bruce Almighty reduces its concept to crude comedy while Truman Show builds genuine profundity.', null);  # base: Truman Show 1998, recommended: Bruce Almighty 2003
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (303564, 134193, 1, 'oriliss', 'Though both involve creatures that exist outside the normal world, it is a bad recommendation since Gremlins is campy Christmas comedy while The Sixth Sense is a slow-burn psychological drama.', null);  # base: Sixth Sense 1999, recommended: Gremlins 1984
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (210511, 5573, 1, 'oriliss', 'Though both feature a protagonist who struggles to retain memory, it is a bad recommendation since Ace Ventura is broad physical comedy and Memento is a tightly constructed psychological thriller.', null);  # base: Memento 2000, recommended: Ace Ventura 1994

-- --- Comedy false positives ---
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (267038, 37178, 1, 'oriliss', 'Though both are quirky American cult films with unconventional characters, it is a bad recommendation since Lebowski''s slow meandering pace frustrates fans expecting Pulp Fiction''s propulsive style.', null);  # base: Pulp Fiction 1994, recommended: Big Lebowski 1998
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (13789, 14131, 2, 'oriliss', 'Though both feature American characters confronting sexuality and social identity, it is a bad recommendation since American Pie''s gross-out comedy is a world apart from American Beauty''s dark critique.', null);  # base: American Beauty 1999, recommended: American Pie 1999
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (117874, 239786, 1, 'oriliss', 'Though both are American comedies following a likeable protagonist through life, it is a bad recommendation since Old School''s frat-house shock comedy is tonally the opposite of Forrest Gump''s warmth.', 'a friend suggested this combo - completely wrong vibe');  # base: Forrest Gump 1994, recommended: Old School 2003
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (301540, 48075, 2, 'oriliss', 'Though both prominently feature Morgan Freeman as a wise authority figure, it is a bad recommendation since Bruce Almighty is a broad Carrey comedy while Silence of the Lambs is a chilling thriller.', null);  # base: Silence of the Lambs 1991, recommended: Bruce Almighty 2003

-- --- Adventure / treasure hunt false positives ---
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (256632, 228313, 2, 'oriliss', 'Though both feature a charismatic lead hunting legendary hidden treasure, it is a bad recommendation since National Treasure''s flat characters cannot deliver Pirates'' swashbuckling wit and Johnny Depp magic.', null);  # base: Pirates of Caribbean 2003, recommended: National Treasure 2004
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (194497, 63208, 2, 'oriliss', 'Though both are fantasy epics about unlikely heroes journeying to defeat an ancient evil, it is a bad recommendation since Narnia lacks the depth, scale, and emotional weight of Tolkien''s world.', null);  # base: LotR Fellowship 2001, recommended: Chronicles of Narnia 2005
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (159175, 163715, 2, 'oriliss', 'Though both feature a witty protagonist outwitting adversaries in exotic locations, it is a bad recommendation since The Italian Job''s generic remake cannot match Indy''s imagination or iconic set pieces.', null);  # base: Temple of Doom 1984, recommended: Italian Job 2003

-- --- Sports false positives ---
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (280270, 66286, 3, 'oriliss', 'Though both are sports films about an underdog overcoming the odds, it is a bad recommendation since Coach Carter is formulaic feel-good sports without Rocky''s cinematic innovation.', null);  # base: Rocky 1976, recommended: Coach Carter 2005
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (64093, 66286, 2, 'oriliss', 'Though both are sports dramas about coaches transforming struggling teams, it is a bad recommendation since Coach Carter is a more generic execution of the formula Cinderella Man applies with far more nuance.', null);  # base: Cinderella Man 2005, recommended: Coach Carter 2005

-- --- Tom Cruise false positives ---
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (335835, 278855, 2, 'oriliss', 'Though both are iconic Tom Cruise vehicles, it is a bad recommendation since Risky Business is a quiet coming-of-age drama while Top Gun is a loud aerobatic spectacle.', null);  # base: Top Gun 1986, recommended: Risky Business 1983
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (335835, 215876, 3, 'oriliss', 'Though both are high-octane Tom Cruise action films, it is a bad recommendation since Mission Impossible''s Cold War intrigue disappoints fans of Top Gun''s visceral aerial combat and emotional simplicity.', null);  # base: Top Gun 1986, recommended: Mission Impossible 1996

-- --- Miscellaneous theme false positives ---
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (13978, 112290, 2, 'oriliss', 'Though both are Edward Norton films exploring dark American male identity, it is a bad recommendation since Fight Club''s nihilistic twists frustrate fans of American History X''s direct moral clarity.', null);  # base: American History X 1998, recommended: Fight Club 1999
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (165961, 134193, 2, 'oriliss', 'Though both are creature-horror films about a small community threatened by a monster, it is a bad recommendation since Gremlins is campy Christmas-horror comedy while Jaws is a masterwork of sustained suspense.', null);  # base: Jaws 1975, recommended: Gremlins 1984
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (297838, 66286, 2, 'oriliss', 'Though both feature an authority figure guiding men toward growth through discipline, it is a bad recommendation since Coach Carter''s basketball-court inspiration feels modest next to Shawshank''s examination of hope and freedom.', null);  # base: Shawshank Redemption 1994, recommended: Coach Carter 2005
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (90772, 375745, 2, 'oriliss', 'Though both feature a mysterious stranger upending ordinary community life, it is a bad recommendation since Zonad is low-budget absurdist comedy that cannot match Donnie Darko''s haunting atmosphere.', null);  # base: Donnie Darko 2001, recommended: Zonad 2003
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (96593, 190869, 3, 'oriliss', 'Though both are about a child bonding with an alien creature not of their world, it is a bad recommendation since Lilo and Stitch''s family comedy lacks the spiritual longing and magic Spielberg wove into E.T.', null);  # base: E.T. 1982, recommended: Lilo & Stitch 2002
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (367073, 206881, 2, 'oriliss', 'Though both are classic Hollywood musicals featuring a magical figure transporting someone into wonder, it is a bad recommendation since Mary Poppins'' vaudeville whimsy feels slight compared to Wizard of Oz''s timeless journey.', null);  # base: Wizard of Oz 1939, recommended: Mary Poppins 1964
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (309634, 361688, 2, 'oriliss', 'Though both are classic Hollywood musicals with iconic scores and star-crossed romance, it is a bad recommendation since West Side Story''s gang-war tragedy is tonally bleak for fans of Sound of Music''s warmth.', null);  # base: Sound of Music 1965, recommended: West Side Story 1961
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (185628, 177636, 2, 'oriliss', 'Though both feature a conflicted Western warrior immersed in a culture on the brink, it is a bad recommendation since Kingdom of Heaven''s theatrical cut lacks The Last Samurai''s emotional intimacy.', null);  # base: Last Samurai 2003, recommended: Kingdom of Heaven 2005
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (111813, 76382, 2, 'oriliss', 'Though both feature a protagonist uncovering a hidden truth through a dramatic revelation, it is a bad recommendation since Da Vinci Code''s exposition-heavy conspiracy plotting cannot match A Few Good Men''s courtroom electricity.', null);  # base: A Few Good Men 1992, recommended: Da Vinci Code 2006
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (176711, 215880, 2, 'oriliss', 'Though both feature a skilled operative on a vengeance-driven mission through stylised action, it is a bad recommendation since Mission Impossible III''s slick spy formula lacks the operatic fury and Tarantino-directed punch of Kill Bill.', null);  # base: Kill Bill Vol 1 2003, recommended: Mission Impossible III 2006


-- more bad/unreasonable pairs
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (39551, 360480, 2, 'oriliss', 'Though both are intense modern military combat films, it is a bad recommendation since We Were Soldiers is more sentimental compared to Black Hawk Down''s punishing documentary-like immersion.', null);  # base: Black Hawk Down 2001, recommended: We Were Soldiers 2002
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (96593, 199255, 2, 'oriliss', 'Though both feature creatures far outside their natural habitat, it is a bad recommendation since Madagascar reduces the premise to pop-culture gags while E.T. delivers genuine spiritual longing.', null);  # base: E.T. 1982, recommended: Madagascar 2005
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (117874, 37002, 2, 'oriliss', 'Though both are comedies about a man unexpectedly taking on a parental role, it is a bad recommendation since Big Daddy''s toilet humour is a long way from Forrest Gump''s warmth and lifetime-spanning pathos.', null);  # base: Forrest Gump 1994, recommended: Big Daddy 1999
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (130129, 27168, 2, 'oriliss', 'Though both are crime films about men navigating dangerous power dynamics, it is a bad recommendation since Bad Boys is a breezy action comedy while Godfather Part II is a layered multi-decade tragedy.', null);  # base: Godfather Part II 1974, recommended: Bad Boys 1995
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (256632, 163715, 3, 'oriliss', 'Though both are heist-adventure films with a witty charismatic protagonist, it is a bad recommendation since The Italian Job''s generic remake cannot deliver Pirates'' swashbuckling charm or Johnny Depp magic.', null);  # base: Pirates of Caribbean 2003, recommended: Italian Job 2003
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (272644, 155213, 2, 'oriliss', 'Though both are animated films about an animal pursuing an unlikely dream, it is a bad recommendation since Ice Age''s slapstick road-trip lacks Ratatouille''s passion and quietly radical central theme.', null);  # base: Ratatouille 2006, recommended: Ice Age 2002
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (82967, 163715, 2, 'oriliss', 'Though both involve criminals executing a high-stakes plan, it is a bad recommendation since The Italian Job is a lightweight heist caper while The Departed is a morally devastating crime epic.', null);  # base: The Departed 2006, recommended: Italian Job 2003
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (188507, 27168, 2, 'oriliss', 'Though both are buddy-cop action films with mismatched partners, it is a bad recommendation since Bad Boys'' loud shallow formula lacks Lethal Weapon''s genuine chemistry and Riggs'' compelling character arc.', null);  # base: Lethal Weapon 1987, recommended: Bad Boys 1995
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (107166, 112205, 2, 'oriliss', 'Though both are 1990s action films with outlandish high-concept premises, it is a bad recommendation since The Fifth Element''s baffling alien mythology disappoints fans of Face/Off''s slick B-movie thrills.', null);  # base: Face/Off 1997, recommended: Fifth Element 1997
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313479, 313476, 2, 'oriliss', 'Though both are Star Wars chapter entries, it is a bad recommendation since Attack of the Clones'' wooden romance and CGI overload are a brutal comedown from the original trilogy''s authenticity.', null);  # base: Return of the Jedi 1983, recommended: Attack of the Clones 2002
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (56304, 27168, 2, 'oriliss', 'Though both are crime films where loyalty and betrayal shape the protagonist''s fate, it is a bad recommendation since Bad Boys is a shallow action comedy while Casino is a three-hour operatic crime epic.', null);  # base: Casino 1995, recommended: Bad Boys 1995
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (104338, 146780, 2, 'oriliss', 'Though both are romantic films about a man navigating complex emotional terrain, it is a bad recommendation since Hitch is a formulaic crowd-pleaser while Eternal Sunshine demands far more from its audience.', null);  # base: Eternal Sunshine 2004, recommended: Hitch 2005
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (49696, 335245, 2, 'oriliss', 'Though both feature a legendary gunfighter in a climactic showdown, it is a bad recommendation since Tombstone is entertaining genre fare while Good Bad and Ugly is a three-hour operatic masterpiece.', null);  # base: Good Bad and Ugly 1966, recommended: Tombstone 1993
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (158927, 311040, 2, 'oriliss', 'Though both feature a superhero balancing personal struggles with saving the world, it is a bad recommendation since Spider-Man 3''s tonally confused screenplay is a disappointment after The Incredibles'' tight Pixar storytelling.', null);  # base: The Incredibles 2004, recommended: Spider-Man 3 2007
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (129185, 123849, 2, 'oriliss', 'Though both are epics about a morally complex protagonist surviving a corrupt power structure, it is a bad recommendation since Gangs of New York''s sprawling narrative cannot match Gladiator''s lean arc of vengeance.', null);  # base: Gladiator 2000, recommended: Gangs of New York 2002
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (131780, 35522, 2, 'oriliss', 'Though both feature a charismatic protagonist navigating criminal networks through wit, it is a bad recommendation since Beverly Hills Cop is light 80s comedy while Goodfellas is a three-hour crime epic.', null);  # base: Goodfellas 1990, recommended: Beverly Hills Cop 1984
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (45128, 215880, 2, 'oriliss', 'Though both are spy action films with a skilled agent tracking a dangerous villain, it is a bad recommendation since Mission Impossible III''s glossy formula feels shallow compared to Bourne''s gritty realism.', null);  # base: Bourne Identity 2002, recommended: Mission Impossible III 2006
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (291698, 76382, 2, 'oriliss', 'Though both chase a serial trail of clues toward a shocking revelation, it is a bad recommendation since Da Vinci Code''s slow conspiracy plotting will disappoint fans expecting Fincher''s suffocating dread.', null);  # base: Se7en 1995, recommended: Da Vinci Code 2006
insert into movies_recommendations (base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (194497, 359297, 2, 'oriliss', 'Though both are blockbusters about ordinary people caught up in an extraordinary threat, it is a bad recommendation since War of the Worlds'' bleak survival thriller clashes with Fellowship''s epic myth of hope.', null);  # base: LotR Fellowship 2001, recommended: War of the Worlds 2005
