insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (139655, 139652, 9, 'msdevlab', 'Prisoner of Azkaban and Goblet of Fire are both high-point Harry Potter entries that raise the stakes, sharpen the tone, and deliver the most emotionally involving chapters of the series.', null);  -- 139655 Harry Potter and the Prisoner of Azkaban 2004 | 139652 Harry Potter and the Goblet of Fire 2005
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (139654, 139655, 9, 'msdevlab', 'Order of the Phoenix and Prisoner of Azkaban both focus on Harry''s emotional frustration and feature the most compelling adult characters in the series.', null);  -- 139654 Harry Potter and the Order of the Phoenix 2007 | 139655 Harry Potter and the Prisoner of Azkaban 2004
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (139652, 139654, 9, 'msdevlab', 'Goblet of Fire and Order of the Phoenix both deepen Voldemort''s return while giving Harry personal emotional stakes beyond a typical school adventure.', null);  -- 139652 Harry Potter and the Goblet of Fire 2005 | 139654 Harry Potter and the Order of the Phoenix 2007
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (139657, 139655, 9, 'msdevlab', 'Sorcerer''s Stone introduces the world that Prisoner of Azkaban expands brilliantly, making it the natural next recommendation for fans of the magical school setting.', null);  -- 139657 Harry Potter and the Sorcerer's Stone 2001 | 139655 Harry Potter and the Prisoner of Azkaban 2004
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (139650, 139652, 9, 'msdevlab', 'Chamber of Secrets fans who enjoy magical mysteries will find Goblet of Fire elevates the excitement with the Triwizard Tournament and Voldemort''s dramatic return.', null);  -- 139650 Harry Potter and the Chamber of Secrets 2002 | 139652 Harry Potter and the Goblet of Fire 2005
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (139653, 139655, 9, 'msdevlab', 'Half-Blood Prince and Prisoner of Azkaban both build mystery around hidden truths about characters Harry trusted, linking them thematically.', null);  -- 139653 Harry Potter and the Half-Blood Prince 2008 | 139655 Harry Potter and the Prisoner of Azkaban 2004
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (139657, 139654, 9, 'msdevlab', 'Sorcerer''s Stone begins the friendship that Order of the Phoenix brings to its emotional peak, making both essential for the full character arc.', null);  -- 139657 Harry Potter and the Sorcerer's Stone 2001 | 139654 Harry Potter and the Order of the Phoenix 2007
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (139653, 139652, 9, 'msdevlab', 'Half-Blood Prince and Goblet of Fire both raise the darkness of Voldemort''s threat while centering each story on a specific dramatic event at Hogwarts.', null);  -- 139653 Harry Potter and the Half-Blood Prince 2008 | 139652 Harry Potter and the Goblet of Fire 2005
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (311038, 311037, 9, 'msdevlab', 'Spider-Man 2''s emotional depth builds directly on the 2002 original''s character setup, making both feel like one unified story about Peter Parker''s growth.', null);  -- 311038 Spider-Man 2 2004 | 311037 Spider-Man 2002
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (311040, 311038, 9, 'msdevlab', 'Spider-Man 3 fans will find Spider-Man 2''s tighter and more emotionally focused version of the same Peter Parker conflict even more satisfying.', null);  -- 311040 Spider-Man 3 2007 | 311038 Spider-Man 2 2004
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (215880, 215876, 9, 'msdevlab', 'Mission Impossible III and the 1996 Mission Impossible both make Ethan''s personal stakes the emotional core, delivering the best combination of suspense and action in the franchise.', null);  -- 215880 Mission: Impossible III 2006 | 215876 Mission: Impossible 1996
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (215876, 215879, 9, 'msdevlab', 'Mission Impossible 1996''s CIA-betrayal tension leads naturally to Mission Impossible II''s stylish action with equally strong personal stakes for Ethan Hunt.', null);  -- 215876 Mission: Impossible 1996 | 215879 Mission: Impossible II 2000
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (215880, 215879, 9, 'msdevlab', 'Mission Impossible III and II both balance romantic tension with intense mission design, making them the two most emotionally invested entries in the franchise.', null);  -- 215880 Mission: Impossible III 2006 | 215879 Mission: Impossible II 2000
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (256632, 256631, 9, 'msdevlab', 'Pirates of the Caribbean Black Pearl''s Jack Sparrow charm and sea adventure carry directly into Dead Man''s Chest''s Davy Jones mythology with equal energy.', null);  -- 256632 Pirates of the Caribbean: The Curse of the Black Pearl 2003 | 256631 Pirates of the Caribbean 2 2006
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313477, 313478, 9, 'msdevlab', 'Revenge of the Sith and The Empire Strikes Back share the darkest emotional tone in their respective trilogies, making them natural companions for serious Star Wars fans.', null);  -- 313477 Star Wars: Episode III - Revenge of the Sith 2005 | 313478 Star Wars: Episode V - The Empire Strikes Back 1980
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313478, 313479, 9, 'msdevlab', 'The Empire Strikes Back''s cliffhanger ending makes Return of the Jedi''s rescue and final Vader confrontation deeply satisfying for fans of the original trilogy.', null);  -- 313478 Star Wars: Episode V - The Empire Strikes Back 1980 | 313479 Star Wars: Episode VI - Return of the Jedi 1983
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313477, 313479, 9, 'msdevlab', 'Revenge of the Sith and Return of the Jedi both dramatize Vader''s legacy and the final confrontation between darkness and redemption in compelling ways.', null);  -- 313477 Star Wars: Episode III - Revenge of the Sith 2005 | 313479 Star Wars: Episode VI - Return of the Jedi 1983
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (194497, 194502, 9, 'msdevlab', 'Fellowship of the Ring sets up Two Towers'' split journey brilliantly, delivering Helm''s Deep as the emotional peak of the trilogy.', null);  -- 194497 Lord of the Rings: The Fellowship of the Ring, The 2001 | 194502 Lord of the Rings: The Two Towers, The 2002
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (194502, 194495, 9, 'msdevlab', 'Two Towers builds to a level of stakes and sacrifice that Return of the King fulfills with the most emotionally complete ending in the trilogy.', null);  -- 194502 Lord of the Rings: The Two Towers, The 2002 | 194495 Lord of the Rings: Return of the King, The (2003/II) 2003
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (194497, 194495, 9, 'msdevlab', 'Fellowship of the Ring and Return of the King bookend Frodo''s journey with the strongest emotional investment, making both essential for the full story.', null);  -- 194497 Lord of the Rings: The Fellowship of the Ring, The 2001 | 194495 Lord of the Rings: Return of the King, The (2003/II) 2003
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (300229, 300230, 9, 'msdevlab', 'Shrek''s fairy-tale parody humor and emotional warmth carry into Shrek 2''s equally sharp comedy, with Puss in Boots and the Fairy Godmother making the sequel just as rewarding.', null);  -- 300229 Shrek 2001 | 300230 Shrek 2 2004
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30959, 162380, 9, 'msdevlab', 'Batman Begins and Iron Man both ground their superhero origins in realistic character psychology, making them the two most thoughtfully written superhero origin films of their era.', null);  -- 30959 Batman Begins 2005 | 162380 Iron Man 2005
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (158999, 359297, 9, 'msdevlab', 'Independence Day and War of the Worlds both follow charismatic heroes surviving a devastating alien invasion, delivering high-stakes action with a clear emotional center.', null);  -- 158999 Independence Day 1996 | 359297 War of the Worlds 2005
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (214755, 359297, 9, 'msdevlab', 'Minority Report and War of the Worlds are both Spielberg-directed, Tom Cruise-led sci-fi thrillers that reward viewers with intelligent action and a personal chase at the center.', null);  -- 214755 Minority Report 2002 | 359297 War of the Worlds 2005
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (214755, 158999, 9, 'msdevlab', 'Minority Report''s futuristic chase plot and Independence Day''s alien-invasion survival story both deliver clear sci-fi stakes, urgent pacing, and heroes fighting systems larger than themselves.', null);  -- 214755 Minority Report 2002 | 158999 Independence Day 1996
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (129185, 46169, 9, 'msdevlab', 'Gladiator and Braveheart both use betrayal, personal loss, and large battlefield moments to turn historical action into an emotional fight for justice.', null);  -- 129185 Gladiator 2000 | 46169 Braveheart 1995
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (185628, 129185, 9, 'msdevlab', 'The Last Samurai and Gladiator both follow warriors navigating the collapse of an honorable world, creating deep emotional stakes in spectacular battle settings.', null);  -- 185628 Last Samurai, The 2003 | 129185 Gladiator 2000
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (185628, 46169, 9, 'msdevlab', 'The Last Samurai and Braveheart both dramatize the loss of a warrior culture through a deeply personal character journey, making them natural companions for epic drama fans.', null);  -- 185628 Last Samurai, The 2003 | 46169 Braveheart 1995
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (340652, 129185, 9, 'msdevlab', 'Troy''s Achilles and Gladiator''s Maximus both offer powerful stories of legendary warriors caught between personal honor and political betrayal in ancient combat settings.', null);  -- 340652 Troy 2004 | 129185 Gladiator 2000
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (340652, 46169, 9, 'msdevlab', 'Troy''s war between kingdoms and Braveheart''s rebellion story both focus on charismatic warriors whose personal choices become tied to a much larger national conflict.', null);  -- 340652 Troy 2004 | 46169 Braveheart 1995
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (333856, 263360, 9, 'msdevlab', 'Titanic and Pretty Woman are both timeless romance stories about love across social divides, making them the two most emotionally satisfying classic romantic films.', null);  -- 333856 Titanic 1997 | 263360 Pretty Woman 1990
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (151616, 263360, 9, 'msdevlab', 'How to Lose a Guy in 10 Days and Pretty Woman are both witty romantic comedies featuring strong-willed women who discover genuine love while playing a game that turns real.', null);  -- 151616 How to Lose a Guy in 10 Days 2003 | 263360 Pretty Woman 1990
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (644, 151616, 9, 'msdevlab', '10 Things I Hate About You and How to Lose a Guy in 10 Days both feature sharp-witted heroines drawn into romantic games that turn into real love.', null);  -- 644 10 Things I Hate About You 1999 | 151616 How to Lose a Guy in 10 Days 2003
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (238072, 56871, 9, 'msdevlab', 'Ocean''s Eleven and Catch Me If You Can both celebrate charming, intelligent protagonists who outsmart the system with style and effortless confidence.', null);  -- 238072 Ocean's Eleven 2001 | 56871 Catch Me If You Can 2002
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (238072, 238073, 9, 'msdevlab', 'Ocean''s Eleven fans who love the team''s chemistry and wit will enjoy following them to Ocean''s Twelve''s more complex European caper.', null);  -- 238072 Ocean's Eleven 2001 | 238073 Ocean's Twelve 2004
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (271095, 159172, 9, 'msdevlab', 'Raiders of the Lost Ark and Indiana Jones and the Last Crusade are both peak Indiana Jones adventures combining humor, danger, and memorable quest objects.', null);  -- 271095 Raiders of the Lost Ark 1981 | 159172 Indiana Jones and the Last Crusade 1989
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (335835, 215876, 9, 'msdevlab', 'Top Gun and Mission Impossible 1996 both feature Tom Cruise at his most intense and mission-focused, delivering some of his finest action-thriller performances.', null);  -- 335835 Top Gun 1986 | 215876 Mission: Impossible 1996
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (335835, 215880, 9, 'msdevlab', 'Top Gun''s military-edge intensity closely matches the personal-stakes urgency of Mission Impossible III, making both Tom Cruise''s finest action films.', null);  -- 335835 Top Gun 1986 | 215880 Mission: Impossible III 2006
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (210739, 158999, 9, 'msdevlab', 'Men in Black and Independence Day are both classic Will Smith films that blend humor with alien-invasion action in an effortlessly entertaining way.', null);  -- 210739 Men in Black 1997 | 158999 Independence Day 1996
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (210739, 214755, 9, 'msdevlab', 'Men in Black''s fast-paced sci-fi action and sharp wit pair well with Minority Report''s equally smart take on future technology and personal stakes.', null);  -- 210739 Men in Black 1997 | 214755 Minority Report 2002
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (109421, 162380, 9, 'msdevlab', 'The Fast and the Furious and Iron Man both thrive on tech, speed, and charismatic heroes whose loyalty to their team drives the most exciting action sequences.', null);  -- 109421 Fast and the Furious, The 2001 | 162380 Iron Man 2005
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (109421, 220805, 9, 'msdevlab', 'The Fast and the Furious and Mr. and Mrs. Smith both deliver adrenaline-driven action built around magnetic characters and exciting relationship dynamics.', null);  -- 109421 Fast and the Furious, The 2001 | 220805 Mr. and Mrs. Smith 2005
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (220805, 215880, 9, 'msdevlab', 'Mr. and Mrs. Smith''s blend of romantic tension and spy action perfectly matches Mission Impossible III''s personal stakes and mission-driven urgency.', null);  -- 220805 Mr. and Mrs. Smith 2005 | 215880 Mission: Impossible III 2006
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (162380, 214755, 9, 'msdevlab', 'Iron Man and Minority Report both feature brilliant protagonists forced to outrun the very system they once trusted, making them equally smart and thrilling.', null);  -- 162380 Iron Man 2005 | 214755 Minority Report 2002
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (297838, 56871, 9, 'msdevlab', 'The Shawshank Redemption and Catch Me If You Can both follow characters who maintain hope and ingenuity under extreme pressure with warm, engaging performances.', null);  -- 297838 Shawshank Redemption, The 1994 | 56871 Catch Me If You Can 2002
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (297838, 238072, 9, 'msdevlab', 'Shawshank Redemption fans will find Ocean''s Eleven equally satisfying since both reward careful, clever planning over brute force with deeply fulfilling conclusions.', null);  -- 297838 Shawshank Redemption, The 1994 | 238072 Ocean's Eleven 2001
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (39551, 129185, 9, 'msdevlab', 'Black Hawk Down and Gladiator both portray soldiers and warriors pushed beyond their limits, connecting through their intense studies of survival, loyalty, and sacrifice under fire.', null);  -- 39551 Black Hawk Down 2001 | 129185 Gladiator 2000
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (39551, 46169, 9, 'msdevlab', 'Black Hawk Down and Braveheart both show fighters relying on loyalty under extreme pressure, making the action feel connected to duty rather than empty spectacle.', null);  -- 39551 Black Hawk Down 2001 | 46169 Braveheart 1995
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (142491, 142492, 9, 'msdevlab', 'Hellboy and Hellboy 2 share the same supernatural outsider charm and monster-fighting adventure, making the sequel a natural continuation for fans of the original.', null);  -- 142491 Hellboy 2004 | 142492 Hellboy 2 2006
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (142491, 30959, 9, 'msdevlab', 'Hellboy and Batman Begins both follow reluctant heroes with dark origins who choose to defend humanity despite the threatening nature of their own power.', null);  -- 142491 Hellboy 2004 | 30959 Batman Begins 2005
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (142492, 162380, 9, 'msdevlab', 'Hellboy 2 and Iron Man both feature sarcastic heroes with unique abilities who navigate colorful team dynamics and outsized threats with wit and confidence.', null);  -- 142492 Hellboy 2 2006 | 162380 Iron Man 2005
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (328272, 297838, 9, 'msdevlab', 'The Terminal and Shawshank Redemption both follow men navigating impossible situations with patience, warmth, and a refusal to give up on hope.', null);  -- 328272 Terminal, The 2004 | 297838 Shawshank Redemption, The 1994
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (328272, 56871, 9, 'msdevlab', 'The Terminal and Catch Me If You Can are both Spielberg films featuring charming protagonists who navigate unusual bureaucratic situations with ingenuity and warmth.', null);  -- 328272 Terminal, The 2004 | 56871 Catch Me If You Can 2002
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (131780, 238072, 9, 'msdevlab', 'Goodfellas and Ocean''s Eleven both explore the seductive appeal of crime through stylish storytelling and charismatic protagonists who make it all look effortless.', null);  -- 131780 Goodfellas 1990 | 238072 Ocean's Eleven 2001
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (131780, 297838, 9, 'msdevlab', 'Goodfellas and The Shawshank Redemption both follow men surviving inside criminal institutions, but each keeps the story compelling through voiceover, loyalty, and long-term consequences.', null);  -- 131780 Goodfellas 1990 | 297838 Shawshank Redemption, The 1994
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (188511, 210739, 9, 'msdevlab', 'Lethal Weapon 4 and Men in Black are both buddy-action comedies where the humor between the leads drives the entertainment as much as the action itself.', null);  -- 188511 Lethal Weapon 4 1998 | 210739 Men in Black 1997
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (188511, 109421, 9, 'msdevlab', 'Lethal Weapon 4 fans who enjoy team loyalty and fast action will find the same energy in The Fast and the Furious with a modern racing spin.', null);  -- 188511 Lethal Weapon 4 1998 | 109421 Fast and the Furious, The 2001
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (370017, 109421, 9, 'msdevlab', 'XXX and The Fast and the Furious both celebrate extreme-sports energy and undercover missions with the same bold, adrenaline-first attitude.', null);  -- 370017 XXX 2002 | 109421 Fast and the Furious, The 2001
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (370017, 215876, 9, 'msdevlab', 'XXX and Mission Impossible 1996 both follow unconventional agents on high-stakes missions, combining stylish action with clever spy setups.', null);  -- 370017 XXX 2002 | 215876 Mission: Impossible 1996
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (86263, 215876, 9, 'msdevlab', 'Die Another Day and Mission Impossible 1996 both offer high-concept spy missions with memorable set pieces and charismatic leads.', null);  -- 86263 Die Another Day 2002 | 215876 Mission: Impossible 1996
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (86263, 370017, 9, 'msdevlab', 'Die Another Day and XXX both feature action-first agents with gadgets and international dangers, sharing the same bold, entertaining spy-action energy.', null);  -- 86263 Die Another Day 2002 | 370017 XXX 2002
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (97727, 300229, 9, 'msdevlab', 'Edward Scissorhands and Shrek both tell stories of misunderstood outsiders who find acceptance and love despite the prejudice of the world around them.', null);  -- 97727 Edward Scissorhands 1990 | 300229 Shrek 2001
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (190869, 300229, 9, 'msdevlab', 'Lilo and Stitch and Shrek both use animated comedy to explore found family and the idea that outsiders can find belonging when given the chance.', null);  -- 190869 Lilo & Stitch 2002 | 300229 Shrek 2001
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (190869, 300230, 9, 'msdevlab', 'Lilo and Stitch and Shrek 2 both balance genuine humor and heart in animated tales about unconventional families facing outside pressure to conform.', null);  -- 190869 Lilo & Stitch 2002 | 300230 Shrek 2 2004
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (247579, 214755, 9, 'msdevlab', 'Panic Room and Minority Report are both tight, intelligent thrillers built on cat-and-mouse tension with a single protagonist under relentless pressure.', null);  -- 247579 Panic Room 2002 | 214755 Minority Report 2002
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (335835, 271095, 9, 'msdevlab', 'Top Gun and Raiders of the Lost Ark are both iconic 1980s action classics featuring magnetic heroes on high-stakes missions defined by skill, personal rivalry, and determination.', null);  -- 335835 Top Gun 1986 | 271095 Raiders of the Lost Ark 1981
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (280284, 129185, 9, 'msdevlab', 'Rocky IV and Gladiator both present a champion fighting against an overwhelming opponent with the emotional weight of justice and personal honor behind every action.', null);  -- 280284 Rocky IV 1985 | 129185 Gladiator 2000
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (151616, 220805, 9, 'msdevlab', 'How to Lose a Guy in 10 Days and Mr. and Mrs. Smith are both witty comedies where romantic deception between two strong personalities escalates into something real and explosive.', null);  -- 151616 How to Lose a Guy in 10 Days 2003 | 220805 Mr. and Mrs. Smith 2005
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (644, 66194, 9, 'msdevlab', '10 Things I Hate About You and Clueless are both witty 1990s teen comedies with sharp, memorable female leads and a classic literary framework behind the story.', null);  -- 644 10 Things I Hate About You 1999 | 66194 Clueless 1995
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (271095, 256632, 9, 'msdevlab', 'Raiders of the Lost Ark and Pirates of the Caribbean share the same swashbuckling adventure spirit, with iconic heroes navigating traps, ancient mysteries, and memorable villains.', null);  -- 271095 Raiders of the Lost Ark 1981 | 256632 Pirates of the Caribbean: The Curse of the Black Pearl 2003
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (139650, 139655, 9, 'msdevlab', 'Chamber of Secrets and Prisoner of Azkaban both work as Hogwarts mysteries, moving from the Chamber threat to the Sirius Black reveal while keeping Harry''s friendships central.', null);  -- 139650 Harry Potter and the Chamber of Secrets 2002 | 139655 Harry Potter and the Prisoner of Azkaban 2004
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (139650, 139657, 9, 'msdevlab', 'Chamber of Secrets is a strong follow-up to Sorcerer''s Stone because both keep the magical-school wonder, the trio''s teamwork, and a mystery hidden inside Hogwarts.', null);  -- 139650 Harry Potter and the Chamber of Secrets 2002 | 139657 Harry Potter and the Sorcerer's Stone 2001
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (139654, 139653, 9, 'msdevlab', 'Order of the Phoenix and Half-Blood Prince both focus on Harry carrying heavier emotional pressure while Hogwarts becomes darker, more political, and less safe.', null);  -- 139654 Harry Potter and the Order of the Phoenix 2007 | 139653 Harry Potter and the Half-Blood Prince 2008
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (139657, 139652, 9, 'msdevlab', 'Sorcerer''s Stone''s introduction to Hogwarts leads naturally into Goblet of Fire, where the same magical world becomes more competitive, dangerous, and emotionally mature.', null);  -- 139657 Harry Potter and the Sorcerer's Stone 2001 | 139652 Harry Potter and the Goblet of Fire 2005
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (311037, 311040, 9, 'msdevlab', 'Spider-Man and Spider-Man 3 both follow Peter Parker struggling with responsibility, romance, and identity, so the later film feels like a darker continuation of the same conflict.', null);  -- 311037 Spider-Man 2002 | 311040 Spider-Man 3 2007
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (311038, 30959, 9, 'msdevlab', 'Spider-Man 2 and Batman Begins both make superhero action meaningful by tying the set pieces to guilt, responsibility, and the hero''s doubts about the life he chose.', null);  -- 311038 Spider-Man 2 2004 | 30959 Batman Begins 2005
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (311038, 162380, 9, 'msdevlab', 'Spider-Man 2 and Iron Man both balance humor, superhero spectacle, and a protagonist learning that power matters most when it is connected to responsibility.', null);  -- 311038 Spider-Man 2 2004 | 162380 Iron Man 2005
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (215875, 215879, 9, 'msdevlab', 'The 1991 Mission: Impossible and Mission: Impossible II both rely on undercover strategy, disguises, and spy-team suspense, making them a reasonable franchise-based recommendation.', null);  -- 215875 Mission: Impossible 1991 | 215879 Mission: Impossible II 2000
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (215875, 215880, 9, 'msdevlab', 'The 1991 Mission: Impossible and Mission: Impossible III share the IMF mission structure, but the third film adds stronger urgency while keeping the same spy-operation appeal.', null);  -- 215875 Mission: Impossible 1991 | 215880 Mission: Impossible III 2006
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (256631, 271095, 9, 'msdevlab', 'Pirates of the Caribbean 2 and Raiders of the Lost Ark both build adventure around dangerous treasure hunts, witty heroes, and set pieces that keep the story moving.', null);  -- 256631 Pirates of the Caribbean 2 2006 | 271095 Raiders of the Lost Ark 1981
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (256631, 159172, 9, 'msdevlab', 'Pirates of the Caribbean 2 and The Last Crusade both combine humor, mythology, and fast adventure, with the quest itself revealing more about the heroes'' relationships.', null);  -- 256631 Pirates of the Caribbean 2 2006 | 159172 Indiana Jones and the Last Crusade 1989
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313478, 194502, 9, 'msdevlab', 'The Empire Strikes Back and The Two Towers are both darker middle chapters where the heroes are separated, tested, and forced to keep hope alive before the final battle.', null);  -- 313478 Star Wars: Episode V - The Empire Strikes Back 1980 | 194502 Lord of the Rings: The Two Towers, The 2002
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313477, 194495, 9, 'msdevlab', 'Revenge of the Sith and Return of the King both feel like epic conclusions, using large battles and emotional good-versus-evil choices to give the saga real weight.', null);  -- 313477 Star Wars: Episode III - Revenge of the Sith 2005 | 194495 Lord of the Rings: Return of the King, The (2003/II) 2003
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313479, 194495, 9, 'msdevlab', 'Return of the Jedi and Return of the King both close beloved trilogies with rescue missions, final confrontations, and a strong sense of emotional resolution.', null);  -- 313479 Star Wars: Episode VI - Return of the Jedi 1983 | 194495 Lord of the Rings: Return of the King, The (2003/II) 2003
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (300229, 210739, 9, 'msdevlab', 'Shrek and Men in Black both mix fantasy or sci-fi worlds with fast comedy, using a strange duo dynamic to make the adventure feel fun rather than childish.', null);  -- 300229 Shrek 2001 | 210739 Men in Black 1997
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (300230, 210739, 9, 'msdevlab', 'Shrek 2 and Men in Black both turn bizarre creatures and hidden worlds into sharp comedy, while still giving the main characters clear emotional loyalty.', null);  -- 300230 Shrek 2 2004 | 210739 Men in Black 1997
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30959, 214755, 9, 'msdevlab', 'Batman Begins and Minority Report both use sleek thriller pacing, moral pressure, and a hero hunted by powerful systems to make the action feel intelligent.', null);  -- 30959 Batman Begins 2005 | 214755 Minority Report 2002
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (162380, 215880, 9, 'msdevlab', 'Iron Man and Mission: Impossible III both center on charismatic heroes facing personal danger, advanced technology, and action that depends on quick thinking rather than strength alone.', null);  -- 162380 Iron Man 2005 | 215880 Mission: Impossible III 2006
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (158999, 335835, 9, 'msdevlab', 'Independence Day and Top Gun both deliver patriotic action built around confident heroes, teamwork, and big crowd-pleasing moments that still feel emotionally clear.', null);  -- 158999 Independence Day 1996 | 335835 Top Gun 1986
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (359297, 247579, 9, 'msdevlab', 'War of the Worlds and Panic Room both create suspense from a family trapped under threat, making survival feel personal, immediate, and easy to follow.', null);  -- 359297 War of the Worlds 2005 | 247579 Panic Room 2002
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (185628, 340652, 9, 'msdevlab', 'The Last Samurai and Troy both explore warrior honor in historical settings, focusing on men caught between loyalty, identity, and the cost of battle.', null);  -- 185628 Last Samurai, The 2003 | 340652 Troy 2004
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (333856, 151616, 9, 'msdevlab', 'Titanic and How to Lose a Guy in 10 Days are very different in scale, but both depend on strong romantic chemistry and a relationship tested by social pressure and deception.', null);  -- 333856 Titanic 1997 | 151616 How to Lose a Guy in 10 Days 2003
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (263360, 644, 9, 'msdevlab', 'Pretty Woman and 10 Things I Hate About You both turn a familiar romance setup into something memorable through sharp chemistry, strong female leads, and emotional payoff.', null);  -- 263360 Pretty Woman 1990 | 644 10 Things I Hate About You 1999
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (238073, 56871, 9, 'msdevlab', 'Ocean''s Twelve and Catch Me If You Can both enjoy clever deception, stylish escapes, and the pleasure of watching charming characters stay one step ahead.', null);  -- 238073 Ocean's Twelve 2004 | 56871 Catch Me If You Can 2002
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (297838, 129185, 9, 'msdevlab', 'The Shawshank Redemption and Gladiator both turn injustice into a powerful personal journey, rewarding patience, loyalty, and hope through very satisfying endings.', null);  -- 297838 Shawshank Redemption, The 1994 | 129185 Gladiator 2000
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (328272, 333856, 9, 'msdevlab', 'The Terminal and Titanic both follow kind-hearted characters trapped by circumstances beyond their control, making the emotional connection more important than the setting itself.', null);  -- 328272 Terminal, The 2004 | 333856 Titanic 1997
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (142491, 311037, 9, 'msdevlab', 'Hellboy and Spider-Man both follow outsiders with unusual powers who struggle with acceptance while still choosing to protect people who do not fully understand them.', null);  -- 142491 Hellboy 2004 | 311037 Spider-Man 2002
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (142492, 311038, 9, 'msdevlab', 'Hellboy 2 and Spider-Man 2 both improve superhero storytelling by giving the hero stronger emotional conflict alongside creative villains and memorable action sequences.', null);  -- 142492 Hellboy 2 2006 | 311038 Spider-Man 2 2004
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (370017, 335835, 9, 'msdevlab', 'XXX and Top Gun both focus on fearless, competitive men whose confidence and physical skill drive fast, high-risk action in a very entertaining way.', null);  -- 370017 XXX 2002 | 335835 Top Gun 1986
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (86263, 215880, 9, 'msdevlab', 'Die Another Day and Mission: Impossible III both deliver modern spy action with gadgets, international threats, and a lead character pushed through stylish high-pressure missions.', null);  -- 86263 Die Another Day 2002 | 215880 Mission: Impossible III 2006
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (86263, 92573, 2, 'msdevlab', 'The James Bond connection is clear, but Dr. No feels like an early, stripped-down spy story; it lacks the modern gadgets, speed, and spectacle that make Die Another Day entertaining.', null);  -- 86263 Die Another Day 2002 | 92573 Dr. No 1962
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (86263, 120574, 2, 'msdevlab', 'A Bond fan may understand the pairing, yet From Russia with Love is built around slow Cold War espionage and train suspense rather than Die Another Day''s flashy action style.', null);  -- 86263 Die Another Day 2002 | 120574 From Russia with Love 1963
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (86263, 85871, 2, 'msdevlab', 'Diamonds Are Forever uses campy Las Vegas humor and an older Connery-era rhythm, so it would feel like the wrong follow-up to Die Another Day''s sleek, gadget-heavy adventure.', null);  -- 86263 Die Another Day 2002 | 85871 Diamonds Are Forever 1971
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (86263, 192514, 2, 'msdevlab', 'Live and Let Die shares the Bond formula, but its dated tone and unusual voodoo storyline do not fit the fast, modern spy-adventure feeling of Die Another Day.', null);  -- 86263 Die Another Day 2002 | 192514 Live and Let Die 1973
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (86263, 372233, 2, 'msdevlab', 'You Only Live Twice has a large villain plan, yet its 1960s pacing and outdated stereotypes make it a weak match for someone drawn to Die Another Day''s quick modern action.', null);  -- 86263 Die Another Day 2002 | 372233 You Only Live Twice 1967
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (86263, 332065, 2, 'msdevlab', 'Thunderball includes exotic Bond danger, but the long underwater scenes make it much slower than the energetic, gadget-driven pace that Die Another Day fans would expect.', null);  -- 86263 Die Another Day 2002 | 332065 Thunderball 1965
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (335336, 92573, 2, 'msdevlab', 'Dr. No is historically important for Bond, yet it does not deliver the media-villain plot, fast chases, or modern action rhythm that make Tomorrow Never Dies appealing.', null);  -- 335336 Tomorrow Never Dies 1997 | 92573 Dr. No 1962
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (335336, 85871, 2, 'msdevlab', 'Diamonds Are Forever has glamour, but its campier humor and looser 1970s plot do not match Tomorrow Never Dies'' tighter action around a global media villain.', null);  -- 335336 Tomorrow Never Dies 1997 | 85871 Diamonds Are Forever 1971
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (368418, 203649, 2, 'msdevlab', 'The Man with the Golden Gun has an assassin premise, but its thin villain story and 1970s silliness make it much weaker than The World Is Not Enough''s more emotional Bond plot.', null);  -- 368418 World Is Not Enough, The 1999 | 203649 Man with the Golden Gun, The 1974
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (368418, 192514, 2, 'msdevlab', 'Live and Let Die may have memorable villains, but the voodoo and blaxploitation elements feel too dated beside The World Is Not Enough''s personal betrayal and modern spy stakes.', null);  -- 368418 World Is Not Enough, The 1999 | 192514 Live and Let Die 1973
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30959, 30965, 2, 'msdevlab', 'Batman Forever keeps Gotham and Batman, but the neon colors, jokey villains, and camp tone are the opposite of the grounded fear-and-training story in Batman Begins.', null);  -- 30959 Batman Begins 2005 | 30965 Batman Forever 1995
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30959, 30967, 2, 'msdevlab', 'Batman Returns has gothic style, yet its strange circus-villain focus and messier plot do not give the clean origin arc and realism that Batman Begins offers.', null);  -- 30959 Batman Begins 2005 | 30967 Batman Returns 1992
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30959, 30955, 2, 'msdevlab', 'Batman 1989 is iconic, but its more theatrical tone and uneven character depth make it a weak recommendation after Batman Begins'' serious psychological origin story.', null);  -- 30959 Batman Begins 2005 | 30955 Batman 1989
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30959, 381392, 2, 'msdevlab', 'Batman Beyond reimagines the hero in a futuristic animated teen format, which feels too light and small compared with the cinematic realism of Batman Begins.', null);  -- 30959 Batman Begins 2005 | 381392 "Batman Beyond" 1999
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30959, 30976, 2, 'msdevlab', 'Mask of the Phantasm has an emotional Batman mystery, but its animated scale makes it feel less satisfying for someone wanting Batman Begins'' full live-action intensity.', null);  -- 30959 Batman Begins 2005 | 30976 Batman: Mask of the Phantasm 1993
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313477, 313475, 2, 'msdevlab', 'The Phantom Menace is connected to Revenge of the Sith, but its Jar Jar humor, child-centered adventure, and flat politics weaken the dark emotional payoff expected from Episode III.', null);  -- 313477 Star Wars: Episode III - Revenge of the Sith 2005 | 313475 Star Wars: Episode I - The Phantom Menace (1999/II) 1999
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313477, 313476, 2, 'msdevlab', 'Attack of the Clones sits in the same prequel storyline, yet its stiff romance and slower middle chapter cannot match Revenge of the Sith''s tragedy and momentum.', null);  -- 313477 Star Wars: Episode III - Revenge of the Sith 2005 | 313476 Star Wars: Episode II - Attack of the Clones 2002
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313478, 313474, 2, 'msdevlab', 'The Phantom Menace belongs to the same saga, but its childish humor and lighter adventure feel far away from The Empire Strikes Back''s darker, more mature storytelling.', null);  -- 313478 Star Wars: Episode V - The Empire Strikes Back 1980 | 313474 Star Wars: Episode I - The Phantom Menace 1999
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313478, 313476, 2, 'msdevlab', 'Attack of the Clones has Jedi battles and galactic politics, but its awkward dialogue and romance make it a poor substitute for Empire''s tight emotional drama.', null);  -- 313478 Star Wars: Episode V - The Empire Strikes Back 1980 | 313476 Star Wars: Episode II - Attack of the Clones 2002
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313479, 313474, 2, 'msdevlab', 'The Phantom Menace reaches a heroic ending, yet its kid-focused tone and comic relief do not match the stronger emotional closure of Return of the Jedi.', null);  -- 313479 Star Wars: Episode VI - Return of the Jedi 1983 | 313474 Star Wars: Episode I - The Phantom Menace 1999
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313477, 313506, 2, 'msdevlab', 'X-Wing includes the same Star Wars universe, but its mission-based flight gameplay misses the character tragedy and dramatic story that make Revenge of the Sith powerful.', null);  -- 313477 Star Wars: Episode III - Revenge of the Sith 2005 | 313506 Star Wars: X-Wing 1995
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313478, 313464, 2, 'msdevlab', 'Rogue Leader uses Rebel-pilot action, but it is mainly an arcade flight experience, not the character-driven tension that defines The Empire Strikes Back.', null);  -- 313478 Star Wars: Episode V - The Empire Strikes Back 1980 | 313464 Star Wars Rogue Leader: Rogue Squadron 2 2001
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313477, 313488, 2, 'msdevlab', 'Jedi Starfighter shares space battles with the prequel era, but its vehicle-combat focus lacks the Anakin downfall and emotional stakes of Revenge of the Sith.', null);  -- 313477 Star Wars: Episode III - Revenge of the Sith 2005 | 313488 Star Wars: Jedi Starfighter 2002
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313489, 313486, 2, 'msdevlab', 'Mysteries of the Sith has Force-user gameplay, yet its dated design and thinner story cannot satisfy someone who liked Knights of the Old Republic for its RPG depth.', null);  -- 313489 Star Wars: Knights of the Old Republic 2003 | 313486 Star Wars: Jedi Knight - Mysteries of the Sith 1998
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313489, 313493, 2, 'msdevlab', 'Racer Revenge is only a Star Wars racing spin-off, so it misses the choices, characters, and long narrative arc that make Knights of the Old Republic interesting.', null);  -- 313489 Star Wars: Knights of the Old Republic 2003 | 313493 Star Wars: Racer Revenge 2002
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (280284, 280305, 2, 'msdevlab', 'Rocky V follows the same boxer, but its street-level drama feels deflated after Rocky IV''s bigger training montage, patriotic showdown, and inspirational energy.', null);  -- 280284 Rocky IV 1985 | 280305 Rocky V 1990
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (280270, 280305, 2, 'msdevlab', 'The original Rocky works because of its underdog heart, while Rocky V shifts into a bleak street conflict that loses the emotional simplicity of the first film.', null);  -- 280270 Rocky 1976 | 280305 Rocky V 1990
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (280282, 280305, 2, 'msdevlab', 'Rocky III has arena excitement and a memorable comeback arc, but Rocky V replaces that energy with a weaker street story and less satisfying rivalry.', null);  -- 280282 Rocky III 1982 | 280305 Rocky V 1990
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (271095, 159167, 2, 'msdevlab', 'Indiana Jones 4 keeps the adventure brand, but the CGI-heavy alien direction feels forced compared with Raiders of the Lost Ark''s practical danger and clean treasure-hunt momentum.', null);  -- 271095 Raiders of the Lost Ark 1981 | 159167 Indiana Jones 4 2006
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (159172, 159167, 2, 'msdevlab', 'Last Crusade balances mystery, humor, and the father-son bond, while Indiana Jones 4''s alien mythology feels less grounded and much less emotionally warm.', null);  -- 159172 Indiana Jones and the Last Crusade 1989 | 159167 Indiana Jones 4 2006
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (159172, 159175, 2, 'msdevlab', 'Temple of Doom is still Indy, but its harsher violence and darker atmosphere make it a poor fit for fans of Last Crusade''s lighter humor and family dynamic.', null);  -- 159172 Indiana Jones and the Last Crusade 1989 | 159175 Indiana Jones and the Temple of Doom 1984
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (215876, 215878, 2, 'msdevlab', 'Operation Surma uses the IMF name, but its routine gadget missions do not recreate the paranoia, betrayal, and suspense that make the 1996 Mission Impossible memorable.', null);  -- 215876 Mission: Impossible 1996 | 215878 Mission: Impossible - Operation Surma 2003
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (215880, 215877, 2, 'msdevlab', 'The 1998 Mission Impossible entry feels much thinner as a story, especially compared with Mission Impossible III''s personal danger around Ethan and Julia.', null);  -- 215880 Mission: Impossible III 2006 | 215877 Mission: Impossible 1998
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (215880, 215878, 2, 'msdevlab', 'Operation Surma has spy assignments, but it lacks the urgent villain, emotional stakes, and cinematic tension that make Mission Impossible III work.', null);  -- 215880 Mission: Impossible III 2006 | 215878 Mission: Impossible - Operation Surma 2003
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (300229, 311607, 2, 'msdevlab', 'SuperSponge is too game-like and child-focused for a Shrek fan, because Shrek combines fairy-tale satire, adult jokes, and a real emotional arc.', null);  -- 300229 Shrek 2001 | 311607 SpongeBob SquarePants: SuperSponge 2001
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (300230, 311604, 2, 'msdevlab', 'Legend of the Lost Spatula is a very thin SpongeBob adventure, while Shrek 2 succeeds because of sharper jokes, family tension, and stronger characters.', null);  -- 300230 Shrek 2 2004 | 311604 SpongeBob SquarePants: Legend of the Lost Spatula 2001
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (300229, 311604, 2, 'msdevlab', 'SpongeBob''s Lost Spatula is silly in a much more juvenile way, so it does not match Shrek''s mix of parody, romance, and character growth.', null);  -- 300229 Shrek 2001 | 311604 SpongeBob SquarePants: Legend of the Lost Spatula 2001
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (190869, 311606, 2, 'msdevlab', 'Revenge of the Flying Dutchman has goofy cartoon chaos, but it lacks the family theme and emotional loneliness that give Lilo and Stitch its heart.', null);  -- 190869 Lilo & Stitch 2002 | 311606 SpongeBob SquarePants: Revenge of the Flying Dutchman 2002
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (300229, 849, 2, 'msdevlab', 'Patch''s London Adventure is aimed much younger and feels plot-light, which makes it a weak match for Shrek''s layered humor and outsider love story.', null);  -- 300229 Shrek 2001 | 849 101 Dalmatians II: Patch's London Adventure 2003
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (300230, 850, 2, 'msdevlab', 'The 101 Dalmatians sing-along is basically music-focused children''s material, not a full comic story like Shrek 2 with jokes, conflict, and character payoff.', null);  -- 300230 Shrek 2 2004 | 850 101 Dalmatians Sing Along 1996
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (190869, 849, 2, 'msdevlab', 'Patch''s London Adventure has cute animals, but it does not reach Lilo and Stitch''s emotional focus on family, loneliness, and belonging.', null);  -- 190869 Lilo & Stitch 2002 | 849 101 Dalmatians II: Patch's London Adventure 2003
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (300229, 312152, 2, 'msdevlab', 'Spy Kids 3-D is family entertainment, but its video-game gimmick and thin plot do not offer the clever fairy-tale satire that makes Shrek memorable.', null);  -- 300229 Shrek 2001 | 312152 Spy Kids 3-D: Game Over 2003
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (312150, 312152, 2, 'msdevlab', 'The first Spy Kids has a fun family-spy idea, while Spy Kids 3-D turns the series into a much weaker game-world gimmick with less character charm.', null);  -- 312150 Spy Kids 2001 | 312152 Spy Kids 3-D: Game Over 2003
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (312151, 312152, 2, 'msdevlab', 'Spy Kids 2 already leans childish, and Spy Kids 3-D pushes even further into shallow visual gimmicks instead of improving the family-adventure story.', null);  -- 312151 Spy Kids 2: Island of Lost Dreams 2002 | 312152 Spy Kids 3-D: Game Over 2003
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (162380, 312150, 2, 'msdevlab', 'Spy Kids has tech and missions, but its very young target audience makes it a poor match for Iron Man''s confident adult humor, charisma, and superhero stakes.', null);  -- 162380 Iron Man 2005 | 312150 Spy Kids 2001
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (109421, 54209, 2, 'msdevlab', 'Cape Fear turns pursuit into psychological horror and stalking, which is completely different from The Fast and the Furious'' racing, friendship, and adrenaline.', null);  -- 109421 Fast and the Furious, The 2001 | 54209 Cape Fear 1991
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (109421, 120506, 2, 'msdevlab', 'From Hell is a grim Jack the Ripper thriller, so its horror mood does not match the street-racing excitement and lighter energy of The Fast and the Furious.', null);  -- 109421 Fast and the Furious, The 2001 | 120506 From Hell 2001
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (162380, 176711, 2, 'msdevlab', 'Kill Bill is stylish action, but its revenge violence and harsh tone are far darker than Iron Man''s witty, polished superhero adventure.', null);  -- 162380 Iron Man 2005 | 176711 Kill Bill: Vol. 1 2003
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (238072, 276217, 2, 'msdevlab', 'Reservoir Dogs is also about criminals, yet its brutal mistrust and warehouse tension clash with Ocean''s Eleven''s playful, elegant heist style.', null);  -- 238072 Ocean's Eleven 2001 | 276217 Reservoir Dogs 1992
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (238072, 267038, 2, 'msdevlab', 'Pulp Fiction has sharp crime dialogue, but its disturbing violence and cynical structure make it a bad fit for someone expecting Ocean''s Eleven''s charming team heist.', null);  -- 238072 Ocean's Eleven 2001 | 267038 Pulp Fiction 1994
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (129185, 270971, 2, 'msdevlab', 'Raging Bull centers on physical conflict, but its self-destructive psychological portrait is the opposite of Gladiator''s honorable heroism and epic revenge quest.', null);  -- 129185 Gladiator 2000 | 270971 Raging Bull 1980
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (280284, 270971, 2, 'msdevlab', 'Raging Bull is serious boxing cinema, yet its bleak character study does not match Rocky IV''s uplifting training, music, and Cold War victory feeling.', null);  -- 280284 Rocky IV 1985 | 270971 Raging Bull 1980
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (297838, 291698, 2, 'msdevlab', 'Se7en has Morgan Freeman and strong drama, but its serial-killer darkness would feel punishing for fans of Shawshank''s patient hope and human warmth.', null);  -- 297838 Shawshank Redemption, The 1994 | 291698 Se7en 1995
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (297838, 326155, 2, 'msdevlab', 'Taxi Driver is a classic character study, but its violent isolation and urban decay move in the opposite emotional direction from Shawshank''s dignity and hope.', null);  -- 297838 Shawshank Redemption, The 1994 | 326155 Taxi Driver 1976
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (333856, 30686, 2, 'msdevlab', 'Basketball Diaries also stars a young Leonardo DiCaprio, but its addiction and street-crime descent have none of Titanic''s sweeping romance or tragic grandeur.', null);  -- 333856 Titanic 1997 | 30686 Basketball Diaries, The 1995
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (263360, 185176, 2, 'msdevlab', 'Last Dance has a woman trying to change her life, but it lacks the central chemistry, charm, and romantic fantasy that make Pretty Woman enjoyable.', null);  -- 263360 Pretty Woman 1990 | 185176 Last Dance 2002
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (151616, 46878, 2, 'msdevlab', 'Bridget Jones: The Edge of Reason has romantic-comedy elements, but its sequel messiness and repetitive misunderstandings feel weaker than How to Lose a Guy''s focused battle-of-the-sexes setup.', null);  -- 151616 How to Lose a Guy in 10 Days 2003 | 46878 Bridget Jones: The Edge of Reason 2004
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (644, 200864, 2, 'msdevlab', 'Maid in Manhattan uses a social-class romance, yet its predictable Cinderella plot has less wit and spark than 10 Things I Hate About You.', null);  -- 644 10 Things I Hate About You 1999 | 200864 Maid in Manhattan 2002
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (158999, 65811, 2, 'msdevlab', 'Close Encounters is an alien-contact film, but its slow wonder-focused mood is very different from Independence Day''s loud disaster action and heroic speeches.', null);  -- 158999 Independence Day 1996 | 65811 Close Encounters of the Third Kind 1977
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (158999, 256839, 2, 'msdevlab', 'Pitch Black has humans against alien danger, but the dark survival-horror atmosphere does not match Independence Day''s crowd-pleasing, triumphant blockbuster style.', null);  -- 158999 Independence Day 1996 | 256839 Pitch Black 2000
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (214755, 10945, 2, 'msdevlab', 'Alien is sci-fi, but its creature-horror suspense is too scary and claustrophobic for someone looking for Minority Report''s clever future-crime chase.', null);  -- 214755 Minority Report 2002 | 10945 Alien 1992
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (214755, 10920, 2, 'msdevlab', 'Aliens adds action to sci-fi, yet its monster-horror intensity is still a poor match for Minority Report''s mystery, technology, and chase-thriller logic.', null);  -- 214755 Minority Report 2002 | 10920 Aliens 1986
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (162380, 21213, 2, 'msdevlab', 'A.I. also deals with technology and humanity, but its slow melancholy tone would frustrate someone expecting Iron Man''s fast charisma and superhero fun.', null);  -- 162380 Iron Man 2005 | 21213 Artificial Intelligence: AI 2001
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (214755, 40199, 2, 'msdevlab', 'Blade Runner shares futuristic noir ideas, but its abstract atmosphere and very slow mood do not fit Minority Report''s clearer suspense and movement.', null);  -- 214755 Minority Report 2002 | 40199 Blade Runner 1982
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (129185, 289109, 2, 'msdevlab', 'Saving Private Ryan is excellent war realism, but it is much heavier and more traumatic than Gladiator''s heroic ancient revenge adventure.', null);  -- 129185 Gladiator 2000 | 289109 Saving Private Ryan 1998
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (46169, 289109, 2, 'msdevlab', 'Saving Private Ryan and Braveheart both involve sacrifice, yet the WWII realism feels harsher and less romantic than Braveheart''s sweeping freedom epic.', null);  -- 46169 Braveheart 1995 | 289109 Saving Private Ryan 1998
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (131885, 54209, 2, 'msdevlab', 'Cape Fear is built on violent psychological menace, which makes it a terrible follow-up for The Goonies'' playful treasure-hunt friendship adventure.', null);  -- 131885 Goonies, The 1985 | 54209 Cape Fear 1991
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (149287, 292671, 2, 'msdevlab', 'Secret Window has a writer and a strange mystery, but its dark psychological twist is far from Hook''s nostalgic Peter Pan family adventure.', null);  -- 149287 Hook 1991 | 292671 Secret Window 2004
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (97727, 304862, 2, 'msdevlab', 'Sleepy Hollow has Burton style, yet its stronger horror elements and murders make it a poor fit for Edward Scissorhands'' gentle outsider romance.', null);  -- 97727 Edward Scissorhands 1990 | 304862 Sleepy Hollow 1999
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (109421, 350424, 2, 'msdevlab', 'Vanilla Sky is driven by dream logic and psychological confusion, which would not satisfy a Fast and Furious fan looking for direct racing action.', null);  -- 109421 Fast and the Furious, The 2001 | 350424 Vanilla Sky 2001
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (109421, 200521, 2, 'msdevlab', 'Magnolia''s long, contemplative ensemble drama has almost nothing in common with The Fast and the Furious'' quick street-racing conflict and action momentum.', null);  -- 109421 Fast and the Furious, The 2001 | 200521 Magnolia 1999
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (56871, 164572, 2, 'msdevlab', 'Jackie Brown is a crime story with charm, but its slow Tarantino rhythm feels very different from Catch Me If You Can''s lighter, warmer chase.', null);  -- 56871 Catch Me If You Can 2002 | 164572 Jackie Brown 1997
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (56871, 306032, 2, 'msdevlab', 'Snatch is clever crime entertainment, but the chaotic editing and rough British underworld humor do not match Catch Me If You Can''s smoother Spielberg tone.', null);  -- 56871 Catch Me If You Can 2002 | 306032 Snatch. 2000
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (129185, 290070, 2, 'msdevlab', 'Schindler''s List is historically powerful, but its Holocaust tragedy is far heavier than Gladiator''s accessible heroic revenge and arena spectacle.', null);  -- 129185 Gladiator 2000 | 290070 Schindler's List 1993
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (333856, 245699, 2, 'msdevlab', 'Overboard has a rich-poor romance angle, but its dated mistaken-identity comedy feels too small beside Titanic''s epic class-crossing love story.', null);  -- 333856 Titanic 1997 | 245699 Overboard 1987
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (263360, 311428, 2, 'msdevlab', 'Splash is an unlikely romance, but the mermaid fantasy and 1980s silliness do not offer Pretty Woman''s glamour, chemistry, and makeover charm.', null);  -- 263360 Pretty Woman 1990 | 311428 Splash 1984
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (86263, 203649, 2, 'msdevlab', 'The Man with the Golden Gun includes Bond assassins, but its goofy 1970s tone and weaker plot would disappoint someone who prefers Die Another Day''s bigger modern spectacle.', null);  -- 86263 Die Another Day 2002 | 203649 Man with the Golden Gun, The 1974
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (335336, 120574, 2, 'msdevlab', 'From Russia with Love has classic espionage, yet its slower Cold War style is not ideal after Tomorrow Never Dies'' fast media-conspiracy action.', null);  -- 335336 Tomorrow Never Dies 1997 | 120574 From Russia with Love 1963
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (368418, 372233, 2, 'msdevlab', 'You Only Live Twice has a giant villain lair, but its dated 1960s execution feels weaker than The World Is Not Enough''s more personal stakes.', null);  -- 368418 World Is Not Enough, The 1999 | 372233 You Only Live Twice 1967
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (311037, 406158, 2, 'msdevlab', 'The 2003 Spider-Man version has the character in action, but it lacks the full origin story, emotion, and cinematic scale of the 2002 film.', null);  -- 311037 Spider-Man 2002 | 406158 "Spider-Man" 2003
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (311038, 311036, 2, 'msdevlab', 'The 2000 Spider-Man game shares the hero, yet it cannot deliver Spider-Man 2''s emotional Peter Parker conflict or memorable Doctor Octopus story.', null);  -- 311038 Spider-Man 2 2004 | 311036 Spider-Man 2000
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (238072, 178994, 2, 'msdevlab', 'Knockaround Guys also involves crime groups, but it lacks the polish, wit, and star-powered teamwork that make Ocean''s Eleven so fun.', null);  -- 238072 Ocean's Eleven 2001 | 178994 Knockaround Guys 2001
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (39551, 326155, 2, 'msdevlab', 'Taxi Driver explores violence through one man''s isolation, while Black Hawk Down is about a military rescue mission and battlefield teamwork.', null);  -- 39551 Black Hawk Down 2001 | 326155 Taxi Driver 1976
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (39551, 30686, 2, 'msdevlab', 'Basketball Diaries follows danger around young men, but its addiction drama is far from Black Hawk Down''s urgent soldiers-under-fire combat story.', null);  -- 39551 Black Hawk Down 2001 | 30686 Basketball Diaries, The 1995
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (162380, 319602, 2, 'msdevlab', 'Superman 1978 matters to superhero history, but its slower, campier tone cannot match Iron Man''s modern wit, technology, and pacing.', null);  -- 162380 Iron Man 2005 | 319602 Superman 1978
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (162380, 319613, 2, 'msdevlab', 'Superman II has superhero conflict, yet its older effects and lighter 1980s humor feel dated next to Iron Man''s sleek modern confidence.', null);  -- 162380 Iron Man 2005 | 319613 Superman II 1980
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (30959, 319602, 2, 'msdevlab', 'Superman 1978 is an origin film, but its bright, campy optimism does not fit Batman Begins'' darker fear-based realism.', null);  -- 30959 Batman Begins 2005 | 319602 Superman 1978
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (297838, 209158, 2, 'msdevlab', 'Mean Streets is a respected crime drama, but its rough 1970s street violence feels too bleak and distant from Shawshank''s hopeful prison story.', null);  -- 297838 Shawshank Redemption, The 1994 | 209158 Mean Streets 1973
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (151616, 200521, 2, 'msdevlab', 'Magnolia includes relationship struggles, but its long, heavy ensemble drama is the wrong mood for How to Lose a Guy''s upbeat romantic comedy.', null);  -- 151616 How to Lose a Guy in 10 Days 2003 | 200521 Magnolia 1999
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (215876, 215875, 2, 'msdevlab', 'The 1991 Mission Impossible version has the title, but it lacks Tom Cruise''s star presence and the tense betrayal plot of the 1996 film.', null);  -- 215876 Mission: Impossible 1996 | 215875 Mission: Impossible 1991
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (300229, 267038, 2, 'msdevlab', 'Pulp Fiction subverts crime genres, but its cynical violence is far away from Shrek''s warm fairy-tale parody and emotional humor.', null);  -- 300229 Shrek 2001 | 267038 Pulp Fiction 1994
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (238072, 371305, 2, 'msdevlab', 'Yes and may be an ensemble film, but its unclear plot and forgettable character work make it weak beside Ocean''s Eleven''s crisp heist structure.', null);  -- 238072 Ocean's Eleven 2001 | 371305 Yes and 2004
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (194497, 194492, 2, 'msdevlab', 'The 1990 Lord of the Rings adaptation covers Tolkien material, but it cannot match Fellowship''s emotional scale, cast chemistry, and visual world-building.', null);  -- 194497 Lord of the Rings: The Fellowship of the Ring, The 2001 | 194492 Lord of the Rings 1990
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (194502, 194501, 2, 'msdevlab', 'The Third Age is set in Middle-earth, yet its game structure cannot replace The Two Towers'' character arcs, battles, and cinematic urgency.', null);  -- 194502 Lord of the Rings: The Two Towers, The 2002 | 194501 Lord of the Rings: The Third Age 2004
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (194495, 194504, 2, 'msdevlab', 'The War of the Ring uses Middle-earth battles, but strategy-game mechanics do not capture Return of the King''s emotional endings and character payoffs.', null);  -- 194495 Lord of the Rings: Return of the King, The (2003/II) 2003 | 194504 Lord of the Rings: The War of the Ring, The 2003
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (335835, 54209, 2, 'msdevlab', 'Cape Fear''s stalker-thriller violence is the wrong direction for a Top Gun fan who wants jets, rivalry, romance, and high-energy military spectacle.', null);  -- 335835 Top Gun 1986 | 54209 Cape Fear 1991
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (210739, 291698, 2, 'msdevlab', 'Se7en also follows investigators, but its bleak serial-killer case is the opposite of Men in Black''s playful aliens and buddy-cop humor.', null);  -- 210739 Men in Black 1997 | 291698 Se7en 1995
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (335835, 291698, 2, 'msdevlab', 'Se7en has pressure and investigation, yet its dark crime mood would disappoint someone expecting Top Gun''s fast, uplifting aviation excitement.', null);  -- 335835 Top Gun 1986 | 291698 Se7en 1995
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (210739, 326155, 2, 'msdevlab', 'Taxi Driver''s unstable urban isolation has no match with Men in Black''s light alien cases, comedy timing, and Will Smith charm.', null);  -- 210739 Men in Black 1997 | 326155 Taxi Driver 1976
insert into movies_recommendations(base_movie_id, recommended_movie_id, recommendation, suggested_by, justification, comment) values (313478, 313508, 2, 'msdevlab', 'X-Wing vs. TIE Fighter stays inside Star Wars, but its technical space-combat focus misses the emotional story that makes The Empire Strikes Back special.', null);  -- 313478 Star Wars: Episode V - The Empire Strikes Back 1980 | 313508 Star Wars: X-Wing vs. TIE Fighter 1996
