INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (276085, 10, 'talh2000', 'This movie is so upsetting and it really shocks your soul.', NULL); -- 276085 Requiem for a Dream (2000)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (289109, 10, 'talh2000', 'A brutal, unforgettable war picture; the opening Omaha Beach sequence is legendary.', NULL); -- 289109 Saving Private Ryan (1998)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (330388, 8, 'talh2000', 'A meditative, visually stunning meditation on war.', NULL); -- 330388 Thin Red Line, The (1998)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (300230, 10, 'talh2000', 'I love this sequel. The funny songs make it a joy to watch.', NULL); -- 300230 Shrek 2 (2004)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (300229, 7, 'talh2000', 'A very funny movie that makes fun of old stories in a cool way.', NULL); -- 300229 Shrek (2001)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (30959, 8, 'talh2000', 'The best way to show how Batman started. It feels real.', NULL); -- 30959 Batman Begins (2005)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (207992, 9, 'talh2000', 'The techno music fits the digital world and action perfectly.', NULL); -- 207992 Matrix, The (1999)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (18960, 9, 'talh2000', 'A hallucinatory descent into the heart of Vietnam.', NULL); -- 18960 Apocalypse Now (1979)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (333856, 8, 'talh2000', 'A very sad love story. The moving flute music made me sad.', NULL); -- 333856 Titanic (1997)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (210511, 8, 'talh2000', 'The story moves backwards and it is very smart and unique.', NULL); -- 210511 Memento (2000)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (112290, 8, 'talh2000', 'A wild movie with a big surprise that makes you think.', NULL); -- 112290 Fight Club (1999)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (267038, 10, 'talh2000', 'The retro songs fit the cool vibe of the movie perfectly, most iconic Tarantino film.', NULL); -- 267038 Pulp Fiction (1994)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (131780, 9, 'talh2000', 'A great look at mob life. The period songs fit the era well.', NULL); -- 131780 Goodfellas (1990)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (257459, 8, 'talh2000', 'Raw and unflinching combat through a young soldier''s eyes.', NULL); -- 257459 Platoon (1986)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (290070, 10, 'talh2000', 'A very sad story. The violin music is truly heartbreaking.', NULL); -- 290070 Schindler's List (1993)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (337166, 9, 'talh2000', 'A classic that I loved as a kid and still enjoy today.', NULL); -- 337166 Toy Story (1995)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (10830, 8, 'talh2000', 'A scary space movie. The silence makes it feel very lonely.', NULL); -- 10830 Alien (1979)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (141544, 9, 'talh2000', 'The diner scene alone is worth the whole movie.', NULL); -- 141544 Heat (1995)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (10920, 8, 'talh2000', 'Action at its best and more exciting than the first one.', NULL); -- 10920 Aliens (1986)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (297838, 10, 'talh2000', 'A beautiful story about having a real friend in prison.', NULL); -- 297838 Shawshank Redemption, The (1994)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (40199, 7, 'talh2000', 'The dark synth music fits this future city vibe perfectly.', NULL); -- 40199 Blade Runner (1982)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (46169, 9, 'talh2000', 'Big battles and a strong story about fighting for freedom.', NULL); -- 46169 Braveheart (1995)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (335835, 8, 'talh2000', 'Fast planes and cool rock songs that make you feel the speed.', NULL); -- 335835 Top Gun (1986)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (326155, 7, 'talh2000', 'A dark story about a lonely man. The city feels very dirty.', NULL); -- 326155 Taxi Driver (1976)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (159172, 9, 'talh2000', 'The adventure music and the jokes make this a perfect movie.', NULL); -- 159172 Indiana Jones and the Last Crusade (1989)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (271095, 8, 'talh2000', 'The trumpet theme is famous and makes scenes feel exciting.', NULL); -- 271095 Raiders of the Lost Ark (1981)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (313478, 9, 'talh2000', 'A great sequel with a big secret and iconic hero music.', NULL); -- 313478 Star Wars: Episode V - The Empire Strikes Back (1980)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (313479, 8, 'talh2000', 'A satisfying ending to the original story with a lot of heart.', NULL); -- 313479 Star Wars: Episode VI - Return of the Jedi (1983)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (49696, 9, 'talh2000', 'The whistling music in the desert makes this feel so cool.', NULL); -- 49696 Buono, il brutto, il cattivo, Il (1966)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (188507, 8, 'talh2000', 'The saxophone music really fits the cool cop vibe of the eighties.', NULL); -- 188507 Lethal Weapon (1987)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (188509, 8, 'talh2000', 'A great action sequel that keeps the same high energy.', NULL); -- 188509 Lethal Weapon 2 (1989)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (301540, 10, 'talh2000', 'Hopkins is hypnotic; the tension never lets up.', NULL); -- 301540 Silence of the Lambs, The (1991)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (139657, 7, 'talh2000', 'The magical music theme makes you feel like you are there.', NULL); -- 139657 Harry Potter and the Sorcerer's Stone (2001)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (137655, 8, 'talh2000', 'The simple piano notes are so scary and iconic for horror.', NULL); -- 137655 Halloween (1978)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (139655, 8, 'talh2000', 'My favorite in the series. The style and the music are cool.', NULL); -- 139655 Harry Potter and the Prisoner of Azkaban (2004)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (191246, 10, 'talh2000', 'The opening song is one of the best moments in any cartoon.', NULL); -- 191246 Lion King, The (1994)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (319602, 8, 'talh2000', 'The classic hero music makes you believe he can really fly.', NULL); -- 319602 Superman (1978)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (97727, 9, 'talh2000', 'A beautiful but sad story. The pretty music fits it well.', NULL); -- 97727 Edward Scissorhands (1990)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (30955, 8, 'talh2000', 'A dark and cool Batman. The music by Danny Elfman is great.', NULL); -- 30955 Batman (1989)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (291698, 9, 'talh2000', 'A grim, relentless thriller with a devastating finale.', NULL); -- 291698 Se7en (1995)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (311038, 9, 'talh2000', 'The best Spider-Man movie. It shows the hard hero life.', NULL); -- 311038 Spider-Man 2 (2004)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (130128, 9, 'talh2000', 'The classic slow music makes the whole story feel grand.', NULL); -- 130128 Godfather, The (1972)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (348944, 9, 'talh2000', 'Twisty, stylish, and the ending still surprises on rewatches.', NULL); -- 348944 Usual Suspects, The (1995)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (215876, 8, 'talh2000', 'A cool spy movie with a theme song that everyone knows.', NULL); -- 215876 Mission: Impossible (1996)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (256632, 9, 'talh2000', 'The pirate music is fun and makes the adventure better.', NULL); -- 256632 Pirates of the Caribbean: The Curse of the Black Pearl (2003)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (129185, 10, 'talh2000', 'Epic scale, great score, and a career-defining performance.', NULL); -- 129185 Gladiator (2000)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (123435, 9, 'talh2000', 'A clever movie that keeps you guessing. Very tense and cool.', NULL); -- 123435 Game, The (1997)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (56304, 9, 'talh2000', 'A fast look at the bad side of Vegas with a cool soundtrack.', NULL); -- 56304 Casino (1995)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (96593, 9, 'talh2000', 'Spielberg at his most tender; still magical.', NULL); -- 96593 E.T. the Extra-Terrestrial (1982)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (82967, 9, 'talh2000', 'Scorsese''s Boston crime epic; an ending nobody saw coming.', NULL); -- 82967 Departed, The (2006)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (65811, 10, 'talh2000', 'The five music notes are so famous and work perfectly.', NULL); -- 65811 Close Encounters of the Third Kind (1977)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (254986, 10, 'talh2000', 'The piano songs are beautiful and make the story sad.', NULL); -- 254986 Pianist, The (2002)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (26844, 10, 'talh2000', 'A near-perfect blockbuster with wit and heart.', NULL); -- 26844 Back to the Future (1985)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (186439, 10, 'talh2000', 'The desert theme music is grand and sounds amazing.', NULL); -- 186439 Lawrence of Arabia (1962)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (121538, 9, 'talh2000', 'The rhythmic songs in the army scenes feel strong.', NULL); -- 121538 Full Metal Jacket (1987)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (70959, 8, 'talh2000', 'A dark but sweet story. The songs fit the style well.', NULL); -- 70959 Corpse Bride, The (2005)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (74259, 8, 'talh2000', 'A funny take on old movies. The music is high energy.', NULL); -- 74259 Cry-Baby (1990)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (106790, 9, 'talh2000', 'The slow violin soundtrack is beautiful and very sad.', NULL); -- 106790 Fa yeung nin wa (2000)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (66194, 8, 'talh2000', 'A smart and funny look at school life. The songs are great.', NULL); -- 66194 Clueless (1995)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (644, 8, 'talh2000', 'A fresh and fun version of an old story with good music.', NULL); -- 644 10 Things I Hate About You (1999)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (313059, 9, 'talh2000', 'The friendship drama that defines coming-of-age.', NULL); -- 313059 Stand by Me (1986)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (67395, 9, 'talh2000', 'The gospel songs make the story feel very emotional.', NULL); -- 67395 Color Purple, The (1985)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (299073, 9, 'talh2000', 'The weird high noises in the music make this movie creepy.', NULL); -- 299073 Shining, The (1980)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (62076, 9, 'talh2000', 'A perfect neo-noir with one of the great endings.', NULL); -- 62076 Chinatown (1974)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (313459, 9, 'talh2000', 'The Imperial March is so cool and very scary for a movie.', NULL); -- 313459 Star Wars (1977)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (70248, 8, 'talh2000', 'Paranoia done with surgical precision.', NULL); -- 70248 Conversation, The (1974)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (303564, 9, 'talh2000', 'A ghost story that earns its twist.', NULL); -- 303564 Sixth Sense, The (1999)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (311040, 5, 'talh2000', 'Too many bad guys and the story felt a bit messy to me.', NULL); -- 311040 Spider-Man 3 (2007)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (30952, 2, 'talh2000', 'This was just a bad movie. It felt like a joke gone wrong.', NULL); -- 30952 Batman & Robin (1997)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (238073, 5, 'talh2000', 'It was okay but felt a bit too messy compared to the first.', NULL); -- 238073 Ocean's Twelve (2004)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (220805, 5, 'talh2000', 'Lots of action and shooting but the story was very simple.', NULL); -- 220805 Mr. and Mrs. Smith (2005)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (188511, 6, 'talh2000', 'Still okay but there was too much going on in the story.', NULL); -- 188511 Lethal Weapon 4 (1998)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (149287, 6, 'talh2000', 'A different take on Peter Pan. It was a nice family movie.', NULL); -- 149287 Hook (1991)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (379290, 8, 'talh2000', 'A cool old Batman cartoon. It sounds just like the 60s.', NULL); -- 379290 "Adventures of Batman, The" (1969)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (33179, 8, 'talh2000', 'Weird, wonderful, and hilariously unsettling.', NULL); -- 33179 Being John Malkovich (1999)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (134672, 9, 'talh2000', 'Sweet, existential, and quietly profound.', NULL); -- 134672 Groundhog Day (1993)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (337830, 9, 'talh2000', 'Kinetic, ugly, funny — the 90s on film.', NULL); -- 337830 Trainspotting (1996)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (113506, 9, 'talh2000', 'A very pretty movie about dreams and the Peter Pan creator.', NULL); -- 113506 Finding Neverland (2004)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (123849, 9, 'talh2000', 'The old city sounds and music make it feel very real.', NULL); -- 123849 Gangs of New York (2002)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (185628, 9, 'talh2000', 'The Japanese flute music makes the battles look epic.', NULL); -- 185628 Last Samurai, The (2003)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (220276, 9, 'talh2000', 'The songs are amazing. It is a very pretty movie to see.', NULL); -- 220276 Moulin Rouge! (2001)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (280270, 10, 'talh2000', 'The trumpet music in the training is very famous and good.', NULL); -- 280270 Rocky (1976)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (359297, 9, 'talh2000', 'The scary horn sound in the movie is very terrifying.', NULL); -- 359297 War of the Worlds (2005)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (372233, 8, 'talh2000', 'Bond in Japan. The soundtrack is actually very pretty.', NULL); -- 372233 You Only Live Twice (1967)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (406411, 8, 'talh2000', 'The war sounds in the cartoons are very well done.', NULL); -- 406411 "Star Wars: Clone Wars" (2003)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (1390, 7, 'talh2000', 'Spielberg''s loud, chaotic WWII comedy.', NULL); -- 1390 1941 (1979)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (1038, 9, 'talh2000', 'The 80s songs are amazing in this very fun comedy.', NULL); -- 1038 13 Going On 30 (2004)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (1121, 8, 'talh2000', 'The epic Vangelis music is just incredible to hear.', NULL); -- 1121 1492: Conquest of Paradise (1992)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (280281, 9, 'talh2000', 'The trumpet theme is still so strong and good here.', NULL); -- 280281 Rocky II (1979)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (280282, 8, 'talh2000', 'The Eye of the Tiger song is just perfect for this.', NULL); -- 280282 Rocky III (1982)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (124554, 8, 'talh2000', 'Quiet sci-fi with big ideas about fate and choice.', NULL); -- 124554 Gattaca (1997)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (311037, 8, 'talh2000', 'A good start for Spider-Man. It felt just like the comics.', NULL); -- 311037 Spider-Man (2002)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (160524, 8, 'talh2000', 'A tense thriller where the sun never goes down. Cool.', NULL); -- 160524 Insomnia (2002)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (328277, 10, 'talh2000', 'Action filmmaking at its absolute peak.', NULL); -- 328277 Terminator 2: Judgment Day (1991)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (209158, 9, 'talh2000', 'A raw story about guys in a rough city. Good acting.', NULL); -- 209158 Mean Streets (1973)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (328285, 9, 'talh2000', 'Lean, mean, and genre-defining.', NULL); -- 328285 Terminator, The (1984)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (34104, 8, 'talh2000', 'A sweet and odd story about love. It has heart.', NULL); -- 34104 Benny & Joon (1993)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (304862, 8, 'talh2000', 'A dark scary story. The music makes it feel spooky.', NULL); -- 304862 Sleepy Hollow (1999)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (59578, 7, 'talh2000', 'A colorful candy factory. The songs are fun for kids.', NULL); -- 59578 Charlie and the Chocolate Factory (2005)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (139650, 8, 'talh2000', 'Darker and more exciting. The magic world looks great.', NULL); -- 139650 Harry Potter and the Chamber of Secrets (2002)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (350424, 7, 'talh2000', 'A strange story about dreams. The songs are very moody.', NULL); -- 350424 Vanilla Sky (2001)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (86274, 10, 'talh2000', 'The template every action movie since has tried to copy.', NULL); -- 86274 Die Hard (1988)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (238695, 9, 'talh2000', 'Mike Judge''s workplace comedy that only gets funnier.', NULL); -- 238695 Office Space (1999)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (120506, 8, 'talh2000', 'A dark mystery set in old London. Very tense vibe.', NULL); -- 120506 From Hell (2001)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (247579, 8, 'talh2000', 'A tense thriller in one house. The sound design is good.', NULL); -- 247579 Panic Room (2002)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (69812, 7, 'talh2000', 'A fun movie about secret plots and mystery. Exciting.', NULL); -- 69812 Conspiracy Theory (1997)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (181766, 8, 'talh2000', 'A very pretty movie that takes its time to tell the story.', NULL); -- 181766 Kundun (1997)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (185704, 8, 'talh2000', 'A bold story that really makes you think about things.', NULL); -- 185704 Last Temptation of Christ, The (1988)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (328272, 8, 'talh2000', 'A nice story about a man stuck in an airport. Sweet.', NULL); -- 328272 Terminal, The (2004)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (318388, 8, 'talh2000', 'A fast road movie with a lot of soul and heart.', NULL); -- 318388 Sugarland Express, The (1974)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (183873, 8, 'talh2000', 'A nice magic story from long ago. The vibe was good.', NULL); -- 183873 Ladyhawke (1985)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (311428, 8, 'talh2000', 'A funny story with a lot of charm. The music is light.', NULL); -- 311428 Splash (1984)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (114955, 8, 'talh2000', 'A good story about growing up. It has a summer feeling.', NULL); -- 114955 Flamingo Kid, The (1984)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (235615, 8, 'talh2000', 'A serious look at a family. The dialogue is well written.', NULL); -- 235615 Nothing in Common (1986)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (31715, 8, 'talh2000', 'A sad and beautiful story about friends over years.', NULL); -- 31715 Beaches (1988)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (308025, 8, 'talh2000', 'A cool look for the city. It has a very tense feeling.', NULL); -- 308025 Someone to Watch Over Me (1987)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (210739, 9, 'talh2000', 'Fun with cool aliens. The music makes it high energy.', NULL); -- 210739 Men in Black (1997)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (158999, 8, 'talh2000', 'A huge movie about aliens. The action is very big.', NULL); -- 158999 Independence Day (1996)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (14477, 8, 'talh2000', 'A tough and important story. The acting is powerful.', NULL); -- 14477 Amistad (1997)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (330670, 8, 'talh2000', 'A real story with great acting. It feels grounded.', NULL); -- 330670 This Boy's Life (1993)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (118980, 8, 'talh2000', 'A sweet story with stars. The music is very nice.', NULL); -- 118980 Frankie and Johnny (1991)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (208245, 8, 'talh2000', 'A fast and fun western trip. The music is upbeat.', NULL); -- 208245 Maverick (1994)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (379327, 9, 'talh2000', 'A classic adventure with very bright and fun colors.', NULL); -- 379327 "Adventures of Robin Hood, The" (1955)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (311036, 7, 'talh2000', 'A cool hero cartoon. I liked the funny sound effects.', NULL); -- 311036 Spider-Man (2000)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (18979, 9, 'talh2000', 'A gripping true story told with real craft.', NULL); -- 18979 Apollo 13 (1995)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (370017, 8, 'talh2000', 'High energy action. The rock music is very loud.', NULL); -- 370017 XXX (2002)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (158927, 9, 'talh2000', 'Superhero family drama that works on every level.', NULL); -- 158927 Incredibles, The (2004)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (113504, 9, 'talh2000', 'Gorgeous, funny, and surprisingly moving.', NULL); -- 113504 Finding Nemo (2003)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (218415, 9, 'talh2000', 'Pixar at its most charming and inventive.', NULL); -- 218415 Monsters, Inc. (2001)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (194874, 9, 'talh2000', 'Quiet, melancholy, and wonderfully acted.', NULL); -- 194874 Lost in Translation (2003)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (267165, 8, 'talh2000', 'Sandler in a role no one expected; it works.', NULL); -- 267165 Punch-Drunk Love (2002)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (13789, 8, 'talh2000', 'Suburban disquiet captured with unusual clarity.', NULL); -- 13789 American Beauty (1999)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (222194, 9, 'talh2000', 'Lynch at his most hypnotic and baffling.', NULL); -- 222194 Mulholland Dr. (2001)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (32712, 9, 'talh2000', 'A whole romance in one walking conversation.', NULL); -- 32712 Before Sunrise (1995)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (32713, 9, 'talh2000', 'Even better than the original; real-time romance.', NULL); -- 32713 Before Sunset (2004)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (35522, 8, 'talh2000', 'Eddie Murphy''s charm carries a sharp action-comedy.', NULL); -- 35522 Beverly Hills Cop (1984)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (239851, 9, 'talh2000', 'Shocking, stylish Korean revenge thriller.', NULL); -- 239851 Oldboy (2003)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (300945, 8, 'talh2000', 'Wine country, midlife, and a genuinely human script.', NULL); -- 300945 Sideways (2004)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (270971, 9, 'talh2000', 'De Niro committing to the role like few actors ever have.', NULL); -- 270971 Raging Bull (1980)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (13978, 9, 'talh2000', 'Powerful, painful, and still relevant.', NULL); -- 13978 American History X (1998)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (37178, 9, 'talh2000', 'Shaggy, quotable, endlessly rewatchable.', NULL); -- 37178 Big Lebowski, The (1998)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (104338, 9, 'talh2000', 'Romance told backwards and sideways; emotionally brutal.', NULL); -- 104338 Eternal Sunshine of the Spotless Mind (2004)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (194818, 8, 'talh2000', 'Lynch noir that refuses to explain itself.', NULL); -- 194818 Lost Highway (1997)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (306032, 9, 'talh2000', 'Fast, funny British crime caper with a killer ensemble.', NULL); -- 306032 Snatch. (2000)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (193253, 9, 'talh2000', 'Ritchie''s debut; stylish crime comedy.', NULL); -- 193253 Lock, Stock and Two Smoking Barrels (1998)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (276217, 10, 'talh2000', 'A warehouse, a heist gone wrong, and a soundtrack to die for.', NULL); -- 276217 Reservoir Dogs (1992)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (176711, 9, 'talh2000', 'Pure Tarantino spectacle.', NULL); -- 176711 Kill Bill: Vol. 1 (2003)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (176712, 9, 'talh2000', 'The quieter, richer half of the story.', NULL); -- 176712 Kill Bill: Vol. 2 (2004)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (7842, 9, 'talh2000', 'A wild night in the city. The jazz is cool.', NULL); -- 7842 After Hours (1985)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (77701, 8, 'talh2000', 'Lars von Trier at his most emotionally ruthless.', NULL); -- 77701 Dancer in the Dark (2000)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (109093, 10, 'talh2000', 'Darkly funny, quietly devastating Coen classic.', NULL); -- 109093 Fargo (1996)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (280305, 5, 'talh2000', 'Not a great one. The music was okay though.', NULL); -- 280305 Rocky V (1990)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (41988, 9, 'talh2000', 'Lynch at his most unsettling and visually striking.', NULL); -- 41988 Blue Velvet (1986)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (271339, 8, 'talh2000', 'Coen brothers comedy at its warmest.', NULL); -- 271339 Raising Arizona (1987)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (299846, 8, 'talh2000', 'Altman weaving stories into a kaleidoscopic portrait.', NULL); -- 299846 Short Cuts (1993)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (99075, 8, 'talh2000', 'Quiet, clinical, devastating.', NULL); -- 99075 Elephant (2003)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (218345, 8, 'talh2000', 'Charlize Theron disappears into the role.', NULL); -- 218345 Monster (2003)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (90772, 8, 'talh2000', 'Weird, dreamy, and instantly iconic.', NULL); -- 90772 Donnie Darko (2001)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (14942, 9, 'talh2000', 'Intersecting tragedies told with raw energy.', NULL); -- 14942 Amores perros (2000)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (56044, 10, 'talh2000', 'Still the most romantic movie ever made.', NULL); -- 56044 Casablanca (1942)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (64729, 10, 'talh2000', 'The film that invented modern cinema.', NULL); -- 64729 Citizen Kane (1941)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (352639, 10, 'talh2000', 'Hitchcock''s most hypnotic and haunting masterpiece.', NULL); -- 352639 Vertigo (1958)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (266574, 10, 'talh2000', 'The shower scene is only the beginning.', NULL); -- 266574 Psycho (1960)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (235062, 9, 'talh2000', 'Hitchcock''s perfect chase thriller.', NULL); -- 235062 North by Northwest (1959)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (273543, 9, 'talh2000', 'A one-room thriller that never stops tightening.', NULL); -- 273543 Rear Window (1954)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (307913, 9, 'talh2000', 'Still the funniest film of its era.', NULL); -- 307913 Some Like It Hot (1959)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (302696, 10, 'talh2000', 'A musical where every number is a showstopper.', NULL); -- 302696 Singin' in the Rain (1952)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (130129, 10, 'talh2000', 'Expands and deepens the original in every way.', NULL); -- 130129 Godfather: Part II, The (1974)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (367073, 10, 'talh2000', 'The original spectacle; still mesmerizing.', NULL); -- 367073 Wizard of Oz, The (1939)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (1711, 10, 'talh2000', 'A cosmic trip nothing else has matched.', NULL); -- 1711 2001: A Space Odyssey (1968)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (92616, 10, 'talh2000', 'Kubrick''s darkest, funniest satire.', NULL); -- 92616 Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1964)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (241347, 10, 'talh2000', 'Nicholson at the peak of his powers.', NULL); -- 241347 One Flew Over the Cuckoo's Nest (1975)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (165961, 10, 'talh2000', 'The original summer blockbuster, still terrifying.', NULL); -- 165961 Jaws (1975)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (42056, 9, 'talh2000', 'A musical chase film with unbeatable energy.', NULL); -- 42056 Blues Brothers, The (1980)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (264146, 10, 'talh2000', 'Fairy-tale perfection from start to finish.', NULL); -- 264146 Princess Bride, The (1987)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (131885, 9, 'talh2000', 'The 80s adventure that lives on in every kid''s memory.', NULL); -- 131885 Goonies, The (1985)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (111442, 9, 'talh2000', 'The most charming truancy ever filmed.', NULL); -- 111442 Ferris Bueller's Day Off (1986)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (46322, 9, 'talh2000', 'John Hughes at his sharpest.', NULL); -- 46322 Breakfast Club, The (1985)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (80583, 9, 'talh2000', 'Williams turns the teacher drama into something unforgettable.', NULL); -- 80583 Dead Poets Society (1989)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (271192, 8, 'talh2000', 'Brother-road-movie with one of Hoffman''s best performances.', NULL); -- 271192 Rain Man (1988)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (362808, 9, 'talh2000', 'The romantic comedy template every other tries to copy.', NULL); -- 362808 When Harry Met Sally... (1989)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (117874, 9, 'talh2000', 'Sentimental in the best way; Hanks carries everything.', NULL); -- 117874 Forrest Gump (1994)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (77728, 8, 'talh2000', 'Sweeping revisionist western.', NULL); -- 77728 Dances with Wolves (1990)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (271915, 9, 'talh2000', 'Kurosawa''s devastating late masterpiece.', NULL); -- 271915 Ran (1985)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (371844, 9, 'talh2000', 'Kurosawa invents the lone-gunslinger archetype.', NULL); -- 371844 Yojimbo (1961)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (241141, 9, 'talh2000', 'Leone''s sprawling gangster epic.', NULL); -- 241141 Once Upon a Time in America (1984)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (198435, 9, 'talh2000', 'Fritz Lang''s serial-killer thriller still shocks.', NULL); -- 198435 M (1931)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (212097, 9, 'talh2000', 'Silent sci-fi that invented the genre.', NULL); -- 212097 Metropolis (1927)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (312963, 9, 'talh2000', 'Tarkovsky''s slow, haunting journey.', NULL); -- 312963 Stalker (1979)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (253440, 9, 'talh2000', 'Bergman''s most unsettling psychological study.', NULL); -- 253440 Persona (1966)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (202537, 9, 'talh2000', 'The noir that set the template for every detective film after.', NULL); -- 202537 Maltese Falcon, The (1941)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (92573, 8, 'talh2000', 'The Bond film that started it all.', NULL); -- 92573 Dr. No (1962)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (130953, 9, 'talh2000', 'Peak Connery-era Bond.', NULL); -- 130953 Goldfinger (1964)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (120574, 9, 'talh2000', 'Bond at his most cold-war spiky.', NULL); -- 120574 From Russia with Love (1963)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (159175, 8, 'talh2000', 'Darker, weirder Indy sequel.', NULL); -- 159175 Indiana Jones and the Temple of Doom (1984)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (309634, 9, 'talh2000', 'A musical landslide you can hum in your sleep.', NULL); -- 309634 Sound of Music, The (1965)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (361688, 9, 'talh2000', 'Musical romance with some of the best dance ever filmed.', NULL); -- 361688 West Side Story (1961)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (223867, 8, 'talh2000', 'Stage-to-screen perfection.', NULL); -- 223867 My Fair Lady (1964)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (250861, 8, 'talh2000', 'Scott''s portrait of war''s most complicated general.', NULL); -- 250861 Patton (1970)
INSERT INTO personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) VALUES (7678, 8, 'talh2000', 'Bogart and Hepburn at their best.', NULL); -- 7678 African Queen, The (1951)

insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (1390, 5, 'Ronamit01', 'Not a classic Spielberg,messy plot', null); # 1390 1941 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (7842, 8, 'Ronamit01', 'A high-tension, gritty urban nightmare.', null); # 7842 After Hours 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (8183, 7, 'Ronamit01', 'Great story about social rules', null); # 8183 Age of Innocence, The 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10702, 7, 'Ronamit01', 'very beautiful atmosphere to the story', null); # 10702 Alice Doesn't Live Here Anymore 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (14132, 4, 'Ronamit01', 'Stupid.Funny,but not as near as the first one.', null); # 14132 American Pie 2 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (14477, 8, 'Ronamit01', 'Great movie based on real events', null); # 14477 Amistad 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30686, 8, 'Ronamit01', 'Tough movie, great acting of DiCaprio', null); # 30686 Basketball Diaries, The 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30955, 8, 'Ronamit01', 'one of the best versions of Batman', null); # 30955 Batman 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30967, 7, 'Ronamit01', 'Not as good as the first one but still great', null); # 30967 Batman Returns 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (31715, 6, 'Ronamit01', 'very sad but inspiring movie about friendship', null); # 31715 Beaches 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (32707, 7, 'Ronamit01', 'Thrilling movie about the struggle for personal freedom', null); # 32707 Before Night Falls 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (34104, 7, 'Ronamit01', 'very cute, interesting perspective on dealing with mental issues', null); # 34104 Benny & Joon 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (39551, 8, 'Ronamit01', 'Great combat movie based on real events, very nerve wracking.', null); # 39551 Black Hawk Down 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (39829, 7, 'Ronamit01', 'A tense, atmospheric clash of international cultures', null); # 39829 Black Rain 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (40199, 9, 'Ronamit01', 'A very original sci-fi movie harrison ford is great.', null); # 40199 Blade Runner 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (41518, 7, 'Ronamit01', 'A sad story about a massive criminal business with a twist.', null); # 41518 Blow 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (44238, 3, 'Ronamit01', 'A silly, messy horror movie with weak acting.', null); # 44238 Bordello of Blood 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46167, 6, 'Ronamit01', 'Heavy, a very sad story.', null); # 46167 Brave, The 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46169, 8, 'Ronamit01', 'Epic story, the Scottish atmosphere is nice.', null); # 46169 Braveheart 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46878, 5, 'Ronamit01', 'Cute, but shallow and predictable', null); # 46878 Bridget Jones: The Edge of Reason 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (47130, 7, 'Ronamit01', 'Dark and stressful but interesting.', null); # 47130 Bringing Out the Dead 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (53921, 4, 'Ronamit01', 'stupid movie about making movies.', null); # 53921 Cannes Man 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (54209, 9, 'Ronamit01', 'scary. De niro is great.', null); # 54209 Cape Fear 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56304, 8, 'Ronamit01', 'interesting perspective on gambling industry.', null); # 56304 Casino 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56871, 8, 'Ronamit01', 'Great acting by DiCaprio and Tom Hanks.', null); # 56871 Catch Me If You Can 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (59578, 10, 'Ronamit01', 'super nostalgic and cute movie for kids and adults.', null); # 59578 Charlie and the Chocolate Factory 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (61751, 8, 'Ronamit01', 'A beautiful story about the struggle to save the future.', null); # 61751 Children of Men, The 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (62460, 5, 'Ronamit01', 'A light story about how a small shop changes the town.', null); # 62460 Chocolat 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (65811, 6, 'Ronamit01', 'Old, but a good sci-fi movie', null); # 65811 Close Encounters of the Third Kind 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (66194, 5, 'Ronamit01', 'A Silly teen age comedy', null); # 66194 Clueless 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (67388, 8, 'Ronamit01', 'Interesting perspective on the gambling industry.', null); # 67388 Color of Money, The 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (67395, 8, 'Ronamit01', 'A very moving serious drama', null); # 67395 Color Purple, The 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (69812, 7, 'Ronamit01', 'starts strong turns into a generic action movie.', null); # 69812 Conspiracy Theory 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (70959, 6, 'Ronamit01', 'Visually great but too light.', null); # 70959 Corpse Bride, The 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (74259, 3, 'Ronamit01', 'Too silly and shallow.', null); # 74259 Cry-Baby 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (85871, 5, 'Ronamit01', 'Not a good James Bond.', null); # 85871 Diamonds Are Forever 1971
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (86263, 5, 'Ronamit01', 'Bad production,bad CGI.', null); # 86263 Die Another Day 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (92573, 6, 'Ronamit01', 'The first Bond, old but a classic.', null); # 92573 Dr. No 1962
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (96593, 9, 'Ronamit01', 'A classic movie about friendship against all odds.', null); # 96593 E.T. the Extra-Terrestrial 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (97360, 8, 'Ronamit01', 'Masterclass acting about a total failure that''s fascinating to watch.', null); # 97360 Ed Wood 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (97727, 6, 'Ronamit01', 'Great performance but a bit too much of a fairy tale.', null); # 97727 Edward Scissorhands 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (98681, 4, 'Ronamit01', 'Too generic and silly.', null); # 98681 El Mariachi: 10 Years Later 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (100130, 8, 'Ronamit01', 'An epic, war drama but a bit long.', null); # 100130 Empire of the Sun 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (109421, 6, 'Ronamit01', 'Silly but light and fun action', null); # 109421 Fast and the Furious, The 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (112290, 9, 'Ronamit01', 'Amazing psychological dark movie, great acting of brad pitt and edward norton.', null); # 112290 Fight Club 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (113506, 7, 'Ronamit01', 'Great acting, a bit too emotional.', null); # 113506 Finding Neverland 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (114955, 7, 'Ronamit01', 'Solid look at money and class', null); # 114955 Flamingo Kid, The 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (116556, 7, 'Ronamit01', 'Nolan''s first, cheap production but good.', null); # 116556 Following 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (117314, 6, 'Ronamit01', 'Another pretty stupid Bond movie.', null); # 117314 For Your Eyes Only 1981
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (118367, 6, 'Ronamit01', 'Very weird, divided into 4 parts.', null); # 118367 Four Rooms 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (118980, 6, 'Ronamit01', 'Good acting, but too simple.', null); # 118980 Frankie and Johnny 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120506, 7, 'Ronamit01', 'Nice movie about Jack The Ripper.', null); # 120506 From Hell 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (123435, 9, 'Ronamit01', 'Very smart and nerve wracking.', null); # 123435 Game, The 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (123849, 8, 'Ronamit01', 'Scorsese classic, nice atmosphere.', null); # 123849 Gangs of New York 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (25192, 7, 'Ronamit01', 'Nice movie, based on Howard Hughes'' life.', null); # 25192 Aviator, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (129185, 9, 'Ronamit01', 'A great thriller based on ancient Rome times.', null); # 129185 Gladiator 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130945, 7, 'Ronamit01', 'A slightly less stupid Bond.', null); # 130945 GoldenEye 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130953, 7, 'Ronamit01', 'Very old Bond but nice.', null); # 130953 Goldfinger 1964
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131780, 9, 'Ronamit01', 'Amazing movie about the mafia life.', null); # 131780 Goodfellas 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (142491, 6, 'Ronamit01', 'A weird super heroes movie.', null); # 142491 Hellboy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (149287, 6, 'Ronamit01', 'Looking at Peter Pan from a different angle.', null); # 149287 Hook 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30959, 8, 'Ronamit01', 'The best Batman series, but not the best in the series.', null); # 30959 Batman Begins 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (151616, 7, 'Ronamit01', 'silly but Matthew McConaughey is cute.', null); # 151616 How to Lose a Guy in 10 Days 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159172, 8, 'Ronamit01', 'One of the best Indiana Jones movies.', null); # 159172 Indiana Jones and the Last Crusade 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159665, 10, 'Ronamit01', 'Tarantino at his best, Also brad Pitt and Christoph Waltz are amazing.', null); # 159665 Inglorious Bastards 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (160375, 7, 'Ronamit01', 'Very emotional and down to earth.', null); # 160375 Inside Moves 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (160524, 8, 'Ronamit01', 'A great Pacino performance', null); # 160524 Insomnia 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (164572, 8, 'Ronamit01', 'Smart crime plan, grounded acting.', null); # 164572 Jackie Brown 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (165961, 6, 'Ronamit01', 'silly but scary', null); # 165961 Jaws 1975
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176711, 8, 'Ronamit01', 'Great cynical movie of Tarantino.', null); # 176711 Kill Bill: Vol. 1 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176712, 7, 'Ronamit01', 'not as good as the first one.', null); # 176712 Kill Bill: Vol. 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (177369, 7, 'Ronamit01', 'Dark, raw study of obsession.', null); # 177369 King of Comedy, The 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (178994, 7, 'Ronamit01', 'Tense, professional mob family drama.', null); # 178994 Knockaround Guys 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (181766, 7, 'Ronamit01', 'Epic, beautiful, slow historical biography.', null); # 181766 Kundun 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (183873, 6, 'Ronamit01', 'Stylized, technical 80s fantasy romance.', null); # 183873 Ladyhawke 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185628, 8, 'Ronamit01', 'great movie about different cultures.', null); # 185628 Last Samurai, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185704, 7, 'Ronamit01', 'Old yet an epic and serious drama.', null); # 185704 Last Temptation of Christ, The 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188507, 9, 'Ronamit01', 'A great classic, police movie.', null); # 188507 Lethal Weapon 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188511, 6, 'Ronamit01', 'Not a great one in the series.', null); # 188511 Lethal Weapon 4 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (192514, 7, 'Ronamit01', 'A Big-budget bond, but silly.', null); # 192514 Live and Let Die 1973
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194497, 10, 'Ronamit01', 'Amazing,one of the best fantasy movies ever.', null); # 194497 Lord of the Rings: The Fellowship of the Ring, The 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194500, 9, 'Ronamit01', 'Epic closure to the series.', null); # 194500 Lord of the Rings: The Return of the King, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194502, 8, 'Ronamit01', 'Very good but not as good as the first one.', null); # 194502 Lord of the Rings: The Two Towers, The 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (200521, 8, 'Ronamit01', 'Epic, intense, and masterful drama.', null); # 200521 Magnolia 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (200864, 5, 'Ronamit01', 'A glossy rom-com.', null); # 200864 Maid in Manhattan 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (203649, 7, 'Ronamit01', 'Professional hitman vs. gadget-heavy spy.', null); # 203649 Man with the Golden Gun, The 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (208245, 8, 'Ronamit01', 'Clever, big-budget, professional Western fun.', null); # 208245 Maverick 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (209158, 7, 'Ronamit01', 'Raw, serious look at loyalty.', null); # 209158 Mean Streets 1973
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210511, 8, 'Ronamit01', 'One of Nolan''s best movies.', null); # 210511 Memento 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210739, 7, 'Ronamit01', 'A classic, silly but fun.', null); # 210739 Men in Black 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (214755, 8, 'Ronamit01', 'Elite, technical, professional sci-fi mystery.', null); # 214755 Minority Report 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215876, 7, 'Ronamit01', 'Fun light action, featuring Tom Cruise.', null); # 215876 Mission: Impossible 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215879, 6, 'Ronamit01', 'Fun and light, not original.', null); # 215879 Mission: Impossible II 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218219, 8, 'Ronamit01', 'Great animated movie.', null); # 218219 Mononoke-hime 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218808, 5, 'Ronamit01', 'Another silly bond.', null); # 218808 Moonraker 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (220276, 6, 'Ronamit01', 'Elaborate, tragic, high-budget musical spectacle.', null); # 220276 Moulin Rouge! 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (220805, 7, 'Ronamit01', 'Great chemistry of Bradgelina.', null); # 220805 Mr. and Mrs. Smith 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (230947, 8, 'Ronamit01', 'Elite directors, raw urban tales.', null); # 230947 New York Stories 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (230963, 7, 'Ronamit01', 'Lavish, serious jazz-era relationship drama.', null); # 230963 New York, New York 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (233058, 8, 'Ronamit01', 'Elite, atmospheric Roman Polanski production.', null); # 233058 Ninth Gate, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (235615, 6, 'Ronamit01', 'Serious drama about professional life and family.', null); # 235615 Nothing in Common 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238072, 8, 'Ronamit01', 'Clever action with amazing cast.', null); # 238072 Ocean's Eleven 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238073, 7, 'Ronamit01', 'Good but not as the first one.', null); # 238073 Ocean's Twelve 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (240327, 7, 'Ronamit01', 'old but interesting.', null); # 240327 Omen, The 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (240521, 8, 'Ronamit01', 'super old but fun.', null); # 240521 On Her Majesty's Secret Service 1969
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (244421, 5, 'Ronamit01', 'Very predictable.', null); # 244421 Other Sister, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (245699, 6, 'Ronamit01', 'A charming blue collar comedy.', null); # 245699 Overboard 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (247579, 9, 'Ronamit01', 'Elite, tactical home-invasion thriller.', null); # 247579 Panic Room 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (253010, 8, 'Ronamit01', 'A classic eastwood,thrilling.', null); # 253010 Perfect World, A 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256627, 7, 'Ronamit01', 'Sharp, technical business-war drama.', null); # 256627 Pirates of Silicon Valley 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256632, 9, 'Ronamit01', 'Very fun and light fantasy, Johnny Depp is great.', null); # 256632 Pirates of the Caribbean: The Curse of the Black Pearl 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256839, 7, 'Ronamit01', 'Serious sci-fi survival thriller.', null); # 256839 Pitch Black 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (257744, 7, 'Ronamit01', 'Romantic with many stars.', null); # 257744 Playing by Heart 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (258948, 6, 'Ronamit01', 'Interesting but a bit over dramatic.', null); # 258948 Poison Ivy 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (259826, 7, 'Ronamit01', 'Spooky and fun.', null); # 259826 Poltergeist 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (263360, 6, 'Ronamit01', 'Cute but very cheesy.', null); # 263360 Pretty Woman 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (264157, 5, 'Ronamit01', 'Stupid but i like Anne Hathaway.', null); # 264157 Princess Diaries 2: Royal Engagement, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (267038, 9, 'Ronamit01', 'Amazing, dark and cynical with great acting.', null); # 267038 Pulp Fiction 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (270971, 8, 'Ronamit01', 'Great movie about boxing.', null); # 270971 Raging Bull 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (271095, 8, 'Ronamit01', 'Another great indiana Jones.', null); # 271095 Raiders of the Lost Ark 1981
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (271344, 6, 'Ronamit01', 'silly kids movie.', null); # 271344 Raising Helen 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (276217, 8, 'Ronamit01', 'Crime epic with a lot of humor,another classic of Tarantino.', null); # 276217 Reservoir Dogs 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280270, 8, 'Ronamit01', 'Iconic Boxing movie, original at the time.', null); # 280270 Rocky 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280281, 7, 'Ronamit01', 'Good but not as the first one.', null); # 280281 Rocky II 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280282, 6, 'Ronamit01', 'The plot is a bit boring.', null); # 280282 Rocky III 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280284, 7, 'Ronamit01', 'The mix of politics and boxing is interesting.', null); # 280284 Rocky IV 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (283410, 6, 'Ronamit01', 'professional small-town romantic comedy.', null); # 283410 Runaway Bride 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (289109, 10, 'Ronamit01', 'One of the greatest war movies of all time.', null); # 289109 Saving Private Ryan 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (290070, 9, 'Ronamit01', 'Great holocaust movie with many lessons to learn.', null); # 290070 Schindler's List 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (291698, 9, 'Ronamit01', 'Nerve wracking thriller, great acting by kevin spacey.', null); # 291698 Se7en 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (292671, 7, 'Ronamit01', 'Based on stephen king, interesting but predictable.', null); # 292671 Secret Window 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (297838, 10, 'Ronamit01', 'Amazing movie about about escaping from jail, many twists.', null); # 297838 Shawshank Redemption, The 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300229, 9, 'Ronamit01', 'Great movie about a green creature for kids and adults.', null); # 300229 Shrek 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300230, 8, 'Ronamit01', 'Good but not as the first one.', null); # 300230 Shrek 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (304862, 8, 'Ronamit01', 'Very gothic but mysterious.', null); # 304862 Sleepy Hollow 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (306032, 9, 'Ronamit01', 'Very original movie by Guy Ritchie.', null); # 306032 Snatch. 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311037, 8, 'Ronamit01', 'Tobey Maguire Was a very good fit to be Spiderman.', null); # 311037 Spider-Man 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311038, 7, 'Ronamit01', 'Another good movie in the series the villain was good.', null); # 311038 Spider-Man 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311428, 7, 'Ronamit01', 'An elegant romantic fantasy.', null); # 311428 Splash 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312170, 7, 'Ronamit01', 'Another generic yet amusing Bond movie.', null); # 312170 Spy Who Loved Me, The 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313160, 7, 'Ronamit01', 'Fascinating movie about the life and work of Kubrick.', null); # 313160 Stanley Kubrick: A Life in Pictures 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313474, 6, 'Ronamit01', 'Not the best of the not very good second trilogy of star wars.', null); # 313474 Star Wars: Episode I - The Phantom Menace 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313476, 6, 'Ronamit01', 'mediocre but still fun to watch.', null); # 313476 Star Wars: Episode II - Attack of the Clones 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313477, 7, 'Ronamit01', 'The best one from the second trilogy.', null); # 313477 Star Wars: Episode III - Revenge of the Sith 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (326155, 8, 'Ronamit01', 'A great classic with amazing acting of De Niro.', null); # 326155 Taxi Driver 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (328272, 7, 'Ronamit01', 'An elegant airport-survival drama.', null); # 328272 Terminal, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (330670, 7, 'Ronamit01', 'A grounded domestic drama.', null); # 330670 This Boy's Life 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (332209, 7, 'Ronamit01', 'Refined, serious, and intimate spiritual biography.', null); # 332209 Thrse: The Story of Saint Thrse of Lisieux 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (332065, 6, 'Ronamit01', 'Another generic Bond, some under water fun.', null); # 332065 Thunderball 1965
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (333856, 9, 'Ronamit01', 'Massive production with great acting, very long.', null); # 333856 Titanic 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335336, 5, 'Ronamit01', 'One of the worst Bond movies.', null); # 335336 Tomorrow Never Dies 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335835, 8, 'Ronamit01', 'Classic mix of romance and action.', null); # 335835 Top Gun 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (337166, 9, 'Ronamit01', 'Very original and fun cartoon movie.', null); # 337166 Toy Story 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (340652, 9, 'Ronamit01', 'An amazing epic about ancient times.', null); # 340652 Troy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (350424, 7, 'Ronamit01', 'Fun sci-fi with Tom Cruise.', null); # 350424 Vanilla Sky 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (354178, 5, 'Ronamit01', 'Another bad Bond, pretty stupid.', null); # 354178 View to a Kill, A 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (359297, 5, 'Ronamit01', 'Pretty stupid sci-fi.', null); # 359297 War of the Worlds 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (368418, 6, 'Ronamit01', 'mediocre Bond.', null); # 368418 World Is Not Enough, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (368865, 8, 'Ronamit01', 'Great documentary about Bret Hart, very recommended for WWE lovers.', null); # 368865 Wrestling with Shadows 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (370017, 5, 'Ronamit01', 'Vin Diesel in a pretty lame action movie.', null); # 370017 XXX 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (372233, 7, 'Ronamit01', 'Very old Bond but a nice one.', null); # 372233 You Only Live Twice 1967
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (372525, 5, 'Ronamit01', 'Cringe comedy about doctors.', null); # 372525 Young Doctors in Love 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (372733, 8, 'Ronamit01', 'Innovative and serious Victorian mystery.', null); # 372733 Young Sherlock Holmes 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10830, 8, 'Ronamit01', 'Amazing feministic sci-fi.', null); # 10830 Alien 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10920, 7, 'Ronamit01', 'Good but not as the first one.', null); # 10920 Aliens 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (21213, 7, 'Ronamit01', 'Nice visual effects.', null); # 21213 Artificial Intelligence: AI 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (158999, 6, 'Ronamit01', 'Fun but not very smart.', null); # 158999 Independence Day 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159167, 6, 'Ronamit01', 'Not the best Indiana Jones.', null); # 159167 Indiana Jones 4 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120574, 8, 'Ronamit01', 'One of the better early Bonds, stylish Cold War thriller.', null); # 120574 From Russia with Love 1963
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131885, 8, 'Ronamit01', 'Classic Spielberg adventure, fun for kids and adults alike.', null); # 131885 Goonies, The 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139657, 8, 'Ronamit01', 'Magical intro to a great fantasy world, very well produced.', null); # 139657 Harry Potter and the Sorcerer's Stone 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139655, 8, 'Ronamit01', 'The best Harry Potter, dark and emotionally mature.', null); # 139655 Harry Potter and the Prisoner of Azkaban 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139650, 7, 'Ronamit01', 'Good entry in the series, entertaining but less magical.', null); # 139650 Harry Potter and the Chamber of Secrets 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139652, 7, 'Ronamit01', 'Action-heavy Potter, exciting but overly long.', null); # 139652 Harry Potter and the Goblet of Fire 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159175, 8, 'Ronamit01', 'More exotic and intense than Raiders, thrilling adventure.', null); # 159175 Indiana Jones and the Temple of Doom 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188509, 7, 'Ronamit01', 'Great sequel, South Africa setting adds fresh energy.', null); # 188509 Lethal Weapon 2 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188510, 6, 'Ronamit01', 'Decent but the series is starting to feel tired.', null); # 188510 Lethal Weapon 3 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (189403, 6, 'Ronamit01', 'Timothy Dalton Bond, darker but not very memorable.', null); # 189403 Licence to Kill 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (190869, 7, 'Ronamit01', 'Charming and funny animated film, great for all ages.', null); # 190869 Lilo & Stitch 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (192702, 6, 'Ronamit01', 'Dalton brings realism to Bond but the film is forgettable.', null); # 192702 Living Daylights, The 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256631, 7, 'Ronamit01', 'Fun but messier than the first Pirates, too many characters.', null); # 256631 Pirates of the Caribbean 2 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280305, 5, 'Ronamit01', 'The weakest Rocky, lost its spirit completely.', null); # 280305 Rocky V 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (291495, 7, 'Ronamit01', 'Bill Murray at his cynical best, fun Christmas dark comedy.', null); # 291495 Scrooged 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311040, 6, 'Ronamit01', 'Too many villains, loses the charm of the earlier films.', null); # 311040 Spider-Man 3 2007
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312150, 6, 'Ronamit01', 'Lightweight fun kids action, creative concept.', null); # 312150 Spy Kids 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313478, 9, 'Ronamit01', 'The best Star Wars, dark and emotionally powerful.', null); # 313478 Star Wars: Episode V - The Empire Strikes Back 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313479, 8, 'Ronamit01', 'Great conclusion to the original trilogy, epic and satisfying.', null); # 313479 Star Wars: Episode VI - Return of the Jedi 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (319602, 8, 'Ronamit01', 'Classic superhero film, Christopher Reeve is iconic.', null); # 319602 Superman 1978
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (319613, 7, 'Ronamit01', 'Great sequel, the Phantom Zone villains make it exciting.', null); # 319613 Superman II 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (342512, 7, 'Ronamit01', 'Interesting anthology, some segments are genuinely scary.', null); # 342512 Twilight Zone: The Movie 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (174953, 8, 'Ronamit01', 'Stunning Miyazaki epic, gorgeous visuals and deep themes.', null); # 174953 Kaze no tani no Naushika 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30965, 5, 'Ronamit01', 'Too campy, Jim Carrey is fun but the film is a mess.', null); # 30965 Batman Forever 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30952, 3, 'Ronamit01', 'One of the worst superhero movies, embarrassingly bad.', null); # 30952 Batman & Robin 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30976, 7, 'Ronamit01', 'Excellent animated Batman, better than most live-action entries.', null); # 30976 Batman: Mask of the Phantasm 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (94741, 8, 'Ronamit01', 'Spielberg tension at its purest, riveting from start to finish.', null); # 94741 Duel 1971
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (270628, 7, 'Ronamit01', 'Emotional Richard Donner film about childhood trauma, Tom Hanks narrates.', null); # 270628 Radio Flyer 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (336445, 7, 'Ronamit01', 'Intense and raw, DiCaprio gives a brave early performance.', null); # 336445 Total Eclipse 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215880, 7, 'Ronamit01', 'More polished and action-packed than the earlier entries.', null); # 215880 Mission: Impossible III 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (20253, 7, 'Ronamit01', 'Quirky surreal drama, Depp at his most unpredictable.', null); # 20253 Arizona Dream 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30961, 7, 'Ronamit01', 'Great animated continuation of Batman Beyond, dark and fun.', null); # 30961 Batman Beyond: Return of the Joker 2000
