#Personal movie reccomendations
#GitHub : galsasson4
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (644, 10, 'galsasson4', "The perfect teen movie funny and heart worming, prefect cast", null);  # 644 10 Things I Hate About You 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46878, 10, 'galsasson4', "The funniest movie, Bridgit the main chareter is relateable", null );  # 46878 Bridget Jones: The Edge of Reason 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (59578, 9, 'galsasson4', "Iconic movie, love the originality and the story line", null);  # 59578 Charlie and the Chocolate Factory 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (66194, 6, 'galsasson4', "Nice girl night's movie, the plot is not the most interesting but it is nostalgic", null);  # 66194 Clueless 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (129185, 10, 'galsasson4', "Historic movie, one of my favorites, you cannot stop watching it!", null);  # 129185 Gladiator 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (151616, 4, 'galsasson4', "I found the plot to be boring, good actors ", null);  # 151616 How to Lose a Guy in 10 Days 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159665, 10, 'galsasson4', "Tarentino at his best. World War II, so exciting you can't stop watching.", null);  # 159665 Inglorious Bastards 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (190869, 8, 'galsasson4',"Good animation,nice messege, original, Lilo and Stitch are loveable cherecters  ", null);  # 190869 Lilo & Stitch 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (220805, 7, 'galsasson4',"Spy movie but also funny and easy to watch");  # 220805 Mr. and Mrs. Smith 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (263360, 10, 'galsasson4', "Richard Gere and Julia Roberts are the perfect cast! Feel good movie that make you fall in love with the charecters");  # 263360 Pretty Woman 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (264157, 6, 'galsasson4', "Girls night movie, not as good as the first one", null);  # 264157 Princess Diaries 2: Royal Engagement, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (267038, 9, 'galsasson4', "Icoinic movie, Uma Thorman and Jhon Travolta in a thrilling Tartentino movie", null);  # 267038 Pulp Fiction 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300229, 10, 'galsasson4', "The best animated movie. Sherk gives an amazing moral of the story, a funny complex plot. always makes you feel good", null);  # 300229 Shrek 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300230, 10, 'galsasson4',"Even better than the first one! somehow the story is thrilling and the charecters are so loveable", null);  # 300230 Shrek 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300233, 10, 'galsasson4', "The same Shrek but in 4D. It is fun to feel like the charecters are in real life", null);  # 300233 Shrek 4-D 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311037, 7, 'galsasson4', "Fun superhero movie, not the most complex but still nice", null);  # 311037 Spider-Man 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311038, 6, 'galsasson4', "Continue with Spiderman and Jane, fun superhero movie", null);  # 311038 Spider-Man 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311040, 6, 'galsasson4', "3 movie of the Spiderman seires, fun superhero", null);  # 311040 Spider-Man 3 2007
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311604, 6, 'galsasson4', "Funny. Nice kids movie, SpongBob is an iconic charecter", null);  # 311604 SpongeBob SquarePants: Legend of the Lost Spatula 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311606, 5, 'galsasson4', "SpongBob is an iconic charecter but the movie is not exiciting", null);  # 311606 SpongeBob SquarePants: Revenge of the Flying Dutchman 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312150, 8, 'galsasson4',"Exiciting spy kids movie,was very unique fot it's timg ", null);  # 312150 Spy Kids 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (333856, 9, 'galsasson4', "Iconic movie, touching drama with Leonardo DiCaprio", null);  # 333856 Titanic 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335835, 10, 'galsasson4', "Tom Cruise with a thrilling army movie, amazing stunts", null);  # 335835 Top Gun 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (397121, 9, 'galsasson4', "One of the best science fiction created before the millenume. Strong concept", null);  # 397121 Matrix 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (263, 6, 'galsasson4', "Not impressive love comedy", null);  # 263 'Til There Was You 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (8183, 7, 'galsasson4', "Sophisticated drama with scams and intrigs of the high society", null);  # 8183 Age of Innocence, The 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30955, 7 , 'galsasson4', "The story of Batman with Jack Niclson as the Joker", null);  # 30955 Batman 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30952, 4, 'galsasson4', "The story of Batman and Robin staring Gorge Cloony, forgetable", null);  # 30952 Batman & Robin 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30959, 4, 'galsasson4', "Not the best version of the story of Batman", null);  # 30959 Batman Begins 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (372233, 7, 'galsasson4', "James Bond with Sean Connery at his best, mystery, romance and action", null);  # 372233 You Only Live Twice 1967
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (359297, 6, 'galsasson4', "Good science fiction starring Tom Cruise", null);  # 359297 War of the Worlds 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (354178, 7 , 'galsasson4', "Usual James Bond action, this time with Grace Jones", null);  # 354178 View to a Kill, A 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (350424, 7, 'galsasson4', "Good cast, action sci-fi movie", null);  # 350424 Vanilla Sky 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (340652, 6 , 'galsasson4',"Historic action with Brad Pitt", null);  # 340652 Troy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (337166, 8 , 'galsasson4', "Woody and Buzz Light year, going on a mission. Heart warming kids movie", null);  # 337166 Toy Story 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335336, 8, 'galsasson4', "James Bond with Pierce Brosnan as James trying to save the world from atom bomb", null);  # 335336 Tomorrow Never Dies 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (332065, 7, 'galsasson4', "Oscar winning James Bond, one of thr first Bonds with Sean Connert", null);  # 332065 Thunderball 1965
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (328272, 7, 'galsasson4',"Thrilling Steaven Spielberg film, comedy romance with Tom Hanks", null);  # 328272 Terminal, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (319602, 8, 'galsasson4', "Iconic superhero movie the first one thrilling and action based", null);  # 319602 Superman 1978
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (319613, 9, 'galsasson4', "Superman gives up his power for true love.", null);  # 319613 Superman II 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313478, 9, 'galsasson4',"Star Wars films, from the original trilogy, acton sci-fi", null);  # 313478 Star Wars: Episode V - The Empire Strikes Back 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313479, 9 , 'galsasson4', "Star Wars films, Luke learns to become a Jedi, acton sci-fi, ", null);  # 313479 Star Wars: Episode VI - Return of the Jedi 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313474, 6, 'galsasson4',"The first Star Wars in chronological order", null);  # 313474 Star Wars: Episode I - The Phantom Menace 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313476, 6, 'galsasson4', "From the Star Wars saga, Lea ans Luke's mother falls in love with Darth Vader", null);  # 313476 Star Wars: Episode II - Attack of the Clones 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313477, 6, 'galsasson4', "From the Star Wars saga, the story behind Darth Vader", null);  # 313477 Star Wars: Episode III - Revenge of the Sith 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312170, 7 , 'galsasson4', "James Bond against the KGB, with Roger Moore, saving the world", null);  # 312170 Spy Who Loved Me, The 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (304862, 7, 'galsasson4',"Horror ghost movie with Jonny Depp, felt slow and dark", null);  # 304862 Sleepy Hollow 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (290070, 8, 'galsasson4', "Holocost movie, the story of Oscar Schindler who saves jews during world war II, inspiring", null);  # 290070 Schindler's List 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (289109, 9, 'galsasson4', "Inspiring war movie with fantastic cast", null);  # 289109 Saving Private Ryan 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (283410, 5, 'galsasson4', "Nice love story with the iconic couple Julia Roberts and Richard Gere", null);  # 283410 Runaway Bride 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280270, 8, 'galsasson4', "The amazing story of a boxer Rocky to fame, thrilling, action, iconic soundtrack", null);  # 280270 Rocky 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280281, 7, 'galsasson4', "The rematch of Rocky and Apollo, thriling boxing movie", null);  # 280281 Rocky II 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280282, 7, 'galsasson4',"Rocky fights a new strong boxer", null);  # 280282 Rocky III 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280284,5, 'galsasson4', "Rocky fights a new russia boxer, amazing cast", null);  # 280284 Rocky IV 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280305, 5, 'galsasson4', "Rocky becomes a coach to a young boxer", null);  # 280305 Rocky V 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280306, 4, 'galsasson4', "Rocky continues to be a coach to a young boxer, exciting movie", null);  # 280306 Rocky VI 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256631, 7, 'galsasson4', "continueing with the advanture Pirates movie starring Jhonnny Depp. Thrilling movie about captain Jack Sparrow", null);  # 256631 Pirates of the Caribbean 2 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256632, 8, 'galsasson4',"Advanture Pirates movie starring Jhonnny Depp thrilling and exciting", null);  # 256632 Pirates of the Caribbean: The Curse of the Black Pearl 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (251234, 7, 'galsasson4', "Thrilling Mel Gibson action movie", null);  # 251234 Payback 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (240521, 8, 'galsasson4', "James Bond saga, spy action movie with Gorge Lazenby", null);  # 240521 On Her Majesty's Secret Service 1969
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238072, 8, 'galsasson4', "Crime movie with an outstanding cast,thrilling and breathtaking", null);  # 238072 Ocean's Eleven 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238073, 6, 'galsasson4',"Continuing the crime movie with an outstanding cast,the ocean gang tries to still from a cazino. thrilling and breath taking", null);  # 238073 Ocean's Twelve 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (230963, 7, 'galsasson4', "Musical and a romantic saxophonist and a singer starring Liza Minaly", null);  # 230963 New York, New York 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (230947, 6, 'galsasson4', "Comedy about three stories in New York by Woody Allen", null);  # 230947 New York Stories 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (220276, 8, 'galsasson4', "Musical on the behinde the scene of the cabaret, with Nicole Kidman", null);  # 220276 Moulin Rouge! 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218808, 6, 'galsasson4',"James Bond saga, saves the world from theft of space shuttle, not my favorite Bond", null);  # 218808 Moonraker 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215876, 9 , 'galsasson4', "Action about secret agent team with Tom Cruise, thrilling", null);  # 215876 Mission: Impossible 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215879, 7,'galsasson4',"The mission team is out to save US from a genetic disease", null);  # 215879 Mission: Impossible II 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215880, 9, 'galsasson4', "Action about secret agent team, the mission team goes to save students from terror ", null);  # 215880 Mission: Impossible III 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (214755, 9, 'galsasson4',"Action Sci-Fi movie with Top Cruise about the risks of a future world with no crime, Steven Spilberg", null);  # 214755 Minority Report 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210739, 8, 'galsasson4', "Special unit against alains. Sci-Fi and action film. Great cast", null);  # 210739 Men in Black 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210511, 9, 'galsasson4',"Sophisticated crime movie", null);  # 210511 Memento 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (203649, 6, 'galsasson4',"James Bond saves the worls from sensitive solar cell technology", null);  # 203649 Man with the Golden Gun, The 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (200864, 5, 'galsasson4', "Romantic comedy with Jennifer Lopez, not the most interesting", null);  # 200864 Maid in Manhattan 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (200521, 8, 'galsasson4', "Drama on friendship between two cancer servivors", null);  # 200521 Magnolia 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194497, 9, 'galsasson4', "Fantastic story of the hobbits part 1, adventures", null);  # 194497 Lord of the Rings: The Fellowship of the Ring, The 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194502, 9, 'galsasson4',"Fantastic story of the hobbits part 2.The hobbits continue the journy to distroy rhe rings", null);  # 194502 Lord of the Rings: The Two Towers, The 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194500, 9, 'galsasson4', "The magnificent end of the journy to distroy the rings, Fantasy ", null);  # 194500 Lord of the Rings: The Return of the King, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (192514, 6,'galsasson4', "James Bond is looking for traitors in the agancy", null);  # 192514 Live and Let Die 1973
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (189403, 7, 'galsasson4', "James Bond spy movie, he's fighting drug lords", null);  # 189403 Licence to Kill 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188507, 8, 'galsasson4', "Action about two police detectives with Mel Gibson and Danny Glober", null);  # 188507 Lethal Weapon 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188509, 8, 'galsasson4', "Action about two police detectives with Mel Gibson and Danny Glober. The two police officers need to protect a witness", null);  # 188509 Lethal Weapon 2 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188510, 6, 'galsasson4', "Action about two police detectives with Mel Gibson and Danny Glober. The two police officers fight police corruption", null);  # 188510 Lethal Weapon 3 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188511,7, 'galsasson4', "Action about two police detectives with Mel Gibson and Danny Glober. The two officers fight the chinees triads", null);  # 188511 Lethal Weapon 4 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185628, 9 , 'galsasson4', "Action movie about a military officer who joins the Japanese traditional fighting group", null);  # 185628 Last Samurai, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (183873, 5, 'galsasson4', "Dark fantasy with Michelle Pfiffer", null);  # 183873 Ladyhawke 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176711, 9, 'galsasson4',"Action, gangster stories with Uma Thurman Tarantino part 1", null);  # 176711 Kill Bill: Vol. 1 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176712, 9, 'galsasson4',"Action, gangster stories with Uma Thurman Tarantino part 2", null);  # 176712 Kill Bill: Vol. 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (170721, 9, 'galsasson4', "A family story about a kid who was raised in a jungle", null);  # 170721 Jungle Book 2, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (164572, 9, 'galsasson4', "Tarantino movie about a flight attendent who does scams", null);  # 164572 Jackie Brown 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (165961, 6, 'galsasson4',"Horror movie about sharks who attacks swimmers", null);  # 165961 Jaws 1975
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (160524, 6, 'galsasson4',"Thriller movie about a detective that investigates a murder", null);  # 160524 Insomnia 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159175, 8, 'galsasson4', "Adventure movie about an archiologist looking for ancient stone", null);  # 159175 Indiana Jones and the Temple of Doom 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159172, 7, 'galsasson4', "Adventure about Indiana Jones looking for the holy grail", null);  # 159172 Indiana Jones and the Last Crusade 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (158999, 6, 'galsasson4', "Aliens arrive to destroy the worls. Action", null);  # 158999 Independence Day 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (149287, 7, 'galsasson4', "Fantasy about Captain Hook and Peter Pan with Robin Williams", null);  # 149287 Hook 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139650, 10, 'galsasson4', "Fantasy about a child wizard that fights agaist evil. Harry's adventures at hogworts", null);  # 139650 Harry Potter and the Chamber of Secrets 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139652,10, 'galsasson4', "Fantasy about a child wizard that fights agaist evil.Harry participates in a dangerous competition", null);  # 139652 Harry Potter and the Goblet of Fire 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139653, 10, 'galsasson4', "Fantasy about a child wizard that fights agaist evil.Harry finds a book that belongs to the half blood prince", null);  # 139653 Harry Potter and the Half-Blood Prince 2008
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139654, 10, 'galsasson4', "Fantasy about a child wizard that fights agaist evil.The return of lord Voldemort", null);  # 139654 Harry Potter and the Order of the Phoenix 2007
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139655, 10, 'galsasson4', "Fantasy about a child wizard that fights agaist evil.Harry finds his family", null);  # 139655 Harry Potter and the Prisoner of Azkaban 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139657, 10 , 'galsasson4',"Fantasy about a child wizard that fights agaist evil. Great fanasy story", null);  # 139657 Harry Potter and the Sorcerer's Stone 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130945, 8, 'galsasson4', "James Bond, with Pierce Brosnan saving the world from Russian wepon", null);  # 130945 GoldenEye 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130953, 7, 'galsasson4', "James Bond with Sean Connery. James is saving the world from an evil enemy named Gold Finger", null);  # 130953 Goldfinger 1964
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131885, 8, 'galsasson4', "Adventure, family movie about kids who discover pirate's tresure", null);  # 131885 Goonies, The 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (123849, 8, 'galsasson4',"Great hictorical crime movie with great cast", null);  # 123849 Gangs of New York 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120574, 7, 'galsasson4', "James Bond. Bond gets involved with russian crime", null);  # 120574 From Russia with Love 1963
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (118980, 7, 'galsasson4',"Love story between two strangers in New York great cast", null);  # 118980 Frankie and Johnny 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (117314, 7, 'galsasson4', "James Bond with Roger Moore. Bonds prevents world war", null);  # 117314 For Your Eyes Only 1981
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (114955, 6, 'galsasson4', "Teen comedy on a young teenager who starts working at a beach club", null);  # 114955 Flamingo Kid, The 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (113506, 8, 'galsasson4', "Drama about the author of Peter Pan. Great cast", null);  # 113506 Finding Neverland 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (112290, 10, 'galsasson4',"A great iconic movie. Action, crime movie about a young guy who joins an undergroung fight club. Pyschological thriller ", null);  # 112290 Fight Club 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (109421, 7, 'galsasson4',"Action movie about car racing", null);  # 109421 Fast and the Furious, The 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (105587,5, 'galsasson4', "Spanish short love story", null);  # 105587 Examen 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (100130, 8, 'galsasson4', "Epic drama about a young boy surviving war times", null);  # 100130 Empire of the Sun 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (96593, 9,'galsasson4', "Family Sci Fi movie about an alien who's lost on earth.", null);  # 96593 E.T. the Extra-Terrestrial 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (92573, 8, 'galsasson4', "James Bond with Sean Connery. James saves the US space program", null);  # 92573 Dr. No 1962
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (85871, 7, 'galsasson4', "James Bond. James is fighting diamonds smugglers", null);  # 85871 Diamonds Are Forever 1971
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (86263, 7, 'galsasson4', "Bond fights NK terrorists", null);  # 86263 Die Another Day 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (69812, 8, 'galsasson4', "Thriller starring Julia Roberts and Mel Gibson", null);  # 69812 Conspiracy Theory 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (62460, 9, 'galsasson4', "Franch love story", null);  # 62460 Chocolat 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (276217, 9, 'galsasson4', 'Thriller action movie, highly sophisticated Quentin Tarantino', null);  # 276217 Reservoir Dogs 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56871, 8, 'galsasson4', "Crime comedy with Leonardo DiCaprio", null);  # 56871 Catch Me If You Can 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56304, 9, 'galsasson4', "Gangster movie, great cast", null);  # 56304 Casino 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56282, 6, 'galsasson4', "Teen romantic comedy", null);  # 56282 Cashback 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (54209, 8 , 'galsasson4', "Great horror movie", null);  # 54209 Cape Fear 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46169, 9, 'galsasson4', "Historic drama movie", null);  # 46169 Braveheart 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (40199, 10 , 'galsasson4', "Breaking through Sci-Fi movie", null);  # 40199 Blade Runner 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (39551, 7, 'galsasson4', "War action movie", null);  # 39551 Black Hawk Down 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (34077, 7, 'galsasson4', "Movie about a man that ages backwards with Brad Pitt", null);  # 34077 Benjamin Button 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (32180, 7 , 'galsasson4', "Family movie, nostaligc", null);  # 32180 Beauty and the Beast 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (32707, 6, 'galsasson4', "Biogrphical drama with Jonny Depp", null);  # 32707 Before Night Falls 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30967, 8, 'galsasson4', "The best atmospheric Batman movie, Michelle Pfeiffer as Catwoman is legendary", null); # 30967 Batman Returns 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10830, 10, 'galsasson4', "A masterpiece of suspense and sci-fi horror. The practical effects still hold up today", null); # 10830 Alien 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10920, 10, 'galsasson4', "Rare case where the sequel is as good as the original, perfect shift to action-sci-fi", null); # 10920 Aliens 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (326155, 10, 'galsasson4', "De Niro's performance is chilling and the grit of 70s NYC is perfectly captured", null); # 326155 Taxi Driver 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (297838, 10, 'galsasson4', "The ultimate story of hope and friendship, perfectly paced and emotionally resonant", null); # 297838 Shawshank Redemption, The 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (291698, 9, 'galsasson4', "Dark, gritty, and the ending is one of the most shocking in cinema history", null); # 291698 Se7en 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131780, 10, 'galsasson4', "Scorsese's best mob movie, the narration and soundtrack are flawless", null); # 131780 Goodfellas 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (270971, 9, 'galsasson4', "A brutal look at a boxer's life, the black and white cinematography is stunning", null); # 270971 Raging Bull 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (271105, 10, 'galsasson4', "The absolute standard for adventure movies, Spielberg and Ford at their peak", null); # 271105 Raiders of the Lost Ark 1981
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (65811, 8, 'galsasson4', "A beautiful and curious exploration of first contact with aliens", null); # 65811 Close Encounters of the Third Kind 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (306032, 9, 'galsasson4', "Guy Ritchie's best work, fast-paced dialogue and hilarious British underworld characters", null); # 306032 Snatch. 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (209158, 8, 'galsasson4', "Early Scorsese brilliance, showing the guilt and struggle of life in Little Italy", null); # 209158 Mean Streets 1973
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (381392, 7, 'galsasson4', "A fresh, futuristic take on Batman that actually worked for fans of the original", null); # 381392 Batman Beyond 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30976, 9, 'galsasson4', "Arguably the best written Batman story outside of the comics, very emotional", null); # 30976 Batman: Mask of the Phantasm 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (14132, 6, 'galsasson4', "Not as fresh as the first one but has some classic funny moments with the gang", null); # 14132 American Pie 2 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (21213, 8, 'galsasson4', "A heartbreaking fairy tale about the search for love and belonging in a robotic age", null); # 21213 Artificial Intelligence: AI 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (25192, 8, 'galsasson4', "DiCaprio is fantastic as Howard Hughes, great look at old Hollywood ambition", null); # 25192 Aviator, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30686, 7, 'galsasson4', "A rough and realistic portrayal of addiction and lost dreams", null); # 30686 Basketball Diaries, The 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (14477, 7, 'galsasson4', "Strong historical drama about the legal fight for freedom, very powerful courtroom scenes", null); # 14477 Amistad 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10702, 8, 'galsasson4', "A touching road movie about a woman finding her own identity and path", null); # 10702 Alice Doesn't Live Here Anymore 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (7842, 9, 'galsasson4', "An underrated Scorsese dark comedy, captures the feeling of a nightmare that won't end", null); # 7842 After Hours 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30965, 5, 'galsasson4', "A bit too colorful and campy compared to the Burton films, Jim Carrey is too much", null); # 30965 Batman Forever 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (47130, 8, 'galsasson4', "Nic Cage at his best, a frantic and spiritual journey through NYC nights", null); # 47130 Bringing Out the Dead 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (41518, 7, 'galsasson4', "Interesting biopic about the drug trade, though it feels a bit repetitive in the middle", null); # 41518 Blow 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (67388, 8, 'galsasson4', "Paul Newman returns to his iconic role with style, great chemistry with Tom Cruise", null); # 67388 Color of Money, The 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (67395, 10, 'galsasson4', "A beautiful, painful, and ultimately triumphant story of family and survival", null); # 67395 Color Purple, The 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (74259, 7, 'galsasson4', "Johnny Depp is great in this weird and funny tribute to 50s teen rebel movies", null); # 74259 Cry-Baby 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (97360, 9, 'galsasson4', "A hilarious and loving tribute to the 'worst' director of all time, Johnny Depp shines", null); # 97360 Ed Wood 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (97727, 10, 'galsasson4', "A gothic masterpiece about being an outsider, Tim Burton's most personal film", null); # 97727 Edward Scissorhands 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120506, 7, 'galsasson4', "A visually striking graphic novel adaptation, though the plot gets a bit messy", null); # 120506 From Hell 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (123435, 9, 'galsasson4', "One of the best psychological thrillers, keeps you guessing until the very last frame", null); # 123435 Game, The 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159167, 4, 'galsasson4', "A major disappointment in the franchise, the aliens plot felt out of place", "Title in DB says 2006, but it released in 2008"); # 159167 Indiana Jones 4 2008
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (174953, 9, 'galsasson4', "Stunning animation and a powerful ecological message, Miyazaki at his early best", null); # 174953 Kaze no tani no Naushika 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (177369, 9, 'galsasson4', "De Niro's obsession is terrifying and relatable, a great satire on fame", null); # 177369 King of Comedy, The 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185704, 8, 'galsasson4', "A controversial but deeply spiritual and human look at a religious figure", null); # 185704 Last Temptation of Christ, The 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (192702, 7, 'galsasson4', "Timothy Dalton brought a welcome grit and seriousness to the role of Bond", null); # 192702 Living Daylights, The 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (208245, 8, 'galsasson4', "A fun, fast-talking Western comedy that doesn't take itself too seriously", null); # 208245 Maverick 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218219, 10, 'galsasson4', "Epic, beautiful, and violent. A monumental achievement in animation history", null); # 218219 Mononoke-hime 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (233058, 6, 'galsasson4', "An interesting mystery with a good atmosphere, but the ending feels abrupt", null); # 233058 Ninth Gate, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (240327, 9, 'galsasson4', "Genuinely scary horror with a great score and a building sense of dread", null); # 240327 Omen, The 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (247579, 8, 'galsasson4', "Fincher's tight direction makes this a masterclass in tension within a small space", null); # 247579 Panic Room 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (253010, 9, 'galsasson4', "A beautiful, tragic story about an unlikely bond between a kidnapper and a boy", null); # 253010 Perfect World, A 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256627, 8, 'galsasson4', "Surprisingly good TV movie about the birth of the personal computer age", null); # 256627 Pirates of Silicon Valley 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256839, 8, 'galsasson4', "Vin Diesel is great as Riddick, a very creative and tense sci-fi horror movie", null); # 256839 Pitch Black 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (258948, 6, 'galsasson4', "A typical 90s thriller that is entertaining but lacks depth", null); # 258948 Poison Ivy 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (259826, 9, 'galsasson4', "Classic ghost story that manages to be both fun and genuinely frightening", null); # 259826 Poltergeist 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (291495, 8, 'galsasson4', "Bill Murray is hilarious in this cynical modern take on A Christmas Carol", null); # 291495 Scrooged 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (292671, 7, 'galsasson4', "Depp carries this thriller which has a nice atmosphere even if the twist is common", null); # 292671 Secret Window 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311428, 7, 'galsasson4', "A charming 80s comedy with a young Tom Hanks, very nostalgic", null); # 311428 Splash 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (318388, 8, 'galsasson4', "Spielberg's first theatrical film shows all his talent for chases and tension", null); # 318388 Sugarland Express, The 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (330670, 8, 'galsasson4', "Strong performances by DiCaprio and De Niro in a realistic look at a troubled childhood", null); # 330670 This Boy's Life 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (336445, 7, 'galsasson4', "A poetic and tragic look at the relationship between Rimbaud and Verlaine", null); # 336445 Total Eclipse 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (342512, 6, 'galsasson4', "Anthology movies are hit and miss, but the segment with the airplane monster is classic", null); # 342512 Twilight Zone: The Movie 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (368418, 7, 'galsasson4', "Brosnan is a great Bond, and Sophie Marceau is one of the best Bond villains", null); # 368418 World Is Not Enough, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (370017, 6, 'galsasson4', "Pure adrenaline and stunts, doesn't need much brain power but it's fun to watch", null); # 370017 XXX 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (372733, 8, 'galsasson4', "A very fun 'What if' story about Holmes meeting Watson as a teenager", null); # 372733 Young Sherlock Holmes 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (61751, 10, 'galsasson4', "One of the best sci-fi films of the 21st century, the long shots are incredible", null); # 61751 Children of Men, The 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (70959, 8, 'galsasson4', "Beautiful stop-motion animation with a lovely, slightly macabre romance", null); # 70959 Corpse Bride, The 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (142491, 8, 'galsasson4', "Del Toro brings his amazing creature design to a fun superhero story", null); # 142491 Hellboy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (142492, 9, 'galsasson4', "Even better than the first, the fantasy world design is absolutely breathtaking", null); # 142492 Hellboy 2 2008
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (34104, 8, 'galsasson4', "A quirky and heartwarming story about being different and finding love", null); # 34104 Benny & Joon 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46167, 7, 'galsasson4', "Johnny Depp's directorial debut is slow and bleak but has a powerful atmosphere", null); # 46167 Brave, The 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (379331, 8, 'galsasson4', "The definitive Sherlock for many, captures the Victorian fog and mystery perfectly", null); # 379331 Adventures of Sherlock Holmes, The 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (849, 5, 'galsasson4', "A direct-to-video sequel that misses the charm of the original animated classic", null); # 849 101 Dalmatians II: Patch's London Adventure 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (1038, 8, 'galsasson4', "A sweet and funny 'Big' style comedy, Jennifer Garner is perfectly cast", null); # 1038 13 Going On 30 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (1121, 7, 'galsasson4', "An epic look at Columbus's journey, the Vangelis soundtrack is the best part", null); # 1121 1492: Conquest of Paradise 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (1390, 6, 'galsasson4', "Spielberg's rare comedy miss; it's too loud and chaotic but has some great stunts", null); # 1390 1941 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (245699, 8, 'galsasson4', "Classic 80s comedy with great chemistry between Kurt Russell and Goldie Hawn", null); # 245699 Overboard 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (271344, 6, 'galsasson4', "Predictable but sweet family comedy about sudden motherhood", null); # 271344 Raising Helen 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312151, 7, 'galsasson4', "More of the same gadgets and fun, kids will love the island setting", null); # 312151 Spy Kids 2: Island of Lost Dreams 2002
