insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (235541, 10, 'Alma', 'The painful romance and final scenes stayed with me because the relationship felt intense and sincere.', NULL); # 235541 Notebook, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (263555, 10, 'Alma', 'Elizabeth and Darcy''s slow tension makes even the smallest conversation feel romantic and important.', NULL); # 263555 Pride and Prejudice 1940
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (294217, 10, 'Alma', 'Watching the sisters handle love and disappointment made the heartbreak feel believable instead of exaggerated.', NULL); # 294217 Sense and Sensibility 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (192413, 8, 'Alma', 'Jo''s stubbornness and the sisters'' bond made the family scenes feel personal and easy to care about.', NULL); # 192413 Little Women 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (362808, 8, 'Alma', 'The friendship slowly turning into love felt natural, and the awkward conversations made the chemistry believable.', NULL); # 362808 When Harry Met Sally... 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (235790, 10, 'Alma', 'The awkwardness between the movie star and the regular guy made the romance charming and easy to enjoy.', NULL); # 235790 Notting Hill 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (118393, 8, 'Alma', 'The wedding chaos was funny, but the almost missed romance gave the story its emotional pull.', NULL); # 118393 Four Weddings and a Funeral 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46877, 8, 'Alma', 'The messy dating mistakes felt funny and relatable, especially because the main character was not perfect.', NULL); # 46877 Bridget Jones's Diary 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (195300, 10, 'Alma', 'Different love stories kept the mood light, but a few moments still had real emotion.', NULL); # 195300 Love Actually 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (297115, 8, 'Alma', 'The relationship felt more interesting because the romance kept becoming more complicated as the characters tried to protect it.', NULL); # 297115 Shakespeare in Love 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (220276, 8, 'Alma', 'The songs made the tragic romance hit harder, especially once the love story turned painful.', NULL); # 220276 Moulin Rouge! 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (62460, 8, 'Alma', 'Vianne changing the small town made the romance feel personal and easy to care about.', NULL); # 62460 Chocolat 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (32712, 10, 'Alma', 'I liked how the relationship grew through small conversations instead of dramatic moments or instant romance.', NULL); # 32712 Before Sunrise 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (32713, 10, 'Alma', 'Watching them reconnect made the emotional tension feel stronger without needing dramatic scenes.', NULL); # 32713 Before Sunset 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280803, 10, 'Alma', 'The princess romance was charming, but the bittersweet ending is what made it memorable.', NULL); # 280803 Roman Holiday 1953
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46321, 8, 'Alma', 'The glamorous life looked fun at first, but the sadness underneath gave the story more depth.', NULL); # 46321 Breakfast at Tiffany's 1961
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (105069, 8, 'Alma', 'Danielle felt brave and active, so the fairy tale romance never felt passive or too perfect.', NULL); # 105069 Ever After 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (264146, 8, 'Alma', 'The jokes and adventure were fun, but the loyal love story made it lovable.', NULL); # 264146 Princess Bride, The 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (33940, 8, 'Alma', 'Jess''s family pressure made her football dream more meaningful, and the crush added a fun spark.', NULL); # 33940 Bend It Like Beckham 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (362042, 8, 'Alma', 'The young heroine carried the story with strength, and the family conflict made the emotional scenes work.', NULL); # 362042 Whale Rider 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120148, 8, 'Alma', 'The women''s friendship felt lasting, and the memories gave the story real emotional weight.', NULL); # 120148 Fried Green Tomatoes 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (329833, 8, 'Alma', 'The bond between the two women made the road story powerful, even when the plot became darker.', NULL); # 329833 Thelma & Louise 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (52204, 8, 'Alma', 'Watching the women support each other made the humor feel warmer and more meaningful.', NULL); # 52204 Calendar Girls 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (328301, 8, 'Alma', 'Mother and daughter scenes felt honest, and the painful moments made the drama strong.', NULL); # 328301 Terms of Endearment 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (180705, 8, 'Alma', 'Both parents felt human in the divorce story, which made the family conflict believable.', NULL); # 180705 Kramer vs. Kramer 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (309039, 8, 'Alma', 'The emotional weight of her past made the entire story feel heavier and much more heartbreaking.', NULL); # 309039 Sophie's Choice 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (101418, 8, 'Alma', 'The wartime setting made the romance feel larger, with every private moment carrying sadness.', NULL); # 101418 English Patient, The 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (275390, 8, 'Alma', 'So much was left unsaid in the almost romance, and that regret stayed with me.', NULL); # 275390 Remains of the Day, The 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (281446, 8, 'Alma', 'Lucy''s trip changed her in a believable way, and the romance fit that growing confidence.', NULL); # 281446 Room with a View, A 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (93837, 8, 'Alma', 'Watching the friendship develop slowly made the bond feel more real by the end.', NULL); # 93837 Driving Miss Daisy 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (111928, 8, 'Alma', 'The daughters'' choices about love and tradition gave the musical its most emotional moments.', NULL); # 111928 Fiddler on the Roof 1971
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (309634, 8, 'Alma', 'Music, family scenes, and romance came together in a way that made this easy to revisit.', NULL); # 309634 Sound of Music, The 1965
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (206881, 8, 'Alma', 'Playful songs and family problems gave the fantasy a cheerful emotional center.', NULL); # 206881 Mary Poppins 1964
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (223867, 8, 'Alma', 'The musical scenes added energy, while the relationship drama kept me interested in what would happen next.', NULL); # 223867 My Fair Lady 1964
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (361688, 8, 'Alma', 'The soundtrack made the young love feel even more tragic once the conflict took over.', NULL); # 361688 West Side Story 1961
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (51576, 8, 'Alma', 'Sally Bowles gave the story a messy emotional center, especially during the stage scenes.', NULL); # 51576 Cabaret 1972
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (302696, 8, 'Alma', 'Dancing brought a lot of joy, while the romance added charm beyond the musical numbers.', NULL); # 302696 Singin' in the Rain 1952
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (17760, 8, 'Alma', 'The breakup story felt honest because the jokes never hid how complicated the relationship became.', NULL); # 17760 Annie Hall 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218848, 8, 'Alma', 'Loud family scenes were funny, and the couple''s chemistry made the romance feel alive.', NULL); # 218848 Moonstruck 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (169594, 8, 'Alma', 'Old sacrifices made the mother and daughter stories feel painful and personal.', NULL); # 169594 Joy Luck Club, The 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (67395, 8, 'Alma', 'Survival and friendship made the drama powerful, and the emotional payoff felt earned.', NULL); # 67395 Color Purple, The 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131240, 8, 'Alma', 'The difficult heroine was fascinating, and the huge romance kept the long drama from feeling empty.', NULL); # 131240 Gone with the Wind 1939
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (88936, 8, 'Alma', 'Beautiful music and the war setting made every separation in the love story hurt.', NULL); # 88936 Doctor Zhivago 1965
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56044, 10, 'Alma', 'The final sacrifice gave the romance real weight and made the choice unforgettable.', NULL); # 56044 Casablanca 1942
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (273585, 8, 'Alma', 'The haunted marriage made the mystery personal, especially with the new wife always feeling watched.', NULL); # 273585 Rebecca 1940
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (253542, 8, 'Alma', 'Anne''s quiet regret made the second chance romance feel mature and very satisfying.', NULL); # 253542 Persuasion (1995/I) 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (18828, 8, 'Alma', 'I liked how the relationship grew quietly, because it felt more honest than a typical romantic story.', NULL); # 18828 Apartment, The 1960
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (11108, 8, 'Alma', 'Backstage rivalry and sharp dialogue made the ambitious characters fun to watch.', NULL); # 11108 All About Eve 1950
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (121829, 8, 'Alma', 'Fanny''s talent and humor made her easy to root for, even when the marriage became painful.', NULL); # 121829 Funny Girl 1968
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (248685, 8, 'Alma', 'Sung dialogue made the heartbreak feel constant, and the lost love was hard to shake.', NULL); # 248685 Parapluies de Cherbourg, Les 1964
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (236806, 8, 'Alma', 'I liked how the childhood memories and love for movies made the ending feel much more emotional.', NULL); # 236806 Nuovo cinema Paradiso 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (316881, 8, 'Alma', 'The dancing competition was fun, and the romance brought extra energy to the story.', NULL); # 316881 Strictly Ballroom 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (222831, 8, 'Alma', 'Muriel''s need to be loved made the comedy more emotional than expected.', NULL); # 222831 Muriel's Wedding 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (223758, 8, 'Alma', 'Choosing her own future made the heroine''s story stronger than a simple romance.', NULL); # 223758 My Brilliant Career 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (255009, 8, 'Alma', 'Piano scenes made the desire and jealousy intense, while the silence added pressure.', NULL); # 255009 Piano, The 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (100663, 8, 'Alma', 'Women escaping routine gave the story a refreshing feeling, and the friendships carried it.', NULL); # 100663 Enchanted April 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (292419, 8, 'Alma', 'Watching the children heal through the hidden garden gave the story its charm.', NULL); # 292419 Secret Garden, The 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (259777, 8, 'Alma', 'The optimism could feel simple, but it made the story hopeful and sincere.', NULL); # 259777 Pollyanna 1960
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (96829, 8, 'Alma', 'The brothers'' jealousy and need for approval gave the story a sad emotional pull.', NULL); # 96829 East of Eden 1955
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335799, 8, 'Alma', 'Identity comedy brought the laughs, and the romantic confusion kept the plot moving.', NULL); # 335799 Tootsie 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (289222, 8, 'Alma', 'Small gestures mattered more than big speeches, which made the teen romance feel sincere.', NULL); # 289222 Say Anything... 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46322, 8, 'Alma', 'Detention scenes became memorable when the students started opening up honestly.', NULL); # 46322 Breakfast Club, The 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (78093, 8, 'Alma', 'Dangerous flirting and cruelty made the romantic games tense to watch.', NULL); # 78093 Dangerous Liaisons 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (75914, 8, 'Alma', 'Hidden love behind clever words made the sadness feel personal and sharp.', NULL); # 75914 Cyrano de Bergerac 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (166264, 8, 'Alma', 'Village greed and family secrets made the drama tense in a slow but effective way.', NULL); # 166264 Jean de Florette 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (26156, 8, 'Alma', 'Babette''s dinner felt generous and meaningful, turning a small food story into something memorable.', NULL); # 26156 Babettes gstebud 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (334678, 8, 'Alma', 'Women rebuilding life after grief gave the drama an emotional strength that felt genuine.', NULL); # 334678 Todo sobre mi madre 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (136987, 8, 'Alma', 'The emotional dependence between the characters felt strange, but it kept me curious about where the story was going.', NULL); # 136987 Hable con ella 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (1759, 8, 'Alma', 'Memories of lost love gave the story a sad mood that fit the romance well.', NULL); # 1759 2046 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (99287, 8, 'Alma', 'Duty clashing with desire made the historical drama more interesting than just costumes and politics.', NULL); # 99287 Elizabeth 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (78015, 8, 'Alma', 'Her independence made the romance feel risky, especially in such a judgmental society.', NULL); # 78015 Dangerous Beauty 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (128515, 8, 'Alma', 'Silent glances around the painting created tension, and the attraction felt delicate.', NULL); # 128515 Girl with a Pearl Earring 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (113489, 8, 'Alma', 'The writing mentor bond felt sincere, and the trust between them grew naturally.', NULL); # 113489 Finding Forrester 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238161, 8, 'Alma', 'Watching him keep chasing his goal despite family pressure made the success feel more emotional.', NULL); # 238161 October Sky 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (63832, 8, 'Alma', 'Found family moments made the hard choices more emotional and gave the story heart.', NULL); # 63832 Cider House Rules, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (37995, 8, 'Alma', 'I liked how Billy kept following what he loved even when his family struggled to support him.', NULL); # 37995 Billy Elliot 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (5009, 8, 'Alma', 'That unlikely friendship felt earned, and the small moments between the characters worked best.', NULL); # 5009 About a Boy 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (157499, 8, 'Alma', 'Immigrant family grief felt real, and the hopeful moments stopped the story from becoming too heavy.', NULL); # 157499 In America 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (23873, 8, 'Alma', 'I connected with the uncertainty between the characters because it felt similar to real friendships at that age.', NULL); # 23873 Auberge espagnole, L' 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (220171, 8, 'Alma', 'The road trip mattered because the travel changed the characters instead of just showing places.', NULL); # 220171 Motorcycle Diaries, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (32726, 8, 'Alma', 'Connected stories carried a lot of grief, and the painful choices made the drama intense.', NULL); # 32726 Before the Rain 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313989, 8, 'Alma', 'Small town friendship felt natural, and the story avoided fake drama in a nice way.', NULL); # 313989 Station Agent, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (255442, 8, 'Alma', 'Family dinner stress felt real, and the awkwardness made the emotional moments better.', NULL); # 255442 Pieces of April 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (273423, 8, 'Alma', 'A daughter pushing against expectations made the story relatable and gave it energy.', NULL); # 273423 Real Women Have Curves 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218341, 8, 'Alma', 'Wedding chaos was fun, but the family secrets gave the celebration more emotional weight.', NULL); # 218341 Monsoon Wedding 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (18436, 8, 'Alma', 'Trauma and family truth made the story painful, while growing trust kept it moving.', NULL); # 18436 Antwone Fisher 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (275453, 8, 'Alma', 'Watching the players slowly trust each other made the emotional parts stronger than the sports scenes.', NULL); # 275453 Remember the Titans 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (283006, 8, 'Alma', 'The underdog effort made the familiar sports story satisfying by the end.', NULL); # 283006 Rudy 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (112008, 8, 'Alma', 'The family emotions surprised me because I expected a sports story and ended up caring more about the relationships.', NULL); # 112008 Field of Dreams 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (291825, 8, 'Alma', 'The horse racing story became emotional because the broken people also needed healing.', NULL); # 291825 Seabiscuit 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (113506, 10, 'Alma', 'Grief was handled with imagination, and the affection between the characters made the story moving.', NULL); # 113506 Finding Neverland 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (253920, 8, 'Alma', 'Childhood magic was charming, and the nostalgia made the fantasy feel lighter.', NULL); # 253920 Peter Pan 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (117874, 7, 'Alma', 'Watching Forrest stay loyal to the people he cared about made the emotional parts much stronger.', NULL); # 117874 Forrest Gump 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (134077, 7, 'Alma', 'A dark prison setting became emotionally strong because of the unexpected kindness inside it.', NULL); # 134077 Green Mile, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (297838, 7, 'Alma', 'Friendship inside prison gave the story hope and made the hard parts easier to watch.', NULL); # 297838 Shawshank Redemption, The 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (190129, 7, 'Alma', 'A father protecting his son made the tragedy painful, especially when humor turned into survival.', NULL); # 190129 Life Is Beautiful 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (32114, 7, 'Alma', 'Marriage support felt honest, and the vulnerable acting made the story more than a simple biography.', NULL); # 32114 Beautiful Mind, A 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131665, 7, 'Alma', 'Will''s defenses slowly breaking down made the therapy scenes powerful, and the friendships felt real.', NULL); # 131665 Good Will Hunting 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (80583, 7, 'Alma', 'Classroom scenes stayed memorable because the teacher pushed the students to feel brave.', NULL); # 80583 Dead Poets Society 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (37057, 7, 'Alma', 'His father''s stories became emotional by showing love in a strange, creative way.', NULL); # 37057 Big Fish 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (271192, 7, 'Alma', 'Brothers bonding during the trip made the awkward moments more touching.', NULL); # 271192 Rain Man 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (254645, 7, 'Alma', 'The courtroom fight was serious, and the love around the main character gave it dignity.', NULL); # 254645 Philadelphia 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (102514, 7, 'Alma', 'Erin''s confidence and anger made the justice story satisfying, especially when people underestimated her.', NULL); # 102514 Erin Brockovich 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (154040, 7, 'Alma', 'Father daughter love made the sad scenes harder, and the performances felt very committed.', NULL); # 154040 I Am Sam 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (25417, 7, 'Alma', 'Fragile hope made the medical miracle story moving without ever feeling easy.', NULL); # 25417 Awakenings 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (113504, 7, 'Alma', 'Family love stayed clear through the colorful rescue adventure, which made it enjoyable.', NULL); # 113504 Finding Nemo 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (337166, 7, 'Alma', 'Jealousy and friendship between the toys made the story funny while still giving it emotion.', NULL); # 337166 Toy Story 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218415, 7, 'Alma', 'Boo made the monster world feel caring, and her bond with Sulley was the best part.', NULL); # 218415 Monsters, Inc. 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300229, 7, 'Alma', 'Fairy tale jokes were funny, and the odd romance gave the story more heart than expected.', NULL); # 300229 Shrek 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300230, 7, 'Alma', 'Family dinner jokes were strong, and the romance problems kept the sequel entertaining.', NULL); # 300230 Shrek 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139657, 7, 'Alma', 'School magic was fun, but the friendships made the story comforting.', NULL); # 139657 Harry Potter and the Sorcerer's Stone 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139650, 7, 'Alma', 'A creepy school mystery stayed enjoyable because the friendships were loyal.', NULL); # 139650 Harry Potter and the Chamber of Secrets 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139655, 7, 'Alma', 'Family secrets and time travel gave this one more emotion than just magic lessons.', NULL); # 139655 Harry Potter and the Prisoner of Azkaban 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (13789, 7, 'Alma', 'Suburban marriage falling apart was uncomfortable, but the dark humor kept it interesting.', NULL); # 13789 American Beauty 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194874, 7, 'Alma', 'Two strangers bonding in the hotel made the story intimate and quietly sad.', NULL); # 194874 Lost in Translation 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (104338, 7, 'Alma', 'That strange memory idea worked because the breakup pain underneath felt real.', NULL); # 104338 Eternal Sunshine of the Spotless Mind 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (124110, 7, 'Alma', 'Awkward romance after grief gave the story a soft emotional center.', NULL); # 124110 Garden State 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (5037, 7, 'Alma', 'Schmidt''s disappointment felt honest, and the sadness made the story more interesting.', NULL); # 5037 About Schmidt 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300945, 7, 'Alma', 'The wine trip was funny because the friendship was messy and the romance kept failing.', NULL); # 300945 Sideways 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (282696, 7, 'Alma', 'A strange damaged family became easier to watch because of the dry humor.', NULL); # 282696 Royal Tenenbaums, The 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120080, 7, 'Alma', 'Art, anger, and a messy love life made the biography colorful and emotionally interesting.', NULL); # 120080 Frida 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (150790, 7, 'Alma', 'Three women''s sadness connected through the book, which made the drama stronger.', NULL); # 150790 Hours, The 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (66947, 7, 'Alma', 'Separated lovers made the war story personal, especially when survival kept pulling them apart.', NULL); # 66947 Cold Mountain 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (241799, 7, 'Alma', 'A mother''s illness brought out old resentment, making the family drama hurt more.', NULL); # 241799 One True Thing 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (119358, 7, 'Alma', 'The body swap was silly, but the mother daughter understanding gave it heart.', NULL); # 119358 Freaky Friday 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (128583, 7, 'Alma', 'Young women struggling in the hospital made the drama intense and uncomfortable.', NULL); # 128583 Girl, Interrupted 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (217741, 7, 'Alma', 'A rough crime story became easier to care about through the protective relationship.', NULL); # 217741 Mona Lisa 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (309657, 7, 'Alma', 'A poor family holding together through hardship made the drama simple but powerful.', NULL); # 309657 Sounder 1972
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (214984, 7, 'Alma', 'Teacher and student breakthrough scenes felt emotional because the progress was hard earned.', NULL); # 214984 Miracle Worker, The 1962
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (303564, 7, 'Alma', 'A creepy ghost mystery became more emotional because of the sad child at the center.', NULL); # 303564 Sixth Sense, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210511, 7, 'Alma', 'The memory puzzle stayed interesting because grief gave every clue meaning.', NULL); # 210511 Memento 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (301540, 7, 'Alma', 'Clarice''s bravery made the disturbing case easier to watch, and her focus kept the tension sharp.', NULL); # 301540 Silence of the Lambs, The 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (291698, 7, 'Alma', 'Strong twists kept me invested, but the miserable mood made the story hard to enjoy.', NULL); # 291698 Se7en 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (182955, 7, 'Alma', 'Hollywood crime and complicated people kept the tension stylish and alive.', NULL); # 182955 L.A. Confidential 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (224842, 7, 'Alma', 'A murder case rooted in childhood trauma and old guilt hit harder than a normal thriller.', NULL); # 224842 Mystic River 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (263740, 7, 'Alma', 'Courtroom surprises worked well, and the creepy defendant kept the story tense.', NULL); # 263740 Primal Fear 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (348944, 7, 'Alma', 'A clever con story became more memorable once the ending reframed the mystery.', NULL); # 348944 Usual Suspects, The 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (121386, 7, 'Alma', 'The wrong man chase was tense, and proving his innocence kept the action interesting.', NULL); # 121386 Fugitive, The 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (222727, 7, 'Alma', 'A train full of suspects made the murder puzzle fun and full of doubt.', NULL); # 222727 Murder on the Orient Express 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (366974, 7, 'Alma', 'Forbidden attraction made the crime danger stronger by making every choice harder.', NULL); # 366974 Witness 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (334212, 7, 'Alma', 'The children''s view made the justice story clearer and the unfairness harder to ignore.', NULL); # 334212 To Kill a Mockingbird 1962
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (352639, 7, 'Alma', 'Watching affection slowly become something darker made the tension much more unsettling.', NULL); # 352639 Vertigo 1958
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (273543, 7, 'Alma', 'Neighbor spying became tense in a fun way once every small clue started to matter.', NULL); # 273543 Rear Window 1954
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (235062, 7, 'Alma', 'Stylish chase scenes and flirty jokes kept the suspense from feeling too heavy.', NULL); # 235062 North by Northwest 1959
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (59411, 7, 'Alma', 'Paris mystery stayed fun because romance and danger kept switching places.', NULL); # 59411 Charade 1963
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (235676, 7, 'Alma', 'Spy danger landed better because love and trust were tangled together the whole time.', NULL); # 235676 Notorious 1946
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (85669, 7, 'Alma', 'A personal betrayal made the murder plan feel much more tense.', NULL); # 85669 Dial M for Murder 1954
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (54208, 7, 'Alma', 'The villain''s threat was effective, but the cruelty made the story unpleasant to sit through.', NULL); # 54208 Cape Fear 1962
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215346, 7, 'Alma', 'A trapped writer setup was tense, though the cruelty made it hard to enjoy.', NULL); # 215346 Misery 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (283434, 7, 'Alma', 'The pressure of deciding someone elses future made the courtroom scenes more tense than I expected.', NULL); # 283434 Runaway Jury 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (87423, 7, 'Alma', 'Immigrant danger made the crime thriller feel grounded and more disturbing.', NULL); # 87423 Dirty Pretty Things 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (193917, 7, 'Alma', 'Gangster power games were sharp, but the cold mood kept it from being enjoyable.', NULL); # 193917 Long Good Friday, The 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215869, 7, 'Alma', 'Missionary guilt and sacrifice gave the drama weight, even when the story felt heavy.', NULL); # 215869 Mission, The 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (266574, 7, 'Alma', 'Classic suspense worked well, but the horror parts pushed it away from enjoyment.', NULL); # 266574 Psycho 1960
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194497, 6, 'Alma', 'Friendship and loyalty helped, but the fantasy fighting took up too much space.', NULL); # 194497 Lord of the Rings: The Fellowship of the Ring, The 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194502, 6, 'Alma', 'A few good bonds helped the sequel, though the battle scenes started to feel long.', NULL); # 194502 Lord of the Rings: The Two Towers, The 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194500, 6, 'Alma', 'Emotional farewells worked, but the endless war scenes made the ending tiring.', NULL); # 194500 Lord of the Rings: The Return of the King, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (165961, 6, 'Alma', 'Shark suspense was effective, but it felt more stressful than fun to watch.', NULL); # 165961 Jaws 1975
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (129185, 6, 'Alma', 'Revenge and grief added drama, but the gladiator fights dominated too much.', NULL); # 129185 Gladiator 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (340652, 6, 'Alma', 'A messy love triangle interested me more than the battle scenes.', NULL); # 340652 Troy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (45128, 6, 'Alma', 'Amnesia gave the story a good hook, but the constant chases took over.', NULL); # 45128 Bourne Identity, The 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176712, 6, 'Alma', 'Revenge backstory added some depth, but the violence still dominated the experience.', NULL); # 176712 Kill Bill: Vol. 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (306283, 6, 'Alma', 'Fairy tale charm was pleasant, though the story felt too simple to be exciting.', NULL); # 306283 Snow White and the Seven Dwarfs 1937
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (367073, 6, 'Alma', 'Songs and the homecoming feeling made the story nostalgic and easy to enjoy.', NULL); # 367073 Wizard of Oz, The 1939
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (307913, 6, 'Alma', 'Fast comedy and romantic chaos kept this entertaining without feeling too heavy.', NULL); # 307913 Some Like It Hot 1959
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (254654, 6, 'Alma', 'The tension between the exes made the second chance romance feel playful and much more interesting.', NULL); # 254654 Philadelphia Story, The 1940
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (255274, 6, 'Alma', 'Intriguing mystery helped, but the distant mood made it harder to connect with.', NULL); # 255274 Picnic at Hanging Rock 1975
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (14942, 6, 'Alma', 'Connected lives were powerful, but the harshness made the story difficult to enjoy fully.', NULL); # 14942 Amores perros 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (207992, 1, 'Alma', 'Computer chosen one plot felt cold, with too little emotion to make it appealing.', NULL); # 207992 Matrix, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313459, 1, 'Alma', 'Space adventure had energy, but the battles took over almost everything.', NULL); # 313459 Star Wars 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313478, 1, 'Alma', 'Space war drowned out the small romance and made the story less appealing.', NULL); # 313478 Star Wars: Episode V - The Empire Strikes Back 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313479, 1, 'Alma', 'Creatures and battles became tiring without enough emotion to balance them.', NULL); # 313479 Star Wars: Episode VI - Return of the Jedi 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313476, 1, 'Alma', 'I never connected with the characters because the action and visual effects took over almost every emotional moment.', NULL); # 313476 Star Wars: Episode II - Attack of the Clones 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311037, 2, 'Alma', 'Superhero duty took over, leaving the romance too small to matter much.', NULL); # 311037 Spider-Man 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30955, 2, 'Alma', 'Dark comic book mood did not pull me in, and the romance was barely there.', NULL); # 30955 Batman 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (369458, 2, 'Alma', 'Mutant powers and fights left little room for anything emotionally interesting.', NULL); # 369458 X-Men 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (86274, 2, 'Alma', 'Hostage action and explosions created stress more than entertainment, with barely any emotional payoff.', NULL); # 86274 Die Hard 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (86287, 2, 'Alma', 'Buddy action barely had any heart, so the danger became tiring.', NULL); # 86287 Die Hard: With a Vengeance 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (310726, 2, 'Alma', 'Bus danger got annoying after a while, even with the fast pace.', NULL); # 310726 Speed 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (340799, 2, 'Alma', 'Spy chaos was loud, and the marriage jokes were not enough to save it.', NULL); # 340799 True Lies 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (107166, 2, 'Alma', 'Body swap idea was interesting, but the violence made the thriller too much.', NULL); # 107166 Face/Off 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10830, 1, 'Alma', 'Space monster horror was too stressful, and the fear was not enjoyable.', NULL); # 10830 Alien 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10920, 2, 'Alma', 'Military action plus creatures made the story too intense and not fun.', NULL); # 10920 Aliens 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (328285, 1, 'Alma', 'Killer robot chase had almost no softness, so the story felt cold.', NULL); # 328285 Terminator, The 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (328277, 2, 'Alma', 'Machines and fights overpowered the family bond that could have made it better.', NULL); # 328277 Terminator 2: Judgment Day 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (105891, 1, 'Alma', 'Possession horror was too disturbing, and the scary scenes were not enjoyable.', NULL); # 105891 Exorcist, The 1973
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (137655, 1, 'Alma', 'Slasher stalking gave the story tension, but not the kind that felt interesting.', NULL); # 137655 Halloween 1978
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (232458, 1, 'Alma', 'Nightmare murders and jump scares made this a hard pass.', NULL); # 232458 Nightmare On Elm Street, A 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (291221, 4, 'Alma', 'Self aware jokes helped a little, but it was still mainly a slasher.', NULL); # 291221 Scream 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (281937, 2, 'Alma', 'Pregnancy paranoia felt uncomfortable, and the horror tone made it hard to enjoy.', NULL); # 281937 Rosemary's Baby 1968
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120092, 4, 'Alma', 'That older comedy gave little romance or drama to care about, so it stayed low.', NULL); # 120092 Friday 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176711, 4, 'Alma', 'Revenge style looked cool at first, but the constant violence took over.', NULL); # 176711 Kill Bill: Vol. 1 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (39551, 2, 'Alma', 'Military combat felt exhausting, with very little space for emotion.', NULL); # 39551 Black Hawk Down 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (289109, 4, 'Alma', 'Powerful rescue story aside, the brutal battle scenes were hard to sit through.', NULL); # 289109 Saving Private Ryan 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (45257, 2, 'Alma', 'Important topic, but the documentary style did not feel enjoyable to watch.', NULL); # 45257 Bowling for Columbine 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (107353, 2, 'Alma', 'Political focus made this feel more like homework than an enjoyable watch.', NULL); # 107353 Fahrenheit 9/11 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (319462, 2, 'Alma', 'Memorable food experiment, but the gross moments made it unpleasant.', NULL); # 319462 Super Size Me 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (149353, 4, 'Alma', 'Basketball dreams were moving and personal, but the long documentary structure dragged.', NULL); # 149353 Hoop Dreams 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (48793, 4, 'Alma', 'Great music helped a lot, but the documentary format kept the story at a distance.', NULL); # 48793 Buena Vista Social Club 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (107351, 2, 'Alma', 'I understood why the story was important, but I never became attached to the characters or their journey.', NULL); # 107351 Fahrenheit 451 1966
