insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (96593, 8, 'EliLevey', 'Balances strong performances with memorable scenes that still hold up extremely well today.', null);  # 96593 E.T. the Extra-Terrestrial 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (303564, 9, 'EliLevey', 'The atmosphere, pacing, and performances make this movie easy to revisit repeatedly.', null);  # 303564 Sixth Sense, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (13978, 9, 'EliLevey', 'Feels influential and entertaining at the same time, which makes it stand out from similar films.', null);  # 13978 American History X 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (109093, 8, 'EliLevey', 'The combination of storytelling, direction, and memorable characters makes this highly recommendable.', null);  # 109093 Fargo 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (134672, 8, 'EliLevey', 'A very rewatchable movie because the tension and emotional moments both land effectively.', null);  # 134672 Groundhog Day 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46322, 8, 'EliLevey', 'Balances strong performances with memorable scenes that still hold up extremely well today.', null);  # 46322 Breakfast Club, The 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (111442, 8, 'EliLevey', 'The atmosphere, pacing, and performances make this movie easy to revisit repeatedly.', null);  # 111442 Ferris Bueller's Day Off 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (328285, 9, 'EliLevey', 'Feels influential and entertaining at the same time, which makes it stand out from similar films.', null);  # 328285 Terminator, The 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10920, 9, 'EliLevey', 'The combination of storytelling, direction, and memorable characters makes this highly recommendable.', null);  # 10920 Aliens 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (224842, 8, 'EliLevey', 'A very rewatchable movie because the tension and emotional moments both land effectively.', null);  # 224842 Mystic River 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (173933, 9, 'EliLevey', 'A strong recommendation thanks to its sharp pacing, standout performances, and clear rewatch value. (1984 pick)', null);  # 173933 Karate Kid, The 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (272644, 9, 'EliLevey', 'Ratatouille earns this score because it combines lasting cultural impact with scenes that still feel memorable.', null);  # 272644 Ratatouille 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (276085, 4, 'EliLevey', 'The movie is memorable enough to include, though it is weaker than most of the list.', null);  # 276085 Requiem for a Dream 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (235790, 7, 'EliLevey', 'The movie has mainstream appeal and enough personality to stand out from similar films. (1999 pick)', null);  # 235790 Notting Hill 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210739, 7, 'EliLevey', 'The movie has mainstream appeal and enough personality to stand out from similar films.', null);  # 210739 Men in Black 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (207992, 8, 'EliLevey', 'The Matrix earns this score because it combines lasting cultural impact with scenes that still feel memorable.', null);  # 207992 Matrix, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (363780, 2, 'EliLevey', 'The movie is memorable enough to include, though it is weaker than most of the list. (2004 pick)', null);  # 363780 White Chicks 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (26064, 7, 'EliLevey', 'A charming family movie with a simple story, likeable characters, and a surprisingly sincere emotional center.', null);  # 26064 Babe 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (97727, 8, 'EliLevey', 'It has a distinctive identity, strong momentum, and enough iconic moments to justify the high rating. (1990 pick)', null);  # 97727 Edward Scissorhands 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (158927, 9, 'EliLevey', 'The Incredibles is a classic crowd-pleaser with enough craft and energy to hold up well over time.', null);  # 158927 Incredibles, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (134077, 9, 'EliLevey', 'The Green Mile delivers exactly what people remember it for, while still feeling entertaining beyond nostalgia.', null);  # 134077 Green Mile, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (189403, 8, 'EliLevey', 'A strong recommendation thanks to its sharp pacing, standout performances, and clear rewatch value. (1989 pick)', null);  # 189403 Licence to Kill 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (368418, 6, 'EliLevey', 'The film has recognizable charm, good pacing, and enough standout scenes to recommend. (1999 pick)', null);  # 368418 World Is Not Enough, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (359297, 7, 'EliLevey', 'It is a fun, accessible movie with a few strong sequences that make it easy to watch. (2005 pick)', null);  # 359297 War of the Worlds 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (222339, 7, 'EliLevey', 'The movie has mainstream appeal and enough personality to stand out from similar films. (1999 pick)', null);  # 222339 Mummy, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46169, 8, 'EliLevey', 'The film has the kind of iconic moments and confident storytelling that make it easy to recommend. (1995 pick)', null);  # 46169 Braveheart 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (166917, 9, 'EliLevey', 'Jerry Maguire remains popular for a reason: it balances entertainment, style, and memorable character moments.', null);  # 166917 Jerry Maguire 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (123849, 8, 'EliLevey', 'Gangs of New York earns this score because it combines lasting cultural impact with scenes that still feel memorable.', null);  # 123849 Gangs of New York 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (66194, 8, 'EliLevey', 'This works because the story stays engaging while the performances give the whole film real weight. (1995 pick)', null);  # 66194 Clueless 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312151, 7, 'EliLevey', 'A worthwhile choice because the performances and premise carry it even when it is not flawless. (2002 pick)', null);  # 312151 Spy Kids 2: Island of Lost Dreams 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (151616, 8, 'EliLevey', 'It has a distinctive identity, strong momentum, and enough iconic moments to justify the high rating. (2003 pick)', null);  # 151616 How to Lose a Guy in 10 Days 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (328277, 9, 'EliLevey', 'It has a distinctive identity, strong momentum, and enough iconic moments to justify the high rating. (1991 pick)', null);  # 328277 Terminator 2: Judgment Day 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311037, 8, 'EliLevey', 'A popular and reliable choice because the characters, tone, and big moments all land well. (2002 pick)', null);  # 311037 Spider-Man 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (45129, 10, 'EliLevey', 'A popular and reliable choice because the characters, tone, and big moments all land well. (2004 pick)', null);  # 45129 Bourne Supremacy, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (104699, 8, 'EliLevey', 'The film has the kind of iconic moments and confident storytelling that make it easy to recommend. (2004 pick)', null);  # 104699 Eurotrip 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215880, 8, 'EliLevey', 'A popular and reliable choice because the characters, tone, and big moments all land well. (2006 pick)', null);  # 215880 Mission: Impossible III 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (336458, 9, 'EliLevey', 'Total Recall earns this score because it combines lasting cultural impact with scenes that still feel memorable.', null);  # 336458 Total Recall 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130121, 9, 'EliLevey', 'This works because the story stays engaging while the performances give the whole film real weight. (1992 pick)', null);  # 130121 Godfather 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (270971, 8, 'EliLevey', 'It has a distinctive identity, strong momentum, and enough iconic moments to justify the high rating. (1980 pick)', null);  # 270971 Raging Bull 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (297802, 8, 'EliLevey', 'It blends zombie horror with British comedy in a way that is funny, clever, and surprisingly heartfelt.', null);  # 297802 Shaun of the Dead 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (90772, 9, 'EliLevey', 'Donnie Darko earns this score because it combines lasting cultural impact with scenes that still feel memorable.', null);  # 90772 Donnie Darko 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (177328, 7, 'EliLevey', 'A worthwhile choice because the performances and premise carry it even when it is not flawless. (2005 pick)', null);  # 177328 King Kong 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (337814, 9, 'EliLevey', 'The mix of memorable scenes, strong lead performances, and polished direction makes this an easy pick. (2001 pick)', null);  # 337814 Training Day 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (375827, 8, 'EliLevey', 'This works because the story stays engaging while the performances give the whole film real weight. (2001 pick)', null);  # 375827 Zoolander 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (264146, 10, 'EliLevey', 'The film has the kind of iconic moments and confident storytelling that make it easy to recommend. (1987 pick)', null);  # 264146 Princess Bride, The 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (160524, 7, 'EliLevey', 'A worthwhile choice because the performances and premise carry it even when it is not flawless. (2002 pick)', null);  # 160524 Insomnia 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (112290, 10, 'EliLevey', 'A popular and reliable choice because the characters, tone, and big moments all land well. (1999 pick)', null);  # 112290 Fight Club 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (223799, 8, 'EliLevey', 'A strong recommendation thanks to its sharp pacing, standout performances, and clear rewatch value. (1992 pick)', null);  # 223799 My Cousin Vinny 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (80583, 9, 'EliLevey', 'Dead Poets Society earns this score because it combines lasting cultural impact with scenes that still feel memorable.', null);  # 80583 Dead Poets Society 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (55727, 8, 'EliLevey', 'The film has the kind of iconic moments and confident storytelling that make it easy to recommend. (2005 pick)', null);  # 55727 Cars 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300229, 7, 'EliLevey', 'Shrek is not the strongest film on the list, but it is memorable and still entertaining.', null);  # 300229 Shrek 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (37178, 7, 'EliLevey', 'A good recommendation for its mix of familiar storytelling, charisma, and replay value. (1998 pick)', null);  # 37178 Big Lebowski, The 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (2709, 8, 'EliLevey', 'A popular and reliable choice because the characters, tone, and big moments all land well. (2004 pick)', null);  # 2709 50 First Dates 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131665, 9, 'EliLevey', 'Good Will Hunting is a classic crowd-pleaser with enough craft and energy to hold up well over time.', null);  # 131665 Good Will Hunting 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335336, 8, 'EliLevey', 'A strong recommendation thanks to its sharp pacing, standout performances, and clear rewatch value. (1997 pick)', null);  # 335336 Tomorrow Never Dies 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (333856, 9, 'EliLevey', 'It has a distinctive identity, strong momentum, and enough iconic moments to justify the high rating. (1997 pick)', null);  # 333856 Titanic 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139657, 10, 'EliLevey', 'A popular and reliable choice because the characters, tone, and big moments all land well. (2001 pick)', null);  # 139657 Harry Potter and the Sorcerer's Stone 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (26847, 7, 'EliLevey', 'It has some rough edges, but the core idea and key scenes still make it enjoyable. (1990 pick)', null);  # 26847 Back to the Future Part III 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256632, 10, 'EliLevey', 'This works because the story stays engaging while the performances give the whole film real weight. (2003 pick)', null);  # 256632 Pirates of the Caribbean: The Curse of the Black Pearl 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (199255, 8, 'EliLevey', 'Madagascar remains popular for a reason: it balances entertainment, style, and memorable character moments.', null);  # 199255 Madagascar 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (14132, 8, 'EliLevey', 'This works because the story stays engaging while the performances give the whole film real weight.', null);  # 14132 American Pie 2 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (158999, 8, 'EliLevey', 'A strong recommendation thanks to its sharp pacing, standout performances, and clear rewatch value. (1996 pick)', null);  # 158999 Independence Day 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (301540, 10, 'EliLevey', 'This works because the story stays engaging while the performances give the whole film real weight. (1991 pick)', null);  # 301540 Silence of the Lambs, The 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (26844, 8, 'EliLevey', 'The film has the kind of iconic moments and confident storytelling that make it easy to recommend. (1985 pick)', null);  # 26844 Back to the Future 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (112205, 8, 'EliLevey', 'The Fifth Element remains popular for a reason: it balances entertainment, style, and memorable character moments.', null);  # 112205 Fifth Element, The 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (1529, 9, 'EliLevey', '2 Fast 2 Furious is a classic crowd-pleaser with enough craft and energy to hold up well over time.', null);  # 1529 2 Fast 2 Furious 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (9795, 8, 'EliLevey', 'The songs, humor, and Robin Williams performance make it one of Disney’s most entertaining animated films.', null);  # 9795 Aladdin 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (279841, 8, 'EliLevey', 'RoboCop is a classic crowd-pleaser with enough craft and energy to hold up well over time.', null);  # 279841 RoboCop 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312152, 6, 'EliLevey', 'The movie has mainstream appeal and enough personality to stand out from similar films. (2003 pick)', null);  # 312152 Spy Kids 3-D: Game Over 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (155213, 10, 'EliLevey', 'It has a distinctive identity, strong momentum, and enough iconic moments to justify the high rating. (2002 pick)', null);  # 155213 Ice Age 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (162380, 9, 'EliLevey', 'The mix of memorable scenes, strong lead performances, and polished direction makes this an easy pick. (2005 pick)', null);  # 162380 Iron Man 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238072, 10, 'EliLevey', 'A strong recommendation thanks to its sharp pacing, standout performances, and clear rewatch value. (2001 pick)', null);  # 238072 Ocean's Eleven 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (195300, 7, 'EliLevey', 'Love Actually is not the strongest film on the list, but it is memorable and still entertaining.', null);  # 195300 Love Actually 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (50639, 7, 'EliLevey', 'It has some rough edges, but the core idea and key scenes still make it enjoyable. (2004 pick)', null);  # 50639 Butterfly Effect, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (138797, 7, 'EliLevey', 'Happy Gilmore is enjoyable and well-made, with enough memorable moments to make it worth adding.', null);  # 138797 Happy Gilmore 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (155070, 8, 'EliLevey', 'The film has the kind of iconic moments and confident storytelling that make it easy to recommend. (2004 pick)', null);  # 155070 I, Robot 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (9125, 10, 'EliLevey', 'Airplane! delivers exactly what people remember it for, while still feeling entertaining beyond nostalgia.', null);  # 9125 Airplane! 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131885, 7, 'EliLevey', 'The Goonies works well because it understands its genre and gives the audience what they came for.', null);  # 131885 Goonies, The 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (289558, 9, 'EliLevey', 'The mix of memorable scenes, strong lead performances, and polished direction makes this an easy pick. (1983 pick)', null);  # 289558 Scarface 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (235541, 8, 'EliLevey', 'The Notebook remains popular for a reason: it balances entertainment, style, and memorable character moments.', null);  # 235541 Notebook, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (39551, 9, 'EliLevey', 'A popular and reliable choice because the characters, tone, and big moments all land well.', null);  # 39551 Black Hawk Down 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (299073, 8, 'EliLevey', 'It has a distinctive identity, strong momentum, and enough iconic moments to justify the high rating. (1980 pick)', null);  # 299073 Shining, The 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (79716, 7, 'EliLevey', 'The film has recognizable charm, good pacing, and enough standout scenes to recommend. (2004 pick)', null);  # 79716 Day After Tomorrow, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (289787, 9, 'EliLevey', 'The mix of memorable scenes, strong lead performances, and polished direction makes this an easy pick. (1992 pick)', null);  # 289787 Scent of a Woman 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (14145, 10, 'EliLevey', 'This works because the story stays engaging while the performances give the whole film real weight. (2000 pick)', null);  # 14145 American Psycho 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313476, 5, 'EliLevey', 'A known film with some fun moments, but it does not fully deliver compared with stronger picks.', null);  # 313476 Star Wars: Episode II - Attack of the Clones 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (267038, 10, 'EliLevey', 'The mix of memorable scenes, strong lead performances, and polished direction makes this an easy pick. (1994 pick)', null);  # 267038 Pulp Fiction 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (32114, 9, 'EliLevey', 'A Beautiful Mind is a classic crowd-pleaser with enough craft and energy to hold up well over time.', null);  # 32114 Beautiful Mind, A 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (291221, 6, 'EliLevey', 'It has some rough edges, but the core idea and key scenes still make it enjoyable.', null);  # 291221 Scream 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194502, 9, 'EliLevey', 'This works because the story stays engaging while the performances give the whole film real weight. (2002 pick)', null);  # 194502 Lord of the Rings: The Two Towers, The 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (191246, 10, 'EliLevey', 'The Lion King delivers exactly what people remember it for, while still feeling entertaining beyond nostalgia.', null);  # 191246 Lion King, The 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (275453, 10, 'EliLevey', 'The film has the kind of iconic moments and confident storytelling that make it easy to recommend. (2000 pick)', null);  # 275453 Remember the Titans 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (32178, 8, 'EliLevey', 'The music, animation, and central romance give it a classic Disney feeling that holds up well.', null);  # 32178 Beauty and the Beast 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (370017, 5, 'EliLevey', 'XXX has appeal in places, but the writing and pacing make the recommendation more limited.', null);  # 370017 XXX 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139654, 8, 'EliLevey', 'It has a distinctive identity, strong momentum, and enough iconic moments to justify the high rating. (2007 pick)', null);  # 139654 Harry Potter and the Order of the Phoenix 2007
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (290070, 9, 'EliLevey', 'Schindler''s List delivers exactly what people remember it for, while still feeling entertaining beyond nostalgia.', null);  # 290070 Schindler's List 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (37002, 7, 'EliLevey', 'A good recommendation for its mix of familiar storytelling, charisma, and replay value. (1999 pick)', null);  # 37002 Big Daddy 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (337166, 10, 'EliLevey', 'A popular and reliable choice because the characters, tone, and big moments all land well. (1995 pick)', null);  # 337166 Toy Story 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280284, 8, 'EliLevey', 'Rocky IV remains popular for a reason: it balances entertainment, style, and memorable character moments.', null);  # 280284 Rocky IV 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (117314, 8, 'EliLevey', 'It has a distinctive identity, strong momentum, and enough iconic moments to justify the high rating. (1981 pick)', null);  # 117314 For Your Eyes Only 1981
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (109421, 9, 'EliLevey', 'The Fast and the Furious delivers exactly what people remember it for, while still feeling entertaining beyond nostalgia.', null);  # 109421 Fast and the Furious, The 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238073, 6, 'EliLevey', 'The film has recognizable charm, good pacing, and enough standout scenes to recommend. (2004 pick)', null);  # 238073 Ocean's Twelve 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (86274, 9, 'EliLevey', 'It has a distinctive identity, strong momentum, and enough iconic moments to justify the high rating. (1988 pick)', null);  # 86274 Die Hard 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (340901, 9, 'EliLevey', 'The Truman Show earns this score because it combines lasting cultural impact with scenes that still feel memorable.', null);  # 340901 Truman Show, The 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (87280, 8, 'EliLevey', 'Dirty Dancing remains popular for a reason: it balances entertainment, style, and memorable character moments.', null);  # 87280 Dirty Dancing 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131780, 10, 'EliLevey', 'Goodfellas remains popular for a reason: it balances entertainment, style, and memorable character moments.', null);  # 131780 Goodfellas 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (121538, 10, 'EliLevey', 'A strong recommendation thanks to its sharp pacing, standout performances, and clear rewatch value. (1987 pick)', null);  # 121538 Full Metal Jacket 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159175, 8, 'EliLevey', 'The film has the kind of iconic moments and confident storytelling that make it easy to recommend. (1984 pick)', null);  # 159175 Indiana Jones and the Temple of Doom 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (163715, 9, 'EliLevey', 'The Italian Job delivers exactly what people remember it for, while still feeling entertaining beyond nostalgia.', null);  # 163715 Italian Job, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (16006, 9, 'EliLevey', 'This works because the story stays engaging while the performances give the whole film real weight. (2004 pick)', null);  # 16006 Anchorman: The Legend of Ron Burgundy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56304, 9, 'EliLevey', 'A strong recommendation thanks to its sharp pacing, standout performances, and clear rewatch value.', null);  # 56304 Casino 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313474, 5, 'EliLevey', 'It is worth including for popularity, even though the story and execution are uneven.', null);  # 313474 Star Wars: Episode I - The Phantom Menace 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (340652, 9, 'EliLevey', 'The film has the kind of iconic moments and confident storytelling that make it easy to recommend. (2004 pick)', null);  # 340652 Troy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (113504, 10, 'EliLevey', 'The mix of memorable scenes, strong lead performances, and polished direction makes this an easy pick. (2003 pick)', null);  # 113504 Finding Nemo 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139653, 8, 'EliLevey', 'The mix of memorable scenes, strong lead performances, and polished direction makes this an easy pick. (2008 pick)', null);  # 139653 Harry Potter and the Half-Blood Prince 2008
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (129185, 9, 'EliLevey', 'Gladiator remains popular for a reason: it balances entertainment, style, and memorable character moments.', null);  # 129185 Gladiator 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (66286, 10, 'EliLevey', 'A strong recommendation thanks to its sharp pacing, standout performances, and clear rewatch value. (2005 pick)', null);  # 66286 Coach Carter 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (348944, 9, 'EliLevey', 'A popular and reliable choice because the characters, tone, and big moments all land well. (1995 pick)', null);  # 348944 Usual Suspects, The 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194497, 9, 'EliLevey', 'The Lord of the Rings: The Fellowship of the Ring remains popular for a reason: it balances entertainment, style, and memorable character moments.', null);  # 194497 Lord of the Rings: The Fellowship of the Ring, The 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (248878, 5, 'EliLevey', 'It is worth including for popularity, even though the story and execution are uneven. (1998 pick)', null);  # 248878 Parent Trap, The 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (254986, 9, 'EliLevey', 'The Pianist remains popular for a reason: it balances entertainment, style, and memorable character moments.', null);  # 254986 Pianist, The 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194500, 10, 'EliLevey', 'The film has the kind of iconic moments and confident storytelling that make it easy to recommend. (2003 pick)', null);  # 194500 Lord of the Rings: The Return of the King, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (644, 7, 'EliLevey', 'A solid pick that may not be perfect, but still has strong entertainment value and clear appeal.', null);  # 644 10 Things I Hate About You 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313479, 8, 'EliLevey', 'Star Wars: Episode VI - Return of the Jedi is a classic crowd-pleaser with enough craft and energy to hold up well over time.', null);  # 313479 Star Wars: Episode VI - Return of the Jedi 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (119358, 7, 'EliLevey', 'A solid pick that may not be perfect, but still has strong entertainment value and clear appeal. (2003 pick)', null);  # 119358 Freaky Friday 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (40187, 9, 'EliLevey', 'A strong recommendation thanks to its sharp pacing, standout performances, and clear rewatch value. (1998 pick)', null);  # 40187 Blade 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (276217, 9, 'EliLevey', 'A popular and reliable choice because the characters, tone, and big moments all land well. (1992 pick)', null);  # 276217 Reservoir Dogs 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (302329, 8, 'EliLevey', 'The film has the kind of iconic moments and confident storytelling that make it easy to recommend. (2005 pick)', null);  # 302329 Sin City 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194123, 8, 'EliLevey', 'This works because the story stays engaging while the performances give the whole film real weight. (2005 pick)', null);  # 194123 Longest Yard, The 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256631, 10, 'EliLevey', 'The film has the kind of iconic moments and confident storytelling that make it easy to recommend. (2006 pick)', null);  # 256631 Pirates of the Caribbean 2 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (207157, 8, 'EliLevey', 'This works because the story stays engaging while the performances give the whole film real weight. (1994 pick)', null);  # 207157 Mask, The 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30955, 8, 'EliLevey', 'The gothic style, memorable villain, and darker superhero tone make it an important Batman film.', null);  # 30955 Batman 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (328272, 6, 'EliLevey', 'The Terminal is enjoyable and well-made, with enough memorable moments to make it worth adding.', null);  # 328272 Terminal, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (209133, 6, 'EliLevey', 'Mean Girls is enjoyable and well-made, with enough memorable moments to make it worth adding.', null);  # 209133 Mean Girls 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280305, 5, 'EliLevey', 'Rocky V has appeal in places, but the writing and pacing make the recommendation more limited.', null);  # 280305 Rocky V 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (271095, 9, 'EliLevey', 'Raiders of the Lost Ark delivers exactly what people remember it for, while still feeling entertaining beyond nostalgia.', null);  # 271095 Raiders of the Lost Ark 1981
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139652, 9, 'EliLevey', 'Harry Potter and the Goblet of Fire is a classic crowd-pleaser with enough craft and energy to hold up well over time.', null);  # 139652 Harry Potter and the Goblet of Fire 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30967, 9, 'EliLevey', 'It has a distinctive identity, strong momentum, and enough iconic moments to justify the high rating.', null);  # 30967 Batman Returns 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (34077, 8, 'EliLevey', 'Benjamin Button delivers exactly what people remember it for, while still feeling entertaining beyond nostalgia.', null);  # 34077 Benjamin Button 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (310726, 8, 'EliLevey', 'This works because the story stays engaging while the performances give the whole film real weight. (1994 pick)', null);  # 310726 Speed 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312150, 8, 'EliLevey', 'Spy Kids remains popular for a reason: it balances entertainment, style, and memorable character moments.', null);  # 312150 Spy Kids 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139650, 8, 'EliLevey', 'This works because the story stays engaging while the performances give the whole film real weight. (2002 pick)', null);  # 139650 Harry Potter and the Chamber of Secrets 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (209591, 7, 'EliLevey', 'Meet Joe Black is enjoyable and well-made, with enough memorable moments to make it worth adding.', null);  # 209591 Meet Joe Black 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (337168, 9, 'EliLevey', 'A strong recommendation thanks to its sharp pacing, standout performances, and clear rewatch value. (1999 pick)', null);  # 337168 Toy Story 2 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139655, 10, 'EliLevey', 'Harry Potter and the Prisoner of Azkaban delivers exactly what people remember it for, while still feeling entertaining beyond nostalgia.', null);  # 139655 Harry Potter and the Prisoner of Azkaban 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176711, 9, 'EliLevey', 'Kill Bill: Vol. 1 delivers exactly what people remember it for, while still feeling entertaining beyond nostalgia.', null);  # 176711 Kill Bill: Vol. 1 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280282, 7, 'EliLevey', 'A solid pick that may not be perfect, but still has strong entertainment value and clear appeal. (1982 pick)', null);  # 280282 Rocky III 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (297838, 10, 'EliLevey', 'The mix of memorable scenes, strong lead performances, and polished direction makes this an easy pick. (1994 pick)', null);  # 297838 Shawshank Redemption, The 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313478, 10, 'EliLevey', 'This works because the story stays engaging while the performances give the whole film real weight. (1980 pick)', null);  # 313478 Star Wars: Episode V - The Empire Strikes Back 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30965, 9, 'EliLevey', 'The mix of memorable scenes, strong lead performances, and polished direction makes this an easy pick.', null);  # 30965 Batman Forever 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (142491, 7, 'EliLevey', 'Hellboy is enjoyable and well-made, with enough memorable moments to make it worth adding.', null);  # 142491 Hellboy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (289666, 8, 'EliLevey', 'A strong recommendation thanks to its sharp pacing, standout performances, and clear rewatch value. (2000 pick)', null);  # 289666 Scary Movie 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (297761, 9, 'EliLevey', 'Se7en stays gripping because the mystery, performances, and dark atmosphere all work together extremely well.', null);  # 297761 Se7en 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (134979, 9, 'EliLevey', 'The Dark Knight combines strong action, memorable characters, and a standout villain performance.', null);  # 134979 Dark Knight, The 2008
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (178103, 8, 'EliLevey', 'Jurassic Park remains exciting because the adventure, effects, and suspense still hold up today.', null);  # 178103 Jurassic Park 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (113277, 9, 'EliLevey', 'Finding Neverland balances emotional storytelling with performances that make the film memorable.', null);  # 113277 Finding Neverland 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (257756, 8, 'EliLevey', 'The Prestige rewards repeat viewings thanks to its structure, performances, and clever twists.', null);  # 257756 Prestige, The 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (190590, 9, 'EliLevey', 'Leon: The Professional works because the action and emotional core support each other effectively.', null);  # 190590 Leon: The Professional 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215670, 8, 'EliLevey', 'Memento stands out for its unusual structure and the way it keeps the audience engaged.', null);  # 215670 Memento 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (330566, 9, 'EliLevey', 'The Departed delivers strong performances, tension, and sharp dialogue throughout.', null);  # 330566 The Departed 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10830, 9, 'EliLevey', 'Alien builds tension brilliantly with a simple setting, strong atmosphere, and memorable sci-fi horror.', null);  # 10830 Alien 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30959, 9, 'EliLevey', 'Batman Begins gives the character a grounded origin story with strong action and clear emotional stakes.', null);  # 30959 Batman Begins 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (40199, 9, 'EliLevey', 'Blade Runner stands out because of its visuals, atmosphere, and lasting influence on science fiction.', null);  # 40199 Blade Runner 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56871, 9, 'EliLevey', 'Catch Me If You Can is stylish, fast-paced, and carried by very strong lead performances.', null);  # 56871 Catch Me If You Can 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (59578, 7, 'EliLevey', 'Charlie and the Chocolate Factory is visually creative and entertaining, even if it is not perfect.', null);  # 59578 Charlie and the Chocolate Factory 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (92573, 8, 'EliLevey', 'Dr. No is important because it introduces the Bond style with charm, danger, and memorable spy elements.', null);  # 92573 Dr. No 1962
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130953, 9, 'EliLevey', 'Goldfinger is one of the strongest Bond films because of its villain, style, and iconic moments.', null);  # 130953 Goldfinger 1964
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159172, 9, 'EliLevey', 'Indiana Jones and the Last Crusade mixes adventure, humor, and family emotion extremely well.', null);  # 159172 Indiana Jones and the Last Crusade 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159665, 9, 'EliLevey', 'Inglorious Bastards works because of its tense dialogue, stylish scenes, and memorable characters.', null);  # 159665 Inglorious Bastards 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (165961, 9, 'EliLevey', 'Jaws stays effective because the suspense builds slowly and the threat feels memorable throughout.', null);  # 165961 Jaws 1975
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176712, 8, 'EliLevey', 'Kill Bill Vol. 2 adds more character depth while keeping the revenge story stylish and engaging.', null);  # 176712 Kill Bill Vol. 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185628, 8, 'EliLevey', 'The Last Samurai combines large-scale action with a personal story about loyalty and identity.', null);  # 185628 Last Samurai, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215876, 8, 'EliLevey', 'Mission Impossible is entertaining because of its espionage tension, twists, and memorable set pieces.', null);  # 215876 Mission Impossible 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215879, 6, 'EliLevey', 'Mission Impossible II has fun action and style, but it is weaker than the better franchise entries.', null);  # 215879 Mission Impossible II 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (220805, 7, 'EliLevey', 'Mr. and Mrs. Smith is enjoyable because of the chemistry between the leads and the action-comedy tone.', null);  # 220805 Mr. and Mrs. Smith 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (263360, 7, 'EliLevey', 'Pretty Woman remains memorable because of its charm, romance, and strong lead performances.', null);  # 263360 Pretty Woman 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280270, 9, 'EliLevey', 'Rocky is a classic underdog story with strong emotion, memorable training scenes, and real heart.', null);  # 280270 Rocky 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280281, 7, 'EliLevey', 'Rocky II continues the underdog story well and keeps the emotional connection from the first film.', null);  # 280281 Rocky II 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (289109, 10, 'EliLevey', 'Saving Private Ryan is powerful because of its realism, emotional weight, and unforgettable war scenes.', null);  # 289109 Saving Private Ryan 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300230, 8, 'EliLevey', 'Shrek 2 is funny, clever, and expands the original story without losing its charm.', null);  # 300230 Shrek 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311038, 9, 'EliLevey', 'Spider-Man 2 improves the superhero story with stronger emotion, action, and a great villain.', null);  # 311038 Spider-Man 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313477, 8, 'EliLevey', 'Star Wars Episode III has strong dramatic moments and gives the prequel story a memorable payoff.', null);  # 313477 Star Wars Episode III 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (326155, 9, 'EliLevey', 'Taxi Driver is intense and memorable because of its atmosphere, character study, and lead performance.', null);  # 326155 Taxi Driver 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335835, 9, 'EliLevey', 'Top Gun is entertaining because of its energy, aerial scenes, soundtrack, and confident style.', null);  # 335835 Top Gun 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (45128, 9, 'EliLevey', 'The Bourne Identity feels sharp and exciting because of its grounded action and spy mystery.', null);  # 45128 Bourne Identity, The 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (18960, 9, 'EliLevey', 'Apocalypse Now is unforgettable because of its atmosphere, scale, and powerful look at war.', null);  # 18960 Apocalypse Now 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (65764, 8, 'EliLevey', 'A Clockwork Orange is disturbing but memorable because of its bold style and unusual storytelling.', null);  # 65764 Clockwork Orange, A 1971
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (141544, 9, 'EliLevey', 'Heat is gripping because of its crime story, strong performances, and tense confrontations.', null);  # 141544 Heat 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (969, 10, 'EliLevey', '12 Angry Men is excellent because it creates constant tension through dialogue and character conflict.', null);  # 969 12 Angry Men 1957
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (2238, 8, 'EliLevey', '300 is visually memorable and entertaining because of its style, action, and simple heroic story.', null);  # 2238 300 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (148200, 9, 'EliLevey', 'Home Alone is still funny and rewatchable because of its simple idea and memorable comedy scenes.', null);  # 148200 Home Alone 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (369458, 8, 'EliLevey', 'X-Men works because it combines superhero action with characters who feel different and interesting.', null);  # 369458 X-Men 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218415, 9, 'EliLevey', 'Monsters Inc. is funny, creative, and emotional in a way that makes it easy to rewatch.', null);  # 218415 Monsters Inc 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (26846, 8, 'EliLevey', 'Back to the Future Part II keeps the time-travel idea fun, clever, and very entertaining.', null);  # 26846 Back to the Future Part II 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (362808, 8, 'EliLevey', 'When Harry Met Sally works because the dialogue, chemistry, and humor feel natural and memorable.', null);  # 362808 When Harry Met Sally 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (18979, 9, 'EliLevey', 'Apollo 13 is tense and inspiring because the survival story feels realistic and emotional.', null);  # 18979 Apollo 13 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120574, 8, 'EliLevey', 'From Russia with Love is a strong Bond film because it focuses on tension, espionage, and style.', null);  # 120574 From Russia with Love 1963
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (332065, 7, 'EliLevey', 'Thunderball has classic Bond style, memorable underwater action, and a strong adventure feeling.', null);  # 332065 Thunderball 1965
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (117874, 10, 'EliLevey', 'Forrest Gump is memorable because it mixes humor, emotion, history, and a very strong lead performance.', null);  # 117874 Forrest Gump 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (226939, 8, 'EliLevey', 'The Naked Gun is funny and memorable because of its absurd jokes and fast comic timing.', null);  # 226939 Naked Gun 1988
