
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (1390, 5, 'erangolani27', 'Not one of Spielberg''s stronger efforts, the plot feels disjointed', null); # 1390 1941 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (7842, 8, 'erangolani27', 'A tense and gritty urban descent into paranoia, hard to look away', null); # 7842 After Hours 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (14132, 4, 'erangolani27', 'Has its funny moments but falls well short of what the first film achieved', null); # 14132 American Pie 2 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (14477, 8, 'erangolani27', 'A powerful true story told with conviction and strong performances throughout', null); # 14477 Amistad 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30686, 8, 'erangolani27', 'A brutal and unflinching portrait of addiction, DiCaprio carries it brilliantly', null); # 30686 Basketball Diaries, The 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30955, 8, 'erangolani27', 'Tim Burton''s gothic vision of Gotham still holds up as one of the definitive Batman films', null); # 30955 Batman 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30967, 7, 'erangolani27', 'Darker and weirder than the first, still enjoyable if not quite as fresh', null); # 30967 Batman Returns 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (31715, 6, 'erangolani27', 'Emotionally heavy story about lifelong friendship that leaves a real mark', null); # 31715 Beaches 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (32707, 7, 'erangolani27', 'A tense and moving film about the cost of living authentically under oppression', null); # 32707 Before Night Falls 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (34104, 7, 'erangolani27', 'A warm and gentle film that treats mental illness with real care and charm', null); # 34104 Benny & Joon 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (39551, 8, 'erangolani27', 'Relentlessly intense combat sequences based on real events, exhausting in the best way', null); # 39551 Black Hawk Down 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (40199, 9, 'erangolani27', 'A landmark sci-fi film with a world so detailed and atmospheric it feels completely real', null); # 40199 Blade Runner 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (44238, 3, 'erangolani27', 'Messy and cheap horror that wastes its premise with weak writing and acting', null); # 44238 Bordello of Blood 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46167, 6, 'erangolani27', 'A bleak and sorrowful story that is difficult to shake once you have seen it', null); # 46167 Brave, The 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46169, 8, 'erangolani27', 'A sweeping historical epic with great battle scenes and a strong sense of place', null); # 46169 Braveheart 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46878, 5, 'erangolani27', 'Likeable enough but too predictable to rise above standard romantic comedy territory', null); # 46878 Bridget Jones: The Edge of Reason 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (47130, 7, 'erangolani27', 'A darkly compelling Scorsese film that puts you inside a truly exhausting night shift', null); # 47130 Bringing Out the Dead 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (53921, 4, 'erangolani27', 'A self-indulgent comedy about filmmaking that never really finds its footing', null); # 53921 Cannes Man 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (54209, 9, 'erangolani27', 'De Niro is genuinely terrifying and the slow-burn tension never lets up', null); # 54209 Cape Fear 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56304, 8, 'erangolani27', 'Scorsese pulls back the curtain on the casino world with style and sharp detail', null); # 56304 Casino 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56871, 8, 'erangolani27', 'DiCaprio and Hanks make a wonderful pairing in this slick and charming true story', null); # 56871 Catch Me If You Can 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (59578, 10, 'erangolani27', 'A wildly imaginative and nostalgic film that works on every level for all ages', null); # 59578 Charlie and the Chocolate Factory 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (61751, 8, 'erangolani27', 'A gripping dystopian thriller with real emotional stakes and stunning long takes', null); # 61751 Children of Men, The 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (62460, 5, 'erangolani27', 'Pleasant and well-acted but too slight to leave a lasting impression', null); # 62460 Chocolat 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (65811, 6, 'erangolani27', 'A classic of the genre that still conveys genuine wonder despite its age', null); # 65811 Close Encounters of the Third Kind 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (66194, 5, 'erangolani27', 'Breezy and fun at times but too shallow to stick with you', null); # 66194 Clueless 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (67395, 8, 'erangolani27', 'A deeply affecting drama anchored by outstanding performances from its entire cast', null); # 67395 Color Purple, The 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (69812, 7, 'erangolani27', 'An intriguing setup that unfortunately drifts into generic thriller territory by the end', null); # 69812 Conspiracy Theory 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (70959, 6, 'erangolani27', 'Beautifully animated with a distinctive look, though the story feels a bit thin', null); # 70959 Corpse Bride, The 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (74259, 3, 'erangolani27', 'Deliberately over the top but the jokes land rarely enough to justify the effort', null); # 74259 Cry-Baby 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (85871, 5, 'erangolani27', 'One of the more forgettable Bond entries, lacking any real tension or personality', null); # 85871 Diamonds Are Forever 1971
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (86263, 5, 'erangolani27', 'Over-produced and hollow, the CGI has aged terribly and the plot is embarrassing', null); # 86263 Die Another Day 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (92573, 6, 'erangolani27', 'Rough around the edges but you can feel the birth of an iconic franchise', null); # 92573 Dr. No 1962
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (96593, 9, 'erangolani27', 'A timeless and heartwarming story about connection that holds up for every generation', null); # 96593 E.T. the Extra-Terrestrial 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (97360, 8, 'erangolani27', 'Depp and Burton make incompetence utterly mesmerizing in this oddly touching biography', null); # 97360 Ed Wood 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (97727, 6, 'erangolani27', 'Depp is captivating but the film leans too hard into fairy-tale logic', null); # 97727 Edward Scissorhands 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (98681, 4, 'erangolani27', 'A weak follow-up that relies on tired gags and adds nothing new', null); # 98681 El Mariachi: 10 Years Later 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (109421, 6, 'erangolani27', 'Pure popcorn entertainment that does not pretend to be anything more', null); # 109421 Fast and the Furious, The 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (114955, 7, 'erangolani27', 'A quiet and observant coming-of-age story with a solid grasp of class dynamics', null); # 114955 Flamingo Kid, The 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (116556, 7, 'erangolani27', 'Impressively assured debut from Nolan, rough edges and all', null); # 116556 Following 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (117314, 6, 'erangolani27', 'A watchable but fairly routine Bond entry without much that distinguishes it', null); # 117314 For Your Eyes Only 1981
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (118367, 6, 'erangolani27', 'Uneven anthology with wildly different tones across its four segments', null); # 118367 Four Rooms 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (118980, 6, 'erangolani27', 'Well acted but the story never develops beyond its basic romantic premise', null); # 118980 Frankie and Johnny 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120506, 7, 'erangolani27', 'A moody and stylish take on the Jack the Ripper legend with a good cast', null); # 120506 From Hell 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (123435, 9, 'erangolani27', 'An incredibly clever thriller that keeps pulling the rug out from under you', null); # 123435 Game, The 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (123849, 8, 'erangolani27', 'A sweeping and atmospheric portrait of New York''s immigrant underworld', null); # 123849 Gangs of New York 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (25192, 7, 'erangolani27', 'A slick and well-crafted biopic about a fascinating and complex figure', null); # 25192 Aviator, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (129185, 9, 'erangolani27', 'A spectacular action epic with a strong emotional core and Crowe at his best', null); # 129185 Gladiator 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130945, 7, 'erangolani27', 'Pierce Brosnan''s best Bond outing, tense and reasonably grounded', null); # 130945 GoldenEye 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130953, 7, 'erangolani27', 'Connery at his most suave, a classic Cold War spy adventure', null); # 130953 Goldfinger 1964
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131780, 9, 'erangolani27', 'Scorsese''s definitive crime epic, electric from the opening scene to the last', null); # 131780 Goodfellas 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (142491, 6, 'erangolani27', 'A quirky superhero film that never quite decides what kind of movie it wants to be', null); # 142491 Hellboy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (149287, 6, 'erangolani27', 'An interesting reimagining of Peter Pan that works better in concept than execution', null); # 149287 Hook 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30959, 8, 'erangolani27', 'A grounded and intelligent reboot that takes the character seriously for the first time', null); # 30959 Batman Begins 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (151616, 7, 'erangolani27', 'Light and enjoyable, McConaughey''s charm does a lot of the heavy lifting', null); # 151616 How to Lose a Guy in 10 Days 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159172, 8, 'erangolani27', 'A satisfying and adventurous conclusion to the original Indiana Jones trilogy', null); # 159172 Indiana Jones and the Last Crusade 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (160375, 7, 'erangolani27', 'A grounded and quietly moving drama that treats its characters with real dignity', null); # 160375 Inside Moves 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (164572, 8, 'erangolani27', 'A tightly plotted Tarantino film with outstanding performances and sharp dialogue', null); # 164572 Jackie Brown 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (165961, 6, 'erangolani27', 'More effective as a thriller than a horror film, and still surprisingly tense today', null); # 165961 Jaws 1975
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176711, 8, 'erangolani27', 'A stylish and visceral revenge story packed with Tarantino''s signature wit', null); # 176711 Kill Bill: Vol. 1 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176712, 7, 'erangolani27', 'More contemplative than the first volume but loses some of the kinetic energy', null); # 176712 Kill Bill: Vol. 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (177369, 7, 'erangolani27', 'A chilling and uncomfortable portrait of celebrity obsession told with dark humor', null); # 177369 King of Comedy, The 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (178994, 7, 'erangolani27', 'A competent mob drama that benefits from a strong cast even if the plot is familiar', null); # 178994 Knockaround Guys 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (181766, 7, 'erangolani27', 'A meditative and visually stunning biography that rewards patient viewing', null); # 181766 Kundun 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (183873, 6, 'erangolani27', 'A visually inventive fantasy romance that is more style than substance', null); # 183873 Ladyhawke 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185628, 8, 'erangolani27', 'A respectful and engaging look at cultural collision with Tom Cruise giving his best dramatic work', null); # 185628 Last Samurai, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188507, 9, 'erangolani27', 'The chemistry between Gibson and Glover makes this one of the great buddy cop films', null); # 188507 Lethal Weapon 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188511, 6, 'erangolani27', 'The series is running on fumes by this point, though the leads remain likeable', null); # 188511 Lethal Weapon 4 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (192514, 7, 'erangolani27', 'An entertaining Bond romp even if the plot is more ridiculous than most', null); # 192514 Live and Let Die 1973
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194497, 10, 'erangolani27', 'A breathtaking adaptation that captures the full scope and magic of Tolkien''s world', null); # 194497 Lord of the Rings: The Fellowship of the Ring, The 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194500, 9, 'erangolani27', 'A triumphant and emotionally satisfying conclusion to one of cinema''s greatest trilogies', null); # 194500 Lord of the Rings: The Return of the King, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194502, 8, 'erangolani27', 'Helm''s Deep alone is worth the price of admission, even if the pacing is uneven', null); # 194502 Lord of the Rings: The Two Towers, The 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (200521, 8, 'erangolani27', 'A sprawling and operatic ensemble drama that somehow holds all its threads together', null); # 200521 Magnolia 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (200864, 5, 'erangolani27', 'Polished and watchable but entirely predictable from start to finish', null); # 200864 Maid in Manhattan 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (203649, 7, 'erangolani27', 'A fun Bond with a memorable villain concept even if the execution is uneven', null); # 203649 Man with the Golden Gun, The 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (208245, 8, 'erangolani27', 'A hugely entertaining Western comedy that does not take itself too seriously', null); # 208245 Maverick 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (209158, 7, 'erangolani27', 'An early Scorsese with raw energy and a strong sense of street-level authenticity', null); # 209158 Mean Streets 1973
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210511, 8, 'erangolani27', 'Nolan''s reverse-chronology puzzle is as clever as it is emotionally gripping', null); # 210511 Memento 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210739, 7, 'erangolani27', 'A fun and breezy sci-fi comedy that never outstays its welcome', null); # 210739 Men in Black 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (214755, 8, 'erangolani27', 'A polished and thought-provoking sci-fi thriller with great action to match its ideas', null); # 214755 Minority Report 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215876, 7, 'erangolani27', 'Slick and entertaining spy action with Cruise fully committed to the role', null); # 215876 Mission: Impossible 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215879, 6, 'erangolani27', 'Bigger and flashier but lacks the tightness and tension of the original', null); # 215879 Mission: Impossible II 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218219, 8, 'erangolani27', 'A rich and visually stunning Miyazaki epic with real environmental depth', null); # 218219 Mononoke-hime 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218808, 5, 'erangolani27', 'Absurdly over the top even by Bond standards, more parody than spy film', null); # 218808 Moonraker 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (220276, 6, 'erangolani27', 'Visually dazzling but emotionally exhausting, the excess starts to numb you', null); # 220276 Moulin Rouge! 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (220805, 7, 'erangolani27', 'The leads have real spark together and the action sequences are surprisingly good', null); # 220805 Mr. and Mrs. Smith 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (230947, 8, 'erangolani27', 'Three distinct stories from elite directors, uneven but consistently interesting', null); # 230947 New York Stories 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (230963, 7, 'erangolani27', 'A lavish musical drama with De Niro and Minnelli giving everything they have', null); # 230963 New York, New York 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (233058, 8, 'erangolani27', 'A brooding and unsettling occult thriller with a genuinely creepy atmosphere', null); # 233058 Ninth Gate, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (235615, 6, 'erangolani27', 'A decent drama about a father-son relationship, anchored by Hanks and Jackie Gleason', null); # 235615 Nothing in Common 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238073, 7, 'erangolani27', 'Still stylish and fun but the plot is unnecessarily convoluted compared to the first', null); # 238073 Ocean''s Twelve 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (240327, 7, 'erangolani27', 'A genuinely unsettling horror film that builds its dread methodically and effectively', null); # 240327 Omen, The 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (240521, 8, 'erangolani27', 'A bold and entertaining Bond with a different lead that deserves more credit than it gets', null); # 240521 On Her Majesty''s Secret Service 1969
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (244421, 5, 'erangolani27', 'Well-meaning but every story beat can be seen coming from miles away', null); # 244421 Other Sister, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (245699, 6, 'erangolani27', 'A lightweight but likeable comedy carried by the charm of its two leads', null); # 245699 Overboard 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (247579, 9, 'erangolani27', 'Fincher builds an almost unbearable level of claustrophobic tension throughout', null); # 247579 Panic Room 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (253010, 8, 'erangolani27', 'Eastwood at his most restrained and affecting, a quietly powerful road movie', null); # 253010 Perfect World, A 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256627, 7, 'erangolani27', 'A sharp and well-researched look at the early Silicon Valley rivalry', null); # 256627 Pirates of Silicon Valley 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256632, 9, 'erangolani27', 'A hugely entertaining swashbuckler with Depp creating one of cinema''s most beloved characters', null); # 256632 Pirates of the Caribbean: The Curse of the Black Pearl 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (257744, 7, 'erangolani27', 'A warm ensemble romance with an impressive cast and genuine emotional moments', null); # 257744 Playing by Heart 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (258948, 6, 'erangolani27', 'An intriguing psychological setup that tips into melodrama before the end', null); # 258948 Poison Ivy 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (259826, 7, 'erangolani27', 'A fun and creepy haunted house film with some genuinely effective scares', null); # 259826 Poltergeist 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (263360, 6, 'erangolani27', 'Hard to resist even if the fairy-tale romance is completely implausible', null); # 263360 Pretty Woman 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (264157, 5, 'erangolani27', 'Harmless fun but entirely forgettable, exists mainly as a showcase for Hathaway', null); # 264157 Princess Diaries 2: Royal Engagement, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (267038, 9, 'erangolani27', 'Tarantino''s masterwork, layered with dark humor and unforgettable dialogue', null); # 267038 Pulp Fiction 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (270971, 8, 'erangolani27', 'De Niro''s physical and emotional transformation is one of the great screen performances', null); # 270971 Raging Bull 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (271095, 8, 'erangolani27', 'A perfect adventure film that set the template for action cinema that followed', null); # 271095 Raiders of the Lost Ark 1981
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (271344, 6, 'erangolani27', 'Watchable but forgettable family comedy that plays it very safe throughout', null); # 271344 Raising Helen 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280270, 8, 'erangolani27', 'A genuinely inspiring underdog story that earned every one of its accolades', null); # 280270 Rocky 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280281, 7, 'erangolani27', 'A solid follow-up that recaptures some of the original''s heart and energy', null); # 280281 Rocky II 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280282, 6, 'erangolani27', 'The formula is starting to feel stretched and the villain is underdeveloped', null); # 280282 Rocky III 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280284, 7, 'erangolani27', 'The Cold War backdrop gives the film an unexpected layer of political interest', null); # 280284 Rocky IV 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (289109, 10, 'erangolani27', 'The most visceral and honest depiction of combat ever committed to film', null); # 289109 Saving Private Ryan 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (291698, 9, 'erangolani27', 'A masterfully constructed thriller with Spacey delivering a chilling and unforgettable performance', null); # 291698 Se7en 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (297838, 10, 'erangolani27', 'One of the greatest films ever made, with hope and resilience at its beating heart', null); # 297838 Shawshank Redemption, The 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300229, 9, 'erangolani27', 'A brilliantly funny and subversive fairy tale that works for children and adults equally', null); # 300229 Shrek 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300230, 8, 'erangolani27', 'A worthy sequel with more laughs, even if it cannot match the freshness of the original', null); # 300230 Shrek 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (304862, 8, 'erangolani27', 'Burton''s gothic atmosphere is perfectly matched to the Washington Irving source material', null); # 304862 Sleepy Hollow 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (306032, 9, 'erangolani27', 'Guy Ritchie''s snappy editing and overlapping plots make this endlessly rewatchable', null); # 306032 Snatch. 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311038, 7, 'erangolani27', 'A strong sequel with Doc Ock as a genuinely compelling villain', null); # 311038 Spider-Man 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311428, 7, 'erangolani27', 'A sweet and inventive romantic fantasy that still holds a lot of charm', null); # 311428 Splash 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312170, 7, 'erangolani27', 'A well-crafted Bond entry with a great underwater set-piece and solid pacing', null); # 312170 Spy Who Loved Me, The 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313160, 7, 'erangolani27', 'A thorough and absorbing portrait of one of cinema''s most enigmatic directors', null); # 313160 Stanley Kubrick: A Life in Pictures 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313474, 6, 'erangolani27', 'Visually impressive but dramatically flat, the prequel trilogy stumbles out of the gate', null); # 313474 Star Wars: Episode I - The Phantom Menace 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313476, 6, 'erangolani27', 'An improvement over Episode I but the romance storyline drags the film down', null); # 313476 Star Wars: Episode II - Attack of the Clones 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313477, 7, 'erangolani27', 'The strongest of the prequel trilogy, with Anakin''s fall finally feeling earned', null); # 313477 Star Wars: Episode III - Revenge of the Sith 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (326155, 8, 'erangolani27', 'De Niro''s haunted performance makes Taxi Driver one of the most powerful character studies ever filmed', null); # 326155 Taxi Driver 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (328272, 7, 'erangolani27', 'A warm and gentle Spielberg film held together by Hanks'' effortless likability', null); # 328272 Terminal, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (330670, 7, 'erangolani27', 'A raw and honest coming-of-age story with a brave early performance from DiCaprio', null); # 330670 This Boy''s Life 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (332209, 7, 'erangolani27', 'A quiet and intimate spiritual biography told with great care and sincerity', null); # 332209 Thrse: The Story of Saint Thrse of Lisieux 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (332065, 6, 'erangolani27', 'A passable Bond entry with some entertaining underwater sequences but little else', null); # 332065 Thunderball 1965
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (333856, 9, 'erangolani27', 'An overwhelming spectacle with a love story that still manages to feel genuinely tragic', null); # 333856 Titanic 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335336, 5, 'erangolani27', 'A weak and forgettable Bond entry that wastes a decent cast on a dull plot', null); # 335336 Tomorrow Never Dies 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335835, 8, 'erangolani27', 'Cruise is magnetic and the aerial sequences are exhilarating, a crowd-pleaser that earns it', null); # 335835 Top Gun 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (337166, 9, 'erangolani27', 'Pixar''s founding masterpiece, a warm and inventive story that changed animation forever', null); # 337166 Toy Story 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (340652, 9, 'erangolani27', 'A grand and visually stunning epic that brings the siege of Troy to vivid life', null); # 340652 Troy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (350424, 7, 'erangolani27', 'An ambitious sci-fi remake that is more interesting for its ideas than its execution', null); # 350424 Vanilla Sky 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (354178, 5, 'erangolani27', 'A tired and uninspired Bond entry that feels like it is going through the motions', null); # 354178 View to a Kill, A 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (359297, 5, 'erangolani27', 'Spielberg delivers spectacle but the human story never connects the way it should', null); # 359297 War of the Worlds 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (368418, 6, 'erangolani27', 'A watchable Bond with some good moments but nothing that stands out from the crowd', null); # 368418 World Is Not Enough, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (372233, 7, 'erangolani27', 'Connery''s final Bond has aged well and the Japan setting gives it a distinctive feel', null); # 372233 You Only Live Twice 1967
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (372525, 5, 'erangolani27', 'A broad medical comedy that relies too heavily on cheap gags and caricature', null); # 372525 Young Doctors in Love 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (372733, 8, 'erangolani27', 'A clever and atmospheric Holmes origin story with strong production values', null); # 372733 Young Sherlock Holmes 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10830, 8, 'erangolani27', 'A tense and groundbreaking sci-fi horror with Sigourney Weaver as one of cinema''s great heroes', null); # 10830 Alien 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10920, 7, 'erangolani27', 'Cameron shifts the tone to action but delivers some genuinely thrilling set-pieces', null); # 10920 Aliens 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (21213, 7, 'erangolani27', 'A visually ambitious Spielberg film that raises big questions even if it does not fully answer them', null); # 21213 Artificial Intelligence: AI 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (158999, 6, 'erangolani27', 'A bombastic blockbuster that prioritizes spectacle over substance but remains entertaining', null); # 158999 Independence Day 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120574, 8, 'erangolani27', 'The most refined and suspenseful of the early Bond films, a true Cold War thriller', null); # 120574 From Russia with Love 1963
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131885, 8, 'erangolani27', 'Pure adventure filmmaking with heart, the kind of movie that defined a generation''s childhood', null); # 131885 Goonies, The 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139655, 8, 'erangolani27', 'Cuaron brings genuine darkness and visual imagination to the franchise''s best entry', null); # 139655 Harry Potter and the Prisoner of Azkaban 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139650, 7, 'erangolani27', 'A solid middle chapter that expands the world even if the tone feels slightly off', null); # 139650 Harry Potter and the Chamber of Secrets 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139652, 7, 'erangolani27', 'The stakes are raised and the action is thrilling, though the film strains under its own weight', null); # 139652 Harry Potter and the Goblet of Fire 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159175, 8, 'erangolani27', 'Darker and more intense than Raiders, with a relentless pace and brilliant set-pieces', null); # 159175 Indiana Jones and the Temple of Doom 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188509, 7, 'erangolani27', 'The South Africa setting refreshes the formula and the chemistry between the leads remains strong', null); # 188509 Lethal Weapon 2 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188510, 6, 'erangolani27', 'Still watchable thanks to the leads but the series is clearly running low on inspiration', null); # 188510 Lethal Weapon 3 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (189403, 6, 'erangolani27', 'Dalton brings a harder edge to Bond but the film itself never fully comes alive', null); # 189403 Licence to Kill 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (190869, 7, 'erangolani27', 'A loveable animated film with a big heart and a wonderfully odd central friendship', null); # 190869 Lilo & Stitch 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (192702, 6, 'erangolani27', 'Dalton tries his best but the script lets him down with a forgettable story', null); # 192702 Living Daylights, The 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256631, 7, 'erangolani27', 'A fun if overstuffed sequel that loses focus by cramming in too many characters and subplots', null); # 256631 Pirates of the Caribbean 2 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280305, 5, 'erangolani27', 'A misguided entry that strips away everything that made the original series work', null); # 280305 Rocky V 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (291495, 7, 'erangolani27', 'Murray''s dry cynicism is perfect for this dark Christmas comedy with real bite', null); # 291495 Scrooged 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311040, 6, 'erangolani27', 'An overcrowded mess that squanders three villains and undoes the goodwill of the previous films', null); # 311040 Spider-Man 3 2007
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312150, 6, 'erangolani27', 'A fun and inventive kids adventure that does not talk down to its young audience', null); # 312150 Spy Kids 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313478, 9, 'erangolani27', 'The darkest and most emotionally complex Star Wars film, and easily the best of the saga', null); # 313478 Star Wars: Episode V - The Empire Strikes Back 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (319613, 7, 'erangolani27', 'The Kryptonian villains add real menace and the film matches the original in energy and fun', null); # 319613 Superman II 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (342512, 7, 'erangolani27', 'A mixed but worthwhile anthology with a couple of segments that are genuinely haunting', null); # 342512 Twilight Zone: The Movie 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (174953, 8, 'erangolani27', 'A breathtaking Miyazaki epic with stunning hand-drawn visuals and a powerful ecological message', null); # 174953 Kaze no tani no Naushika 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30965, 5, 'erangolani27', 'Carrey is entertaining in isolation but the film around him is an incoherent disaster', null); # 30965 Batman Forever 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30952, 3, 'erangolani27', 'A catastrophic misfire that nearly killed the superhero genre before it truly began', null); # 30952 Batman & Robin 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (94741, 8, 'erangolani27', 'Spielberg''s TV debut is a masterclass in sustained tension with almost no dialogue', null); # 94741 Duel 1971
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (270628, 7, 'erangolani27', 'A heartfelt and difficult film about childhood trauma that does not shy away from the pain', null); # 270628 Radio Flyer 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (336445, 7, 'erangolani27', 'A bold and uncompromising film with DiCaprio delivering a fearless early performance', null); # 336445 Total Eclipse 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215880, 7, 'erangolani27', 'The best of the Cruise sequels, with tighter action and a more confident directorial hand', null); # 215880 Mission: Impossible III 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (20253, 7, 'erangolani27', 'A beautifully strange film that follows its own dream logic with complete conviction', null); # 20253 Arizona Dream 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30961, 7, 'erangolani27', 'A surprisingly dark and mature animated film that takes the Batman mythology seriously', null); # 30961 Batman Beyond: Return of the Joker 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (299073, 9, 'erangolani27', 'The weird high noises in the music make this movie creepy.', null); # 299073 Shining, The (1980)
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (18960, 9, 'erangolani27', 'A hallucinatory descent into the heart of Vietnam.', null); # 18960 Apocalypse Now (1979)
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (276085, 10, 'erangolani27', 'This movie is so upsetting and it really shocks your soul.', null); # 276085 Requiem for a Dream (2000)
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (137655, 8, 'erangolani27', 'The simple piano notes are so scary and iconic for horror.', null); # 137655 Halloween (1978)
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (301540, 10, 'erangolani27', 'Hopkins is hypnotic; the tension never lets up.', null); # 301540 Silence of the Lambs, The (1991)
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (303564, 9, 'erangolani27', 'A ghost story that earns its twist.', null); # 303564 Sixth Sense, The (1999)
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (257459, 8, 'erangolani27', 'Raw and unflinching combat through a young soldier''s eyes.', null); # 257459 Platoon (1986)
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (70248, 8, 'erangolani27', 'Paranoia done with surgical precision.', null); # 70248 Conversation, The (1974)
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (207992, 9, 'erangolani27', 'The techno music fits the digital world and action perfectly.', null); # 207992 Matrix, The (1999)
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (254986, 10, 'erangolani27', 'The piano songs are beautiful and make the story sad.', null); # 254986 Pianist, The (2002)
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313459, 9, 'erangolani27', 'The Imperial March is so cool and very scary for a movie.', null); # 313459 Star Wars (1977)
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (26844, 10, 'erangolani27', 'A near-perfect blockbuster with wit and heart.', null); # 26844 Back to the Future (1985)
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (330388, 8, 'erangolani27', 'A meditative, visually stunning meditation on war.', null); # 330388 Thin Red Line, The (1998)
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (106790, 9, 'erangolani27', 'The slow violin soundtrack is beautiful and very sad.', null); # 106790 Fa yeung nin wa (2000)
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (348944, 9, 'erangolani27', 'Twisty, stylish, and the ending still surprises on rewatches.', null); # 348944 Usual Suspects, The (1995)
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (62076, 9, 'erangolani27', 'A perfect neo-noir with one of the great endings.', null); # 62076 Chinatown (1974)
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (186439, 10, 'erangolani27', 'The desert theme music is grand and sounds amazing.', null); # 186439 Lawrence of Arabia (1962)
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130128, 9, 'erangolani27', 'The classic slow music makes the whole story feel grand.', null); # 130128 Godfather, The (1972)
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (141544, 9, 'erangolani27', 'The diner scene alone is worth the whole movie.', null); # 141544 Heat (1995)
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (49696, 9, 'erangolani27', 'The whistling music in the desert makes this feel so cool.', null); # 49696 Buono, il brutto, il cattivo, Il (1966)
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (644, 8, 'erangolani27', 'A fresh and fun version of an old story with good music.', null); # 644 10 Things I Hate About You (1999)
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313059, 9, 'erangolani27', 'The friendship drama that defines coming-of-age.', null); # 313059 Stand by Me (1986)
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (191246, 10, 'erangolani27', 'The opening song is one of the best moments in any cartoon.', null); # 191246 Lion King, The (1994)
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (82967, 9, 'erangolani27', 'Scorsese''s Boston crime epic; an ending nobody saw coming.', null); # 82967 Departed, The (2006)
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (121538, 9, 'erangolani27', 'The rhythmic songs in the army scenes feel strong.', null); # 121538 Full Metal Jacket (1987)
