insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (379290,8,'guyn1414','Loved it; great storytelling and strong performances, would watch this again happily.',NULL); # 379290 Adventures of Batman, The 1969
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (379327,5,'guyn1414','Ok movie; decent enough but nothing that stands out or stays with you after watching.',NULL); # 379327 Adventures of Robin Hood, The 1955
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (379331,4,'guyn1414','I dont like this; slow and unengaging, the story never pulls me in at any point.',NULL); # 379331 Adventures of Sherlock Holmes, The 1984
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (379931,7,'guyn1414','Loved it at the time; enjoyable and well-crafted, left me with a good impression.',NULL); # 379931 Amazing Stories 1985
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (381392,6,'guyn1414','Good movie that fits my taste; solid entertainment with enough quality to recommend.',NULL); # 381392 Batman Beyond 1999
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (382208,2,'guyn1414','No way; painfully bad and a waste of time, would never sit through this again.',NULL); # 382208 Blansky's Beauties 1977
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (383395,10,'guyn1414','I love this movie and would watch it anytime; an absolute masterpiece in every way.',NULL); # 383395 Captain America 1966
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (390691,5,'guyn1414','Ok movie; watchable but forgettable, does not leave much of an impression overall.',NULL); # 390691 Growing Pains 1985
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (391006,4,'guyn1414','I dont like this; poor execution and dull pacing make this very hard to enjoy.',NULL); # 391006 Happy Days 1974
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (391453,6,'guyn1414','Good movie that fits my taste; entertaining and competent with moments worth seeing.',NULL); # 391453 Herndon 1983
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (393012,7,'guyn1414','Loved it at the time; memorable and engaging, the kind of film I recall fondly.',NULL); # 393012 Iron Man 1966
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (395271,8,'guyn1414','Loved it; compelling and well made, I would definitely watch more like this.',NULL); # 395271 Laverne & Shirley 1976
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (397121,5,'guyn1414','Ok movie; has its moments but overall too average to leave a lasting impression.',NULL); # 397121 Matrix 1993
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (397250,4,'guyn1414','I dont like this; the premise had potential but the execution is deeply disappointing.',NULL); # 397250 Me and the Chimp 1972
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (398232,6,'guyn1414','Good movie that fits my taste; enjoyable watch with solid craft and a good pace.',NULL); # 398232 Mork & Mindy 1978
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (398571,2,'guyn1414','No way; unwatchable from start to finish, no redeeming qualities I can point to.',NULL); # 398571 Murphy Brown 1988
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (399427,7,'guyn1414','Loved it at the time; well directed and emotionally engaging, holds up very well.',NULL); # 399427 Night Gallery 1970
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (400612,10,'guyn1414','I love this movie and would watch it anytime; every scene is a joy, a true classic.',NULL); # 400612 Owen Marshall: Counselor at Law 1971
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (400853,5,'guyn1414','Ok movie; inoffensive and mildly entertaining but nothing to seek out intentionally.',NULL); # 400853 Parenthood 1990
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (405119,8,'guyn1414','Loved it; outstanding film with real depth and craft, would gladly revisit this.',NULL); # 405119 Sherlock Holmes 1951
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (406158,8,'guyn1414','Loved it; great storytelling and strong performances, would watch this again happily.',NULL); # 406158 Spider-Man 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (406411,5,'guyn1414','Ok movie; decent enough but nothing that stands out or stays with you after watching.',NULL); # 406411 Star Wars: Clone Wars 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (406759,4,'guyn1414','I dont like this; slow and unengaging, the story never pulls me in at any point.',NULL); # 406759 Strokes of Genius 1984
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (2,7,'guyn1414','Loved it at the time; enjoyable and well-crafted, left me with a good impression.',NULL); # 2 $ 1971
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (12,6,'guyn1414','Good movie that fits my taste; solid entertainment with enough quality to recommend.',NULL); # 12 $20,000 Carat, The 1913
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (15,2,'guyn1414','No way; painfully bad and a waste of time, would never sit through this again.',NULL); # 15 $30 1999
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (18,10,'guyn1414','I love this movie and would watch it anytime; an absolute masterpiece in every way.',NULL); # 18 $40,000 1996
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (20,5,'guyn1414','Ok movie; watchable but forgettable, does not leave much of an impression overall.',NULL); # 20 $5,000,000 Counterfeiting Plot, The 1914
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (33,4,'guyn1414','I dont like this; poor execution and dull pacing make this very hard to enjoy.',NULL); # 33 $windle 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (37,6,'guyn1414','Good movie that fits my taste; entertaining and competent with moments worth seeing.',NULL); # 37 '24-25' ne vozvrashchayetsya 1968
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (47,7,'guyn1414','Loved it at the time; memorable and engaging, the kind of film I recall fondly.',NULL); # 47 '88 Dodge Aries 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (51,8,'guyn1414','Loved it; compelling and well made, I would definitely watch more like this.',NULL); # 51 'A' 1965
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (52,5,'guyn1414','Ok movie; has its moments but overall too average to leave a lasting impression.',NULL); # 52 'A' gai waak 1983
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (53,4,'guyn1414','I dont like this; the premise had potential but the execution is deeply disappointing.',NULL); # 53 'A' gai waak juk jaap 1987
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (74,6,'guyn1414','Good movie that fits my taste; enjoyable watch with solid craft and a good pace.',NULL); # 74 'C' Word, The 1993
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (81,2,'guyn1414','No way; unwatchable from start to finish, no redeeming qualities I can point to.',NULL); # 81 'Columbia' and 'Shamrock II': Jockeying and Starting 1901
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (82,7,'guyn1414','Loved it at the time; well directed and emotionally engaging, holds up very well.',NULL); # 82 'Columbia' and 'Shamrock II': Start of Second Race 1901
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (83,10,'guyn1414','I love this movie and would watch it anytime; every scene is a joy, a true classic.',NULL); # 83 'Columbia' and 'Shamrock II': Starting in the Third Race 1901
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (84,5,'guyn1414','Ok movie; inoffensive and mildly entertaining but nothing to seek out intentionally.',NULL); # 84 'Columbia' and 'Shamrock II': Turning the Outer Stake Boat 1901
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (100,8,'guyn1414','Loved it; outstanding film with real depth and craft, would gladly revisit this.',NULL); # 100 'E' 1981
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (108,8,'guyn1414','Loved it; great storytelling and strong performances, would watch this again happily.',NULL); # 108 'G' Men 1935
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (121,5,'guyn1414','Ok movie; decent enough but nothing that stands out or stays with you after watching.',NULL); # 121 'High Sign', The 1921
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (152,4,'guyn1414','I dont like this; slow and unengaging, the story never pulls me in at any point.',NULL); # 152 'M' Word 1996
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (153,7,'guyn1414','Loved it at the time; enjoyable and well-crafted, left me with a good impression.',NULL); # 153 'Mad' Boy, I'll Blow Your Blues Away. Be Mine 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (154,6,'guyn1414','Good movie that fits my taste; solid entertainment with enough quality to recommend.',NULL); # 154 'Make-Up' Thief, The 1899
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (167,2,'guyn1414','No way; painfully bad and a waste of time, would never sit through this again.',NULL); # 167 'Minagoroshi no uta' yori kenj-yo saraba! 1960
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (168,10,'guyn1414','I love this movie and would watch it anytime; an absolute masterpiece in every way.',NULL); # 168 'Ming wang xing' xing dong 1992
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (178,5,'guyn1414','Ok movie; watchable but forgettable, does not leave much of an impression overall.',NULL); # 178 'N Sync: 'Ntimate Holiday Special 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (179,4,'guyn1414','I dont like this; poor execution and dull pacing make this very hard to enjoy.',NULL); # 179 'N Sync: Live From Madison Square Garden 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (180,6,'guyn1414','Good movie that fits my taste; entertaining and competent with moments worth seeing.',NULL); # 180 'N Sync: Making the Tour 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (181,7,'guyn1414','Loved it at the time; memorable and engaging, the kind of film I recall fondly.',NULL); # 181 'N Sync: No Strings Attached 1999
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (182,8,'guyn1414','Loved it; compelling and well made, I would definitely watch more like this.',NULL); # 182 'N Sync: PopOdyssey Live 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (183,5,'guyn1414','Ok movie; has its moments but overall too average to leave a lasting impression.',NULL); # 183 'N Sync: The Atlantis Concert 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (184,4,'guyn1414','I dont like this; the premise had potential but the execution is deeply disappointing.',NULL); # 184 'Ne gnstige Gelegenheit 1999
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (244,6,'guyn1414','Good movie that fits my taste; enjoyable watch with solid craft and a good pace.',NULL); # 244 'Sloboda' - Kula 1971
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (253,2,'guyn1414','No way; unwatchable from start to finish, no redeeming qualities I can point to.',NULL); # 253 't Is wreed in de wereld 1954
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (254,7,'guyn1414','Loved it at the time; well directed and emotionally engaging, holds up very well.',NULL); # 254 't Was een April 1935
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (263,10,'guyn1414','I love this movie and would watch it anytime; every scene is a joy, a true classic.',NULL); # 263 'Til There Was You 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (275,5,'guyn1414','Ok movie; inoffensive and mildly entertaining but nothing to seek out intentionally.',NULL); # 275 'Tong tatlong tatay kong pakitong-kitong 1998
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (315,8,'guyn1414','Loved it; outstanding film with real depth and craft, would gladly revisit this.',NULL); # 315 (Now) 1976
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (316,8,'guyn1414','Loved it; great storytelling and strong performances, would watch this again happily.',NULL); # 316 (Ohne Titel) 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (318,5,'guyn1414','Ok movie; decent enough but nothing that stands out or stays with you after watching.',NULL); # 318 (Past Present Future) 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (321,4,'guyn1414','I dont like this; slow and unengaging, the story never pulls me in at any point.',NULL); # 321 (Stories from) 1995
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (322,7,'guyn1414','Loved it at the time; enjoyable and well-crafted, left me with a good impression.',NULL); # 322 (T) 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (323,6,'guyn1414','Good movie that fits my taste; solid entertainment with enough quality to recommend.',NULL); # 323 (Un) 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (330,2,'guyn1414','No way; painfully bad and a waste of time, would never sit through this again.',NULL); # 330 +1 -1 1987
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (338,10,'guyn1414','I love this movie and would watch it anytime; an absolute masterpiece in every way.',NULL); # 338 ...A Valparaso 1962
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (365,5,'guyn1414','Ok movie; watchable but forgettable, does not leave much of an impression overall.',NULL); # 365 ...borgnes sont rois, Les 1974
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (370,4,'guyn1414','I dont like this; poor execution and dull pacing make this very hard to enjoy.',NULL); # 370 ...continuavano a chiamarlo Trinit 1972
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (387,6,'guyn1414','Good movie that fits my taste; entertaining and competent with moments worth seeing.',NULL); # 387 ...e la vita continua 1984
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (411,7,'guyn1414','Loved it at the time; memorable and engaging, the kind of film I recall fondly.',NULL); # 411 ...It Is Nice to Be Privileged 1976
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (413,8,'guyn1414','Loved it; compelling and well made, I would definitely watch more like this.',NULL); # 413 ...Ja teeb trikke 1978
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (450,5,'guyn1414','Ok movie; has its moments but overall too average to leave a lasting impression.',NULL); # 450 ...tick...tick...tick... 1970
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (494,4,'guyn1414','I dont like this; the premise had potential but the execution is deeply disappointing.',NULL); # 494 ...Y los sueos pasan 1939
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (499,6,'guyn1414','Good movie that fits my taste; enjoyable watch with solid craft and a good pace.',NULL); # 499 ...ya no puede caminar. 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (517,2,'guyn1414','No way; unwatchable from start to finish, no redeeming qualities I can point to.',NULL); # 517 .hack//Quarantine 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (523,7,'guyn1414','Loved it at the time; well directed and emotionally engaging, holds up very well.',NULL); # 523 0-600-Amor ya 1998
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (576,10,'guyn1414','I love this movie and would watch it anytime; every scene is a joy, a true classic.',NULL); # 576 1 s a semmi 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (589,5,'guyn1414','Ok movie; inoffensive and mildly entertaining but nothing to seek out intentionally.',NULL); # 589 1-2-3 Go! 1941
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (599,8,'guyn1414','Loved it; outstanding film with real depth and craft, would gladly revisit this.',NULL); # 599 1. maj 1960 1960
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (618,8,'guyn1414','Loved it; great storytelling and strong performances, would watch this again happily.',NULL); # 618 10 from Your Show of Shows 1973
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (628,5,'guyn1414','Ok movie; decent enough but nothing that stands out or stays with you after watching.',NULL); # 628 10 minuta 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (632,4,'guyn1414','I dont like this; slow and unengaging, the story never pulls me in at any point.',NULL); # 632 10 Minuten zwischen Hamburg und Salzburg 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (641,7,'guyn1414','Loved it at the time; enjoyable and well-crafted, left me with a good impression.',NULL); # 641 10 Seconds 1998
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (644,6,'guyn1414','Good movie that fits my taste; solid entertainment with enough quality to recommend.',NULL); # 644 10 Things I Hate About You 1999
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (660,2,'guyn1414','No way; painfully bad and a waste of time, would never sit through this again.',NULL); # 660 10,000 Kids and a Cop 1948
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (661,10,'guyn1414','I love this movie and would watch it anytime; an absolute masterpiece in every way.',NULL); # 661 10,000 Maniacs Time Capsule 1990
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (671,5,'guyn1414','Ok movie; watchable but forgettable, does not leave much of an impression overall.',NULL); # 671 10/65: Selbstverstmmelung 1965
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (672,4,'guyn1414','I dont like this; poor execution and dull pacing make this very hard to enjoy.',NULL); # 672 100 aos de perdn 1998
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (673,6,'guyn1414','Good movie that fits my taste; entertaining and competent with moments worth seeing.',NULL); # 673 100 Bullets 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (674,7,'guyn1414','Loved it at the time; memorable and engaging, the kind of film I recall fondly.',NULL); # 674 100 Cameras: Capturing Lars Von Trier's Vision 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (675,8,'guyn1414','Loved it; compelling and well made, I would definitely watch more like this.',NULL); # 675 100 Days 1991
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (676,5,'guyn1414','Ok movie; has its moments but overall too average to leave a lasting impression.',NULL); # 676 100 Days 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (690,4,'guyn1414','I dont like this; the premise had potential but the execution is deeply disappointing.',NULL); # 690 100 Greatest TV Characters, The 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (720,6,'guyn1414','Good movie that fits my taste; enjoyable watch with solid craft and a good pace.',NULL); # 720 100 Worst Pop Records 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (724,2,'guyn1414','No way; unwatchable from start to finish, no redeeming qualities I can point to.',NULL); # 724 100 Years of Horror 1996
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (725,7,'guyn1414','Loved it at the time; well directed and emotionally engaging, holds up very well.',NULL); # 725 100 Years of Horror: Freaks 1996
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (726,10,'guyn1414','I love this movie and would watch it anytime; every scene is a joy, a true classic.',NULL); # 726 100 Years of Horror: Giants and Dinosaurs 1996
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (727,5,'guyn1414','Ok movie; inoffensive and mildly entertaining but nothing to seek out intentionally.',NULL); # 727 100 Years of Horror: Maniacs 1996
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (728,8,'guyn1414','Loved it; outstanding film with real depth and craft, would gladly revisit this.',NULL); # 728 100 Years of Horror: Scream Queens 1996
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (729,8,'guyn1414','Loved it; great storytelling and strong performances, would watch this again happily.',NULL); # 729 100 Years of Horror: Sorcerers 1996
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (731,5,'guyn1414','Ok movie; decent enough but nothing that stands out or stays with you after watching.',NULL); # 731 100 Years of Horror: The Count and Company 1996
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (735,4,'guyn1414','I dont like this; slow and unengaging, the story never pulls me in at any point.',NULL); # 735 100 Years of Horror: The Monster Makers 1996
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (798,7,'guyn1414','Loved it at the time; enjoyable and well-crafted, left me with a good impression.',NULL); # 798 100% Service 1931
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (818,6,'guyn1414','Good movie that fits my taste; solid entertainment with enough quality to recommend.',NULL); # 818 1000 Marys 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (829,2,'guyn1414','No way; painfully bad and a waste of time, would never sit through this again.',NULL); # 829 10000th Day, The 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (832,10,'guyn1414','I love this movie and would watch it anytime; an absolute masterpiece in every way.',NULL); # 832 1001 crtez 1960
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (837,5,'guyn1414','Ok movie; watchable but forgettable, does not leave much of an impression overall.',NULL); # 837 1001 Nights 1998
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (846,4,'guyn1414','I dont like this; poor execution and dull pacing make this very hard to enjoy.',NULL); # 846 101 Biggest Celebrity Oops 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (849,6,'guyn1414','Good movie that fits my taste; entertaining and competent with moments worth seeing.',NULL); # 849 101 Dalmatians II: Patch's London Adventure 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (850,7,'guyn1414','Loved it at the time; memorable and engaging, the kind of film I recall fondly.',NULL); # 850 101 Dalmatians Sing Along 1996
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (870,8,'guyn1414','Loved it; compelling and well made, I would definitely watch more like this.',NULL); # 870 101 Reykjavk 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (878,5,'guyn1414','Ok movie; has its moments but overall too average to leave a lasting impression.',NULL); # 878 102 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (886,4,'guyn1414','I dont like this; the premise had potential but the execution is deeply disappointing.',NULL); # 886 105 % alibi 1959
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (895,6,'guyn1414','Good movie that fits my taste; enjoyable watch with solid craft and a good pace.',NULL); # 895 10:30 Check-Out 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (923,2,'guyn1414','No way; unwatchable from start to finish, no redeeming qualities I can point to.',NULL); # 923 11-22-63: The Day the Nation Cried 1989
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (952,7,'guyn1414','Loved it at the time; well directed and emotionally engaging, holds up very well.',NULL); # 952 11:00 AM 1999
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (957,10,'guyn1414','I love this movie and would watch it anytime; every scene is a joy, a true classic.',NULL); # 957 11th & Congress 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (966,5,'guyn1414','Ok movie; inoffensive and mildly entertaining but nothing to seek out intentionally.',NULL); # 966 12 (2003/II) 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (985,8,'guyn1414','Loved it; outstanding film with real depth and craft, would gladly revisit this.',NULL); # 985 12 Mdchen und 1 Mann 1959
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (997,8,'guyn1414','Loved it; great storytelling and strong performances, would watch this again happily.',NULL); # 997 12 Uhr mittags kommt der Bo 1968
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (1018,5,'guyn1414','Ok movie; decent enough but nothing that stands out or stays with you after watching.',NULL); # 1018 12:01 1993
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (1024,4,'guyn1414','I dont like this; slow and unengaging, the story never pulls me in at any point.',NULL); # 1024 13 (1999/I) 1999
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (1027,7,'guyn1414','Loved it at the time; enjoyable and well-crafted, left me with a good impression.',NULL); # 1027 13 dni 1964
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (1029,6,'guyn1414','Good movie that fits my taste; solid entertainment with enough quality to recommend.',NULL); # 1029 13 Erotic Ghosts 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (1038,2,'guyn1414','No way; painfully bad and a waste of time, would never sit through this again.',NULL); # 1038 13 Going On 30 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (1046,10,'guyn1414','I love this movie and would watch it anytime; an absolute masterpiece in every way.',NULL); # 1046 13 Moons 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (1100,5,'guyn1414','Ok movie; watchable but forgettable, does not leave much of an impression overall.',NULL); # 1100 14 Million Dreams 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (1121,4,'guyn1414','I dont like this; poor execution and dull pacing make this very hard to enjoy.',NULL); # 1121 1492: Conquest of Paradise 1992
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (1390,6,'guyn1414','Good movie that fits my taste; entertaining and competent with moments worth seeing.',NULL); # 1390 1941 1979
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (2057,7,'guyn1414','Loved it at the time; memorable and engaging, the kind of film I recall fondly.',NULL); # 2057 2wks, 1yr 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (2352,8,'guyn1414','Loved it; compelling and well made, I would definitely watch more like this.',NULL); # 2352 36K 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (2656,5,'guyn1414','Ok movie; has its moments but overall too average to leave a lasting impression.',NULL); # 2656 5 Card Stud 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (2986,4,'guyn1414','I dont like this; the premise had potential but the execution is deeply disappointing.',NULL); # 2986 7 jin gong 1994
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (3055,6,'guyn1414','Good movie that fits my taste; enjoyable watch with solid craft and a good pace.',NULL); # 3055 76th Annual Academy Awards, The 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (3261,2,'guyn1414','No way; unwatchable from start to finish, no redeeming qualities I can point to.',NULL); # 3261 97 goo waak jai jin mo bat sing 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (3634,7,'guyn1414','Loved it at the time; well directed and emotionally engaging, holds up very well.',NULL); # 3634 A&E Biography: Captain Bligh - Mutiny on the Bounty 1996
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (4948,10,'guyn1414','I love this movie and would watch it anytime; every scene is a joy, a true classic.',NULL); # 4948 Able's House Is Green, The 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (5496,5,'guyn1414','Ok movie; inoffensive and mildly entertaining but nothing to seek out intentionally.',NULL); # 5496 Accordon 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (5889,8,'guyn1414','Loved it; outstanding film with real depth and craft, would gladly revisit this.',NULL); # 5889 Act Your Age 1939
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (7341,8,'guyn1414','Loved it; great storytelling and strong performances, would watch this again happily.',NULL); # 7341 Aerosmith: Big Ones You Can Look at 1994
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (7842,5,'guyn1414','Ok movie; decent enough but nothing that stands out or stays with you after watching.',NULL); # 7842 After Hours 1985
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (8183,4,'guyn1414','I dont like this; slow and unengaging, the story never pulls me in at any point.',NULL); # 8183 Age of Innocence, The 1993
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (8820,7,'guyn1414','Loved it at the time; enjoyable and well-crafted, left me with a good impression.',NULL); # 8820 Ai-Fak 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (8880,6,'guyn1414','Good movie that fits my taste; solid entertainment with enough quality to recommend.',NULL); # 8880 Aiglon, L' 1931
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (9813,2,'guyn1414','No way; painfully bad and a waste of time, would never sit through this again.',NULL); # 9813 Aladdin in Nasira's Revenge 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (10702,10,'guyn1414','I love this movie and would watch it anytime; an absolute masterpiece in every way.',NULL); # 10702 Alice Doesn't Live Here Anymore 1974
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (10945,5,'guyn1414','Ok movie; watchable but forgettable, does not leave much of an impression overall.',NULL); # 10945 Alien 1992
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (10830,4,'guyn1414','I dont like this; poor execution and dull pacing make this very hard to enjoy.',NULL); # 10830 Alien 1979
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (10920,6,'guyn1414','Good movie that fits my taste; entertaining and competent with moments worth seeing.',NULL); # 10920 Aliens 1986
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (11147,7,'guyn1414','Loved it at the time; memorable and engaging, the kind of film I recall fondly.',NULL); # 11147 All American Hero 1999
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (11286,8,'guyn1414','Loved it; compelling and well made, I would definitely watch more like this.',NULL); # 11286 All In 2005
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (11507,5,'guyn1414','Ok movie; has its moments but overall too average to leave a lasting impression.',NULL); # 11507 All the Invisible Children 2006
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (12744,4,'guyn1414','I dont like this; the premise had potential but the execution is deeply disappointing.',NULL); # 12744 Always 1989
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (13343,6,'guyn1414','Good movie that fits my taste; enjoyable watch with solid craft and a good pace.',NULL); # 13343 Amazing Adventures of Spider-Man, The 1999
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (13395,2,'guyn1414','No way; unwatchable from start to finish, no redeeming qualities I can point to.',NULL); # 13395 Amazing Stories: Book Four 1992
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (13396,7,'guyn1414','Loved it at the time; well directed and emotionally engaging, holds up very well.',NULL); # 13396 Amazing Stories: Book One 1992
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (13444,10,'guyn1414','I love this movie and would watch it anytime; every scene is a joy, a true classic.',NULL); # 13444 Amazones 2000 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (13547,5,'guyn1414','Ok movie; inoffensive and mildly entertaining but nothing to seek out intentionally.',NULL); # 13547 Amblin' 1968
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (14132,8,'guyn1414','Loved it; outstanding film with real depth and craft, would gladly revisit this.',NULL); # 14132 American Pie 2 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (14157,8,'guyn1414','Loved it; great storytelling and strong performances, would watch this again happily.',NULL); # 14157 American Reunion, An 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (14477,5,'guyn1414','Ok movie; decent enough but nothing that stands out or stays with you after watching.',NULL); # 14477 Amistad 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (15187,4,'guyn1414','I dont like this; slow and unengaging, the story never pulls me in at any point.',NULL); # 15187 Amsterdamned 1988
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (16730,7,'guyn1414','Loved it at the time; enjoyable and well-crafted, left me with a good impression.',NULL); # 16730 Angel on My Shoulder 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (17370,6,'guyn1414','Good movie that fits my taste; solid entertainment with enough quality to recommend.',NULL); # 17370 Anjangarh (1948/II) 1948
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (17812,2,'guyn1414','No way; painfully bad and a waste of time, would never sit through this again.',NULL); # 17812 Anno Domini 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (19433,10,'guyn1414','I love this movie and would watch it anytime; an absolute masterpiece in every way.',NULL); # 19433 Aquarium, L' 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (20253,5,'guyn1414','Ok movie; watchable but forgettable, does not leave much of an impression overall.',NULL); # 20253 Arizona Dream 1993
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (20446,4,'guyn1414','I dont like this; poor execution and dull pacing make this very hard to enjoy.',NULL); # 20446 Armenian Archbishop, Rome 1898
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (20713,6,'guyn1414','Good movie that fits my taste; entertaining and competent with moments worth seeing.',NULL); # 20713 Arregui, la noticia del da 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (21213,7,'guyn1414','Loved it at the time; memorable and engaging, the kind of film I recall fondly.',NULL); # 21213 Artificial Intelligence: AI 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (21454,8,'guyn1414','Loved it; compelling and well made, I would definitely watch more like this.',NULL); # 21454 As I Was Moving Ahead Occasionally I Saw Brief Glimpses of Beauty 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (22093,5,'guyn1414','Ok movie; has its moments but overall too average to leave a lasting impression.',NULL); # 22093 Asla Navra Nakoga Bai 1977
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (22651,4,'guyn1414','I dont like this; the premise had potential but the execution is deeply disappointing.',NULL); # 22651 Astronaut's Wife, The 1999
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (24235,6,'guyn1414','Good movie that fits my taste; enjoyable watch with solid craft and a good pace.',NULL); # 24235 Aunt Tiger 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (24259,2,'guyn1414','No way; unwatchable from start to finish, no redeeming qualities I can point to.',NULL); # 24259 Aura 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (24339,7,'guyn1414','Loved it at the time; well directed and emotionally engaging, holds up very well.',NULL); # 24339 Aus der Waldbhne Berlin - Italienische Nacht/Italian Night 1996
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (25192,10,'guyn1414','I love this movie and would watch it anytime; every scene is a joy, a true classic.',NULL); # 25192 Aviator, The 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (25729,5,'guyn1414','Ok movie; inoffensive and mildly entertaining but nothing to seek out intentionally.',NULL); # 25729 Azrail benim 1968
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (25943,8,'guyn1414','Loved it; outstanding film with real depth and craft, would gladly revisit this.',NULL); # 25943 Baan sau chuk dak hin dui 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (28085,8,'guyn1414','Loved it; great storytelling and strong performances, would watch this again happily.',NULL); # 28085 Bakit may kahapon pa? 1996
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (28092,5,'guyn1414','Ok movie; decent enough but nothing that stands out or stays with you after watching.',NULL); # 28092 Bakom jalusin 1984
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (28631,4,'guyn1414','I dont like this; slow and unengaging, the story never pulls me in at any point.',NULL); # 28631 Balloon 1991
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (29760,7,'guyn1414','Loved it at the time; enjoyable and well-crafted, left me with a good impression.',NULL); # 29760 Barbie Riding Club 1998
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (29768,6,'guyn1414','Good movie that fits my taste; solid entertainment with enough quality to recommend.',NULL); # 29768 Barbier de Sville, Le 1904
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (29771,2,'guyn1414','No way; painfully bad and a waste of time, would never sit through this again.',NULL); # 29771 Barbier de Sville, Le 1980
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (29772,10,'guyn1414','I love this movie and would watch it anytime; an absolute masterpiece in every way.',NULL); # 29772 Barbier von Sevilla, Der 1972
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (29773,5,'guyn1414','Ok movie; watchable but forgettable, does not leave much of an impression overall.',NULL); # 29773 Barbier, Le (2001/I) 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (30686,4,'guyn1414','I dont like this; poor execution and dull pacing make this very hard to enjoy.',NULL); # 30686 Basketball Diaries, The 1995
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (30955,6,'guyn1414','Good movie that fits my taste; entertaining and competent with moments worth seeing.',NULL); # 30955 Batman 1989
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (30951,7,'guyn1414','Loved it at the time; memorable and engaging, the kind of film I recall fondly.',NULL); # 30951 Batman & Mr. Freeze: SubZero 1998
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (30952,8,'guyn1414','Loved it; compelling and well made, I would definitely watch more like this.',NULL); # 30952 Batman & Robin 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (30953,5,'guyn1414','Ok movie; has its moments but overall too average to leave a lasting impression.',NULL); # 30953 Batman & Robin 1998
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (30957,4,'guyn1414','I dont like this; the premise had potential but the execution is deeply disappointing.',NULL); # 30957 Batman and Robin 1949
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (30959,6,'guyn1414','Good movie that fits my taste; enjoyable watch with solid craft and a good pace.',NULL); # 30959 Batman Begins 2005
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (30961,2,'guyn1414','No way; unwatchable from start to finish, no redeeming qualities I can point to.',NULL); # 30961 Batman Beyond: Return of the Joker (2000/I) 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (30962,7,'guyn1414','Loved it at the time; well directed and emotionally engaging, holds up very well.',NULL); # 30962 Batman Beyond: The Movie 1999
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (30965,10,'guyn1414','I love this movie and would watch it anytime; every scene is a joy, a true classic.',NULL); # 30965 Batman Forever 1995
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (30967,5,'guyn1414','Ok movie; inoffensive and mildly entertaining but nothing to seek out intentionally.',NULL); # 30967 Batman Returns 1992
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (30968,8,'guyn1414','Loved it; outstanding film with real depth and craft, would gladly revisit this.',NULL); # 30968 Batman Returns (1992/II) 1992
