insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (151616, 10, 'hilinetz', 'one of my all time favorites, watched it like five times already. kate hudson and matthew mcconaughey are hilarious together and the ending is so satisfying.', null);  # 151616 How to Lose a Guy in 10 Days 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (333856, 10, 'hilinetz', 'i cry every single time no matter how many times i watch it. the love story feels so real and the visuals are stunning.', null);  # 333856 Titanic 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (644, 9, 'hilinetz', 'so rewatchable. the banter between the two leads is actually really funny and the shakespeare twist works surprisingly well.', null);  # 644 10 Things I Hate About You 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (66194, 10, 'hilinetz', 'clueless is genuinely iconic. alicia silverstone carries the whole film and even after all these years it is still hilarious.', null);  # 66194 Clueless 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (1038, 9, 'hilinetz', 'i love this movie so much. the nostalgia, the romance, the thriller night scene. it has everything.', null);  # 1038 13 Going On 30 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46878, 9, 'hilinetz', 'loved this sequel just as much as the first bridget jones. mark darcy is everything and the humor still lands perfectly.', null);  # 46878 Bridget Jones: The Edge of Reason 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (62460, 9, 'hilinetz', 'chocolat is so beautiful and warm. the romance with johnny depp sneaks up on you and the whole film just feels magical.', null);  # 62460 Chocolat 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (200864, 9, 'hilinetz', 'jennifer lopez is perfect in this. the story is predictable but in the best way and the chemistry is really charming.', null);  # 200864 Maid in Manhattan 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (220276, 9, 'hilinetz', 'moulin rouge is like nothing else. the music combined with the love story creates something genuinely unique and emotional.', null);  # 220276 Moulin Rouge! 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (245699, 9, 'hilinetz', 'overboard is so funny and the enemies to lovers dynamic is done really well. goldie hawn and kurt russell have amazing chemistry.', null);  # 245699 Overboard 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (257744, 8, 'hilinetz', 'playing by heart is really underrated. the ensemble cast and all the different love stories weaving together work so well.', null);  # 257744 Playing by Heart 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (118980, 8, 'hilinetz', 'frankie and johnny is a quiet and touching romance between two very unlikely people. pacino and pfeiffer make it really believable.', null);  # 118980 Frankie and Johnny 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (34104, 8, 'hilinetz', 'benny and joon is the most adorable quirky romance. johnny depp doing silent film physical comedy is unexpectedly sweet.', null);  # 34104 Benny & Joon 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (113506, 9, 'hilinetz', 'finding neverland is genuinely beautiful. johnny depp and kate winslet have this lovely chemistry and the ending broke me.', null);  # 113506 Finding Neverland 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (97727, 9, 'hilinetz', 'edward scissorhands is such a unique love story. the sadness underneath the whole film makes it more powerful than i expected.', null);  # 97727 Edward Scissorhands 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (328272, 9, 'hilinetz', 'the terminal is so warm and funny. the way the romance develops slowly and naturally is really sweet and tom hanks is perfect.', null);  # 328272 Terminal, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (59578, 8, 'hilinetz', 'charlie and the chocolate factory is visually stunning. tim burton and johnny depp together always create something memorable.', null);  # 59578 Charlie and the Chocolate Factory 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (74259, 7, 'hilinetz', 'cry baby is so ridiculous but in a really fun way. johnny depp being a teen rebel is entertaining even if it is completely over the top.', null);  # 74259 Cry-Baby 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (304862, 8, 'hilinetz', 'sleepy hollow has such a beautiful gothic atmosphere and the romance between depp and ricci is unexpectedly tender.', null);  # 304862 Sleepy Hollow 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (97360, 7, 'hilinetz', 'ed wood is a really charming film about following your passion even when you fail. the friendship between ed and bela is touching.', null);  # 97360 Ed Wood 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256632, 9, 'hilinetz', 'pirates of the caribbean is so fun. johnny depp as jack sparrow is one of the most iconic performances and the romance between will and elizabeth is really sweet.', null);  # 256632 Pirates of the Caribbean: The Curse of the Black Pearl 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256631, 7, 'hilinetz', 'the second pirates is entertaining but a bit too long and complicated compared to the first one.', null);  # 256631 Pirates of the Caribbean 2 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139657, 10, 'hilinetz', 'harry potter sorcerers stone is pure childhood magic. every time i rewatch it i feel like a kid again.', null);  # 139657 Harry Potter and the Sorcerer''s Stone 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139650, 9, 'hilinetz', 'chamber of secrets is so creepy and exciting. the basilisk reveal genuinely scared me the first time i watched it as a kid.', null);  # 139650 Harry Potter and the Chamber of Secrets 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139655, 10, 'hilinetz', 'prisoner of azkaban is my favorite of the whole series. the time travel twist is so clever and the direction feels different and more artistic.', null);  # 139655 Harry Potter and the Prisoner of Azkaban 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139652, 8, 'hilinetz', 'goblet of fire gets so dark and exciting. the ending genuinely shocked me the first time and the triwizard tournament is so tense.', null);  # 139652 Harry Potter and the Goblet of Fire 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139654, 8, 'hilinetz', 'order of the phoenix is emotionally heavy but umbridge is such a perfectly hateable villain. the battle at the ministry is great.', null);  # 139654 Harry Potter and the Order of the Phoenix 2007
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139653, 9, 'hilinetz', 'half blood prince is so emotional and the dumbledore moments are beautiful. the ending is devastating but done really well.', null);  # 139653 Harry Potter and the Half-Blood Prince 2008
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (149287, 8, 'hilinetz', 'hook is such a feel good movie. robin williams is perfect and the idea of peter pan forgetting neverland is so creative.', null);  # 149287 Hook 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (190869, 9, 'hilinetz', 'lilo and stitch made me cry which i did not expect. the sister relationship is so real and the humor is actually really funny.', null);  # 190869 Lilo & Stitch 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (32180, 9, 'hilinetz', 'beauty and the beast is a classic for a reason. the romance is enchanting and the soundtrack is one of the best disney has ever made.', null);  # 32180 Beauty and the Beast 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (337166, 10, 'hilinetz', 'toy story is a childhood classic that still holds up completely. woody and buzz are iconic and the story is genuinely heartwarming.', null);  # 337166 Toy Story 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (70959, 8, 'hilinetz', 'corpse bride is visually stunning and the love story is actually really moving. tim burton at his best.', null);  # 70959 Corpse Bride, The 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (96593, 9, 'hilinetz', 'e.t. is one of the most emotional films ever made. cried as a kid and honestly still cry as an adult.', null);  # 96593 E.T. the Extra-Terrestrial 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (100130, 8, 'hilinetz', 'empire of the sun is really moving and young christian bale is an incredible actor. the war setting makes the emotional moments hit harder.', null);  # 100130 Empire of the Sun 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (12744, 8, 'hilinetz', 'always is such a romantic and bittersweet film. the fantasy element of the love story is really beautiful.', null);  # 12744 Always 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56871, 8, 'hilinetz', 'catch me if you can is so entertaining. leo dicaprio and tom hanks have a fascinating dynamic and the film never slows down.', null);  # 56871 Catch Me If You Can 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311037, 8, 'hilinetz', 'spider-man 2002 is such a great origin story. the romance with mary jane feels real and the uncle ben scene still gets me.', null);  # 311037 Spider-Man 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311038, 9, 'hilinetz', 'spider-man 2 is even better than the first. the train scene is iconic and the internal conflict makes peter parker so much more interesting.', null);  # 311038 Spider-Man 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311040, 6, 'hilinetz', 'spider-man 3 tries to do too much at once. the venom storyline had so much potential but got rushed and the emo peter parker is just awkward.', null);  # 311040 Spider-Man 3 2007
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238072, 8, 'hilinetz', 'ocean''s eleven is effortlessly cool. the whole ensemble works so well together and the heist is really clever.', null);  # 238072 Ocean's Eleven 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238073, 7, 'hilinetz', 'ocean''s twelve is entertaining but the plot gets a bit too convoluted and it loses some of the charm of the first film.', null);  # 238073 Ocean's Twelve 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (220805, 8, 'hilinetz', 'mr and mrs smith is so fun. the action and the romance are perfectly balanced and the chemistry between brad and angelina is undeniable.', null);  # 220805 Mr. and Mrs. Smith 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215876, 8, 'hilinetz', 'the original mission impossible has such a great twist in the middle. really tense and well constructed.', null);  # 215876 Mission: Impossible 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215879, 7, 'hilinetz', 'mission impossible 2 is a bit over the top but the action is exciting and tom cruise is as committed as ever.', null);  # 215879 Mission: Impossible II 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215880, 8, 'hilinetz', 'mission impossible 3 is really exciting and the villain is genuinely terrifying. probably the best of the first three.', null);  # 215880 Mission: Impossible III 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210739, 8, 'hilinetz', 'men in black is so fun and creative. will smith and tommy lee jones are a perfect comedy duo and the alien world is really inventive.', null);  # 210739 Men in Black 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (158999, 7, 'hilinetz', 'independence day is a classic blockbuster. it is loud and over the top but genuinely entertaining to watch with a group.', null);  # 158999 Independence Day 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (359297, 7, 'hilinetz', 'war of the worlds is really tense. the family dynamic makes it more emotional than your average alien film and the ending is satisfying.', null);  # 359297 War of the Worlds 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312150, 8, 'hilinetz', 'spy kids is so creative and fun. the whole concept of kid spies with gadgets is brilliant and the family dynamic is really sweet.', null);  # 312150 Spy Kids 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312151, 7, 'hilinetz', 'spy kids 2 is still fun but a bit less magical than the first one. still enjoyable though.', null);  # 312151 Spy Kids 2: Island of Lost Dreams 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312152, 5, 'hilinetz', 'spy kids 3 feels like it was made just to use the 3d gimmick. the story is the weakest of the three.', null);  # 312152 Spy Kids 3-D: Game Over 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (129185, 8, 'hilinetz', 'gladiator is so epic. the relationship between maximus and his family gives the action real emotional weight.', null);  # 129185 Gladiator 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194500, 9, 'hilinetz', 'return of the king is such an emotional ending. the grey havens scene completely wrecked me and the whole trilogy pays off perfectly.', null);  # 194500 Lord of the Rings: The Return of the King, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194497, 9, 'hilinetz', 'fellowship of the ring draws you into the world completely. the friendship between frodo and sam is the emotional heart of the whole story.', null);  # 194497 Lord of the Rings: The Fellowship of the Ring, The 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194502, 8, 'hilinetz', 'two towers has the best battle sequence in the trilogy. helm''s deep is incredible filmmaking even now.', null);  # 194502 Lord of the Rings: The Two Towers, The 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313478, 9, 'hilinetz', 'empire strikes back is the best star wars film. the han and leia romance and the vader reveal are both iconic moments.', null);  # 313478 Star Wars: Episode V - The Empire Strikes Back 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313479, 8, 'hilinetz', 'return of the jedi has such a satisfying ending. the ewoks get a lot of hate but they are actually cute.', null);  # 313479 Star Wars: Episode VI - Return of the Jedi 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313477, 8, 'hilinetz', 'revenge of the sith is surprisingly emotional. anakin''s fall is genuinely tragic and the final duel is spectacular.', null);  # 313477 Star Wars: Episode III - Revenge of the Sith 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313476, 6, 'hilinetz', 'attack of the clones has the anakin and padme romance which feels a bit forced but the action and the mystery plot are decent.', null);  # 313476 Star Wars: Episode II - Attack of the Clones 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313474, 6, 'hilinetz', 'phantom menace has some great moments like the pod racing and darth maul but jar jar binks is a lot to deal with.', null);  # 313474 Star Wars: Episode I - The Phantom Menace 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30959, 9, 'hilinetz', 'batman begins completely reinvented the superhero film. christian bale is the perfect bruce wayne and the origin story feels real and grounded.', null);  # 30959 Batman Begins 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30955, 7, 'hilinetz', 'the 1989 batman is a classic. michael keaton is iconic in the role and the gothic visual style is so cool.', null);  # 30955 Batman 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30967, 6, 'hilinetz', 'batman returns is quite dark and weird but michelle pfeiffer as catwoman is genuinely iconic and worth watching for that alone.', null);  # 30967 Batman Returns 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30965, 5, 'hilinetz', 'batman forever has its moments but it gets too campy and loses the tone of the first two films.', null);  # 30965 Batman Forever 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30952, 2, 'hilinetz', 'batman and robin is genuinely painful to watch. the ice puns never stop and nothing about it works.', null);  # 30952 Batman & Robin 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30976, 8, 'hilinetz', 'mask of the phantasm is surprisingly dark and emotional for an animated batman film. way better than i expected.', null);  # 30976 Batman: Mask of the Phantasm 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130945, 7, 'hilinetz', 'goldeneye is such a fun bond film. natalya is one of the most likeable bond partners and the action is exciting throughout.', null);  # 130945 GoldenEye 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (86263, 7, 'hilinetz', 'die another day is a bit too over the top but halle berry is great and some of the action set pieces are really impressive.', null);  # 86263 Die Another Day 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335336, 7, 'hilinetz', 'tomorrow never dies is a solid bond film. wai lin is one of the most capable and fun bond partners in the whole series.', null);  # 335336 Tomorrow Never Dies 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (368418, 7, 'hilinetz', 'world is not enough is entertaining with a good twist villain but the ending feels a bit flat.', null);  # 368418 World Is Not Enough, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120574, 6, 'hilinetz', 'from russia with love is one of the stronger older bond films. the spy thriller elements are genuinely tense and well constructed.', null);  # 120574 From Russia with Love 1963
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (117314, 6, 'hilinetz', 'for your eyes only is more grounded than most bond films which actually makes it more interesting.', null);  # 117314 For Your Eyes Only 1981
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (189403, 5, 'hilinetz', 'licence to kill is very dark for a bond film. it is well made but not really what i watch bond for.', null);  # 189403 Licence to Kill 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (192702, 6, 'hilinetz', 'living daylights has a fresh feel with timothy dalton and the action is solid even if it is not the most memorable bond film.', null);  # 192702 Living Daylights, The 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188507, 8, 'hilinetz', 'lethal weapon is such a great buddy action film. riggs and murtaugh have incredible chemistry and the emotional beats actually land.', null);  # 188507 Lethal Weapon 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188509, 8, 'hilinetz', 'lethal weapon 2 is as good as the first. the villain is memorable and the action is exciting without feeling too repetitive.', null);  # 188509 Lethal Weapon 2 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188510, 6, 'hilinetz', 'lethal weapon 3 is still enjoyable but starting to feel a bit formulaic. joe pesci is funny though.', null);  # 188510 Lethal Weapon 3 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188511, 5, 'hilinetz', 'lethal weapon 4 feels like it is running on fumes at this point. jet li saves it a little but it is clearly the weakest of the four.', null);  # 188511 Lethal Weapon 4 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (109421, 7, 'hilinetz', 'fast and furious is just fun. the cars, the action, the friendships between the characters all work together nicely.', null);  # 109421 Fast and the Furious, The 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159172, 9, 'hilinetz', 'last crusade is my favorite indiana jones by far. harrison ford and sean connery as father and son is comedy gold.', null);  # 159172 Indiana Jones and the Last Crusade 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159175, 7, 'hilinetz', 'temple of doom is darker and weirder but the mine cart scene and the energy of it make it really entertaining.', null);  # 159175 Indiana Jones and the Temple of Doom 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159167, 6, 'hilinetz', 'indiana jones 4 is fun to see again but the crystal skull storyline is so silly it takes you out of it.', null);  # 159167 Indiana Jones 4 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210511, 7, 'hilinetz', 'memento is so clever with the reverse timeline. i had to watch it twice to fully understand what was happening but it was worth it.', null);  # 210511 Memento 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (160524, 7, 'hilinetz', 'insomnia is a really gripping thriller. al pacino and robin williams together is such an unexpected pairing and it totally works.', null);  # 160524 Insomnia 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (116556, 6, 'hilinetz', 'following is impressive for such a low budget early film. you can already see nolan''s style developing and the twist is good.', null);  # 116556 Following 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (112290, 6, 'hilinetz', 'fight club is fascinating and the twist is genuinely shocking. not really my type of film but i understand why people love it.', null);  # 112290 Fight Club 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (123435, 7, 'hilinetz', 'the game is so tense and the twist completely blindsided me. a really well made thriller that keeps you guessing.', null);  # 123435 Game, The 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (247579, 6, 'hilinetz', 'panic room is tense and well made but very claustrophobic. jodie foster is excellent though and the direction is slick.', null);  # 247579 Panic Room 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (69812, 7, 'hilinetz', 'conspiracy theory is such a fun thriller. the romantic dynamic between mel gibson and julia roberts adds a lot to what could have been a generic story.', null);  # 69812 Conspiracy Theory 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (350424, 7, 'hilinetz', 'vanilla sky kept me guessing the whole time. it is confusing in places but the love triangle and the dreamlike atmosphere are really interesting.', null);  # 350424 Vanilla Sky 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (306032, 7, 'hilinetz', 'snatch is really funny and clever. the editing style is so fast and the way all the storylines connect is satisfying.', null);  # 306032 Snatch. 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131780, 6, 'hilinetz', 'goodfellas is undeniably brilliant but not really my genre. the storytelling and pacing are incredible though.', null);  # 131780 Goodfellas 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (8183, 7, 'hilinetz', 'age of innocence is such a beautiful and tragic love story. scorsese doing period romance is surprisingly stunning.', null);  # 8183 Age of Innocence, The 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56304, 5, 'hilinetz', 'casino is well made but too long and violent for my personal taste. not something i would rewatch.', null);  # 56304 Casino 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (31715, 8, 'hilinetz', 'beaches completely destroyed me emotionally. the friendship between the two women is so authentic and the ending is devastating.', null);  # 31715 Beaches 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (67395, 8, 'hilinetz', 'the color purple is such a powerful film. whoopi goldberg is magnificent and the story stays with you long after it ends.', null);  # 67395 Color Purple, The 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (34077, 8, 'hilinetz', 'benjamin button is so beautiful and melancholy. the love story across so many years is genuinely moving even if the film is quite long.', null);  # 34077 Benjamin Button 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (208245, 7, 'hilinetz', 'maverick is such a fun and charming film. mel gibson and jodie foster together are hilarious and the poker storyline keeps you entertained.', null);  # 208245 Maverick 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218219, 8, 'hilinetz', 'princess mononoke is stunning. the visuals are incredible and the story has a real depth to it that stays with you.', null);  # 218219 Mononoke-hime 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (174953, 8, 'hilinetz', 'nausicaa of the valley of the wind is so ahead of its time. the heroine is incredible and the world feels so richly imagined.', null);  # 174953 Kaze no tani no Naushika 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311428, 8, 'hilinetz', 'splash is such a sweet and funny love story. daryl hannah as a mermaid is completely charming and the romance is genuinely cute.', null);  # 311428 Splash 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46169, 7, 'hilinetz', 'braveheart is really emotional and the love story with murron is so tragically short. the battle sequences are intense.', null);  # 46169 Braveheart 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (340652, 7, 'hilinetz', 'troy is epic and the paris and helen love story drives everything. it is a bit long but the performances are really engaging.', null);  # 340652 Troy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (308025, 7, 'hilinetz', 'someone to watch over me is a really romantic thriller. the choice between two very different women feels emotionally real.', null);  # 308025 Someone to Watch Over Me 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (69469, 8, 'hilinetz', 'intimate strangers is such an intriguing and romantic french film. the tension between the two characters builds so slowly and beautifully.', null);  # 69469 Confidences trop intimes 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (33492, 8, 'hilinetz', 'bella martha is a really sweet romance about two completely different people slowly falling for each other. really charming.', null);  # 33492 Bella Martha 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56282, 7, 'hilinetz', 'cashback is such a creative and romantic film. the whole concept of freezing time to appreciate beauty is really original.', null);  # 56282 Cashback 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (244421, 7, 'hilinetz', 'the other sister is such a touching film. the love story is really sweet and the performances feel very genuine.', null);  # 244421 Other Sister, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (235615, 7, 'hilinetz', 'nothing in common is really sweet and underrated. the father son relationship is the real heart of the film and tom hanks is great.', null);  # 235615 Nothing in Common 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (263, 7, 'hilinetz', 'til there was you is such a sweet concept. two people whose lives keep almost intersecting is a really romantic idea.', null);  # 263 'Til There Was You 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (183370, 8, 'hilinetz', 'ladies in lavender is quietly beautiful. the performances are really moving and the bittersweet ending stayed with me.', null);  # 183370 Ladies in Lavender 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185628, 7, 'hilinetz', 'last samurai has a surprising amount of emotional depth. the romance and the cultural clash both work really well together.', null);  # 185628 Last Samurai, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335835, 7, 'hilinetz', 'top gun is a classic. the romance and the action are both entertaining and the soundtrack is iconic.', null);  # 335835 Top Gun 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (14132, 7, 'hilinetz', 'american pie 2 is honestly funnier than the first one. the whole summer house concept works really well.', null);  # 14132 American Pie 2 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (105851, 5, 'hilinetz', 'exit to eden is a weird romantic comedy that never quite figures out what it wants to be. dan aykroyd and rosie o''donnell are funny but the tone is all over the place.', null);  # 105851 Exit to Eden 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (199763, 7, 'hilinetz', 'madonna immaculate collection is basically a perfect greatest hits package. the videos are iconic and hold up really well.', null);  # 199763 Madonna: The Immaculate Collection 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (3055, 6, 'hilinetz', 'the 76th academy awards was a memorable ceremony. watching lord of the rings sweep everything was so satisfying.', null);  # 3055 76th Annual Academy Awards, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (25192, 7, 'hilinetz', 'the aviator is quite long but really fascinating. leo dicaprio carries the whole film and the obsessive behavior is genuinely compelling.', null);  # 25192 Aviator, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (14477, 7, 'hilinetz', 'amistad is really powerful and important. spielberg handles the subject carefully and the performances are strong throughout.', null);  # 14477 Amistad 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10702, 7, 'hilinetz', 'alice doesn''t live here anymore is a really charming story about a woman starting her life over. really ahead of its time.', null);  # 10702 Alice Doesn't Live Here Anymore 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (67388, 6, 'hilinetz', 'color of money is a solid sequel. newman and cruise together are interesting to watch even if the story is not as strong as the hustler.', null);  # 67388 Color of Money, The 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (253010, 7, 'hilinetz', 'a perfect world is really touching. kevin costner and the kid have such a sweet unlikely bond and the ending is really emotional.', null);  # 253010 Perfect World, A 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (65811, 8, 'hilinetz', 'close encounters is such a classic. the buildup and the final scene with the alien ship are genuinely awe inspiring.', null);  # 65811 Close Encounters of the Third Kind 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (94741, 6, 'hilinetz', 'duel is impressive for an early spielberg tv film. the concept of being hunted by a truck is absurd but genuinely effective.', null);  # 94741 Duel (1971/I) 1971
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (21213, 7, 'hilinetz', 'a.i. is emotional and thought provoking. the ending got to me in a way i did not expect and the visuals are stunning.', null);  # 21213 Artificial Intelligence: AI 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (214755, 7, 'hilinetz', 'minority report is really gripping. the futuristic world feels believable and the twist is satisfying without feeling cheap.', null);  # 214755 Minority Report 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (319602, 7, 'hilinetz', 'superman 1978 is such a charming classic. christopher reeve is the most likeable superhero and the romance with lois is really sweet.', null);  # 319602 Superman 1978
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (319613, 7, 'hilinetz', 'superman 2 is even more fun. clark giving up his powers for lois is genuinely romantic and the story has real emotional stakes.', null);  # 319613 Superman II 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (400853, 8, 'hilinetz', 'parenthood is so real and moving. the ensemble family dynamics are completely authentic and it made me think about my own family.', null);  # 400853 Parenthood 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (390691, 7, 'hilinetz', 'growing pains is such a warm and nostalgic family show. the teen storylines feel really relatable even now.', null);  # 390691 Growing Pains 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (391006, 7, 'hilinetz', 'happy days is so nostalgic and warm. the friendships and the romances between the characters are genuinely sweet.', null);  # 391006 Happy Days 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (398232, 8, 'hilinetz', 'mork and mindy is so sweet. the alien falling in love with a human concept is so charming and robin williams is electric.', null);  # 398232 Mork & Mindy 1978
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (398571, 7, 'hilinetz', 'murphy brown is really smart and funny. candice bergen is hilarious and the show is surprisingly ahead of its time.', null);  # 398571 Murphy Brown 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131885, 8, 'hilinetz', 'the goonies is such a classic adventure film. the friendship between all the kids is so fun and the whole treasure hunt is genuinely exciting.', null);  # 131885 Goonies, The 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (379931, 6, 'hilinetz', 'amazing stories has some really touching and creative episodes. the spielberg influence gives it a warmth that most anthology shows lack.', null);  # 379931 Amazing Stories 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (372733, 7, 'hilinetz', 'young sherlock holmes is a fun adventure and the romance adds a really nice emotional layer to the whole mystery.', null);  # 372733 Young Sherlock Holmes 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (142491, 7, 'hilinetz', 'hellboy is a really fun supernatural action film. the liz and hellboy romance is surprisingly sweet and gives it real heart.', null);  # 142491 Hellboy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (142492, 7, 'hilinetz', 'hellboy 2 is even more visually stunning than the first. the romance between hellboy and liz becomes more central and emotional here.', null);  # 142492 Hellboy 2 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46190, 6, 'hilinetz', 'the bravo profile on johnny depp is a fun and interesting look at his career and personality. good watch for fans.', null);  # 46190 Bravo Profiles: Johnny Depp 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (102108, 6, 'hilinetz', 'epic at sea is a fun behind the scenes documentary for fans of pirates of the caribbean. interesting to see how the action was made.', null);  # 102108 Epic at Sea: The Making of 'Pirates of the Caribbean: The Curse of the Black Pearl', An 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256627, 6, 'hilinetz', 'pirates of silicon valley is really interesting. the jobs versus gates rivalry is fascinating and the two actors are well cast.', null);  # 256627 Pirates of Silicon Valley 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (248090, 7, 'hilinetz', 'paper clips is such a moving documentary about a school project that grew into something much bigger. really inspiring.', null);  # 248090 Paper Clips 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (114955, 7, 'hilinetz', 'the flamingo kid is such a charming coming of age film. the summer romance feels very real and the ending is satisfying.', null);  # 114955 Flamingo Kid, The 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (61751, 7, 'hilinetz', 'children of men is really gripping and emotional. the long unbroken takes are incredible filmmaking and the world feels terrifyingly real.', null);  # 61751 Children of Men, The 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (49854, 5, 'hilinetz', 'buried secret of m night shyamalan is a clever mockumentary. it is fun if you know his films but probably confusing otherwise.', null);  # 49854 Buried Secret of M. Night Shyamalan, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (80969, 7, 'hilinetz', 'dear god is such a cute and funny film. the concept of answering letters to god is charming and greg kinnear is likeable.', null);  # 80969 Dear God 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (113931, 6, 'hilinetz', 'firelight is a classic romantic thriller that is actually quite underrated. the twist is good and the atmosphere is effective.', null);  # 113931 Firelight 1964
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30686, 5, 'hilinetz', 'basketball diaries is really powerful and leo dicaprio is incredible but it is very dark and not something i would rewatch easily.', null);  # 30686 Basketball Diaries, The 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (41518, 5, 'hilinetz', 'blow is well made and leo is good but it is just too dark and bleak for me personally.', null);  # 41518 Blow 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (54209, 4, 'hilinetz', 'cape fear is well made but genuinely frightening in an unpleasant way. de niro is terrifying but not my genre at all.', null);  # 54209 Cape Fear 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (200521, 6, 'hilinetz', 'magnolia is impressive and ambitious but almost three hours long and very intense. the frog scene is completely unforgettable though.', null);  # 200521 Magnolia 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10830, 4, 'hilinetz', 'alien is a masterpiece of tension but too scary for me. i had to look away multiple times and it genuinely gave me nightmares.', null);  # 10830 Alien 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10920, 5, 'hilinetz', 'aliens is more action focused which makes it a bit easier to watch than the first but still quite scary for my taste.', null);  # 10920 Aliens 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (259826, 4, 'hilinetz', 'poltergeist is really effective horror but too scary for me. the clown doll scene traumatized me as a kid.', null);  # 259826 Poltergeist 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (240327, 3, 'hilinetz', 'the omen is a classic horror but genuinely disturbing. not my genre and i found it hard to enjoy even objectively.', null);  # 240327 Omen, The 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120506, 4, 'hilinetz', 'from hell is atmospheric and interesting but too dark and gory for me. the ripper story is compelling but the violence is too much.', null);  # 120506 From Hell 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (233058, 5, 'hilinetz', 'the ninth gate has a great atmosphere and johnny depp is good but the ending is anticlimactic and left me feeling unsatisfied.', null);  # 233058 Ninth Gate, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (44238, 2, 'hilinetz', 'bordello of blood is really bad. it is supposed to be a fun horror comedy but it is neither funny nor scary.', null);  # 44238 Bordello of Blood 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (198835, 2, 'hilinetz', 'macabre pair of shorts is genuinely unpleasant to watch. not my thing at all.', null);  # 198835 Macabre Pair of Shorts 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176711, 4, 'hilinetz', 'kill bill is impressive stylistically but way too violent for my taste. the action choreography is cool but i spent half the film looking away.', null);  # 176711 Kill Bill: Vol. 1 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176712, 5, 'hilinetz', 'kill bill vol 2 is slower and more emotional which i preferred. the ending is actually really satisfying and less gory than the first.', null);  # 176712 Kill Bill: Vol. 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (123849, 6, 'hilinetz', 'gangs of new york is intense and epic but a bit too long and violent for my usual taste. the production design is incredible though.', null);  # 123849 Gangs of New York 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185704, 4, 'hilinetz', 'last temptation of christ is thought provoking but very difficult and uncomfortable to watch. not something i would revisit.', null);  # 185704 Last Temptation of Christ, The 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (209158, 4, 'hilinetz', 'mean streets is historically important but quite rough and violent. not really my genre even though i can see it is well made.', null);  # 209158 Mean Streets 1973
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (45312, 3, 'hilinetz', 'boxcar bertha is very early scorsese and it shows. too rough and exploitative for my taste.', null);  # 45312 Boxcar Bertha 1972
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (85871, 4, 'hilinetz', 'diamonds are forever feels quite dated now. the humor and the bond girl treatment have not aged well at all.', null);  # 85871 Diamonds Are Forever 1971
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (92573, 5, 'hilinetz', 'dr no is where it all started so it is worth watching but it feels very dated compared to modern films.', null);  # 92573 Dr. No 1962
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (192514, 5, 'hilinetz', 'live and let die has an interesting voodoo theme but some of the racial elements feel quite uncomfortable now.', null);  # 192514 Live and Let Die 1973
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (203649, 4, 'hilinetz', 'man with the golden gun is one of the weaker bond films. the villain is memorable but the story feels very thin.', null);  # 203649 Man with the Golden Gun, The 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218808, 4, 'hilinetz', 'moonraker is so ridiculous that it becomes almost unwatchable. going to space in a bond film was a step too far.', null);  # 218808 Moonraker 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312170, 6, 'hilinetz', 'the spy who loved me is one of the better older bond films. anya is a strong female lead and the underwater base is iconic.', null);  # 312170 Spy Who Loved Me, The 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (240521, 4, 'hilinetz', 'on her majesty''s secret service suffers from the recasting of bond. george lazenby is not very convincing and the pacing is slow.', null);  # 240521 On Her Majesty's Secret Service 1969
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (372233, 4, 'hilinetz', 'you only live twice feels quite dated now. the japanese setting is interesting but the story is too formulaic even for bond.', null);  # 372233 You Only Live Twice 1967
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (29768, 2, 'hilinetz', 'this 1904 film is only of historical interest. there is no real story and it is difficult to engage with as a modern viewer.', null);  # 29768 Barbier de Sville, Le 1904
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (29771, 4, 'hilinetz', 'this opera recording is very niche. beautiful music but not really what i look for in a film.', null);  # 29771 Barbier de Sville, Le 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (29772, 4, 'hilinetz', 'another opera adaptation that is pleasant but very specialized. only really for opera fans.', null);  # 29772 Barbier von Sevilla, Der 1972
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (29773, 4, 'hilinetz', 'le barbier is a short french film that is charming enough but too brief to be memorable.', null);  # 29773 Barbier, Le (2001/I) 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (78877, 3, 'hilinetz', 'dark mist is too vague and abstract to be engaging. the title is more interesting than the actual content.', null);  # 78877 Dark Mist, The 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (85524, 2, 'hilinetz', 'this 1941 portuguese film is only of historical interest. no real story that a modern viewer can connect with.', null);  # 85524 Dia  Nosso, O 1941
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (82868, 3, 'hilinetz', 'this german documentary is very culturally specific and hard to engage with without relevant background knowledge.', null);  # 82868 Denk ich an Deutschland - Wir haben vergessen zurckzukehren 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (78702, 3, 'hilinetz', 'dari jemapoh ke manchestee is a malay film that i could not really connect with. the humor is very culturally specific.', null);  # 78702 Dari Jemapoh ke Manchestee 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (126792, 3, 'hilinetz', 'this korean film is too slow and understated for my taste. i appreciate the style but it does not hold my attention.', null);  # 126792 Geudeulmanui sesang 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (70507, 3, 'hilinetz', 'copi je t''aime is a french documentary that is very niche and hard to appreciate without knowing the subject.', null);  # 70507 Copi, je t'aime 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (25729, 2, 'hilinetz', 'this 1968 turkish film is very obscure and the story does not translate well for modern international audiences.', null);  # 25729 Azrail benim 1968
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (25943, 3, 'hilinetz', 'baan sau chuk dak hin dui is a cantonese film that i could not follow at all without subtitles. not accessible for me.', null);  # 25943 Baan sau chuk dak hin dui 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (28085, 3, 'hilinetz', 'this filipino film is too culturally specific. the humor and the references did not land for me at all.', null);  # 28085 Bakit may kahapon pa? 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (28092, 3, 'hilinetz', 'bakom jalusin is a swedish film that is too slow and quiet for my taste. not much happens and the pacing is very difficult.', null);  # 28092 Bakom jalusin 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (36426, 3, 'hilinetz', 'this chinese film from 1984 has beautiful visuals but the pacing is too slow and the story is hard to follow.', null);  # 36426 Bian cheng 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (57894, 3, 'hilinetz', 'this french film is very meta and cinematic but too intellectual and slow for my personal taste.', null);  # 57894 Cent et une nuits de Simon Cinma, Les 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (64230, 3, 'hilinetz', 'this french documentary is very academic and dry. interesting subject matter but not engaging as a film experience.', null);  # 64230 Cinquantenaire du deuxime sexe, 1949-1999 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (67592, 5, 'hilinetz', 'columbo murder by the book is a decent early episode of the series. the formula works even here at the very beginning.', null);  # 67592 Columbo: Murder by the Book 1971
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (89441, 4, 'hilinetz', 'doki doki is a japanese short film that is quite abstract and hard to follow without cultural context.', null);  # 89441 Doki-Doki 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (89823, 3, 'hilinetz', 'le domaine is a slow french short that is too minimalist to hold my attention.', null);  # 89823 Domaine, Le 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (96239, 3, 'hilinetz', 'this french film is quite dated and the humor does not really translate to a modern audience.', null);  # 96239 Dtachez vos ceintures 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (99875, 3, 'hilinetz', 'emigranti is a slovenian film that is too culturally specific and hard to engage with as an outside viewer.', null);  # 99875 Emigranti (2002/I) 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (100241, 3, 'hilinetz', 'en attendant la cigogne is a french film that is charming in concept but too slow and understated to be engaging.', null);  # 100241 En attendant la cigogne 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (102311, 3, 'hilinetz', 'era outra vez is a portuguese film that is too quiet and slow for my taste. the story does not build to anything satisfying.', null);  # 102311 Era outra vez 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (104484, 3, 'hilinetz', 'eu adam is an israeli film i had trouble connecting with. the humor is very local and the pacing is uneven.', null);  # 104484 Eu Adam 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (105587, 3, 'hilinetz', 'examen is a romanian short that is too bleak and slow to be enjoyable. the subject is interesting but the execution is not engaging.', null);  # 105587 Examen 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (111963, 3, 'hilinetz', 'this 1979 opera recording is beautiful musically but as a film experience it is very dry and only for opera enthusiasts.', null);  # 111963 Fidelio 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (117582, 2, 'hilinetz', 'foreigners out is a provocative documentary that is more uncomfortable than enlightening. not something i enjoyed watching.', null);  # 117582 Foreigners out! Schlingensiefs Container 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (121912, 2, 'hilinetz', 'this 1921 silent short is only of historical interest. there is no real story and the humor does not land for modern viewers.', null);  # 121912 Fur Coats and Pants 1921
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (122277, 4, 'hilinetz', 'fyrsti april is an icelandic short film that is mildly amusing but too culturally specific to be really engaging.', null);  # 122277 Fyrsti aprl 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (129042, 3, 'hilinetz', 'this verdi requiem recording is a beautiful piece of music but as a film experience it is very dry and niche.', null);  # 129042 Giuseppe Verdi: Messa da Requiem 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (141779, 3, 'hilinetz', 'the berlioz te deum is an impressive classical performance but as a film it is very dry and only for classical music fans.', null);  # 141779 Hector Berlioz: Te Deum 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (175872, 3, 'hilinetz', 'this khachaturian documentary is pleasant for classical music fans but too academic for general audiences.', null);  # 175872 Khachaturian 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (175873, 4, 'hilinetz', 'the khachaturian piano concerto performance is really dramatic and beautiful. more engaging than a typical classical recording.', null);  # 175873 Khachaturian Piano Concerto 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (175875, 2, 'hilinetz', 'this 1951 film is very obscure and impossible to find any information about. could not really evaluate it properly.', null);  # 175875 Khadaini abi 1951
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (175879, 4, 'hilinetz', 'khadgam is a telugu action film that is entertaining but the story is very predictable and the romance feels rushed.', null);  # 175879 Khadgam 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (175880, 2, 'hilinetz', 'this 1952 egyptian film is too obscure and culturally specific for me to engage with meaningfully.', null);  # 175880 Khadra wa Sindibad el khebli 1952
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (175881, 3, 'hilinetz', 'this soviet tolstoy adaptation is beautifully shot but very slow. the pacing is really difficult for modern viewers.', null);  # 175881 Khadzhi murat 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (175883, 2, 'hilinetz', 'this 1990 iranian film is very culturally specific and the story did not translate at all for me.', null);  # 175883 Khagher 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (20446, 1, 'hilinetz', 'this 1898 film is purely a historical document. there is nothing to watch as a modern viewer looking for a film experience.', null);  # 20446 Armenian Archbishop, Rome 1898
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (17370, 2, 'hilinetz', 'this 1948 indian film is too old and culturally specific for me to connect with at all.', null);  # 17370 Anjangarh (1948/II) 1948
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (22093, 2, 'hilinetz', 'this 1977 marathi film is very obscure and i could not engage with the story or the characters at all.', null);  # 22093 Asla Navra Nakoga Bai 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (15187, 4, 'hilinetz', 'amsterdamned is a dutch thriller that is decent but a bit dated. the amsterdam canal setting is cool though.', null);  # 15187 Amsterdamned 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (31256, 3, 'hilinetz', 'battle squad is a very dated 1961 war film that has not aged well at all. feels very formulaic.', null);  # 31256 Battle Squad 1961
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (34304, 3, 'hilinetz', 'berlin babylon is a very slow documentary about berlin that is too minimalist and abstract for my taste.', null);  # 34304 Berlin Babylon 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (34306, 4, 'hilinetz', 'berlin berlin is a german comedy that has some funny moments but the humor is very specific and does not always translate.', null);  # 34306 Berlin Berlin 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (47456, 2, 'hilinetz', 'the broken coin is a 1915 silent serial that is only of historical interest. impossible to engage with as entertainment today.', null);  # 47456 Broken Coin, The 1915
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (51413, 3, 'hilinetz', 'c''est le vent is a quiet french short that is too slow and minimal to keep my attention.', null);  # 51413 C'est le vent 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (58084, 3, 'hilinetz', 'cerebrium is an experimental short that is too abstract and hard to follow even for a short film.', null);  # 58084 Cerebrium 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (60408, 3, 'hilinetz', 'chek 2000 is a very obscure short film without much to recommend it to a general audience.', null);  # 60408 Chek 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (65762, 4, 'hilinetz', 'clockwork maury is a short parody that has some funny ideas but wears out its welcome pretty quickly.', null);  # 65762 Clockwork Maury, A 2000

