insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46878, 7, 'Lior', 'The awkward situations and Bridget’s romantic struggles are relatable, even if it is not as strong as the first movie.', null);  -- Bridget Jones: The Edge of Reason 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (66194, 9, 'Lior', 'The light romantic storyline and Cher’s character make it fun, easy to watch, and very memorable.', null);  -- Clueless 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (59578, 9, 'Lior', 'The magical world and Charlie’s relationship with his family make it emotional and enjoyable.', null);  -- Charlie and the Chocolate Factory 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139657, 8, 'Lior', 'The introduction to the magical world and the friendships make it very engaging and nostalgic.', null);  -- Harry Potter and the Sorcerer''s Stne 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139650, 8, 'Lior', 'The stronger mystery and darker tone make it more interesting while still keeping the emotional connections.', null);  -- Harry Potter and the Chamber of Secrets 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139655, 9, 'Lior', 'The time-travel element and deeper character development make it one of the most engaging in the series.', null);  -- Harry Potter and the Prisoner of Azkaban 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139652, 8, 'Lior', 'The emotional stakes and relationships become stronger, even though it is more intense.', null);  -- Harry Potter and the Goblet of Fire 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30959, 4, 'Lior', 'The darker superhero tone and focus on action make it less appealing to me compared to emotional stories.', null);  -- Batman Begins 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30955, 4, 'Lior', 'The visual style is strong, but the superhero focus and lack of emotional connection make it less engaging for me.', null);  -- Batman 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30967, 4, 'Lior', 'Even with memorable characters, the dark and action-heavy tone is not really my style.', null);  -- Batman Returns 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (25192, 7, 'Lior', 'The personal struggles and ambition make it interesting, though it feels more serious than emotional.', null);  -- The Aviator 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56871, 10, 'Lior', 'The cat-and-mouse dynamic and the charm of the main character make it very fun and engaging.', null);  -- Catch Me If You Can 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (34077, 10, 'Lior', 'This is one of my all time favorites! The unique life story and the emotional relationship make it very touching and memorable.', null);  -- The Curious Case of Benjamn Button
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (129185, 7, 'Lior', 'The emotional motivation of Maximus makes the story stronger.', null);  -- Gladiator 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312150, 10, 'Lior', 'I really enjoy Spy Kids because it is imaginative, family-friendly, and adventurous without feeling too heavy or violent.', null);  # 312150 Spy Kids 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (199763, 6, 'Lior', 'It is interesting to see Madonna’s music videos, but it feels more like a collection than a story.', null);  # Madonna: The Immaculate Collection 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (199764, 6, 'Lior', 'The different eras of Madonna’s style are interesting, but it is less engaging than a narrative film.', null);  # Madonna: The Video Collection 93:99 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (192514, 5, 'Lior', 'The spy theme and action scenes are not really my preference compared to romantic or emotional films.', null);  # Live and Let Die 1973
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194492, 6, 'Lior', 'The fantasy world and characters are interesting.', null);  # Lord of the Rings 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (190677, 6, 'Lior', 'The story about relationships and identity is interesting, but it is not very memorable.', null);  # Like a Lady 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (192850, 6, 'Lior', 'The coming-of-age elements are relatable, but the story feels quite simple.', null);  # Lizzie 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194313, 6, 'Lior', 'The character-focused story is interesting, but it feels less emotional than I usually prefer.', null);  # Looking Out 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215875, 3, 'Lior', 'I am less connected to action and spy movies, and this kind of fast-paced mission plot is not usually my favorite.', null);  # 215875 Mission: Impossible 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (220276, 9, 'Lior', 'I loved the music, the romance, and the dramatic atmosphere, and the film feels very emotional.', null);  # 220276 Moulin Rouge! 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (220805, 9, 'Lior', 'The chemistry between the leads is entertaining, I love Brad Pitt and Angelina Jolie', null);  # 220805 Mr. and Mrs. Smith 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (263360, 10, 'Lior', 'I love this movie! iconic scenes and the best actors- Richard Gere and Julia Roberts, the story is charming', null);  # 263360 Pretty Woman 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (290070, 9, 'Lior', 'This is a deeply powerful and emotional historical film, and I appreciated how meaningful and unforgettable the story is.', null);  # 290070 Schindler's List 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300229, 10, 'Lior', 'I love the humor, the lovable characters, and the way the movie works as both a funny children''s film and a clever story for adults.', null);  # 300229 Shrek 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300230, 9, 'Lior', 'A very fun sequel with great humor, memorable side characters, and an entertaining fairy-tale world. I also like the music', null);  # 300230 Shrek 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300233, 7, 'Lior', 'I like the Shrek world and the characters, so this is still enjoyable, even though it feels smaller than the main films.', null);  # 300233 Shrek 4-D 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311036, 4, 'Lior', 'Superhero action movies are usually not my favorite, and although Spider-Man is iconic, this genre is less enjoyable for me.', null);  # 311036 Spider-Man 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311604, 8, 'Lior', 'I enjoy SpongeBob because it is silly, colorful, and fun, and reminds me of my childhood', null);  # 311604 SpongeBob SquarePants: Legend of the Lost Spatula 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311606, 8, 'Lior', 'This is fun and light, and I like the humorous SpongeBob style and the familiar characters.', null);  # 311606 SpongeBob SquarePants: Revenge of the Flying Dutchman 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311607, 8, 'Lior', 'I like the playful humor and the cheerful atmosphere, and SpongeBob is always entertaining in a simple and nostalgic way.', null);  # 311607 SpongeBob SquarePants: SuperSponge 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312151, 9, 'Lior', 'A very fun sequel with creative settings and a playful adventure style that makes it enjoyable as a family movie.', null);  # 312151 Spy Kids 2: Island of Lost Dreams 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312152, 8, 'Lior', 'Still entertaining and imaginative', null);  # 312152 Spy Kids 3-D: Game Over 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313464, 2, 'Lior', 'This is exactly the kind of action-driven science fiction title I usually do not connect with very much.', null);  # 313464 Star Wars Rogue Leader: Rogue Squadron 2 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (319602, 4, 'Lior', 'I understand why this is a classic superhero movie, but superhero and action films are generally not my personal preference.', null);  # 319602 Superman 1978
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (319613, 3, 'Lior', 'Like other superhero sequels, this is less aligned with my taste, I find it boring', null);  # 319613 Superman II 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (333856, 10, 'Lior', 'I love the romance, the emotional story, and the tragic scale of the film, and it is one of the most memorable love stories, also amazing music', null);  # 333856 Titanic 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (333849, 6, 'Lior', 'I find the Titanic story itself interesting and emotional, although this older version is less engaging to me than the later adaptation.', null);  # 333849 Titanic 1915
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (337166, 10, 'Lior', 'I love Toy Story because it is warm, imaginative, funny, and emotionally meaningful for both children and adults.', null);  # 337166 Toy Story 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (340652, 4, 'Lior', 'The historical setting is interesting, but because the film is centered on war and action, it is not really my kind of movie.', null);  # 340652 Troy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (644, 9, 'Lior', 'I really liked the enemies-to-lovers dynamic between Kat and Patrick, and the high school setting with witty dialogue makes it fun and memorable.', null);  # 10 Things I Hate About You 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (849, 9, 'Lior', 'I enjoy family animations like this, especially the cute puppies and the light adventure story set in London.', null);  # 101 Dalmatians II: Patch's London Adventure 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (850, 8, 'Lior', 'The songs and familiar characters make it fun and nostalgic, especially as a light family movie.', null);  # 101 Dalmatians Sing Along 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (837, 7, 'Lior', 'I like the fairy-tale structure and imaginative setting, which makes it enjoyable.', null);  # 1001 Nights 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (359297, 6, 'Lior', 'The story of a family trying to survive during an alien invasion is interesting, but the focus on action and tension makes it less engaging for me.', null);  # War of the Worlds 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (360667, 7, 'Lior', 'The wedding theme and relationship focus make it more appealing, and I enjoy stories built around love and commitment.', null);  # Wedding Advice: Speak Now or Forever Hold Your Peace 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (366967, 7, 'Lior', 'A beautiful relationship-focused story that explores emotional connection and loss.', null);  # Without You 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (372733, 8, 'Lior', 'I like the mix of mystery and adventure, especially seeing a younger version of Sherlock Holmes and how his character develops.', null);  # Young Sherlock Holmes 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (350424, 8, 'Lior', 'The mix of romance and mystery is interesting, especially the relationship with Sofia and the dream-like twist.', null);  # Vanilla Sky 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (336445, 7, 'Lior', 'The intense relationship between Rimbaud and Verlaine is emotional and dramatic, which makes it interesting to watch.', null);  # Total Eclipse 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (342797, 6, 'Lior', 'A simple romantic-style story that focuses on connection between characters, though it is not very memorable.', null);  # Two Days with Juliet 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (328272, 9, 'Lior', 'I liked the story of Viktor being stuck in the airport and his relationship with Amelia, which adds a warm romantic element.', null);  # Terminal, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (330670, 8, 'Lior', 'The emotional story of growing up and the complicated relationship with the stepfather makes it very engaging.', null);  # This Boy's Life 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (326155, 6, 'Lior', 'The character of Travis is interesting, but the dark tone and loneliness make it less enjoyable for me.', null);  # Taxi Driver 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (329880, 7, 'Lior', 'I like the mystery of people disappearing one by one, which keeps the story interesting and engaging.', null);  # Then There Were None 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (297838, 10, 'Lior', 'I really liked the friendship between Andy and Red and the hopeful ending after all the struggle makes it very emotional.', null);  # Shawshank Redemption, The 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (113506, 10, 'Lior', 'I loved the emotional story behind Peter Pan and the connection between J.M. Barrie and the children.', null);  # Finding Neverland 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (118980, 8, 'Lior', 'The slow-building romance between Frankie and Johnny feels real and very character-driven.', null);  # Frankie and Johnny 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (118367, 7, 'Lior', 'The hotel setting and the different quirky stories make it fun and unpredictable to watch.', null);  # Four Rooms 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (123435, 8, 'Lior', 'The mystery of the game controlling the main character’s life keeps the story tense and surprising.', null);  # The Game 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (123849, 7, 'Lior', 'The historical setting and rivalry are interesting, though it feels more intense than I usually prefer.', null);  # Gangs of New York 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130945, 6, 'Lior', 'The Bond adventure is entertaining, but still focuses heavily on action and missions.', null);  # GoldenEye 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120506, 6, 'Lior', 'The Jack the Ripper investigation is interesting, but the dark tone makes it less enjoyable for me.', null);  # From Hell 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (116556, 7, 'Lior', 'The simple black-and-white style and the idea of following strangers create an interesting tension.', null);  # Following 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (114955, 7, 'Lior', 'The coming-of-age story and summer atmosphere make it feel light and relatable.', null);  # Flamingo Kid 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (123371, 6, 'Lior', 'The sports theme is engaging, but it feels more straightforward and less emotional.', null);  # Game Day 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (283410, 9, 'Lior', 'I liked the chemistry between Julia Roberts and Richard Gere and the idea of a woman afraid of commitment adds a fun romantic tension.', null);  # Runaway Bride 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (271344, 8, 'Lior', 'The story of Helen suddenly becoming responsible for her nieces and nephew is emotional and shows her personal growth.', null);  # Raising Helen 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (270628, 7, 'Lior', 'The friendship between the two brothers and their imaginative escape story makes it emotional and touching.', null);  # Radio Flyer 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (271095, 8, 'Lior', 'The adventure of Indiana Jones searching for the Ark is exciting, and the character is very charismatic and fun to watch.', null);  # Raiders of the Lost Ark 1981
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280270, 7, 'Lior', 'I liked the underdog story of Rocky training for the fight and his relationship with Adrian adds a softer emotional side.', null);  # Rocky 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (264157, 9, 'Lior', 'I enjoy the transformation of Mia into a princess and the light romantic storyline with Nicholas makes it fun and charming.', null);  # Princess Diaries 2: Royal Engagement 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256632, 8, 'Lior', 'Captain Jack Sparrow is a very fun character, and the mix of adventure and humor makes it entertaining even if it is action-based.', null);  # Pirates of the Caribbean: The Curse of the Black Pearl 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (257744, 8, 'Lior', 'I like how the film follows several couples and shows different types of love and relationships in a connected way.', null);  # Playing by Heart 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (253010, 7, 'Lior', 'The bond between the escaped prisoner and the young boy is emotional and adds depth beyond the crime storyline.', null);  # A Perfect World 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (191246, 10, 'Lior', 'The music id to die for and the story is charming.', NULL); -- 191246 Lion King, The (1994)
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238072, 8, 'Lior', 'I enjoyed the clever casino heist plan and the chemistry between the team, which makes it fun to follow.', null);  # Ocean's Eleven 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238073, 7, 'Lior', 'Still entertaining with the same characters, but the storyline feels more complicated and less engaging.', null);  # Ocean's Twelve 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (233058, 6, 'Lior', 'The mystery around rare books and the Devil is interesting', null);  # The Ninth Gate 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (235615, 7, 'Lior', 'The relationship between the father and son feels real and emotional, especially as they reconnect later in life.', null);  # Nothing in Common 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (230947, 7, 'Lior', 'I liked seeing different stories set in New York, each with its own tone and perspective.', null);  # New York Stories 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (244421, 8, 'Lior', 'The love story between the two sisters is sweet and emotional, especially seeing personal growth and independence.', null);  # The Other Sister 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (245699, 9, 'Lior', 'I like the funny dynamic between the actors, and how their relationship slowly turns into real love.', null);  # Overboard 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (247579, 7, 'Lior', 'The tension of being trapped inside the house is strong, but it is more suspenseful than emotional.', null);  # Panic Room 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (242530, 6, 'Lior', 'The outdoor adventure setting is nice, but it feels more like a simple story without strong emotional depth.', null);  # Open Season 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (208245, 7, 'Lior', 'The poker scenes and the dinamif make it light and entertaining.', null);  # Maverick 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210511, 7, 'Lior', 'The reversed timeline and Leonard''s memory condition make the story unique, though it feels more intellectual than emotional.', null);  # Memento 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210739, 8, 'Lior', 'The chemistry between the agents and the humorous take on aliens hiding on Earth makes it fun and easy to watch.', null);  # Men in Black 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (214755, 7, 'Lior', 'The idea of predicting crimes before they happen is interesting', null);  # Minority Report 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218219, 9, 'Lior', 'The beautiful animation and the relationships makes it emotional and visually memorable.', null);  # Princess Mononoke 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (209158, 6, 'Lior', 'The street life in New York is portrayed realistically, but the tone feels darker than I usually prefer.', null);  # Mean Streets 1973
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218808, 5, 'Lior', 'The James Bond adventure in space is creative, but the focus on action and gadgets is less appealing to me.', null);  # Moonraker 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (223499, 7, 'Lior', 'The story about relationships and artistic connections feels more personal and easier to relate to.', null);  # Mutual Admiration Society 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176711, 6, 'Lior', 'The stylized fight scenes and the Bride’s revenge story are interesting, but it is very action-focused.', null);  # Kill Bill: Vol. 1 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176712, 7, 'Lior', 'I liked the emotional background of the Bride and her relationship with Bill, which adds depth to the story.', null);  # Kill Bill: Vol. 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (177369, 7, 'Lior', 'The character of Rupert Pupkin and his obsession with fame is interesting and slightly uncomfortable to watch.', null);  # The King of Comedy 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (181766, 7, 'Lior', 'The story of the Dalai Lama is visually beautiful and meaningful, though it feels more spiritual than emotional.', null);  # Kundun 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (183370, 8, 'Lior', 'The quiet friendship between the two sisters and the young violinist feels gentle and emotional.', null);  # Ladies in Lavender 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (183873, 8, 'Lior', 'The romantic connection combined with the curse that keeps the lovers apart makes the story unique and emotional.', null);  # Ladyhawke 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185176, 9, 'Lior', 'for me it is a classic.', null);  # Last Dance 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185628, 7, 'Lior', 'The cultural contrast and the relationship between the soldier and the samurai world are interesting to follow.', null);  # The Last Samurai 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (186732, 7, 'Lior', 'The relationship between the two main characters feels realistic and focuses on personal growth.', null);  # Learning to Swim 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188509, 6, 'Lior', 'The characters are fun, but the focus on action and crime is still not my preferred style.', null);  # Lethal Weapon 2 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188510, 6, 'Lior', 'The dynamic between the main characters continues to be entertaining, even if it stays action-heavy.', null);  # Lethal Weapon 3 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188511, 6, 'Lior', 'The series stays consistent, but it is still focused more on action than emotional storytelling.', null);  # Lethal Weapon 4 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (189403, 5, 'Lior', 'The James Bond storyline is classic, but the action and missions are less interesting to me.', null);  # Licence to Kill 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (178994, 6, 'Lior', 'The story about friendship and crime is interesting, but the tone is darker than I usually prefer.', null);  # Knockaround Guys 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (151616, 10, 'Lior', 'I love the playful relationship between Andie and Ben and how their opposite goals slowly turn into real feelings.', null);  # How to Lose a Guy in 10 Days 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (158999, 7, 'Lior', 'The alien invasion scale is exciting and memorable, even if it is more action-focused than emotional.', null);  # Independence Day 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159172, 8, 'Lior', 'The father-son dynamic between Indiana Jones and his dad adds humor and warmth to the adventure.', null);  # Indiana Jones and the Last Crusade 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159175, 7, 'Lior', 'The adventure is entertaining', null);  # Indiana Jones and the Temple of Doom 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (160524, 7, 'Lior', 'The Alaskan setting and the insomnia theme create strong tension, although it feels quite heavy.', null);  # Insomnia 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (164572, 7, 'Lior', 'Jackie Brown is a very strong main character, and I like that the story relies more on character than spectacle.', null);  # Jackie Brown 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (170721, 9, 'Lior', 'I enjoy the familiar Jungle Book characters and the fun jungle setting, which makes it easy and enjoyable to watch.', null);  # Jungle Book 2, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (174953, 9, 'Lior', 'Nausicaa is a very touching  and meaningful.', null);  # Kaze no tani no Naushika 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (162380, 7, 'Lior', 'The tech-based hero idea is interesting, but the film still leans more toward too much action', null);  # Iron Man 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159167, 6, 'Lior', 'Another Indiana Jones adventure is fun to follow, but it feels less memorable than the earlier films.', null);  # Indiana Jones 4 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (163571, 7, 'Lior', 'The coffee-shop conversations make the story feel simple and relatable, with a focus on connection between people.', null);  # It''s Just Coffee 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159665, 6, 'Lior', 'The war setting is intense and dramatic, but it is heavier and harsher than what I usually enjoy most.', null);  # Inglorious Bastards 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (161705, 7, 'Lior', 'I like the fantasy world and emotional loyalty in Inuyasha stories.', null);  # Inuyasha - Tenka hadou no ken 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (110509, 5, 'Lior', 'It seems more like a small personal story, but it does not look especially memorable or emotional to me.', null);  # Feel Neil 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (111963, 5, 'Lior', 'As an opera film, it is visually and musically impressive.', null);  # Fidelio 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (112290, 7, 'Lior', 'The twist with Tyler Durden and the narrator makes it very memorable', null);  # Fight Club 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (113459, 7, 'Lior', 'The courtroom setting and Vin Diesel''s more humorous performance make it easier to enjoy than a standard crime film.', null);  # Find Me Guilty 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (113547, 5, 'Lior', 'The idea of romance crossing into discomfort is interesting.', null);  # Fine Line Between Cute and Creepy, The 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (113814, 6, 'Lior', 'A sports-centered underdog story can be inspiring.', null);  # Fire Inside, The 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (116358, 6, 'Lior', 'The period setting and identity-based romance are interesting, but the tone feels heavy.', null);  # Focus 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (116829, 5, 'Lior', 'Did not leave a strong impression on me.', null);  # Foot Shooting Party, The 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (117582, 4, 'Lior', 'The political and documentary style makes it feel much less appealing to me than a story-based film.', null);  # Foreigners out! Schlingensiefs Container 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (119344, 4, 'Lior', 'The horror-related subject matter is not really my taste, even if it might be interesting from a film-history angle.', null);  # Freaks Uncensored! 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120722, 5, 'Lior', 'It seems more experimental and distant, which makes it harder for me to connect to emotionally.', null);  # Fronterz 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (121552, 6, 'Lior', 'The country and music atmosphere could be appealing, though it sounds more modest than memorable.', null);  # Full Moon Rising 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (122277, 5, 'Lior', 'The title suggests something offbeat or ironic, but it does not sound like the kind of film I would strongly connect to.', null);  # Fyrsti aprl 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (126144, 5, 'Lior', 'A filmmaker portrait can be interesting, but I usually prefer an actual narrative film with characters and relationships.', null);  # Gerald L'Ecuyer: A Filmmaker's Journey 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (117874, 9, 'Lior', 'One of the best movies Ive seen, Sentimental in the best way.', NULL); -- 117874 Forrest Gump (1994)
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (362808, 9, 'Lior', 'The best romantic comedy.', NULL); -- 362808 When Harry Met Sally... (1989)
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (92573, 4, 'Lior', 'Classic spy film, first film in the James Bond series, but the focus on action and missions makes it less appealing to me', null);  # Dr. No
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (94741, 4, 'Lior', 'The tension is strong, but the focus on suspense and danger is not my preferred style.', null);  # Duel
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (96593, 10, 'Lior', 'A very touching story about friendship and loneliness, with a strong emotional core. This is a master piece in my opinion', null);  # E.T.
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (96681, 5, 'Lior', 'kind of funny dark comedy', null);  # Earl's Your Uncle
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (97360, 7, 'Lior', 'I liked how the movie shows Ed Wood''s passion and optimism despite making objectively bad films.', null);  # Ed Wood
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (97727, 9, 'Lior', 'A beautiful and emotional story about being different and finding connection.', null);  # Edward Scissorhands
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (99633, 3, 'Lior', 'heavy focus on violence.', null);  # Elysium
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (100130, 7, 'Lior', 'A strong emotional journey with a personal perspective on survival and growth.', null);  # Empire of the Sun
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (101687, 5, 'Lior', 'The pub setting and physical storytelling are interesting, but the abstract style made it harder for me to connect', null);  # Enter Achilles
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (102108, 4, 'Lior', 'Behind-the-scenes content is interesting', null);  # Pirates BTS
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (103334, 5, 'Lior', 'Feels more like a war or survival story, which is less aligned with my taste.', null);  # Escape to Nowhere
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (109421, 3, 'Lior', 'Car racing and action scenes are not very interesting to me.', null);  # Fast and Furious
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (363633, 6, 'Lior', 'The title suggests emotional tension, but it feels less personal.', null);  -- The Whirlpool 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (363902, 6, 'Lior', 'The social theme is interesting, but it feels more serious than what I usually enjoy.', null);  -- White Like Me 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (320303, 5, 'Lior', 'The idea is interesting, but it feels more conceptual than emotional.', null);  -- Suspension of Disbelief
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (320669, 5, 'Lior', 'Feels more symbolic and distant, which makes it harder to connect to.', null);  -- Sveto mesto
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (321797, 6, 'Lior', 'The nostalgic tone and relationships are interesting, but not very memorable.', null);  -- Sylvia, rimembri ancora?
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (323509, 5, 'Lior', 'The documentary style makes it less engaging compared to story-driven films.', null);  -- Taken for a Ride
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (326384, 7, 'Lior', 'A soft and intimate story that focuses on connection and relationships.', null);  -- Tea with Tiffany
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (332065, 5, 'Lior', 'Classic Bond story, but still very focused on action rather than emotion.', null);  -- Thunderball
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (333398, 6, 'Lior', 'The concept is interesting, but feels less emotional and more technical.', null);  -- The Timekeeper
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335336, 5, 'Lior', 'Another action-heavy Bond film, which is less appealing to me.', null);  -- Tomorrow Never Dies
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335592, 6, 'Lior', 'The idea of a relationship that seems perfect is interesting, but not very deep.', null);  -- Too Good to Be True
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335835, 5, 'Lior', 'The flight scenes are iconic, but the focus on action and competition is less appealing.', null);  -- Top Gun
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (338478, 5, 'Lior', 'Feels more artistic and abstract, making it harder to connect emotionally.', null);  -- Travail
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (342512, 6, 'Lior', 'The different short stories are interesting, but not very emotionally connected.', null);  -- Twilight Zone: The Movie
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313474, 6, 'Lior', 'The Star Wars world is interesting, but it focuses more on action than emotional connection.', null);  -- Star Wars Episode I
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313476, 6, 'Lior', 'The relationship between Anakin and Padme adds some emotional depth, but still very action-driven.', null);  -- Star Wars Episode II
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313477, 7, 'Lior', 'The tragic story of Anakin turning into Darth Vader makes it more emotional than the others.', null);  -- Star Wars Episode III
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313478, 7, 'Lior', 'The story is iconic and the characters are strong, even if it is still action-focused.', null);  -- Empire Strikes Back
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313479, 7, 'Lior', 'The resolution of the story and character relationships makes it more satisfying.', null);  -- Return of the Jedi
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313160, 6, 'Lior', 'Interesting to learn about Kubrick, but I usually prefer story-driven films.', null);  -- Stanley Kubrick documentary
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (319027, 6, 'Lior', 'Feels like a quiet, reflective story, but not very memorable.', null);  -- Sunday Morning
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (316511, 6, 'Lior', 'The personal perspective makes it somewhat interesting, but not very emotional.', null);  -- Stray Glance
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312678, 5, 'Lior', 'The experimental style makes it harder to connect to emotionally.', null);  -- Staccato Purr
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312473, 6, 'Lior', 'The coming-of-age theme is relatable, even if the story is not very memorable.', null);  -- Sretno dijete
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (298884, 7, 'Lior', 'The contrast between the two girls and their friendship makes it unique and fun.', null);  -- Shimotsuma monogatari
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (304862, 7, 'Lior', 'The gothic atmosphere and the mystery make it visually interesting, even if a bit dark.', null);  -- Sleepy Hollow
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (306032, 6, 'Lior', 'The fast-paced story is entertaining, but more focused on crime than emotions.', null);  -- Snatch
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (308025, 7, 'Lior', 'The romantic and protective dynamic between the characters makes it engaging.', null);  -- Someone to Watch Over Me
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256839, 5, 'Lior', 'The survival idea is interesting, but the dark science-fiction tone is less appealing to me.', null);  -- Pitch Black 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (258132, 5, 'Lior', 'It feels more serious and distant, so it is harder for me to connect emotionally.', null);  -- Plenilunio 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (258874, 5, 'Lior', 'The concept seems modern and light, but it does not sound especially memorable.', null);  -- Point Five 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (258948, 4, 'Lior', 'The darker and more provocative tone is not really my style.', null);  -- Poison Ivy 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (259529, 4, 'Lior', 'It seems more procedural and grim than the kind of emotional story I usually enjoy.', null);  -- Polizeiruf 110 - Die Spur des 13. Apostels 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (261504, 5, 'Lior', 'It feels more artistic than emotional, so it is harder for me to connect to.', null);  -- Postal Branco, O 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (261532, 5, 'Lior', 'A documentary about an author can be interesting, but I usually prefer a full narrative film.', null);  -- Postcards from the Future: The Chuck Palahniuk Documentary 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (263403, 6, 'Lior', 'The family and political contrast sounds interesting, even if it is not a very familiar film to me.', null);  -- Prezident i yego vnuchka 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (263443, 5, 'Lior', 'The war theme makes it feel heavier than what I usually enjoy.', null);  -- Price for Peace 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (264084, 6, 'Lior', 'The title suggests a more personal or romantic tone, which is more in my direction.', null);  -- Prince Solitaire 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (264363, 5, 'Lior', 'The historical setting is meaningful, but it sounds more documentary-like than emotional.', null);  -- Pripyat 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (266446, 5, 'Lior', 'It seems more artistic and distant, which makes it harder for me to engage with.', null);  -- Prncipe, O 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (265273, 6, 'Lior', 'The idea of talent and pressure can be interesting, though it feels less emotional than relationship-driven stories.', null);  -- Prodigy, The 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (267038, 7, 'Lior', 'The dialogue and structure are very memorable, even if the violence makes it less enjoyable for me personally.', null);  -- Pulp Fiction 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (267066, 5, 'Lior', 'It feels more atmospheric than emotionally engaging, so it is harder to connect to.', null);  -- Pulso, O 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (268034, 6, 'Lior', 'The title suggests mystery and tension, which can be interesting, though not very moving.', null);  -- Puzzle, The 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (270134, 4, 'Lior', 'The horror tone is not really my preference, even if the concept may be interesting.', null);  -- R.I.P., Rest in Pieces 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (271199, 5, 'Lior', 'It sounds quiet and atmospheric, but not especially memorable for me.', null);  -- Rain, Drizzle, and Fog 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (272877, 5, 'Lior', 'The darker mood makes it less aligned with my taste than romantic or family films.', null);  -- Raven, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (273164, 6, 'Lior', 'The memory and reflection theme sounds emotional, even if it is not a very familiar film.', null);  -- Re-Membering Jack 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (274677, 6, 'Lior', 'A reflective personal story can be meaningful, though it sounds more quiet than memorable.', null);  -- Reflections of a Life 2003
