insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (9125, 6, 'Matan Dan On', 'The deadpan delivery and constant visual gags are impressive, but the joke density feels exhausting enough that I would not rewatch often.', null); -- 9125 Airplane! 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (9795, 8, 'Matan Dan On', 'Robin Williams gives the movie its spark, and the songs and expressive animation still feel bright and funny decades later.', null); -- 9795 Aladdin 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (24430, 7, 'Matan Dan On', 'The spy-movie parody lands because the costumes, catchphrases, and awkward timing commit fully to the absurd premise.', null); -- 24430 Austin Powers: International Man of Mystery 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (24432, 7, 'Matan Dan On', 'Dr. Evil and Mini-Me add the strongest laughs, though the sequel works best when it leans into silly character chemistry.', null); -- 24432 Austin Powers: The Spy Who Shagged Me 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (24429, 6, 'Matan Dan On', 'There are still good bits, but the movie stretches familiar jokes thinner and feels less sharp than the earlier entries.', null); -- 24429 Austin Powers in Goldmember 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (32178, 9, 'Matan Dan On', 'The character arc, gothic castle atmosphere, and flawless songs make it one of Disney''s most emotionally complete films.', null); -- 32178 Beauty and the Beast 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (40226, 6, 'Matan Dan On', 'The found-footage impact is important and the tension feels raw, but the slow pacing and vague ending limit my enjoyment.', null); -- 40226 Blair Witch Project, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (59578, 7, 'Matan Dan On', 'Tim Burton''s factory design is imaginative and strange, although the emotional warmth is weaker than the visual creativity.', null); -- 59578 Charlie and the Chocolate Factory 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (66194, 8, 'Matan Dan On', 'The fashion, slang, and social satire are extremely sharp, and Cher''s growth keeps the comedy from feeling shallow.', null); -- 66194 Clueless 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (68232, 8, 'Matan Dan On', 'Eddie Murphy''s character work is hilarious, and the barbershop scenes alone make the film feel endlessly quotable.', null); -- 68232 Coming to America 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (80583, 9, 'Matan Dan On', 'The teacher-student dynamic is deeply moving, and the film makes its message about courage and individuality feel earned.', null); -- 80583 Dead Poets Society 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (84941, 9, 'Matan Dan On', 'Managing two businesses myself, the high-stakes, demanding workplace dynamics in this film felt surprisingly intense and relatable.', null); #Devil Wears Prada, the 2006 
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (96593, 8, 'Matan Dan On', 'The friendship story is gentle and sincere, and the farewell scene still has a simple emotional power that works.', null); -- 96593 E.T. the Extra-Terrestrial 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (104338, 9, 'Matan Dan On', 'The fractured memory structure turns heartbreak into something visual and inventive, while the relationship still feels painfully human.', null); -- 104338 Eternal Sunshine of the Spotless Mind 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (117874, 8, 'Matan Dan On', 'The historical sweep, music choices, and emotional simplicity make it endlessly watchable despite covering so much ground.', null); -- 117874 Forrest Gump 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (151483, 7, 'Matan Dan On', 'Jim Carrey''s physical comedy gives the movie wild energy, and the exaggerated sets make it a memorable holiday watch.', null); -- 151483 How the Grinch Stole Christmas 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (140221, 9, 'Matan Dan On', 'The moving castle design is full of imagination, and the anti-war fantasy gives the romance more weight than expected.', null); -- 140221 Howl's Moving Castle 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (201302, 8, 'Matan Dan On', 'The small story about burnout, independence, and confidence is comforting, and the flying scenes have a lovely lightness.', null); -- 201302 Kiki's Delivery Service 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139650, 8, 'Matan Dan On', 'The mystery is paced well, the basilisk sequence is genuinely tense, and Hogwarts still feels huge and magical.', null); -- 139650 Harry Potter and the Chamber of Secrets 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139651, 7, 'Matan Dan On', 'As a secondary cut, it keeps the same magical appeal but feels less essential because the core experience is unchanged.', null); -- 139651 Harry Potter and the Chamber of Secrets (2002/II) 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139652, 9, 'Matan Dan On', 'The tournament structure gives the film momentum, and the graveyard scene turns the series darker in a convincing way.', null); -- 139652 Harry Potter and the Goblet of Fire 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139654, 7, 'Matan Dan On', 'The school bureaucracy conflict is frustrating in the right way, and Umbridge works as a memorably cruel villain.', null); -- 139654 Harry Potter and the Order of the Phoenix 2007
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139655, 8, 'Matan Dan On', 'Cuaron gives the series a richer visual language, and the time-travel mechanics are clear without losing their wonder.', null); -- 139655 Harry Potter and the Prisoner of Azkaban 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139657, 8, 'Matan Dan On', 'The first trip to Hogwarts is still charming, with strong world-building and a sense of discovery that holds up.', null); -- 139657 Harry Potter and the Sorcerer's Stone 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (143526, 8, 'Matan Dan On', 'The gospel-inspired songs are fantastic, and Hades gives the movie a funny, sarcastic villain energy.', null); -- 143526 Hercules 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (158927, 8, 'Matan Dan On', 'The superhero action works because the family conflict is just as strong as the powers and set pieces.', null); -- 158927 Incredibles, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (187191, 8, 'Matan Dan On', 'Elle''s law-school arc is funny and genuinely empowering because her kindness and preparation beat everyone''s stereotypes.', null); -- 187191 Legally Blonde 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (191246, 10, 'Matan Dan On', 'The opening sequence, music, and coming-of-age tragedy make it one of the most complete animated films I know.', null); -- 191246 Lion King, The 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (192017, 8, 'Matan Dan On', 'The songs are iconic, and the underwater animation gives the fairy tale a sense of motion and personality.', null); -- 192017 Little Mermaid, The 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (207992, 9, 'Matan Dan On', 'The simulated-reality concept is brilliant yet convoluted, and the action style still feels precise, stylish, and intellectually exciting.', null); -- 207992 Matrix, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (209133, 9, 'Matan Dan On', 'The script captures toxic high-school social rules with sharp jokes, and nearly every major scene is quotable.', null); -- 209133 Mean Girls 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218415, 8, 'Matan Dan On', 'The door-chase sequence is a creative triumph, and the movie turns childhood fear into a warm friendship story.', null); -- 218415 Monsters, Inc. 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (222112, 7, 'Matan Dan On', 'The action scale is unusually strong for Disney animation, and the themes of honor and bravery land cleanly.', null); -- 222112 Mulan 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335380, 9, 'Matan Dan On', 'Totoro''s calm presence makes the fantasy feel safe and comforting, while the rural setting stays beautifully observed. Will and have watched many times', null); -- 335380 My Neighbor Totoro 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (248878, 8, 'Matan Dan On', 'The camp pranks and twin switch are fun, and the family-reunion plot has more charm than it needs to.', null); -- 248878 Parent Trap, The 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (263360, 8, 'Matan Dan On', 'The lead chemistry carries the film, and the fairy-tale tone is balanced by several genuinely iconic character moments.', null); -- 263360 Pretty Woman 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (264158, 8, 'Matan Dan On', 'The makeover comedy is delightful, but the real appeal is Mia learning confidence without losing her awkward sweetness.', null); -- 264158 Princess Diaries, The 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (264157, 7, 'Matan Dan On', 'The sequel is lighter and sillier, but the royal politics and Anne Hathaway''s charm keep it enjoyable.', null); -- 264157 Princess Diaries 2: Royal Engagement, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (267038, 9, 'Matan Dan On', 'The non-linear structure and sharp dialogue make every storyline feel dangerous, funny, and weirdly controlled.', null); -- 267038 Pulp Fiction 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (272644, 10, 'Matan Dan On', 'A beautiful tribute to the artistry of cooking. The scene where the critic eats the final dish is pure cinematic perfection.', null); #Ratatouille 2007 
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (279888, 7, 'Matan Dan On', 'The mechanical world is visually inventive and playful, even when the story leans too much on slapstick.', null); -- 279888 Robots 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300229, 9, 'Matan Dan On', 'The fairy-tale parody changed animated comedy, and the mix of sarcasm, heart, and music is still very rewatchable.', null); -- 300229 Shrek 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300230, 10, 'Matan Dan On', 'The sequel improves the world, the jokes, and the emotional stakes, with a climax that is pure animated comedy joy.', null); -- 300230 Shrek 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300232, 6, 'Matan Dan On', 'It lost a lot of the biting wit of the first two films, relying a bit too much on tired tropes rather than parodying them.', null); #Shrek 3 2007 
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (294028, 10, 'Matan Dan On', 'The bathhouse world is mesmerizing, and the surreal spirit designs make every scene feel alive with imagination.', null); -- 294028 Spirited Away 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312150, 7, 'Matan Dan On', 'The gadgets and family-spy premise are very creative, and the movie captures a childlike adventure mood well.', null); -- 312150 Spy Kids 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (333856, 7, 'Matan Dan On', 'The romance is broad but effective, and the practical detail of the sinking gives the spectacle real force, yet makes the movie drag out.', null); -- 333856 Titanic 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (340901, 9, 'Matan Dan On', 'The surveillance satire feels more relevant over time, and the ending is quiet, brave, and emotionally perfect.', null); -- 340901 Truman Show, The 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (337166, 9, 'Matan Dan On', 'The technology was groundbreaking, but the jealousy and friendship story is what makes it last beyond the novelty.', null); -- 337166 Toy Story 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (337168, 9, 'Matan Dan On', 'The sequel expands the world with richer themes about abandonment, collectors, and what toys mean to children.', null); -- 337168 Toy Story 2 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (367073, 9, 'Matan Dan On', 'The shift into color still feels magical, and the songs and production design remain central to film history.', null); -- 367073 Wizard of Oz, The 1939
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (342384, 8, 'Matan Dan On', 'The grim future and unstable timeline create a strong paranoid mood, even when the plot is intentionally disorienting.', null); -- 342384 12 Monkeys 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130128, 10, 'Matan Dan On', 'The family politics are gripping, and every quiet conversation feels like it could change the balance of power.', null); -- 130128 The Godfather 1972
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130129, 10, 'Matan Dan On', 'The parallel timelines deepen Michael''s tragedy and make the sequel feel even more ambitious than the original.', null); -- 130129 The Godfather: Part II 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130130, 6, 'Matan Dan On', 'It has strong regret and legacy themes, but the pacing and uneven performances make it much weaker than the first two.', null); -- 130130 The Godfather: Part III 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (297838, 10, 'Matan Dan On', 'The friendship builds patiently, and the ending feels earned because the movie makes hope seem practical rather than naive.', null); -- 297838 The Shawshank Redemption 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (290070, 10, 'Matan Dan On', 'The restraint, black-and-white photography, and moral focus make it devastating without ever feeling manipulative.', null); -- 290070 Schindler's List 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56044, 9, 'Matan Dan On', 'The romance works because the sacrifice is clear, and the dialogue still has a timeless wartime elegance.', null); -- 56044 Casablanca 1942
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (64729, 8, 'Matan Dan On', 'The camera work and structure are historically impressive, though I admire it more intellectually than emotionally.', null); -- 64729 Citizen Kane 1941
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131240, 7, 'Matan Dan On', 'The scale and production are enormous, but the length and dated worldview make it harder for me to fully embrace.', null); -- 131240 Gone with the Wind 1939
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313459, 10, 'Matan Dan On', 'The adventure is clean, mythic, and instantly readable, with world-building that still feels bigger than the frame.', null); -- 313459 Star Wars 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313478, 10, 'Matan Dan On', 'The darker tone, character setbacks, and Vader reveal make it the most dramatically satisfying Star Wars film.', null); -- 313478 Star Wars: Episode V - The Empire Strikes Back 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313479, 9, 'Matan Dan On', 'The throne-room conflict gives Vader and Luke a powerful ending, even if the middle is a little uneven.', null); -- 313479 Star Wars: Episode VI - Return of the Jedi 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313474, 4, 'Matan Dan On', 'The pod race and score are memorable, but the stiff dialogue and trade-politics plot drain too much energy.', null); -- 313474 Star Wars: Episode I - The Phantom Menace 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313476, 5, 'Matan Dan On', 'The Obi-Wan detective thread is fun, but the romance dialogue is awkward enough to hurt the central story.', null); -- 313476 Star Wars: Episode II - Attack of the Clones 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313477, 7, 'Matan Dan On', 'Anakin''s fall is melodramatic but compelling, and the final act gives the prequels real tragic momentum.', null); -- 313477 Star Wars: Episode III - Revenge of the Sith 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (271095, 10, 'Matan Dan On', 'The action is perfectly staged, and Indiana Jones feels clever, vulnerable, and iconic from the opening sequence.', null); -- 271095 Raiders of the Lost Ark 1981
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159175, 7, 'Matan Dan On', 'It has great set pieces and a darker adventure tone, but some choices are too harsh and dated.', null); -- 159175 Indiana Jones and the Temple of Doom 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159172, 9, 'Matan Dan On', 'The father-son dynamic adds warmth, and the quest structure brings back the playful adventure feeling beautifully.', null); -- 159172 Indiana Jones and the Last Crusade 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (165961, 9, 'Matan Dan On', 'The shark is most frightening when unseen, and the boat scenes turn the thriller into a character piece.', null); -- 165961 Jaws 1975
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (26844, 10, 'Matan Dan On', 'The script is incredibly tight, with every setup paying off in a funny and satisfying time-travel loop.', null); -- 26844 Back to the Future 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (26846, 8, 'Matan Dan On', 'The future and alternate-timeline ideas are inventive, even when the plot becomes busier than the original.', null); -- 26846 Back to the Future Part II 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (26847, 7, 'Matan Dan On', 'The western setting is charming and gives Doc a sweet arc, though it is the lightest of the trilogy.', null); -- 26847 Back to the Future Part III 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (328285, 9, 'Matan Dan On', 'The lean chase structure and machine-like villain make it a tense sci-fi thriller from start to finish.', null); -- 328285 The Terminator 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (328277, 10, 'Matan Dan On', 'The action, effects, and protector reversal are all excellent, and Sarah Connor''s arc gives it real weight.', null); -- 328277 Terminator 2: Judgment Day 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (328281, 5, 'Matan Dan On', 'The ending is bold, but most of the movie feels like a weaker repeat of better set pieces.', null); -- 328281 Terminator 3: Rise of the Machines 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10830, 9, 'Matan Dan On', 'The slow reveal of the creature and industrial spaceship design make the horror feel claustrophobic and believable.', null); -- 10830 Alien 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10920, 10, 'Matan Dan On', 'The sequel changes genres brilliantly, turning survival horror into a tense action film with a strong found-family core.', null); -- 10920 Aliens 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10916, 4, 'Matan Dan On', 'There are interesting creature ideas, but the tone is messy and the suspense never reaches the earlier films.', null); -- 10916 Alien: Resurrection 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (262645, 8, 'Matan Dan On', 'The jungle hunt premise is simple and effective, and the creature design gives the action a strong payoff.', null); -- 262645 Predator 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (86274, 10, 'Matan Dan On', 'The contained tower setting, practical action, and vulnerable hero make it one of the cleanest action films ever made.', null); -- 86274 Die Hard 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (86279, 7, 'Matan Dan On', 'The airport setup is tense and entertaining, though it feels more mechanical and less fresh than the original.', null); -- 86279 Die Hard 2 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (86287, 8, 'Matan Dan On', 'The buddy dynamic with Samuel L. Jackson refreshes the formula and gives the puzzles more personality.', null); -- 86287 Die Hard with a Vengeance 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188507, 8, 'Matan Dan On', 'The action works because the mismatched partnership has real rhythm, pain, and humor behind it.', null); -- 188507 Lethal Weapon 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (310726, 8, 'Matan Dan On', 'The bus premise is wonderfully direct, and the movie keeps escalating without wasting much time.', null); -- 310726 Speed 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46169, 8, 'Matan Dan On', 'The battle scenes and freedom theme are powerful, even though the historical simplifications are hard to ignore.', null); -- 46169 Braveheart 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (129185, 9, 'Matan Dan On', 'The revenge story is muscular and emotional, and the arena scenes have a grand tragic intensity.', null); -- 129185 Gladiator 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (289109, 10, 'Matan Dan On', 'The opening battle is overwhelming, and the mission that follows keeps asking what one life is worth.', null); -- 289109 Saving Private Ryan 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131780, 10, 'Matan Dan On', 'The narration, editing, and escalating paranoia make the gangster lifestyle feel seductive and rotten at the same time.', null); -- 131780 Goodfellas 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (289558, 8, 'Matan Dan On', 'The rise-and-fall story is excessive by design, and Pacino''s performance makes the greed feel volcanic.', null); -- 289558 Scarface 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (276217, 8, 'Matan Dan On', 'The limited locations and fractured timeline turn a failed robbery into a tense study of suspicion.', null); -- 276217 Reservoir Dogs 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (112290, 9, 'Matan Dan On', 'The satire of masculinity and consumer culture is messy but bold, with a twist that recontextualizes everything.', null); -- 112290 Fight Club 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (291698, 9, 'Matan Dan On', 'The oppressive atmosphere and moral bleakness make the investigation feel dirty, with an ending that really lands.', null); -- 291698 Se7en 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (301540, 10, 'Matan Dan On', 'Clarice and Lecter''s conversations are electric, and the thriller balances psychology, fear, and procedure perfectly.', null); -- 301540 The Silence of the Lambs 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (348944, 9, 'Matan Dan On', 'The unreliable storytelling is clever, and the final reveal gives the whole movie a satisfying snap.', null); -- 348944 The Usual Suspects 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210511, 9, 'Matan Dan On', 'The reverse structure is not just a gimmick; it puts the audience inside Leonard''s broken certainty.', null); -- 210511 Memento 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (13789, 8, 'Matan Dan On', 'The suburban critique is sharp and uncomfortable, with strong performances that make the characters feel trapped.', null); -- 13789 American Beauty 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (13978, 8, 'Matan Dan On', 'The lead performance is intense, and the film is strongest when it shows hatred damaging a whole family.', null); -- 13978 American History X 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (303564, 9, 'Matan Dan On', 'The twist is famous, but the quiet grief in the child therapy scenes is what makes it work.', null); -- 303564 The Sixth Sense 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (134077, 9, 'Matan Dan On', 'The prison setting, magical realism, and performances create a long but deeply affecting moral story.', null); -- 134077 The Green Mile 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (32114, 8, 'Matan Dan On', 'The film makes abstract genius personal, and the relationship story gives the mental-health struggle emotional focus.', null); -- 32114 A Beautiful Mind 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56871, 8, 'Matan Dan On', 'The cat-and-mouse structure is breezy and stylish, while the loneliness underneath keeps it from feeling hollow.', null); -- 56871 Catch Me If You Can 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56431, 8, 'Matan Dan On', 'The survival section is patient and physical, and the volleyball relationship somehow becomes emotionally convincing.', null); -- 56431 Cast Away 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (18979, 8, 'Matan Dan On', 'The engineering problem-solving is suspenseful, and the film makes teamwork feel as heroic as bravery.', null); -- 18979 Apollo 13 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (36694, 8, 'Matan Dan On', 'Tom Hanks makes the body-swap idea sweet rather than creepy, and the toy-store scenes are wonderfully playful.', null); -- 36694 Big 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (134672, 9, 'Matan Dan On', 'The time-loop comedy becomes surprisingly philosophical, and Phil''s growth feels earned through repetition.', null); -- 134672 Groundhog Day 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (221259, 8, 'Matan Dan On', 'Robin Williams balances chaos and tenderness, making the divorce story funnier and sadder than expected.', null); -- 221259 Mrs. Doubtfire 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (148200, 8, 'Matan Dan On', 'The traps are funny, but the movie works because Kevin''s independence and loneliness are both clear.', null); -- 148200 Home Alone 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (148203, 6, 'Matan Dan On', 'New York gives the sequel scale, but it repeats the first movie''s beats too closely.', null); -- 148203 Home Alone 2: Lost in New York 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (111442, 8, 'Matan Dan On', 'The rule-breaking fantasy is charming, and Cameron''s anxiety gives the comedy a more thoughtful emotional layer.', null); -- 111442 Ferris Bueller's Day Off 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46322, 8, 'Matan Dan On', 'The character stereotypes soften through conversation, and the library setting keeps the drama focused.', null); -- 46322 The Breakfast Club 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (303545, 6, 'Matan Dan On', 'It has memorable teen-comedy moments, but some jokes have aged badly and make it uneven now.', null); -- 303545 Sixteen Candles 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (362808, 9, 'Matan Dan On', 'The friendship-to-romance arc is beautifully paced, and the dialogue understands how relationships change over time.', null); -- 362808 When Harry Met Sally... 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (304829, 7, 'Matan Dan On', 'The romantic fate idea is sweet and comforting, though the leads spend surprisingly little time together.', null); -- 304829 Sleepless in Seattle 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (372372, 7, 'Matan Dan On', 'The email-era charm is strong, but the bookstore business conflict makes the romance a little complicated.', null); -- 372372 You've Got Mail 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (235790, 8, 'Matan Dan On', 'The ordinary-person fantasy works because the supporting friends are funny and the romance stays warm.', null); -- 235790 Notting Hill 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (118393, 7, 'Matan Dan On', 'The ensemble is charming and the funeral scene adds depth, though the romance can feel slightly passive.', null); -- 118393 Four Weddings and a Funeral 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (166917, 7, 'Matan Dan On', 'The sports-agent story is uneven, but the catchphrases and Cuba Gooding Jr. energy make it memorable.', null); -- 166917 Jerry Maguire 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (195300, 8, 'Matan Dan On', 'The many storylines vary in quality, but the holiday warmth and musical moments make it very rewatchable.', null); -- 195300 Love Actually 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (644, 8, 'Matan Dan On', 'The Shakespeare update works because the teen characters are funny, specific, and carried by strong chemistry.', null); -- 644 10 Things I Hate About You 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (1038, 7, 'Matan Dan On', 'The wish-fulfillment premise is light, but Jennifer Garner gives it sincere sweetness and comic timing.', null); -- 1038 13 Going on 30 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215507, 7, 'Matan Dan On', 'Sandra Bullock makes the undercover-pageant setup funny, and the movie has an easy crowd-pleasing rhythm.', null); -- 215507 Miss Congeniality 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (223711, 7, 'Matan Dan On', 'The film is interesting because the heroine is selfish, and the ending avoids the easiest romantic answer.', null); -- 223711 My Best Friend's Wedding 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (360723, 8, 'Matan Dan On', 'The 80s jokes are fun, and the central romance is sweet without becoming too sugary.', null); -- 360723 The Wedding Singer 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (330057, 7, 'Matan Dan On', 'The gross-out comedy is hit-or-miss, but the best scenes have fearless timing and memorable absurdity.', null); -- 330057 There's Something About Mary 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (95078, 7, 'Matan Dan On', 'The stupidity is extremely committed, and the road-trip structure gives the best jokes room to build.', null); -- 95078 Dumb and Dumber 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (5573, 6, 'Matan Dan On', 'Jim Carrey''s physical energy is undeniable, but the humor is more uneven and dated now.', null); -- 5573 Ace Ventura: Pet Detective 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (207157, 7, 'Matan Dan On', 'The cartoon effects fit Carrey''s performance perfectly, even when the crime plot is fairly simple.', null); -- 207157 The Mask 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (189233, 7, 'Matan Dan On', 'The truth-telling premise is a perfect showcase for Carrey''s chaos, with just enough family emotion.', null); -- 189233 Liar Liar 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (209658, 7, 'Matan Dan On', 'The escalating social embarrassment is painful but funny, and De Niro makes every small test feel serious.', null); -- 209658 Meet the Parents 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (375827, 7, 'Matan Dan On', 'The fashion-world satire is proudly ridiculous, and the best quotes are still funny because of the straight-faced delivery.', null); -- 375827 Zoolander 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (16006, 8, 'Matan Dan On', 'The newsroom parody is loose and absurd, but the ensemble turns nearly every scene into a quotable bit.', null); -- 16006 Anchorman: The Legend of Ron Burgundy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (89057, 7, 'Matan Dan On', 'The sports-underdog formula is silly, but the dodgeball matches and villain performance make it easy fun.', null); -- 89057 Dodgeball: A True Underdog Story 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (290378, 8, 'Matan Dan On', 'Jack Black''s energy is perfect, and the movie makes music education feel joyful rather than preachy.', null); -- 290378 School of Rock 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (227549, 7, 'Matan Dan On', 'The awkward deadpan style is very specific, and the tiny-town details make the weirdness feel complete.', null); -- 227549 Napoleon Dynamite 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194497, 10, 'Matan Dan On', 'The fellowship formation is emotional, and the world feels ancient, detailed, and dangerous from the start.', null); -- 194497 The Lord of the Rings: The Fellowship of the Ring 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194502, 10, 'Matan Dan On', 'The parallel storylines build beautifully, and Helm''s Deep remains one of the best fantasy battles filmed.', null); -- 194502 The Lord of the Rings: The Two Towers 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194500, 10, 'Matan Dan On', 'The emotional payoff is enormous, and the battles, loyalty, and farewells make the long ending feel deserved.', null); -- 194500 The Lord of the Rings: The Return of the King 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256632, 9, 'Matan Dan On', 'The pirate adventure is energetic, and Jack Sparrow''s unpredictable rhythm makes the whole film feel fresh.', null); -- 256632 Pirates of the Caribbean: The Curse of the Black Pearl 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311037, 8, 'Matan Dan On', 'The origin story is sincere and colorful, and Peter''s responsibility theme is handled with real clarity.', null); -- 311037 Spider-Man 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311038, 9, 'Matan Dan On', 'The sequel improves the personal stakes, and Doc Ock is both visually memorable and emotionally grounded.', null); -- 311038 Spider-Man 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30959, 9, 'Matan Dan On', 'The reboot makes Batman''s fear and discipline feel practical, giving the superhero story a strong foundation.', null); -- 30959 Batman Begins 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30955, 8, 'Matan Dan On', 'The gothic style and Nicholson''s Joker make Gotham feel theatrical, strange, and instantly recognizable.', null); -- 30955 Batman 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30967, 4, 'Matan Dan On', 'Way too focused on the director''s weird obsessions. The actual hero takes a backseat to bizarre, grotesque villains.', null); -- 30967 Batman Returns 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30965, 3, 'Matan Dan On', 'A neon nightmare. The villains are just screaming at the camera for two hours with absolutely no nuance.', null); -- 30965 Batman Forever 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30952, 2, 'Matan Dan On', 'The camp can be amusing, but the puns, toy-like sets, and flat character work make it exhausting.', null); -- 30952 Batman & Robin 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (319602, 8, 'Matan Dan On', 'The optimism is sincere, and Christopher Reeve makes the character noble without losing warmth or humor.', null); -- 319602 Superman 1978
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (369458, 8, 'Matan Dan On', 'The mutant prejudice theme gives the superhero setup weight, and the casting of Wolverine and Magneto is strong.', null); -- 369458 X-Men 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (369486, 8, 'Matan Dan On', 'The sequel expands the team well, and the mansion attack sequence gives the action real urgency.', null); -- 369486 X2 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (152426, 5, 'Matan Dan On', 'The comic-panel editing is interesting, but the slow pacing and uneven effects make the drama hard to enjoy.', null); -- 152426 Hulk 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (40187, 7, 'Matan Dan On', 'The vampire action has a cool visual identity, and Wesley Snipes gives the character sharp presence.', null); -- 40187 Blade 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210739, 8, 'Matan Dan On', 'The alien bureaucracy idea is clever, and the Smith-Jones pairing keeps the sci-fi comedy moving quickly.', null); -- 210739 Men in Black 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210741, 5, 'Matan Dan On', 'It has a few fun creature jokes, but the story feels like a smaller and less surprising repeat.', null); -- 210741 Men in Black II 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (127084, 8, 'Matan Dan On', 'The paranormal comedy works because the cast treats the absurd ghost business like a normal, messy job.', null); -- 127084 Ghost Busters 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (35522, 8, 'Matan Dan On', 'Eddie Murphy''s loose comic style gives the police plot personality, speed, and a great soundtrack vibe.', null); -- 35522 Beverly Hills Cop 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (112205, 8, 'Matan Dan On', 'The visual design is wild and colorful, and the movie commits completely to its strange sci-fi tone.', null); -- 112205 The Fifth Element 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (158999, 8, 'Matan Dan On', 'The disaster spectacle is huge and patriotic, and the ensemble makes the alien invasion very entertaining.', null); -- 158999 Independence Day 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (20371, 6, 'Matan Dan On', 'The emotional manipulation is obvious, but the movie has enough spectacle and personality to stay watchable.', null); -- 20371 Armageddon 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (342685, 7, 'Matan Dan On', 'The storm-chasing scenes are exciting, and the practical danger gives the simple character drama enough momentum.', null); -- 342685 Twister 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (155070, 7, 'Matan Dan On', 'The robot mystery is polished and accessible, with enough questions about trust and control to stay engaging.', null); -- 155070 I, Robot 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (214755, 8, 'Matan Dan On', 'The future policing concept is smart, and the chase sequences are full of memorable technology ideas.', null); -- 214755 Minority Report 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (359297, 6, 'Matan Dan On', 'The invasion scenes are intense, but the family drama is uneven and the ending feels too abrupt.', null); -- 359297 War of the Worlds 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (69895, 8, 'Matan Dan On', 'The science-faith debate is thoughtful, and the first-contact mystery feels patient and genuinely curious.', null); -- 69895 Contact 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (301391, 7, 'Matan Dan On', 'The farmhouse tension is strong, and the family grief gives the alien story a personal shape.', null); -- 301391 Signs 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (345690, 8, 'Matan Dan On', 'The superhero idea is quiet and grounded, with a final reveal that fits the comic-book structure.', null); -- 345690 Unbreakable 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (177328, 5, 'Matan Dan On', 'The spectacle is impressive and Kong is expressive, though the long runtime makes the adventure feel heavy.', null); -- 177328 King Kong 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (222339, 8, 'Matan Dan On', 'The adventure-horror balance is fun, and Brendan Fraser gives the movie a relaxed heroic charm.', null); -- 222339 The Mummy 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (113504, 9, 'Matan Dan On', 'The ocean world is gorgeous, and the parent-child story turns a rescue mission into something deeply tender.', null); -- 113504 Finding Nemo 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (155213, 8, 'Matan Dan On', 'The prehistoric road-trip setup is simple, but the herd dynamic is funny and surprisingly warm.', null); -- 155213 Ice Age 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (199255, 7, 'Matan Dan On', 'The zoo-animal personalities are broad but fun, and the penguins add a lot of comic energy.', null); -- 199255 Madagascar 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (297650, 5, 'Matan Dan On', 'The celebrity voices are recognizable, but the pop-culture jokes date the movie and weaken the story.', null); -- 297650 Shark Tale 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (162352, 9, 'Matan Dan On', 'The friendship with the robot is gentle and powerful, and the anti-weapon message lands without preaching.', null); -- 162352 The Iron Giant 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (325098, 8, 'Matan Dan On', 'The movement through the trees is thrilling, and the Phil Collins songs give the story strong emotion.', null); -- 325098 Tarzan 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (258509, 6, 'Matan Dan On', 'The music is beautiful, but the simplified history and thinner characters hold it below Disney''s best.', null); -- 258509 Pocahontas 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (152724, 8, 'Matan Dan On', 'The darker tone, cathedral visuals, and villain song make it one of Disney''s boldest films.', null); -- 152724 The Hunchback of Notre Dame 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (48950, 8, 'Matan Dan On', 'The tiny-world perspective is clever, and the circus-insect group gives the adventure a playful ensemble feel.', null); -- 48950 A Bug's Life 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (61291, 8, 'Matan Dan On', 'The prison-break parody is charming, and the stop-motion texture gives every joke extra personality.', null); -- 61291 Chicken Run 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (70959, 7, 'Matan Dan On', 'The underworld design is beautiful and musical, though the romance is slighter than the visuals.', null); -- 70959 Corpse Bride 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (232425, 9, 'Matan Dan On', 'The holiday mashup is visually unforgettable, and the songs give the gothic world a playful rhythm.', null); -- 232425 The Nightmare Before Christmas 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (364161, 9, 'Matan Dan On', 'The live-action and animation blend is still impressive, and the noir mystery gives the cartoon chaos structure.', null); -- 364161 Who Framed Roger Rabbit 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (310130, 6, 'Matan Dan On', 'The nostalgia and Looney Tunes energy are fun, but the story is thin and mostly built around novelty.', null); -- 310130 Space Jam 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (26064, 8, 'Matan Dan On', 'The talking-animal story is gentle and sincere, with a kindness theme that feels surprisingly mature.', null); -- 26064 Babe 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (207828, 8, 'Matan Dan On', 'The exaggerated villains and telekinetic wish-fulfillment work because Matilda herself is smart and easy to root for.', null); -- 207828 Matilda 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (170522, 8, 'Matan Dan On', 'The board-game disasters are creative, and Robin Williams adds real sadness to the adventure comedy.', null); -- 170522 Jumanji 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (149287, 7, 'Matan Dan On', 'The adult Peter Pan idea is uneven, but the Neverland design and nostalgia still make it enjoyable.', null); -- 149287 Hook 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (264146, 10, 'Matan Dan On', 'The comedy, romance, and adventure all work together, and nearly every character gets a memorable moment.', null); -- 264146 The Princess Bride 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (365906, 9, 'Matan Dan On', 'Gene Wilder makes Wonka mysterious and funny, and the factory tour has a strange moral imagination.', null); -- 365906 Willy Wonka and the Chocolate Factory 1971
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131885, 8, 'Matan Dan On', 'The kid-adventure chaos is messy in the best way, with treasure-map energy and strong group chemistry.', null); -- 131885 The Goonies 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (97727, 8, 'Matan Dan On', 'The suburbia satire and lonely fairy-tale romance fit together beautifully through Burton''s visual style.', null); -- 97727 Edward Scissorhands 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (37057, 8, 'Matan Dan On', 'The tall tales are colorful, and the father-son ending gives the fantasy a moving personal reason.', null); -- 37057 Big Fish 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (257296, 3, 'Matan Dan On', 'The makeup is impressive, but the remake feels emotionally flat and the ending is more confusing than clever.', null); -- 257296 Planet of the Apes 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (6249, 8, 'Matan Dan On', 'The gothic family comedy works because the cast treats the weirdness with total sincerity and affection.', null); -- 6249 The Addams Family 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (133401, 8, 'Matan Dan On', 'The songs are infectious and the school-musical energy is iconic, even if the ending is thematically odd.', null); -- 133401 Grease 1978
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (309634, 9, 'Matan Dan On', 'The songs, landscape, and family warmth make the long runtime feel comforting rather than slow.', null); -- 309634 The Sound of Music 1965
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (206881, 9, 'Matan Dan On', 'The mix of live action, animation, and songs is delightful, with Julie Andrews giving it perfect control.', null); -- 206881 Mary Poppins 1964
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (302696, 9, 'Matan Dan On', 'The musical numbers are joyful and precise, and the movie industry satire is still surprisingly funny.', null); -- 302696 Singin' in the Rain 1952
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (57064, 1, 'Matan Dan On', 'The editing, villain plan, and character choices feel incoherent, wasting a performer who deserved a better superhero film.', null); -- 57064 Catwoman 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (127627, 1, 'Matan Dan On', 'The tone is awkward, the dialogue rarely works, and the romance never becomes believable enough to carry the movie.', null); -- 127627 Gigli 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (365498, 3, 'Matan Dan On', 'The steampunk ideas could have been fun, but the jokes and action feel noisy instead of clever.', null); -- 365498 Wild Wild West 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (319416, 3, 'Matan Dan On', 'The production design is bizarrely memorable, but it barely captures the games and rarely works as adventure comedy.', null); -- 319416 Super Mario Bros. 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (165976, 1, 'Matan Dan On', 'The shark revenge premise is impossible to take seriously, and the suspense is almost completely gone.', null); -- 165976 Jaws: The Revenge 1987