
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (290070, 10, 'MeniWeingarten', 'One of the most important films ever made, hits you like a punch to the gut every single time', null); # Schindler's List 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (297838, 10, 'MeniWeingarten', 'I don''t think any film has ever made me feel as hopeful as this one does, an absolute masterpiece', null); # Shawshank Redemption, The 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313478, 10, 'MeniWeingarten', 'The best Star Wars film by a mile, dark, emotional and the Vader reveal is still incredible', null); # Star Wars: Episode V - The Empire Strikes Back 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (289109, 10, 'MeniWeingarten', 'The opening 25 minutes alone are worth the price of admission, nothing has come close to depicting war like this', null); # Saving Private Ryan 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194497, 10, 'MeniWeingarten', 'A breathtaking adaptation that captures the scope and magic of Tolkien''s world like nothing else could', null); # Lord of the Rings: The Fellowship of the Ring 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313479, 9, 'MeniWeingarten', 'A satisfying and joyful ending to the original trilogy, Ewoks and all', null); # Star Wars: Episode VI - Return of the Jedi 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30959, 9, 'MeniWeingarten', 'Finally a Batman film that takes itself seriously, Nolan completely changed how superhero movies can be made', null); # Batman Begins 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (271095, 9, 'MeniWeingarten', 'Pure adventure filmmaking done perfectly, still the gold standard for action films', null); # Raiders of the Lost Ark 1981
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238072, 9, 'MeniWeingarten', 'A perfectly assembled heist film, the cast chemistry alone makes it worth watching twice', null); # Ocean's Eleven 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (306032, 9, 'MeniWeingarten', 'Ritchie''s editing style makes this endlessly rewatchable, every character gets a great moment', null); # Snatch. 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210511, 9, 'MeniWeingarten', 'Nolan''s reverse chronology puzzle is as gripping as it is clever, genuinely unlike anything else', null); # Memento 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (291698, 9, 'MeniWeingarten', 'Spacey''s performance alone puts this in the top tier, one of the best thrillers ever made', null); # Se7en 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (54209, 9, 'MeniWeingarten', 'De Niro is legitimately terrifying in this, Scorsese builds the tension masterfully', null); # Cape Fear 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (247579, 9, 'MeniWeingarten', 'Fincher makes a single apartment feel like the most claustrophobic place on earth', null); # Panic Room 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (123435, 9, 'MeniWeingarten', 'One of the cleverest thrillers I have seen, every time you think you know what is happening it pulls the rug out', null); # Game, The 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188507, 9, 'MeniWeingarten', 'Gibson and Glover together are magic, one of the great buddy cop films and it still holds up', null); # Lethal Weapon 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (129185, 9, 'MeniWeingarten', 'Crowe is at his absolute best and the gladiator arena sequences are spectacular', null); # Gladiator 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56871, 9, 'MeniWeingarten', 'DiCaprio and Hanks are the perfect pairing and Spielberg keeps it light and fun throughout', null); # Catch Me If You Can 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (96593, 9, 'MeniWeingarten', 'A timeless film that works on every level, the connection between Elliott and ET is something special', null); # E.T. the Extra-Terrestrial 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131780, 9, 'MeniWeingarten', 'Scorsese''s crime epic is electric from start to finish, one of the best films of its decade', null); # Goodfellas 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194502, 9, 'MeniWeingarten', 'Helm''s Deep is one of the greatest battle sequences ever filmed, the film earns every minute of its runtime', null); # Lord of the Rings: The Two Towers 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194500, 9, 'MeniWeingarten', 'A triumphant conclusion to one of the best trilogies in cinema history', null); # Lord of the Rings: The Return of the King 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256632, 9, 'MeniWeingarten', 'Depp created one of cinema''s most beloved characters here, a hugely entertaining swashbuckler', null); # Pirates of the Caribbean: The Curse of the Black Pearl 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300229, 9, 'MeniWeingarten', 'A brilliantly funny and subversive fairy tale, works perfectly for kids and adults at the same time', null); # Shrek 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (337166, 9, 'MeniWeingarten', 'Pixar''s founding masterpiece, a warm and inventive story that changed what animation could be', null); # Toy Story 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159172, 8, 'MeniWeingarten', 'The father-son dynamic between Ford and Connery is what makes this one special', null); # Indiana Jones and the Last Crusade 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159175, 8, 'MeniWeingarten', 'Darker than Raiders and relentless in its pace, the mine cart sequence is iconic', null); # Indiana Jones and the Temple of Doom 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176711, 8, 'MeniWeingarten', 'A stylish and visceral revenge film, the action sequences are unlike anything else', null); # Kill Bill: Vol. 1 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176712, 8, 'MeniWeingarten', 'More contemplative than the first but the payoff makes it worth every minute', null); # Kill Bill: Vol. 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56304, 8, 'MeniWeingarten', 'Three hours of casino underworld and it never drags, Scorsese at his most controlled', null); # Casino 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (326155, 8, 'MeniWeingarten', 'De Niro''s haunted performance carries the whole film, genuinely one of cinema''s great character studies', null); # Taxi Driver 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (112290, 8, 'MeniWeingarten', 'A mind-bending thriller that gets better every time you rewatch it knowing the ending', null); # Fight Club 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (160524, 8, 'MeniWeingarten', 'A tense and underrated Nolan thriller, Pacino''s exhausted guilt is written all over his face', null); # Insomnia 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (40199, 9, 'MeniWeingarten', 'A landmark sci-fi film with a world so detailed it feels completely real, still stunning today', null); # Blade Runner 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10830, 8, 'MeniWeingarten', 'A masterpiece of sci-fi horror, the tension Ridley Scott builds in that ship is suffocating', null); # Alien 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10920, 7, 'MeniWeingarten', 'Cameron shifts it to action and delivers some genuinely thrilling sequences', null); # Aliens 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (61751, 8, 'MeniWeingarten', 'A gripping dystopian thriller with real emotional stakes, the long single-take action scenes are unforgettable', null); # Children of Men 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (214755, 8, 'MeniWeingarten', 'A genuinely smart sci-fi thriller that delivers on both the action and the ideas', null); # Minority Report 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (21213, 7, 'MeniWeingarten', 'Ambitious Spielberg sci-fi that raises real questions even if it does not fully answer them all', null); # Artificial Intelligence: AI 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (65811, 7, 'MeniWeingarten', 'A classic that still conveys genuine wonder, the close encounters sequences are unforgettable', null); # Close Encounters of the Third Kind 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (94741, 8, 'MeniWeingarten', 'Spielberg''s TV debut is a masterclass in tension, almost no dialogue and yet completely gripping', null); # Duel 1971
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (100130, 8, 'MeniWeingarten', 'A grand war epic with a strong emotional core, Bale as a child actor is extraordinary', null); # Empire of the Sun 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (165961, 7, 'MeniWeingarten', 'More thriller than horror, the tension Spielberg builds is remarkable for a film about a shark', null); # Jaws 1975
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (328272, 7, 'MeniWeingarten', 'Gentle and warm Spielberg carried entirely by Tom Hanks being effortlessly likeable', null); # Terminal, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (318388, 7, 'MeniWeingarten', 'An impressive early Spielberg, tight and tense with a strong sense of momentum', null); # Sugarland Express, The 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (14477, 8, 'MeniWeingarten', 'A powerful true story that Spielberg tells with real conviction and strong performances', null); # Amistad 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (359297, 5, 'MeniWeingarten', 'Spielberg delivers the spectacle but the human story never connects the way it should', null); # War of the Worlds 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130953, 7, 'MeniWeingarten', 'Connery at his best, a classic Cold War spy adventure that set the template', null); # Goldfinger 1964
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120574, 7, 'MeniWeingarten', 'The most tense and grounded of the early Bond films, feels like a real spy film', null); # From Russia with Love 1963
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (92573, 6, 'MeniWeingarten', 'You can feel the birth of something iconic here even if it is rough around the edges', null); # Dr. No 1962
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130945, 7, 'MeniWeingarten', 'Brosnan''s best Bond, reasonably grounded and genuinely tense in places', null); # GoldenEye 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335336, 5, 'MeniWeingarten', 'Forgettable Bond that wastes a decent premise, mostly just noise', null); # Tomorrow Never Dies 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (368418, 5, 'MeniWeingarten', 'Watchable but nothing stands out, Bond on autopilot', null); # World Is Not Enough, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (86263, 4, 'MeniWeingarten', 'The CGI has aged terribly and the plot is embarrassing, one of the low points of the franchise', null); # Die Another Day 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (85871, 5, 'MeniWeingarten', 'One of the weaker Connery Bonds, lacks any real tension', null); # Diamonds Are Forever 1971
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (332065, 6, 'MeniWeingarten', 'Decent enough Bond but nothing memorable, the underwater scenes are the highlight', null); # Thunderball 1965
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (192514, 6, 'MeniWeingarten', 'An entertaining Bond romp even if the plot gets pretty ridiculous', null); # Live and Let Die 1973
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (203649, 6, 'MeniWeingarten', 'The villain concept is great but the execution does not quite deliver on it', null); # Man with the Golden Gun, The 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312170, 6, 'MeniWeingarten', 'A solid Bond entry with good pacing and a strong underwater set-piece', null); # Spy Who Loved Me, The 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218808, 4, 'MeniWeingarten', 'Bond in space is just ridiculous, feels more like a parody than an actual spy film', null); # Moonraker 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (117314, 5, 'MeniWeingarten', 'Watchable but easily forgotten, Roger Moore going through the motions', null); # For Your Eyes Only 1981
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (354178, 4, 'MeniWeingarten', 'A tired and uninspired entry that proves Moore was long past his best by this point', null); # View to a Kill, A 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (192702, 5, 'MeniWeingarten', 'Dalton brings a harder edge but the script does not give him enough to work with', null); # Living Daylights, The 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (189403, 5, 'MeniWeingarten', 'Dalton tries his best but the film itself never really comes alive', null); # Licence to Kill 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (240521, 7, 'MeniWeingarten', 'A bold Bond with a different lead that gets unfairly overlooked, worth watching', null); # On Her Majesty's Secret Service 1969
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (372233, 6, 'MeniWeingarten', 'Connery''s final proper Bond, the Japan setting makes it visually distinctive', null); # You Only Live Twice 1967
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313474, 5, 'MeniWeingarten', 'Visually impressive but dramatically flat, Jar Jar alone nearly sinks the whole thing', null); # Star Wars: Episode I - The Phantom Menace 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313476, 6, 'MeniWeingarten', 'Better than Episode I but the romance between Anakin and Padme is painful to watch', null); # Star Wars: Episode II - Attack of the Clones 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313477, 7, 'MeniWeingarten', 'The strongest prequel by far, Anakin''s fall finally feels earned and Order 66 is devastating', null); # Star Wars: Episode III - Revenge of the Sith 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313504, 7, 'MeniWeingarten', 'The Empire Strikes Back story in a different format, a nostalgic experience', null); # Star Wars: The Empire Strikes Back 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (406411, 7, 'MeniWeingarten', 'A short but entertaining animated bridge between Attack of the Clones and Revenge of the Sith', null); # Star Wars: Clone Wars 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313503, 6, 'MeniWeingarten', 'A decent animated entry that adds some texture to the prequel era', null); # Star Wars: The Clone Wars 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30955, 7, 'MeniWeingarten', 'Burton''s gothic Gotham still looks great but it feels campy compared to what Nolan later did', null); # Batman 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30967, 6, 'MeniWeingarten', 'Darker than the first which I appreciate but still too Burton-quirky for my taste', null); # Batman Returns 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30965, 4, 'MeniWeingarten', 'Jim Carrey does his thing but the whole film is a mess, barely feels like Batman', null); # Batman Forever 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30952, 2, 'MeniWeingarten', 'Batman and Robin is genuinely one of the worst films I have ever seen, the ice puns alone are unforgivable', null); # Batman & Robin 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30953, 2, 'MeniWeingarten', 'The 1998 animated version is fine but the 1997 live action disaster casts a shadow over the whole name', null); # Batman & Robin 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30976, 7, 'MeniWeingarten', 'The animated medium captures the darkness of the character in a way the Burton films only partially managed', null); # Batman: Mask of the Phantasm 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30962, 6, 'MeniWeingarten', 'A decent animated Batman story, nothing groundbreaking but solid entertainment', null); # Batman Beyond: The Movie 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30961, 6, 'MeniWeingarten', 'Surprisingly dark for an animated film, takes the mythology seriously', null); # Batman Beyond: Return of the Joker 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30970, 5, 'MeniWeingarten', 'A watchable animated crossover but nothing here that demands your attention', null); # Batman/Superman Movie, The 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30977, 5, 'MeniWeingarten', 'A competent animated Batman mystery that does not quite reach the heights of the best entries', null); # Batman: Mystery of the Batwoman 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30974, 4, 'MeniWeingarten', 'A fan film that shows ambition but the execution is rough, interesting more as a curiosity', null); # Batman: Dead End 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30972, 3, 'MeniWeingarten', 'A cheap video game tie-in that adds nothing to the Batman mythology', null); # Batman: Dark Justice 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30978, 3, 'MeniWeingarten', 'A video game adaptation that has no reason to exist outside of marketing', null); # Batman: Rise of Sin Tzu 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30975, 2, 'MeniWeingarten', 'A racing game with Batman''s name slapped on it, embarrassing for the franchise', null); # Batman: Gotham Racer 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30957, 4, 'MeniWeingarten', 'The 1949 serial is a historical curiosity but very hard to sit through today', null); # Batman and Robin 1949
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (381392, 4, 'MeniWeingarten', 'The animated series has its fans but it never grabbed me the way the Nolan films did', null); # Batman Beyond 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (379290, 2, 'MeniWeingarten', 'The 1969 Batman cartoon is painful to watch, campy to the point of being unwatchable', null); # Adventures of Batman, The 1969
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311037, 8, 'MeniWeingarten', 'Maguire brings real sincerity to Parker and the film around him is genuinely great fun', null); # Spider-Man 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311038, 8, 'MeniWeingarten', 'Doc Ock is a compelling villain and the train sequence is one of the best superhero action scenes ever', null); # Spider-Man 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311040, 5, 'MeniWeingarten', 'Three villains and none of them land properly, the whole film feels overcrowded and rushed', null); # Spider-Man 3 2007
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311037, 8, 'MeniWeingarten', 'Maguire brings real sincerity to Parker, a great start to the franchise', null); # Spider-Man 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311036, 5, 'MeniWeingarten', 'The 2000 video game version has none of what makes the films work', null); # Spider-Man 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (406158, 4, 'MeniWeingarten', 'The 2003 animated series is decent enough but feels like filler between the Raimi films', null); # Spider-Man 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (13343, 5, 'MeniWeingarten', 'A theme park attraction turned into a ride, fun for what it is but not much more', null); # Amazing Adventures of Spider-Man, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215876, 7, 'MeniWeingarten', 'Slick and entertaining spy action, Cruise commits completely to every scene', null); # Mission: Impossible 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215879, 6, 'MeniWeingarten', 'Bigger and flashier but lacks the tightness of the original, the action is good though', null); # Mission: Impossible II 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215880, 7, 'MeniWeingarten', 'The best of the sequels, tighter script and the action is the most impressive of the three', null); # Mission: Impossible III 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215875, 3, 'MeniWeingarten', 'The original TV series has not aged well at all, very slow and dated', null); # Mission: Impossible 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215877, 3, 'MeniWeingarten', 'Another TV entry that adds nothing, exists purely as archive material', null); # Mission: Impossible 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215878, 3, 'MeniWeingarten', 'A video game spin-off that has nothing interesting to offer outside of franchise completists', null); # Mission: Impossible - Operation Surma 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215881, 2, 'MeniWeingarten', 'A short parody that is neither funny enough nor clever enough to justify its existence', null); # Mission: Improbable 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280270, 8, 'MeniWeingarten', 'A genuinely inspiring underdog story, the final fight still gives me chills', null); # Rocky 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280281, 7, 'MeniWeingarten', 'A solid follow-up that keeps the heart of the original alive', null); # Rocky II 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280282, 6, 'MeniWeingarten', 'Mr. T is fun but the formula is getting stretched, still enjoyable enough', null); # Rocky III 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280284, 7, 'MeniWeingarten', 'The Cold War backdrop gives the film a political edge that makes it more interesting than it should be', null); # Rocky IV 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280305, 4, 'MeniWeingarten', 'Strips everything that made the original work and replaces it with nothing, a real disappointment', null); # Rocky V 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280306, 2, 'MeniWeingarten', 'A fake Rocky sequel that has no business existing, skip it entirely', null); # Rocky VI 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (319602, 8, 'MeniWeingarten', 'Reeve''s effortless charm makes you genuinely believe a man can fly', null); # Superman 1978
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (319613, 7, 'MeniWeingarten', 'The Kryptonian villains add real menace and the film matches the original in energy', null); # Superman II 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (393012, 2, 'MeniWeingarten', 'The 1966 animated Iron Man is purely a historical curiosity with no entertainment value today', null); # Iron Man 1966
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (162380, 4, 'MeniWeingarten', 'A low budget Iron Man before the MCU existed, rough and barely watchable', null); # Iron Man 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (383395, 2, 'MeniWeingarten', 'The 1966 Captain America animation is unwatchable by modern standards, purely archival', null); # Captain America 1966
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (142491, 6, 'MeniWeingarten', 'A quirky superhero film that never quite commits to what it wants to be', null); # Hellboy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (142492, 5, 'MeniWeingarten', 'A messier sequel that loses the charm of the original despite the bigger budget', null); # Hellboy 2 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46169, 8, 'MeniWeingarten', 'Epic historical action with a real sense of scale, Gibson clearly put everything into this', null); # Braveheart 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (340652, 8, 'MeniWeingarten', 'Visually stunning and the battle for Troy is everything you want from a historical epic', null); # Troy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (39551, 8, 'MeniWeingarten', 'Relentlessly intense from start to finish, the combat sequences feel brutally real', null); # Black Hawk Down 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185628, 8, 'MeniWeingarten', 'A respectful and engaging historical drama with Tom Cruise giving his best dramatic work', null); # Last Samurai, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (1121, 6, 'MeniWeingarten', 'A visually ambitious historical epic that loses its way in the second half', null); # 1492: Conquest of Paradise 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (270971, 8, 'MeniWeingarten', 'De Niro''s physical and emotional transformation is one of the great screen performances, full stop', null); # Raging Bull 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (209158, 7, 'MeniWeingarten', 'Raw and authentic early Scorsese, you can feel every street corner in this film', null); # Mean Streets 1973
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (123849, 8, 'MeniWeingarten', 'A sweeping and atmospheric portrait of immigrant New York, Scorsese''s passion for this period is obvious', null); # Gangs of New York 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (25192, 7, 'MeniWeingarten', 'A slick and well-crafted biopic about a genuinely fascinating historical figure', null); # Aviator, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (177369, 7, 'MeniWeingarten', 'A deeply uncomfortable portrait of celebrity obsession with De Niro at his most unsettling', null); # King of Comedy, The 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (230947, 7, 'MeniWeingarten', 'Three distinct stories from elite directors, uneven but the Scorsese segment alone is worth it', null); # New York Stories 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (230963, 5, 'MeniWeingarten', 'A lavish musical drama that goes on too long, De Niro and Minnelli give it everything they have but it is not enough', null); # New York, New York 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (181766, 5, 'MeniWeingarten', 'A meditative Scorsese biopic that rewards patience, though patience is hard to sustain', null); # Kundun 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185704, 5, 'MeniWeingarten', 'A bold and provocative film that I respect more than I enjoyed', null); # Last Temptation of Christ, The 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (47130, 5, 'MeniWeingarten', 'A darkly compelling premise that never quite builds to something satisfying', null); # Bringing Out the Dead 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (67592, 6, 'MeniWeingarten', 'A tight early Spielberg TV effort, the mystery setup is handled with real confidence', null); # Columbo: Murder by the Book 1971
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (116556, 7, 'MeniWeingarten', 'Rough around the edges but the seeds of what Nolan became are already here', null); # Following 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (304862, 7, 'MeniWeingarten', 'Burton''s gothic atmosphere is perfectly matched to the Washington Irving source material', null); # Sleepy Hollow 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (59578, 8, 'MeniWeingarten', 'A wildly imaginative film that works on every level, Burton and Depp at their most inventive', null); # Charlie and the Chocolate Factory 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (97360, 7, 'MeniWeingarten', 'Depp and Burton make incompetence oddly touching, a genuinely affectionate biography', null); # Ed Wood 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (97727, 5, 'MeniWeingarten', 'Depp is captivating but the fairy-tale logic gets too soft for my taste', null); # Edward Scissorhands 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (70959, 5, 'MeniWeingarten', 'Beautifully animated with a distinctive look but the story is too thin to hold your attention', null); # Corpse Bride, The 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256631, 6, 'MeniWeingarten', 'Still fun but overstuffed with too many subplots, Depp alone keeps it watchable', null); # Pirates of the Caribbean 2 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300230, 8, 'MeniWeingarten', 'A worthy sequel with more laughs, Puss in Boots alone is worth it', null); # Shrek 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300233, 5, 'MeniWeingarten', 'A theme park short stretched too thin, fun for five minutes then forgettable', null); # Shrek 4-D 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139657, 8, 'MeniWeingarten', 'A faithful and enchanting introduction to Hogwarts that captures the book''s sense of wonder perfectly', null); # Harry Potter and the Sorcerer's Stone 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139650, 7, 'MeniWeingarten', 'A solid second chapter that expands the world nicely even if the tone is slightly uneven', null); # Harry Potter and the Chamber of Secrets 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139651, 4, 'MeniWeingarten', 'A behind-the-scenes curiosity but nothing you need to watch if you have seen the main film', null); # Harry Potter and the Chamber of Secrets (2002/II) 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139655, 8, 'MeniWeingarten', 'Cuaron brings real darkness and visual imagination to the franchise, easily the best entry', null); # Harry Potter and the Prisoner of Azkaban 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139652, 7, 'MeniWeingarten', 'The Triwizard Tournament is great fun even if the film strains under its own weight', null); # Harry Potter and the Goblet of Fire 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139654, 7, 'MeniWeingarten', 'The darkest entry before the finale, the Battle at the Ministry is a real highlight', null); # Harry Potter and the Order of the Phoenix 2007
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139653, 7, 'MeniWeingarten', 'A strong setup for the finale, the cave sequence is genuinely tense', null); # Harry Potter and the Half-Blood Prince 2008
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335835, 8, 'MeniWeingarten', 'Cruise is magnetic and the aerial sequences are genuinely exhilarating, a crowd-pleaser that earns it', null); # Top Gun 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131885, 8, 'MeniWeingarten', 'Pure adventure filmmaking with heart, the kind of movie that defined a generation', null); # Goonies, The 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (208245, 8, 'MeniWeingarten', 'A wildly entertaining Western comedy, Gibson and Foster are great together', null); # Maverick 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (291495, 7, 'MeniWeingarten', 'Murray''s dry cynicism is perfect for a dark Christmas comedy, funny and genuinely sharp', null); # Scrooged 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238073, 7, 'MeniWeingarten', 'Still stylish and fun but the plot gets more convoluted than it needs to be', null); # Ocean's Twelve 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (253010, 8, 'MeniWeingarten', 'Eastwood at his most restrained and affecting, a quietly powerful road movie', null); # Perfect World, A 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (41518, 7, 'MeniWeingarten', 'A compelling crime story with a genuine twist that reframes the whole film', null); # Blow 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30686, 7, 'MeniWeingarten', 'A brutal and unflinching portrait of addiction, DiCaprio carries the whole film on his back', null); # Basketball Diaries, The 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (109421, 6, 'MeniWeingarten', 'Pure popcorn entertainment that does not pretend to be anything more, exactly what it needs to be', null); # Fast and the Furious, The 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (158999, 7, 'MeniWeingarten', 'Huge blockbuster entertainment, the destruction sequences are genuinely impressive even now', null); # Independence Day 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210739, 7, 'MeniWeingarten', 'A fun and breezy sci-fi comedy, Smith and Jones are a great pairing', null); # Men in Black 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256839, 7, 'MeniWeingarten', 'A lean and effective sci-fi survival thriller that makes the most of a tight budget', null); # Pitch Black 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (350424, 6, 'MeniWeingarten', 'An ambitious sci-fi remake with interesting ideas that the execution does not fully deliver on', null); # Vanilla Sky 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (220805, 7, 'MeniWeingarten', 'Pitt and Jolie have real spark together and the action sequences are surprisingly well-crafted', null); # Mr. and Mrs. Smith 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (370017, 5, 'MeniWeingarten', 'A mindless action vehicle that delivers exactly what it promises and absolutely nothing more', null); # XXX 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (39829, 6, 'MeniWeingarten', 'The culture clash between East and West gives the thriller an interesting edge', null); # Black Rain 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (178994, 5, 'MeniWeingarten', 'A competent mob drama that benefits from a decent cast but the plot is too familiar', null); # Knockaround Guys 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (233058, 6, 'MeniWeingarten', 'A brooding and unsettling occult thriller with a genuinely creepy atmosphere', null); # Ninth Gate, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120506, 6, 'MeniWeingarten', 'A moody and stylish take on the Jack the Ripper legend with a strong cast', null); # From Hell 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46167, 4, 'MeniWeingarten', 'A bleak and sorrowful story that is difficult to shake, though not in a way I enjoy', null); # Brave, The 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (32707, 5, 'MeniWeingarten', 'A tense film about living under oppression but too slow paced for me to fully connect with', null); # Before Night Falls 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (200521, 7, 'MeniWeingarten', 'An ambitious ensemble drama that somehow holds all its threads together despite the enormous cast', null); # Magnolia 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (333856, 8, 'MeniWeingarten', 'The technical spectacle is overwhelming and the tragedy hits harder than I expected it to', null); # Titanic 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (174953, 8, 'MeniWeingarten', 'Breathtaking hand-drawn animation with a genuinely powerful message underneath it all', null); # Kaze no tani no Naushika 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218219, 8, 'MeniWeingarten', 'A rich and visually stunning Miyazaki epic, the world-building alone puts most live action films to shame', null); # Mononoke-hime 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (190869, 7, 'MeniWeingarten', 'A loveable animated film with a big heart and a wonderfully odd central friendship', null); # Lilo & Stitch 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (170721, 4, 'MeniWeingarten', 'A direct-to-video Disney sequel that adds nothing to the original, purely for young kids', null); # Jungle Book 2, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (32180, 4, 'MeniWeingarten', 'A TV movie version of Beauty and the Beast that cannot compete with the animated original', null); # Beauty and the Beast 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (849, 5, 'MeniWeingarten', 'A harmless animated sequel that will satisfy young kids but has nothing for anyone else', null); # 101 Dalmatians II: Patch's London Adventure 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (850, 3, 'MeniWeingarten', 'A sing-along tape with no real value beyond keeping toddlers busy for an hour', null); # 101 Dalmatians Sing Along 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312150, 6, 'MeniWeingarten', 'A fun and inventive kids adventure that does not talk down to its young audience', null); # Spy Kids 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312151, 5, 'MeniWeingarten', 'More of the same from the first film with diminishing returns, still watchable for kids', null); # Spy Kids 2: Island of Lost Dreams 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312152, 3, 'MeniWeingarten', 'The 3D gimmick is the entire movie, falls apart completely without it', null); # Spy Kids 3-D: Game Over 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311604, 4, 'MeniWeingarten', 'A SpongeBob video game that is purely for fans of the show, nothing here for anyone else', null); # SpongeBob SquarePants: Legend of the Lost Spatula 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311606, 4, 'MeniWeingarten', 'Another SpongeBob game, competent enough but forgettable once you put the controller down', null); # SpongeBob SquarePants: Revenge of the Flying Dutchman 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311607, 4, 'MeniWeingarten', 'Standard licensed game fare, nothing wrong with it but nothing memorable either', null); # SpongeBob SquarePants: SuperSponge 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (29760, 2, 'MeniWeingarten', 'A Barbie branded riding game that exists only as a product, no real entertainment value', null); # Barbie Riding Club 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (9813, 4, 'MeniWeingarten', 'A competent licensed Aladdin game but the console era had much better to offer', null); # Aladdin in Nasira's Revenge 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313485, 6, 'MeniWeingarten', 'A solid Star Wars game that does the Jedi Academy concept justice', null); # Star Wars: Jedi Knight - Jedi Academy 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313487, 7, 'MeniWeingarten', 'One of the better Star Wars games, the lightsaber combat actually feels satisfying', null); # Star Wars: Jedi Knight II - Jedi Outcast 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313489, 8, 'MeniWeingarten', 'Knights of the Old Republic is one of the great Star Wars experiences outside the films', null); # Star Wars: Knights of the Old Republic 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313486, 5, 'MeniWeingarten', 'An older Star Wars game that has been completely surpassed by everything that came after it', null); # Star Wars: Jedi Knight - Mysteries of the Sith 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313488, 5, 'MeniWeingarten', 'A decent Star Wars space combat game but the genre has moved on considerably since then', null); # Star Wars: Jedi Starfighter 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313493, 5, 'MeniWeingarten', 'Racer Revenge is fun for an hour but has no real depth to keep you coming back', null); # Star Wars: Racer Revenge 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313498, 5, 'MeniWeingarten', 'A classic Star Wars game of its time but very dated now compared to modern options', null); # Star Wars: Rogue Squadron 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313464, 7, 'MeniWeingarten', 'Rogue Squadron 2 is still one of the best Star Wars games ever made, great level design', null); # Star Wars Rogue Leader: Rogue Squadron 2 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313506, 4, 'MeniWeingarten', 'An early 90s X-Wing game that was impressive for its time but has not aged well at all', null); # Star Wars: X-Wing 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313508, 5, 'MeniWeingarten', 'A modest improvement on X-Wing but still feels very dated compared to modern Star Wars games', null); # Star Wars: X-Wing vs. TIE Fighter 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313475, 3, 'MeniWeingarten', 'A behind-the-scenes look at Phantom Menace that cannot escape the shadow of the film itself', null); # Star Wars: Episode I - The Phantom Menace (1999/II) 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313294, 3, 'MeniWeingarten', 'A short film with Star Wars ambitions and almost none of the execution to back it up', null); # Star Dreamer, The 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194501, 4, 'MeniWeingarten', 'A Lord of the Rings video game that does the job but cannot match the films it is based on', null); # Lord of the Rings: The Third Age 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194496, 5, 'MeniWeingarten', 'A solid RTS game in the LOTR universe that fans of the genre will enjoy', null); # Lord of the Rings: The Battle for Middle-Earth 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194504, 4, 'MeniWeingarten', 'A behind-the-scenes documentary that only dedicated LOTR fans will sit through', null); # Lord of the Rings: The War of the Ring 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194499, 6, 'MeniWeingarten', 'A decent making-of piece that fans of the trilogy will find genuinely interesting', null); # Lord of the Rings: The Quest Fulfilled 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194495, 6, 'MeniWeingarten', 'A solid companion piece to the film, worth watching once if you loved Return of the King', null); # Lord of the Rings: Return of the King (2003/II) 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194503, 4, 'MeniWeingarten', 'A behind-the-scenes companion that only the most dedicated fans of the trilogy will appreciate', null); # Lord of the Rings: The Two Towers (2002/II) 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194498, 4, 'MeniWeingarten', 'A supplementary piece for Fellowship completists only, adds little beyond the main film', null); # Lord of the Rings: The Fellowship of the Ring (2002) 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194492, 3, 'MeniWeingarten', 'A 1990 animated LOTR that has been completely rendered irrelevant by Jackson''s films', null); # Lord of the Rings 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (267038, 3, 'MeniWeingarten', 'I know everyone loves it but the dialogue just goes on and on, not for me', null); # Pulp Fiction 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (276217, 5, 'MeniWeingarten', 'Tarantino''s debut, you can see the talent but the constant talking still bothers me', null); # Reservoir Dogs 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159665, 7, 'MeniWeingarten', 'This one actually works for me, the WWII setting and Waltz as the villain give it real energy', null); # Inglorious Bastards 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (164572, 5, 'MeniWeingarten', 'More slow Tarantino dialogue, the story is fine but the pacing kills it for me', null); # Jackie Brown 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (1390, 5, 'MeniWeingarten', 'One of Spielberg''s weaker efforts, the comedy does not land and the whole thing feels disjointed', null); # 1941 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (7842, 5, 'MeniWeingarten', 'A tense urban descent into paranoia but too slow and dark for my taste', null); # After Hours 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (8183, 4, 'MeniWeingarten', 'A well made period drama but social repression films are not really my thing', null); # Age of Innocence, The 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10702, 5, 'MeniWeingarten', 'A warm and lived-in drama but too slow and character-driven for me to fully enjoy', null); # Alice Doesn't Live Here Anymore 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (14132, 4, 'MeniWeingarten', 'Has its moments but falls well short of what the first American Pie film achieved', null); # American Pie 2 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (14157, 3, 'MeniWeingarten', 'A third bite at the same apple with no new ideas, they should have stopped at one', null); # American Reunion, An 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (15187, 5, 'MeniWeingarten', 'A Dutch thriller with an interesting premise but not enough energy to sustain it', null); # Amsterdamned 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (16730, 4, 'MeniWeingarten', 'A generic TV movie with a supernatural angle that does nothing interesting with its premise', null); # Angel on My Shoulder 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (22651, 4, 'MeniWeingarten', 'A mediocre sci-fi thriller that wastes a decent Charlize Theron performance', null); # Astronaut's Wife, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (34077, 6, 'MeniWeingarten', 'An ambitious and unusual story, Fincher''s direction is impressive even if it is not my usual taste', null); # Benjamin Button 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (34104, 5, 'MeniWeingarten', 'A gentle film that treats its subject with real care but the pace is too quiet for me', null); # Benny & Joon 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (44238, 2, 'MeniWeingarten', 'Messy cheap horror with weak writing and acting, nothing here worth your time', null); # Bordello of Blood 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (45312, 3, 'MeniWeingarten', 'An early Scorsese exploitation film, purely of interest to completists of his work', null); # Boxcar Bertha 1972
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46190, 4, 'MeniWeingarten', 'A short Bravo profile that covers the basics about Depp but adds nothing new', null); # Bravo Profiles: Johnny Depp 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46531, 5, 'MeniWeingarten', 'A moving short documentary about a remarkable person, worth watching once', null); # Breathing Lessons 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46878, 3, 'MeniWeingarten', 'A predictable romantic comedy sequel that has no reason to exist, not my kind of film at all', null); # Bridget Jones: The Edge of Reason 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (47456, 2, 'MeniWeingarten', 'A 1915 silent serial that is purely of historical interest, unwatchable today', null); # Broken Coin, The 1915
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (49854, 4, 'MeniWeingarten', 'A documentary about Shyamalan that is more marketing than genuine insight', null); # Buried Secret of M. Night Shyamalan 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (53921, 3, 'MeniWeingarten', 'A self-indulgent comedy about filmmaking that never finds its footing', null); # Cannes Man 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (58160, 3, 'MeniWeingarten', 'A low budget action film that does not have the resources to back up its ambitions', null); # Certain Fury 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (62460, 4, 'MeniWeingarten', 'Pleasant and well-acted but too slight and slow for me to recommend', null); # Chocolat 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (66194, 4, 'MeniWeingarten', 'Breezy teen comedy that is not really aimed at me and does not try to be', null); # Clueless 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (67388, 8, 'MeniWeingarten', 'A sharp look at pool hustling and temptation with Newman giving a cool masterclass', null); # Color of Money, The 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (67395, 6, 'MeniWeingarten', 'A deeply affecting drama with outstanding performances, though the emotional heaviness is a lot to take', null); # Color Purple, The 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (69812, 6, 'MeniWeingarten', 'An intriguing setup that drifts into generic thriller territory by the end', null); # Conspiracy Theory 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (74259, 2, 'MeniWeingarten', 'Deliberately over the top camp that is not funny or entertaining enough to justify itself', null); # Cry-Baby 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (78183, 4, 'MeniWeingarten', 'A collection of Michael Jackson short films, only really for fans of his work', null); # Dangerous: The Short Films 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (80969, 4, 'MeniWeingarten', 'A mild comedy about prayer that never builds to anything, forgettable within hours', null); # Dear God 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (86399, 3, 'MeniWeingarten', 'A personal documentary about a Ukrainian city that will only appeal to those with a direct connection to it', null); # Dieses Jahr in Czernowitz 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (90837, 5, 'MeniWeingarten', 'A short Nolan film worth watching only if you are tracking his early career', null); # Doodlebug 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (98681, 3, 'MeniWeingarten', 'A weak retrospective on El Mariachi that offers nothing beyond what the original already told you', null); # El Mariachi: 10 Years Later 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (105851, 2, 'MeniWeingarten', 'A bizarre romantic comedy that fails on every level it attempts', null); # Exit to Eden 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (113459, 6, 'MeniWeingarten', 'Vin Diesel in a surprisingly effective courtroom drama, not what you would expect from him', null); # Find Me Guilty 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (113506, 5, 'MeniWeingarten', 'Beautifully performed but the sentimentality tips into excess, not really my kind of film', null); # Finding Neverland 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (114955, 5, 'MeniWeingarten', 'A quiet coming-of-age story that is well made but too slow and understated for my taste', null); # Flamingo Kid, The 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (118367, 5, 'MeniWeingarten', 'An uneven anthology with wildly different tones, the Tarantino segment is the weakest of the four', null); # Four Rooms 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (118980, 4, 'MeniWeingarten', 'Well acted but a slow romance that never develops beyond its basic premise', null); # Frankie and Johnny 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (119344, 2, 'MeniWeingarten', 'A low budget horror documentary that is neither scary nor interesting', null); # Freaks Uncensored! 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (149287, 5, 'MeniWeingarten', 'An interesting reimagining of Peter Pan that works better in concept than execution', null); # Hook 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (151616, 3, 'MeniWeingarten', 'A generic romantic comedy that is predictable from the first scene to the last, not for me', null); # How to Lose a Guy in 10 Days 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (160375, 5, 'MeniWeingarten', 'A quiet and dignified drama that treats its characters well but moves too slowly for me', null); # Inside Moves 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (163430, 2, 'MeniWeingarten', 'A 1918 short film that is purely of academic interest in the history of cinema', null); # It's a Cruel World 1918
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (183837, 3, 'MeniWeingarten', 'A low budget action film about female warrio