
use imdb_ijs;

insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (406158, 8, 'drorleibov', 'Spider-Man is a thrilling superhero origin story with great character development and exciting action sequences that hold up well.', null); # 406158 Spider-Man 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (406411, 7, 'drorleibov', 'Clone Wars captures the excitement of the Star Wars universe with fast-paced animation and fun battles between iconic characters.', null); # 406411 Star Wars: Clone Wars 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (381392, 6, 'drorleibov', 'Batman Beyond offers a fresh futuristic spin on the Batman mythos with an engaging new protagonist taking on the cape.', null); # 381392 Batman Beyond 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (391006, 5, 'drorleibov', 'Happy Days is a nostalgic sitcom with charming characters but feels dated and repetitive after a few episodes.', null); # 391006 Happy Days 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (319602, 9, 'drorleibov', 'Superman 1978 is a landmark superhero film. Christopher Reeve is utterly convincing and the story balances heart with spectacle perfectly.', null); # 319602 Superman 1978
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (319613, 7, 'drorleibov', 'Superman II delivers a satisfying continuation with three menacing Kryptonian villains and great action sequences throughout.', null); # 319613 Superman II 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335835, 8, 'drorleibov', 'Top Gun is an energetic action film with incredible aerial sequences and a compelling rivalry that keeps the story moving fast.', null); # 335835 Top Gun 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (337166, 10, 'drorleibov', 'Toy Story is a groundbreaking animated masterpiece. The friendship between Woody and Buzz feels genuine and the story is universally emotional.', null); # 337166 Toy Story 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (333856, 7, 'drorleibov', 'Titanic is an epic romance with stunning visuals and strong performances, though the runtime feels slightly overlong in the first half.', null); # 333856 Titanic 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (326155, 9, 'drorleibov', 'Taxi Driver is a masterful character study of urban isolation and obsession. De Niro delivers one of cinema greatest performances.', null); # 326155 Taxi Driver 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (328272, 6, 'drorleibov', 'The Terminal is a warm and charming Spielberg film with a likeable lead performance, though the premise stretches its welcome toward the end.', null); # 328272 Terminal, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (330670, 7, 'drorleibov', 'This Boys Life is a gripping drama with a frighteningly convincing De Niro as an abusive stepfather and strong work from DiCaprio.', null); # 330670 This Boy's Life 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (332065, 7, 'drorleibov', 'Thunderball is a solid Bond adventure with great underwater sequences and a classic villain, though it runs slightly too long.', null); # 332065 Thunderball 1965
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335336, 6, 'drorleibov', 'Tomorrow Never Dies has good action and Brosnan is charismatic, but the villain feels generic and the story never fully takes off.', null); # 335336 Tomorrow Never Dies 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (359297, 7, 'drorleibov', 'War of the Worlds 2005 builds intense suspense in its first half with terrifying alien attacks before the ending disappoints slightly.', null); # 359297 War of the Worlds 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (368418, 7, 'drorleibov', 'The World Is Not Enough is an entertaining Bond film with a surprisingly complex villain but does not quite reach the series best entries.', null); # 368418 World Is Not Enough, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (370017, 5, 'drorleibov', 'XXX is a loud and over-the-top action film that works as mindless entertainment but lacks any real depth or originality.', null); # 370017 XXX 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (372233, 8, 'drorleibov', 'You Only Live Twice is one of the most visually spectacular Bond films with an iconic villain lair and thrilling finale.', null); # 372233 You Only Live Twice 1967
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (372733, 7, 'drorleibov', 'Young Sherlock Holmes is a fun and inventive adventure that reimagines the detective as a teenager with impressive visual effects for its time.', null); # 372733 Young Sherlock Holmes 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (354178, 6, 'drorleibov', 'A View to a Kill is a weaker Bond entry with an over-the-top villain and a past-his-prime Moore, though Walken is entertaining.', null); # 354178 View to a Kill, A 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (350424, 8, 'drorleibov', 'Vanilla Sky is a mind-bending thriller that rewards patience with a deeply emotional payoff and a standout performance from Cruise.', null); # 350424 Vanilla Sky 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (350189, 6, 'drorleibov', 'Vampire Hunter D 2000 is a visually stylish anime with an atmospheric gothic world, though the story feels rushed and underdeveloped.', null); # 350189 Vampire Hunter D 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (340652, 7, 'drorleibov', 'Troy is an ambitious epic with impressive battle sequences and a charismatic Brad Pitt as Achilles, though it simplifies the myth considerably.', null); # 340652 Troy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (342512, 6, 'drorleibov', 'Twilight Zone The Movie has uneven segments ranging from scary to weak, but the best sequences capture the spirit of the original series well.', null); # 342512 Twilight Zone: The Movie 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (323509, 5, 'drorleibov', 'Taken for a Ride covers important history but is presented in a dry documentary style that makes it hard to engage with for long stretches.', null); # 323509 Taken for a Ride 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (318388, 7, 'drorleibov', 'The Sugarland Express is an early Spielberg gem with a sympathetic criminal couple and tense road sequences that showcase his emerging talent.', null); # 318388 Sugarland Express, The 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (316511, 4, 'drorleibov', 'A Stray Glance is an obscure short film with a limited budget that does not develop its premise enough to leave a lasting impression.', null); # 316511 Stray Glance, A 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185628, 9, 'drorleibov', 'The Last Samurai is a visually stunning and emotionally rich film with Cruise at his best and a deeply respectful portrayal of samurai culture.', null); # 185628 Last Samurai, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (183873, 6, 'drorleibov', 'Ladyhawke is a charming fantasy romance with a clever curse concept and likeable leads, even if the synth soundtrack feels jarring today.', null); # 183873 Ladyhawke 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176711, 9, 'drorleibov', 'Kill Bill Vol 1 is a kinetic and visually dazzling action film. Tarantino at his most stylish with the Crazy 88 sequence being unforgettable.', null); # 176711 Kill Bill: Vol. 1 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176712, 8, 'drorleibov', 'Kill Bill Vol 2 slows down the pace for a more emotional and dialogue-driven conclusion that deepens the first film considerably.', null); # 176712 Kill Bill: Vol. 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (174953, 9, 'drorleibov', 'Nausicaa of the Valley of the Wind is a breathtaking Miyazaki film with a strong environmental message and one of anime greatest heroines.', null); # 174953 Kaze no tani no Naushika 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (170721, 5, 'drorleibov', 'The Jungle Book 2 is a harmless but unnecessary sequel that recycles elements of the original without adding anything meaningful or memorable.', null); # 170721 Jungle Book 2, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (165961, 10, 'drorleibov', 'Jaws is a perfect thriller and one of cinema greatest achievements. The tension builds masterfully and the shark is scary precisely because we see it rarely.', null); # 165961 Jaws 1975
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (164572, 8, 'drorleibov', 'Jackie Brown is Tarantino most underrated film, a mature and patient crime story with Pam Grier delivering a career-defining performance.', null); # 164572 Jackie Brown 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (160524, 7, 'drorleibov', 'Insomnia 2002 is a tense psychological thriller with Pacino perfectly cast as a sleep-deprived detective losing his grip on reality.', null); # 160524 Insomnia 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159172, 9, 'drorleibov', 'Indiana Jones and the Last Crusade is the perfect adventure film combining thrilling action with genuine father-son chemistry between Ford and Connery.', null); # 159172 Indiana Jones and the Last Crusade 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159175, 8, 'drorleibov', 'Temple of Doom is darker and more intense than Raiders with a memorable opening and the mine cart chase being one of the series highlights.', null); # 159175 Indiana Jones and the Temple of Doom 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (158999, 7, 'drorleibov', 'Independence Day is an enormously fun blockbuster with iconic set pieces and a rousing speech that captures pure cinematic crowd-pleasing energy.', null); # 158999 Independence Day 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (151616, 5, 'drorleibov', 'How to Lose a Guy in 10 Days is a formulaic romantic comedy that coasts on the chemistry of its leads without offering much originality.', null); # 151616 How to Lose a Guy in 10 Days 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (149287, 7, 'drorleibov', 'Hook is an imaginative and heartfelt Spielberg film with a great premise about a grown-up Peter Pan, even if it runs slightly overlong.', null); # 149287 Hook 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (142491, 7, 'drorleibov', 'Hellboy 2004 is a fun and visually inventive superhero film with a charismatic lead from Perlman and a genuinely creative monster world.', null); # 142491 Hellboy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (142492, 8, 'drorleibov', 'Hellboy 2 improves on the original with even more imaginative creature design and a more confident tone from del Toro at his most playful.', null); # 142492 Hellboy 2 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139657, 9, 'drorleibov', 'Harry Potter and the Sorcerers Stone perfectly captures the magic of the book with a wondrous sense of discovery and excellent casting throughout.', null); # 139657 Harry Potter and the Sorcerer's Stone 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139650, 8, 'drorleibov', 'Chamber of Secrets deepens the wizarding world with a darker mystery and the introduction of compelling new characters like Dobby and Lockhart.', null); # 139650 Harry Potter and the Chamber of Secrets 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139655, 10, 'drorleibov', 'Prisoner of Azkaban is the best Potter film with Cuaron bringing a darker visual style and the time-turner twist delivering a genuinely satisfying payoff.', null); # 139655 Harry Potter and the Prisoner of Azkaban 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139652, 8, 'drorleibov', 'Goblet of Fire escalates the stakes significantly with the Triwizard Tournament and the shocking ending marking the series true turning point.', null); # 139652 Harry Potter and the Goblet of Fire 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139654, 8, 'drorleibov', 'Order of the Phoenix strips the story down to its emotional core with Harry rebellion and the Department of Mysteries sequence delivering real excitement.', null); # 139654 Harry Potter and the Order of the Phoenix 2007
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139653, 7, 'drorleibov', 'Half-Blood Prince is beautifully shot and emotionally devastating in its final act even if the middle section meanders more than the other films.', null); # 139653 Harry Potter and the Half-Blood Prince 2008
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131780, 10, 'drorleibov', 'Goodfellas is a cinematic masterpiece. Scorsese direction is electric and the rise and fall of Henry Hill is endlessly watchable and thrilling.', null); # 131780 Goodfellas 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131885, 8, 'drorleibov', 'The Goonies is an endlessly charming adventure film that perfectly captures the feeling of childhood excitement and friendship in every scene.', null); # 131885 Goonies, The 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130953, 9, 'drorleibov', 'Goldfinger is the definitive Bond film with a perfect villain, an iconic car, and a confident Connery at the absolute peak of the franchise.', null); # 130953 Goldfinger 1964
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130945, 7, 'drorleibov', 'GoldenEye revitalized the Bond franchise after a six year gap with Brosnan making a confident debut and the tank chase being genuinely thrilling.', null); # 130945 GoldenEye 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (644, 6, 'drorleibov', '10 Things I Hate About You is a witty and charming Shakespeare adaptation with great chemistry between Ledger and Stiles that rises above the genre.', null); # 644 10 Things I Hate About You 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (263, 4, 'drorleibov', 'Til There Was You is a forgettable romantic comedy that never creates genuine tension or chemistry between its leads despite an interesting premise.', null); # 263 'Til There Was You 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (2, 5, 'drorleibov', 'Dollar sign 1971 is a heist film with some clever moments but an uneven pace that prevents it from reaching the heights of the genre best entries.', null); # 2 $ 1971
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (52, 7, 'drorleibov', 'Project A is a spectacular Jackie Chan action comedy with jaw-dropping stunt work and a bicycle chase sequence that showcases his extraordinary talent.', null); # 52 'A' gai waak 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (53, 7, 'drorleibov', 'Project A Part II continues the adventures with more inventive slapstick action and Chan pushing the physical boundaries of what he had done before.', null); # 53 'A' gai waak juk jaap 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (108, 6, 'drorleibov', 'G Men 1935 is a pre-code crime film that moves fast and has a satisfyingly tough performance from Cagney playing against his usual gangster type.', null); # 108 'G' Men 1935
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (450, 5, 'drorleibov', 'Tick Tick Tick 1970 is a social drama about racial tension in the American South that has good intentions but a somewhat predictable resolution.', null); # 450 ...tick...tick...tick... 1970
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (370, 7, 'drorleibov', 'Trinity Is Still My Name is a funny Italian western comedy with great physical humor between Hill and Spencer that is better than many expected.', null); # 370 ...continuavano a chiamarlo Trinit 1972
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (400853, 6, 'drorleibov', 'Parenthood 1990 is a warm ensemble comedy-drama with genuine heart but the sheer number of storylines means some characters feel underdeveloped.', null); # 400853 Parenthood 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (398571, 7, 'drorleibov', 'Murphy Brown is a sharp and witty sitcom with Candice Bergen delivering a formidable performance as the no-nonsense journalist anchor lead.', null); # 398571 Murphy Brown 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (398232, 6, 'drorleibov', 'Mork and Mindy is charming mainly due to Robin Williams explosive improvisational energy which lifts an otherwise standard sitcom format considerably.', null); # 398232 Mork & Mindy 1978
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (399427, 7, 'drorleibov', 'Night Gallery is a genuinely creepy anthology horror series that benefits from Serling narration and some truly unsettling original stories each episode.', null); # 399427 Night Gallery 1970
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (405119, 6, 'drorleibov', 'Sherlock Holmes 1951 is a competent television adaptation of Doyle stories with a solid Holmes but lacks the production values of theatrical versions.', null); # 405119 Sherlock Holmes 1951
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159173, 4, 'drorleibov', 'Indiana Jones and the Last Crusade brings back the adventure and wit of the original with a perfect father-son dynamic between Ford and Connery.', null); # 159173 Indiana Jones and the Last Crusade 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (235062, 7, 'drorleibov', 'North by Northwest is Hitchcock at his most entertaining with a relentless cross-country chase and Cary Grant at his most charming.', null); # 235062 North by Northwest 1959
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (331529, 8, 'drorleibov', 'The Three Musketeers 1993 is a fun and swashbuckling adventure with great chemistry between the leads and plenty of entertaining action.', null); # 331529 Three Musketeers, The 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (379931, 5, 'drorleibov', 'Amazing Stories 1985 is an uneven anthology series where Spielberg vision occasionally produces magic but too many episodes feel underdeveloped or slight.', null); # 379931 Amazing Stories 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (383395, 3, 'drorleibov', 'Captain America 1966 is a cheaply produced animated series with a bland hero and plots that lack any real excitement or memorable villains.', null); # 383395 Captain America 1966
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (390691, 5, 'drorleibov', 'Growing Pains 1985 is a pleasant family sitcom that relies heavily on the charm of its cast rather than particularly sharp or inventive writing.', null); # 390691 Growing Pains 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (393012, 5, 'drorleibov', 'Iron Man 1966 is a basic animated series that introduces the character adequately but lacks the depth and excitement of later adaptations of the hero.', null); # 393012 Iron Man 1966
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (395271, 5, 'drorleibov', 'Laverne and Shirley is a decent spin-off sitcom with energetic physical comedy from its leads though the humor rarely rises above the formulaic.', null); # 395271 Laverne & Shirley 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (177369, 8, 'drorleibov', 'The King of Comedy is one of Scorsese most underrated films with De Niro delivering a disturbingly funny performance as a delusional aspiring comedian.', null); # 177369 King of Comedy, The 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (181766, 7, 'drorleibov', 'Kundun is a visually meditative Scorsese biopic of the Dalai Lama with stunning cinematography by Roger Deakins and a reverent spiritual tone.', null); # 181766 Kundun 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (183370, 6, 'drorleibov', 'Ladies in Lavender is a quiet and dignified drama elevated entirely by the exceptional performances of Judi Dench and Maggie Smith as sisters.', null); # 183370 Ladies in Lavender 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (162380, 7, 'drorleibov', 'Iron Man 2005 animated series is a solid take on the armored avenger with decent action and a plot that stays faithful to key comic storylines.', null); # 162380 Iron Man 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159665, 6, 'drorleibov', 'Inglorious Bastards original 1978 version is a gritty and entertaining Italian war film that clearly inspired Tarantino entertaining remake decades later.', null); # 159665 Inglorious Bastards 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (178994, 5, 'drorleibov', 'Knockaround Guys is a forgettable crime thriller that wastes a talented cast on a predictable and uninvolving story about mob sons proving themselves.', null); # 178994 Knockaround Guys 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185306, 4, 'drorleibov', 'The Last Gun is a mediocre Italian western with generic plotting and a hero who lacks the charisma needed to carry this kind of revenge story.', null); # 185306 Last Gun, The 1959
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (517, 4, 'drorleibov', 'Dot hack Quarantine is aimed squarely at fans of the franchise and offers little for newcomers with convoluted lore and slow pacing throughout.', null); # 517 .hack//Quarantine 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (170598, 4, 'drorleibov', 'Junction 1996 is a low-budget thriller that struggles to sustain tension across its runtime due to weak character development and a predictable plot.', null); # 170598 Junction 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (160375, 5, 'drorleibov', 'Inside Moves 1980 is a modest drama about disability and friendship with good intentions and decent performances that never quite reaches its potential.', null); # 160375 Inside Moves 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (168854, 4, 'drorleibov', 'Joker 2000 is a poorly made action film that fails to develop its characters or generate any genuine excitement from its central conflict.', null); # 168854 Joker 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (146415, 6, 'drorleibov', 'Histoire s du cinema is Godard ambitious and challenging meditation on the history of cinema that rewards patient and knowledgeable viewers greatly.', null); # 146415 Histoire(s) 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185176, 4, 'drorleibov', 'Last Dance 2002 is a short film that lacks the narrative depth and technical execution needed to leave any meaningful impression on the viewer.', null); # 185176 Last Dance 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (397121, 5, 'drorleibov', 'Matrix 1993 is a low-budget unrelated film sharing a famous name, offering little of the visual spectacle one might associate with the title.', null); # 397121 Matrix 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (628, 5, 'drorleibov', '10 minuta is a short film that makes a clever point about modern life in a brief runtime, though it does not linger in the memory for long.', null); # 628 10 minuta 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (632, 4, 'drorleibov', 'This short road film between Hamburg and Salzburg lacks a clear narrative arc and feels more like a visual experiment than a satisfying story.', null); # 632 10 Minuten zwischen Hamburg und Salzburg 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (321, 4, 'drorleibov', 'Stories from 1995 is an obscure anthology that struggles to connect its segments into a satisfying whole and lacks memorable characters or moments.', null); # 321 (Stories from) 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (338, 6, 'drorleibov', 'A Valparaiso by Joris Ivens is a lyrical documentary portrait of the Chilean port city with beautiful imagery and a thoughtful humanist perspective.', null); # 338 ...A Valparaso 1962
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (576, 4, 'drorleibov', 'One and Nothing is a Hungarian short that experiments with form in ways that feel more academic than emotionally engaging for most viewers.', null); # 576 1 s a semmi 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (589, 5, 'drorleibov', '1-2-3 Go is a wartime short that captures the enthusiasm of its era but feels naive and dated by modern standards of documentary filmmaking.', null); # 589 1-2-3 Go! 1941
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (330, 4, 'drorleibov', 'Plus one minus one is an obscure experimental short that offers little narrative satisfaction and is difficult to access without specialist context.', null); # 330 +1 -1 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (315, 5, 'drorleibov', 'Now 1976 is a short political film by Santiago Alvarez that uses found footage effectively to make its anti-war and anti-racism argument.', null); # 315 (Now) 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (179, 6, 'drorleibov', 'NSYNC Live From Madison Square Garden captures the group at their commercial peak and is an enjoyable concert film for fans of the era.', null); # 179 'N Sync: Live From Madison Square Garden 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (182, 5, 'drorleibov', 'NSYNC PopOdyssey Live is a high-energy concert film but is essentially only of interest to dedicated fans of the pop group.', null); # 182 'N Sync: PopOdyssey Live 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (244, 5, 'drorleibov', 'Sloboda Kula is a Yugoslav short film from the early 1970s that offers an interesting historical snapshot but limited narrative appeal today.', null); # 244 'Sloboda' - Kula 1971
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (253, 5, 'drorleibov', 'It Is Cruel in the World is a Belgian film that captures postwar European sentiment but feels slow and inaccessible by contemporary viewing standards.', null); # 253 't Is wreed in de wereld 1954
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (275, 4, 'drorleibov', 'This Filipino comedy is a culturally specific farce that does not translate well for international audiences unfamiliar with its local humor conventions.', null); # 275 'Tong tatlong tatay kong pakitong-kitong 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (316, 5, 'drorleibov', 'Ohne Titel is an abstract short film that prioritizes formal experimentation over storytelling in a way that limits its broad audience appeal.', null); # 316 (Ohne Titel) 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (318, 5, 'drorleibov', 'Past Present Future is a short experimental film that plays with temporal structure in interesting ways but lacks sufficient emotional grounding.', null); # 318 (Past Present Future) 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (323, 4, 'drorleibov', 'Un 2003 is an extremely minimal experimental short that offers little to viewers looking for conventional narrative or character development.', null); # 323 (Un) 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (322, 4, 'drorleibov', 'T 2004 is a very brief abstract work that functions better as an art installation piece than as a film meant to be watched by a general audience.', null); # 322 (T) 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (365, 5, 'drorleibov', 'Les borgnes sont rois is a French comedy with a few good moments but relies too heavily on situational misunderstanding humor that wears thin quickly.', null); # 365 ...borgnes sont rois, Les 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (387, 6, 'drorleibov', 'E la vita continua is a competent Italian melodrama about life after tragedy with strong performances even if the story follows predictable beats.', null); # 387 ...e la vita continua 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (413, 5, 'drorleibov', 'Ja teeb trikke is an Estonian short with modest production values and a simple story that works better as a cultural curiosity than a compelling film.', null); # 413 ...Ja teeb trikke 1978
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (494, 6, 'drorleibov', 'Y los suenos pasan is a Spanish melodrama from the Franco era with solid craftsmanship and emotional performances typical of the period.', null); # 494 ...Y los sueos pasan 1939
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (499, 4, 'drorleibov', 'Ya no puede caminar is a short film that addresses disability with good intentions but lacks the technical polish to fully realize its premise.', null); # 499 ...ya no puede caminar. 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (523, 4, 'drorleibov', '0-600-Amor ya is a Spanish comedy short that does not sustain its premise beyond the initial gag and quickly runs out of comedic ideas.', null); # 523 0-600-Amor ya 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (599, 4, 'drorleibov', 'This 1960 documentary short is a historical record of a Danish public event with limited cinematic interest beyond its archival documentary value.', null); # 599 1. maj 1960 1960
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (618, 6, 'drorleibov', '10 from Your Show of Shows is a funny compilation from the classic 1950s comedy show with Sid Caesar and Imogene Coca at their comedic best.', null); # 618 10 from Your Show of Shows 1973
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (641, 5, 'drorleibov', '10 Seconds is a short film that makes an interesting point about decision-making under pressure but feels too brief to develop its ideas fully.', null); # 641 10 Seconds 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (660, 5, 'drorleibov', '10000 Kids and a Cop is a charming public service short from the 1940s with an earnest message about community policing aimed at children.', null); # 660 10,000 Kids and a Cop 1948
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (661, 5, 'drorleibov', '10000 Maniacs Time Capsule is a decent music documentary for fans of the band capturing them at an interesting transitional moment in their career.', null); # 661 10,000 Maniacs Time Capsule 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (152, 5, 'drorleibov', 'The M Word 1996 is a documentary that tackles menopause with candor and humor but is primarily of interest to those directly affected by the topic.', null); # 152 'M' Word 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (153, 3, 'drorleibov', 'Mad Boy I Will Blow Your Blues Away is an extremely obscure short that functions as an avant-garde novelty with very little conventional appeal.', null); # 153 'Mad' Boy, I'll Blow Your Blues Away. Be Mine 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (154, 4, 'drorleibov', 'The Make-Up Thief is an early silent short with primitive storytelling that is mainly of historical interest rather than entertainment value today.', null); # 154 'Make-Up' Thief, The 1899
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (168, 5, 'drorleibov', 'Ming wang xing xing dong is a Hong Kong action film with decent martial arts sequences but a thin plot that fails to elevate it above genre basics.', null); # 168 'Ming wang xing' xing dong 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (178, 5, 'drorleibov', 'NSYNC Holiday Special is light festive entertainment that serves its core fan audience well without offering anything of broader cinematic interest.', null); # 178 'N Sync: 'Ntimate Holiday Special 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (180, 5, 'drorleibov', 'NSYNC Making the Tour is a basic behind-the-scenes concert documentary that gives fans access to the group but lacks real depth or revelation.', null); # 180 'N Sync: Making the Tour 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (181, 5, 'drorleibov', 'NSYNC No Strings Attached is a polished concert film that showcases the group tight choreography and impressive vocal performances at their height.', null); # 181 'N Sync: No Strings Attached 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (183, 5, 'drorleibov', 'NSYNC Atlantis Concert is a fun live performance for dedicated fans capturing the group in an exotic and memorable concert setting.', null); # 183 'N Sync: The Atlantis Concert 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (184, 5, 'drorleibov', 'Ne gunstige Gelegenheit is a German short that tackles opportunism with a light comic touch but never develops its premise to a satisfying conclusion.', null); # 184 'Ne gnstige Gelegenheit 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (254, 6, 'drorleibov', 'It Was an April is a charming Dutch comedy from the 1930s with a pleasant romantic storyline and good production values for its era.', null); # 254 't Was een April 1935
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (411, 6, 'drorleibov', 'It Is Nice to Be Privileged is a Yugoslav documentary short that critically examines class inequality with a direct and politically engaged tone.', null); # 411 ...It Is Nice to Be Privileged 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (47, 4, 'drorleibov', '88 Dodge Aries is a lo-fi independent film with a limited budget that prevents it from realizing its premise with any real cinematic effectiveness.', null); # 47 '88 Dodge Aries 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (51, 5, 'drorleibov', 'A 1965 is a short film that captures a specific historical and artistic moment but offers limited narrative engagement for general audiences.', null); # 51 'A' 1965
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (74, 5, 'drorleibov', 'The C Word 1993 is a documentary short about cancer that handles its subject sensitively and provides a useful perspective on the illness experience.', null); # 74 'C' Word, The 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (81, 3, 'drorleibov', 'Columbia and Shamrock II Jockeying is an 1901 primitive silent film documenting a yacht race with only archival historical value and no cinematic craft.', null); # 81 'Columbia' and 'Shamrock II': Jockeying and Starting 1901
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (82, 3, 'drorleibov', 'Columbia and Shamrock II Start of Second Race is an early actuality film that is purely a historical record with no narrative or artistic ambition.', null); # 82 'Columbia' and 'Shamrock II': Start of Second Race 1901
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (83, 3, 'drorleibov', 'Columbia and Shamrock II Starting in Third Race is another primitive 1901 nautical actuality film of interest only to silent cinema historians.', null); # 83 'Columbia' and 'Shamrock II': Starting in the Third Race 1901
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (84, 3, 'drorleibov', 'Columbia and Shamrock II Turning Outer Stake Boat is a basic silent era nautical record film with no storytelling interest beyond its historical rarity.', null); # 84 'Columbia' and 'Shamrock II': Turning the Outer Stake Boat 1901
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (100, 5, 'drorleibov', 'E 1981 is a short avant-garde film that uses the letter as a conceptual anchor for visual experimentation that will appeal mainly to art film enthusiasts.', null); # 100 'E' 1981
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (121, 7, 'drorleibov', 'The High Sign is a clever Buster Keaton short with an inventive carnival setting and a perfectly timed gag structure that shows his genius clearly.', null); # 121 'High Sign', The 1921
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (33, 4, 'drorleibov', 'Swindle 2002 is a small independent thriller with a predictable twist and performances that cannot elevate the underdeveloped script material.', null); # 33 $windle 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (37, 5, 'drorleibov', 'This 1968 Soviet film is a competent Cold War action drama with solid production values typical of the era but limited international appeal today.', null); # 37 '24-25' ne vozvrashchayetsya 1968
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (15, 4, 'drorleibov', '30 dollars 1999 is a low-budget short film that lacks the production resources to fully realize its modest dramatic premise about financial struggle.', null); # 15 $30 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (18, 4, 'drorleibov', '40000 1996 is an obscure short that offers an interesting premise about wealth but does not develop it with sufficient depth or visual creativity.', null); # 18 $40,000 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (20, 4, 'drorleibov', 'The 5 Million Dollar Counterfeiting Plot is an early silent crime film of purely historical interest showing primitive storytelling techniques of the era.', null); # 20 $5,000,000 Counterfeiting Plot, The 1914
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (12, 4, 'drorleibov', 'The 20000 Carat is a very early silent comedy short of mostly archival value with primitive staging and a thin comic premise about gems.', null); # 12 $20,000 Carat, The 1913
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (167, 4, 'drorleibov', 'This 1960 Japanese crime film is a genre piece with decent action but lacks the distinctive style of the best Japanese cinema of the same period.', null); # 167 'Minagoroshi no uta' yori kenj-yo saraba! 1960
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185161, 5, 'drorleibov', 'Last Conversation 2003 is a thoughtful short drama about a final goodbye that benefits from restrained performances but feels emotionally incomplete.', null); # 185161 Last Conversation 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (183837, 4, 'drorleibov', 'Lady Warriors 2002 is a low-budget action film that fails to deliver convincing fight sequences or a plot interesting enough to compensate for its limitations.', null); # 183837 Lady Warriors 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (175879, 4, 'drorleibov', 'Khadgam is an average Telugu masala film with some energetic musical numbers but a predictable revenge narrative that adds nothing new to the genre.', null); # 175879 Khadgam 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (175881, 5, 'drorleibov', 'Khadzhi Murat 1989 is a Soviet adaptation of the Tolstoy story with a respectable literary fidelity and interesting location photography in the Caucasus.', null); # 175881 Khadzhi murat 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (175883, 4, 'drorleibov', 'Khagher 1990 is an Indian regional film with limited production values and a conventional drama that fails to distinguish itself within the genre.', null); # 175883 Khagher 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176749, 5, 'drorleibov', 'Kill the Messenger 1992 is a competent thriller about journalistic courage that tells an important story without the filmmaking flair it deserves.', null); # 176749 Kill the Messenger 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176923, 3, 'drorleibov', 'Killing Babies 2002 is a provocatively titled but deeply unpleasant exploitation film that mistakes shock value for genuine artistic statement.', null); # 176923 Killing Babies 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (146758, 4, 'drorleibov', 'Hit the Highway Honey is a country music short film that serves primarily as a promotional vehicle for its featured artist with minimal cinematic value.', null); # 146758 Hit the Highway, Honey 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (146943, 4, 'drorleibov', 'Hitting Zero 2003 is a low-budget independent film with an interesting premise about addiction but insufficient resources to fully realize its vision.', null); # 146943 Hitting Zero 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (147936, 6, 'drorleibov', 'A Holocaust szemei is a moving Hungarian documentary about Holocaust survivors whose testimonies are presented with dignity and emotional power.', null); # 147936 Holocaust szemei, A 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (155201, 4, 'drorleibov', 'Icarus Descending 1998 is a sci-fi film with ambitious ideas that are undermined by low production values and underdeveloped character relationships.', null); # 155201 Icarus Descending 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (155814, 5, 'drorleibov', 'If 2003 is a short film that poses philosophical questions about choice but does not develop its central premise with enough depth or originality.', null); # 155814 If 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (157132, 4, 'drorleibov', 'An Imperfect Solution is a making-of documentary for a cult horror film that will interest dedicated fans but nobody else in any significant way.', null); # 157132 Imperfect Solution: A Tale of the Re-Animator, An 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (157702, 6, 'drorleibov', 'In Good Conscience is a thoughtful documentary about a nun challenging church policy that raises important questions about faith and institutional authority.', null); # 157702 In Good Conscience: Sister Jeannine Gramick's Journey of Faith 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (158508, 4, 'drorleibov', 'In Their Absence 2003 is a short with a melancholy tone about empty spaces left by loss but does not develop emotionally to a satisfying conclusion.', null); # 158508 In Their Absence 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159167, 7, 'drorleibov', 'Indiana Jones 4 Kingdom of the Crystal Skull has thrilling moments and great chemistry between Ford and LaBeouf despite a divisive alien plot resolution.', null); # 159167 Indiana Jones 4 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (160250, 4, 'drorleibov', 'Inseguito 2002 is an Italian short thriller with a simple chase premise that lacks the cinematic craft needed to generate real suspense or tension.', null); # 160250 Inseguito 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (161705, 6, 'drorleibov', 'Inuyasha Tenka hadou no ken is a satisfying theatrical entry for fans of the anime series with higher production values than the TV episodes.', null); # 161705 Inuyasha - Tenka hadou no ken 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (163430, 3, 'drorleibov', 'Its a Cruel World 1918 is a primitive silent film of purely historical interest with basic staging and no narrative complexity by any modern standard.', null); # 163430 It's a Cruel World 1918
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (163571, 4, 'drorleibov', 'Its Just Coffee 2003 is a short film that attempts to find drama in everyday conversation but lacks the sharp writing to make the premise work.', null); # 163571 It's Just Coffee 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (166459, 5, 'drorleibov', 'Jeena Yahan 1979 is a Bollywood drama with decent musical numbers and emotional performances typical of its era but little to distinguish it today.', null); # 166459 Jeena Yahan 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (168725, 4, 'drorleibov', 'Johnny Ostrich and His American Songbag 2002 is an eccentric novelty short that amuses briefly but offers very little of lasting entertainment value.', null); # 168725 Johnny Ostrich and His American Songbag 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (168745, 4, 'drorleibov', 'Johnny the Amazing Firetruck 2000 is a childrens educational short with a charming premise but minimal production values and very basic storytelling.', null); # 168745 Johnny the Amazing Firetruck 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (171305, 5, 'drorleibov', 'Just Weeds 1945 is a short film with a gentle comedic premise about garden obsession that is charming in a modest way typical of 1940s shorts.', null); # 171305 Just Weeds 1945
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (173215, 6, 'drorleibov', 'Kan Zeh Lo Sham is an Israeli comedy from 1997 that captures a specific local humor and cultural moment with energy and genuine comic timing.', null); # 173215 Kan Zeh Lo Sham 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (175872, 6, 'drorleibov', 'Khachaturian 2003 is a documentary about the Armenian composer that captures his powerful music and turbulent relationship with Soviet cultural politics.', null); # 175872 Khachaturian 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (175873, 7, 'drorleibov', 'The Khachaturian Piano Concerto 1998 is a concert film recording that beautifully captures the dramatic power and rhythmic vitality of this landmark work.', null); # 175873 Khachaturian Piano Concerto 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (175875, 4, 'drorleibov', 'Khadaini abi 1951 is an Iranian film of historical interest as an early example of Persian cinema but limited by the production constraints of its era.', null); # 175875 Khadaini abi 1951
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (175880, 4, 'drorleibov', 'Khadra wa Sindibad el khebli 1952 is an Egyptian comedy of its era that showcases the popular entertainment style of postwar Arab cinema.', null); # 175880 Khadra wa Sindibad el khebli 1952
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (179177, 6, 'drorleibov', 'Kobi V Mali 1978 is a beloved Israeli childrens film with great warmth and a friendship story that resonated deeply with Israeli audiences of the era.', null); # 179177 Kobi V'Mali 1978
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (181924, 4, 'drorleibov', 'Kunwara Baap 1942 is an early Bollywood melodrama with period charm but very slow pacing and a predictable family drama narrative structure.', null); # 181924 Kunwara Baap 1942
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (143582, 4, 'drorleibov', 'Here Comes Dr Tran 2003 is an absurdist animated comedy that works in short bursts but whose surreal humor becomes repetitive over time.', null); # 143582 Here Comes Dr. Tran 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (141779, 6, 'drorleibov', 'Hector Berlioz Te Deum 1992 is a fine concert film recording of the grand choral work that faithfully captures the massive scale of Berlioz vision.', null); # 141779 Hector Berlioz: Te Deum 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (137709, 5, 'drorleibov', 'Halo 2001 is a low-budget science fiction short with interesting visual ideas that cannot be fully realized within the constraints of its limited budget.', null); # 137709 Halo 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (137958, 5, 'drorleibov', 'Hammer and Cycle 2004 is a documentary about communist imagery that raises interesting questions about political symbolism with modest production values.', null); # 137958 Hammer and Cycle 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (138142, 5, 'drorleibov', 'Hand of Fate 1999 is a supernatural thriller short that builds atmosphere effectively but does not develop its premise to a fully satisfying conclusion.', null); # 138142 Hand of Fate 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139651, 6, 'drorleibov', 'Harry Potter Chamber of Secrets alternate version 2002 is essentially a minor regional variant that differs negligibly from the primary theatrical cut.', null); # 139651 Harry Potter and the Chamber of Secrets (2002/II) 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (129887, 4, 'drorleibov', 'Goal Club 2001 is a sports documentary short about football culture in a specific regional context that will interest local audiences more than general ones.', null); # 129887 Goal Club 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (134675, 5, 'drorleibov', 'Grounds for Marriage 1951 is a light MGM romantic comedy that passes the time pleasantly without offering any particularly memorable moments or ideas.', null); # 134675 Grounds for Marriage 1951
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (134676, 5, 'drorleibov', 'Grounds for Murder 1930 is an early sound era crime film that is more interesting as a historical artifact than as a dramatically satisfying story.', null); # 134676 Grounds for Murder 1930
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (134677, 4, 'drorleibov', 'Groundspeed is a German documentary road film that moves at a deliberately slow pace that tries patience without providing sufficient visual reward.', null); # 134677 Groundspeed - Ein Film ber das Hin und Her 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (134680, 5, 'drorleibov', 'Group 2002 is a small independent drama that examines community dynamics with modest ambition and decent ensemble work from its cast of unknowns.', null); # 134680 Group 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (133608, 5, 'drorleibov', 'The Great Gabble 2003 is a short film that celebrates verbal comedy and wordplay but needs a stronger narrative frame to fully sustain its concept.', null); # 133608 Great Gabble, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (148614, 6, 'drorleibov', 'Hommage a Rossini 1985 is an affectionate documentary tribute to the Italian opera composer that will delight classical music fans considerably.', null); # 148614 Hommage  Rossini 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (152856, 4, 'drorleibov', 'Hungry 2000 is a short film about food and desire that makes its point quickly but does not sustain enough interest for even its brief runtime.', null); # 152856 Hungry 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (153301, 4, 'drorleibov', 'Huttyn 1996 is a Finnish short film with a very specific cultural context that limits its accessibility for international audiences considerably.', null); # 153301 Huttyn 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (154847, 5, 'drorleibov', 'Id Rather Be in Philadelphia 2003 is a short comedy that lands a few good jokes about city loyalty but feels too slight to leave a lasting impression.', null); # 154847 I'd Rather Be in Philadelphia 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (142881, 5, 'drorleibov', 'Henry and Marvin 2001 is a short film about an odd friendship that has charm but lacks the dramatic depth to fully engage beyond its simple premise.', null); # 142881 Henry and Marvin 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (391453, 4, 'drorleibov', 'Herndon 1983 is an obscure television film that never generated enough audience interest to justify a lasting reputation or find a home video release.', null); # 391453 Herndon 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (397250, 3, 'drorleibov', 'Me and the Chimp 1972 is one of the most notorious television failures of the 1970s with a premise so thin that the series barely lasted one season.', null); # 397250 Me and the Chimp 1972
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (400612, 5, 'drorleibov', 'Owen Marshall Counselor at Law 1971 is a competent legal drama with a likable lead performance that filled a niche in early 1970s network television.', null); # 400612 Owen Marshall: Counselor at Law 1971
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (382208, 2, 'drorleibov', 'Blansky Beauties 1977 is a short-lived Happy Days spin-off that failed to develop any interesting characters or comedic ideas of its own whatsoever.', null); # 382208 Blansky's Beauties 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (320303, 5, 'drorleibov', 'Suspension of Disbelief 2002 is a meta short about filmmaking and belief that has a clever conceptual hook but does not execute it with real flair.', null); # 320303 Suspension of Disbelief 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (320669, 5, 'drorleibov', 'Sveto mesto 1990 is a Yugoslav film set in a sacred location that explores faith and community with a dignified and patient observational style.', null); # 320669 Sveto mesto 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (321797, 5, 'drorleibov', 'Sylvia rimembri ancora 2002 is an Italian short film inspired by Leopardi poetry that captures melancholy nostalgia with reasonable visual sensitivity.', null); # 321797 Sylvia, rimembri ancora? 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (322934, 6, 'drorleibov', 'Tag der Befreiung is a German documentary about the anniversary of WWII liberation that presents its historical material clearly and with genuine emotion.', null); # 322934 Tag der Befreiung, Der 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (324576, 3, 'drorleibov', 'TankUp US 2003 is a promotional documentary about a car service that functions as barely disguised advertising with minimal independent cinematic value.', null); # 324576 TankUp.US 2003
