insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139650, 7, 'msdevlab', 'Mystery around the Chamber, the school setting, and the friendship between Harry, Ron, and Hermione keep the story enjoyable, though some moments still feel a bit childish.', null);  # 139650 Harry Potter and the Chamber of Secrets 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139652, 8, 'msdevlab', 'Triwizard Tournament gives the movie clear stakes, memorable challenges, and a darker tone that makes the fantasy adventure feel more exciting.', null);  # 139652 Harry Potter and the Goblet of Fire 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139653, 7, 'msdevlab', 'Focus on Voldemort''s past and the growing tension at Hogwarts add depth, but the slow pace makes the movie less consistently engaging.', null);  # 139653 Harry Potter and the Half-Blood Prince 2008
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139654, 8, 'msdevlab', 'Dumbledore''s Army, the Ministry conflict, and Harry''s frustration make the story feel more personal and emotionally involving.', null);  # 139654 Harry Potter and the Order of the Phoenix 2007
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139655, 8, 'msdevlab', 'The time-turner mystery, Sirius Black reveal, and more mature atmosphere make this one of the easier Harry Potter stories to stay invested in.', null);  # 139655 Harry Potter and the Prisoner of Azkaban 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139657, 7, 'msdevlab', 'First introduction to Hogwarts is charming and memorable, even if the very young tone makes it feel less mature than later entries.', null);  # 139657 Harry Potter and the Sorcerer's Stone 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311036, 6, 'msdevlab', 'The early Spider-Man idea is fun, but this version does not give Peter Parker enough story depth to feel as memorable as the later films.', null);  # 311036 Spider-Man 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311037, 8, 'msdevlab', 'Peter Parker''s transformation, the Green Goblin conflict, and the balance between action and personal responsibility make the story easy to enjoy.', null);  # 311037 Spider-Man 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311038, 9, 'msdevlab', 'Doctor Octopus, Peter''s doubts, and the train sequence give the action emotional meaning instead of feeling like action only for spectacle.', null);  # 311038 Spider-Man 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311040, 7, 'msdevlab', 'Darker Peter storyline and multiple villains create entertaining moments, but the crowded plot makes the emotional focus less clean.', null);  # 311040 Spider-Man 3 2007
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (351705, 5, 'msdevlab', 'Revenge angle has some tension, but the story does not offer enough memorable character connection to leave a strong impression.', null);  # 351705 Vengeance 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159167, 6, 'msdevlab', 'The Indiana Jones adventure style is still fun, but the later entry feels less natural and less exciting than the character usually should.', null);  # 159167 Indiana Jones 4 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159172, 8, 'msdevlab', 'Father-son dynamic, the Holy Grail quest, and the humor between Indy and his father make the adventure feel lively and character-driven.', null);  # 159172 Indiana Jones and the Last Crusade 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159175, 6, 'msdevlab', 'Temple setting and chase sequences create adventure, but the harsher tone makes it less enjoyable and less easy to connect with.', null);  # 159175 Indiana Jones and the Temple of Doom 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215875, 7, 'msdevlab', 'The secret missions, disguises, and team strategy make the spy story enjoyable, but the older pacing makes it less intense than newer action films.', null);  # 215875 Mission: Impossible 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215876, 9, 'msdevlab', 'The CIA betrayal, tense missions, and Tom Cruise''s focused performance make the action feel smart, suspenseful, and plot-driven.', null);  # 215876 Mission: Impossible 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215877, 6, 'msdevlab', 'The spy missions and IMF setup are enjoyable, but this version feels thinner than the main films and left me less invested in the characters.', null);  # 215877 Mission: Impossible 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215878, 5, 'msdevlab', 'Operation Surma has the right spy elements with stealth, gadgets, and guarded locations, but the plot feels more routine than the stronger Mission: Impossible stories.', null);  # 215878 Mission: Impossible - Operation Surma 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215879, 8, 'msdevlab', 'Motorcycle action, masks, and romantic tension create a fun spy atmosphere, even when the story is not perfectly balanced.', null);  # 215879 Mission: Impossible II 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215880, 9, 'msdevlab', 'Ethan''s personal stakes, the kidnapping threat, and the intense mission structure make the action feel urgent and emotionally connected.', null);  # 215880 Mission: Impossible III 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256631, 8, 'msdevlab', 'The search for Davy Jones'' heart, Jack Sparrow''s chaos, and the sea adventure keep the movie energetic and imaginative.', null);  # 256631 Pirates of the Caribbean 2 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256632, 9, 'msdevlab', 'Jack Sparrow, the cursed pirates, and the mix of humor, romance, and adventure make the movie feel clever and very entertaining.', null);  # 256632 Pirates of the Caribbean: The Curse of the Black Pearl 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (59578, 6, 'msdevlab', 'Candy factory visuals are creative, but the strange tone and exaggerated characters make the story less easy to connect with emotionally.', null);  # 59578 Charlie and the Chocolate Factory 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (162380, 9, 'msdevlab', 'Tony Stark''s confidence, humor, and transformation into Iron Man make the superhero story feel charismatic, modern, and highly enjoyable.', null);  # 162380 Iron Man 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (220805, 8, 'msdevlab', 'Marriage-undercover twist, spy action, and chemistry between the leads make the movie fun without relying only on explosions.', null);  # 220805 Mr. and Mrs. Smith 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313464, 4, 'msdevlab', 'The X-wing battles and space setting are exciting, but the story stays focused on missions and does not give enough character moments to connect with.', null);  # 313464 Star Wars Rogue Leader: Rogue Squadron 2 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313474, 5, 'msdevlab', 'The podracing and Jedi world have visual appeal, but Jar Jar-style humor and uneven pacing make the story feel less mature.', null);  # 313474 Star Wars: Episode I - The Phantom Menace 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313475, 4, 'msdevlab', 'The podrace and Darth Maul scenes are the most exciting parts, but Jar Jar’s humor and the slow political storyline made the movie less enjoyable for me.', null);  # 313475 Star Wars: Episode I - The Phantom Menace (1999/II) 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313476, 5, 'msdevlab', 'Anakin and Padme''s romance is central, but the dialogue and slower political scenes make the movie harder to enjoy fully.', null);  # 313476 Star Wars: Episode II - Attack of the Clones 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313477, 8, 'msdevlab', 'Anakin''s fall, the Jedi tragedy, and the darker final act give this entry stronger emotional weight and clearer stakes.', null);  # 313477 Star Wars: Episode III - Revenge of the Sith 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313478, 8, 'msdevlab', 'Luke''s training, Vader''s presence, and the darker middle-chapter tension make the story feel dramatic despite the older style.', null);  # 313478 Star Wars: Episode V - The Empire Strikes Back 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313479, 7, 'msdevlab', 'Rescue mission, Jabba sequence, and final confrontation with Vader give the movie memorable adventure and emotional closure.', null);  # 313479 Star Wars: Episode VI - Return of the Jedi 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313485, 5, 'msdevlab', 'The idea of a new Jedi student training at Luke’s academy is interesting, especially the lightsaber missions, but the story became repetitive after a while.', null);  # 313485 Star Wars: Jedi Knight - Jedi Academy 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313486, 4, 'msdevlab', 'Mara Jade and the Sith mystery are interesting ideas, but the plot feels too small and technical to stand beside the stronger Star Wars stories.', null);  # 313486 Star Wars: Jedi Knight - Mysteries of the Sith 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313487, 5, 'msdevlab', 'Kyle Katarn''s return to the Jedi path has cool lightsaber action, but the mission structure makes the story feel less personal.', null);  # 313487 Star Wars: Jedi Knight II - Jedi Outcast 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313488, 4, 'msdevlab', 'Starfighter focus gives some adventure, but vehicle-based action alone is not enough without a stronger character story.', null);  # 313488 Star Wars: Jedi Starfighter 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313489, 6, 'msdevlab', 'The Old Republic setting, Jedi choices, and darker backstory make this entry feel richer than most side stories in the Star Wars universe.', null);  # 313489 Star Wars: Knights of the Old Republic 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313493, 4, 'msdevlab', 'Racing idea is energetic, but without a strong character arc it feels too limited to be a highly enjoyable recommendation.', null);  # 313493 Star Wars: Racer Revenge 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313498, 5, 'msdevlab', 'The Rogue Squadron concept has action appeal, but the focus on missions over characters makes it feel only moderately interesting.', null);  # 313498 Star Wars: Rogue Squadron 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313503, 6, 'msdevlab', 'Clone Wars-style action and Jedi battles are enjoyable, but the animated/prequel-era format makes it feel less emotionally strong.', null);  # 313503 Star Wars: The Clone Wars 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313504, 5, 'msdevlab', 'This Empire Strikes Back entry has the Hoth and Vader atmosphere, but it does not capture the main film''s emotional impact as strongly.', null);  # 313504 Star Wars: The Empire Strikes Back 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313506, 4, 'msdevlab', 'The X-Wing battles have nostalgic space-action appeal, but the story does not give enough emotional reason to care about the missions.', null);  # 313506 Star Wars: X-Wing 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313508, 4, 'msdevlab', 'X-Wing versus TIE Fighter concept is exciting on paper, but it feels too technical and battle-focused for personal taste.', null);  # 313508 Star Wars: X-Wing vs. TIE Fighter 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (113506, 5, 'msdevlab', 'Peter Pan inspiration and softer emotional tone are pleasant, but the film feels slower and less immediately engaging.', null);  # 113506 Finding Neverland 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194492, 5, 'msdevlab', 'The fantasy world and quest idea are interesting, but this older Lord of the Rings entry feels less immersive than the later versions.', null);  # 194492 Lord of the Rings 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194495, 8, 'msdevlab', 'Final journey, the battle for Middle-earth, and the emotional ending give the story impressive scale and meaningful stakes.', null);  # 194495 Lord of the Rings: Return of the King, The (2003/II) 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194496, 5, 'msdevlab', 'The Middle-earth battles are interesting, but I missed the emotional focus on Frodo, Aragorn, and the fellowship.', null);  # 194496 Lord of the Rings: The Battle for Middle-Earth, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194497, 8, 'msdevlab', 'Frodo''s mission, the formation of the fellowship, and the clear danger of the ring make the fantasy story easy to follow and invest in.', null);  # 194497 Lord of the Rings: The Fellowship of the Ring, The 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194498, 7, 'msdevlab', 'The fellowship journey is still engaging, though this version feels less definitive than the main film and slightly less memorable.', null);  # 194498 Lord of the Rings: The Fellowship of the Ring, The 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194499, 5, 'msdevlab', 'The behind-the-scenes feeling is interesting for fans, but it works more as extra material than as a story with its own emotional arc.', null);  # 194499 Lord of the Rings: The Quest Fulfilled, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194500, 7, 'msdevlab', 'Return to Gondor, the final battles, and the emotional loyalty between characters make the story strong, even if very long.', null);  # 194500 Lord of the Rings: The Return of the King, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194501, 5, 'msdevlab', 'The Third Age setting has fantasy appeal, but without the same focus on Frodo and the fellowship it feels less personal to me.', null);  # 194501 Lord of the Rings: The Third Age 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194502, 8, 'msdevlab', 'Split fellowship, Helm''s Deep, and rising danger create strong action that still feels connected to the characters.', null);  # 194502 Lord of the Rings: The Two Towers, The 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194503, 7, 'msdevlab', 'The Two Towers material is still exciting, especially the battle atmosphere, but this version feels slightly less complete.', null);  # 194503 Lord of the Rings: The Two Towers, The (2002/II) 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194504, 5, 'msdevlab', 'War of the Ring has scale and big battles, but it focuses more on the war itself than on the characters I care about.', null);  # 194504 Lord of the Rings: The War of the Ring, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (264157, 7, 'msdevlab', 'Mia''s royal responsibility and romantic uncertainty are sweet and easy to watch, though the story can feel predictable at times.', null);  # 264157 Princess Diaries 2: Royal Engagement, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300229, 9, 'msdevlab', 'Shrek''s sarcastic humor, Fiona''s twist, and the fairytale parody make the movie clever, funny, and more original than a typical animated film.', null);  # 300229 Shrek 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300230, 9, 'msdevlab', 'This sequel keeps the humor sharp with Puss in Boots, Fairy Godmother, and the family conflict, while still giving the story real heart.', null);  # 300230 Shrek 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300233, 5, 'msdevlab', 'The 4-D format sounds fun and playful, but it feels too short to build the same charm as the main Shrek movies.', null);  # 300233 Shrek 4-D 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311604, 3, 'msdevlab', 'SpongeBob''s silly style is too childish for this taste, and the lost spatula plot does not create enough meaningful story value.', null);  # 311604 SpongeBob SquarePants: Legend of the Lost Spatula 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311606, 3, 'msdevlab', 'The Flying Dutchman villain fits SpongeBob''s silly world, but the humor stayed too childish for me to enjoy much.', null);  # 311606 SpongeBob SquarePants: Revenge of the Flying Dutchman 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311607, 3, 'msdevlab', 'SuperSponge feels aimed at younger viewers, with light humor but not enough plot or emotional connection for a stronger rating.', null);  # 311607 SpongeBob SquarePants: SuperSponge 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (340652, 7, 'msdevlab', 'Trojan War setting, Achilles conflict, and large-scale battles give the movie drama and action with a clearer story behind them.', null);  # 340652 Troy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (405119, 4, 'msdevlab', 'The detective mystery has some classic Sherlock Holmes appeal, but the old pacing made it hard for me to stay interested.', null);  # 405119 "Sherlock Holmes" 1951
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (406158, 4, 'msdevlab', 'The web-slinging idea is always fun, but this version feels unclear and not developed enough compared with stronger Spider-Man stories.', null);  # 406158 "Spider-Man" 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (406411, 6, 'msdevlab', 'Clone Wars setting offers Jedi action and visual energy, but it feels less powerful than stories with stronger emotional stakes.', null);  # 406411 Star Wars: Clone Wars 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (849, 2, 'msdevlab', 'Patch''s London adventure feels too childish, and the 101 Dalmatians style is not appealing enough to enjoy the movie.', null);  # 849 101 Dalmatians II: Patch's London Adventure 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (850, 1, 'msdevlab', 'A sing-along format feels too young and too thin in plot, making it one of the least fitting choices for my taste.', null);  # 850 101 Dalmatians Sing Along 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30972, 5, 'msdevlab', 'Gotham and Batman''s darker justice theme are appealing, but Dark Justice feels too vague to stand out from stronger Batman stories.', null);  # 30972 Batman: Dark Justice 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30974, 5, 'msdevlab', 'Batman: Dead End has a darker fan-film style that can be visually interesting, but it felt too short and limited to leave a strong impression.', null);  # 30974 Batman: Dead End 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (32180, 5, 'msdevlab', 'The Beauty and the Beast idea is charming, but this version did not feel special or emotional enough compared with stronger fairytale romances.', null);  # 32180 Beauty and the Beast 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (151616, 8, 'msdevlab', 'Bet between Andie and Ben, their chemistry, and the playful romantic tension make the comedy fun without feeling too childish.', null);  # 151616 How to Lose a Guy in 10 Days 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (170721, 4, 'msdevlab', 'Jungle Book sequel has some adventure, but the lighter child-focused tone makes it less engaging than preferred animated stories.', null);  # 170721 Jungle Book 2, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56871, 8, 'msdevlab', 'Frank Abagnale''s clever cons, the FBI chase, and the emotional father-son thread make the movie smart, fast, and easy to follow.', null);  # 56871 Catch Me If You Can 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185176, 4, 'msdevlab', 'The dance scenes could have made it emotional, but the characters and conflict did not stay memorable enough for me.', null);  # 185176 Last Dance 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (190869, 7, 'msdevlab', 'Lilo and Stitch works because the alien chaos is balanced by family, loneliness, and a sweet emotional bond.', null);  # 190869 Lilo & Stitch 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (200864, 6, 'msdevlab', 'Class-gap romance and political setting are pleasant, but the plot is predictable and not as sharp as stronger romantic comedies.', null);  # 200864 Maid in Manhattan 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (14132, 4, 'msdevlab', 'Humor is too crude and situation-based, and the story does not offer enough emotional or meaningful plot value.', null);  # 14132 American Pie 2 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (109421, 9, 'msdevlab', 'Street racing, loyalty, and undercover tension make the action exciting while still giving the characters a clear reason to matter.', null);  # 109421 Fast and the Furious, The 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (129185, 8, 'msdevlab', 'Maximus''s revenge, the arena battles, and the emotional loss behind his mission make the action feel dramatic and meaningful.', null);  # 129185 Gladiator 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (644, 8, 'msdevlab', 'Kat''s independence, Patrick''s charm, and the school-romance setup make the movie fun, witty, and easy to connect with.', null);  # 644 10 Things I Hate About You 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210739, 8, 'msdevlab', 'Alien-agent concept, Will Smith''s energy, and the fast comedy-action rhythm make the movie entertaining without feeling empty.', null);  # 210739 Men in Black 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (333856, 10, 'msdevlab', 'Jack and Rose''s romance, the class conflict, and the disaster''s emotional scale make the movie powerful despite its older release year.', null);  # 333856 Titanic 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (158999, 9, 'msdevlab', 'The alien invasion, Will Smith''s heroism, and the survival stakes create exactly the kind of big action story that feels exciting and clear.', null);  # 158999 Independence Day 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56304, 5, 'msdevlab', 'Casino world and crime drama are well-made, but the slower old-school style makes it less personally engaging.', null);  # 56304 Casino 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (66194, 7, 'msdevlab', 'Cher''s personality, fashion, and social makeover plot make the comedy light and charming without becoming completely childish.', null);  # 66194 Clueless 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (337166, 6, 'msdevlab', 'Toys'' friendship and imagination are sweet, but the very family-oriented style makes it only moderately fitting for this taste.', null);  # 337166 Toy Story 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (290070, 6, 'msdevlab', 'Historical importance is clear and powerful, but the heavy Holocaust subject makes it difficult to enjoy as a personal rewatch choice.', null);  # 290070 Schindler's List 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131780, 7, 'msdevlab', 'Henry Hill''s crime rise and downfall are compelling, though the older gangster style is not always easy to connect with.', null);  # 131780 Goodfellas 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (263360, 8, 'msdevlab', 'Vivian and Edward''s chemistry, the transformation story, and the glamorous romance make it memorable and enjoyable.', null);  # 263360 Pretty Woman 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280305, 5, 'msdevlab', 'Rocky''s later struggle has some emotional value, but the story feels less inspiring and less exciting than a strong sports drama should.', null);  # 280305 Rocky V 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (189403, 5, 'msdevlab', 'The Bond action and revenge angle have appeal, but the older style makes the movie feel less fresh and less personally engaging.', null);  # 189403 Licence to Kill 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188511, 7, 'msdevlab', 'Buddy-cop rhythm, humor, and action scenes are entertaining, even if the formula feels familiar by this fourth entry.', null);  # 188511 Lethal Weapon 4 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335835, 8, 'msdevlab', 'Fighter-pilot training, rivalry, romance, and music make the movie iconic and energetic despite its older style.', null);  # 335835 Top Gun 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311428, 5, 'msdevlab', 'Mermaid romance has a sweet idea, but the 1980s tone feels dated and less exciting for current taste.', null);  # 311428 Splash 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (96593, 6, 'msdevlab', 'E.T. and Elliott''s friendship is emotional and memorable, but the slow and very nostalgic style keeps the rating moderate.', null);  # 96593 E.T. the Extra-Terrestrial 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (271095, 8, 'msdevlab', 'The Ark quest, booby-trap adventure, and Indiana Jones charm make the older film still feel exciting and easy to watch.', null);  # 271095 Raiders of the Lost Ark 1981
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (165961, 5, 'msdevlab', 'Shark suspense is famous, but the horror-thriller feeling and older pacing make it less suitable for personal taste.', null);  # 165961 Jaws 1975
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10945, 4, 'msdevlab', 'Sci-fi creature threat feels too close to horror, making the suspense less enjoyable even with action elements.', null);  # 10945 Alien 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (14477, 5, 'msdevlab', 'Slavery trial story is meaningful, but the serious historical-drama tone feels heavy and not very rewatchable.', null);  # 14477 Amistad 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30686, 5, 'msdevlab', 'The troubled youth story has emotion, but the dark subject matter makes it harder to enjoy as entertainment.', null);  # 30686 Basketball Diaries, The 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (34077, 5, 'msdevlab', 'Benjamin''s reverse-aging life story is original, but the slow, reflective tone makes it less engaging than more direct emotional dramas.', null);  # 34077 Benjamin Button 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (34104, 5, 'msdevlab', 'Quirky romance between Benny and Sam has tenderness, though the slower 1990s style makes it only moderately appealing.', null);  # 34104 Benny & Joon 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (39551, 7, 'msdevlab', 'Mogadishu mission, soldiers under pressure, and urgent rescue structure give the war action strong intensity.', null);  # 39551 Black Hawk Down 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (41518, 5, 'msdevlab', 'George Jung''s rise and downfall have drama, but the drug-crime focus makes the movie less personally appealing.', null);  # 41518 Blow 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46167, 5, 'msdevlab', 'Johnny Depp''s directorial drama has ambition, but the slower tone and bleak atmosphere make it hard to connect with.', null);  # 46167 Brave, The 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46169, 8, 'msdevlab', 'William Wallace''s fight for freedom, betrayal, and large battle scenes make the historical drama emotional and powerful.', null);  # 46169 Braveheart 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46878, 6, 'msdevlab', 'Bridget''s romantic confusion is amusing, but the sequel feels more uneven and less fresh than the character deserves.', null);  # 46878 Bridget Jones: The Edge of Reason 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (54209, 3, 'msdevlab', 'Stalker tension and violent thriller tone are too dark, making the movie much less appealing for this taste.', null);  # 54209 Cape Fear 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (62460, 6, 'msdevlab', 'The small-town chocolate shop, gentle romance, and warm atmosphere are pleasant, though the pace is not very exciting.', null);  # 62460 Chocolat 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (86263, 7, 'msdevlab', 'Bond gadgets, ice-palace action, and fast set pieces make it entertaining, even if some parts feel exaggerated.', null);  # 86263 Die Another Day 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (112290, 5, 'msdevlab', 'Twisty identity themes are interesting, but the harsh tone and nihilistic feeling make the movie less comfortable to enjoy.', null);  # 112290 Fight Club 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120506, 3, 'msdevlab', 'Jack the Ripper setting is too grim and horror-adjacent, so the mystery is not enough to make it appealing.', null);  # 120506 From Hell 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (123435, 6, 'msdevlab', 'The psychological game between Nicholas and the hidden organization is intriguing, though the mood can feel cold.', null);  # 123435 Game, The 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (123849, 5, 'msdevlab', 'Immigrant gang conflict and revenge themes are ambitious, but the long, heavy crime-drama style makes it less enjoyable.', null);  # 123849 Gangs of New York 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (142491, 7, 'msdevlab', 'Hellboy''s sarcasm, monster-fighting world, and outsider personality make the superhero fantasy fun and not too serious.', null);  # 142491 Hellboy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (142492, 7, 'msdevlab', 'Creatures, visual style, and Hellboy-Liz relationship give the sequel personality, while the story stays easy to follow.', null);  # 142492 Hellboy 2 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176711, 5, 'msdevlab', 'Revenge mission is stylish, but the extreme violence and chapter structure make it less enjoyable personally.', null);  # 176711 Kill Bill: Vol. 1 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176712, 5, 'msdevlab', 'The second revenge chapter has emotional closure, but the violent tone still keeps it from fitting this taste strongly.', null);  # 176712 Kill Bill: Vol. 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (178994, 5, 'msdevlab', 'Small-time gangster setup has some tension, but the characters are not memorable enough to make the crime story stand out.', null);  # 178994 Knockaround Guys 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185628, 8, 'msdevlab', 'Samurai culture, inner conflict, and Tom Cruise''s character growth make the historical action feel emotional and meaningful.', null);  # 185628 Last Samurai, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (192850, 4, 'msdevlab', 'The Lizzie-style teen story feels light and easy to watch, but it does not have enough depth or drama to stay memorable.', null);  # 192850 Lizzie 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (200521, 5, 'msdevlab', 'The intersecting character stories are ambitious, but the long and heavy structure feels too scattered for easy enjoyment.', null);  # 200521 Magnolia 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210511, 6, 'msdevlab', 'Reverse-order memory puzzle is clever, though the fragmented storytelling makes it more interesting than emotionally enjoyable.', null);  # 210511 Memento 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (214755, 8, 'msdevlab', 'Future-crime concept, moral dilemma, and chase structure make the sci-fi action smart and exciting.', null);  # 214755 Minority Report 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238072, 8, 'msdevlab', 'Heist plan, casino setting, and charming team dynamic make the movie slick, fun, and easy to enjoy.', null);  # 238072 Ocean's Eleven 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238073, 7, 'msdevlab', 'The European heist setting keeps it stylish, but the plot feels more complicated and less sharp than the team itself.', null);  # 238073 Ocean's Twelve 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (244421, 5, 'msdevlab', 'Family and independence themes are sweet, but the softer drama style feels only moderately engaging.', null);  # 244421 Other Sister, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (245699, 5, 'msdevlab', 'Mistaken-romance and boat setting have comedy potential, but the older tone makes it less naturally appealing.', null);  # 245699 Overboard 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (247579, 7, 'msdevlab', 'Single-location home invasion and mother-daughter danger create focused suspense without relying on horror too much.', null);  # 247579 Panic Room 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256839, 5, 'msdevlab', 'The dark planet and creature threat create tension, but the horror-like sci-fi atmosphere limits the personal appeal.', null);  # 256839 Pitch Black 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (271344, 5, 'msdevlab', 'Helen''s sudden parenting responsibility has emotional potential, though the story feels a bit formulaic.', null);  # 271344 Raising Helen 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (292671, 4, 'msdevlab', 'Writer''s isolation and mystery setup are interesting, but the thriller tone becomes too dark and uncomfortable.', null);  # 292671 Secret Window 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (306032, 5, 'msdevlab', 'Fast editing, London crime schemes, and chaotic characters are clever, though the style can feel too messy.', null);  # 306032 Snatch. 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (310168, 4, 'msdevlab', 'The space-station documentary visuals are interesting, but I missed a real character story to connect with.', null);  # 310168 Space Station 3D 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312150, 5, 'msdevlab', 'The child-spy family idea is playful, but the very young tone makes the adventure feel only mildly enjoyable.', null);  # 312150 Spy Kids 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312151, 4, 'msdevlab', 'Island adventure has imagination, but the sequel leans even more childish and less emotionally interesting.', null);  # 312151 Spy Kids 2: Island of Lost Dreams 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312152, 3, 'msdevlab', 'The 3-D virtual-world idea is creative, but the visual gimmick and child-focused plot make it hard to enjoy.', null);  # 312152 Spy Kids 3-D: Game Over 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (319602, 5, 'msdevlab', 'Superman''s heroism is iconic, but the 1970s style feels dated and less exciting than newer superhero movies.', null);  # 319602 Superman 1978
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (319613, 5, 'msdevlab', 'Superman and Zod''s conflict has classic superhero stakes, though the older pacing makes it only moderately exciting.', null);  # 319613 Superman II 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (328272, 7, 'msdevlab', 'Viktor''s airport life, loneliness, and warm humor make the story surprisingly easy to connect with.', null);  # 328272 Terminal, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (328666, 3, 'msdevlab', 'The office-linebacker joke is funny as a short sketch, but it is too thin to feel like a real movie experience.', null);  # 328666 Terry Tate, Office Linebacker 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335336, 6, 'msdevlab', 'Media-villain plot and Bond action are entertaining, but the story feels more formulaic than truly gripping.', null);  # 335336 Tomorrow Never Dies 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (336445, 4, 'msdevlab', 'Poet romance and period-drama style feel too slow and distant for a strong personal connection.', null);  # 336445 Total Eclipse 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (342797, 5, 'msdevlab', 'The Juliet romance sounds sweet, but the relationship and story do not feel developed enough to leave a strong impression.', null);  # 342797 Two Days with Juliet 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (350424, 5, 'msdevlab', 'The dream-versus-reality mystery is intriguing, but the confusing structure makes the movie less satisfying emotionally.', null);  # 350424 Vanilla Sky 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (359297, 8, 'msdevlab', 'Alien attack, family survival, and constant danger create tense action that feels connected to clear stakes.', null);  # 359297 War of the Worlds 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (368418, 6, 'msdevlab', 'Oil-pipeline plot and Bond spectacle have some excitement, though the older franchise style feels uneven.', null);  # 368418 World Is Not Enough, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (370017, 7, 'msdevlab', 'Xander Cage''s extreme-sports attitude and undercover mission give the action a bold, fast rhythm that is easy to enjoy.', null);  # 370017 XXX 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (371305, 4, 'msdevlab', 'The movie felt unclear, and I did not get enough plot or character development to remember it after watching.', null);  # 371305 Yes and 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30955, 6, 'msdevlab', 'Gotham''s dark atmosphere and Michael Keaton''s Batman are interesting, but the older comic-book style feels somewhat dated.', null);  # 30955 Batman 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30959, 9, 'msdevlab', 'Bruce Wayne''s training, fear, and realistic Gotham crime story make the superhero origin feel serious and very engaging.', null);  # 30959 Batman Begins 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30965, 5, 'msdevlab', 'The colorful villains and campy tone are entertaining at times, but the style feels too exaggerated.', null);  # 30965 Batman Forever 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30967, 5, 'msdevlab', 'Catwoman and Penguin add memorable gothic style, but the darker weird tone makes the movie less easy to enjoy.', null);  # 30967 Batman Returns 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30976, 5, 'msdevlab', 'Animated Batman mystery has emotional ideas, but the animation style feels less appealing than a modern live-action story.', null);  # 30976 Batman: Mask of the Phantasm 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (381392, 5, 'msdevlab', 'The future Gotham setting with Terry as Batman is interesting, but the story feels more like a short episode than a full movie.', null);  # 381392 "Batman Beyond" 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10920, 5, 'msdevlab', 'Alien-action survival is intense, but the creature horror element makes it less enjoyable despite the strong heroine.', null);  # 10920 Aliens 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (40199, 5, 'msdevlab', 'The future-noir world and replicant ideas are thoughtful, but the slow, abstract style feels too distant personally.', null);  # 40199 Blade Runner 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (65811, 5, 'msdevlab', 'Alien-contact mystery is meaningful, but the 1970s pacing makes it less exciting than preferred sci-fi adventures.', null);  # 65811 Close Encounters of the Third Kind 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (21213, 5, 'msdevlab', 'Robot-child story has emotional ambition, but its strange tone and slow pacing make it hard to fully connect with.', null);  # 21213 Artificial Intelligence: AI 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (61751, 6, 'msdevlab', 'Dystopian future, escape mission, and pregnancy hope give the film a strong concept, even if the mood is very bleak.', null);  # 61751 Children of Men, The 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (267038, 6, 'msdevlab', 'The dialogue and crime structure are iconic, but the violent, cynical tone limits how enjoyable it feels personally.', null);  # 267038 Pulp Fiction 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (276217, 5, 'msdevlab', 'Warehouse standoff and criminal suspicion are tense, but the harsh style makes it less emotionally engaging.', null);  # 276217 Reservoir Dogs 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (297838, 8, 'msdevlab', 'Andy and Red''s prison friendship, hope, and final escape make the drama meaningful and very satisfying.', null);  # 297838 Shawshank Redemption, The 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (289109, 6, 'msdevlab', 'D-Day opening and rescue mission are powerful, but the heavy war violence makes it difficult as entertainment.', null);  # 289109 Saving Private Ryan 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (326155, 4, 'msdevlab', 'Travis Bickle''s isolation and violent decline are intense, but the dark psychological tone is not appealing.', null);  # 326155 Taxi Driver 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (270971, 4, 'msdevlab', 'Jake LaMotta''s self-destructive boxing story is well-acted, but the bleak character study feels too heavy.', null);  # 270971 Raging Bull 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (291698, 4, 'msdevlab', 'Serial-killer investigation is gripping, but the disturbing atmosphere and ending make it too dark for this taste.', null);  # 291698 Se7en 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280270, 6, 'msdevlab', 'Rocky''s underdog training and emotional need to prove himself make the sports drama inspiring despite its older pace.', null);  # 280270 Rocky 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280281, 6, 'msdevlab', 'Rocky''s rematch and relationship with Adrian keep the story emotional, though the pacing feels slower than preferred.', null);  # 280281 Rocky II 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280282, 6, 'msdevlab', 'Clubber Lang''s rivalry gives the movie energy, but the tone feels more simple and less emotionally rich.', null);  # 280282 Rocky III 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280284, 8, 'msdevlab', 'The Cold War opponent, training montage, and high-stakes final fight make this Rocky entry especially entertaining.', null);  # 280284 Rocky IV 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188507, 6, 'msdevlab', 'Riggs and Murtaugh''s partnership has humor and action, though the older buddy-cop style feels moderately appealing.', null);  # 188507 Lethal Weapon 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188509, 6, 'msdevlab', 'This sequel keeps the banter and danger moving, but the formula does not feel especially fresh.', null);  # 188509 Lethal Weapon 2 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188510, 6, 'msdevlab', 'Third entry has energetic buddy-cop action, though the story feels familiar rather than memorable.', null);  # 188510 Lethal Weapon 3 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (92573, 4, 'msdevlab', 'First Bond adventure has historical importance, but the 1960s pacing and style feel too dated personally.', null);  # 92573 Dr. No 1962
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120574, 4, 'msdevlab', 'The spy-train intrigue has classic Bond charm, though the old-fashioned tone makes it less engaging.', null);  # 120574 From Russia with Love 1963
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130953, 5, 'msdevlab', 'Goldfinger''s villainy, gadgets, and iconic Bond style are fun, but the older film language keeps it only moderately engaging.', null);  # 130953 Goldfinger 1964
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (332065, 4, 'msdevlab', 'Underwater action has spectacle, but the slow 1960s pacing makes it hard to stay fully interested.', null);  # 332065 Thunderball 1965
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (85871, 4, 'msdevlab', 'Las Vegas setting has some fun, but the campy older Bond tone feels too dated.', null);  # 85871 Diamonds Are Forever 1971
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (117314, 5, 'msdevlab', 'Mountain action and revenge plot are decent, though the older style keeps it from feeling very exciting.', null);  # 117314 For Your Eyes Only 1981
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (192514, 4, 'msdevlab', 'The voodoo and blaxploitation elements make the movie unusual, but the tone feels dated and not very appealing.', null);  # 192514 Live and Let Die 1973
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (203649, 4, 'msdevlab', 'Assassin-villain concept is interesting, but the 1970s Bond style feels uneven and slow.', null);  # 203649 Man with the Golden Gun, The 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218808, 5, 'msdevlab', 'The space-focused Bond spectacle is memorable, but it becomes too silly and exaggerated to feel really exciting.', null);  # 218808 Moonraker 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (240521, 5, 'msdevlab', 'Romance and emotional Bond angle are more serious, though the old style still limits personal enjoyment.', null);  # 240521 On Her Majesty's Secret Service 1969
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312170, 5, 'msdevlab', 'The submarine plot and Bond partnership have adventure appeal, but the pacing feels dated.', null);  # 312170 Spy Who Loved Me, The 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (354178, 5, 'msdevlab', 'Villain plan and action are watchable, but the mid-1980s style makes it less exciting.', null);  # 354178 View to a Kill, A 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (372233, 4, 'msdevlab', 'Volcano lair and Japanese setting are memorable, though the older pacing and stereotypes reduce the appeal.', null);  # 372233 You Only Live Twice 1967
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (164572, 5, 'msdevlab', 'Jackie Brown''s smuggling plot has style, but the slow crime tone makes it less engaging than more energetic stories.', null);  # 164572 Jackie Brown 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (118367, 5, 'msdevlab', 'Hotel-room anthology format is quirky, but the uneven segments make it hard to feel connected to one story.', null);  # 118367 Four Rooms 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (209158, 4, 'msdevlab', 'The street-crime realism has importance, but the rough 1970s style feels distant and less enjoyable.', null);  # 209158 Mean Streets 1973
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131885, 6, 'msdevlab', 'Treasure map, kids'' teamwork, and adventure tone are fun, though the older family style feels only moderately appealing.', null);  # 131885 Goonies, The 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (149287, 6, 'msdevlab', 'Grown-up Peter Pan idea is nostalgic and imaginative, but the tone feels a little too childish at times.', null);  # 149287 Hook 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (97360, 5, 'msdevlab', 'Odd Hollywood biography has interesting artistic detail, but the black-and-white style makes it less immediately engaging.', null);  # 97360 Ed Wood 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (97727, 7, 'msdevlab', 'Edward''s loneliness, the suburban setting, and the gentle romance make the strange fantasy surprisingly emotional.', null);  # 97727 Edward Scissorhands 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (304862, 4, 'msdevlab', 'The headless-horseman mystery and gothic visuals are stylish, but the horror atmosphere lowers the personal appeal.', null);  # 304862 Sleepy Hollow 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (70959, 6, 'msdevlab', 'Stop-motion world is creative and romantic, though the dead-bride theme makes it a bit too dark for high enjoyment.', null);  # 70959 Corpse Bride, The 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (220276, 6, 'msdevlab', 'Music, theatrical romance, and colorful style are memorable, but the exaggerated presentation can feel overwhelming.', null);  # 220276 Moulin Rouge! 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218219, 6, 'msdevlab', 'Forest spirits, environmental conflict, and strong heroine make the fantasy world interesting, though the intensity is heavy.', null);  # 218219 Mononoke-hime 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (25192, 5, 'msdevlab', 'Howard Hughes''s ambition and aviation obsession are interesting, but the long biographical structure feels less personally engaging.', null);  # 25192 Aviator, The 2004
