insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139657, 7, 'nevo-a', 'I enjoyed the magical world setup but it feels a bit kid-oriented compared to later films.', 'Seen');  # 139657 Harry Potter and the Sorcerer's Stone 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139650, 7, 'nevo-a', 'I liked it but it''s a transitional chapter before the series gets darker and better.', 'Seen');  # 139650 Harry Potter and the Chamber of Secrets 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139655, 9, 'nevo-a', 'I think this is where the series gets serious and the Hogwarts world really clicks for me.', 'Seen');  # 139655 Harry Potter and the Prisoner of Azkaban 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139652, 7, 'nevo-a', 'I enjoyed the Triwizard spectacle but the pacing drags and not every set piece lands.', 'Seen');  # 139652 Harry Potter and the Goblet of Fire 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139654, 9, 'nevo-a', 'I love the darker tone, Umbridge as a villain, and the Ministry battle at the end.', 'Seen');  # 139654 Harry Potter and the Order of the Phoenix 2007
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139653, 8, 'nevo-a', 'I really like the buildup to the finale and the emotional weight, even if it''s slower.', 'Seen');  # 139653 Harry Potter and the Half-Blood Prince 2008
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256632, 9, 'nevo-a', 'I love this one - Jack Sparrow, the sword fights, and the perfect blockbuster pacing.', 'Seen');  # 256632 Pirates of the Caribbean: Curse of the Black Pearl 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256631, 8, 'nevo-a', 'I enjoyed the bigger scale and the Kraken set pieces, even if the plot gets tangled.', 'Seen');  # 256631 Pirates of the Caribbean 2 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10830, 9, 'nevo-a', 'I love how it builds dread before the monster shows up and never wastes a scene.', 'Seen');  # 10830 Alien 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (1711, 7, 'nevo-a', 'I appreciate the visuals and scope but the slow pace tested my patience throughout.', 'Seen');  # 1711 2001: A Space Odyssey 1968
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (337166, 9, 'nevo-a', 'I love this - clever, emotional, and somehow holds up perfectly years later.', 'Seen');  # 337166 Toy Story 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (337168, 9, 'nevo-a', 'I love this sequel even more than the first; the Jessie backstory hits hard.', 'Seen');  # 337168 Toy Story 2 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218415, 8, 'nevo-a', 'I really enjoy the friendship between Sully and Boo and the door chase finale.', 'Seen');  # 218415 Monsters, Inc. 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (9795, 7, 'nevo-a', 'I enjoyed Robin Williams as the Genie but the rest is solid-not-special Disney for me.', 'Seen');  # 9795 Aladdin 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (143526, 8, 'nevo-a', 'I like the music and the Hades performance - an underrated 90s Disney for me.', 'Seen');  # 143526 Hercules 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (191246, 9, 'nevo-a', 'I love the scale, the music, and the Mufasa death scene still hits every single time.', 'Seen');  # 191246 The Lion King 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (222112, 7, 'nevo-a', 'I enjoyed it but it''s middle-of-the-road Disney compared to Lion King or Aladdin.', 'Seen');  # 222112 Mulan 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (272644, 8, 'nevo-a', 'I really like the Paris setting, the rat-chef premise, and Anton Ego''s memory moment.', 'Seen');  # 272644 Ratatouille 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159175, 8, 'nevo-a', 'I enjoy the action and pulp adventure feel even if the tone is darker than the first.', 'Seen');  # 159175 Indiana Jones and the Temple of Doom 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (48075, 8, 'nevo-a', 'I really enjoy Jim Carrey going full chaos with god-mode powers - peak dumb fun for me.', 'Seen');  # 48075 Bruce Almighty 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (158999, 9, 'nevo-a', 'I love this - Will Smith, alien ships, big speeches, peak 90s blockbuster energy.', 'Seen');  # 158999 Independence Day 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (333856, 10, 'nevo-a', 'I love this even though I usually skip romance - the spectacle and emotion sell it.', 'Seen');  # 333856 Titanic 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300229, 7, 'nevo-a', 'I enjoyed it but the humor hasn''t aged as well for me as the sequels suggested.', 'Seen');  # 300229 Shrek 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300230, 8, 'nevo-a', 'I think this is better than the first - Puss in Boots and Fairy Godmother are great.', 'Seen');  # 300230 Shrek 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (267038, 8, 'nevo-a', 'I really enjoy Tarantino''s dialogue and the nonlinear structure here.', 'Seen');  # 267038 Pulp Fiction 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (290070, 10, 'nevo-a', 'I think this is one of the most powerful films ever made - devastating and essential.', 'Seen');  # 290070 Schindler's List 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (340901, 8, 'nevo-a', 'I really like the high-concept premise and Jim Carrey playing it straight for once.', 'Seen');  # 340901 The Truman Show 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (289109, 8, 'nevo-a', 'I really like the opening D-Day sequence - one of the most intense things I''ve seen.', 'Seen');  # 289109 Saving Private Ryan 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (207992, 8, 'nevo-a', 'I really like the bullet time, the philosophy lite, and the original sci-fi rush.', 'Seen');  # 207992 The Matrix 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (117874, 10, 'nevo-a', 'I love this - Tom Hanks at his peak and a story that hits every emotional beat for me.', 'Seen');  # 117874 Forrest Gump 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (199255, 7, 'nevo-a', 'I enjoyed it but the DreamWorks shtick wears thin compared to Pixar for me.', 'Seen');  # 199255 Madagascar 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56871, 7, 'nevo-a', 'I enjoyed DiCaprio and Hanks together but it''s mid-tier Spielberg for me.', 'Seen');  # 56871 Catch Me If You Can 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (326155, 8, 'nevo-a', 'I really like De Niro''s performance and the slow burn into chaos here.', 'Seen');  # 326155 Taxi Driver 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56304, 8, 'nevo-a', 'I really enjoy the Vegas atmosphere and the De Niro/Pesci dynamic throughout.', 'Seen');  # 56304 Casino 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (129185, 9, 'nevo-a', 'I love this - the period setting, the arena scenes, and Russell Crowe''s revenge arc.', 'Seen');  # 129185 Gladiator 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (18960, 9, 'nevo-a', 'I love the descent-into-madness war atmosphere and the iconic helicopter scene.', 'Seen');  # 18960 Apocalypse Now 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (301391, 9, 'nevo-a', 'I love the slow tension build and the family-first framing of an alien invasion.', 'Seen');  # 301391 Signs 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131780, 8, 'nevo-a', 'I really enjoy the gangster rise-and-fall and the famous Copacabana tracking shot.', 'Seen');  # 131780 Goodfellas 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131665, 5, 'nevo-a', 'I found it slow and the central character study didn''t hook me at all.', 'Seen');  # 131665 Good Will Hunting 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (207989, 4, 'nevo-a', 'I disliked how the sequel got lost in philosophy and lost the original''s punch.', 'Seen');  # 207989 The Matrix Reloaded 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (207991, 4, 'nevo-a', 'I disliked the muddled ending - the trilogy peaked at the first film for me.', 'Seen');  # 207991 The Matrix Revolutions 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313474, 7, 'nevo-a', 'I enjoyed the pod race and the lightsaber duel even if the politics drag.', 'Seen');  # 313474 Star Wars: Episode I - The Phantom Menace 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313476, 7, 'nevo-a', 'I liked the action and Coruscant but the romance subplot fell flat for me.', 'Seen');  # 313476 Star Wars: Episode II - Attack of the Clones 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10916, 4, 'nevo-a', 'I disliked this sequel - it feels detached from what made the original great.', 'Seen');  # 10916 Alien: Resurrection 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56431, 7, 'nevo-a', 'I enjoyed Tom Hanks''s survival arc but the pacing dragged in the back half.', 'Seen');  # 56431 Cast Away 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194874, 2, 'nevo-a', 'I disliked how slow and quiet it was - nothing happened that grabbed me.', 'Seen');  # 194874 Lost in Translation 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (235790, 3, 'nevo-a', 'I disliked this - romance isn''t my genre and nothing here changed my mind.', 'Seen');  # 235790 Notting Hill 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (104338, 7, 'nevo-a', 'I liked the high-concept memory premise more than I expected to going in.', 'Seen');  # 104338 Eternal Sunshine of the Spotless Mind 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (251477, 6, 'nevo-a', 'I enjoyed the attack sequence but the romance subplot drags the whole film down.', 'Seen');  # 251477 Pearl Harbor 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (340652, 7, 'nevo-a', 'I enjoyed the period spectacle and Achilles vs Hector even if the script is uneven.', 'Seen');  # 340652 Troy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176711, 8, 'nevo-a', 'I really like the stylish action and the Crazy 88s fight sequence.', 'Seen');  # 176711 Kill Bill: Vol. 1 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176712, 8, 'nevo-a', 'I think it sticks the landing - quieter than Vol 1 but I enjoy the payoff.', 'Seen');  # 176712 Kill Bill: Vol. 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (235541, 2, 'nevo-a', 'I disliked this - peak romance is exactly the kind of film I avoid.', 'Seen');  # 235541 The Notebook 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194497, 8, 'nevo-a', 'I really like the world-building and the Mines of Moria sequence here.', 'Seen');  # 194497 LOTR: The Fellowship of the Ring 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313459, 10, 'nevo-a', 'I expect to love this - foundational sci-fi spectacle in my Independence Day wheelhouse.', 'Not seen - inferred from my love of Independence Day and big sci-fi');  # 313459 Star Wars 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313478, 10, 'nevo-a', 'I expect to love this - darker sequel with the Vader reveal, peak OT.', 'Not seen - inferred from my taste for sci-fi spectacle with stakes');  # 313478 Star Wars: Episode V - The Empire Strikes Back 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313479, 9, 'nevo-a', 'I expect to love this - Ewok battle and Vader redemption, big payoff finale.', 'Not seen - inferred from my taste for sci-fi spectacle with stakes');  # 313479 Star Wars: Episode VI - Return of the Jedi 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (328277, 9, 'nevo-a', 'I expect to love this - Cameron sci-fi action peak, T-1000 chase is legendary.', 'Not seen - inferred from my love of action sci-fi like The Matrix');  # 328277 Terminator 2: Judgment Day 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10920, 9, 'nevo-a', 'I expect to love this - Cameron action sequel that doubles down with marines vs xenomorphs.', 'Not seen - inferred from my love of Alien and Cameron''s action style');  # 10920 Aliens 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (26844, 9, 'nevo-a', 'I expect to love this - time travel adventure with perfect pacing and humor.', 'Not seen - inferred from my taste for fun 80s/90s sci-fi adventure');  # 26844 Back to the Future 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (271095, 9, 'nevo-a', 'I expect to love this - Indy at his best, the original pulp adventure template.', 'Not seen - inferred from my enjoyment of Indiana Jones: Temple of Doom');  # 271095 Raiders of the Lost Ark 1981
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159172, 9, 'nevo-a', 'I expect to love this - Connery as Indy''s dad makes it the best in the series.', 'Not seen - inferred from my enjoyment of Indiana Jones: Temple of Doom');  # 159172 Indiana Jones and the Last Crusade 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46169, 9, 'nevo-a', 'I expect to love this - period war epic with Mel Gibson, my exact wheelhouse.', 'Not seen - inferred from my love of Gladiator and period war films');  # 46169 Braveheart 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (297838, 9, 'nevo-a', 'I expect to love this - prison redemption with emotional payoff like Forrest Gump.', 'Not seen - inferred from my love of Forrest Gump and emotional storytelling');  # 297838 The Shawshank Redemption 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (113504, 9, 'nevo-a', 'I expect to love this - Pixar peak with stakes and humor like the Toy Story films.', 'Not seen - inferred from my love of Toy Story and Monsters Inc');  # 113504 Finding Nemo 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (158927, 9, 'nevo-a', 'I expect to love this - Pixar plus superheroes, exactly my MCU energy in animated form.', 'Not seen - inferred from my love of Pixar and superhero spectacle');  # 158927 The Incredibles 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (39551, 9, 'nevo-a', 'I expect to love this - intense modern war film, no romance subplot to drag it down.', 'Not seen - inferred from my love of Saving Private Ryan and modern war films');  # 39551 Black Hawk Down 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194502, 9, 'nevo-a', 'I expect to love this - the trilogy peak with Helm''s Deep, since I liked Fellowship.', 'Not seen - inferred from my enjoyment of LOTR: Fellowship of the Ring');  # 194502 LOTR: The Two Towers 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210739, 8, 'nevo-a', 'I expect to enjoy this - Will Smith plus alien comedy, fast pace, very rewatchable.', 'Not seen - inferred from my Will Smith and Independence Day affinity');  # 210739 Men in Black 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210741, 7, 'nevo-a', 'I expect to enjoy this - weaker sequel but Will Smith carries the chemistry.', 'Not seen - inferred from my Will Smith affinity');  # 210741 Men in Black II 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (222339, 8, 'nevo-a', 'I expect to enjoy this - action-adventure with humor, in the Indiana Jones vein.', 'Not seen - inferred from my taste for action-adventure like Indiana Jones');  # 222339 The Mummy 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (222321, 7, 'nevo-a', 'I expect to enjoy this - louder sequel that doubles down on action and effects.', 'Not seen - inferred from my taste for action-adventure spectacle');  # 222321 The Mummy Returns 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215876, 8, 'nevo-a', 'I expect to enjoy this - tight spy action with iconic vault break-in scene.', 'Not seen - inferred from my love of 90s/00s action thrillers');  # 215876 Mission: Impossible 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (141544, 8, 'nevo-a', 'I expect to enjoy this - crime epic with De Niro and Pacino, Scorsese-adjacent.', 'Not seen - inferred from my love of Casino, Goodfellas, and Pulp Fiction');  # 141544 Heat 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280115, 8, 'nevo-a', 'I expect to enjoy this - Bay action that actually works, Connery and Cage chemistry.', 'Not seen - inferred from my love of 90s action blockbusters');  # 280115 The Rock 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (27168, 7, 'nevo-a', 'I expect to enjoy this - Will Smith buddy cop, peak 90s action energy.', 'Not seen - inferred from my Will Smith affinity');  # 27168 Bad Boys 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (101070, 8, 'nevo-a', 'I expect to enjoy this - Will Smith surveillance thriller with paranoia and chase.', 'Not seen - inferred from my Will Smith affinity');  # 101070 Enemy of the State 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (155070, 7, 'nevo-a', 'I expect to enjoy this - Will Smith sci-fi action, dumb fun with good ideas.', 'Not seen - inferred from my Will Smith and sci-fi action affinity');  # 155070 I, Robot 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (262645, 8, 'nevo-a', 'I expect to enjoy this - Arnold action sci-fi, jungle hunt with practical effects.', 'Not seen - inferred from my love of action sci-fi like Alien');  # 262645 Predator 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (214755, 8, 'nevo-a', 'I expect to enjoy this - Spielberg and Cruise sci-fi thriller with strong concept.', 'Not seen - inferred from my love of sci-fi blockbusters like The Matrix');  # 214755 Minority Report 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (45128, 8, 'nevo-a', 'I expect to enjoy this - spy thriller with brains and grounded action.', 'Not seen - inferred from my taste for smart 00s action thrillers');  # 45128 The Bourne Identity 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (45129, 8, 'nevo-a', 'I expect to enjoy this - tighter sequel that improves on the original.', 'Not seen - inferred from my taste for smart 00s action thrillers');  # 45129 The Bourne Supremacy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (250746, 7, 'nevo-a', 'I expect to enjoy this - Revolutionary War spectacle with Mel Gibson revenge arc.', 'Not seen - inferred from my love of period war films like Gladiator');  # 250746 The Patriot 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185628, 8, 'nevo-a', 'I expect to enjoy this - period war film with Cruise and samurai code.', 'Not seen - inferred from my love of period war films like Gladiator');  # 185628 The Last Samurai 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (18979, 8, 'nevo-a', 'I expect to enjoy this - space rescue with Hanks, exactly my profile match.', 'Not seen - inferred from my love of Tom Hanks and space adventures');  # 18979 Apollo 13 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (111813, 8, 'nevo-a', 'I expect to enjoy this - courtroom drama with iconic Nicholson confrontation.', 'Not seen - inferred from my taste for tight 90s dramas');  # 111813 A Few Good Men 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (134077, 8, 'nevo-a', 'I expect to enjoy this - Hanks with emotional weight, Stephen King prison story.', 'Not seen - inferred from my love of Tom Hanks and Forrest Gump');  # 134077 The Green Mile 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (48950, 7, 'nevo-a', 'I expect to enjoy this - early Pixar, fun but slightly second-tier vs Toy Story.', 'Not seen - inferred from my love of Toy Story and Monsters Inc');  # 48950 A Bug's Life 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (32178, 7, 'nevo-a', 'I expect to enjoy this - Disney 90s peak with music and Beast transformation arc.', 'Not seen - inferred from my enjoyment of Lion King and Aladdin');  # 32178 Beauty and the Beast 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (276217, 8, 'nevo-a', 'I expect to enjoy this - early Tarantino with diamond heist gone wrong.', 'Not seen - inferred from my love of Pulp Fiction and Tarantino''s Django');  # 276217 Reservoir Dogs 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (164572, 7, 'nevo-a', 'I expect to enjoy this - slower Tarantino but still has his dialogue craft.', 'Not seen - inferred from my love of Tarantino''s Pulp Fiction and Django');  # 164572 Jackie Brown 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (264041, 7, 'nevo-a', 'I expect to enjoy this - DreamWorks epic biblical animation with strong music.', 'Not seen - inferred from my taste for animated epics like Lion King');  # 264041 The Prince of Egypt 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (109093, 6, 'nevo-a', 'I think I''d find it odd but interesting - Coen quirk may or may not click.', 'Not seen - inferred from my mixed taste for offbeat indie drama');  # 109093 Fargo 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (37178, 5, 'nevo-a', 'I think the stoner cult comedy could miss me - hit or miss depending on mood.', 'Not seen - inferred from my preference for tighter plotted films');  # 37178 The Big Lebowski 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (200521, 4, 'nevo-a', 'I think the three-hour slow ensemble would trigger my Avatar boredom pattern.', 'Not seen - inferred from my Avatar and Lost in Translation boredom pattern');  # 200521 Magnolia 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (101418, 3, 'nevo-a', 'I think the slow romance prestige format is the kind of film I usually skip.', 'Not seen - inferred from my dislike of slow romance like The Notebook');  # 101418 The English Patient 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (220276, 3, 'nevo-a', 'I think the musical plus romance combo hits two of my avoidance signals at once.', 'Not seen - inferred from my dislike of romance and lack of musical interest');  # 220276 Moulin Rouge! 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (224842, 6, 'nevo-a', 'I think the slow crime drama could land or lose me - mixed signals here.', 'Not seen - inferred from my mixed feelings on slow prestige drama');  # 224842 Mystic River 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (350424, 5, 'nevo-a', 'I think the slow confused sci-fi could lose me even with Cruise headlining.', 'Not seen - inferred from my Cast Away mid-back-half pacing complaints');  # 350424 Vanilla Sky 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (151616, 1, 'nevo-a', 'I think this rom-com formula is exactly the genre I avoid on principle.', 'Not seen - inferred from my Notebook and Notting Hill dislikes');  # 151616 How to Lose a Guy in 10 Days 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (321213, 1, 'nevo-a', 'I think pure rom-com territory will miss me completely, regardless of cast or charm.', 'Not seen - inferred from my Notebook and Notting Hill dislikes');  # 321213 Sweet Home Alabama 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (1038, 2, 'nevo-a', 'I think this rom-com body-swap fantasy hits my avoid list on every signal I have.', 'Not seen - inferred from my Notebook and Notting Hill dislikes');  # 1038 13 Going on 30 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46877, 2, 'nevo-a', 'I think the rom-com format would lose me regardless of Renee Zellweger.', 'Not seen - inferred from my Notebook and Notting Hill dislikes');  # 46877 Bridget Jones's Diary 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (372372, 2, 'nevo-a', 'I think even Hanks and Ryan can''t save a pure romance plot for me here.', 'Not seen - inferred from my dislike of romance even when I like the leads');  # 372372 You've Got Mail 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (304829, 2, 'nevo-a', 'I think this is Hanks in his weakest genre for my taste - pure rom-com territory.', 'Not seen - inferred from my dislike of romance even when I like the leads');  # 304829 Sleepless in Seattle 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (278498, 2, 'nevo-a', 'I think the horror format would lose me before any tension built up.', 'Not seen - inferred from my avoidance of horror as a genre');  # 278498 The Ring 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (289167, 2, 'nevo-a', 'I think the torture horror angle is exactly the type I avoid.', 'Not seen - inferred from my avoidance of horror as a genre');  # 289167 Saw 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (291221, 3, 'nevo-a', 'I think the meta slasher format would feel formulaic to me without genre buy-in.', 'Not seen - inferred from my avoidance of horror as a genre');  # 291221 Scream 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (275453, 3, 'nevo-a', 'I think the inspirational sports drama formula would not connect for me at all.', 'Not seen - inferred from my stated dislike of sports films');  # 275453 Remember the Titans 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335835, 9, 'nevo-a', 'I expect to love this - peak 80s action, fighter jets, exactly my spectacle taste.', 'Not seen - inferred from my love of action blockbusters like Independence Day');  # 335835 Top Gun 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (86274, 9, 'nevo-a', 'I expect to love this - peak action film, tight script and iconic villain.', 'Not seen - inferred from my action-leaning blockbuster taste');  # 86274 Die Hard 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (303564, 9, 'nevo-a', 'I expect to love this - Shyamalan suspense in the same vein as Signs which I loved.', 'Not seen - inferred from my love of Signs and Shyamalan''s slow tension');  # 303564 The Sixth Sense 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311037, 9, 'nevo-a', 'I expect to love this - superhero spectacle with origin story emotional beats.', 'Not seen - inferred from my love of MCU-style superhero spectacle');  # 311037 Spider-Man 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311038, 9, 'nevo-a', 'I expect to love this - sequel that doubles down on character and Doc Ock scenes.', 'Not seen - inferred from my love of MCU-style superhero spectacle');  # 311038 Spider-Man 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194500, 10, 'nevo-a', 'I expect to love this - trilogy capstone with massive war spectacle and emotional payoff.', 'Not seen - inferred from my enjoyment of LOTR: Fellowship of the Ring');  # 194500 LOTR: The Return of the King 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (36694, 7, 'nevo-a', 'I expect to enjoy this - early Hanks at his most charming in a tight premise.', 'Not seen - inferred from my love of Tom Hanks');  # 36694 Big 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (186650, 7, 'nevo-a', 'I expect to enjoy this - Hanks plus ensemble period piece works for me.', 'Not seen - inferred from my love of Tom Hanks and period films');  # 186650 A League of Their Own 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (254645, 7, 'nevo-a', 'I expect to enjoy this - heavy Hanks drama but the subject matter could weigh it down.', 'Not seen - inferred from my love of Tom Hanks');  # 254645 Philadelphia 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (279420, 8, 'nevo-a', 'I expect to enjoy this - Hanks playing a hitman in 30s period gangster setting.', 'Not seen - inferred from my love of Tom Hanks and Goodfellas');  # 279420 Road to Perdition 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (328272, 7, 'nevo-a', 'I expect to enjoy this - lighter Spielberg-Hanks combo, charming if minor.', 'Not seen - inferred from my love of Tom Hanks and Catch Me If You Can');  # 328272 The Terminal 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10502, 7, 'nevo-a', 'I expect to enjoy this - Will Smith doing serious biopic acting work.', 'Not seen - inferred from my Will Smith affinity');  # 10502 Ali 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (365498, 6, 'nevo-a', 'I expect this to be mid - Will Smith but widely panned, dumb steampunk action.', 'Not seen - inferred from my Will Smith affinity but reputation as a flop');  # 365498 Wild Wild West 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (16006, 7, 'nevo-a', 'I expect to enjoy this - Carell ensemble comedy with quotable lines.', 'Not seen - inferred from my Steve Carell affinity and taste for broad comedy');  # 16006 Anchorman: Legend of Ron Burgundy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (96593, 8, 'nevo-a', 'I expect to enjoy this - Spielberg sci-fi with emotional core and family stakes.', 'Not seen - inferred from my love of Spielberg''s Saving Private Ryan and Catch Me If You Can');  # 96593 E.T. the Extra-Terrestrial 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (165961, 8, 'nevo-a', 'I expect to enjoy this - Spielberg thriller foundation with slow dread build.', 'Not seen - inferred from my love of Spielberg and Alien''s slow tension');  # 165961 Jaws 1975
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (149287, 7, 'nevo-a', 'I expect to enjoy this - Spielberg fun adventure even if not his peak.', 'Not seen - inferred from my love of Spielberg adventure films');  # 149287 Hook 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (310726, 8, 'nevo-a', 'I expect to enjoy this - tight 90s action thriller with Keanu and clear stakes.', 'Not seen - inferred from my love of tight 90s action thrillers');  # 310726 Speed 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (68940, 7, 'nevo-a', 'I expect to enjoy this - dumb-fun Cage action with prison airplane premise.', 'Not seen - inferred from my love of 90s action like The Rock');  # 68940 Con Air 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (107166, 8, 'nevo-a', 'I expect to enjoy this - stylish 90s action with Cage and Travolta face-swap.', 'Not seen - inferred from my love of stylish 90s action thrillers');  # 107166 Face/Off 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188507, 7, 'nevo-a', 'I expect to enjoy this - buddy cop classic that started the formula.', 'Not seen - inferred from my taste for 80s/90s action like Die Hard');  # 188507 Lethal Weapon 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (86279, 7, 'nevo-a', 'I expect to enjoy this - solid Die Hard sequel even if less fresh.', 'Not seen - inferred from my taste for Die Hard-style action');  # 86279 Die Hard 2 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (340799, 8, 'nevo-a', 'I expect to enjoy this - Cameron plus Arnold action with marriage comedy hybrid.', 'Not seen - inferred from my love of Cameron action and 90s blockbusters');  # 340799 True Lies 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (342685, 7, 'nevo-a', 'I expect to enjoy this - disaster spectacle with tornado chase set pieces.', 'Not seen - inferred from my love of disaster spectacle like Independence Day');  # 342685 Twister 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (20371, 7, 'nevo-a', 'I expect to enjoy this - Bay disaster blockbuster, loud and emotional.', 'Not seen - inferred from my love of disaster spectacle like Independence Day');  # 20371 Armageddon 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (81776, 6, 'nevo-a', 'I expect this to be mid - quieter disaster pair to Armageddon, less action-forward.', 'Not seen - inferred from my preference for action-forward disaster films');  # 81776 Deep Impact 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (79716, 7, 'nevo-a', 'I expect to enjoy this - climate disaster spectacle with good effects work.', 'Not seen - inferred from my love of disaster spectacle like Independence Day');  # 79716 The Day After Tomorrow 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (331427, 7, 'nevo-a', 'I expect to enjoy this - Gulf War heist hybrid with Clooney and Wahlberg.', 'Not seen - inferred from my love of war films and tight action');  # 331427 Three Kings 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (257459, 8, 'nevo-a', 'I expect to enjoy this - benchmark Vietnam war film with Stone authenticity.', 'Not seen - inferred from my love of Saving Private Ryan and Apocalypse Now');  # 257459 Platoon 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (121538, 8, 'nevo-a', 'I expect to enjoy this - Kubrick war film with iconic boot camp first half.', 'Not seen - inferred from my love of Saving Private Ryan and Apocalypse Now');  # 121538 Full Metal Jacket 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (254986, 6, 'nevo-a', 'I think the slow Holocaust drama could either grab me or feel too heavy.', 'Not seen - inferred from my mixed feelings on slow prestige drama');  # 254986 The Pianist 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (330388, 4, 'nevo-a', 'I think the slow philosophical war film would trigger my Avatar boredom pattern.', 'Not seen - inferred from my Avatar slow-pace boredom pattern');  # 330388 The Thin Red Line 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (21213, 5, 'nevo-a', 'I think the slow Spielberg sci-fi could lose me even with the premise.', 'Not seen - inferred from my preference for tighter sci-fi action');  # 21213 A.I. Artificial Intelligence 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (90772, 5, 'nevo-a', 'I think the indie weird sci-fi could miss me - tone may not match my taste.', 'Not seen - inferred from my preference for accessible mainstream sci-fi');  # 90772 Donnie Darko 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210511, 6, 'nevo-a', 'I think the reverse-order thriller could land if it stays propulsive.', 'Not seen - inferred from my taste for smart action thrillers');  # 210511 Memento 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (367149, 5, 'nevo-a', 'I think the foreign wuxia could go either way - beautiful but slower paced.', 'Not seen - inferred from my mixed feelings on foreign and slower paced films');  # 367149 Crouching Tiger, Hidden Dragon 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (13789, 4, 'nevo-a', 'I think this slow prestige drama would trigger my Good Will Hunting boredom.', 'Not seen - inferred from my Good Will Hunting and slow drama dislike');  # 13789 American Beauty 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (72559, 5, 'nevo-a', 'I think the ensemble drama could be too talky and message-y for my taste.', 'Not seen - inferred from my preference for action-forward storytelling');  # 72559 Crash 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (140221, 5, 'nevo-a', 'I think this anime might miss me - I gave Spirited Away a pass but it''s an exception.', 'Not seen - inferred from my limited anime taste outside Spirited Away');  # 140221 Howl's Moving Castle 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (325098, 6, 'nevo-a', 'I think Tarzan is mid-tier Disney - fun but not Lion King-tier for me.', 'Not seen - inferred from my mid-tier Disney scores like Mulan and Aladdin');  # 325098 Tarzan 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (358604, 1, 'nevo-a', 'I think this teen romance hits multiple avoid signals at once.', 'Not seen - inferred from my Notebook and rom-com dislikes');  # 358604 A Walk to Remember 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (223711, 2, 'nevo-a', 'I think the rom-com would lose me regardless of Julia Roberts.', 'Not seen - inferred from my Notebook and rom-com dislikes');  # 223711 My Best Friend's Wedding 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (360713, 1, 'nevo-a', 'I think peak rom-com formula is exactly the kind of film I avoid on sight.', 'Not seen - inferred from my Notebook and rom-com dislikes');  # 360713 The Wedding Planner 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (362808, 2, 'nevo-a', 'I think rom-com classic status doesn''t override genre for me.', 'Not seen - inferred from my Notebook and rom-com dislikes');  # 362808 When Harry Met Sally... 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (200864, 1, 'nevo-a', 'I think the J. Lo rom-com would miss me cleanly on genre alone, regardless of execution.', 'Not seen - inferred from my Notebook and rom-com dislikes');  # 200864 Maid in Manhattan 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (137655, 2, 'nevo-a', 'I think the slasher horror format would lose me on tone before any tension builds.', 'Not seen - inferred from my avoidance of horror as a genre');  # 137655 Halloween 1978
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (232458, 2, 'nevo-a', 'I think the horror franchise origin would miss me on principle.', 'Not seen - inferred from my avoidance of horror as a genre');  # 232458 A Nightmare on Elm Street 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (40226, 3, 'nevo-a', 'I think the found-footage horror would feel flat without genre interest.', 'Not seen - inferred from my avoidance of horror as a genre');  # 40226 The Blair Witch Project 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (112008, 3, 'nevo-a', 'I think the baseball nostalgia angle would not connect for me as a non-sports fan.', 'Not seen - inferred from my stated dislike of sports films');  # 112008 Field of Dreams 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (76571, 2, 'nevo-a', 'I think this kid comedy flop has nothing in my profile to pull me in.', 'Not seen - inferred from my preference for adult comedy and action');  # 76571 Daddy Day Care 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (112290, 9, 'nevo-a', 'I expect to love this - Fincher cult crime piece with twist and bite.', 'Not seen - inferred from my love of Pulp Fiction and stylish crime films');  # 112290 Fight Club 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (348944, 9, 'nevo-a', 'I expect to love this - tight crime thriller with the famous reveal twist.', 'Not seen - inferred from my love of Pulp Fiction and tight crime thrillers');  # 348944 The Usual Suspects 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (182955, 9, 'nevo-a', 'I expect to love this - neo-noir crime with great cast and 50s LA setting.', 'Not seen - inferred from my love of Goodfellas and Casino crime style');  # 182955 L.A. Confidential 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (5573, 7, 'nevo-a', 'I expect to enjoy this - peak Jim Carrey physical comedy mode.', 'Not seen - inferred from my love of Bruce Almighty and Jim Carrey');  # 5573 Ace Ventura: Pet Detective 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (207157, 7, 'nevo-a', 'I expect to enjoy this - Carrey plus cartoon energy, dumb fun for me.', 'Not seen - inferred from my love of Bruce Almighty and Jim Carrey');  # 207157 The Mask 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (189233, 7, 'nevo-a', 'I expect to enjoy this - peak Jim Carrey high-concept comedy with simple strong hook.', 'Not seen - inferred from my love of Bruce Almighty and Jim Carrey');  # 189233 Liar Liar 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (360480, 8, 'nevo-a', 'I expect to enjoy this - intense Vietnam war film with Gibson.', 'Not seen - inferred from my love of Saving Private Ryan and modern war films');  # 360480 We Were Soldiers 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (123034, 7, 'nevo-a', 'I expect to enjoy this - sci-fi comedy that affectionately roasts Star Trek.', 'Not seen - inferred from my love of comedy plus sci-fi premises');  # 123034 Galaxy Quest 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (221259, 7, 'nevo-a', 'I expect to enjoy this - Robin Williams family comedy with heart.', 'Not seen - inferred from my taste for 90s comedy like Bruce Almighty');  # 221259 Mrs. Doubtfire 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (170522, 7, 'nevo-a', 'I expect to enjoy this - Robin Williams plus adventure board game premise.', 'Not seen - inferred from my taste for fun 90s family adventure');  # 170522 Jumanji 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (148200, 7, 'nevo-a', 'I expect to enjoy this - 90s comedy staple, hijinks and heart.', 'Not seen - inferred from my taste for fun 90s family comedy');  # 148200 Home Alone 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (163715, 7, 'nevo-a', 'I expect to enjoy this - heist remake with good cast and Mini Cooper chase.', 'Not seen - inferred from my taste for heist and action films');  # 163715 The Italian Job 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238072, 8, 'nevo-a', 'I expect to enjoy this - slick Soderbergh heist with all-star cast.', 'Not seen - inferred from my taste for stylish crime films like Pulp Fiction');  # 238072 Ocean's Eleven 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (306032, 7, 'nevo-a', 'I expect to enjoy this - Guy Ritchie crime comedy with overlapping plots.', 'Not seen - inferred from my love of Tarantino-style crime films');  # 306032 Snatch 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (336764, 7, 'nevo-a', 'I expect to enjoy this - mountain survival doc with reenactments and stakes.', 'Not seen - inferred from my love of documentaries and survival stories');  # 336764 Touching the Void 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (346949, 6, 'nevo-a', 'I think the slow Eastwood western could be interesting but might drag.', 'Not seen - inferred from my mixed feelings on slow prestige drama');  # 346949 Unforgiven 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (106988, 4, 'nevo-a', 'I think the slow French romance would miss me on language and tone.', 'Not seen - inferred from my dislike of romance and slow paced films');  # 106988 Amelie 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (63823, 6, 'nevo-a', 'I think the intense Brazilian crime film could land - it''s violent and propulsive.', 'Not seen - inferred from my love of crime films like Goodfellas');  # 63823 City of God 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238695, 6, 'nevo-a', 'I think the cult office comedy could be funny but the tone may not match.', 'Not seen - inferred from my mixed feelings on cult low-key comedies');  # 238695 Office Space 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300945, 4, 'nevo-a', 'I think the slow indie wine-country trip would trigger my Avatar boredom.', 'Not seen - inferred from my Avatar and Good Will Hunting boredom pattern');  # 300945 Sideways 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (337404, 6, 'nevo-a', 'I think the drug-war ensemble drama could land but is heavy on talk.', 'Not seen - inferred from my mixed feelings on ensemble dramas');  # 337404 Traffic 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (102514, 5, 'nevo-a', 'I think the legal drama with Roberts would be a moderate watch for me.', 'Not seen - inferred from my preference for action over courtroom drama');  # 102514 Erin Brockovich 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (1787, 5, 'nevo-a', 'I think the fractured timeline ensemble drama could feel exhausting.', 'Not seen - inferred from my mixed feelings on slow ensemble dramas');  # 1787 21 Grams 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (307274, 4, 'nevo-a', 'I think the slow philosophical sci-fi remake would lose me on pacing alone.', 'Not seen - inferred from my preference for action-forward sci-fi');  # 307274 Solaris 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (45257, 5, 'nevo-a', 'I think this documentary could engage me - I like docs but the politics may date.', 'Not seen - inferred from my interest in documentaries as a genre');  # 45257 Bowling for Columbine 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (2709, 2, 'nevo-a', 'I think rom-com with memory premise still hits my avoid list.', 'Not seen - inferred from my Notebook and rom-com dislikes');  # 2709 50 First Dates 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (113305, 2, 'nevo-a', 'I think the horror premise franchise would lose me on genre.', 'Not seen - inferred from my avoidance of horror as a genre');  # 113305 Final Destination 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (105891, 3, 'nevo-a', 'I think the horror classic status doesn''t override genre for me.', 'Not seen - inferred from my avoidance of horror as a genre');  # 105891 The Exorcist 1973
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120116, 2, 'nevo-a', 'I think the slasher franchise origin would miss me on tone and genre interest.', 'Not seen - inferred from my avoidance of horror as a genre');  # 120116 Friday the 13th 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312150, 2, 'nevo-a', 'I think the kid action film is firmly outside my target zone.', 'Not seen - inferred from my preference for adult action films');  # 312150 Spy Kids 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (254522, 1, 'nevo-a', 'I think musical plus romance is my exact double-avoid combo.', 'Not seen - inferred from my dislike of romance and musicals');  # 254522 The Phantom of the Opera 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (60163, 2, 'nevo-a', 'I think the broad kid family comedy with twelve kids would miss me on tone and pacing.', 'Not seen - inferred from my preference for adult action and comedy');  # 60163 Cheaper by the Dozen 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (290939, 2, 'nevo-a', 'I think the live-action kid franchise would miss me on tone.', 'Not seen - inferred from my preference for adult action films');  # 290939 Scooby-Doo 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (57064, 1, 'nevo-a', 'I think the notorious superhero flop would be a hard reject for me.', 'Not seen - inferred from my taste for quality superhero spectacle');  # 57064 Catwoman 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (31274, 1, 'nevo-a', 'I think this notoriously bad sci-fi flop would be a hard reject.', 'Not seen - inferred from my preference for quality sci-fi spectacle');  # 31274 Battlefield Earth 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (154309, 2, 'nevo-a', 'I think the late-90s slasher format would lose me before the killer reveal lands.', 'Not seen - inferred from my avoidance of horror as a genre');  # 154309 I Know What You Did Last Summer 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56729, 2, 'nevo-a', 'I think the live-action kid book adaptation would miss me on tone.', 'Not seen - inferred from my preference for adult comedy');  # 56729 The Cat in the Hat 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (124160, 2, 'nevo-a', 'I think the live-action plus CGI kid franchise would miss me on tone completely.', 'Not seen - inferred from my preference for adult comedy');  # 124160 Garfield 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300180, 1, 'nevo-a', 'I think this notoriously bad trashy drama would be a hard reject.', 'Not seen - inferred from my preference for substantive blockbusters');  # 300180 Showgirls 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (310728, 2, 'nevo-a', 'I think the panned action sequel would lose me even with the original''s energy.', 'Not seen - inferred from my preference for tight action like the original Speed');  # 310728 Speed 2: Cruise Control 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (45609, 3, 'nevo-a', 'I think the dark indie character drama would miss me on tone and pace.', 'Not seen - inferred from my Avatar and Good Will Hunting boredom pattern');  # 45609 Boys Don't Cry 1999
