insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (163485, 9, 'Nitzan Gavish', 'Capra turns a simple life into something genuinely profound, and the finale earns every tear it generates.', null); -- 163485 It's a Wonderful Life 1946
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (319181, 9, 'Nitzan Gavish', 'Holden narrating from a swimming pool is still the most audacious opening in Hollywood history.', null); -- 319181 Sunset Blvd. 1950
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (144861, 8, 'Nitzan Gavish', 'The moral weight of one man standing alone against a cowardly town resonates long after the credits.', null); -- 144861 High Noon 1952
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (273543, 9, 'Nitzan Gavish', 'Hitchcock proves cinema is most powerful when it places the audience inside a morally uncomfortable perspective.', null); -- 273543 Rear Window 1954
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (969, 10, 'Nitzan Gavish', 'A single room, twelve men, and no score -- yet I was gripping my chair from the first vote to the last.', null); -- 969 12 Angry Men 1957
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (250612, 9, 'Nitzan Gavish', 'Kubrick makes the senselessness of trench warfare visceral without a single battlefield explosion.', null); -- 250612 Paths of Glory 1957
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (352639, 8, 'Nitzan Gavish', 'The obsession at its center is disturbing precisely because the filmmaking is so seductively beautiful.', null); -- 352639 Vertigo 1958
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (33923, 7, 'Nitzan Gavish', 'The chariot race is still one of the most thrilling practical sequences ever filmed despite the long setup.', null); -- 33923 Ben-Hur 1959
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (235062, 9, 'Nitzan Gavish', 'Cary Grant running from a crop duster across an empty field is pure cinema logic at its most exhilarating.', null); -- 235062 North by Northwest 1959
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (307913, 9, 'Nitzan Gavish', 'Wilder somehow makes every joke land while also delivering genuine warmth in the final scene.', null); -- 307913 Some Like It Hot 1959
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (18828, 9, 'Nitzan Gavish', 'Lemmon and MacLaine create chemistry that makes the office romance feel both funny and quietly heartbreaking.', null); -- 18828 Apartment, The 1960
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (266574, 9, 'Nitzan Gavish', 'Hitchcock killed his own star in the first act and permanently changed what audiences could expect from cinema.', null); -- 266574 Psycho 1960
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (310455, 7, 'Nitzan Gavish', 'Kubrick gives the gladiator sequences real weight, though the romance slows momentum at the wrong moments.', null); -- 310455 Spartacus 1960
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (361688, 8, 'Nitzan Gavish', 'The Robbins and Wise choreography is so precise that every gang confrontation feels like controlled electricity.', null); -- 361688 West Side Story 1961
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (92573, 7, 'Nitzan Gavish', 'Connery makes Bond feel genuinely dangerous in a debut that still has more wit than most of its sequels.', null); -- 92573 Dr. No 1962
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (186439, 10, 'Nitzan Gavish', 'Lean turns a desert into an internal landscape, and O''Toole''s performance carries historical weight effortlessly.', null); -- 186439 Lawrence of Arabia 1962
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120574, 7, 'Nitzan Gavish', 'The Orient Express sequence is Bond at his most purely suspenseful and controlled, a model for spy films.', null); -- 120574 From Russia with Love 1963
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (133574, 8, 'Nitzan Gavish', 'The ensemble of McQueen, Garner, and Attenborough gives each escape attempt a distinct personality and texture.', null); -- 133574 Great Escape, The 1963
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (92616, 10, 'Nitzan Gavish', 'Sellers playing three roles while Kubrick dissects nuclear madness through pure comedy is the greatest satire made.', null); -- 92616 Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb 1964
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130953, 8, 'Nitzan Gavish', 'The Aston Martin, the laser table, and Connery at his peak make this the definitive statement of what Bond is.', null); -- 130953 Goldfinger 1964
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (223867, 7, 'Nitzan Gavish', 'The songs and sets are magnificent, though Higgins treating Eliza as a project rather than a person is hard to ignore.', null); -- 223867 My Fair Lady 1964
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (332065, 3, 'Nitzan Gavish', 'The underwater sequences eat up half the runtime and drain all the tension that the series built in previous films.', null); -- 332065 Thunderball 1965
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (49696, 10, 'Nitzan Gavish', 'Leone turns three men in a desert into a mythic standoff that cinema has never surpassed in pure visual language.', null); -- 49696 Buono, il brutto, il cattivo, Il 1966
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (1711, 9, 'Nitzan Gavish', 'Kubrick built a film that demands you bring yourself to it, and it changes every time I return to it.', null); -- 1711 2001: A Space Odyssey 1968
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (51368, 9, 'Nitzan Gavish', 'Leone mourns the end of the frontier with a harmonica theme that is probably the saddest sound in film history.', null); -- 51368 C'era una volta il West 1968
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (257295, 7, 'Nitzan Gavish', 'The final shot on the beach is one of cinema''s great gut punches, earned by a film that never overstays its premise.', null); -- 257295 Planet of the Apes 1968
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (281937, 8, 'Nitzan Gavish', 'Polanski makes ordinary apartment life feel suffocating long before anything supernatural is confirmed on screen.', null); -- 281937 Rosemary's Baby 1968
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (213112, 8, 'Nitzan Gavish', 'Voight and Hoffman form one of cinema''s most unexpectedly tender male friendships in a bleak and honest New York.', null); -- 213112 Midnight Cowboy 1969
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (250861, 8, 'Nitzan Gavish', 'George C. Scott refuses to make Patton likable, and that refusal is what makes the film so compelling.', null); -- 250861 Patton 1970
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (65764, 8, 'Nitzan Gavish', 'Kubrick films violence with such formal elegance that the discomfort becomes the entire point of watching.', null); -- 65764 Clockwork Orange, A 1971
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (87341, 7, 'Nitzan Gavish', 'Eastwood''s barely contained fury makes Harry feel like a threat even when he is theoretically the protagonist.', null); -- 87341 Dirty Harry 1971
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (51576, 8, 'Nitzan Gavish', 'Fosse uses the Kit Kat Klub numbers to mirror Nazi Germany''s rise in a way that still feels urgent and chilling.', null); -- 51576 Cabaret 1972
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (105891, 8, 'Nitzan Gavish', 'Friedkin makes the horror feel clinical and medical before it turns supernatural, which makes it far more disturbing.', null); -- 105891 Exorcist, The 1973
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (192514, 5, 'Nitzan Gavish', 'The voodoo subplot and speedboat chases are entertaining but the Bond formula feels stretched and silly throughout.', null); -- 192514 Live and Let Die 1973
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (40472, 9, 'Nitzan Gavish', 'Brooks dismantles every Western convention while somehow making a film that works as a Western too.', null); -- 40472 Blazing Saddles 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (62076, 10, 'Nitzan Gavish', 'Towne''s screenplay is a machine where every conversation adds pressure until the ending becomes inevitable.', null); -- 62076 Chinatown 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (372551, 8, 'Nitzan Gavish', 'Brooks and Wilder clearly love the monster movies they are parodying, and that affection elevates every joke.', null); -- 372551 Young Frankenstein 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30431, 7, 'Nitzan Gavish', 'The candlelit photography is astonishing but Kubrick deliberately keeps emotional distance, which divides viewers.', null); -- 30431 Barry Lyndon 1975
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (89147, 9, 'Nitzan Gavish', 'Pacino improvising and sweating through a real bank hostage situation gives the film an almost documentary pulse.', null); -- 89147 Dog Day Afternoon 1975
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218599, 9, 'Nitzan Gavish', 'The Black Knight scene alone has given me more joy per minute than almost anything else I have watched.', null); -- 218599 Monty Python and the Holy Grail 1975
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (241347, 10, 'Nitzan Gavish', 'Nicholson makes McMurphy feel both reckless and genuinely free, which makes the ending devastating rather than tragic.', null); -- 241347 One Flew Over the Cuckoo's Nest 1975
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (11525, 9, 'Nitzan Gavish', 'Redford and Hoffman make investigative journalism feel as urgent and dangerous as any action sequence.', null); -- 11525 All the President's Men 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (55625, 6, 'Nitzan Gavish', 'The prom massacre is iconic but De Palma''s split-screen showmanship can feel showy rather than scary.', null); -- 55625 Carrie 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (230151, 10, 'Nitzan Gavish', 'Chayefsky''s dialogue predicts reality television and cable news with a precision that feels like prophecy today.', null); -- 230151 Network 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280270, 8, 'Nitzan Gavish', 'The fight choreography is raw and unglamorous in a way that makes Rocky''s pain feel genuinely earned.', null); -- 280270 Rocky 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (326155, 9, 'Nitzan Gavish', 'Travis Bickle''s detachment from humanity is so carefully constructed that the film''s violence feels almost logical.', null); -- 326155 Taxi Driver 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (17760, 9, 'Nitzan Gavish', 'Allen put real neurosis and genuine romantic disappointment on screen in a way that felt entirely new in 1977.', null); -- 17760 Annie Hall 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (65811, 8, 'Nitzan Gavish', 'Spielberg captures awe so completely that Richard Dreyfuss''s obsession feels completely rational to the audience.', null); -- 65811 Close Encounters of the Third Kind 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312170, 6, 'Nitzan Gavish', 'Carly Simon''s theme and the Lotus submarine are terrific but the film leans too hard on spectacle over character.', null); -- 312170 Spy Who Loved Me, The 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (137655, 8, 'Nitzan Gavish', 'Carpenter uses silence and negative space better than almost any horror director, building dread from nothing.', null); -- 137655 Halloween 1978
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (213125, 8, 'Nitzan Gavish', 'The Turkish prison sequences are so unflinching that the film still feels dangerous rather than exploitative.', null); -- 213125 Midnight Express 1978
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (18960, 10, 'Nitzan Gavish', 'Coppola made the most ambitious American film of its decade and somehow it delivers on every single ambition.', null); -- 18960 Apocalypse Now 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (180705, 8, 'Nitzan Gavish', 'Hoffman and Streep make custody law feel like the most important dramatic subject imaginable in any given scene.', null); -- 180705 Kramer vs. Kramer 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (190166, 9, 'Nitzan Gavish', 'The Pythons take on religious devotion with enough intelligence that the satire feels respectful even at its sharpest.', null); -- 190166 Life of Brian 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218808, 2, 'Nitzan Gavish', 'The franchise abandoned credibility for space shuttles and giant lasers, turning Bond into self-parody overnight.', null); -- 218808 Moonraker 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280281, 4, 'Nitzan Gavish', 'The training scenes are fine but the film exists purely to repeat the original''s emotional beats with less conviction.', null); -- 280281 Rocky II 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120116, 2, 'Nitzan Gavish', 'The kills are unimaginative and the characters exist only to die, with almost no craft in the construction of fear.', null); -- 120116 Friday the 13th 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (243276, 8, 'Nitzan Gavish', 'Redford shows more restraint as director than anyone expected, letting silence carry the emotional weight.', null); -- 243276 Ordinary People 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (270971, 9, 'Nitzan Gavish', 'Scorsese and De Niro make self-destruction look beautiful in black and white and then make you feel terrible about that.', null); -- 270971 Raging Bull 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (299073, 9, 'Nitzan Gavish', 'Kubrick builds dread through geometric space and Nicholson''s deterioration, making the hotel the true antagonist.', null); -- 299073 Shining, The 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (59470, 7, 'Nitzan Gavish', 'Vangelis''s score and the two athletes'' contrasting motivations give the film a spiritual dimension that holds up.', null); -- 59470 Chariots of Fire 1981
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (2597, 7, 'Nitzan Gavish', 'Murphy''s star-making role works because Nolte''s irritation at him feels completely genuine throughout the film.', null); -- 2597 48 Hrs. 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (40199, 10, 'Nitzan Gavish', 'Scott asks what it means to be human through neon rain and dying replicants, and I find new answers every viewing.', null); -- 40199 Blade Runner 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (109524, 7, 'Nitzan Gavish', 'Heckerling captures teenage California so specifically that the film accidentally became a genuine time capsule.', null); -- 109524 Fast Times at Ridgemont High 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (114067, 7, 'Nitzan Gavish', 'The film is sadder than its sequels let on -- Rambo wants to be left alone, not celebrated as a killing machine.', null); -- 114067 First Blood 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (123572, 8, 'Nitzan Gavish', 'Kingsley disappears so completely into Gandhi that the biographical sweep feels personal rather than monumental.', null); -- 123572 Gandhi 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238709, 6, 'Nitzan Gavish', 'Gere and Winger sell a romance that the script only sketches, propping up a film that leans on its finale too much.', null); -- 238709 Officer and a Gentleman, An 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (259826, 7, 'Nitzan Gavish', 'The television static sequence is still effective because Spielberg grounds the haunting in a recognizable family.', null); -- 259826 Poltergeist 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (309039, 9, 'Nitzan Gavish', 'Streep makes Sophie''s tragedy feel inevitable from the opening scene, carrying the unbearable choice with full weight.', null); -- 309039 Sophie's Choice 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335799, 8, 'Nitzan Gavish', 'Hoffman''s physical transformation into Dorothy is convincing enough that the gender commentary actually lands.', null); -- 335799 Tootsie 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (245537, 6, 'Nitzan Gavish', 'Coppola assembles an extraordinary cast but keeps them at such stylistic distance that the emotion never connects fully.', null); -- 245537 Outsiders, The 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (278855, 6, 'Nitzan Gavish', 'Cruise is better here than people credit, though the film''s social anxiety is more interesting than its thriller plot.', null); -- 278855 Risky Business 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (328301, 8, 'Nitzan Gavish', 'MacLaine and Winger make the mother-daughter friction feel so real that the comedy and tragedy coexist naturally.', null); -- 328301 Terms of Endearment 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (12937, 10, 'Nitzan Gavish', 'Abraham''s Salieri watching genius he cannot match is the most devastating portrait of mediocrity ever filmed.', null); -- 12937 Amadeus 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (173933, 4, 'Nitzan Gavish', 'The training montage and wax-on wax-off are iconic but the film''s morality is far too simple and the ending too clean.', null); -- 173933 Karate Kid, The 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46215, 9, 'Nitzan Gavish', 'Gilliam built a nightmare bureaucracy so detailed and believable that it functions as satire, horror, and tragedy at once.', null); -- 46215 Brazil 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (67395, 9, 'Nitzan Gavish', 'Spielberg handles Walker''s harrowing source material with both unflinching honesty and enormous emotional care.', null); -- 67395 Color Purple, The 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (68309, 1, 'Nitzan Gavish', 'Zero plot, zero character, zero tension -- just Schwarzenegger killing an army single-handedly for ninety minutes.', null); -- 68309 Commando 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (245033, 7, 'Nitzan Gavish', 'Pollack and Streep make Kenya feel real, though the romantic center needs more complexity to sustain three hours.', null); -- 245033 Out of Africa 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (366974, 8, 'Nitzan Gavish', 'Weir uses the Amish community as a genuine moral counterpoint to Philadelphia''s violence rather than mere backdrop.', null); -- 366974 Witness 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (149388, 7, 'Nitzan Gavish', 'Hackman''s coach gives the underdog formula emotional credibility because his anger feels earned, not theatrical.', null); -- 149388 Hoosiers 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (257459, 9, 'Nitzan Gavish', 'Stone filmed the moral corruption of the Vietnam War through two competing father figures and it still devastates.', null); -- 257459 Platoon 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313059, 9, 'Nitzan Gavish', 'King''s story about the last days of childhood before the world becomes complicated is told with perfect nostalgia.', null); -- 313059 Stand by Me 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335835, 6, 'Nitzan Gavish', 'Scott made a recruitment poster with great cinematography but almost nothing behind the cockpit windshields.', null); -- 335835 Top Gun 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (100130, 8, 'Nitzan Gavish', 'Young Bale carries an entire wartime epic on his shoulders and the camp sequences have a strange dreamlike power.', null); -- 100130 Empire of the Sun 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (121538, 9, 'Nitzan Gavish', 'The Parris Island half is a complete film on its own and Ermey''s drill sergeant is genuinely terrifying.', null); -- 121538 Full Metal Jacket 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131537, 7, 'Nitzan Gavish', 'Williams improvises brilliance but the film around him struggles to match his energy in the dramatic sections.', null); -- 131537 Good Morning, Vietnam 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (279841, 7, 'Nitzan Gavish', 'Verhoeven uses corporate satire and graphic violence together so precisely that both functions reinforce each other.', null); -- 279841 RoboCop 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (49207, 7, 'Nitzan Gavish', 'Shelton writes baseball dialogue that sounds like people who actually love the game rather than screenwriters guessing.', null); -- 49207 Bull Durham 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (271192, 8, 'Nitzan Gavish', 'Hoffman''s performance is so precise that Cruise''s frustration with him becomes completely understandable and sympathetic.', null); -- 271192 Rain Man 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (93837, 7, 'Nitzan Gavish', 'Tandy and Freeman make the gradual shift in their relationship feel earned across decades of shared small moments.', null); -- 93837 Driving Miss Daisy 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (112008, 8, 'Nitzan Gavish', 'Costner''s willingness to treat magical realism as literal fact is what makes the father-son reunion work completely.', null); -- 112008 Field of Dreams 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (129570, 9, 'Nitzan Gavish', 'Zwick gives the Black soldiers'' story the full dramatic weight it deserved and Freeman''s tears are unforgettable.', null); -- 129570 Glory 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (201320, 6, 'Nitzan Gavish', 'The jokes land and the underdogs are fun to root for, but the film dissolves from memory almost immediately after.', null); -- 201320 Major League 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (289222, 8, 'Nitzan Gavish', 'Cusack holding the boombox outside the window became iconic because the whole film earns that romantic gesture.', null); -- 289222 Say Anything... 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (77728, 7, 'Nitzan Gavish', 'Costner treats Lakota culture with genuine respect and the film''s three-hour length feels necessary rather than indulgent.', null); -- 77728 Dances with Wolves 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (127073, 6, 'Nitzan Gavish', 'The pottery scene is famous for good reason but the thriller mechanics around it are far weaker than the romance.', null); -- 127073 Ghost 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215346, 9, 'Nitzan Gavish', 'Bates makes Annie Wilkes feel terrifyingly plausible because her devotion is recognizable, just scaled to violence.', null); -- 215346 Misery 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (336458, 7, 'Nitzan Gavish', 'Verhoeven layers the action with genuine ambiguity about what is real, rewarding viewers who pay close attention.', null); -- 336458 Total Recall 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (258860, 7, 'Nitzan Gavish', 'Bigelow gives extreme sports a genuine philosophical edge that makes the FBI investigation feel almost secondary.', null); -- 258860 Point Break 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (329833, 9, 'Nitzan Gavish', 'Scott and Davis turned a road movie into a genuine feminist statement that still feels radical in its final image.', null); -- 329833 Thelma & Louise 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (111813, 8, 'Nitzan Gavish', 'Nicholson''s courtroom eruption is so well prepared by the script that it feels inevitable and earned rather than showy.', null); -- 111813 Few Good Men, A 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188510, 4, 'Nitzan Gavish', 'The formula is running on fumes and even Mel Gibson looks tired, with the villain barely registering as a threat.', null); -- 188510 Lethal Weapon 3 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (346949, 10, 'Nitzan Gavish', 'Eastwood deconstructs his own screen persona as the film takes every Western myth and quietly dismantles it.', null); -- 346949 Unforgiven 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (360290, 7, 'Nitzan Gavish', 'Myers and Carvey understood that sincerity about shallow pop culture is funnier than irony, and the film delivers.', null); -- 360290 Wayne's World 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (121386, 8, 'Nitzan Gavish', 'Ford and Jones generate real friction, and the cat-and-mouse structure never loses momentum across two hours.', null); -- 121386 Fugitive, The 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (254645, 9, 'Nitzan Gavish', 'Demme and Hanks made AIDS visible at a moment when the disease was treated as a subject Hollywood refused to touch.', null); -- 254645 Philadelphia 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (283006, 7, 'Nitzan Gavish', 'Astin''s earnestness makes Rudy impossible to dismiss and the final sequence generates real crowd emotion.', null); -- 283006 Rudy 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335245, 7, 'Nitzan Gavish', 'Kilmer as Doc Holliday is so magnetic that every scene without him feels like something is missing from the room.', null); -- 335245 Tombstone 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (97360, 9, 'Nitzan Gavish', 'Burton turns bad filmmaking into a moving love story about creative obsession that transcends craft entirely.', null); -- 97360 Ed Wood 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (340799, 7, 'Nitzan Gavish', 'Cameron uses the spy thriller as an excuse for spectacular sequences while Schwarzenegger shows real comic timing.', null); -- 340799 True Lies 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (32712, 9, 'Nitzan Gavish', 'Linklater captures a night of real conversation with two strangers so honestly it feels like a recovered memory.', null); -- 32712 Before Sunrise 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56304, 8, 'Nitzan Gavish', 'Scorsese makes the Vegas mob story feel like an empire genuinely worth grieving when it finally collapses.', null); -- 56304 Casino 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (141544, 10, 'Nitzan Gavish', 'Mann gives the coffee shop scene between De Niro and Pacino more weight than most films give their entire climax.', null); -- 141544 Heat 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (263740, 8, 'Nitzan Gavish', 'Norton''s debut is so controlled and layered that the reveal recontextualizes everything he did before it completely.', null); -- 263740 Primal Fear 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (109093, 10, 'Nitzan Gavish', 'The Coens balance a wood chipper, a pregnant cop, and genuine tragedy so perfectly that the tonal control is miraculous.', null); -- 109093 Fargo 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215876, 8, 'Nitzan Gavish', 'De Palma uses every camera trick he knows and the film works as pure cinema mechanics more than as a thriller.', null); -- 215876 Mission: Impossible 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (291221, 8, 'Nitzan Gavish', 'Craven uses self-awareness about horror conventions to revive a genre that had become completely exhausted.', null); -- 291221 Scream 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (9023, 6, 'Nitzan Gavish', 'Harrison Ford punching a president villain is satisfying but the film never rises above an expensive TV movie.', null); -- 9023 Air Force One 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (21448, 8, 'Nitzan Gavish', 'Nicholson''s last truly great comedic performance is made possible by Brooks writing a character who earns sympathy.', null); -- 21448 As Good as It Gets 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (43883, 9, 'Nitzan Gavish', 'PTA captures the San Fernando Valley porn world of the 70s and 80s with documentary detail and unexpected warmth.', null); -- 43883 Boogie Nights 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (68940, 5, 'Nitzan Gavish', 'Cage and Malkovich lean so far into absurdity that the film becomes its own genre, which is its only real achievement.', null); -- 68940 Con Air 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (107166, 6, 'Nitzan Gavish', 'John Woo''s ballet of slow-motion violence is technically impressive but the plot collapses under close inspection.', null); -- 107166 Face/Off 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (124554, 9, 'Nitzan Gavish', 'Niccol asks whether the body you were born into should determine your ceiling, and the film refuses an easy answer.', null); -- 124554 Gattaca 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131665, 9, 'Nitzan Gavish', 'Damon and Affleck wrote roles for themselves that play to every strength they had and the chemistry is completely real.', null); -- 131665 Good Will Hunting 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (182955, 10, 'Nitzan Gavish', 'Hanson built a neo-noir so precise and detailed that every revelation feels inevitable in retrospect.', null); -- 182955 L.A. Confidential 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335336, 5, 'Nitzan Gavish', 'Brosnan holds the film together through charm alone but the media mogul villain is the weakest in franchise history.', null); -- 335336 Tomorrow Never Dies 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (37178, 9, 'Nitzan Gavish', 'The Dude is cinema''s most relaxed protagonist and the Coens build an entire universe of absurdity around his passivity.', null); -- 37178 Big Lebowski, The 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (78789, 8, 'Nitzan Gavish', 'Proyas builds a noir sci-fi world so complete and strange that the film should have been much more influential than it was.', null); -- 78789 Dark City 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188511, 3, 'Nitzan Gavish', 'Jet Li is wasted, the plot makes no sense, and the film scrapes the bottom of what the franchise can sustain.', null); -- 188511 Lethal Weapon 4 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (283739, 8, 'Nitzan Gavish', 'Anderson''s most personal film is also his funniest, because the ambition and incompetence of Max Fischer feel real.', null); -- 283739 Rushmore 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (297115, 7, 'Nitzan Gavish', 'Stoppard''s wit and Paltrow''s energy make the Shakespeare premise charming despite the contrivances stacking up.', null); -- 297115 Shakespeare in Love 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (14131, 6, 'Nitzan Gavish', 'The raunchy comedy is more honest about teenage embarrassment than most films claim to be, which saves it.', null); -- 14131 American Pie 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (106666, 7, 'Nitzan Gavish', 'Kubrick deliberately withholds meaning as a structural choice that divides audiences but rewards patient viewing.', null); -- 106666 Eyes Wide Shut 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (200521, 9, 'Nitzan Gavish', 'PTA orchestrates nine storylines around a single emotional center and the frogs are the least surprising thing in it.', null); -- 200521 Magnolia 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (12217, 9, 'Nitzan Gavish', 'Crowe''s thinly veiled autobiography works because Kate Hudson makes every rock-journalist cliche feel freshly observed.', null); -- 12217 Almost Famous 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (14145, 8, 'Nitzan Gavish', 'Harron uses horror to satirize the emptiness of Wall Street masculinity in a way that feels more accurate now.', null); -- 14145 American Psycho 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (37995, 8, 'Nitzan Gavish', 'Daldry and Bell make the joy of dance feel like genuine liberation in a community that treats any joy as suspicious.', null); -- 37995 Billy Elliot 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (102514, 8, 'Nitzan Gavish', 'Roberts fully inhabits Brockovich''s loudness and conviction in a star performance that goes well beyond the formula.', null); -- 102514 Erin Brockovich 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (144804, 8, 'Nitzan Gavish', 'Hornby''s music obsession translates so cleanly to Chicago that Cusack makes record-shop pedantry feel relatable.', null); -- 144804 High Fidelity 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215879, 4, 'Nitzan Gavish', 'Woo drowns every sequence in slow motion and the plot barely coherent enough to connect the action set pieces.', null); -- 215879 Mission: Impossible II 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (275453, 7, 'Nitzan Gavish', 'Washington is magnetic and the racial integration story is told with enough nuance to avoid the expected sentimentality.', null); -- 275453 Remember the Titans 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (276085, 8, 'Nitzan Gavish', 'Aronofsky shows the machinery of addiction without judgment, and the parallel deterioration of four lives is harrowing.', null); -- 276085 Requiem for a Dream 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (337404, 9, 'Nitzan Gavish', 'Soderbergh weaves three intersecting drug war stories without losing coherence or compassion for any single thread.', null); -- 337404 Traffic 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (367964, 8, 'Nitzan Gavish', 'Douglas plays writer''s block and moral failure with a casualness that makes the character more honest than likable.', null); -- 367964 Wonder Boys 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10502, 6, 'Nitzan Gavish', 'Mann''s visual intensity is striking but Ali himself remains elusive behind the style, which is a real missed opportunity.', null); -- 10502 Ali 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (39551, 8, 'Nitzan Gavish', 'Scott''s precise military chaos captures the confusion of urban warfare at a ground level that few films attempt.', null); -- 39551 Black Hawk Down 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (90772, 8, 'Nitzan Gavish', 'The time travel mechanics exist to externalize the internal dread of adolescence in a way that is quietly brilliant.', null); -- 90772 Donnie Darko 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (132122, 8, 'Nitzan Gavish', 'Altman''s ensemble creates a country house murder mystery where the class tension is the real crime being investigated.', null); -- 132122 Gosford Park 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (138463, 5, 'Nitzan Gavish', 'Hopkins is mesmerizing but the script indulges Lecter''s cruelty without the moral tension that made the original work.', null); -- 138463 Hannibal 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (158102, 8, 'Nitzan Gavish', 'Field allows grief to accumulate slowly until the final confrontation, which Wilkinson makes almost unbearable to watch.', null); -- 158102 In the Bedroom 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218398, 7, 'Nitzan Gavish', 'Berry and Thornton create an emotional credibility that the melodramatic plot structure occasionally works against.', null); -- 218398 Monster's Ball 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (220276, 7, 'Nitzan Gavish', 'Luhrmann''s visual excess is the point, and Kidman and McGregor sell the romance under layers of stylization.', null); -- 220276 Moulin Rouge! 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (222194, 9, 'Nitzan Gavish', 'Lynch builds a Hollywood dream that eats itself, and the Silencio club scene remains the most unsettling in his career.', null); -- 222194 Mulholland Dr. 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238072, 8, 'Nitzan Gavish', 'Soderbergh assembled the best ensemble comedy cast of the decade and gave them room to genuinely enjoy themselves.', null); -- 238072 Ocean's Eleven 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (244458, 8, 'Nitzan Gavish', 'Amenbar uses period detail and Nicole Kidman''s fragility to construct a ghost story with a genuinely elegant twist.', null); -- 244458 Others, The 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (337814, 8, 'Nitzan Gavish', 'Washington''s corrupt detective is terrifying because he is also genuinely good at his job, which makes him dangerous.', null); -- 337814 Training Day 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (350424, 6, 'Nitzan Gavish', 'The ambition is real but the film cannot decide between science fiction and romantic grief, and suffers for the indecision.', null); -- 350424 Vanilla Sky 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (5037, 8, 'Nitzan Gavish', 'Nicholson plays quiet regret in a way that reminds you how rarely he lets himself be genuinely subdued on screen.', null); -- 5037 About Schmidt 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (6219, 9, 'Nitzan Gavish', 'Kaufman writing a film about the impossibility of adapting a book is the cleverest structural joke in modern cinema.', null); -- 6219 Adaptation. 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (61156, 8, 'Nitzan Gavish', 'Marshall''s staging makes the fame-and-murder satire feel gleefully cynical rather than heavy-handed or moralistic.', null); -- 61156 Chicago 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (86263, 3, 'Nitzan Gavish', 'The invisible car and Madonna''s villain are the two lowest points in the entire franchise''s long history of embarrassments.', null); -- 86263 Die Another Day 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (123849, 7, 'Nitzan Gavish', 'Day-Lewis is ferocious but the film''s enormous ambition slightly outpaces its emotional delivery in the final act.', null); -- 123849 Gangs of New York 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (267165, 8, 'Nitzan Gavish', 'PTA uses a troubled romance to show how social anxiety can masquerade as love, and Sandler makes it genuinely moving.', null); -- 267165 Punch-Drunk Love 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (274069, 7, 'Nitzan Gavish', 'Norton is genuinely menacing as Dolarhyde and Hopkins recaptures some of what made Lecter frightening initially.', null); -- 274069 Red Dragon 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (279420, 8, 'Nitzan Gavish', 'Mendes shoots a Prohibition-era crime film as an elegy, and Hanks plays against type in a genuinely affecting way.', null); -- 279420 Road to Perdition 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (1787, 7, 'Nitzan Gavish', 'The shattered timeline is bold but keeps the audience at a distance from the grief it wants to convey so urgently.', null); -- 1787 21 Grams 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (48075, 6, 'Nitzan Gavish', 'Carrey''s gifts are real but the theology wraps up too comfortably for the premise to make any lasting impression.', null); -- 48075 Bruce Almighty 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (163715, 7, 'Nitzan Gavish', 'The Mini Coopers and gold chase are pure fun and the film never pretends to be anything more than slick entertainment.', null); -- 163715 Italian Job, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176711, 9, 'Nitzan Gavish', 'Tarantino treats cinema history as a language and Volume 1 speaks it more fluently than anything he made before.', null); -- 176711 Kill Bill: Vol. 1 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194874, 9, 'Nitzan Gavish', 'Coppola finds the loneliness in a luxury hotel and the two performances together feel quietly revelatory.', null); -- 194874 Lost in Translation 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (207390, 8, 'Nitzan Gavish', 'Weir recreates naval warfare with obsessive historical detail and Crowe leads the ensemble with genuine authority.', null); -- 207390 Master and Commander: The Far Side of the World 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (207989, 5, 'Nitzan Gavish', 'The Burly Brawl is technically staggering but the philosophy becomes so inflated it collapses under its own weight.', null); -- 207989 Matrix Reloaded, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (207991, 3, 'Nitzan Gavish', 'The series trades the original''s elegant ideas for machine warfare and a resolution that answers nothing it promised.', null); -- 207991 Matrix Revolutions, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (224842, 9, 'Nitzan Gavish', 'Penn, Bacon, and Robbins each carry their own devastating weight in Eastwood''s most controlled and mature film.', null); -- 224842 Mystic River 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (25192, 7, 'Nitzan Gavish', 'DiCaprio commits entirely to Hughes''s obsessions but Scorsese loses the emotional thread in the spectacle.', null); -- 25192 Aviator, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (32713, 10, 'Nitzan Gavish', 'Linklater and Delpy make nine years of separation feel present in every line, making it more moving than the first film.', null); -- 32713 Before Sunset 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (65885, 8, 'Nitzan Gavish', 'Nichols adapts Marber''s brutal play with four performances that make cruelty feel like the only honest response to desire.', null); -- 65885 Closer (2004/I) 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (72559, 5, 'Nitzan Gavish', 'Haggis means well but the racial collision structure feels contrived, stacking coincidences to deliver its message.', null); -- 72559 Crash 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (150629, 9, 'Nitzan Gavish', 'Cheadle makes diplomatic courage feel completely human, and the genocide is shown with enough restraint to be bearable.', null); -- 150629 Hotel Rwanda 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176712, 9, 'Nitzan Gavish', 'Tarantino slows down and lets the emotional damage accumulate, making Volume 2 the more affecting of the two films.', null); -- 176712 Kill Bill: Vol. 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (177792, 7, 'Nitzan Gavish', 'Liam Neeson brings earnestness to Kinsey that elevates the biographical material above the usual scientist hagiography.', null); -- 177792 Kinsey 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (228313, 6, 'Nitzan Gavish', 'Cage and Kruger are genuinely likable and the Founding Fathers treasure hunt is pleasantly dumb summer entertainment.', null); -- 228313 National Treasure 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238073, 4, 'Nitzan Gavish', 'The sequel forgets why the first film worked and substitutes self-congratulation for the effortless cool of the original.', null); -- 238073 Ocean's Twelve 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (272970, 8, 'Nitzan Gavish', 'Foxx transforms into Ray Charles so completely that the biopic format stops feeling like a limitation for once.', null); -- 272970 Ray (2004/I) 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300945, 9, 'Nitzan Gavish', 'Payne builds the most honest American road movie about middle-age failure and makes it funny without softening the truth.', null); -- 300945 Sideways 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (340652, 5, 'Nitzan Gavish', 'Petersen turns the Iliad into a conventional action film and loses everything that makes the source material immortal.', null); -- 340652 Troy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (351972, 8, 'Nitzan Gavish', 'Staunton makes Vera''s illegal abortions feel like quiet acts of compassion, and Leigh surrounds her with moral complexity.', null); -- 351972 Vera Drake 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (47422, 10, 'Nitzan Gavish', 'Lee films the Wyoming landscape as a character and the final scene is the most quietly devastating I have ever watched.', null); -- 47422 Brokeback Mountain 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (108760, 2, 'Nitzan Gavish', 'The characters have almost no dimension, the effects are cheap, and the tone is confused between comedy and drama.', null); -- 108760 Fantastic Four 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (146664, 9, 'Nitzan Gavish', 'Cronenberg puts American violence inside a family home and asks how much of it we are willing to normalize and accept.', null); -- 146664 History of Violence, A 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (177636, 6, 'Nitzan Gavish', 'The director''s cut adds real depth but even then the characters feel secondary to the spectacle of Crusades-era politics.', null); -- 177636 Kingdom of Heaven 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (358593, 8, 'Nitzan Gavish', 'Phoenix becomes Cash without imitation and Witherspoon makes June Carter feel like a full person, not a supporting role.', null); -- 358593 Walk the Line 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (360684, 6, 'Nitzan Gavish', 'Wilson and Vaughn have genuine comedic rhythm together even when the script gives them nothing particularly sharp to work with.', null); -- 360684 Wedding Crashers, The 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (2238, 5, 'Nitzan Gavish', 'Snyder''s visual language is genuinely striking but the politics underneath the slow motion are deeply uncomfortable.', null); -- 2238 300 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (82967, 10, 'Nitzan Gavish', 'Scorsese finally got his Oscar by making his best film in decades, and the final hallway scene is perfect filmmaking.', null); -- 82967 Departed, The 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (114817, 7, 'Nitzan Gavish', 'Eastwood examines how governments manufacture heroism from tragedy, which gives the Iwo Jima story genuine moral weight.', null); -- 114817 Flags of Our Fathers 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215880, 7, 'Nitzan Gavish', 'Abrams brings real emotional stakes back to the franchise and Hoffman''s villain is genuinely menacing and unpredictable.', null); -- 215880 Mission: Impossible III 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (319619, 3, 'Nitzan Gavish', 'Singer is so reverent toward the Donner films that he forgets to give this Superman anything interesting to actually do.', null); -- 319619 Superman Returns 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (369459, 3, 'Nitzan Gavish', 'Ratner kills off beloved characters carelessly and the Phoenix arc deserved a film entirely of its own to work properly.', null); -- 369459 X-Men 3 2006