-- Personal movie ratings by Noa Amar (github: noa165)
-- 203 movies rated on the project's 1-10 scale with specific justifications.

use imdb_ijs;
SET SQL_SAFE_UPDATES = 0;
DELETE FROM personal_movies_ranking WHERE suggested_by = 'noa165';
SET SQL_SAFE_UPDATES = 1;

insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (333856, 10, 'noa165', 'titanic is just one of those films you never forget. the soundtrack alone makes me emotional before anything even happens.', null); -- 333856 Titanic 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (151616, 9, 'noa165', 'how to lose a guy is such a fun watch. the whole magazine article premise is ridiculous but they make it work really well.', null); -- 151616 How to Lose a Guy in 10 Days 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (220276, 10, 'noa165', 'moulin rouge is one of the most original films ever made. the come what may scene is genuinely one of my favorite movie moments.', null); -- 220276 Moulin Rouge! 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (62460, 9, 'noa165', 'chocolat is so warm and romantic. the whole atmosphere of the film just makes you feel good and the ending is perfect.', null); -- 62460 Chocolat 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (1038, 10, 'noa165', 'i have watched 13 going on 30 so many times i lost count. razzle dazzle will always be one of the best movie scenes ever.', null); -- 1038 13 Going On 30 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (200864, 8, 'noa165', 'maid in manhattan is so cute. jennifer lopez brings so much warmth to the role and the fairytale element works perfectly.', null); -- 200864 Maid in Manhattan 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (244421, 8, 'noa165', 'the other sister is really touching. the love story feels so genuine and the performances are really grounded and honest.', null); -- 244421 Other Sister, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (308025, 8, 'noa165', 'someone to watch over me is such an underrated romantic thriller. the tension between duty and desire is handled really well.', null); -- 308025 Someone to Watch Over Me 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (263, 8, 'noa165', 'til there was you has such a sweet and romantic concept. the whole film builds to their meeting and it feels completely earned.', null); -- 263 'Til There Was You 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (69469, 9, 'noa165', 'intimate strangers is so quietly romantic. the mistaken identity premise creates this beautiful slow burning tension between them.', null); -- 69469 Confidences trop intimes 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (33492, 9, 'noa165', 'bella martha is one of my favorite foreign language films. the way the romance develops through food and cooking is so charming.', null); -- 33492 Bella Martha 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (34077, 9, 'noa165', 'benjamin button made me cry in a way i did not expect. watching a love story across an entire lifetime is devastating and beautiful.', null); -- 34077 Benjamin Button 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56282, 8, 'noa165', 'cashback is such a beautiful and romantic idea. the whole concept of freezing time to appreciate beauty around you is really moving.', null); -- 56282 Cashback 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (113506, 8, 'noa165', 'finding neverland is genuinely lovely. the story about imagination and grief is handled so delicately and the performances are perfect.', null); -- 113506 Finding Neverland 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (97727, 10, 'noa165', 'edward scissorhands is my favorite tim burton film. the love story is so sad and beautiful and the imagery stays with you forever.', null); -- 97727 Edward Scissorhands 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (59578, 7, 'noa165', 'charlie and the chocolate factory is creative and fun. johnny depp is a bit strange in it but the visual world tim burton creates is incredible.', null); -- 59578 Charlie and the Chocolate Factory 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (70959, 9, 'noa165', 'corpse bride is so visually beautiful and the love story is surprisingly emotional. the music is also really memorable.', null); -- 70959 Corpse Bride, The 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (304862, 9, 'noa165', 'sleepy hollow is my favorite gothic romance. the chemistry between depp and ricci is really interesting and the visuals are stunning.', null); -- 304862 Sleepy Hollow 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (74259, 8, 'noa165', 'cry baby is so fun and ridiculous. johnny depp playing a teen rebel is hilarious and the whole thing is so enthusiastically over the top.', null); -- 74259 Cry-Baby 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (34104, 9, 'noa165', 'benny and joon is one of the most unique love stories i have ever seen. johnny depp''s physical comedy is incredible and the whole film is just sweet.', null); -- 34104 Benny & Joon 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256632, 8, 'noa165', 'pirates of the caribbean is so entertaining. jack sparrow is one of the most iconic characters in modern cinema and the adventure is genuinely exciting.', null); -- 256632 Pirates of the Caribbean: The Curse of the Black Pearl 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256631, 6, 'noa165', 'the second pirates is decent but way too long and the plot becomes hard to follow. still fun in places though.', null); -- 256631 Pirates of the Caribbean 2 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139657, 9, 'noa165', 'the first harry potter is pure nostalgia for me. the wonder of discovering hogwarts for the first time is something no other film has captured.', null); -- 139657 Harry Potter and the Sorcerer''s Stone 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139650, 8, 'noa165', 'chamber of secrets is really fun. the mystery is compelling and the basilisk is genuinely terrifying even watching as an adult.', null); -- 139650 Harry Potter and the Chamber of Secrets 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139655, 9, 'noa165', 'prisoner of azkaban changed everything about the tone of the series. the direction is so much more artistic and the time travel twist is brilliant.', null); -- 139655 Harry Potter and the Prisoner of Azkaban 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139652, 9, 'noa165', 'goblet of fire is probably my favorite hp film. the tournament is so exciting and the ending is genuinely shocking every time.', null); -- 139652 Harry Potter and the Goblet of Fire 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139654, 7, 'noa165', 'order of the phoenix is good but the pacing is a bit slow in the middle. umbridge is absolutely perfect as a villain though.', null); -- 139654 Harry Potter and the Order of the Phoenix 2007
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139653, 8, 'noa165', 'half blood prince is so emotional and the scene at the end is devastating. the slower pace actually works really well here.', null); -- 139653 Harry Potter and the Half-Blood Prince 2008
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (190869, 10, 'noa165', 'lilo and stitch is honestly one of the best disney films ever made. the relationship between the sisters is so real and emotional.', null); -- 190869 Lilo & Stitch 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (32180, 10, 'noa165', 'beauty and the beast is perfect. the romance, the music, the animation. everything about it works and the tale as old as time scene is iconic.', null); -- 32180 Beauty and the Beast 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (337166, 9, 'noa165', 'toy story is a childhood classic that still makes me emotional as an adult. the friendship and loyalty between woody and buzz is so touching.', null); -- 337166 Toy Story 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (849, 6, 'noa165', '101 dalmatians 2 is a decent sequel for kids but it does not come close to the charm and stakes of the original.', null); -- 849 101 Dalmatians II: Patch's London Adventure 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (149287, 9, 'noa165', 'hook is so magical and emotional. the idea of peter pan forgetting neverland is heartbreaking and robin williams is absolutely perfect.', null); -- 149287 Hook 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (96593, 10, 'noa165', 'e.t. is one of the most emotional films i have ever watched. the friendship between elliot and e.t. gets me every single time without fail.', null); -- 96593 E.T. the Extra-Terrestrial 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (12744, 7, 'noa165', 'always is really beautiful and bittersweet. the love story has a fantasy quality that makes the emotional moments hit even harder.', null); -- 12744 Always 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (65811, 9, 'noa165', 'close encounters is such a stunning film. the buildup is so slow and patient and the payoff at the end is genuinely awe inspiring.', null); -- 65811 Close Encounters of the Third Kind 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (100130, 7, 'noa165', 'empire of the sun is really moving and young christian bale is remarkable. the war backdrop makes every emotional moment hit harder.', null); -- 100130 Empire of the Sun 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (21213, 8, 'noa165', 'a.i. is really thought provoking and emotional. the ending caught me completely off guard and i thought about it for days after.', null); -- 21213 Artificial Intelligence: AI 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56871, 9, 'noa165', 'catch me if you can is so compelling. leo dicaprio is completely charismatic and the cat and mouse dynamic with tom hanks never gets boring.', null); -- 56871 Catch Me If You Can 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (328272, 8, 'noa165', 'the terminal is such a feel good film. the way a romance slowly develops in such an unlikely place is really sweet and tom hanks is brilliant.', null); -- 328272 Terminal, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (14477, 8, 'noa165', 'amistad is really powerful. spielberg handles the subject with so much care and the courtroom scenes are genuinely gripping.', null); -- 14477 Amistad 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (214755, 8, 'noa165', 'minority report is so gripping. the world feels disturbingly believable and the twist is genuinely satisfying rather than just clever.', null); -- 214755 Minority Report 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (94741, 5, 'noa165', 'duel is impressive for such an early film but the concept only goes so far and it gets a bit repetitive by the end.', null); -- 94741 Duel (1971/I) 1971
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311037, 9, 'noa165', 'spider-man 2002 is such a great superhero film. the uncle ben scene is devastating and the upside down kiss is genuinely iconic.', null); -- 311037 Spider-Man 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311038, 8, 'noa165', 'spider-man 2 is really good. the train scene where everyone sees peter parker is one of my favorite superhero moments ever.', null); -- 311038 Spider-Man 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311040, 5, 'noa165', 'spider-man 3 is such a mess. too many villains, the dancing scene is embarrassing, and the symbiote storyline never really pays off.', null); -- 311040 Spider-Man 3 2007
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238072, 9, 'noa165', 'ocean''s eleven is so slick and fun. the ending twist completely surprised me and i immediately wanted to rewatch it.', null); -- 238072 Ocean's Eleven 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238073, 6, 'noa165', 'ocean''s twelve has its moments but the plot gets way too complicated and some of the jokes feel self indulgent.', null); -- 238073 Ocean's Twelve 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (220805, 9, 'noa165', 'mr and mrs smith is so entertaining. the whole married couple as secret assassins premise is hilarious and the chemistry is amazing.', null); -- 220805 Mr. and Mrs. Smith 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210739, 9, 'noa165', 'men in black is genuinely one of the most fun films ever made. will smith is at his absolute best and the alien world is so creative.', null); -- 210739 Men in Black 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (158999, 8, 'noa165', 'independence day is such a good disaster film. the speech before the final battle gives me chills every time even though i have seen it so many times.', null); -- 158999 Independence Day 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (359297, 6, 'noa165', 'war of the worlds is really tense but the ending feels a bit too convenient. the middle section with the family dynamic is the best part.', null); -- 359297 War of the Worlds 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215876, 7, 'noa165', 'mission impossible the original is such a clever thriller. the vault scene is one of the most tense things i have ever watched.', null); -- 215876 Mission: Impossible 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215879, 6, 'noa165', 'mission impossible 2 is entertaining but too style over substance. the action is impressive but the story is very thin.', null); -- 215879 Mission: Impossible II 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215880, 8, 'noa165', 'mission impossible 3 is the best of the three. the villain is actually scary and the emotional stakes with ethan''s wife feel real.', null); -- 215880 Mission: Impossible III 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312150, 9, 'noa165', 'spy kids is so fun and imaginative. watching it as a kid made me want to be a spy so badly and the gadgets are so creative.', null); -- 312150 Spy Kids 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312151, 7, 'noa165', 'spy kids 2 is still really enjoyable. the island setting is fun and the sibling dynamic between carmen and juni is still charming.', null); -- 312151 Spy Kids 2: Island of Lost Dreams 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312152, 4, 'noa165', 'spy kids 3 is basically just a video game film. the 3d gimmick takes over completely and the story gets lost somewhere along the way.', null); -- 312152 Spy Kids 3-D: Game Over 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (129185, 9, 'noa165', 'gladiator is such an epic film. russell crowe is perfect and the are you not entertained scene is one of the most iconic in cinema.', null); -- 129185 Gladiator 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194500, 10, 'noa165', 'return of the king is the most satisfying ending to a trilogy i have ever seen. the grey havens scene is one of the most emotional things ever filmed.', null); -- 194500 Lord of the Rings: The Return of the King, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194497, 9, 'noa165', 'fellowship of the ring is a perfect adventure film. the world building is extraordinary and the bond between the fellowship feels genuinely real.', null); -- 194497 Lord of the Rings: The Fellowship of the Ring, The 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194502, 9, 'noa165', 'two towers has the most spectacular battle sequence i have ever seen. the whole helm''s deep sequence is breathtaking.', null); -- 194502 Lord of the Rings: The Two Towers, The 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313478, 10, 'noa165', 'empire strikes back is perfect filmmaking. the i am your father reveal is the greatest plot twist in cinema history no question.', null); -- 313478 Star Wars: Episode V - The Empire Strikes Back 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313479, 8, 'noa165', 'return of the jedi has such a satisfying emotional ending. the redemption of darth vader is handled really beautifully.', null); -- 313479 Star Wars: Episode VI - Return of the Jedi 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313477, 9, 'noa165', 'revenge of the sith is genuinely heartbreaking. the you were the chosen one scene is such a powerful moment in the whole saga.', null); -- 313477 Star Wars: Episode III - Revenge of the Sith 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313476, 5, 'noa165', 'attack of the clones has some great action but the romance dialogue between anakin and padme is genuinely painful to listen to.', null); -- 313476 Star Wars: Episode II - Attack of the Clones 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313474, 6, 'noa165', 'phantom menace has good moments like darth maul and pod racing but jar jar binks nearly ruins the whole experience.', null); -- 313474 Star Wars: Episode I - The Phantom Menace 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30959, 10, 'noa165', 'batman begins is just a perfect film. the way nolan grounds everything in reality completely changed how superhero films are made.', null); -- 30959 Batman Begins 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30955, 8, 'noa165', 'the 1989 batman is such a classic. michael keaton and jack nicholson together are incredible and the gothic atmosphere is so distinctive.', null); -- 30955 Batman 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30967, 7, 'noa165', 'batman returns is genuinely strange but michelle pfeiffer as catwoman is the best version of that character by far.', null); -- 30967 Batman Returns 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30965, 4, 'noa165', 'batman forever has too much going on at once. val kilmer is miscast and the tone is all over the place.', null); -- 30965 Batman Forever 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30952, 1, 'noa165', 'batman and robin is one of the worst films ever made. i cannot think of a single redeeming quality. the ice puns alone are unbearable.', null); -- 30952 Batman & Robin 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30976, 7, 'noa165', 'mask of the phantasm is way better than any animated batman film has a right to be. the emotional story is genuinely moving.', null); -- 30976 Batman: Mask of the Phantasm 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130945, 8, 'noa165', 'goldeneye brought bond back so well after years away. natalya is one of the smartest and most likeable bond partners ever.', null); -- 130945 GoldenEye 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (86263, 6, 'noa165', 'die another day is a bit ridiculous in places but the action set pieces are genuinely impressive and halle berry is great.', null); -- 86263 Die Another Day 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335336, 8, 'noa165', 'tomorrow never dies is really entertaining. wai lin is such a capable and fun character and the action is exciting throughout.', null); -- 335336 Tomorrow Never Dies 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (368418, 6, 'noa165', 'world is not enough has an interesting plot twist with the villain but the pacing in the second half loses momentum.', null); -- 368418 World Is Not Enough, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188507, 9, 'noa165', 'lethal weapon is one of the best buddy films ever made. the friendship between riggs and murtaugh feels completely real and the action is exciting.', null); -- 188507 Lethal Weapon 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188509, 8, 'noa165', 'lethal weapon 2 is just as strong as the first. the south africa villain storyline is great and the emotional ending really got me.', null); -- 188509 Lethal Weapon 2 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188510, 6, 'noa165', 'lethal weapon 3 is decent but the series is starting to repeat itself. joe pesci is funny though and keeps things entertaining.', null); -- 188510 Lethal Weapon 3 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188511, 5, 'noa165', 'lethal weapon 4 feels like it went one film too far. the energy is still there sometimes but the whole thing feels unnecessary.', null); -- 188511 Lethal Weapon 4 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (109421, 8, 'noa165', 'fast and furious is so entertaining. the whole found family aspect of the franchise starts right here and it makes the action mean something.', null); -- 109421 Fast and the Furious, The 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159172, 8, 'noa165', 'last crusade is so charming. harrison ford and sean connery as father and son is comedy gold and the ending is perfectly satisfying.', null); -- 159172 Indiana Jones and the Last Crusade 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159175, 8, 'noa165', 'temple of doom is darker and weirder than raiders but the action is so exciting and the mine cart scene is just iconic.', null); -- 159175 Indiana Jones and the Temple of Doom 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159167, 5, 'noa165', 'indiana jones 4 tries hard but the crystal skull storyline is too silly. it was still nice to see the character again though.', null); -- 159167 Indiana Jones 4 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210511, 8, 'noa165', 'memento is so clever and disorienting. i rewatched it immediately to understand everything properly and it was just as good the second time.', null); -- 210511 Memento 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (116556, 7, 'noa165', 'following is such an impressive debut for nolan. for a film made on basically no money the twist is really well executed.', null); -- 116556 Following 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (160524, 6, 'noa165', 'insomnia is a well made thriller but the midnight sun setting is more interesting than the actual story which is a bit slow.', null); -- 160524 Insomnia 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (112290, 7, 'noa165', 'fight club is fascinating and the twist is one of the best ever but it is not really something i enjoy rewatching.', null); -- 112290 Fight Club 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (123435, 8, 'noa165', 'the game is so perfectly constructed. the twist is completely unexpected and rewatching it knowing the ending is a totally different experience.', null); -- 123435 Game, The 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (247579, 7, 'noa165', 'panic room is really tense and well directed. jodie foster is excellent and the single location concept works much better than i expected.', null); -- 247579 Panic Room 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (200521, 5, 'noa165', 'magnolia is technically impressive but three hours of miserable characters is a lot to get through. the frog rain is unforgettable though.', null); -- 200521 Magnolia 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (69812, 8, 'noa165', 'conspiracy theory is so fun. the paranoid energy is perfectly balanced with the romance and mel gibson is completely committed to the role.', null); -- 69812 Conspiracy Theory 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (350424, 6, 'noa165', 'vanilla sky is interesting but a bit too self indulgent in places. the mystery element keeps you watching but the ending divided me.', null); -- 350424 Vanilla Sky 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (306032, 8, 'noa165', 'snatch is so cleverly written. all the storylines coming together at the end feels genuinely earned and the whole thing is just really funny.', null); -- 306032 Snatch. 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131780, 7, 'noa165', 'goodfellas is brilliant filmmaking even if it is not my usual genre. the voiceover and the pacing are just extraordinary.', null); -- 131780 Goodfellas 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56304, 4, 'noa165', 'casino is very well made but three hours of very dark material is just too much for me. not something i would ever rewatch.', null); -- 56304 Casino 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (8183, 8, 'noa165', 'age of innocence is such a beautiful and tragic love story. watching two people deny their feelings because of society is absolutely heartbreaking.', null); -- 8183 Age of Innocence, The 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10702, 7, 'noa165', 'alice doesn''t live here anymore is really ahead of its time. a woman starting over on her own terms is such a compelling story.', null); -- 10702 Alice Doesn't Live Here Anymore 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (67395, 9, 'noa165', 'the color purple is one of the most powerful films i have seen. whoopi goldberg is extraordinary and the story is completely devastating and uplifting at the same time.', null); -- 67395 Color Purple, The 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (31715, 9, 'noa165', 'beaches is such an emotional film about female friendship. the bette midler performance and the wind beneath my wings scene are absolutely iconic.', null); -- 31715 Beaches 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218219, 9, 'noa165', 'princess mononoke is stunning and the themes are so relevant even now. the heroine is one of the greatest female protagonists in any film.', null); -- 218219 Mononoke-hime 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (174953, 7, 'noa165', 'nausicaa is such an impressive achievement for its time. the world and the lead character are both really compelling even compared to modern animation.', null); -- 174953 Kaze no tani no Naushika 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311428, 7, 'noa165', 'splash is such a fun romantic film. the mermaid concept is handled in a surprisingly believable way and the romance is genuinely sweet.', null); -- 311428 Splash 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46169, 8, 'noa165', 'braveheart is so epic and emotional. the love story in the first act is heartbreaking and it motivates everything that follows.', null); -- 46169 Braveheart 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (340652, 6, 'noa165', 'troy is entertaining but quite long and some of the performances are uneven. the production design is incredible though.', null); -- 340652 Troy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (253010, 8, 'noa165', 'a perfect world is so touching. the relationship between kevin costner and the young boy is the heart of the whole film and it really works.', null); -- 253010 Perfect World, A 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (235615, 6, 'noa165', 'nothing in common is decent but a bit uneven in tone. the father son storyline is the strongest part and tom hanks is great as always.', null); -- 235615 Nothing in Common 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (183370, 9, 'noa165', 'ladies in lavender is so quietly beautiful. the performances are extraordinary and the ending is genuinely bittersweet in the best possible way.', null); -- 183370 Ladies in Lavender 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185628, 8, 'noa165', 'last samurai is really moving. the cultural immersion story is fascinating and the way the romance develops so slowly and naturally is lovely.', null); -- 185628 Last Samurai, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335835, 8, 'noa165', 'top gun is so much fun. the chemistry between maverick and charlie is really good and the flying sequences are genuinely thrilling.', null); -- 335835 Top Gun 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (208245, 8, 'noa165', 'maverick is such an underrated film. mel gibson and jodie foster have great comedic chemistry and the poker climax is so entertaining.', null); -- 208245 Maverick 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (248090, 8, 'noa165', 'paper clips is one of the most moving documentaries i have watched. a school project becoming something so meaningful is really inspiring.', null); -- 248090 Paper Clips 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (400853, 9, 'noa165', 'parenthood is so real and funny and sad all at once. the ensemble cast is perfect and the family dynamics feel completely authentic.', null); -- 400853 Parenthood 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (390691, 8, 'noa165', 'growing pains is such a warm and funny family show. the teen relationships feel genuinely relatable even watching it now.', null); -- 390691 Growing Pains 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (391006, 6, 'noa165', 'happy days is charming and nostalgic but feels quite dated now. the fonzie stuff is fun but the show is very much of its time.', null); -- 391006 Happy Days 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (398232, 9, 'noa165', 'mork and mindy is so sweet and inventive. robin williams is electric in every scene and the romance with mindy is really charming.', null); -- 398232 Mork & Mindy 1978
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (398571, 6, 'noa165', 'murphy brown is smart and well written but feels quite dated now. candice bergen is genuinely funny though.', null); -- 398571 Murphy Brown 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (379931, 7, 'noa165', 'amazing stories has some genuinely beautiful episodes. the spielberg magic is very obvious and some of them are really emotionally effective.', null); -- 379931 Amazing Stories 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (142491, 8, 'noa165', 'hellboy is so much more charming than i expected. the romance between hellboy and liz is really sweet and gives the whole film an emotional center.', null); -- 142491 Hellboy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (142492, 7, 'noa165', 'hellboy 2 is more visually creative than the first. the del toro visual style is amazing but the story is a bit thinner.', null); -- 142492 Hellboy 2 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (372733, 8, 'noa165', 'young sherlock holmes is such a fun adventure film. the young romance adds a lovely emotional touch and the mystery is engaging throughout.', null); -- 372733 Young Sherlock Holmes 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131885, 9, 'noa165', 'the goonies is one of my favorite films ever. the adventure is exciting, the kids are all likeable, and hey you guys is the most iconic line.', null); -- 131885 Goonies, The 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46190, 5, 'noa165', 'the bravo profile on johnny depp is interesting if you like him but a bit surface level as a documentary.', null); -- 46190 Bravo Profiles: Johnny Depp 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (14132, 8, 'noa165', 'american pie 2 is so funny and the summer setting works really well. the humor is crude but the friendships between the characters are actually sweet.', null); -- 14132 American Pie 2 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (14157, 5, 'noa165', 'american reunion feels more nostalgic than actually funny. it is nice to see the characters again but it does not add much to the series.', null); -- 14157 American Reunion, An 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (80969, 6, 'noa165', 'dear god is sweet and the concept is genuinely charming but it is a bit too predictable and the comedy is quite gentle.', null); -- 80969 Dear God 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (61751, 8, 'noa165', 'children of men is such a gripping and emotional film. the long unbroken takes are technically extraordinary and the story is genuinely affecting.', null); -- 61751 Children of Men, The 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (25192, 6, 'noa165', 'the aviator is fascinating but very long. leo dicaprio is great but three hours on one person''s obsessions is a lot to sit through.', null); -- 25192 Aviator, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (123849, 7, 'noa165', 'gangs of new york is incredibly made and the production design is stunning. a bit long and violent but the performances are extraordinary.', null); -- 123849 Gangs of New York 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (113931, 5, 'noa165', 'firelight is a decent classic thriller but quite slow by modern standards. the twist is good but not enough to fully save the pacing.', null); -- 113931 Firelight 1964
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (67388, 5, 'noa165', 'color of money is decent but feels like a lesser film compared to the hustler. cruise and newman are watchable but the story is thin.', null); -- 67388 Color of Money, The 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30686, 4, 'noa165', 'basketball diaries is powerful and leo dicaprio is incredible but the subject matter is so dark and harrowing that it is genuinely difficult to watch.', null); -- 30686 Basketball Diaries, The 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (41518, 4, 'noa165', 'blow is competently made but so bleak and depressing throughout. not something i would choose to watch again.', null); -- 41518 Blow 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185704, 3, 'noa165', 'last temptation of christ is genuinely interesting intellectually but extremely uncomfortable and not something i enjoyed watching.', null); -- 185704 Last Temptation of Christ, The 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (209158, 3, 'noa165', 'mean streets is historically important but too rough and violent for my taste. i appreciate it as cinema but do not enjoy watching it.', null); -- 209158 Mean Streets 1973
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (45312, 2, 'noa165', 'boxcar bertha is very early scorsese and the exploitative elements have not aged well at all. only really of historical interest.', null); -- 45312 Boxcar Bertha 1972
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (54209, 3, 'noa165', 'cape fear is genuinely terrifying which is exactly why i do not enjoy it. de niro is unforgettable but horror thrillers are not for me.', null); -- 54209 Cape Fear 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10830, 3, 'noa165', 'alien is a masterpiece of horror filmmaking but too genuinely frightening for me. i made it through once and that was enough.', null); -- 10830 Alien 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10920, 4, 'noa165', 'aliens is more action than horror which makes it slightly more watchable for me but still way outside my comfort zone.', null); -- 10920 Aliens 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (259826, 3, 'noa165', 'poltergeist is effective horror but far too scary for me. the images from this film stuck in my head for weeks and not in a good way.', null); -- 259826 Poltergeist 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (240327, 2, 'noa165', 'the omen is a classic but absolutely not my type of film. the subject matter is deeply disturbing and the whole thing gave me anxiety.', null); -- 240327 Omen, The 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120506, 3, 'noa165', 'from hell has an interesting story but is far too gory and dark for me. the ripper mythology is compelling but the violence is excessive.', null); -- 120506 From Hell 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (44238, 2, 'noa165', 'bordello of blood is just not good. too crude and not funny enough to justify the grossness.', null); -- 44238 Bordello of Blood 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176711, 3, 'noa165', 'kill bill is technically impressive but the constant graphic violence is genuinely too much for me. could not finish the first viewing.', null); -- 176711 Kill Bill: Vol. 1 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176712, 5, 'noa165', 'kill bill vol 2 is much better for me personally. the slower pace and the emotional storyline are far more interesting than the action of the first.', null); -- 176712 Kill Bill: Vol. 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (85871, 3, 'noa165', 'diamonds are forever is very dated and the humor has aged really poorly. the treatment of the female characters is genuinely uncomfortable now.', null); -- 85871 Diamonds Are Forever 1971
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (92573, 4, 'noa165', 'dr no is interesting as the first bond film but it is very slow by modern standards. worth watching once for historical context.', null); -- 92573 Dr. No 1962
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120574, 5, 'noa165', 'from russia with love is genuinely tense for an older bond film. the spy thriller elements work better than most early entries in the series.', null); -- 120574 From Russia with Love 1963
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (192514, 4, 'noa165', 'live and let die has some fun moments but the racial elements have aged really poorly and are quite uncomfortable to watch now.', null); -- 192514 Live and Let Die 1973
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218808, 3, 'noa165', 'moonraker is the low point of the bond series for me. taking bond into space is such a desperate creative decision and the film suffers for it.', null); -- 218808 Moonraker 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312170, 7, 'noa165', 'the spy who loved me is one of the better older bonds. anya is a strong and interesting character and the underwater base villain is iconic.', null); -- 312170 Spy Who Loved Me, The 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (240521, 3, 'noa165', 'on her majesty''s secret service suffers badly from the recasting. george lazenby is simply not convincing as bond and the film is too long.', null); -- 240521 On Her Majesty's Secret Service 1969
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (372233, 3, 'noa165', 'you only live twice is very dated. the japan setting is interesting but the storyline is too formulaic and the film lacks energy.', null); -- 372233 You Only Live Twice 1967
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (203649, 3, 'noa165', 'man with the golden gun is one of the weakest bond films. the villain scaramanga is interesting but everything around him is thin.', null); -- 203649 Man with the Golden Gun, The 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (117314, 6, 'noa165', 'for your eyes only is more grounded than most bond films which actually makes it one of the more interesting older entries.', null); -- 117314 For Your Eyes Only 1981
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (192702, 5, 'noa165', 'living daylights is a solid if unmemorable bond film. timothy dalton is more serious than connery and moore which is a welcome change.', null); -- 192702 Living Daylights, The 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (189403, 4, 'noa165', 'licence to kill is too dark and grim for a bond film in my opinion. it is well made but loses the fun that makes bond enjoyable.', null); -- 189403 Licence to Kill 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (29768, 1, 'noa165', 'this 1904 opera short is purely a historical artefact. there is nothing here for a modern viewer looking for an actual film experience.', null); -- 29768 Barbier de Sville, Le 1904
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (29771, 3, 'noa165', 'this opera performance is beautiful music but as a film experience it is very dry and only really for dedicated opera fans.', null); -- 29771 Barbier de Sville, Le 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (29772, 3, 'noa165', 'another opera recording that is nice musically but not really engaging as a film. very niche content.', null); -- 29772 Barbier von Sevilla, Der 1972
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (78877, 2, 'noa165', 'dark mist is too vague and abstract to be engaging. could not figure out what it was trying to say or do.', null); -- 78877 Dark Mist, The 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (82868, 2, 'noa165', 'this german documentary is very culturally specific and academic. hard to engage with without the relevant background knowledge.', null); -- 82868 Denk ich an Deutschland - Wir haben vergessen zurckzukehren 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (78702, 2, 'noa165', 'dari jemapoh ke manchestee is a malay comedy that is too culturally specific for me to follow or enjoy properly.', null); -- 78702 Dari Jemapoh ke Manchestee 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (126792, 2, 'noa165', 'this korean film is very slow and the story did not translate well for me at all. the pacing is really difficult.', null); -- 126792 Geudeulmanui sesang 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (57894, 2, 'noa165', 'this french meta film about cinema is too intellectual and slow for my taste. interesting concept but hard to actually sit through.', null); -- 57894 Cent et une nuits de Simon Cinma, Les 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (25729, 1, 'noa165', 'this 1968 turkish film is too obscure and dated. could not engage with the story or characters at all.', null); -- 25729 Azrail benim 1968
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (28085, 2, 'noa165', 'this filipino film is too culturally specific. the references and the humor did not land for me at all.', null); -- 28085 Bakit may kahapon pa? 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (36426, 2, 'noa165', 'this chinese film has beautiful cinematography but the extremely slow pacing makes it very hard to stay engaged.', null); -- 36426 Bian cheng 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (89441, 3, 'noa165', 'doki doki is a japanese short that is too abstract for me. without the cultural context i found it really hard to understand.', null); -- 89441 Doki-Doki 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (89823, 2, 'noa165', 'le domaine is a very minimalist french short. the atmosphere is nice but nothing actually happens and i lost patience quickly.', null); -- 89823 Domaine, Le 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (96239, 2, 'noa165', 'this french film is quite dated and the humor does not really translate to a modern viewer at all.', null); -- 96239 Dtachez vos ceintures 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (99875, 2, 'noa165', 'emigranti is a slovenian film that is too culturally specific. the story did not connect with me at all.', null); -- 99875 Emigranti (2002/I) 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (100241, 2, 'noa165', 'en attendant la cigogne is a charming concept but far too slow and understated to hold my attention.', null); -- 100241 En attendant la cigogne 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (111963, 2, 'noa165', 'this opera recording is beautiful music but completely dry as a film experience. really only for dedicated opera enthusiasts.', null); -- 111963 Fidelio 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (117582, 1, 'noa165', 'foreigners out is a deeply uncomfortable documentary that was more upsetting than thought provoking. not something i would ever recommend.', null); -- 117582 Foreigners out! Schlingensiefs Container 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (121912, 1, 'noa165', 'this 1921 silent short is purely a historical artefact. no narrative, no characters, nothing for a modern viewer to engage with.', null); -- 121912 Fur Coats and Pants 1921
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (129042, 2, 'noa165', 'this verdi requiem is an impressive piece of music but as a film it is extremely dry. not something i can engage with as entertainment.', null); -- 129042 Giuseppe Verdi: Messa da Requiem 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (141779, 2, 'noa165', 'the berlioz te deum is a beautiful classical performance but as a film it is very dry and only for classical music specialists.', null); -- 141779 Hector Berlioz: Te Deum 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (175872, 2, 'noa165', 'this khachaturian documentary is very academic and dry. interesting for classical music fans but not for general audiences at all.', null); -- 175872 Khachaturian 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (175873, 3, 'noa165', 'the khachaturian piano concerto is really dramatic music but as a film it is still quite dry for anyone not into classical music.', null); -- 175873 Khachaturian Piano Concerto 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (175879, 3, 'noa165', 'khadgam is a telugu action film that is entertaining enough but very formulaic and the pacing is uneven throughout.', null); -- 175879 Khadgam 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (175881, 2, 'noa165', 'this soviet adaptation of tolstoy is beautifully filmed but impossibly slow for a modern viewer. only for very patient film fans.', null); -- 175881 Khadzhi murat 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (20446, 1, 'noa165', 'this 1898 short is purely a historical document. there is no film experience here at all for a modern viewer.', null); -- 20446 Armenian Archbishop, Rome 1898
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (17370, 1, 'noa165', 'this 1948 indian film is too old and culturally specific to engage with meaningfully. only of historical interest.', null); -- 17370 Anjangarh (1948/II) 1948
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (22093, 1, 'noa165', 'this 1977 marathi film is very obscure and i could not connect with the story or the characters at all.', null); -- 22093 Asla Navra Nakoga Bai 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (47456, 1, 'noa165', 'the broken coin is a 1915 silent serial that only has value as a piece of early film history. impossible to watch as entertainment today.', null); -- 47456 Broken Coin, The 1915
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (85524, 1, 'noa165', 'this 1941 portuguese film is completely inaccessible for a modern viewer. only of archival interest.', null); -- 85524 Dia  Nosso, O 1941
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (34306, 3, 'noa165', 'berlin berlin is a german comedy with some funny moments but the humor is very culturally specific and does not always translate well.', null); -- 34306 Berlin Berlin 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (34304, 2, 'noa165', 'berlin babylon is too slow and abstract for my taste. the documentary is beautifully filmed but nothing actually happens.', null); -- 34304 Berlin Babylon 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (15187, 3, 'noa165', 'amsterdamned is a dutch thriller that is decent but quite dated now. the canal setting is interesting but the story is forgettable.', null); -- 15187 Amsterdamned 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (31256, 2, 'noa165', 'battle squad is a very dated war film with nothing to distinguish it from dozens of similar films from the same era.', null); -- 31256 Battle Squad 1961
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (64230, 2, 'noa165', 'this french documentary is too academic and dry to be engaging. the subject is interesting but the presentation is very difficult.', null); -- 64230 Cinquantenaire du deuxime sexe, 1949-1999 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (70507, 2, 'noa165', 'copi je t''aime is a very niche french documentary. without knowing the subject it is almost impossible to get into.', null); -- 70507 Copi, je t'aime 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (25943, 2, 'noa165', 'this cantonese film did not work for me at all without subtitles. not accessible for me as a viewer.', null); -- 25943 Baan sau chuk dak hin dui 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (28092, 2, 'noa165', 'bakom jalusin is a swedish film that is far too slow and quiet. i appreciate the minimalist style but nothing happens at all.', null); -- 28092 Bakom jalusin 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (102311, 2, 'noa165', 'era outra vez is too quiet and slow for me. the portuguese setting is nice but the story does not build to anything satisfying.', null); -- 102311 Era outra vez 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (104484, 2, 'noa165', 'eu adam is an israeli film with very local humor that i found really hard to connect with.', null); -- 104484 Eu Adam 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (105587, 2, 'noa165', 'examen is a bleak romanian short that is too slow and depressing to be enjoyable even as a short film.', null); -- 105587 Examen 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (122277, 3, 'noa165', 'fyrsti april is an icelandic april fools short that is mildly amusing but too culturally specific to be very engaging.', null); -- 122277 Fyrsti aprl 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (51413, 2, 'noa165', 'c''est le vent is a french short that is too minimal and slow. the atmosphere is pleasant but there is nothing to hold your attention.', null); -- 51413 C'est le vent 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (60408, 2, 'noa165', 'chek 2000 is very obscure and i could not find much to engage with in it at all.', null); -- 60408 Chek 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (58084, 2, 'noa165', 'cerebrium is experimental and abstract in a way that i found more confusing than interesting.', null); -- 58084 Cerebrium 2001
