insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (644,10,'Noa','Funny, very romantic, one of the most rewatchable teen movies and one of my personal favorites',NULL);  # 644 10 Things I Hate About You 1999
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (1038,8,'Noa','Sweet, funny, and very likable. Light romantic comedy with a nostalgic early-2000s feel',NULL);  # 1038 13 Going On 30 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (151616,8,'Noa','Very funny and romantic comedy, super fun to re-watch',NULL);  # 151616 How to Lose a Guy in 10 Days 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (46878,7,'Noa','Fun moments, awkward romance and love triangle drama',NULL);  # 46878 Bridget Jones: The Edge of Reason 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (62460,9,'Noa','Charming, visually beautiful which I really liked and easy to love',NULL);  # 62460 Chocolat 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (33492,8,'Noa','Romantic, the relationships feel realistic and loved  the food and restaurant setting',NULL);  # 33492 Bella Martha 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (34104,8,'Noa','Good chemistry and plenty of heart',NULL);  # 34104 Benny & Joon 1993
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (31715,9,'Noa','Sweet, funny, and I loved that the friendship feels real and emotional',NULL);  # 31715 Beaches 1988
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (118980,7,'Noa','The movie is slower than some of the others but has an easy charm',NULL);  # 118980 Frankie and Johnny 1991
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (12744,7,'Noa','Cute and easy to watch',NULL);  # 12744 Always 1989
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (66194,10,'Noa','It is funny, stylish, and still feels iconic years later. The characters are memorable and the movie is very easy to rewatch',NULL);  # 66194 Clueless 1995
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (74259,7,'Noa','A little weird, musical romantic comedy with a retro style',NULL);  # 74259 Cry-Baby 1990
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (59578,9,'Noa','Creative, visually beautiful, and one of the most entertaining family movies',NULL);  # 59578 Charlie and the Chocolate Factory 2005
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (96593,8,'Noa','Bold sci-fi with emotional weight',NULL);  # 96593 E.T. the Extra-Terrestrial 1982
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (149287,8,'Noa','Fun adventure, darker than the first movie and has more mystery, but still keeps the fun feeling',NULL);  # 149287 Hook 1991
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (131885,8,'Noa','Classic adventure movie with fun characters and a lot of energy',NULL);  # 131885 Goonies, The 1985
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (139657,7,'Noa','Fun classical with good energy',NULL);  # 139657 Harry Potter and the Sorcerer's Stone 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (139650,8,'Noa','Strong franchise entry, very watchable',NULL);  # 139650 Harry Potter and the Chamber of Secrets 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (139655,8,'Noa','One of the strongest Harry Potter films, with a darker tone and a more mature feel',NULL);  # 139655 Harry Potter and the Prisoner of Azkaban 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (139652,9,'Noa','Darker tone, bigger stakes, and more action make it stand out in the series',NULL);  # 139652 Harry Potter and the Goblet of Fire 2005
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (30959,9,'Noa','One of the strongest Batman movies because it is darker, more serious, and has a great cast',NULL);  # 30959 Batman Begins 2005
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (30955,9,'Noa','Classic version of Batman with a very strong visual style',NULL);  # 30955 Batman 1989
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (30967,8,'Noa','Good energy very memorable, loved the characters',NULL);  # 30967 Batman Returns 1992
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (30976,9,'Noa','Exciting and easy to enjoy, good mystery and emotional story',NULL);  # 30976 Batman: Mask of the Phantasm 1993
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (30961,8,'Noa','A more futuristic Batman story that still feels emotional and exciting',NULL);  # 30961 Batman Beyond: Return of the Joker (2000/I) 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (10830,9,'Noa','Very suspenseful with a strong atmosphere and great sci-fi visuals',NULL);  # 10830 Alien 1979
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (10920,8,'Noa','Visually impressive, more action-focused',NULL);  # 10920 Aliens 1986
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (21213,8,'Noa','Emotional sci-fi movie that feels different from most others in the genre',NULL);  # 21213 Artificial Intelligence: AI 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (25192,8,'Noa','Strong performances and real emotion',NULL);  # 25192 Aviator, The 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (56871,10,'Noa','It is very entertaining from start to finish and one of Leonardo DiCaprios most likable performances',NULL);  # 56871 Catch Me If You Can 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (129185,9,'Noa','Strong action, emotional depth, and a story that really hits',NULL);  # 129185 Gladiator 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (46169,8,'Noa','Thoughtful drama with good depth',NULL);  # 46169 Braveheart 1995
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (39551,6,'Noa','Powerful scenes and solid action, though the pacing can feel uneven at times',NULL);  # 39551 Black Hawk Down 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (40199,8,'Noa','Moody sci-fi with real depth',NULL);  # 40199 Blade Runner 1982
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (100130,8,'Noa','Well-acted and emotionally engaging',NULL);  # 100130 Empire of the Sun 1987
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (113506,8,'Noa','Serious, polished, and absorbing',NULL);  # 113506 Finding Neverland 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (67395,9,'Noa','Powerful story with strong performances',NULL);  # 67395 Color Purple, The 1985
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (10702,8,'Noa','Interesting, well made, and engaging',NULL);  # 10702 Alice Doesn't Live Here Anymore 1974
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (8183,8,'Noa','Strong performances and real emotion',NULL);  # 8183 Age of Innocence, The 1993
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (14477,8,'Noa','Thoughtful drama with good depth',NULL);  # 14477 Amistad 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (32707,8,'Noa','Well-acted and emotionally engaging',NULL);  # 32707 Before Night Falls 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (41518,7,'Noa','Entertaining, Johnny Depp makes the movie more interesting, even if the story is a bit uneven.',NULL);  # 41518 Blow 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (56304,8,'Noa','Engaging crime drama, well acted',NULL);  # 56304 Casino 1995
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (131780,9,'Noa','One of the best crime movies, excellent pacing',NULL);  # 131780 Goodfellas 1990
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (123849,8,'Noa','Tense story with solid performances',NULL);  # 123849 Gangs of New York 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (123435,8,'Noa','Very clever. Keeps you interested because you never know what is real.',NULL);  # 123435 Game, The 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (69812,6,'Noa','Decent tension, but not amazing',NULL);  # 69812 Conspiracy Theory 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (54209,6,'Noa','Watchable thriller with some flaws',NULL);  # 54209 Cape Fear 1991
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (94741,8,'Noa','Keeps the tension going well',NULL);  # 94741 Duel (1971/I) 1971
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (97727,9,'Noa','Distinctive, emotional, and memorable',NULL);  # 97727 Edward Scissorhands 1990
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (97360,8,'Noa','Small-scale but emotionally effective',NULL);  # 97360 Ed Wood 1994
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (120506,7,'Noa','Keeps interest, even if uneven',NULL);  # 120506 From Hell 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (47130,6,'Noa','Dark and unusual film with strong atmosphere, but it was not fully easy to connect with',NULL);  # 47130 Bringing Out the Dead 1999
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (112290,10,'Noa','Really liked it, one of the most famous twists in film.',NULL);  # 112290 Fight Club 1999
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (61751,10,'Noa','Atmospheric, smart, and unforgettable',NULL);  # 61751 Children of Men, The 2005
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (70959,8,'Noa','Big-hearted and very watchable',NULL);  # 70959 Corpse Bride, The 2005
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (65811,9,'Noa','Smart sci-fi with strong atmosphere',NULL);  # 65811 Close Encounters of the Third Kind 1977
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (67388,7,'Noa','Decent watch, modest impact',NULL);  # 67388 Color of Money, The 1986
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (85871,5,'Noa','It has some fun moments, but it is not as exciting or polished as the stronger Bond movies.',NULL);  # 85871 Diamonds Are Forever 1971
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (92573,8,'Noa','Interesting because it is the first Bond movie, even if it feels old-fashioned.',NULL);  # 92573 Dr. No 1962
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (120574,8,'Noa','Classic Bond fun, polished and entertaining',NULL);  # 120574 From Russia with Love 1963
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (117314,7,'Noa','Solid Bond entertainment',NULL);  # 117314 For Your Eyes Only 1981
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (130953,7,'Noa','Stylish Bond entry with good pace',NULL);  # 130953 Goldfinger 1964
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (130945,8,'Noa','Classic Bond fun, polished and entertaining',NULL);  # 130945 GoldenEye 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (86263,6,'Noa','Classic appeal, but less exciting',NULL);  # 86263 Die Another Day 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (1390,6,'Noa','Modest film, limited impact, feels too messy overall',NULL);  # 1390 1941 1979
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (7842,9,'Noa','Interesting, well made, and engaging',NULL);  # 7842 After Hours 1985
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (30686,10,'Noa','Emotionally heavy and very well acted, it feels real and leaves a lasting impact',NULL);  # 30686 Basketball Diaries, The 1995
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (15187,6,'Noa','Has an unusual thriller style and some tension, but it is not fully memorable',NULL);  # 15187 Amsterdamned 1988
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (20253,7,'Noa','Creative and strange in a good way, though not always focused enough',NULL);  # 20253 Arizona Dream 1993
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (28631,6,'Noa','Has a nice idea and gentle tone, but it does not fully stand out',NULL);  # 28631 Balloon 1991
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (56282,7,'Noa','Interesting visual style, but the story leaves only a modest impression',NULL);  # 56282 Cashback 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (65522,6,'Noa','Decent tension, but not amazing',NULL);  # 65522 Clearing, The 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (69469,8,'Noa','Small-scale but emotionally effective',NULL);  # 69469 Confidences trop intimes 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (80969,6,'Noa','The concept is interesting, but the movie never becomes especially memorable.',NULL);  # 80969 Dear God 1996
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (22651,5,'Noa','The mystery is interesting at first and the cast is strong, but the story becomes confusing and less exciting as it goes on',NULL);  # 22651 Astronaut's Wife, The 1999
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (58084,6,'Noa','Has some interesting sci-fi ideas, but the story is not engaging enough',NULL);  # 58084 Cerebrium 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (116556,8,'Noa','Engaging thriller, clever and interesting',NULL);  # 116556 Following 1998
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (121552,6,'Noa','Simple and watchable, but it feels too small to leave a real impact',NULL);  # 121552 Full Moon Rising 1996
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (113459,7,'Noa','Interesting setup, mixed payoff',NULL);  # 113459 Find Me Guilty 2005
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (14132,7,'Noa','Funny in parts and easy to watch, even if it is not as strong as the first one.',NULL);  # 14132 American Pie 2 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (109421,8,'Noa','Fun action scenes and good energy',NULL);  # 109421 Fast and the Furious, The 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (34077,8,'Noa','Strong performances and real emotion',NULL);  # 34077 Benjamin Button 2006
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (142491,7,'Noa','It has cool visuals and an interesting main character, but it is not one of the strongest superhero movies',NULL);  # 142491 Hellboy 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (46167,6,'Noa','Serious movie, but it feels slower and less engaging than some of the other dramas',NULL);  # 46167 Brave, The 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (121852,6,'Noa','Has a funny setup, but the humor does not stay strong throughout',NULL);  # 121852 Funny Thing Happened at the Quick Mart, A 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (68065,6,'Noa','A low-key film that keeps things simple but does not leave a strong impression',NULL);  # 68065 Comfort Blanket 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (116358,6,'Noa','The story is decent, but it never becomes especially emotional or memorable',NULL);  # 116358 Focus 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (105851,6,'Noa','Has some entertaining parts, but the tone feels uneven and not fully convincing',NULL);  # 105851 Exit to Eden 1994
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (32180,10,'Noa','Classic Disney story with beautiful music and a nostalgic feel',NULL);  # 32180 Beauty and the Beast 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (849,7,'Noa','Entertaining fun family movie',NULL);  # 849 101 Dalmatians II: Patch's London Adventure 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (9813,7,'Noa','Good action, a bit uneven',NULL);  # 9813 Aladdin in Nasira's Revenge 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (70960,5,'Noa','The mystery idea is fine, but the movie feels too slight overall',NULL);  # 70960 Corpse Came C.O.D., The 1947
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (83470,6,'Noa','Has tension, but feels slight',NULL);  # 83470 Descent 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (78877,6,'Noa','Some scenes are interesting, but the movie feels inconsistent',NULL);  # 78877 Dark Mist, The 1996
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (89441,6,'Noa','Interesting in concept, but the emotional side is not strong enough',NULL);  # 89441 Doki-Doki 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (100241,7,'Noa','Has a very interesting direction, but it does not develop into something very memorable',NULL);  # 100241 En attendant la cigogne 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (101687,6,'Noa','A modest film with limited scope, so it does not leave much of an impact',NULL);  # 101687 Enter Achilles 1996
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (102311,3,'Noa','Nice basic idea, but the final result feels small and forgettable',NULL);  # 102311 Era outra vez 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (103755,5,'Noa','A few interesting moments, but not very memorable overall',NULL);  # 103755 Espera, La 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (104484,3,'Noa','There are a few decent scenes, but never fully comes together as a complete film',NULL);  # 104484 Eu Adam 1996
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (105587,6,'Noa','Interesting concept, but not enough happens to make it stand out',NULL);  # 105587 Examen 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (110509,5,'Noa','Has a few engaging moments, but overall it feels easy to forget',NULL);  # 110509 Feel Neil 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (113814,5,'Noa','Struggles to maintain interest despite having a few promising elements',NULL);  # 113814 Fire Inside, The 1998
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (116829,4,'Noa','Becomes harder to stay invested as it goes on. It has a few good moments, but overall it feels smaller and less memorable than stronger dramas',NULL);  # 116829 Foot Shooting Party, The 1994
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (122277,6,'Noa','The movie has some charm, but it does not leave a lasting impression',NULL);  # 122277 Fyrsti aprl 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (126792,6,'Noa','Has several solid moments, but the story is not memorable enough',NULL);  # 126792 Geudeulmanui sesang 1996
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (134680,4,'Noa','There are a few good moments, but overall it never becomes memorable enough to really stand out',NULL);  # 134680 Group 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (138142,5,'Noa','Focuses on an interesting direction, but doesn’t develop it strongly enough',NULL);  # 138142 Hand of Fate 1999
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (142881,5,'Noa','Even with a few emotional moments, the story feels too small to leave a strong impression overall',NULL);  # 142881 Henry and Marvin 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (146758,7,'Noa','Easy and fun to watch, even if not especially memorable',NULL);  # 146758 Hit the Highway, Honey 1998
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (152856,4,'Noa','Feels limited in scope, which makes the overall experience less impactful',NULL);  # 152856 Hungry 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (63125,7,'Noa','Cute and light, especially for holiday romance fans',NULL);  # 63125 Christmas Tree and a Wedding, A 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (65602,5,'Noa','Shows some potential, but doesn’t take it far enough to be memorable',NULL);  # 65602 Click Three Times 1999
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (65762,5,'Noa','It has an unusual concept and a few funny moments, but overall it feels too small and forgettable to really stand out',NULL);  # 65762 Clockwork Maury, A 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (75646,6,'Noa','Has a decent premise, but the execution feels a bit flat overall',NULL);  # 75646 Custodial Code, The 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (79593,5,'Noa','There are a few entertaining moments, but the movie feels uneven and never fully pulls you in',NULL);  # 79593 David Nelson Live 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (79678,6,'Noa','It is easy enough to watch, even if the story does not fully come together in the end',NULL);  # 79678 Dawn of the Friend 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (82868,6,'Noa','Interesting subject, but the film does not stand out strongly enough',NULL);  # 82868 Denk ich an Deutschland - Wir haben vergessen zurckzukehren 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (85117,7,'Noa','Strong atmosphere and engaging moments throughout, even if the pacing is a bit slow at times',NULL);  # 85117 Devils Are Dreaming 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (86399,8,'Noa','The historical setting and subject matter make it interesting',NULL);  # 86399 Dieses Jahr in Czernowitz 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (89823,5,'Noa','The atmosphere is strong, but the story feels a little distant, which makes it harder to fully connect to',NULL);  # 89823 Domaine, Le 1999
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (93829,6,'Noa','The movie has an unusual style and a few interesting scenes, but it feels too strange and uneven to really connect with',NULL);  # 93829 Driving Fish 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (96193,5,'Noa','There are a few good ideas and some nice atmosphere, but overall it feels too small to leave much of an impression',NULL);  # 96193 Drive de l'Atlantic, La 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (99875,6,'Noa','The story has some emotional potential, but it never becomes strong enough to really stand out',NULL);  # 99875 Emigranti (2002/I) 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (104266,6,'Noa','There are a few interesting scenes and a serious atmosphere, but the pacing feels too slow overall',NULL);  # 104266 Etat 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (105697,6,'Noa','The movie has a serious tone and a few good moments, but it is difficult to stay fully invested in the story',NULL);  # 105697 Exec, The 2006
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (113547,6,'Noa','The concept is funny and relatable, but the movie feels uneven and not as clever as it could have been',NULL);  # 113547 Fine Line Between Cute and Creepy, The 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (114955,7,'Noa','It has a fun summer atmosphere and an easy charm that makes it enjoyable to watch',NULL);  # 114955 Flamingo Kid, The 1984
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (123371,6,'Noa','There are a few entertaining moments, but the story feels too small and forgettable overall',NULL);  # 123371 Game Day 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (129887,6,'Noa','The sports theme is fun and there are a few enjoyable moments, but it never becomes memorable enough overall',NULL);  # 129887 Goal Club 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (133608,5,'Noa','The idea behind the movie is interesting, but the story feels too small and uneven to really stand out',NULL);  # 133608 Great Gabble, The 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (137958,5,'Noa','There are a few scenes with good energy, but overall the movie feels too uneven to stay interesting',NULL);  # 137958 Hammer and Cycle 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (143582,6,'Noa','The humor is unusual and there are some funny moments, but it is not something that stays with you afterward',NULL);  # 143582 Here Comes Dr. Tran 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (146943,6,'Noa','The idea has some potential, but the movie never becomes emotional or exciting enough to really work',NULL);  # 146943 Hitting Zero 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (2057,5,'Noa','There are a few emotional moments, but overall the story feels too small to leave a strong impression',NULL);  # 2057 2wks, 1yr 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (2352,6,'Noa','The movie has a few good moments, but it feels too limited and forgettable overall',NULL);  # 2352 36K 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (2656,5,'Noa','The western setting is interesting, but the movie never becomes exciting enough to stand out',NULL);  # 2656 5 Card Stud 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (4948,6,'Noa','There are a few interesting scenes, but the movie feels too quiet and not memorable enough overall',NULL);  # 4948 Able's House Is Green, The 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (5889,6,'Noa','It has a few charming moments, but overall it feels too dated to leave much of an impression',NULL);  # 5889 Act Your Age 1939
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (8820,4,'Noa','Leaves a mild impression, without building toward something more meaningful',NULL);  # 8820 Ai-Fak 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (16730,6,'Noa','Has a few nice moments, but overall it does not feel very distinctive',NULL);  # 16730 Angel on My Shoulder 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (19433,4,'Noa','Some parts are decent, but the film feels too weak to be memorable',NULL);  # 19433 Aquarium, L' 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (24235,5,'Noa','The movie has an unusual tone and a few interesting character moments, but it never fully comes together',NULL);  # 24235 Aunt Tiger 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (24259,6,'Noa','Decent suspense, but the payoff is not strong enough',NULL);  # 24259 Aura 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (28085,5,'Noa','The movie has some dramatic potential, but it did not work well enough for me',NULL);  # 28085 Bakit may kahapon pa? 1996
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (33965,6,'Noa','The movie has a classic romantic style and some charming moments, but it feels a little too old-fashioned overall',NULL);  # 33965 Bendita seas 1948
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (38743,6,'Noa','The idea is promising, but the execution feels too plain',NULL);  # 38743 Birthmark, The 1987
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (45377,5,'Noa','Has a few interesting elements, but overall it feels average',NULL);  # 45377 Boy 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (50012,6,'Noa','The family comedy style is fun in parts, but the humor feels too simple to really stay with you afterward',NULL);  # 50012 Burning the Grump 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (51413,4,'Noa','The concept is fine, but the movie feels too quiet to stand out',NULL);  # 51413 C'est le vent 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (54879,6,'Noa','A few moments are entertaining, but the overall film is not very memorable',NULL);  # 54879 Card Sharks (2001/II) 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (59656,6,'Noa','Some moments work, but the movie does not build enough impact',NULL);  # 59656 Charlie the Ox 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (60408,5,'Noa','Interesting idea, but the movie feels underdeveloped',NULL);  # 60408 Chek 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (70507,6,'Noa','The movie has a softer emotional side, but the pacing makes it harder to stay fully invested',NULL);  # 70507 Copi, je t'aime 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (74133,6,'Noa','It has a serious tone and a few strong scenes, but the story feels a little too slow overall',NULL);  # 74133 Crutch 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (78702,6,'Noa','The road-trip idea is fun, but the movie feels uneven and not as funny as it could have been',NULL);  # 78702 Dari Jemapoh ke Manchestee 1998
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (96681,5,'Noa','There are a few amusing moments, but the humor is too random to really make the movie work',NULL);  # 96681 Earl's Your Uncle 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (99633,5,'Noa','The atmosphere is interesting, but the plot feels too confusing to fully connect with',NULL);  # 99633 Elysium 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (102108,8,'Noa','Interesting topic, especially for fans of the franchise',NULL);  # 102108 Epic at Sea: The Making of 'Pirates of the Caribbean: The Curse of the Black Pearl', An 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (137709,7,'Noa','Enjoyable if you already like this type of movie',NULL);  # 137709 Halo 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (400853,7,'Noa','Fun cast and entertaining moments, even with flaws',NULL);  # 400853 Parenthood 1990
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (406158,6,'Noa','Entertaining action, but not one of the stronger entries',NULL);  # 406158 Spider-Man 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (406411,7,'Noa','It is fun to watch if you already enjoy Star Wars because it adds more action and background to the characters',NULL);  # 406411 Star Wars: Clone Wars 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (121,7,'Noa','Fun and nostalgic, even if a little uneven',NULL);  # 121 'High Sign', The 1921
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (263,8,'Noa','Light, romantic, and easy to watch',NULL);  # 263 'Til There Was You 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (370,6,'Noa','Has some charm, but does not leave a strong impression',NULL);  # 370 ...continuavano a chiamarlo Trinit 1972
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (517,4,'Noa','Fine for fans of the franchise, but not essential',NULL);  # 517 .hack//Quarantine 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (675,6,'Noa','The story has potential, but it does not become especially memorable',NULL);  # 675 100 Days 1991
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (676,6,'Noa','Has some meaningful moments, but overall it stays fairly forgettable',NULL);  # 676 100 Days 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (818,6,'Noa','Some parts are pleasant, but the film does not leave a strong impression',NULL);  # 818 1000 Marys 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (837,8,'Noa','Fun adventure that is easy to enjoy',NULL);  # 837 1001 Nights 1998
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (870,6,'Noa','Quirky and different, but not strong enough to fully stand out',NULL);  # 870 101 Reykjavk 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (878,4,'Noa','Has a few decent moments, but it feels too ordinary overall',NULL);  # 878 102 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (952,5,'Noa','The film has some good parts, but the overall effect is limited',NULL);  # 952 11:00 AM 1999
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (1018,7,'Noa','Interesting sci-fi idea, even if somewhat uneven',NULL);  # 1018 12:01 1993
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (1024,7,'Noa','The concept is interesting, but the movie does not fully deliver',NULL);  # 1024 13 (1999/I) 1999
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (1046,6,'Noa','Has an unusual atmosphere, but it is not very memorable overall',NULL);  # 1046 13 Moons 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (3634,6,'Noa','Interesting subject, but not strong enough overall',NULL);  # 3634 A&E Biography: Captain Bligh - Mutiny on the Bounty 1996
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (13343,7,'Noa','Fun action scenes, even if uneven in parts',NULL);  # 13343 Amazing Adventures of Spider-Man, The 1999
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (29760,5,'Noa','Simple concept, but overall pretty forgettable',NULL);  # 29760 Barbie Riding Club 1998
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (34306,7,'Noa','Some scenes are enjoyable, but the movie does not feel very special',NULL);  # 34306 Berlin Berlin 1998
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (45312,6,'Noa','It has an interesting outlaw story and a rough older style, but it is harder to connect to the characters than in stronger crime dramas',NULL);  # 45312 Boxcar Bertha 1972
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (53921,8,'Noa','A clever and entertaining take on the film industry, with sharp humor and a fun concept',NULL);  # 53921 Cannes Man 1996
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (58160,6,'Noa','Some tension, but not enough to really stand out',NULL);  # 58160 Certain Fury 1985
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (73574,5,'Noa','Hard to stay interested in overall',NULL);  # 73574 Critters 3 1991
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (79845,7,'Noa','The western setting is interesting and there are a few tense moments',NULL);  # 79845 Day of the Evil Gun 1968
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (92323,6,'Noa','The idea is decent, but the result feels too generic',NULL);  # 92323 Dozen Kliks, A 1998
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (103334,6,'Noa','Has some tension, but the movie feels limited and forgettable',NULL);  # 103334 Escape to Nowhere 1961
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (134675,7,'Noa','Charming and easy to watch',NULL);  # 134675 Grounds for Marriage 1951
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (379327,9,'Noa','Pleasant watch with fun adventure energy',NULL);  # 379327 Adventures of Robin Hood, The 1955
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (379331,6,'Noa','Some mystery elements work, but it is not one of the stronger versions',NULL);  # 379331 Adventures of Sherlock Holmes, The 1984
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (383395,7,'Noa','Interesting to see an older version of Captain America with a classic comic-book feel',NULL);  # 383395 Captain America 1966
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (397121,5,'Noa','Some fun moments, but not as exciting or polished as the later Matrix movies',NULL);  # 397121 Matrix 1993
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (399427,6,'Noa','The concept is interesting, but the overall result feels inconsistent',NULL);  # 399427 Night Gallery 1970
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (405119,6,'Noa','Classic detective idea, but this version does not feel especially strong',NULL);  # 405119 Sherlock Holmes 1951
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (391453,5,'Noa','Interesting idea, but less effective in practice',NULL);  # 391453 Herndon 1983
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (108,4,'Noa','Feels very dated, with weak pacing and not much to hold interest',NULL);  # 108 'G' Men 1935
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (450,5,'Noa','The setup creates some tension and the cast is solid, but the movie moves a little too slowly overall',NULL);  # 450 ...tick...tick...tick... 1970
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (672,6,'Noa','Has a few interesting moments, but the movie does not leave a strong final impact',NULL);  # 672 100 aos de perdn 1998