
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (290070, 10, 'orimor25', 'The contrast between Goeth and Schindler is what makes it unforgettable. Story and direction at their absolute peak, nothing feels wasted in three hours.', null); # 290070 Schindler''s List 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131780, 10, 'orimor25', 'Scorsese built a world so vivid you forget you are watching a film. The Copacabana tracking shot alone is worth the whole runtime.', null); # 131780 Goodfellas 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (297838, 10, 'orimor25', 'Never really left after the first watch. The redemption arc is earned minute by minute, and Freeman''s narration makes even quiet scenes feel profound.', null); # 297838 Shawshank Redemption 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (112290, 10, 'orimor25', 'The twist does not just shock you, it reframes every scene you already watched. Changed how a whole generation thought about unreliable narration.', null); # 112290 Fight Club 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (267038, 10, 'orimor25', 'Every scene works on its own and together they form something greater. The script is untouchable and the dialogue never ages.', null); # 267038 Pulp Fiction 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210511, 9, 'orimor25', 'Nolan built a structure nobody had tried before and executed it perfectly. You feel the confusion alongside the character, never above him.', null); # 210511 Memento 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313478, 10, 'orimor25', 'The reveal on Bespin alone would be enough. Add Dagobah, Hoth, and the best villain entrance in cinema history and this is untouchable.', null); # 313478 Star Wars: Episode V - The Empire Strikes Back 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194500, 10, 'orimor25', 'Lands the ending of a trilogy that had no right to be this consistently great. The Grey Havens farewell is one of the most emotional final 	scenes ever filmed.', null); # 194500 Lord of the Rings: The Return of the King 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (291698, 10, 'orimor25', 'The villain, the tension in every single scene, and that ending. Nothing feels safe from the first frame and Fincher never lets you breathe.', null); # 291698 Se7en 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (117874, 10, 'orimor25', 'Every chapter of his life hits differently, not because of what happens but because you genuinely care about him. The bench scenes carry more emotion than most full films.', null); # 117874 Forrest Gump 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (289109, 9, 'orimor25', 'The Omaha Beach opening is unlike anything filmed before or since. After those twenty minutes you watch the rest of the film in a completely different state of mind.', null); # 289109 Saving Private Ryan 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (271095, 9, 'orimor25', 'Pure adventure filmmaking. The boulder, the Well of Souls, the truck fight, each set piece tops the last and Ford holds it all together effortlessly.', null); # 271095 Raiders of the Lost Ark 1981
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (165961, 9, 'orimor25', 'Barely shows the shark and still terrifies you. The three men on the boat at night is some of the best written dialogue in any blockbuster ever made.', null); # 165961 Jaws 1975
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (326155, 9, 'orimor25', 'Travis Bickle feels real in a way that is genuinely unsettling. De Niro does not play the character, he disappears into him completely.', null); # 326155 Taxi Driver 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10830, 9, 'orimor25', 'The dread builds before the alien even appears. Ridley Scott understood that what you do not see is always scarier than what you do.', null); # 10830 Alien 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10920, 9, 'orimor25', 'Cameron took the same world and made it a completely different genre without losing any tension. Hudson, Vasquez and Hicks are a perfect ensemble.', null); # 10920 Aliens 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (276217, 9, 'orimor25', 'More directorial confidence in a debut than most filmmakers show across an entire career. The ear scene set the tone for everything Tarantino made after it.', null); # 276217 Reservoir Dogs 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (61751, 9, 'orimor25', 'The long uncut takes through a war zone feel completely real. Brutal and beautiful at the same time, and the ending earns every second of tension before it.', null); # 61751 Children of Men, The 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159172, 8, 'orimor25', 'The father and son dynamic between Ford and Connery is the whole film. Best Indiana Jones entry by a comfortable margin.', null); # 159172 Indiana Jones and the Last Crusade 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194497, 9, 'orimor25', 'McKellen makes Gandalf feel genuinely ancient and wise in a way no special effect could achieve on its own. The Shire to Rivendell journey captures Tolkien perfectly.', null); # 194497 Lord of the Rings: The Fellowship of the Ring 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194502, 9, 'orimor25', 'Helms Deep is still the gold standard for large scale battle sequences. Gollum alone was a landmark moment for what digital characters could become.', null); # 194502 Lord of the Rings: The Two Towers 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218219, 9, 'orimor25', 'No clean villain, just humans and nature destroying each other. Miyazaki at his most morally complex and somehow it still ends with something like hope.', null); # 218219 Mononoke-hime 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280270, 9, 'orimor25', 'Not a boxing film, a film about dignity. Going the distance when nobody believes in you, and the final round is one of the most earned moments in sports cinema.', null); # 280270 Rocky 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30959, 9, 'orimor25', 'Gave Batman the psychological seriousness the character always deserved. Nolan built a Gotham that feels like a real city with real consequences.', null); # 30959 Batman Begins 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (123435, 9, 'orimor25', 'Fincher at his most underrated. The paranoia builds so carefully that by the end you genuinely do not know what is real, and Douglas sells every moment.', null); # 123435 Game, The 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56871, 9, 'orimor25', 'DiCaprio is so charming you root for a con man the entire time. Spielberg keeps it light without ever trivializing what the guy actually did to real people.', null); # 56871 Catch Me If You Can 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (129185, 9, 'orimor25', 'Crowe made Maximus a warrior and a grieving father simultaneously and you believe both completely. The arena sequences still hold up decades later.', null); # 129185 Gladiator 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (270971, 8, 'orimor25', 'LaMotta is impossible to like and impossible to look away from. Scorsese shot it in black and white for a reason and every frame proves him right.', null); # 270971 Raging Bull 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176711, 8, 'orimor25', 'The anime chapter and the Crazy 88 fight are unlike anything else Tarantino made. Pure kinetic filmmaking, style completely in service of story.', null); # 176711 Kill Bill: Vol. 1 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (96593, 8, 'orimor25', 'The bicycle across the moon is one of the most iconic images in cinema. Spielberg made the alien feel fragile and precious rather than threatening.', null); # 96593 E.T. the Extra-Terrestrial 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (65811, 8, 'orimor25', 'Holds back the mothership reveal for so long that when it finally comes the payoff is enormous. Patience as a filmmaking virtue at its finest.', null); # 65811 Close Encounters of the Third Kind 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30955, 8, 'orimor25', 'Burton made Gotham feel operatic and genuinely dark. Nicholson understood the assignment and then went further than anyone asked him to.', null); # 30955 Batman 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (306032, 8, 'orimor25', 'More wit per scene than most comedies manage across an entire runtime. Gets better on every rewatch once you know all the overlapping plots.', null); # 306032 Snatch 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238072, 8, 'orimor25', 'The heist almost becomes secondary to how enjoyable the ensemble is. Soderbergh made cool look effortless.', null); # 238072 Ocean''s Eleven 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (214755, 8, 'orimor25', 'The pre-crime concept is genuinely thought through, not just a plot device. One of the smarter sci-fi films of that entire decade.', null); # 214755 Minority Report 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (116556, 8, 'orimor25', 'Shot with nothing and shows none of the budget constraints. The reverse structure was already pointing directly at what Nolan would do with Memento.', null); # 116556 Following 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (174953, 8, 'orimor25', 'Made before environmental collapse was a mainstream conversation and still feels urgent today. The Giant Warrior sequence is terrifying for an animated film.', null); # 174953 Kaze no tani no Naushika 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188507, 8, 'orimor25', 'Gibson and Glover clicked instantly and the rooftop opening establishes Riggs as genuinely unhinged, a quality the sequels slowly diluted away.', null); # 188507 Lethal Weapon 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130953, 8, 'orimor25', 'Connery at peak Bond, Oddjob as one of the great silent henchmen. The gold-painted woman is an image that defined the franchise visually forever.', null); # 130953 Goldfinger 1964
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120574, 8, 'orimor25', 'The Orient Express setting creates suspense before the action even starts. Probably the most intelligent plot construction in the entire Bond franchise.', null); # 120574 From Russia with Love 1963
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130945, 8, 'orimor25', 'Reinvented the franchise for a post Cold War world and actually had something to say. Bean as a friend turned villain gave it emotional weight most Bond films never attempt.', null); # 130945 GoldenEye 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56304, 8, 'orimor25', 'Three hours and never drags. Sharon Stone deserved every award she did not receive and the money-counting montages are genuinely hypnotic.', null); # 56304 Casino 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (209158, 8, 'orimor25', 'Scorsese bottling the energy of the streets he grew up on. De Niro walking in to Jumping Jack Flash is one of the coolest character introductions in any film.', null); # 209158 Mean Streets 1973
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (67395, 8, 'orimor25', 'Whoopi Goldberg and Oprah carry enormous emotional weight together. Rare that a literary adaptation translates the heart of its source this faithfully.', null); # 67395 Color Purple, The 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (97727, 8, 'orimor25', 'Depp communicates everything through body language with almost no dialogue needed. The suburban satire underneath the fairy tale is sharper than it first appears.', null); # 97727 Edward Scissorhands 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (54209, 8, 'orimor25', 'De Niro as Cady never rushes. He takes his time and that patience makes every scene genuinely uncomfortable to sit through.', null); # 54209 Cape Fear 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (164572, 8, 'orimor25', 'Pam Grier was overdue a film built entirely around her. Tarantino restrained himself completely and the result is his most character driven work.', null); # 164572 Jackie Brown 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (67388, 8, 'orimor25', 'Newman and Cruise as a generational clash is perfect casting. The pool hall sequence is a masterclass in filming competitive tension without a single punch thrown.', null); # 67388 Color of Money, The 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (330670, 8, 'orimor25', 'Young DiCaprio against De Niro at his most intimidating is a genuinely remarkable thing to watch. The cruelty is hard to sit through and completely necessary.', null); # 330670 This Boy''s Life 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131885, 8, 'orimor25', 'Those kids feel like real kids, not movie kids. The pirate ship reveal in the cave is one of the great adventure payoffs in any family film.', null); # 131885 Goonies, The 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256632, 8, 'orimor25', 'Depp made Captain Jack genuinely iconic, not just entertaining. The three-way sword fight is choreographed like a comedy routine and every beat lands.', null); # 256632 Pirates of the Caribbean: The Curse of the Black Pearl 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311038, 8, 'orimor25', 'Molina brought real tragedy to a villain origin and elevated the whole film. The train sequence and the surgery scene showed what superhero cinema could actually do.', null); # 311038 Spider-Man 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (94741, 8, 'orimor25', 'A truck is the villain and it works completely. Made with almost nothing and announced a major directorial talent immediately.', null); # 94741 Duel 1971
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46169, 8, 'orimor25', 'The battle sequences have a rawness that big budget films rarely manage. Gibson directed with a chaos that suits the material in every scene.', null); # 46169 Braveheart 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30976, 8, 'orimor25', 'Phantasm is a genuinely tragic villain whose backstory reframes Bruce Wayne in a meaningful way. The best Batman film in animation and one of the best overall.', null); # 30976 Batman: Mask of the Phantasm 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159665, 8, 'orimor25', 'The farmhouse opening alone justifies the runtime. Waltz as Landa is one of the great villain performances and the film builds perfectly around him.', null); # 159665 Inglorious Bastards 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139655, 8, 'orimor25', 'Cuaron brought a real directorial vision to a franchise that needed one. The time-turner third act is the most satisfying puzzle the series ever constructed.', null); # 139655 Harry Potter and the Prisoner of Azkaban 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (337166, 8, 'orimor25', 'Woody''s fear of being replaced is more relatable than most human characters in live action. Pixar proved from the start that animation could carry genuinely adult anxieties.', null); # 337166 Toy Story 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (123849, 8, 'orimor25', 'Day-Lewis as Bill the Butcher is a force of nature. The 19th century New York feels so detailed it reads as a document rather than a set.', null); # 123849 Gangs of New York 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (7842, 8, 'orimor25', 'A single bad night in Manhattan turned into a Kafkaesque comedy nightmare. Griffin Dunne''s face tells the whole story even when the script does not need to.', null); # 7842 After Hours 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (13547, 8, 'orimor25', 'A student film with complete command of visual storytelling. No dialogue needed, the images carry everything Spielberg wanted to say.', null); # 13547 Amblin'' 1968
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313160, 8, 'orimor25', 'Makes Kubrick feel like a real obsessive rather than a myth. The behind the scenes footage from The Shining is worth the full runtime on its own.', null); # 313160 Stanley Kubrick: A Life in Pictures 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300229, 8, 'orimor25', 'Shrek and Donkey are one of the great comedy duos. Pure nostalgia but the film earns every bit of it, and mentioning it puts a smile on everyone''s face.', null); # 300229 Shrek 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (100130, 7, 'orimor25', 'Spielberg committed fully to the child''s perspective and never broke from it. The internment sequences are patient and more devastating because of that patience.', null); # 100130 Empire of the Sun 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185628, 7, 'orimor25', 'The research showed. Watanabe deserved his Oscar nomination and honestly deserved to win it.', null); # 185628 Last Samurai, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313479, 7, 'orimor25', 'The Ewoks are a problem but the throne room confrontation between Luke and Vader is the emotional peak of the entire original trilogy and nothing else comes close.', null); # 313479 Star Wars: Episode VI - Return of the Jedi 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176712, 7, 'orimor25', 'The buried alive sequence with no music is some of the best sustained tension Tarantino ever put on screen. Volume 2 earns its slower pace completely.', null); # 176712 Kill Bill: Vol. 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (160524, 7, 'orimor25', 'Pacino plays the guilt and sleep deprivation subtly, which makes it more effective than if he had gone big with it. The Alaska setting stays oppressive throughout.', null); # 160524 Insomnia 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (200521, 7, 'orimor25', 'Cruise gives his most unguarded performance and it sits at the centre of three hours of intersecting lives. The frog rain is brave and divisive and completely intentional.', null); # 200521 Magnolia 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (304862, 7, 'orimor25', 'The autumn colour palette and the Horseman design are genuinely striking. Burton and Depp at the peak of what their collaboration could produce.', null); # 304862 Sleepy Hollow 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (59578, 7, 'orimor25', 'Playing Wonka as damaged rather than whimsical was a braver and more interesting choice. The factory design is visually unlike anything else in the franchise.', null); # 59578 Charlie and the Chocolate Factory 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (97360, 7, 'orimor25', 'Ed Wood''s total belief in his own terrible films is what makes this work. Landau as Lugosi earned every award he received and then some.', null); # 97360 Ed Wood 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (149287, 7, 'orimor25', 'Hoffman and Williams are an underrated pairing. The Lost Boys sequence captures childhood adventure in a way that genuinely holds up.', null); # 149287 Hook 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (14477, 7, 'orimor25', 'Hopkins controls every courtroom scene and Hounsou brings real dignity to Cinque. An important story given the weight it deserves.', null); # 14477 Amistad 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215876, 7, 'orimor25', 'The Prague train heist and the opening mask sequence are great set pieces. De Palma knew exactly how to build and release tension.', null); # 215876 Mission: Impossible 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215880, 7, 'orimor25', 'Philip Seymour Hoffman as the villain is the best casting decision the franchise ever made. The film moves with real urgency around him.', null); # 215880 Mission: Impossible III 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (192702, 7, 'orimor25', 'Dalton made Bond genuinely dangerous again after years of Moore. The cello case snow chase is one of the best action sequences the franchise produced.', null); # 192702 Living Daylights, The 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312170, 7, 'orimor25', 'Nobody Does It Better is still the best Bond theme and the submarine opening is spectacular. A Moore entry that actually has real stakes.', null); # 312170 Spy Who Loved Me, The 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (240521, 7, 'orimor25', 'Lazenby was dismissed unfairly and Diana Rigg gave the story emotional weight most Bond entries never even attempt. The most un-Bond Bond film.', null); # 240521 On Her Majesty''s Secret Service 1969
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280281, 7, 'orimor25', 'Earns its training montage because you already care deeply about these characters. The rematch ending mirrors the original with real payoff.', null); # 280281 Rocky II 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280284, 7, 'orimor25', 'Drago works as a villain despite the Cold War propaganda being completely ridiculous. The mountain training sequence is an all-time sports film montage.', null); # 280284 Rocky IV 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311037, 7, 'orimor25', 'Raimi got Peter Parker''s teenage awkwardness genuinely right. The upside-down kiss became iconic almost immediately and for good reason.', null); # 311037 Spider-Man 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (142491, 7, 'orimor25', 'Perlman was born for this role. Del Toro gave the character real warmth that goes well beyond the red skin and the oversized fist.', null); # 142491 Hellboy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (142492, 7, 'orimor25', 'The Golden Army design is spectacular and Prince Nuada is a compelling antagonist. Del Toro leaned further into fairy-tale aesthetics and it suits the material.', null); # 142492 Hellboy 2 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210739, 7, 'orimor25', 'Smith and Jones have perfect deadpan chemistry. The worm alien at the pawnshop is one of the best alien comedy gags any film has ever landed.', null); # 210739 Men in Black 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (359297, 7, 'orimor25', 'Spielberg shot the invasion like a news event and that choice makes it far more frightening than a traditional blockbuster approach would have.', null); # 359297 War of the Worlds 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (328272, 7, 'orimor25', 'Hanks makes Viktor''s isolation funny and moving simultaneously. The airport set was built from scratch and you believe every inch of it.', null); # 328272 Terminal, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313477, 7, 'orimor25', 'Order 66 and McGregor''s cry at the end finally gave the saga the tragedy it was always supposed to have. Best prequel by a significant margin.', null); # 313477 Star Wars: Episode III - Revenge of the Sith 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188509, 7, 'orimor25', 'The South Africa backdrop gives it real political edge. Pesci''s Leo Getz is an inspired addition that nobody could have predicted from the first film.', null); # 188509 Lethal Weapon 2 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335835, 7, 'orimor25', 'Campy in all the right places and genuinely thrilling when it counts. The aerial photography holds up technically even now.', null); # 335835 Top Gun 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139657, 7, 'orimor25', 'Columbus got the tone exactly right on the first attempt. Diagon Alley and Hogwarts look precisely how they should and the three leads feel genuinely cast.', null); # 139657 Harry Potter and the Sorcerer''s Stone 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139652, 7, 'orimor25', 'The graveyard ending is the darkest the series ever goes and it earns every second of it. The Triwizard tournament gives the film real stakes for the first time.', null); # 139652 Harry Potter and the Goblet of Fire 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139654, 7, 'orimor25', 'Umbridge is the most hateable character in the entire series and that is a genuine achievement. The Ministry politics make this the most thematically interesting entry.', null); # 139654 Harry Potter and the Order of the Phoenix 2007
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139653, 7, 'orimor25', 'The cave sequence and Dumbledore''s death are the strongest dramatic moments in the film. The teen romance is its weakest element but does not derail it.', null); # 139653 Harry Potter and the Half-Blood Prince 2008
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (177369, 7, 'orimor25', 'De Niro as an obsessive fan is genuinely disturbing in a way that feels completely real. Scorsese shoots it as a dark comedy and the balance never tips either way.', null); # 177369 King of Comedy, The 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30967, 7, 'orimor25', 'Pfeiffer''s Catwoman is the definitive version of that character and it is not particularly close. Burton doubled down on the gothic and the material absorbed it completely.', null); # 30967 Batman Returns 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159175, 7, 'orimor25', 'The mine car chase and the opening with young Indy are genuinely inventive. Short Round is memorable despite some humour that has dated noticeably.', null); # 159175 Indiana Jones and the Temple of Doom 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30686, 7, 'orimor25', 'DiCaprio with more raw talent at that age than most actors show in a full career. The film never once romanticises the addiction and is far better for it.', null); # 30686 Basketball Diaries, The 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (32707, 7, 'orimor25', 'Bardem gives everything physically to Arenas. The Cuban political backdrop keeps it from being just a biography and gives the story genuine weight.', null); # 32707 Before Night Falls 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (34104, 7, 'orimor25', 'Depp and Masterson have a chemistry that feels completely unforced. A gentle and unusual film that treats its characters with real care throughout.', null); # 34104 Benny & Joon 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256839, 7, 'orimor25', 'Diesel made a character with almost no dialogue genuinely magnetic. The dark planet concept is clever and the alien design is completely original.', null); # 256839 Pitch Black 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (25192, 7, 'orimor25', 'Blanchett''s Hepburn is genuinely uncanny. DiCaprio sells the obsession without ever losing your sympathy, which is a harder balance than it looks.', null); # 25192 Aviator, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (34077, 7, 'orimor25', 'The concept is explored emotionally rather than as a visual gimmick. Blanchett anchors the film in a way that keeps it grounded when it could easily drift.', null); # 34077 Benjamin Button 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (113506, 7, 'orimor25', 'Depp as Barrie is warm without ever tipping into sentimentality. Winslet and the child actors are exceptional and the ending earns its emotion.', null); # 113506 Finding Neverland 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (291495, 7, 'orimor25', 'Murray riffing on A Christmas Carol with sadness underneath every joke. That combination gives it a staying power most straight comedies never achieve.', null); # 291495 Scrooged 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (190869, 7, 'orimor25', 'Lilo and Nani as struggling sisters is more emotionally honest than most Disney films of that era. Stitch works as a comedy character and an emotional anchor simultaneously.', null); # 190869 Lilo & Stitch 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (70959, 7, 'orimor25', 'Emily''s blue glow and the land of the dead colour scheme are genuinely beautiful. Burton found a stop-motion visual language that is completely his own.', null); # 70959 Corpse Bride, The 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (208245, 7, 'orimor25', 'Gibson is perfectly cast as a gambler who cannot help himself. Light and fun, Donner knew exactly what kind of film he was making and never overreached.', null); # 208245 Maverick 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (253010, 7, 'orimor25', 'Eastwood and Costner make a convincing unlikely pair. The Texas landscape breathes and the moral ambiguity at the end is left genuinely unresolved.', null); # 253010 Perfect World, A 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (90837, 7, 'orimor25', 'Three minutes long and already playing with time and memory. Points directly at what Nolan would do with Memento and impressive as a student work.', null); # 90837 Doodlebug 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (644, 7, 'orimor25', 'Witty and funny update of Taming of the Shrew. Ledger and Stiles had a chemistry the screenplay fully deserved and rarely gets credit for.', null); # 644 10 Things I Hate About You 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (240327, 7, 'orimor25', 'The slow build of dread in the first act works better than most modern horror. Peck''s confusion feels grounded and real throughout.', null); # 240327 Omen, The 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (259826, 7, 'orimor25', 'The closet and TV scenes defined suburban horror for a whole generation. Tobe Hooper directed and Spielberg produced and both fingerprints are all over it.', null); # 259826 Poltergeist 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (318388, 7, 'orimor25', 'One of Spielberg''s first theatrical features and already completely in command of suspense. The highway chase grips from start to finish.', null); # 318388 Sugarland Express, The 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (319602, 7, 'orimor25', 'Reeve made earnestness feel heroic rather than naive. The flying sequences over Metropolis set a standard the franchise has not matched since.', null); # 319602 Superman 1978
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (319613, 7, 'orimor25', 'The Phantom Zone villains gave the sequel genuine menace that the first film''s Lex Luthor never quite managed. The Metropolis battle is exactly the right scale.', null); # 319613 Superman II 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (230947, 7, 'orimor25', 'Scorsese''s Life Lessons with Nick Nolte is the standout, a short film punching well above its length. The anthology format works better here than most attempts.', null); # 230947 New York Stories 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (92573, 7, 'orimor25', 'The tarantula scene and the SPECTRE briefing room work because Connery makes you believe every second. The film that started it all and it still holds up.', null); # 92573 Dr. No 1962
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (33492, 7, 'orimor25', 'A quiet German film about a chef falling for someone. The food preparation scenes are sensuous and the emotional restraint makes the ending feel genuinely earned.', null); # 33492 Bella Martha 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56282, 7, 'orimor25', 'The time-stop sequences in the supermarket are inventive and visually distinctive. Takes its concept seriously and builds a film around it rather than just a gimmick.', null); # 56282 Cashback 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (20253, 7, 'orimor25', 'Kusturica brought Balkan surrealism into an American setting and somehow made it feel natural. Depp and Jerry Lewis together is an improbable combination that clicks.', null); # 20253 Arizona Dream 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (350189, 7, 'orimor25', 'The gothic European setting and the knight companion add real variety. A much stronger film than the original in every way that matters.', null); # 350189 Vampire Hunter D 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (74259, 7, 'orimor25', 'Waters using Depp to satirize 1950s greaser culture is exactly as entertaining as it sounds. Iggy Pop in a cameo is perfect casting without question.', null); # 74259 Cry-Baby 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (333856, 7, 'orimor25', 'Too iconic to rate lower. The engineering feat of filming on the ocean is real and the ending still lands even after all these years.', null); # 333856 Titanic 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (151616, 7, 'orimor25', 'Hudson and McConaughey are genuinely charming together and the dual-con premise is clever. A fun and rewatchable rom-com that never takes itself too seriously.', null); # 151616 How to Lose a Guy in 10 Days 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300230, 6, 'orimor25', 'Puss in Boots is a great addition. Slightly less original than the first but still delivers.', null); # 300230 Shrek 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (220276, 6, 'orimor25', 'The visual energy is real. Works better on repeat once you know when each song is coming.', null); # 220276 Moulin Rouge! 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (21213, 6, 'orimor25', 'Visually rich but loses focus in the second act. The robot boy at the frozen fairground at the end is genuinely moving and almost saves the whole thing.', null); # 21213 Artificial Intelligence: AI 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (66194, 6, 'orimor25', 'Silverstone''s Valley Girl performance carries the film further than the premise deserves. Sharp enough satire of high school hierarchies to stay worthwhile.', null); # 66194 Clueless 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280282, 6, 'orimor25', 'Mr T as Clubber Lang is entertaining and the beach training with Apollo is uplifting. A step down from the first two but not without its moments.', null); # 280282 Rocky III 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238073, 6, 'orimor25', 'Still enjoyable but loses the original''s elegant simplicity. The convoluted plotting feels deliberate rather than clever.', null); # 238073 Ocean''s Twelve 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256631, 6, 'orimor25', 'Davy Jones is a great creation and Nighy gives him real personality. The plot spins its wheels too long in the middle to fully work.', null); # 256631 Pirates of the Caribbean 2 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (69812, 6, 'orimor25', 'Gibson and Roberts in a paranoid thriller is an appealing premise. The resolution is a bit flat but the ride getting there is fun.', null); # 69812 Conspiracy Theory 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (41518, 6, 'orimor25', 'Depp is restrained in a way that suits the material. Covers too much ground to go deep anywhere but the period detail convinces throughout.', null); # 41518 Blow 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (350424, 6, 'orimor25', 'The open-ended grief concept is interesting and Cruise commits fully. The original is more unsettling but this version has its own qualities.', null); # 350424 Vanilla Sky 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (263360, 6, 'orimor25', 'Roberts and Gere have real chemistry and the film knows exactly what it is. Harmless and enjoyable even if the economic fantasy has aged awkwardly.', null); # 263360 Pretty Woman 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (62460, 6, 'orimor25', 'Warm performances throughout. Never fully commits to being a romance or a character study but Dench is excellent regardless.', null); # 62460 Chocolat 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (158999, 6, 'orimor25', 'The alien attack sequences are spectacular. The president-as-fighter-pilot speech is completely absurd and completely enjoyable because of it.', null); # 158999 Independence Day 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (247579, 6, 'orimor25', 'Fincher wrings real tension from a single contained location. Foster commits even when the premise tests credibility in the final act.', null); # 247579 Panic Room 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (47130, 6, 'orimor25', 'Cage fully inhabits a paramedic losing his grip and it is one of his more interesting choices. Underrated Scorsese, not warm but definitely distinctive.', null); # 47130 Bringing Out the Dead 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120506, 6, 'orimor25', 'The Victorian London atmosphere is very well built. The Ripper''s identity is a genuine surprise and the ending is darker than the film prepares you for.', null); # 120506 From Hell 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (118367, 6, 'orimor25', 'Uneven by design. Rodriguez and Tarantino''s segments are the clear highlights and the others are significantly below them.', null); # 118367 Four Rooms 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (233058, 6, 'orimor25', 'Langella makes the villain persuasive without overplaying it. Polanski builds dread carefully and never rushes toward the resolution.', null); # 233058 Ninth Gate, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (181766, 6, 'orimor25', 'The monastic pacing is completely intentional and the Tibetan landscape photography is breathtaking. Scorsese''s most meditative work by a wide margin.', null); # 181766 Kundun 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185704, 6, 'orimor25', 'Made with genuine reverence for the theological questions it raises. Braver than the controversy around it suggested and Keitel is unexpectedly strong.', null); # 185704 Last Temptation of Christ, The 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (109421, 6, 'orimor25', 'The street racing culture is presented with real specificity. The franchise lost its identity the moment it left those streets and never fully recovered.', null); # 109421 Fast and the Furious, The 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (189403, 6, 'orimor25', 'Dalton goes hardboiled and the drug cartel setting makes it feel like a different genre entirely. Not a bad thing, just a different Bond film.', null); # 189403 Licence to Kill 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (8183, 6, 'orimor25', 'Scorsese at his most restrained. Day-Lewis inhabits the period so completely it feels less like a film about the past and more like a time capsule.', null); # 8183 Age of Innocence, The 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (230963, 6, 'orimor25', 'Minnelli and De Niro clash with real electricity. The Depression-era music numbers are outstanding and the film is stronger than its current reputation.', null); # 230963 New York, New York 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30962, 6, 'orimor25', 'The Joker flashback reveal is darker than anything in the theatrical Batman films. Better than expected as a feature length story.', null); # 30962 Batman Beyond: The Movie 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30951, 6, 'orimor25', 'Victor Fries gets more nuanced writing here than in the theatrical film. A solid bridge that respects the animated series it comes from.', null); # 30951 Batman & Mr. Freeze: SubZero 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (308025, 6, 'orimor25', 'An underrated Ridley Scott thriller. Berenger and Rogers commit to an unusual and claustrophobic premise that most directors would have played much safer.', null); # 308025 Someone to Watch Over Me 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (257744, 6, 'orimor25', 'Genuine warmth throughout. Connery and Anderson make even the minor scenes feel worth watching.', null); # 257744 Playing by Heart 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (114955, 6, 'orimor25', 'Dillon is well cast and Garry Marshall knew exactly what kind of film he was making. Delivers cleanly on a modest but well-defined ambition.', null); # 114955 Flamingo Kid, The 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (235615, 6, 'orimor25', 'Hanks and Gleason as father and son is an unusual pairing that genuinely works. More honest about parental disappointment than most films from that decade.', null); # 235615 Nothing in Common 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (308057, 6, 'orimor25', 'Early Spielberg pulling more menace from a farmhouse than most directors manage with a much larger budget. A useful document of where the talent was heading.', null); # 308057 Something Evil 1972
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (231917, 6, 'orimor25', 'The Spielberg-directed segment shows his instinct for dread before his feature career had even started. Worth it for that segment alone.', null); # 231917 Night Gallery 1969
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312150, 6, 'orimor25', 'Rodriguez made a genuinely inventive family action film. The spy gadget creativity and the kids-as-heroes premise are executed with real energy.', null); # 312150 Spy Kids 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (85871, 5, 'orimor25', 'Connery is visibly disengaged and the Las Vegas setting feels garish. The MacGuffin logic is more confusing than clever.', null); # 85871 Diamonds Are Forever 1971
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (332065, 5, 'orimor25', 'The underwater sequences are impressive for the era but the film drags badly between them. Largo is a notably weak villain.', null); # 332065 Thunderball 1965
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (372233, 5, 'orimor25', 'Pure spectacle with a hollowed-out volcano lair. Blofeld is theatrical but the film prioritises sets over any real story.', null); # 372233 You Only Live Twice 1967
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (192514, 5, 'orimor25', 'Moore''s debut has Caribbean charm but the villain is too weak to anchor the film. The crocodile farm escape does not compensate.', null); # 192514 Live and Let Die 1973
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (354178, 5, 'orimor25', 'The car and ski chases are competent. Walken as Zorin is interesting casting wasted on a thin and underwritten role.', null); # 354178 View to a Kill, A 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335336, 5, 'orimor25', 'Slick but hollow compared to GoldenEye. The satellite weapon premise is weaker and the Teri Hatcher subplot leads nowhere.', null); # 335336 Tomorrow Never Dies 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (368418, 5, 'orimor25', 'Sophie Marceau is underused and Christmas Jones is a real casting disappointment. Falls well short of what it could have been.', null); # 368418 World Is Not Enough, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188510, 5, 'orimor25', 'The Gibson and Glover chemistry still works but the script does not support them. The toilet humour sits badly alongside the emotional beats.', null); # 188510 Lethal Weapon 3 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313474, 5, 'orimor25', 'The pod racing and Duel of the Fates are genuine highlights. Jar Jar and the trade dispute framing do not serve what the story is trying to be.', null); # 313474 Star Wars: Episode I - The Phantom Menace 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313476, 5, 'orimor25', 'The arena fight and Jango Fett work well. The Anakin and Padme romance on Naboo is the weakest element in the entire prequel trilogy.', null); # 313476 Star Wars: Episode II - Attack of the Clones 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (203649, 5, 'orimor25', 'Christopher Lee as a Bond villain sounds great and is surrounded by a mediocre film. The fun-house mirrors finale is at least inventive.', null); # 203649 Man with the Golden Gun, The 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (117314, 5, 'orimor25', 'Moore is likeable and Bouquet is a strong Bond woman. The mountain skiing sequence is the film''s one genuinely memorable contribution.', null); # 117314 For Your Eyes Only 1981
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215879, 5, 'orimor25', 'Woo''s direction is kinetic but the story underneath the stunts is hollow. The windmill fight is impressive, which is about the limit of what works.', null); # 215879 Mission: Impossible II 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280305, 5, 'orimor25', 'Rocky back on the streets was an interesting idea the film fails to execute. Tommy Gunn never generates the investment Creed or Drago did.', null); # 280305 Rocky V 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (14132, 5, 'orimor25', 'The gross-out humour settled into formula rather than anything fresh. Watchable but the novelty that made the first one work is completely gone.', null); # 14132 American Pie 2 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (283410, 5, 'orimor25', 'Roberts and Gere reunited without recovering what made Pretty Woman click. Pleasant and predictable from start to finish.', null); # 283410 Runaway Bride 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (200864, 5, 'orimor25', 'Lopez gives a genuinely committed performance in a thin template. The class-barrier story goes exactly where you expect from the opening scene.', null); # 200864 Maid in Manhattan 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (1038, 5, 'orimor25', 'Garner commits fully even when the script does not deserve it. Harmless body-swap fun that does not outstay its welcome.', null); # 1038 13 Going On 30 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159167, 5, 'orimor25', 'The crystal skull mythology does not belong in this world at all. The fridge scene says everything about where the franchise had arrived.', null); # 159167 Indiana Jones 4 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (245699, 5, 'orimor25', 'Hawn and Russell are charming together. The amnesia premise relies on ethics that have aged badly but the film itself stays good natured throughout.', null); # 245699 Overboard 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (370017, 5, 'orimor25', 'Diesel fills the screen with charisma even when the stunts are implausible. Knows exactly what it is and delivers on that narrow brief.', null); # 370017 XXX 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (292671, 5, 'orimor25', 'The alter ego concept is interesting and Depp commits to it. The King source material has been compressed too aggressively for the twist to land properly.', null); # 292671 Secret Window 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188511, 5, 'orimor25', 'The charm between Gibson and Glover is still there but the story has run out of ideas around them. Jet Li as the villain is a complete waste of his talent.', null); # 188511 Lethal Weapon 4 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (31715, 5, 'orimor25', 'Midler and Hershey are emotionally authentic together. Made for a specific audience and delivers for them without pretending to be more than it is.', null); # 31715 Beaches 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46878, 5, 'orimor25', 'The first film''s charm has settled into formula. Resolves exactly where you expect with no real surprises along the way.', null); # 46878 Bridget Jones: The Edge of Reason 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139650, 5, 'orimor25', 'Dobby is a memorable addition and the Basilisk reveal is handled well. The middle section drags more noticeably than the first film.', null); # 139650 Harry Potter and the Chamber of Secrets 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (340652, 5, 'orimor25', 'Impressive production design and cast. The characters get lost in the spectacle and the film never finds the emotional core it needs to work fully.', null); # 340652 Troy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (1121, 5, 'orimor25', 'Ambitious attempt to give Columbus real moral complexity. Scott''s visual instincts elevate what is otherwise a slow and uneven epic.', null); # 1121 1492: Conquest of Paradise 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (270628, 5, 'orimor25', 'The premise is painful and handled with more sentimentality than it deserves. The brotherly bond is touching even when the plot loses credibility.', null); # 270628 Radio Flyer 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (271344, 5, 'orimor25', 'Hudson carries the film on charm alone. The New York fashion world setting is decorative rather than something the story actually needs.', null); # 271344 Raising Helen 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (178994, 5, 'orimor25', 'Pepper and Diesel have real chemistry but the mobster-kids premise never goes anywhere interesting. A wasted opportunity with a good cast.', null); # 178994 Knockaround Guys 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10945, 5, 'orimor25', 'The ideas about faith and sacrifice are genuinely interesting. The production chaos shows in the uneven pacing and Fincher disowned it for understandable reasons.', null); # 10945 Alien 3 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (258948, 5, 'orimor25', 'Barrymore is an interesting choice for the manipulative teenager. The thriller elements work better than the romantic subplot surrounding them.', null); # 258948 Poison Ivy 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (1390, 5, 'orimor25', 'The ambition is there but the execution is too noisy to be funny consistently. The set pieces are spectacular in scale and empty in substance.', null); # 1390 1941 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312151, 5, 'orimor25', 'Bigger set pieces but the tight charm of the first film is gone. The island creatures are imaginative and the plot meanders around them.', null); # 312151 Spy Kids 2: Island of Lost Dreams 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (86263, 4, 'orimor25', 'The invisible car and the fencing match on ice are the low points of the entire franchise. Halle Berry is completely wasted from start to finish.', null); # 86263 Die Another Day 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311040, 6, 'orimor25', 'Three villains, not enough time for any of them. The Venom reveal is rushed and the film never recovers from the structural mess of the second act.', null); # 311040 Spider-Man 3 2007
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280306, 4, 'orimor25', 'A mislabelled entry in the database. The Rocky series had run well past its natural ending point long before reaching this.', null); # 280306 Rocky VI 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218808, 4, 'orimor25', 'The space station plot takes Bond so far from reality that any tension disappears. Jaws becoming a romantic sidekick is a decision that defies explanation.', null); # 218808 Moonraker 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (264157, 4, 'orimor25', 'Falls back on the exact same beats as the first film. The royal wedding setup deserved a more inventive script than this one provides.', null); # 264157 Princess Diaries 2: Royal Engagement 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (14157, 4, 'orimor25', 'Nostalgia is the only real draw and it runs dry very quickly. A reunion film with no genuine reason to exist beyond the reunion itself.', null); # 14157 American Reunion 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (105851, 4, 'orimor25', 'An extraordinary premise completely squandered. Every opportunity the concept creates is ignored in favour of something far less interesting.', null); # 105851 Exit to Eden 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312152, 4, 'orimor25', 'The 3D gimmick overwhelmed any remaining story. Stallone as the villain is self-aware but the film around him has genuinely nothing to say.', null); # 312152 Spy Kids 3-D: Game Over 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30952, 2, 'orimor25', 'Every single creative decision is wrong. The bat-credit card, the neon, the nipples on the suit. Unwatchable rather than entertainingly bad.', null); # 30952 Batman & Robin 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30965, 5, 'orimor25', 'Kilmer is a credible Bruce Wayne. The two-villain structure dilutes both Jones and Carrey and the film never settles on the tone it wants.', null); # 30965 Batman Forever 1995

	
