-- Personal Movie Rankings
-- GitHub: Tomer-Spector

insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (290070, 10, 'Tomer-Spector', 'Three hours and I didn''t check my phone once. Fiennes on the balcony is the scariest performance I''ve ever watched.', null); # 290070 Schindler''s List 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (297838, 9, 'Tomer-Spector', 'Rewatched this last month and still get hit by the tar-roof beer scene every single time. Don''t know any movie that earns its ending more cleanly.', null); # 297838 Shawshank Redemption, The 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (267038, 9, 'Tomer-Spector', 'I quote this thing constantly without meaning to. The Mia overdose scene still makes me sit forward in my chair.', null); # 267038 Pulp Fiction 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313478, 10, 'Tomer-Spector', 'Saw this before A New Hope and somehow it didn''t ruin anything. Hoth, Dagobah, Bespin in one movie and they all hit.', null); # 313478 Star Wars: Episode V - The Empire Strikes Back 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194500, 10, 'Tomer-Spector', 'I rewatch this every winter. The lighting of the beacons scene with Shore''s score is the moment I always come back for.', null); # 194500 Lord of the Rings: The Return of the King 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (112290, 9, 'Tomer-Spector', 'First watch I bought what it was selling. Second watch I realized that was the whole point. Pitt and Norton have ridiculous chemistry.', null); # 112290 Fight Club 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131780, 9, 'Tomer-Spector', 'Pesci genuinely scares me. Like I tense up every time he opens his mouth and Scorsese knows exactly how long to hold each scene to keep me there.', null); # 131780 Goodfellas 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (291698, 9, 'Tomer-Spector', 'The box. That''s it, the box. Twenty years later and I still won''t shut up about how perfect that ending is.', null); # 291698 Se7en 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194497, 10, 'Tomer-Spector', 'Probably my favorite stretch of cinema is everything from Bag End to Rivendell. Shore''s score does about half the storytelling and nobody complains.', null); # 194497 Lord of the Rings: The Fellowship of the Ring 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (271095, 8, 'Tomer-Spector', 'If I''m flipping through channels and this is on I stop. Every set piece is iconic and there''s not a slow scene in the whole thing.', null); # 271095 Raiders of the Lost Ark 1981
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194502, 10, 'Tomer-Spector', 'Helms Deep is the only battle in any film I''ve fully rewatched on YouTube without rewatching the whole movie. Bumping it over Fellowship just for that.', null); # 194502 Lord of the Rings: The Two Towers 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210511, 10, 'Tomer-Spector', 'Nolan''s whole career is in this one film and he was 30 years old. The reverse structure is the only way it could possibly work.', null); # 210511 Memento 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (165961, 8, 'Tomer-Spector', 'Holds up because the shark barely shows up. The Indianapolis speech is one of those things I''ll watch on loop sometimes.', null); # 165961 Jaws 1975
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (289109, 8, 'Tomer-Spector', 'Omaha Beach is a workout to sit through. The rest of the film is a steady decline from those twenty minutes but you forgive it.', null); # 289109 Saving Private Ryan 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (276217, 8, 'Tomer-Spector', 'Cannot believe this is a debut. Tarantino''s whole style is here already and the ear scene still makes me physically uncomfortable.', null); # 276217 Reservoir Dogs 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (326155, 8, 'Tomer-Spector', 'Travis Bickle made me uncomfortable in a way I didn''t expect. De Niro is so locked in it stops feeling like a performance.', null); # 326155 Taxi Driver 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10830, 8, 'Tomer-Spector', 'Slow burn that earns it. Knew the chestburster was coming and still flinched. The whole film is about waiting and dread.', null); # 10830 Alien 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10920, 10, 'Tomer-Spector', 'Cameron took a horror movie and made it a war movie and somehow improved it. Bumping it over the original because Hicks Hudson and Vasquez are the best ensemble in the franchise.', null); # 10920 Aliens 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (117874, 8, 'Tomer-Spector', 'Should be cheesy garbage. Isn''t. Hanks holds the whole forty-year arc together without breaking once.', null); # 117874 Forrest Gump 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (61751, 10, 'Tomer-Spector', 'The car ambush scene physically stresses me out every rewatch. Cuaron''s dystopia feels closer to reality every year and that''s a problem.', null); # 61751 Children of Men, The 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30959, 8, 'Tomer-Spector', 'First time a superhero movie made me forget it was a superhero movie. The League of Shadows training stretch is better than most full action films.', null); # 30959 Batman Begins 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159172, 9, 'Tomer-Spector', 'Connery and Ford bickering is the whole movie and that''s why it works. Best Indy by a clear margin.', null); # 159172 Indiana Jones and the Last Crusade 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313479, 8, 'Tomer-Spector', 'Endor drags. Throne room is a top-three sequence in the entire franchise. Net positive.', null); # 313479 Star Wars: Episode VI - Return of the Jedi 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159175, 8, 'Tomer-Spector', 'Darker than I remembered when I rewatched. Mine cart chase is still one of the best practical sequences out there.', null); # 159175 Indiana Jones and the Temple of Doom 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218219, 8, 'Tomer-Spector', 'Watched this expecting standard Miyazaki and got something much heavier. Ashitaka might be the most quiet protagonist in any animated film I''ve seen.', null); # 218219 Mononoke-hime 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176711, 9, 'Tomer-Spector', 'House of Blue Leaves fight is choreographed better than everything in the genre that decade. Pure stylized revenge done right.', null); # 176711 Kill Bill: Vol. 1 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (270971, 7, 'Tomer-Spector', 'Heavy and exhausting in the way it''s supposed to be. De Niro doesn''t ask you to like Jake which is why it works.', null); # 270971 Raging Bull 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (96593, 7, 'Tomer-Spector', 'Holds up because it takes the kid perspective completely seriously. Bike-flying scene is famous because it earns every second.', null); # 96593 E.T. the Extra-Terrestrial 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (129185, 8, 'Tomer-Spector', 'Russell Crowe in this movie is the kind of performance you build a film around. Opening battle and the arena finale are the bookends.', null); # 129185 Gladiator 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (123435, 8, 'Tomer-Spector', 'Fincher messing with you for two hours and never letting you settle. Douglas was perfectly cast.', null); # 123435 Game, The 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313477, 8, 'Tomer-Spector', 'Best prequel by a clear margin. The Anakin Obi-Wan duel is the only emotional payoff the trilogy actually earned.', null); # 313477 Star Wars: Episode III - Revenge of the Sith 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176712, 8, 'Tomer-Spector', 'Way slower than Vol 1 and that''s the right call. Pai Mei training and the Bill confrontation are the conversations the first film didn''t have time for.', null); # 176712 Kill Bill: Vol. 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256632, 9, 'Tomer-Spector', 'Depp as Jack Sparrow was an actual creative swing and it worked. Best in the franchise and nothing else comes close.', null); # 256632 Pirates of the Caribbean: The Curse of the Black Pearl 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311038, 9, 'Tomer-Spector', 'Doc Ock train fight is one of my favorite action set pieces ever. Raimi was clearly not embarrassed to be making a comic book movie and that''s why it hits.', null); # 311038 Spider-Man 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256631, 7, 'Tomer-Spector', 'Davy Jones is one of the best CG villains anyone ever rendered. Story doesn''t matter and the kraken is genuinely scary.', null); # 256631 Pirates of the Caribbean 2 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215879, 6, 'Tomer-Spector', 'Dumber than the first and third by a wide margin. Woo style with motorcycles and slow-mo doves and I''m here for it.', null); # 215879 Mission: Impossible II 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215880, 8, 'Tomer-Spector', 'Hoffman as the villain is what makes this work. Vatican break-in is one of Cruise''s best.', null); # 215880 Mission: Impossible III 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215876, 8, 'Tomer-Spector', 'Vault scene has been parodied so much I forgot how tense it is. De Palma''s paranoid spy movie hidden inside a Cruise vehicle.', null); # 215876 Mission: Impossible 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (220276, 8, 'Tomer-Spector', 'Baz turned everything to eleven and McGregor and Kidman went with it. That''s why the emotional stuff actually lands.', null); # 220276 Moulin Rouge! 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (340652, 6, 'Tomer-Spector', 'Bana as Hector is genuinely great. Pitt is fine. Supporting cast carries the whole thing.', null); # 340652 Troy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313474, 6, 'Tomer-Spector', 'Pod race and Darth Maul. That''s the whole pitch and that''s what I rewatch for.', null); # 313474 Star Wars: Episode I - The Phantom Menace 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313476, 7, 'Tomer-Spector', 'Geonosis arena and Yoda fighting carried the entire film for me as a kid. Romance subplot is the worst thing in any Star Wars movie.', null); # 313476 Star Wars: Episode II - Attack of the Clones 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300229, 9, 'Tomer-Spector', 'Eddie Murphy as Donkey is the best voice performance in any animated film I''ve watched. The fairy-tale parody had real bite when it dropped.', null); # 300229 Shrek 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300230, 7, 'Tomer-Spector', 'Puss in Boots in the cat eyes scene is the actual reason I rate this so high. Fairy Godmother song is a banger and I won''t apologize for it.', null); # 300230 Shrek 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188507, 7, 'Tomer-Spector', 'Riggs and Murtaugh is the template every buddy cop movie is still trying to hit. Gibson here is the most charismatic he ever was.', null); # 188507 Lethal Weapon 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188509, 8, 'Tomer-Spector', 'Pesci joining was the perfect chaotic add. South African villains date it badly but the chemistry covers most of it.', null); # 188509 Lethal Weapon 2 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (319602, 9, 'Tomer-Spector', 'Reeve made me believe a man could fly through pure earnestness. Slow first half is way better than most superhero film climaxes.', null); # 319602 Superman 1978
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (319613, 8, 'Tomer-Spector', 'Kneel before Zod is the line every villain still tries to land. Metropolis fight is still influencing how superhero scenes get blocked.', null); # 319613 Superman II 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (164572, 9, 'Tomer-Spector', 'Tarantino''s most patient film and the only one where he lets characters just exist. Grier and Forster have the quietest devastating chemistry I''ve watched.', null); # 164572 Jackie Brown 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210739, 8, 'Tomer-Spector', 'Will Smith at peak Will Smith and Tommy Lee Jones as the perfect straight man. Aged way better than most 90s blockbusters.', null); # 210739 Men in Black 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (54209, 7, 'Tomer-Spector', 'De Niro as Cady is one of the scariest performances of his whole career. Scorsese remaking a thriller and turning it into something operatic.', null); # 54209 Cape Fear 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (200521, 6, 'Tomer-Spector', 'Three hours of overlapping LA misery that should not work. Cruise''s monologue alone justifies the runtime.', null); # 200521 Magnolia 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130953, 9, 'Tomer-Spector', 'The Bond film every other Bond keeps trying to be. Oddjob and the laser scene are franchise-defining.', null); # 130953 Goldfinger 1964
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120574, 7, 'Tomer-Spector', 'Quieter and more grounded than later Bond. Train fight with Shaw is some of the best close-quarters action of the 60s.', null); # 120574 From Russia with Love 1963
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (92573, 6, 'Tomer-Spector', 'The Bond template that had no business launching sixty years of sequels. Andress walking out of the sea is the franchise''s defining image.', null); # 92573 Dr. No 1962
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (158999, 9, 'Tomer-Spector', 'Smith and Pullman owning the screen on either end. The White House blowing up is still the most satisfying VFX shot ever rendered.', null); # 158999 Independence Day 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (123849, 7, 'Tomer-Spector', 'Day-Lewis as Bill the Butcher is one of the all-time villain performances. Plot wanders, his scenes don''t.', null); # 123849 Gangs of New York 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139655, 9, 'Tomer-Spector', 'Cuaron took the franchise away from kid stuff and gave it actual identity. Patronus scene at the lake is one of the most beautiful things in the series.', null); # 139655 Harry Potter and the Prisoner of Azkaban 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139653, 8, 'Tomer-Spector', 'Slow burn that finally pays off the Snape arc. The cave is the first time Potter felt genuinely scary.', null); # 139653 Harry Potter and the Half-Blood Prince 2008
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139654, 8, 'Tomer-Spector', 'Umbridge is the most punchable villain in the franchise and Staunton nails it. Ministry battle is the best set piece in any Potter film.', null); # 139654 Harry Potter and the Order of the Phoenix 2007
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (65811, 7, 'Tomer-Spector', 'Mashed potatoes scene is a better character moment than most films pull off in two hours. Spielberg before he learned to make crowd-pleasers.', null); # 65811 Close Encounters of the Third Kind 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (47130, 7, 'Tomer-Spector', 'Scorsese and Cage as a burnt-out paramedic should have been a bigger deal. Closest Cage came to a quiet performance in this era.', null); # 47130 Bringing Out the Dead 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (94741, 7, 'Tomer-Spector', 'Spielberg before he was Spielberg. A truck and a car for ninety minutes and somehow you can''t look away.', null); # 94741 Duel 1971
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (192514, 6, 'Tomer-Spector', 'Moore''s first Bond and the most unhinged the franchise ever got. Voodoo, alligators, blaxploitation — completely tonal mess and I love it.', null); # 192514 Live and Let Die 1973
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159665, 7, 'Tomer-Spector', 'Not the Tarantino one. The Italian original. Rough but the cast chemistry is real.', null); # 159665 Inglorious Bastards 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (291495, 6, 'Tomer-Spector', 'Murray doing his cynical thing in a Christmas Carol setup. Exactly as good as that sounds.', null); # 291495 Scrooged 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (118367, 5, 'Tomer-Spector', 'Anthology that lives or dies on the Tarantino and Rodriguez segments. Roth as the bellhop holding it together is the unsung hero.', null); # 118367 Four Rooms 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139657, 8, 'Tomer-Spector', 'Solid opener that mostly just had to introduce Hogwarts and got the casting right. Quidditch scenes look rough now but the wonder hits.', null); # 139657 Harry Potter and the Sorcerer''s Stone 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139650, 6, 'Tomer-Spector', 'Dobby works better than I expected and the Basilisk reveal is well handled. Middle drags hard.', null); # 139650 Harry Potter and the Chamber of Secrets 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139652, 8, 'Tomer-Spector', 'The three tasks are excellent and the graveyard scene is when the franchise turned dark for real. Cuts too much from the book though.', null); # 139652 Harry Potter and the Goblet of Fire 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (149287, 8, 'Tomer-Spector', 'Williams as adult Peter Pan should not work and mostly does. Hoffman as Hook is the right level of ridiculous.', null); # 149287 Hook 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335835, 8, 'Tomer-Spector', 'Volleyball, sunglasses, Maverick. Plot doesn''t exist and the vibes are immortal.', null); # 335835 Top Gun 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (333856, 6, 'Tomer-Spector', 'Cameron made a three-hour love story and somehow made the sinking feel longer. DiCaprio and Winslet do the heavy lifting.', null); # 333856 Titanic 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130945, 9, 'Tomer-Spector', 'Brosnan''s first Bond and the franchise needed exactly this reset. Bean and Janssen are the right kind of over-the-top.', null); # 130945 GoldenEye 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185628, 8, 'Tomer-Spector', 'Beautifully shot and the choreography is excellent. The white-savior structure is what it is — the film knows.', null); # 185628 Last Samurai, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (332065, 6, 'Tomer-Spector', 'Underwater action hasn''t aged well but the rest holds up. Connery cruising on autopilot.', null); # 332065 Thunderball 1965
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (372233, 6, 'Tomer-Spector', 'Volcano lair is one of the most iconic Bond sets ever built. Story is paper thin.', null); # 372233 You Only Live Twice 1967
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (240521, 8, 'Tomer-Spector', 'Lazenby gets unfair criticism. The film around him is one of the more grounded Bonds and the ending genuinely lands.', null); # 240521 On Her Majesty''s Secret Service 1969
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (354178, 6, 'Tomer-Spector', 'Walken having a great time and Grace Jones owning every scene. Moore is too old by this point and the film is aware.', null); # 354178 View to a Kill, A 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (192702, 8, 'Tomer-Spector', 'Dalton brought a colder more book-accurate Bond. The cello case sled chase is one of the better mid-tier set pieces.', null); # 192702 Living Daylights, The 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (203649, 6, 'Tomer-Spector', 'Christopher Lee elevates every scene he''s in. Hong Kong middle drags and the film never recovers.', null); # 203649 Man with the Golden Gun, The 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335336, 6, 'Tomer-Spector', 'Pryce as a media-mogul villain was ahead of its time. BMW motorcycle chase is one of the better 90s action sequences.', null); # 335336 Tomorrow Never Dies 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (368418, 6, 'Tomer-Spector', 'Marceau is the most interesting Bond villain in years. Denise Richards as a nuclear physicist defines an era of bad casting.', null); # 368418 World Is Not Enough, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (189403, 7, 'Tomer-Spector', 'Dalton''s revenge Bond goes harder than I expected. Davi is a properly nasty villain.', null); # 189403 Licence to Kill 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (109421, 8, 'Tomer-Spector', 'The whole franchise started here and it''s still about cars and family. Walker and Diesel have the chemistry that built a fifteen-film universe.', null); # 109421 Fast and the Furious, The 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (220805, 7, 'Tomer-Spector', 'Pitt and Jolie chemistry is undeniable and the film knows it. Gets sillier as it goes and you don''t really care.', null); # 220805 Mr. and Mrs. Smith 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238072, 9, 'Tomer-Spector', 'Eleven movie stars in suits riffing for two hours and somehow it works. Soderbergh keeps the heist moving and lets the cast carry the rest.', null); # 238072 Ocean''s Eleven 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238073, 7, 'Tomer-Spector', 'The Julia Roberts gag is either the funniest or worst thing in the film depending on your mood. Less tight than the first.', null); # 238073 Ocean''s Twelve 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (142491, 8, 'Tomer-Spector', 'Perlman is perfect casting and del Toro''s monster designs are always the best part. Story is generic, atmosphere isn''t.', null); # 142491 Hellboy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (142492, 8, 'Tomer-Spector', 'Visually more confident than the first and the troll market is one of del Toro''s best world-building scenes.', null); # 142492 Hellboy 2 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (190869, 8, 'Tomer-Spector', 'Disney made a film about Hawaiian family dynamics that actually feels lived in. Stitch is better designed than most major animated leads.', null); # 190869 Lilo & Stitch 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (66194, 7, 'Tomer-Spector', 'Writing is sharper than the bubble-gum aesthetic suggests. Silverstone is genuinely great in a role that could have been forgettable.', null); # 66194 Clueless 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (97727, 7, 'Tomer-Spector', 'Burton at his most heartfelt before he became a brand. Depp sells the whole emotion through posture alone.', null); # 97727 Edward Scissorhands 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (70959, 6, 'Tomer-Spector', 'Beautifully animated and quietly sad in the way Burton used to do reliably. Story is thin, the design carries it.', null); # 70959 Corpse Bride, The 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (59578, 6, 'Tomer-Spector', 'Burton remake that works because of the production design. Depp''s Wonka is divisive and probably the weakest part.', null); # 59578 Charlie and the Chocolate Factory 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56871, 8, 'Tomer-Spector', 'Spielberg in light mode and DiCaprio at his most charming. Hanks as the FBI agent is the steady anchor.', null); # 56871 Catch Me If You Can 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (113506, 6, 'Tomer-Spector', 'Depp doing restrained dramatic work which he doesn''t do often enough. Winslet brings the emotional weight as always.', null); # 113506 Finding Neverland 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (62460, 7, 'Tomer-Spector', 'Binoche and Depp at their most charming. Light fable that knows what it is and commits.', null); # 62460 Chocolat 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (160524, 8, 'Tomer-Spector', 'Pacino and Williams playing against type, both effective. Nolan''s most underrated early film.', null); # 160524 Insomnia 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (214755, 7, 'Tomer-Spector', 'Pre-crime concept is interesting and the chases are kinetic. Third act unwinds the mystery in a less satisfying way.', null); # 214755 Minority Report 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256839, 6, 'Tomer-Spector', 'Diesel as Riddick was a star-making turn. Tight contained sci-fi horror before the franchise got bloated.', null); # 256839 Pitch Black 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (350189, 6, 'Tomer-Spector', 'Stylish anime that doesn''t get talked about enough. Animation has held up better than most films from that era.', null); # 350189 Vampire Hunter D 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (350424, 7, 'Tomer-Spector', 'Cruise doing experimental and mostly pulling it off. Glossier remake of Open Your Eyes that still works.', null); # 350424 Vanilla Sky 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (359297, 8, 'Tomer-Spector', 'First half is some of Spielberg''s most intense disaster filmmaking. Robbins basement sequence drops the energy hard.', null); # 359297 War of the Worlds 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (174953, 7, 'Tomer-Spector', 'Early Miyazaki and every theme he''d develop later is already here. World-building is dense and pays off if you''re patient.', null); # 174953 Kaze no tani no Naushika 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (370017, 6, 'Tomer-Spector', 'Diesel doing his thing in a Bond parody that takes itself too seriously to be funny. Snowboarding avalanche is genuinely impressive.', null); # 370017 XXX 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (247579, 7, 'Tomer-Spector', 'Fincher in a contained setting and you can feel him restless. Whitaker as the conflicted villain is the most interesting character.', null); # 247579 Panic Room 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (200864, 6, 'Tomer-Spector', 'Romcom with standard beats at standard times. JLo and Fiennes have just enough chemistry to make it work.', null); # 200864 Maid in Manhattan 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (151616, 6, 'Tomer-Spector', 'Hudson and McConaughey are the rare romcom pair where you actually buy the chemistry. Dumb premise the film commits to.', null); # 151616 How to Lose a Guy in 10 Days 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (306032, 9, 'Tomer-Spector', 'Pitt''s Mickey is one of the most quotable supporting characters of the decade. Ritchie at peak Ritchie before the formula went stale.', null); # 306032 Snatch 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (208245, 6, 'Tomer-Spector', 'Gibson and Foster on a riverboat being charming for two hours. The kind of mid-budget star vehicle they don''t make anymore.', null); # 208245 Maverick 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (177369, 8, 'Tomer-Spector', 'De Niro and Lewis doing uncomfortable comedy decades before that became fashionable. Scorsese''s weirdest mainstream film.', null); # 177369 King of Comedy, The 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (97360, 8, 'Tomer-Spector', 'Depp and Burton''s best collaboration. Landau as Bela Lugosi is one of the most touching supporting performances of the 90s.', null); # 97360 Ed Wood 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (304862, 8, 'Tomer-Spector', 'Burton''s gothic look at peak before it became self-parody. Walken as the Headless Horseman is genuinely menacing.', null); # 304862 Sleepy Hollow 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312150, 7, 'Tomer-Spector', 'Surprisingly creative kids action movie. Rodriguez clearly had fun and the gadgets are inventive.', null); # 312150 Spy Kids 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (34077, 8, 'Tomer-Spector', 'Concept is more interesting than the execution but Pitt and Blanchett are reliably great. Fincher fighting his own instincts.', null); # 34077 Benjamin Button 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30955, 9, 'Tomer-Spector', 'Keaton is a better Batman than people remember and Nicholson''s Joker defined the character for a whole generation. Burton''s Gotham is iconic.', null); # 30955 Batman 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280270, 8, 'Tomer-Spector', 'The original underdog story everyone has copied since. Stallone''s screenplay is way better than people give him credit for.', null); # 280270 Rocky 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311037, 8, 'Tomer-Spector', 'Maguire wasn''t the cool choice and that''s why it worked. Green Goblin is the weakest part.', null); # 311037 Spider-Man 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312170, 8, 'Tomer-Spector', 'Roger Moore''s best Bond. Submarine car and Jaws''s debut are franchise highlights.', null); # 312170 Spy Who Loved Me, The 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (117314, 6, 'Tomer-Spector', 'Moore''s most grounded Bond after the Moonraker disaster. Reasonable mid-tier entry that course-corrected the franchise.', null); # 117314 For Your Eyes Only 1981
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (74259, 5, 'Tomer-Spector', 'Waters at his most accessible which makes it less interesting than his earlier work. Depp commits with the right amount of self-aware ridiculousness.', null); # 74259 Cry-Baby 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (1038, 6, 'Tomer-Spector', 'Garner is charming and the Thriller dance is iconic. Film around it is paint-by-numbers.', null); # 1038 13 Going On 30 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (245699, 4, 'Tomer-Spector', 'Hawn and Russell have chemistry but the premise has aged into something I''m not comfortable with. Charm covers some of it.', null); # 245699 Overboard 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (644, 8, 'Tomer-Spector', 'Updated Shakespeare with Ledger at his most charming. Stiles is the better performance even if she gets less credit.', null); # 644 10 Things I Hate About You 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (114955, 5, 'Tomer-Spector', 'Dillon at his most charismatic. Coming of age that''s competent without ever surprising me.', null); # 114955 Flamingo Kid, The 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131885, 7, 'Tomer-Spector', 'Nostalgic for people who saw it as kids. Sloth and the pirate ship are the parts everyone remembers.', null); # 131885 Goonies, The 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (240327, 6, 'Tomer-Spector', 'Slower than modern horror but the score and slow build still work. The decapitation scene is one of the more iconic shocks of the era.', null); # 240327 Omen, The 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (259826, 6, 'Tomer-Spector', 'Hooper and Spielberg fighting for credit and you can see both. TV scene still works as suburban horror.', null); # 259826 Poltergeist 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (32707, 6, 'Tomer-Spector', 'Bardem makes the film. Schnabel''s painterly direction can be slow if you''re not in the mood.', null); # 32707 Before Night Falls 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (233058, 5, 'Tomer-Spector', 'Polanski and Depp doing slow occult detective work. Atmosphere is great, ending is famously confused.', null); # 233058 Ninth Gate, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (270628, 4, 'Tomer-Spector', 'Premise is heavy and the film leans into sentiment too hard. Real emotion in the brotherly bond carries it past where the script gives up.', null); # 270628 Radio Flyer 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (283410, 4, 'Tomer-Spector', 'Gere and Roberts reunion that doesn''t recapture Pretty Woman magic. Coasts on the leads'' charm.', null); # 283410 Runaway Bride 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (258948, 4, 'Tomer-Spector', 'Barrymore as the manipulator works in unsettling ways. Thriller mechanics around her less interesting than her performance.', null); # 258948 Poison Ivy 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (292671, 6, 'Tomer-Spector', 'Depp committing to a King short story that didn''t have enough material. Twist is the kind you see coming half an hour out.', null); # 292671 Secret Window 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (257744, 5, 'Tomer-Spector', 'Ensemble drama with a stacked cast that doesn''t fully cohere. Nielsen and Connery have the most interesting subplot.', null); # 257744 Playing by Heart 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (253010, 6, 'Tomer-Spector', 'Costner doing his best understated work and Eastwood directing without flash. Slow but earns the payoff.', null); # 253010 Perfect World, A 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188510, 6, 'Tomer-Spector', 'Russo joining the cast gave it a needed shake-up. Starting to feel formulaic at this point.', null); # 188510 Lethal Weapon 3 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46878, 4, 'Tomer-Spector', 'Sequel that hits the same beats less effectively. Zellweger is still committed even with thinner material.', null); # 46878 Bridget Jones: The Edge of Reason 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (41518, 7, 'Tomer-Spector', 'Depp as a coke smuggler in a fairly standard rise and fall structure. The 70s aesthetic is well done.', null); # 41518 Blow 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159167, 4, 'Tomer-Spector', 'The fridge scene is the moment the franchise crossed a line I can''t come back from. LaBeouf is fine, writing isn''t.', null); # 159167 Indiana Jones 4 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (1390, 4, 'Tomer-Spector', 'Spielberg''s only major flop and I see exactly why. Too loud, too long, not funny enough for the runtime.', null); # 1390 1941 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (1121, 6, 'Tomer-Spector', 'Vangelis score and Scott visuals doing all the heavy lifting. Story drags and Depardieu is miscast.', null); # 1121 1492: Conquest of Paradise 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (271344, 6, 'Tomer-Spector', 'Hudson on autopilot in a film that does nothing with its premise. Supporting cast can''t save it.', null); # 271344 Raising Helen 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10945, 6, 'Tomer-Spector', 'Fincher''s debut where you can see what he became fighting what the studio wanted. Disowned by him for understandable reasons.', null); # 10945 Alien 3 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (264157, 5, 'Tomer-Spector', 'Hathaway is charming as always and the film around her is empty. The first one didn''t need a sequel.', null); # 264157 Princess Diaries 2: Royal Engagement 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (14157, 5, 'Tomer-Spector', 'Cast reunion that exists for nostalgia and not much else. Premise has run out of road and the film knows it.', null); # 14157 American Reunion 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312151, 6, 'Tomer-Spector', 'Rodriguez piling on imagination without anchoring it to a story. Bigger doesn''t mean better.', null); # 312151 Spy Kids 2: Island of Lost Dreams 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30951, 5, 'Tomer-Spector', 'Direct-to-video animated Batman that''s competent at best. The TV series episodes are stronger.', null); # 30951 Batman & Mr. Freeze: SubZero 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30962, 5, 'Tomer-Spector', 'Compilation of TV episodes presented as a movie. Not really a film.', null); # 30962 Batman Beyond: The Movie 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30967, 4, 'Tomer-Spector', 'Burton at his most Burton-y and the film suffers. Walken and Pfeiffer are the only reasons to revisit.', null); # 30967 Batman Returns 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30976, 7, 'Tomer-Spector', 'Animated Batman film with surprisingly mature themes. Aged better than several live-action entries.', null); # 30976 Batman: Mask of the Phantasm 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30965, 4, 'Tomer-Spector', 'Kilmer is fine but the film around him is a cartoon. Carrey and Tommy Lee Jones competing for the same energy.', null); # 30965 Batman Forever 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (31715, 4, 'Tomer-Spector', 'Midler and Hershey are fine. Exactly what it advertises and not a frame more.', null); # 31715 Beaches 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (263360, 5, 'Tomer-Spector', 'Iconic for the wrong reasons. Roberts and Gere are charming but the premise is rougher in retrospect.', null); # 263360 Pretty Woman 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (336445, 4, 'Tomer-Spector', 'DiCaprio doing arthouse before he was a star. Interesting performance, exhausting movie.', null); # 336445 Total Eclipse 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30686, 6, 'Tomer-Spector', 'DiCaprio committing to a role nobody else his age could have played. Film around the performance is less interesting.', null); # 30686 Basketball Diaries, The 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (20253, 6, 'Tomer-Spector', 'Kusturica''s American film with Depp and Dunaway. Surreal in a way that''s either fascinating or exhausting depending on mood.', null); # 20253 Arizona Dream 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (21213, 5, 'Tomer-Spector', 'Spielberg finishing Kubrick''s project and the seams show. The flesh fair is one of the bleakest things either director ever made.', null); # 21213 Artificial Intelligence: AI 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120506, 5, 'Tomer-Spector', 'Depp doing Jack the Ripper. Hughes brothers visual style covers a thin mystery.', null); # 120506 From Hell 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215875, 5, 'Tomer-Spector', 'The TV movie pilot before the franchise restart. Curiosity more than entertainment.', null); # 215875 Mission: Impossible 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (328272, 6, 'Tomer-Spector', 'Hanks doing accent work and Spielberg keeping it gentle. Lower-tier Spielberg but watchable.', null); # 328272 Terminal, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (330670, 7, 'Tomer-Spector', 'DiCaprio''s breakthrough opposite De Niro. The film around them is competent and the leads make it more.', null); # 330670 This Boy''s Life 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (34104, 6, 'Tomer-Spector', 'Depp doing Buster Keaton tribute is the highlight. Whimsical to a fault.', null); # 34104 Benny & Joon 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218808, 3, 'Tomer-Spector', 'Bond in space is exactly as bad as it sounds. Jaws becoming a romantic sidekick is one of the worst creative choices in the franchise.', null); # 218808 Moonraker 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (86263, 3, 'Tomer-Spector', 'Invisible car. Surfing CGI tsunami. Berry''s dialogue. The franchise needed Daniel Craig after this and quickly.', null); # 86263 Die Another Day 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280305, 4, 'Tomer-Spector', 'Stallone trying to course-correct after IV and overshooting the other way. Morrison as the protege never works.', null); # 280305 Rocky V 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280282, 5, 'Tomer-Spector', 'Mr. T is iconic and the film around him is silly. Eye of the Tiger is the most enduring contribution.', null); # 280282 Rocky III 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280284, 5, 'Tomer-Spector', 'Pure 80s Cold War cartoon. Drago is a cardboard cutout and the training montage is the only thing anyone remembers.', null); # 280284 Rocky IV 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280281, 6, 'Tomer-Spector', 'Rematch movie that exists because the first one made money. None of the underdog charm survives the sequel structure.', null); # 280281 Rocky II 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280306, 3, 'Tomer-Spector', 'Database curiosity. Rocky IV mislabeled probably. Not its own film.', null); # 280306 Rocky VI 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188511, 3, 'Tomer-Spector', 'Jet Li wasted as a silent villain. Gibson Glover chemistry is still there but the franchise had nothing left.', null); # 188511 Lethal Weapon 4 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (85871, 3, 'Tomer-Spector', 'Connery''s reluctant return and you can tell he''s coasting. Vegas setting and Blofeld plot barely keep it watchable.', null); # 85871 Diamonds Are Forever 1971
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312152, 3, 'Tomer-Spector', 'Stallone showing up doesn''t save a film that''s a tech demo for terrible 3D. Genuinely a chore.', null); # 312152 Spy Kids 3-D: Game Over 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30952, 3, 'Tomer-Spector', 'The bat-credit card. The nipples on the suit. The ice puns. Complete creative collapse start to finish.', null); # 30952 Batman & Robin 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30957, 4, 'Tomer-Spector', 'Old serial that has historical value only. Not really watchable as entertainment today.', null); # 30957 Batman and Robin 1949
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (40199, 9, 'Tomer-Spector', 'Watched this expecting old slow sci-fi and got the visual language every film since has copied. Hauer''s Tears in the Rain is the kind of monologue that gets quoted forever for a reason.', null); # 40199 Blade Runner 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (39551, 8, 'Tomer-Spector', 'Scott directing combat as controlled chaos. The Mogadishu sequences feel closer to documentary than to anything choreographed.', null); # 39551 Black Hawk Down 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256627, 8, 'Tomer-Spector', 'Watched this because of my own tech interests. Noah Wyle as Jobs and Anthony Michael Hall as Gates is somehow perfect casting and neither company comes out the hero.', null); # 256627 Pirates of Silicon Valley 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (39829, 7, 'Tomer-Spector', 'Scott and Michael Douglas in Osaka is the kind of stylish thriller they stopped making. The neon and rain does most of the storytelling.', null); # 39829 Black Rain 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (113459, 7, 'Tomer-Spector', 'Lumet doing a courtroom procedural in his sleep is still better than most directors awake. Diesel''s one genuinely good dramatic performance.', null); # 113459 Find Me Guilty 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (22651, 5, 'Tomer-Spector', 'Depp and Theron in a paranoid sci-fi thriller that mostly works on atmosphere. Wants to be Rosemary''s Baby in space and doesn''t quite get there.', null); # 22651 Astronaut''s Wife, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (12744, 6, 'Tomer-Spector', 'Spielberg doing romantic fantasy with Hunter and Dreyfuss. Minor in his filmography and softer than anything else he made that decade.', null); # 12744 Always 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (244421, 6, 'Tomer-Spector', 'Garry Marshall sentimentality with Keaton and Lewis. The kind of comfort watch you put on during a rainy afternoon and don''t think about again.', null); # 244421 Other Sister, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (183873, 8, 'Tomer-Spector', 'Hauer and Pfeiffer cursed to never meet in the same form. The 80s synth score is divisive but the rest is pure fantasy charm.', null); # 183873 Ladyhawke 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (372733, 7, 'Tomer-Spector', 'Spielberg produced and Levinson directed and the result is a fun teen deduction adventure. Stained-glass knight is one of the first proper CG character composites.', null); # 372733 Young Sherlock Holmes 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (116358, 6, 'Tomer-Spector', 'Macy doing his quiet desperation thing in a McGuffin-driven post-war drama. Arthur Miller source material gives it more weight than the marketing suggested.', null); # 116358 Focus 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (118980, 6, 'Tomer-Spector', 'Pacino and Pfeiffer playing against type as a short-order cook and a waitress. Small stakes done with real craft.', null); # 118980 Frankie and Johnny 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (251234, 5, 'Tomer-Spector', 'Pre-Gibson revenge film with the same source novel. Watchable but the Gibson remake is the one anyone actually remembers.', null); # 251234 Payback 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (65522, 5, 'Tomer-Spector', 'Niche drama with a stacked cast that doesn''t go anywhere especially interesting. Worth it for Redford completionists only.', null); # 65522 Clearing, The 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (80969, 5, 'Tomer-Spector', 'Kinnear and Plummer doing harmless 90s comedy. Forgettable but never irritating.', null); # 80969 Dear God 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (73574, 4, 'Tomer-Spector', 'Direct-to-video horror that exists because DiCaprio happened to be in it. Skip unless you''re charting his early career.', null); # 73574 Critters 3 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30970, 7, 'Tomer-Spector', 'Animated crossover stitched from the TV series. Decent because the source shows were strong.', null); # 30970 Batman/Superman Movie, The 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (44238, 4, 'Tomer-Spector', 'Tales from the Crypt feature with Dennis Miller and Corey Feldman. Has its cult but the script collapses halfway through.', null); # 44238 Bordello of Blood 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (192850, 5, 'Tomer-Spector', 'Forgettable indie thriller. Curiosity for the cast more than anything in the script.', null); # 192850 Lizzie 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (168854, 5, 'Tomer-Spector', 'Not the Phoenix one. Niche art film that''s mostly noise without payoff.', null); # 168854 Joker 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (287501, 5, 'Tomer-Spector', 'Local Israeli production with limited reach abroad. Cultural-context interest more than essential viewing.', null); # 287501 Sanhedrin 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (351705, 5, 'Tomer-Spector', 'Mid-tier revenge film that doesn''t do enough with the premise. Streaming background watch.', null); # 351705 Vengeance 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (53921, 4, 'Tomer-Spector', 'Industry-insider satire that''s funnier if you''ve been to a film festival. Cameos are the main appeal.', null); # 53921 Cannes Man 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (58084, 4, 'Tomer-Spector', 'Low-budget psychological thriller. Ambition exceeds budget by a wide margin and you feel it in every scene.', null); # 58084 Cerebrium 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (242530, 5, 'Tomer-Spector', 'Not the animated film. 1999 thriller with limited release and limited reasons to seek it out.', null); # 242530 Open Season 1999
