insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (77,8,'EyalRabby','A very fun, fast-paced cat and mouse game.',NULL); # 77 'Catch Me If You Can': Behind the Camera 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (1529,4,'EyalRabby','Terrible acting and ridiculous car stunts that look like a cartoon.',NULL); # 1529 2 Fast 2 Furious 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (2709,8,'EyalRabby','A surprisingly sweet and creative romantic comedy.',NULL); # 2709 50 First Dates 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (3884,8,'EyalRabby','Very dark and mature for Disney, with an incredible soundtrack.',NULL); # 3884 A&E Biography: The Hunchback of Notre Dame 1996
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (9795,9,'EyalRabby','The absolute greatest voice acting performance in animation.',NULL); # 9795 Aladdin 1992
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (10741,8,'EyalRabby','The artwork is breathtaking, a fantastic and surreal journey.',NULL); # 10741 Alice in Wonderland 1951
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (10830,9,'EyalRabby','Tense, terrifying and brilliant sci-fi horror.',NULL); # 10830 Alien 1979
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (10916,4,'EyalRabby','An absolute disaster. Weird, gross, and completely unnecessary.',NULL); # 10916 Alien: Resurrection 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (10920,9,'EyalRabby','Perfect action sequel, expanded the lore brilliantly.',NULL); # 10920 Aliens 1986
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (13787,9,'EyalRabby','A beautifully crafted and deeply disturbing look at suburban life.',NULL); # 13787 American Beauty 1927
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (13978,9,'EyalRabby','An Oscar-worthy performance in a brutal and necessary film.',NULL); # 13978 American History X 1998
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (14131,7,'EyalRabby','Defined an entire generation of teen comedies. A bit dated but fun.',NULL); # 14131 American Pie 1999
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (16006,9,'EyalRabby','Completely absurd and hilarious newsroom satire.',NULL); # 16006 Anchorman: The Legend of Ron Burgundy 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (18960,10,'EyalRabby','I love the smell of napalm in the morning. An epic descent into madness.',NULL); # 18960 Apocalypse Now 1979
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (20371,6,'EyalRabby','Way too cheesy, filled with logical errors and melodrama.',NULL); # 20371 Armageddon 1998
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (24429,5,'EyalRabby','Recycles all the jokes from the previous movies. Very lazy writing.',NULL); # 24429 Austin Powers in Goldmember 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (24430,8,'EyalRabby','A brilliant parody of the spy genre. Extremely funny.',NULL); # 24430 Austin Powers: International Man of Mystery 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (26844,10,'EyalRabby','The perfect time travel movie, pure 80s magic.',NULL); # 26844 Back to the Future 1985
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (26846,8,'EyalRabby','A fantastic continuation, the vision of the future is iconic.',NULL); # 26846 Back to the Future Part II 1989
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (26847,7,'EyalRabby','A fun western conclusion, though not as tight as the first two.',NULL); # 26847 Back to the Future Part III 1990
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (27168,8,'EyalRabby','A hilarious and highly chaotic buddy cop action flick.',NULL); # 27168 Bad Boys 1995
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (27171,6,'EyalRabby','Way too long and chaotic. Cinematic excess at its worst.',NULL); # 27171 Bad Boys II 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (30952,3,'EyalRabby','Ice puns, bat-nipples, and a ridiculous neon aesthetic. Trash.',NULL); # 30952 Batman & Robin 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (30955,8,'EyalRabby','The Burton gothic aesthetic is absolutely perfect here.',NULL); # 30955 Batman 1989
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (30965,5,'EyalRabby','Too goofy and cartoonish, stepping away from the gothic tone.',NULL); # 30965 Batman Forever 1995
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (30967,7,'EyalRabby','A bit weird and dark, but highly memorable.',NULL); # 30967 Batman Returns 1992
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (32114,9,'EyalRabby','A fascinating and inspiring biographical drama.',NULL); # 32114 Beautiful Mind, A 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (32178,9,'EyalRabby','A tale as old as time, visually stunning and beautiful music.',NULL); # 32178 Beauty and the Beast 1991
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (33045,8,'EyalRabby','Extremely fun pacing and a great buddy dynamic.',NULL); # 33045 Behind the Scenes: Die Hard - With a Vengeance 1995
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (35522,8,'EyalRabby','A perfect, fast-paced 80s action-comedy blend.',NULL); # 35522 Beverly Hills Cop 1984
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (35523,7,'EyalRabby','A solid sequel with good action, though not quite as fresh as the original.',NULL); # 35523 Beverly Hills Cop II 1987
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (35524,4,'EyalRabby','Completely lost the magic. The lead looks bored and the script is awful.',NULL); # 35524 Beverly Hills Cop III 1994
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (37178,9,'EyalRabby','The Dude abides. A hilarious, chaotic, and perfectly directed film.',NULL); # 37178 Big Lebowski, The 1998
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (40187,7,'EyalRabby','Great vampire action that set the stage for modern Marvel.',NULL); # 40187 Blade 1998
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (40199,9,'EyalRabby','The atmosphere and visuals defined cyberpunk. A masterpiece.',NULL); # 40199 Blade Runner 1982
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (45126,8,'EyalRabby','Redefined the modern spy genre with gritty realism.',NULL); # 45126 Bourne Identity Crisis, The 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (45129,8,'EyalRabby','Excellent sequel, the shaky-cam action actually works here.',NULL); # 45129 Bourne Supremacy, The 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (46168,9,'EyalRabby','An epic historical masterpiece with incredible battle sequences.',NULL); # 46168 Braveheart 1925
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (48075,8,'EyalRabby','Playing God is a brilliant concept executed perfectly.',NULL); # 48075 Bruce Almighty 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (48792,9,'EyalRabby','The first rule is you do not talk about it. Great twist.',NULL); # 48792 Buena Vista Fight Club 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (50639,8,'EyalRabby','The butterfly effect concept is executed brilliantly. Very tense.',NULL); # 50639 Butterfly Effect, The 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (50760,10,'EyalRabby','A masterpiece that deserved all its Oscars.',NULL); # 50760 Buttsizer 3: Return of the King of Rears 1995
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (56431,9,'EyalRabby','Making the audience care about a volleyball takes incredible acting.',NULL); # 56431 Cast Away 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (57064,2,'EyalRabby','One of the worst comic book movies ever made. Nonsensical plot.',NULL); # 57064 Catwoman 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (58250,10,'EyalRabby','Iconic dialogues and unforgettable non-linear storytelling.',NULL); # 58250 Cesk Pulp Fiction a Blair Witch 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (64069,7,'EyalRabby','A beautiful classic, though the pacing is a bit slow for modern standards.',NULL); # 64069 Cinderella 1950
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (65811,8,'EyalRabby','Spielberg classic sci-fi, visually stunning and very uplifting.',NULL); # 65811 Close Encounters of the Third Kind 1977
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (66194,8,'EyalRabby','A surprisingly smart and highly quotable 90s teen comedy.',NULL); # 66194 Clueless 1995
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (68940,8,'EyalRabby','A ridiculously fun and over-the-top action movie.',NULL); # 68940 Con Air 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (78677,4,'EyalRabby','Awful editing, bad costumes, and a painfully edgy tone.',NULL); # 78677 Daredevil 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (79715,5,'EyalRabby','Impressive CGI for the time, but the science is laughable and the dialogue is painfully bad.',NULL); # 79715 Day After Tomorrow 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (80583,9,'EyalRabby','O Captain, my Captain! A truly powerful drama.',NULL); # 80583 Dead Poets Society 1989
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (81776,6,'EyalRabby','A bit too melodramatic and slow. Armageddon was dumber but at least more fun.',NULL); # 81776 Deep Impact 1998
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (82662,8,'EyalRabby','Great futuristic satire and explosive 90s action.',NULL); # 82662 Demolition Man 1993
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (83789,5,'EyalRabby','Lacks all the charm and originality of the first movie.',NULL); # 83789 Design in Motion: The Look of 'Men in Black II' 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (86274,10,'EyalRabby','Yippee-ki-yay! The ultimate Christmas action movie.',NULL); # 86274 Die Hard 1988
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (86279,7,'EyalRabby','A great sequel, though a bit repetitive compared to the first.',NULL); # 86279 Die Hard 2 1990
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (90772,8,'EyalRabby','Time travel mechanics are really clever, very dark and engaging.',NULL); # 90772 Donnie Darko 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (96590,8,'EyalRabby','A magical story, pure cinematic wonder.',NULL); # 96590 E.T. and Friends: Magical Movie Visitors 1982
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (99164,8,'EyalRabby','A highly quotable and energetic modern holiday classic.',NULL); # 99164 Elf 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (100138,10,'EyalRabby','Perfect dark tone and the greatest twist in cinema.',NULL); # 100138 Empire Strikes Back, The 1985
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (102108,9,'EyalRabby','Swashbuckling adventure at its absolute best.',NULL); # 102108 Epic at Sea: The Making of 'Pirates of the Caribbean: The Curse of the Black Pearl', An 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (106217,10,'EyalRabby','Peak action sequences and a phenomenal villain.',NULL); # 106217 Exterminator 2 1984
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (107166,8,'EyalRabby','The premise is completely absurd but the execution is perfection.',NULL); # 107166 Face/Off 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (109093,9,'EyalRabby','A brilliant, quirky, and dark comedy thriller.',NULL); # 109093 Fargo 1996
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (111442,10,'EyalRabby','Life moves pretty fast. The ultimate feel-good rebellion movie.',NULL); # 111442 Ferris Bueller's Day Off 1986
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (112205,8,'EyalRabby','Colourful and weird futuristic ride. Extremely fun.',NULL); # 112205 Fifth Element, The 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (113504,9,'EyalRabby','Beautiful underwater world and a very touching story.',NULL); # 113504 Finding Nemo 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (114067,8,'EyalRabby','A surprisingly deep and tragic story about a traumatized veteran.',NULL); # 114067 First Blood 1982
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (117874,8,'EyalRabby','Classic 90s cinema, heartwarming and historically rich.',NULL); # 117874 Forrest Gump 1994
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (121538,9,'EyalRabby','The boot camp segment is terrifying and unforgettable.',NULL); # 121538 Full Metal Jacket 1987
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (127254,6,'EyalRabby','Recycles the exact same jokes from the first one. Not nearly as funny or iconic.',NULL); # 127254 Ghostbusters II 1989
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (128694,2,'EyalRabby','An absolute abomination of a sequel. Terrible acting and completely unnecessary.',NULL); # 128694 Girls Home Alone 4 1998
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (129185,9,'EyalRabby','Epic and brutal arena action. Are you not entertained?',NULL); # 129185 Gladiator 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (130128,10,'EyalRabby','One of the greatest films ever made, fantastic acting.',NULL); # 130128 Godfather, The 1972
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (130129,10,'EyalRabby','A rare sequel that is just as good, if not better, than the original.',NULL); # 130129 Godfather: Part II, The 1974
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (130130,5,'EyalRabby','A boring, confusing mess that completely tarnishes the legacy.',NULL); # 130130 Godfather: Part III, The 1990
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (130201,3,'EyalRabby','Terrible CGI and completely ruined the monster legacy.',NULL); # 130201 Godzilla 1998
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (130708,8,'EyalRabby','A pioneer in animation, visually stunning for its time.',NULL); # 130708 Golden Anniversary of Snow White and the Seven Dwarfs 1987
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (131537,8,'EyalRabby','A powerhouse of energy in a great wartime dramedy.',NULL); # 131537 Good Morning, Vietnam 1987
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (131665,9,'EyalRabby','Such a wholesome and emotional movie, a timeless classic.',NULL); # 131665 Good Will Hunting 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (131780,10,'EyalRabby','The definitive mob movie. Pacing and soundtrack are flawless.',NULL); # 131780 Goodfellas 1990
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (133725,10,'EyalRabby','The absolute perfect adventure film. Flawless pacing.',NULL); # 133725 Great Movie Stunts: Raiders of the Lost Ark 1981
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (134077,9,'EyalRabby','Incredibly emotional and powerful story. Stephen King adaptation at its best.',NULL); # 134077 Green Mile, The 1999
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (134193,8,'EyalRabby','A brilliant mix of horror and comedy, very creative creature designs.',NULL); # 134193 Gremlins 1984
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (134672,9,'EyalRabby','A brilliant time-loop concept executed flawlessly.',NULL); # 134672 Groundhog Day 1993
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (138797,8,'EyalRabby','The price is wrong! Classic 90s slapstick comedy.',NULL); # 138797 Happy Gilmore 1996
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (139650,8,'EyalRabby','The basilisk terrified me as a kid, great mystery.',NULL); # 139650 Harry Potter and the Chamber of Secrets 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (139655,9,'EyalRabby','Darker tone, arguably the best in the series.',NULL); # 139655 Harry Potter and the Prisoner of Azkaban 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (139657,8,'EyalRabby','Very nostalgic, a magical introduction to the wizarding world.',NULL); # 139657 Harry Potter and the Sorcerer's Stone 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (143526,8,'EyalRabby','Very funny and energetic, features a perfectly sassy villain.',NULL); # 143526 Hercules 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (148200,9,'EyalRabby','The ultimate Christmas comedy with brilliant slapstick traps.',NULL); # 148200 Home Alone 1990
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (148203,8,'EyalRabby','Almost as good as the first, the New York setting adds a lot of fun.',NULL); # 148203 Home Alone 2: Lost in New York 1992
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (148205,3,'EyalRabby','An absolute insult to the franchise without the original cast.',NULL); # 148205 Home Alone 3 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (152426,4,'EyalRabby','Terrible CGI and a boring script. A complete waste of potential.',NULL); # 152426 Hulk 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (154797,10,'EyalRabby','A deeply moving and heartbreaking masterpiece by Spielberg.',NULL); # 154797 I Was On Schindler's List 1996
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (155069,8,'EyalRabby','Highly charismatic lead in a great robot rebellion film.',NULL); # 155069 I, Robot 1983
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (155213,8,'EyalRabby','Hilarious side characters and a very nostalgic early CGI film.',NULL); # 155213 Ice Age 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (158999,8,'EyalRabby','Welcome to Earth! The ultimate 90s alien invasion blockbuster.',NULL); # 158999 Independence Day 1996
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (159172,10,'EyalRabby','Perfect father-son dynamic in a great adventure.',NULL); # 159172 Indiana Jones and the Last Crusade 1989
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (159175,6,'EyalRabby','Too dark, annoying side characters, and culturally insensitive.',NULL); # 159175 Indiana Jones and the Temple of Doom 1984
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (160313,5,'EyalRabby','A massive downgrade that ruins the perfect ending of T2.',NULL); # 160313 Inside 'Terminator 3: Rise of the Machines' 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (161481,10,'EyalRabby','The Omaha beach scene is the best war sequence ever filmed.',NULL); # 161481 Into the Breach: 'Saving Private Ryan' 1998
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (162352,9,'EyalRabby','Incredibly emotional and beautifully animated. A masterpiece.',NULL); # 162352 Iron Giant, The 1999
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (165961,9,'EyalRabby','The original summer blockbuster. A masterpiece of suspense and music.',NULL); # 165961 Jaws 1975
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (166917,8,'EyalRabby','A very moving story with surprisingly great dramatic moments.',NULL); # 166917 Jerry Maguire 1996
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (176711,9,'EyalRabby','Amazing fight choreography and unforgettable stylish action.',NULL); # 176711 Kill Bill: Vol. 1 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (176712,8,'EyalRabby','Slower than the first volume, but a great emotional conclusion.',NULL); # 176712 Kill Bill: Vol. 2 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (182955,9,'EyalRabby','A complex and perfectly executed neo-noir with an amazing cast.',NULL); # 182955 L.A. Confidential 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (184814,4,'EyalRabby','Terrible script and completely boring action sequences.',NULL); # 184814 Lara Croft: Tomb Raider 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (188507,8,'EyalRabby','The blueprint for all buddy-cop movies. Great action.',NULL); # 188507 Lethal Weapon 1987
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (188509,7,'EyalRabby','More action and comedy, holds up really well as a sequel.',NULL); # 188509 Lethal Weapon 2 1989
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (188510,6,'EyalRabby','Starting to feel formulaic and tired. Not as sharp.',NULL); # 188510 Lethal Weapon 3 1992
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (189233,8,'EyalRabby','The ultimate peak of chaotic 90s physical comedy.',NULL); # 189233 Liar Liar 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (190166,9,'EyalRabby','A brilliant and daring religious satire. Always look on the bright side.',NULL); # 190166 Life of Brian 1979
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (194497,10,'EyalRabby','The ultimate epic fantasy, incredible world building.',NULL); # 194497 Lord of the Rings: The Fellowship of the Ring, The 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (194502,10,'EyalRabby','The battle of Helm''s Deep is unmatched in cinematic history.',NULL); # 194502 Lord of the Rings: The Two Towers, The 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (199207,8,'EyalRabby','A great dystopian setting, started a fantastic franchise.',NULL); # 199207 Mad Max 1979
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (199209,9,'EyalRabby','Incredible vehicular action, sets the standard for post-apocalyptic films.',NULL); # 199209 Mad Max 2: The Road Warrior 1981
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (199210,6,'EyalRabby','The kids ruin an otherwise okay dystopian movie.',NULL); # 199210 Mad Max Beyond Thunderdome 1985
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (201516,10,'EyalRabby','A pioneer in sci-fi action, completely changed cinema.',NULL); # 201516 Making 'The Matrix' 1999
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (201609,5,'EyalRabby','Too depressing and weird, killed off beloved characters.',NULL); # 201609 Making of 'Alien 3', The 1992
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (201795,8,'EyalRabby','Classic Disney renaissance film with an incredible villain.',NULL); # 201795 Making of 'The Little Mermaid', The 1989
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (201822,9,'EyalRabby','A timeless classic that revolutionized animation.',NULL); # 201822 Making of 'Toy Story', The 1995
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (207989,5,'EyalRabby','Overcomplicated plot that loses the philosophical magic.',NULL); # 207989 Matrix Reloaded, The 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (207991,4,'EyalRabby','A boring CGI fest that completely ruined the trilogy.',NULL); # 207991 Matrix Revolutions, The 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (209133,8,'EyalRabby','Incredibly smart and quotable. A perfect high school satire.',NULL); # 209133 Mean Girls 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (209657,8,'EyalRabby','Awkward family dynamics turned into pure comedy gold.',NULL); # 209657 Meet the Parents 1992
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (210509,9,'EyalRabby','Early non-linear storytelling genius. Extremely engaging.',NULL); # 210509 Memento 1967
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (210739,8,'EyalRabby','A fantastic blend of sci-fi, comedy, and action.',NULL); # 210739 Men in Black 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (214755,8,'EyalRabby','Great action sci-fi concept, visually very slick.',NULL); # 214755 Minority Report 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (215876,8,'EyalRabby','The wire drop scene is iconic. Great start to the franchise.',NULL); # 215876 Mission: Impossible 1996
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (215879,5,'EyalRabby','Too much slow-motion and doves. Feels more like a music video.',NULL); # 215879 Mission: Impossible II 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (218415,9,'EyalRabby','So creative and heartwarming, iconic monster duo.',NULL); # 218415 Monsters, Inc. 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (218599,10,'EyalRabby','Absolute comedy perfection. Every scene is a legendary meme.',NULL); # 218599 Monty Python and the Holy Grail 1975
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (219534,5,'EyalRabby','Cheesy 90s video game adaptation. Has a great theme song but terrible acting.',NULL); # 219534 Mortal Kombat 1995
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (221259,9,'EyalRabby','A highly heartfelt and hilarious comedy performance.',NULL); # 221259 Mrs. Doubtfire 1993
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (222112,9,'EyalRabby','Let''s get down to business! The songs are absolute bangers.',NULL); # 222112 Mulan 1998
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (222115,4,'EyalRabby','A terrible, cheap-looking sequel that completely ruins the characters.',NULL); # 222115 Mulan II 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (222321,5,'EyalRabby','The CGI is offensively bad. A bloated and messy sequel.',NULL); # 222321 Mummy Returns, The 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (232425,9,'EyalRabby','Incredible stop-motion animation and a wonderfully creepy atmosphere.',NULL); # 232425 Nightmare Before Christmas, The 1993
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (235617,10,'EyalRabby','The greatest plot twist in cinematic history. Mind blown.',NULL); # 235617 Nothing Is What It Seems: The Making of 'The Usual Suspects' 1998
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (235790,7,'EyalRabby','A classic rom-com with a very charming leading duo.',NULL); # 235790 Notting Hill 1999
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (237008,6,'EyalRabby','The gross-out humor gets old very quickly.',NULL); # 237008 Nutty Professor, The 1996
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (238072,9,'EyalRabby','The coolest cast ever assembled. A perfect, slick heist movie.',NULL); # 238072 Ocean's Eleven 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (238073,5,'EyalRabby','A smug, confusing sequel that thinks it is much smarter than it is.',NULL); # 238073 Ocean's Twelve 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (240868,9,'EyalRabby','Who you gonna call? Absolute classic comedy with great practical effects.',NULL); # 240868 On the Scene with the Ghostbusters 1984
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (253914,7,'EyalRabby','A fun adventure with Captain Hook, very nostalgic.',NULL); # 253914 Peter Pan 1953
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (256342,8,'EyalRabby','Darker than most Disney movies, a classic morality tale.',NULL); # 256342 Pinocchio 1940
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (257459,9,'EyalRabby','A brutal and realistic look at the Vietnam war. Very intense.',NULL); # 257459 Platoon 1986
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (258509,6,'EyalRabby','Beautiful animation, but the historical inaccuracies and weak plot drag it down.',NULL); # 258509 Pocahontas 1995
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (262645,8,'EyalRabby','One of the best testosterone-fueled action movies ever made.',NULL); # 262645 Predator 1987
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (263360,8,'EyalRabby','A modern, highly charming and feel-good fairytale romance.',NULL); # 263360 Pretty Woman 1990
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (271192,9,'EyalRabby','A very touching and emotional cross-country road movie.',NULL); # 271192 Rain Man 1988
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (271826,7,'EyalRabby','Turns into pure 80s action cheese, but undeniably fun.',NULL); # 271826 Rambo: First Blood Part II 1985
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (276217,8,'EyalRabby','Great dialogue and tension, a fantastic directorial debut.',NULL); # 276217 Reservoir Dogs 1992
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (279841,7,'EyalRabby','Violent, satirical, and strangely thought-provoking.',NULL); # 279841 RoboCop 1987
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (280270,9,'EyalRabby','A fantastic underdog story with a legendary soundtrack.',NULL); # 280270 Rocky 1976
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (280284,7,'EyalRabby','Pure 80s cold-war cheese, but incredibly entertaining.',NULL); # 280284 Rocky IV 1985
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (280305,4,'EyalRabby','Completely ruined the franchise momentum with a boring story.',NULL); # 280305 Rocky V 1990
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (283712,8,'EyalRabby','Unmatched comedic chemistry and great stunt work.',NULL); # 283712 Rush Hour 1998
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (289558,9,'EyalRabby','A brutal and iconic rise-and-fall crime story.',NULL); # 289558 Scarface 1983
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (289666,6,'EyalRabby','Relies heavily on cheap laughs and pop culture references that aged poorly.',NULL); # 289666 Scary Movie 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (290378,9,'EyalRabby','Incredible energy, great laughs, and a fantastic soundtrack.',NULL); # 290378 School of Rock, The 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (291698,9,'EyalRabby','One of the best and darkest endings in thriller history.',NULL); # 291698 Se7en 1995
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (297838,9,'EyalRabby','Very inspiring story about hope and persistence.',NULL); # 297838 Shawshank Redemption, The 1994
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (300229,9,'EyalRabby','A brilliant parody of fairytales, the humor still holds up.',NULL); # 300229 Shrek 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (300230,10,'EyalRabby','The rare sequel that is actually better than the original.',NULL); # 300230 Shrek 2 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (304829,8,'EyalRabby','The ultimate 90s romantic comedy classic.',NULL); # 304829 Sleepless in Seattle 1993
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (310130,7,'EyalRabby','A crazy crossover that shouldn''t work but somehow is super nostalgic.',NULL); # 310130 Space Jam 1996
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (310726,8,'EyalRabby','Great concept and incredibly tense execution throughout.',NULL); # 310726 Speed 1994
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (311037,8,'EyalRabby','The definitive and classic superhero origin story.',NULL); # 311037 Spider-Man 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (311038,9,'EyalRabby','Incredible villain arc. One of the best superhero sequels.',NULL); # 311038 Spider-Man 2 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (313059,9,'EyalRabby','A beautiful and nostalgic coming-of-age story based on Stephen King.',NULL); # 313059 Stand by Me 1986
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (313441,5,'EyalRabby','Incredibly boring and slow paced. Looks like a screensaver for two hours.',NULL); # 313441 Star Trek: The Motion Picture 1979
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (313449,9,'EyalRabby','KHAAAAAN! The absolute peak of the classic Star Trek movies.',NULL); # 313449 Star Trek: The Wrath of Khan 1982
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (313474,5,'EyalRabby','Jar Jar ruins the tone, and the politics are incredibly boring.',NULL); # 313474 Star Wars: Episode I - The Phantom Menace 1999
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (313476,4,'EyalRabby','The romance dialogue is physically painful to watch.',NULL); # 313476 Star Wars: Episode II - Attack of the Clones 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (313479,8,'EyalRabby','A great conclusion to the original trilogy, Ewoks are fun.',NULL); # 313479 Star Wars: Episode VI - Return of the Jedi 1983
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (313820,9,'EyalRabby','Would you like to know more? A brilliant and bloody political satire.',NULL); # 313820 Starship Troopers 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (325098,8,'EyalRabby','An absolutely amazing and iconic drum-heavy soundtrack.',NULL); # 325098 Tarzan 1999
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (326155,10,'EyalRabby','You talkin to me? A gritty, disturbing and masterfully directed film.',NULL); # 326155 Taxi Driver 1976
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (326243,8,'EyalRabby','Excellent! A classic 90s comedy that still holds up perfectly.',NULL); # 326243 Taylor Wayne's World 1992
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (333856,8,'EyalRabby','An absolute spectacle. The practical effects of the sinking are incredible.',NULL); # 333856 Titanic 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (335834,8,'EyalRabby','Classic 80s action, great soundtrack and aerial dogfights.',NULL); # 335834 Top Gun 1955
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (336458,8,'EyalRabby','Mind-bending action classic. Practical effects are grotesque.',NULL); # 336458 Total Recall 1990
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (337168,9,'EyalRabby','A rare sequel that expands the world and hits right in the feels.',NULL); # 337168 Toy Story 2 1999
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (337830,9,'EyalRabby','A kinetic and wildly energetic dive into addiction. Visually striking.',NULL); # 337830 Trainspotting 1996
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (340799,9,'EyalRabby','Pure, unadulterated and highly entertaining 90s action-comedy.',NULL); # 340799 True Lies 1994
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (340901,9,'EyalRabby','A brilliant and satirical look at media and reality TV ahead of its time.',NULL); # 340901 Truman Show, The 1998
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (342685,6,'EyalRabby','Cool special effects for the time, but the characters and dialogue are completely flat.',NULL); # 342685 Twister 1996
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (345690,8,'EyalRabby','A brilliant and grounded take on the superhero genre.',NULL); # 345690 Unbreakable 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (360100,5,'EyalRabby','A bloated mess with an absurd budget and very little substance.',NULL); # 360100 Waterworld 1995
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (365906,8,'EyalRabby','A weird, wonderful, and highly imaginative classic.',NULL); # 365906 Willy Wonka & the Chocolate Factory 1971
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (369458,8,'EyalRabby','Kicked off the modern superhero craze in style.',NULL); # 369458 X-Men 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (369486,9,'EyalRabby','Nightcrawler White House scene is legendary. Best of the trilogy.',NULL); # 369486 X2 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (375827,8,'EyalRabby','Blue Steel! A hilarious and absurd fashion industry satire.',NULL); # 375827 Zoolander 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (379168,8,'EyalRabby','Physical comedy at its absolute peak. Endlessly quotable.',NULL); # 379168 Ace Ventura: Pet Detective 1996
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (380706,9,'EyalRabby','A sharp, witty, and unconventional romantic comedy.',NULL); # 380706 As Good as It Gets 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (410647,6,'EyalRabby','Some funny moments but the funny voice gets annoying quickly.',NULL); # 410647 Waterboys 2003