insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139657, 10, 'Noam-Barkai', 'The film that started it all. Magical from start to finish.', null);  # 139657 Harry Potter and the Sorcerer's Stone 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139650, 10, 'Noam-Barkai', 'A worthy sequel, slightly darker than the first. The basilisk scene stuck with me.', null);  # 139650 Harry Potter and the Chamber of Secrets 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139655, 10, 'Noam-Barkai', 'The best in the series. The time turner twist is clever and surprising.', null);  # 139655 Harry Potter and the Prisoner of Azkaban 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139652, 8, 'Noam-Barkai', 'Exciting tournament tasks and a gorgeous Yule Ball. A little long but worth it.', null);  # 139652 Harry Potter and the Goblet of Fire 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139654, 8, 'Noam-Barkai', 'Umbridge is one of the most hateable villains in any film, and that is exactly the point.', null);  # 139654 Harry Potter and the Order of the Phoenix 2007
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139653, 7, 'Noam-Barkai', 'The story turns serious here. The ending genuinely surprised me.', null);  # 139653 Harry Potter and the Half-Blood Prince 2008
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194497, 7, 'Noam-Barkai', 'Beautiful fantasy world and a great journey. A very long sit though.', null);  # 194497 Lord of the Rings: The Fellowship of the Ring, The 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194502, 6, 'Noam-Barkai', 'The big battle is great. Everything around it drags.', null);  # 194502 Lord of the Rings: The Two Towers, The 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194500, 6, 'Noam-Barkai', 'Epic ending but it stretches across five endings in a row. Too long.', null);  # 194500 Lord of the Rings: The Return of the King, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (263360, 10, 'Noam-Barkai', 'Classic and a must-watch film. Julia Roberts is unforgettable in this role.', null);  # 263360 Pretty Woman 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (283410, 8, 'Noam-Barkai', 'Not as strong as Pretty Woman but the same vibe and the same leads make it lovely.', null);  # 283410 Runaway Bride 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (200864, 8, 'Noam-Barkai', 'A modern Cinderella story. Cozy, sweet and one I keep coming back to.', null);  # 200864 Maid in Manhattan 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (264157, 8, 'Noam-Barkai', 'More fun than the first. The mattress slide and the slumber party are great scenes.', null);  # 264157 Princess Diaries 2: Royal Engagement, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46878, 8, 'Noam-Barkai', 'Funny, awkward and relatable. The skiing scene cracks me up every time.', null);  # 46878 Bridget Jones: The Edge of Reason 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (151616, 10, 'Noam-Barkai', 'Classic romantic comedy. Light, fun, funny and rewatchable.', null);  # 151616 How to Lose a Guy in 10 Days 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (644, 10, 'Noam-Barkai', 'A clever Shakespeare adaptation that really holds up. Smart, funny and with real heart.', null);  # 644 10 Things I Hate About You 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (1038, 10, 'Noam-Barkai', 'Jennifer Garner sells every minute. Pure fun, and the Thriller dance alone earns the ten.', null);  # 1038 13 Going On 30 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (66194, 10, 'Noam-Barkai', 'A classic teen comedy that holds up incredibly well. Sharper than most people remember.', null);  # 66194 Clueless 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (263, 7, 'Noam-Barkai', 'Sweet little romance. Nothing groundbreaking but easy to enjoy.', null);  # 263 'Til There Was You 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (297838, 8, 'Noam-Barkai', 'Slow build, but the ending makes everything worth it. Deserves the reputation.', null);  # 297838 Shawshank Redemption, The 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (333856, 7, 'Noam-Barkai', 'Iconic romance with a heartbreaking ending. Three hours is a real commitment though.', null);  # 333856 Titanic 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (113506, 8, 'Noam-Barkai', 'Depp gives an understated, lovely performance. The play scene made me cry.', null);  # 113506 Finding Neverland 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (31715, 7, 'Noam-Barkai', 'A friendship film for the ages. The title song earns every tear.', null);  # 31715 Beaches 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (34077, 7, 'Noam-Barkai', 'Beautiful concept and lovely to look at. Way too long.', null);  # 34077 Benjamin Button 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (34104, 8, 'Noam-Barkai', 'Quirky and genuinely romantic. A small lovely film.', null);  # 34104 Benny & Joon 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (244421, 7, 'Noam-Barkai', 'Diane Keaton anchors the cast. Surprisingly moving and more honest than I expected.', null);  # 244421 Other Sister, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (32180, 8, 'Noam-Barkai', 'A nice retelling of a classic story. Better than I expected for a TV version.', null);  # 32180 Beauty and the Beast 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (190869, 8, 'Noam-Barkai', 'Cute, funny and full of heart. One of the better Disney films. Stitch is a great character.', null);  # 190869 Lilo & Stitch 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (170721, 6, 'Noam-Barkai', 'Decent sequel but the songs do not come close to the original.', null);  # 170721 Jungle Book 2, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (337166, 8, 'Noam-Barkai', 'Still holds up after all these years. A great friendship story.', null);  # 337166 Toy Story 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300229, 10, 'Noam-Barkai', 'Works for kids and adults equally. Funny, sweet, with a great soundtrack.', null);  # 300229 Shrek 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300230, 10, 'Noam-Barkai', 'Even better than the first. Puss in Boots steals every scene.', null);  # 300230 Shrek 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300233, 4, 'Noam-Barkai', 'Felt more like a theme park gimmick than a real film. Forgettable.', null);  # 300233 Shrek 4-D 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (70959, 8, 'Noam-Barkai', 'Dark and sweet at the same time. Stunning stop motion animation and a haunting score.', null);  # 70959 Corpse Bride, The 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (97727, 8, 'Noam-Barkai', 'Burton is one of my favorites and this is him at his best. Depp barely speaks and still says everything.', null);  # 97727 Edward Scissorhands 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (59578, 8, 'Noam-Barkai', 'A weird, colorful version with great songs. Different from the older one but charming in its own way.', null);  # 59578 Charlie and the Chocolate Factory 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256632, 10, 'Noam-Barkai', 'Pirate adventure done right. Jack Sparrow is an unforgettable character.', null);  # 256632 Pirates of the Caribbean: The Curse of the Black Pearl 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256631, 8, 'Noam-Barkai', 'Not as tight as the first but the action scenes are excellent.', null);  # 256631 Pirates of the Caribbean 2 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (142491, 6, 'Noam-Barkai', 'Del Toro''s creature design and atmosphere are great. The story itself is only okay.', null);  # 142491 Hellboy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (142492, 6, 'Noam-Barkai', 'Even more imaginative visuals from Del Toro. The troll market scene is the highlight.', null);  # 142492 Hellboy 2 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (183873, 7, 'Noam-Barkai', 'Romantic fantasy with an original curse premise. The music has dated badly.', null);  # 183873 Ladyhawke 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (304862, 7, 'Noam-Barkai', 'Burton''s gothic touch all over this one. Spooky and exactly the kind of dark fairy tale I enjoy.', null);  # 304862 Sleepy Hollow 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (96593, 8, 'Noam-Barkai', 'A classic Spielberg family film. The flying bike scene is rightfully iconic.', null);  # 96593 E.T. the Extra-Terrestrial 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (149287, 8, 'Noam-Barkai', 'Robin Williams gives the role real heart. A fresh, emotional take on Peter Pan.', null);  # 149287 Hook 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (372733, 6, 'Noam-Barkai', 'An entertaining mystery with supernatural touches. Better than expected.', null);  # 372733 Young Sherlock Holmes 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311428, 7, 'Noam-Barkai', 'Light mermaid romance, easy to watch. Better than it has any right to be.', null);  # 311428 Splash 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311037, 7, 'Noam-Barkai', 'Solid superhero origin. The upside down kiss is iconic.', null);  # 311037 Spider-Man 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311038, 8, 'Noam-Barkai', 'Better than the first. The train scene is one of the best in the genre.', null);  # 311038 Spider-Man 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311040, 4, 'Noam-Barkai', 'Too many villains, too many tones. The dance scene is memorable in the worst way.', null);  # 311040 Spider-Man 3 2007
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (220276, 7, 'Noam-Barkai', 'Visually overwhelming. The musical mashups really land, even if the style is a lot.', null);  # 220276 Moulin Rouge! 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (220805, 7, 'Noam-Barkai', 'Pitt and Jolie chemistry is the engine. Funnier action comedy than I expected.', null);  # 220805 Mr. and Mrs. Smith 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (62460, 8, 'Noam-Barkai', 'A warm story in a beautifully shot French village. Romantic and cozy throughout.', null);  # 62460 Chocolat 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (271344, 7, 'Noam-Barkai', 'Sweet family story that does not lean on the cheese.', null);  # 271344 Raising Helen 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (118980, 7, 'Noam-Barkai', 'Two lonely people finding each other. Quiet, honest and grounded.', null);  # 118980 Frankie and Johnny 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (245699, 7, 'Noam-Barkai', 'The amnesia plot has no right to work, yet the leads sell it.', null);  # 245699 Overboard 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (328272, 8, 'Noam-Barkai', 'Charming and unusual. Hard to believe an airport setting could work this well.', null);  # 328272 Terminal, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56871, 8, 'Noam-Barkai', 'DiCaprio carries the whole film with real charm. Fun cat and mouse from start to finish.', null);  # 56871 Catch Me If You Can 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (291495, 7, 'Noam-Barkai', 'Clever modern take on the Christmas Carol story. Good for holiday rewatches.', null);  # 291495 Scrooged 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131885, 7, 'Noam-Barkai', 'Classic kid adventure. They really do not make these anymore.', null);  # 131885 Goonies, The 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (208245, 7, 'Noam-Barkai', 'Light, funny western with great chemistry between the leads.', null);  # 208245 Maverick 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188507, 7, 'Noam-Barkai', 'Sets up the buddy cop formula brilliantly. Action and comedy in balance.', null);  # 188507 Lethal Weapon 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188509, 7, 'Noam-Barkai', 'My favorite of the four. Memorable villains and a sharp script.', null);  # 188509 Lethal Weapon 2 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188510, 6, 'Noam-Barkai', 'Decent enough but the spark from the second is gone.', null);  # 188510 Lethal Weapon 3 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188511, 4, 'Noam-Barkai', 'Tired by this point in the series. Felt like a cash grab.', null);  # 188511 Lethal Weapon 4 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280270, 7, 'Noam-Barkai', 'The underdog story done right. Iconic training scenes.', null);  # 280270 Rocky 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280281, 6, 'Noam-Barkai', 'Rematch sequel. Watchable but mostly recycles the first.', null);  # 280281 Rocky II 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280282, 6, 'Noam-Barkai', 'Eye of the Tiger and Mr T are what save this one.', null);  # 280282 Rocky III 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280284, 6, 'Noam-Barkai', 'Ridiculous Cold War boxing. Knows what it is and commits.', null);  # 280284 Rocky IV 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280305, 2, 'Noam-Barkai', 'The weakest in the series by far. Better off skipped.', null);  # 280305 Rocky V 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215876, 6, 'Noam-Barkai', 'The vault drop scene is fantastic. The rest of the plot lost me.', null);  # 215876 Mission: Impossible 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215879, 4, 'Noam-Barkai', 'Felt empty. Loud action but I forgot the whole film quickly.', null);  # 215879 Mission: Impossible II 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215880, 6, 'Noam-Barkai', 'Decent installment, mostly thanks to a strong villain performance.', null);  # 215880 Mission: Impossible III 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159172, 7, 'Noam-Barkai', 'Sean Connery as the father is perfect casting. The best of the series.', null);  # 159172 Indiana Jones and the Last Crusade 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (271095, 7, 'Noam-Barkai', 'Spielberg setting the standard for the adventure genre. Iconic scenes throughout.', null);  # 271095 Raiders of the Lost Ark 1981
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159175, 4, 'Noam-Barkai', 'Tonally off from the rest of the series. The dinner scene is unforgettable in the worst way.', null);  # 159175 Indiana Jones and the Temple of Doom 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159167, 4, 'Noam-Barkai', 'Too many silly choices. They should have left the series alone.', null);  # 159167 Indiana Jones 4 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313478, 6, 'Noam-Barkai', 'Iconic reveal scene. The rest does not really stand out.', null);  # 313478 Star Wars: Episode V - The Empire Strikes Back 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313479, 6, 'Noam-Barkai', 'Strong throne room scene but the Ewok material has aged poorly.', null);  # 313479 Star Wars: Episode VI - Return of the Jedi 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313474, 4, 'Noam-Barkai', 'Only the pod race is worth watching. Most of it is a slog.', null);  # 313474 Star Wars: Episode I - The Phantom Menace 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313476, 4, 'Noam-Barkai', 'Painful romance dialogue throughout. The Yoda fight is the only highlight.', null);  # 313476 Star Wars: Episode II - Attack of the Clones 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313477, 5, 'Noam-Barkai', 'The strongest of the prequel trilogy. The final duel is well done.', null);  # 313477 Star Wars: Episode III - Revenge of the Sith 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (92573, 5, 'Noam-Barkai', 'Very dated. Worth watching as the first in the series, not much else.', null);  # 92573 Dr. No 1962
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120574, 5, 'Noam-Barkai', 'Outside the train fight, slow and unmemorable.', null);  # 120574 From Russia with Love 1963
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130953, 6, 'Noam-Barkai', 'The most iconic of the early Bond films. Memorable villain and theme song.', null);  # 130953 Goldfinger 1964
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (332065, 4, 'Noam-Barkai', 'The underwater scenes go on forever. Got bored midway.', null);  # 332065 Thunderball 1965
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (372233, 4, 'Noam-Barkai', 'Forgettable. Would not return to it.', null);  # 372233 You Only Live Twice 1967
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218808, 4, 'Noam-Barkai', 'Bond in space, as silly as it sounds. One of the worst in the series.', null);  # 218808 Moonraker 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (117314, 5, 'Noam-Barkai', 'Mostly forgettable. Only the ski chase stood out.', null);  # 117314 For Your Eyes Only 1981
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312170, 6, 'Noam-Barkai', 'The theme song is one of the best in the series. The film itself is decent.', null);  # 312170 Spy Who Loved Me, The 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (192514, 4, 'Noam-Barkai', 'Only the theme song stuck with me. The rest is weak.', null);  # 192514 Live and Let Die 1973
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (203649, 4, 'Noam-Barkai', 'Forgettable apart from the villain.', null);  # 203649 Man with the Golden Gun, The 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (240521, 6, 'Noam-Barkai', 'Underrated Bond with real emotional stakes for once.', null);  # 240521 On Her Majesty's Secret Service 1969
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (192702, 4, 'Noam-Barkai', 'Tried for a more serious Bond. Did not quite get there.', null);  # 192702 Living Daylights, The 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (189403, 4, 'Noam-Barkai', 'Too dark for the character. Did not work for me.', null);  # 189403 Licence to Kill 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (354178, 2, 'Noam-Barkai', 'Bad casting choices and a tired plot. Not worth a watch.', null);  # 354178 View to a Kill, A 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130945, 7, 'Noam-Barkai', 'Strong Bond reboot. The tank chase is one of the best action scenes around.', null);  # 130945 GoldenEye 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335336, 5, 'Noam-Barkai', 'Decent Bond. The female lead is really the only highlight.', null);  # 335336 Tomorrow Never Dies 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (368418, 4, 'Noam-Barkai', 'Routine Bond, nothing stands out. Felt like filler.', null);  # 368418 World Is Not Enough, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (86263, 4, 'Noam-Barkai', 'The invisible car alone makes it hard to take seriously. Disappointing.', null);  # 86263 Die Another Day 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (85871, 4, 'Noam-Barkai', 'Very dated. Only the theme song held my attention.', null);  # 85871 Diamonds Are Forever 1971
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (267038, 6, 'Noam-Barkai', 'Tarantino''s writing is sharp. The runtime feels longer than it needs to be.', null);  # 267038 Pulp Fiction 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (276217, 6, 'Noam-Barkai', 'Tarantino''s opening scene is a great one. The rest is way too violent for my taste.', null);  # 276217 Reservoir Dogs 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (164572, 4, 'Noam-Barkai', 'Dragged. I kept losing interest.', null);  # 164572 Jackie Brown 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176711, 4, 'Noam-Barkai', 'Some impressive action but more violence than I want to sit through.', null);  # 176711 Kill Bill: Vol. 1 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176712, 4, 'Noam-Barkai', 'Slow and talky. Splitting it into two films felt pointless.', null);  # 176712 Kill Bill: Vol. 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159665, 5, 'Noam-Barkai', 'Memorable villain performance. The film around it is too long.', null);  # 159665 Inglorious Bastards 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (270971, 4, 'Noam-Barkai', 'De Niro''s transformation is impressive. Boxing dramas are just not for me.', null);  # 270971 Raging Bull 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (326155, 4, 'Noam-Barkai', 'De Niro''s performance is striking. The film itself is too bleak for me to enjoy.', null);  # 326155 Taxi Driver 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56304, 4, 'Noam-Barkai', 'Scorsese always loses me with these long crime dramas. Heavy, long, not for me.', null);  # 56304 Casino 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (123849, 4, 'Noam-Barkai', 'Drags on forever. Only the central performance kept me there.', null);  # 123849 Gangs of New York 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131780, 4, 'Noam-Barkai', 'A few memorable scenes. Scorsese''s mob style is just not for me.', null);  # 131780 Goodfellas 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (25192, 4, 'Noam-Barkai', 'Three hours of DiCaprio''s slow descent. Hard to sit through despite the strong performance.', null);  # 25192 Aviator, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (67388, 6, 'Noam-Barkai', 'More accessible than most Scorsese films. A pool drama with heart.', null);  # 67388 Color of Money, The 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (54209, 4, 'Noam-Barkai', 'Genuinely scary, not in a fun way. Not something I would revisit.', null);  # 54209 Cape Fear 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (165961, 6, 'Noam-Barkai', 'Spielberg hiding the shark is what makes it work. Clever tension throughout.', null);  # 165961 Jaws 1975
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (289109, 5, 'Noam-Barkai', 'Unforgettable opening sequence. The rest is hard to revisit.', null);  # 289109 Saving Private Ryan 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (39551, 4, 'Noam-Barkai', 'Ridley Scott''s camera never lets up. Exhausting more than enjoyable.', null);  # 39551 Black Hawk Down 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (359297, 4, 'Noam-Barkai', 'Tense and well shot but the ending falls completely flat.', null);  # 359297 War of the Worlds 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (158999, 6, 'Noam-Barkai', 'Cheesy in the best 90s way. Commits to being a blockbuster.', null);  # 158999 Independence Day 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (21213, 4, 'Noam-Barkai', 'Looks beautiful but the third act lost me completely.', null);  # 21213 Artificial Intelligence: AI 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (65811, 4, 'Noam-Barkai', 'A few memorable scenes. Mostly very slow.', null);  # 65811 Close Encounters of the Third Kind 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (100130, 4, 'Noam-Barkai', 'Strong child lead. The film overstays its welcome by an hour.', null);  # 100130 Empire of the Sun 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (12744, 4, 'Noam-Barkai', 'Forgettable. Could not tell you what happens in it now.', null);  # 12744 Always 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (290070, 6, 'Noam-Barkai', 'Important and beautifully shot in black and white. Also a very heavy, very long sit.', null);  # 290070 Schindler's List 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46169, 5, 'Noam-Barkai', 'Famous speech aside, three hours of medieval war is a lot.', null);  # 46169 Braveheart 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (340652, 6, 'Noam-Barkai', 'Strong central performance and a memorable duel. Long but engaging.', null);  # 340652 Troy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185628, 6, 'Noam-Barkai', 'More emotional than I expected. A touch too long.', null);  # 185628 Last Samurai, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (129185, 5, 'Noam-Barkai', 'Solid spectacle and a strong Crowe performance. The ending feels stretched.', null);  # 129185 Gladiator 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (112290, 6, 'Noam-Barkai', 'A clever Fincher twist. I admire it more than I actually enjoy it.', null);  # 112290 Fight Club 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210511, 6, 'Noam-Barkai', 'Color and black and white separate the timelines, very clever. Demanding to follow but worth it.', null);  # 210511 Memento 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (291698, 4, 'Noam-Barkai', 'Fincher does atmosphere brilliantly. The film is just too bleak for me though.', null);  # 291698 Se7en 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (123435, 6, 'Noam-Barkai', 'Fincher mystery thriller. The twist mostly works.', null);  # 123435 Game, The 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (247579, 6, 'Noam-Barkai', 'A tight Fincher thriller in a confined space.', null);  # 247579 Panic Room 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (292671, 5, 'Noam-Barkai', 'A decent Stephen King adaptation, nothing more.', null);  # 292671 Secret Window 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210739, 7, 'Noam-Barkai', 'Great buddy chemistry. The alien plot is just an excuse for that.', null);  # 210739 Men in Black 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (40199, 4, 'Noam-Barkai', 'Drags throughout. The visuals are the only thing keeping it watchable.', null);  # 40199 Blade Runner 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (214755, 6, 'Noam-Barkai', 'The precognition premise is well used. Solid science fiction.', null);  # 214755 Minority Report 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (97360, 4, 'Noam-Barkai', 'Slow biopic that did not pull me in.', null);  # 97360 Ed Wood 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (233058, 5, 'Noam-Barkai', 'Atmospheric occult mystery. The ending falls completely flat.', null);  # 233058 Ninth Gate, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (240327, 5, 'Noam-Barkai', 'Only the photo death scene really stands out. Otherwise dated.', null);  # 240327 Omen, The 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (259826, 5, 'Noam-Barkai', 'Only the TV static scene really sticks. The rest is forgettable.', null);  # 259826 Poltergeist 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (14132, 7, 'Noam-Barkai', 'More of the same as the first. The cast still works together.', null);  # 14132 American Pie 2 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (14157, 7, 'Noam-Barkai', 'Nostalgic and still funny. Nice to see the original cast back together.', null);  # 14157 American Reunion, An 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312150, 7, 'Noam-Barkai', 'Surprisingly fun kid spy movie. Holds up better than expected.', null);  # 312150 Spy Kids 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312151, 7, 'Noam-Barkai', 'An improvement on the first in places. The creatures are great.', null);  # 312151 Spy Kids 2: Island of Lost Dreams 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312152, 4, 'Noam-Barkai', 'The 3D gimmick ruined this one. Only for younger viewers.', null);  # 312152 Spy Kids 3-D: Game Over 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238072, 8, 'Noam-Barkai', 'Stylish heist film with a strong ensemble. Always easy to rewatch.', null);  # 238072 Ocean's Eleven 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238073, 5, 'Noam-Barkai', 'Nowhere near as tight as the first. A few good moments aside.', null);  # 238073 Ocean's Twelve 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (319602, 6, 'Noam-Barkai', 'Sets the standard for superhero films. A solid origin story.', null);  # 319602 Superman 1978
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (319613, 6, 'Noam-Barkai', 'Decent sequel, mainly thanks to strong villains.', null);  # 319613 Superman II 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30955, 6, 'Noam-Barkai', 'Atmospheric and dark. Important entry in the superhero genre.', null);  # 30955 Batman 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30967, 4, 'Noam-Barkai', 'Only the villain is worth watching. The rest is a mess.', null);  # 30967 Batman Returns 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30965, 4, 'Noam-Barkai', 'Too cartoonish. A real drop in quality from what came before.', null);  # 30965 Batman Forever 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30952, 2, 'Noam-Barkai', 'A real mess. Hard to watch from start to finish.', null);  # 30952 Batman & Robin 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30959, 7, 'Noam-Barkai', 'A reset for the series that actually works. Grounded and well done.', null);  # 30959 Batman Begins 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30976, 7, 'Noam-Barkai', 'One of the stronger animated Batman films. A shame it is underseen.', null);  # 30976 Batman: Mask of the Phantasm 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335835, 6, 'Noam-Barkai', 'Sillier than I remembered. The flight scenes hold up.', null);  # 335835 Top Gun 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (109421, 4, 'Noam-Barkai', 'Where the franchise started. Loud and shallow, not for me.', null);  # 109421 Fast and the Furious, The 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10920, 4, 'Noam-Barkai', 'The action is fine. No urge to revisit it.', null);  # 10920 Aliens 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10830, 4, 'Noam-Barkai', 'Too tense to enjoy. Cannot rewatch.', null);  # 10830 Alien 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (350424, 4, 'Noam-Barkai', 'Lost me by the end. Pretentious in a way I did not connect with.', null);  # 350424 Vanilla Sky 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (33492, 8, 'Noam-Barkai', 'A small German film about grief and food. Quiet and lovely.', null);  # 33492 Bella Martha 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (160524, 4, 'Noam-Barkai', 'Slow and dull. The setting is more interesting than the story.', null);  # 160524 Insomnia 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (69812, 6, 'Noam-Barkai', 'A 90s thriller that holds up better than expected.', null);  # 69812 Conspiracy Theory 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (8183, 4, 'Noam-Barkai', 'Pretty to look at, but I felt nothing watching it.', null);  # 8183 Age of Innocence, The 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (7842, 6, 'Noam-Barkai', 'A cascade of disasters in one New York night. Niche but well done.', null);  # 7842 After Hours 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (177369, 4, 'Noam-Barkai', 'Intentionally uncomfortable. I did not enjoy sitting through it.', null);  # 177369 King of Comedy, The 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185704, 2, 'Noam-Barkai', 'Slow, heavy and not for me. Could not finish it a second time.', null);  # 185704 Last Temptation of Christ, The 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (200521, 4, 'Noam-Barkai', 'Way too long. The frog scene completely lost me.', null);  # 200521 Magnolia 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (118367, 5, 'Noam-Barkai', 'Anthology of four directors in one hotel. Mostly weak, the last segment is the best.', null);  # 118367 Four Rooms 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (235615, 6, 'Noam-Barkai', 'Tom Hanks in early dramatic mode. More substantial than I expected from the premise.', null);  # 235615 Nothing in Common 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (257744, 7, 'Noam-Barkai', 'Multiple romance storylines handled with real heart. Bittersweet and good.', null);  # 257744 Playing by Heart 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (336445, 2, 'Noam-Barkai', 'Bleak and depressing. Did not work for me at all.', null);  # 336445 Total Eclipse 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (74259, 4, 'Noam-Barkai', 'A 50s greaser musical. Weird and not really my thing.', null);  # 74259 Cry-Baby 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120506, 6, 'Noam-Barkai', 'A Victorian Jack the Ripper mystery. Well shot and atmospheric.', null);  # 120506 From Hell 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (174953, 8, 'Noam-Barkai', 'Strong early Miyazaki with great environmental themes.', null);  # 174953 Kaze no tani no Naushika 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218219, 8, 'Noam-Barkai', 'One of Miyazaki''s strongest. Intense and beautiful all the way through.', null);  # 218219 Mononoke-hime 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (395271, 4, 'Noam-Barkai', 'Very dated humor. Hard to watch now.', null);  # 395271 Laverne & Shirley 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (391006, 4, 'Noam-Barkai', 'Easy background sitcom. Nothing memorable.', null);  # 391006 Happy Days 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (398232, 4, 'Noam-Barkai', 'Only the lead character is worth tuning in for. Everything else is weak.', null);  # 398232 Mork & Mindy 1978
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (398571, 5, 'Noam-Barkai', 'Strong lead. The writing around her is uneven and dated.', null);  # 398571 Murphy Brown 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (400853, 7, 'Noam-Barkai', 'A balanced family drama with a strong ensemble.', null);  # 400853 Parenthood 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (390691, 6, 'Noam-Barkai', 'Comfort sitcom. Holds up better than other shows from the same period.', null);  # 390691 Growing Pains 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (381392, 7, 'Noam-Barkai', 'Underrated animated series. The future Gotham setting is well done.', null);  # 381392 Batman Beyond 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30961, 7, 'Noam-Barkai', 'Darker than expected for an animated film. Surprisingly well done.', null);  # 30961 Batman Beyond: Return of the Joker (2000/I) 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30962, 6, 'Noam-Barkai', 'A solid setup for the new Batman character.', null);  # 30962 Batman Beyond: The Movie 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (406411, 6, 'Noam-Barkai', 'Sharper than the prequel films. Strong animation.', null);  # 406411 Star Wars: Clone Wars 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (406158, 5, 'Noam-Barkai', 'Standard animated series. Nothing special.', null);  # 406158 Spider-Man 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (379327, 5, 'Noam-Barkai', 'Has the charm of older TV. A simple Robin Hood take, nothing more.', null);  # 379327 Adventures of Robin Hood, The 1955
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (379331, 6, 'Noam-Barkai', 'Considered the definitive Sherlock adaptation for good reason.', null);  # 379331 Adventures of Sherlock Holmes, The 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (231917, 5, 'Noam-Barkai', 'Anthology horror. Similar in tone to The Twilight Zone but less memorable.', null);  # 231917 Night Gallery 1969
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (399427, 5, 'Noam-Barkai', 'More of the same anthology format. Fine.', null);  # 399427 Night Gallery 1970
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (183370, 7, 'Noam-Barkai', 'A small English seaside drama with Maggie Smith and Judi Dench. Quietly beautiful.', null);  # 183370 Ladies in Lavender 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (39829, 4, 'Noam-Barkai', 'Style over substance. The plot did nothing for me.', null);  # 39829 Black Rain 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (270628, 6, 'Noam-Barkai', 'A difficult subject handled with an unusual fantasy framing.', null);  # 270628 Radio Flyer 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (253010, 6, 'Noam-Barkai', 'A quieter drama. Slow but considered, with some real moments.', null);  # 253010 Perfect World, A 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (67395, 6, 'Noam-Barkai', 'Important drama with strong performances. Also a very long sit.', null);  # 67395 Color Purple, The 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30686, 4, 'Noam-Barkai', 'Heavy addiction drama. Bleak more than affecting.', null);  # 30686 Basketball Diaries, The 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (330670, 6, 'Noam-Barkai', 'An intense small drama about a difficult stepfather.', null);  # 330670 This Boy's Life 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (306032, 6, 'Noam-Barkai', 'A fast paced crime comedy. Easier to follow than other films of its kind.', null);  # 306032 Snatch. 2000
