insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (397121, 8, 'Liam', 'visually ahead of its time, completely changed action filmmaking', null);  # 397121 Matrix 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (644, 7, 'Liam', 'sharp wit and great chemistry between the leads', null);  # 644 10 Things I Hate About You 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (1038, 6, 'Liam', 'lighthearted and fun, Jennifer Garner carries it well', null);  # 1038 13 Going On 30 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10830, 9, 'Liam', 'masterclass in slow-burn tension, Ridley Scott at his best', null);  # 10830 Alien 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (14132, 8, 'Liam', 'funnier than the original with solid comedic timing', null);  # 14132 American Pie 2 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30959, 10, 'Liam', 'Nolan redefined the genre with a grounded and serious tone', null);  # 30959 Batman Begins 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30965, 9, 'Liam', 'Val Kilmer brings style and edge to the role', null);  # 30965 Batman Forever 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30967, 9, 'Liam', 'Michael Keaton is perfectly cast, dark and entertaining', null);  # 30967 Batman Returns 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (34077, 8, 'Liam', 'sweeping and melancholic, Pitt delivers a career performance', null);  # 34077 Benjamin Button 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (39551, 9, 'Liam', 'brutally realistic war film, Ridley Scott does not flinch', null);  # 39551 Black Hawk Down 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (40199, 10, 'Liam', 'dystopian sci-fi that still feels relevant decades later', null);  # 40199 Blade Runner 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56304, 9, 'Liam', 'Scorsese and De Niro at peak power, a crime epic', null);  # 56304 Casino 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56871, 10, 'Liam', 'DiCaprio is magnetic, clever and endlessly rewatchable', null);  # 56871 Catch Me If You Can 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (59578, 7, 'Liam', 'Tim Burton adds a quirky darkness that elevates the source material', null);  # 59578 Charlie and the Chocolate Factory 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (66194, 8, 'Liam', 'sharp satire of high school social hierarchies, still quotable', null);  # 66194 Clueless 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (86263, 7, 'Liam', 'classic Bond formula, fun but not among the best entries', null);  # 86263 Die Another Day 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (92573, 10, 'Liam', 'Sean Connery defines the spy archetype here', null);  # 92573 Dr. No 1962
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (97727, 8, 'Liam', 'visually poetic and emotionally resonant Tim Burton film', null);  # 97727 Edward Scissorhands 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (109421, 9, 'Liam', 'high-energy racing action before the franchise lost its way', null);  # 109421 Fast and the Furious, The 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (112290, 10, 'Liam', 'the twist is earned and the social commentary cuts deep', null);  # 112290 Fight Club 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (123849, 8, 'Liam', 'DiCaprio and Day-Lewis in the same film is electric', null);  # 123849 Gangs of New York 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130953, 9, 'Liam', 'Goldfinger set the gold standard for Bond villains', null);  # 130953 Goldfinger 1964
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131780, 10, 'Liam', 'Scorsese crime epic with an unforgettable ensemble cast', null);  # 131780 Goodfellas 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131885, 7, 'Liam', 'pure adventure spirit, fun for every age', null);  # 131885 Goonies, The 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139650, 8, 'Liam', 'the Chamber of Secrets expands the world with darker themes', null);  # 139650 Harry Potter and the Chamber of Secrets 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139652, 9, 'Liam', 'the tournament format raises the stakes dramatically', null);  # 139652 Harry Potter and the Goblet of Fire 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139653, 8, 'Liam', 'visually rich and emotionally heavy, the series matures here', null);  # 139653 Harry Potter and the Half-Blood Prince 2008
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139654, 8, 'Liam', 'longest and most political entry, still compelling', null);  # 139654 Harry Potter and the Order of the Phoenix 2007
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139655, 10, 'Liam', 'Cuaron brings a cinematic boldness that transforms the franchise', null);  # 139655 Harry Potter and the Prisoner of Azkaban 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139657, 10, 'Liam', 'perfectly introduces a world that feels real and magical', null);  # 139657 Harry Potter and the Sorcerers Stone 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (142491, 7, 'Liam', 'Del Toro brings warmth and humor to an unlikely hero', null);  # 142491 Hellboy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (158999, 8, 'Liam', 'spectacular set pieces and Will Smith at his charismatic peak', null);  # 158999 Independence Day 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159172, 9, 'Liam', 'father-son dynamic adds emotional weight to the adventure', null);  # 159172 Indiana Jones and the Last Crusade 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159175, 8, 'Liam', 'darker and more intense, the temple sequences are unforgettable', null);  # 159175 Indiana Jones and the Temple of Doom 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159665, 10, 'Liam', 'Tarantino at full power, the dialogue and tension are extraordinary', null);  # 159665 Inglorious Bastards 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (160524, 7, 'Liam', 'Nolan uses sleep deprivation as a thriller device brilliantly', null);  # 160524 Insomnia 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (162380, 9, 'Liam', 'Downey Jr makes Tony Stark feel effortlessly real', null);  # 162380 Iron Man 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (165961, 8, 'Liam', 'Spielberg builds dread masterfully before you see anything', null);  # 165961 Jaws 1975
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176711, 9, 'Liam', 'stylized revenge thriller with incredible fight choreography', null);  # 176711 Kill Bill Vol. 1 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176712, 9, 'Liam', 'the slower pace lets the characters breathe and deepen', null);  # 176712 Kill Bill Vol. 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185628, 8, 'Liam', 'Tom Cruise fully commits to the cultural immersion', null);  # 185628 Last Samurai, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (189403, 8, 'Liam', 'Timothy Dalton brings a grittier edge to the Bond character', null);  # 189403 Licence to Kill 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194497, 9, 'Liam', 'Jackson creates a world that feels completely lived in', null);  # 194497 Lord of the Rings The Fellowship of the Ring 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194500, 10, 'Liam', 'the final battle and emotional payoff are unmatched in fantasy cinema', null);  # 194500 Lord of the Rings The Return of the King 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194502, 9, 'Liam', 'Helms Deep sequence alone makes this one of cinema best action sequences', null);  # 194502 Lord of the Rings The Two Towers 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210511, 8, 'Liam', 'Nolan uses memory as both plot and theme with precision', null);  # 210511 Memento 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210739, 7, 'Liam', 'Smith and Jones have natural buddy-cop chemistry', null);  # 210739 Men in Black 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215876, 7, 'Liam', 'De Palma direction makes the vault scene iconic', null);  # 215876 Mission Impossible 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215879, 6, 'Liam', 'John Woo style overwhelms the plot at times', null);  # 215879 Mission Impossible II 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215880, 8, 'Liam', 'Abrams brings emotional stakes back to the franchise', null);  # 215880 Mission Impossible III 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (220805, 7, 'Liam', 'Pitt and Jolie spark off each other in an entertaining way', null);  # 220805 Mr. and Mrs. Smith 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238072, 10, 'Liam', 'Soderbergh assembled a dream cast and let them shine', null);  # 238072 Oceans Eleven 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238073, 6, 'Liam', 'weaker sequel that loses the original tightness', null);  # 238073 Oceans Twelve 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256631, 10, 'Liam', 'expands the world and Davy Jones is a phenomenal villain', null);  # 256631 Pirates of the Caribbean 2 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256632, 10, 'Liam', 'Depp creates one of cinema most iconic characters from scratch', null);  # 256632 Pirates of the Caribbean Curse of the Black Pearl 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (263360, 7, 'Liam', 'Roberts is magnetic and the chemistry feels genuine', null);  # 263360 Pretty Woman 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (267038, 10, 'Liam', 'nonlinear storytelling that rewards multiple viewings', null);  # 267038 Pulp Fiction 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (270971, 8, 'Liam', 'raw and uncompromising, De Niro physically transformed', null);  # 270971 Raging Bull 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (271095, 9, 'Liam', 'the boulder scene alone cemented its place in cinema history', null);  # 271095 Raiders of the Lost Ark 1981
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (276217, 9, 'Liam', 'dialogue-driven crime film with a tightly wound structure', null);  # 276217 Reservoir Dogs 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280270, 8, 'Liam', 'Stallone wrote and starred in the ultimate underdog story', null);  # 280270 Rocky 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280281, 7, 'Liam', 'solid continuation that keeps the emotional core intact', null);  # 280281 Rocky II 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280282, 7, 'Liam', 'Mr. T as Clubber Lang is an entertaining villain', null);  # 280282 Rocky III 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280284, 8, 'Liam', 'the training montage in the snow is genuinely motivating', null);  # 280284 Rocky IV 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280305, 5, 'Liam', 'loses the magic of the earlier entries, feels directionless', null);  # 280305 Rocky V 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (289109, 9, 'Liam', 'the Omaha Beach opening is the most harrowing war sequence filmed', null);  # 289109 Saving Private Ryan 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (291698, 9, 'Liam', 'Fincher and Pitt create unbearable tension throughout', null);  # 291698 Se7en 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (297838, 10, 'Liam', 'Freeman narration and Robbins performance are both flawless', null);  # 297838 Shawshank Redemption, The 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300229, 7, 'Liam', 'works on multiple levels for kids and adults simultaneously', null);  # 300229 Shrek 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300230, 7, 'Liam', 'raises the humor bar of the original with great new characters', null);  # 300230 Shrek 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311037, 8, 'Liam', 'Raimi captures the youthful energy of Peter Parker perfectly', null);  # 311037 Spider-Man 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311038, 8, 'Liam', 'Doc Ock is one of the best superhero villains ever written', null);  # 311038 Spider-Man 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313474, 5, 'Liam', 'Darth Maul is underused and the midichlorian plot kills the mystery', null);  # 313474 Star Wars Episode I 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313476, 5, 'Liam', 'the Anakin romance dialogue is painfully written', null);  # 313476 Star Wars Episode II 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313477, 7, 'Liam', 'the Anakin fall to the dark side is finally compelling', null);  # 313477 Star Wars Episode III 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313478, 10, 'Liam', 'Empire is the rare sequel that surpasses its predecessor in every way', null);  # 313478 Star Wars Episode V 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313479, 8, 'Liam', 'emotionally satisfying conclusion to the original trilogy', null);  # 313479 Star Wars Episode VI 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (326155, 9, 'Liam', 'De Niro builds a character that is both terrifying and pitiable', null);  # 326155 Taxi Driver 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (333856, 9, 'Liam', 'Cameron balances spectacle and romance without sacrificing either', null);  # 333856 Titanic 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335835, 9, 'Liam', 'the aerial sequences are thrilling and the soundtrack is iconic', null);  # 335835 Top Gun 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (337166, 10, 'Liam', 'Pixar invented a new language of animation and emotion simultaneously', null);  # 337166 Toy Story 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (340901, 9, 'Liam', 'Carrey plays against type and delivers his best dramatic performance', null);  # 340901 Truman Show, The 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (45128, 10, 'Liam', 'Damon reinvents the spy thriller with raw physicality', null);  # 45128 Bourne Identity, The 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (235541, 8, 'Liam', 'the story within a story structure adds genuine emotional depth', null);  # 235541 Notebook, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46169, 8, 'Liam', 'Gibson directs with sweeping ambition and visceral battle scenes', null);  # 46169 Braveheart 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130128, 9, 'Liam', 'Brando and Pacino command the screen in every shared moment', null);  # 130128 Godfather, The 1972
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (18960, 10, 'Liam', 'Coppola captures the psychological disintegration of war', null);  # 18960 Apocalypse Now 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (158927, 9, 'Liam', 'family dynamics and superhero action blend in a fresh way', null);  # 158927 Incredibles, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (289558, 9, 'Liam', 'Pacino is mesmerizing in every frame of this crime saga', null);  # 289558 Scarface 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (299073, 8, 'Liam', 'Kubrick uses space and silence to create psychological horror', null);  # 299073 Shining, The 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (37178, 7, 'Liam', 'the Dude is one of cinema most effortlessly likeable characters', null);  # 37178 Big Lebowski, The 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (45129, 10, 'Liam', 'Greengrass shaky cam style creates genuine thriller urgency', null);  # 45129 Bourne Supremacy, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (90772, 9, 'Liam', 'layers of mystery that reveal themselves differently on each rewatch', null);  # 90772 Donnie Darko
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (66286, 10, 'Liam', 'Carter speech in the locker room is one of the best sports movie scenes', null);  # 66286 Coach Carter 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (254986, 9, 'Liam', 'Polanski and Brody create a quietly devastating portrait of survival', null);  # 254986 Pianist, The 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (340652, 9, 'Liam', 'Pitt as Achilles brings physicality and arrogance perfectly', null);  # 340652 Troy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (14145, 10, 'Liam', 'Bale walks a razor thin line between satire and horror', null);  # 14145 American Psycho 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (32114, 9, 'Liam', 'Russell Crowe shows the human cost of mathematical genius', null);  # 32114 Beautiful Mind, A 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (113504, 10, 'Liam', 'the father-son search is emotionally devastating in all the right ways', null);  # 113504 Finding Nemo 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (86274, 9, 'Liam', 'Willis creates the definitive reluctant action hero under pressure', null);  # 86274 Die Hard 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (65764, 9, 'Liam', 'Kubrick challenges the audience in ways most directors avoid', null);  # 65764 Clockwork Orange, A 1971
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (191246, 10, 'Liam', 'the villain arc and the circle of life theme are timeless', null);  # 191246 Lion King, The 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (291221, 6, 'Liam', 'clever meta-horror but relies too heavily on self-reference', null);  # 291221 Scream 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (272644, 9, 'Liam', 'Remy is one of Pixar most loveable and determined protagonists', null);  # 272644 Ratatouille 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (121538, 10, 'Liam', 'the two-act structure creates a tonal shift that stays with you', null);  # 121538 Full Metal Jacket 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (129185, 9, 'Liam', 'Crowe and Phoenix elevate what could have been pure spectacle', null);  # 129185 Gladiator 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (26844, 8, 'Liam', 'time travel logic is actually internally consistent here', null);  # 26844 Back to the Future 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (301540, 10, 'Liam', 'Hopkins creates the most chilling villain with the least screen time', null);  # 301540 Silence of the Lambs, The 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131665, 9, 'Liam', 'Williams and Damon have one of cinema greatest mentor exchanges', null);  # 131665 Good Will Hunting 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (141544, 9, 'Liam', 'De Niro and Pacino finally share the screen and it lives up to the hype', null);  # 141544 Heat 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (969, 10, 'Liam', 'a single room and twelve men and it never loses tension for a second', null);  # 969 12 Angry Men 1957
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (134077, 9, 'Liam', 'Michael Clarke Duncan and Tom Hanks create genuine on-screen warmth', null);  # 134077 Green Mile, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (276085, 4, 'Liam', 'relentlessly bleak with no emotional relief offered to the viewer', null);  # 276085 Requiem for a Dream 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (336458, 9, 'Liam', 'Schwarzenegger and the concept alone make this rewatchable', null);  # 336458 Total Recall 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (173933, 9, 'Liam', 'the underdog arc and mentor bond feel genuinely earned', null);  # 173933 Karate Kid, The 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (2238, 7, 'Liam', 'visually striking stylization compensates for thin character writing', null);  # 2238 300 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (302329, 8, 'Liam', 'Rodriguez and Miller create a visual language unlike anything else', null);  # 302329 Sin City 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (310726, 8, 'Liam', 'a single vehicle and a ticking clock create relentless momentum', null);  # 310726 Speed 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (148200, 9, 'Liam', 'McCallister is the perfect child protagonist for this kind of chaos', null);  # 148200 Home Alone 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (337814, 9, 'Liam', 'Washington and Hawke create a morally complex power dynamic', null);  # 337814 Training Day 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (369458, 9, 'Liam', 'the mutant metaphor for social exclusion lands with real weight', null);  # 369458 X-Men 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218415, 10, 'Liam', 'Pixar proves monsters can carry a laugh-out-loud comedy', null);  # 218415 Monsters Inc 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (26847, 7, 'Liam', 'the western setting refreshes a concept that could have felt tired', null);  # 26847 Back to the Future Part III 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (26846, 8, 'Liam', 'the 1955 within 1955 storytelling is genuinely clever', null);  # 26846 Back to the Future Part II 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (40187, 9, 'Liam', 'stylish action with Snipes commanding every fight sequence', null);  # 40187 Blade 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (166917, 9, 'Liam', 'Crowe is completely believable as a man learning what actually matters', null);  # 166917 Jerry Maguire 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (275453, 10, 'Liam', 'demonstrates how sport can dismantle prejudice when leadership is real', null);  # 275453 Remember the Titans 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (16006, 9, 'Liam', 'Ferrell commits to the absurdity completely and it pays off', null);  # 16006 Anchorman 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (177328, 7, 'Liam', 'Jackson brings real spectacle but the runtime tests patience', null);  # 177328 King Kong 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (289787, 9, 'Liam', 'Pacino commands every scene with quiet authority and charm', null);  # 289787 Scent of a Woman 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (155213, 10, 'Liam', 'the mammoth trio works immediately and never stops being funny', null);  # 155213 Ice Age 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (362808, 8, 'Liam', 'the friendship-to-romance arc is written with honesty and wit', null);  # 362808 When Harry Met Sally 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (18979, 9, 'Liam', 'based on a true story that demonstrates real heroism under failure', null);  # 18979 Apollo 13 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (80583, 9, 'Liam', 'Williams delivers one of the most inspiring teacher portrayals on film', null);  # 80583 Dead Poets Society 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120574, 9, 'Liam', 'the train fight sequence stands as one of Bond finest moments', null);  # 120574 From Russia with Love 1963
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (332065, 8, 'Liam', 'underwater action and a memorable villain make this a standout entry', null);  # 332065 Thunderball 1965
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (85871, 6, 'Liam', 'Connery phoning it in makes the whole film feel low-energy', null);  # 85871 Diamonds Are Forever 1971
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218808, 5, 'Liam', 'Bond in space abandons every grounded element that made the series work', null);  # 218808 Moonraker 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (1529, 9, 'Liam', 'the street racing sequences genuinely push adrenaline', null);  # 1529 2 Fast 2 Furious 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (117874, 10, 'Liam', 'Hanks carries four decades of emotion without ever feeling false', null);  # 117874 Forrest Gump 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (226939, 10, 'Liam', 'the comedy is so committed to its own stupidity it circles back to genius', null);  # 226939 Naked Gun 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (9125, 10, 'Liam', 'every single joke lands and the timing never misses once', null);  # 9125 Airplane! 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (111813, 10, 'Liam', 'Nicholson and Cruise face off in a courtroom scene for the ages', null);  # 111813 Few Good Men, A 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (209133, 6, 'Liam', 'sharp satire of high school social politics with strong comedic writing', null);  # 209133 Mean Girls 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (323813, 8, 'Liam', 'Damon plays charm and menace on the same face throughout', null);  # 323813 Talented Mr. Ripley, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (112205, 8, 'Liam', 'Besson packs so many ideas into this that it never slows down', null);  # 112205 Fifth Element, The 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (155070, 8, 'Liam', 'Will Smith elevates a standard action premise with real screen presence', null);  # 155070 I Robot 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (375827, 8, 'Liam', 'Stiller and Wilson playing it completely straight makes it funnier', null);  # 375827 Zoolander 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (279841, 8, 'Liam', 'satirizes corporate greed while delivering genuinely satisfying action', null);  # 279841 RoboCop 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (222339, 7, 'Liam', 'Brendan Fraser is perfectly cast as the charismatic adventurer', null);  # 222339 Mummy, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (258860, 7, 'Liam', 'Swayze and Reeves have an unlikely but effective on-screen bond', null);  # 258860 Point Break 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (163715, 9, 'Liam', 'the Mini Cooper chase is one of the most fun heist sequences filmed', null);  # 163715 Italian Job, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (50639, 7, 'Liam', 'Kutcher carries an ambitious sci-fi premise with surprising sincerity', null);  # 50639 Butterfly Effect, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (209591, 7, 'Liam', 'Brad Pitt plays death with a curiosity that is genuinely compelling', null);  # 209591 Meet Joe Black 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (223799, 8, 'Liam', 'Pesci and Tomei create one of the funniest courtroom double acts', null);  # 223799 My Cousin Vinny 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (87280, 8, 'Liam', 'the lift sequence is iconic and the chemistry between the leads is electric', null);  # 87280 Dirty Dancing 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (264146, 10, 'Liam', 'quotable from start to finish, the sword fight banter is legendary', null);  # 264146 Princess Bride, The 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (207157, 8, 'Liam', 'Jim Carrey builds on pure physical energy and it never gets old', null);  # 207157 Mask, The 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (63208, 10, 'Liam', 'the wardrobe sequence and Tilda Swinton as the White Witch are unforgettable', null);  # 63208 Chronicles of Narnia 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (235790, 7, 'Liam', 'Grant and Roberts have a natural, relaxed romantic chemistry', null);  # 235790 Notting Hill 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (151616, 8, 'Liam', 'the reverse psychology premise is clever and the leads execute it well', null);  # 151616 How to Lose a Guy in 10 Days 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (37002, 7, 'Liam', 'Sandler plays against type with unexpected warmth here', null);  # 37002 Big Daddy 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (2709, 8, 'Liam', 'the memory loss premise adds a genuinely emotional layer to the comedy', null);  # 2709 50 First Dates 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (138797, 7, 'Liam', 'Sandler leans fully into the absurdity and the crowd scenes are hilarious', null);  # 138797 Happy Gilmore 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (119358, 7, 'Liam', 'body swap premise executed with good comedic energy from both leads', null);  # 119358 Freaky Friday 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312150, 8, 'Liam', 'Rodriguez brings surprising imagination to a kids spy concept', null);  # 312150 Spy Kids 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (192514, 8, 'Liam', 'Roger Moore debut is livelier than expected with a distinct style', null);  # 192514 Live and Let Die 1973
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (203649, 6, 'Liam', 'entertaining but the villain is one of the weaker Bond antagonists', null);  # 203649 Man with the Golden Gun 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (240521, 6, 'Liam', 'Lazenby is underrated but the film never fully capitalizes on his potential', null);  # 240521 On Her Majesty Secret Service 1969
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (372233, 8, 'Liam', 'Connery at his most exotic, the Japan setting adds visual richness', null);  # 372233 You Only Live Twice 1967
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (117314, 8, 'Liam', 'stripped back Bond that prioritizes tension over gadgetry', null);  # 117314 For Your Eyes Only 1967
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (319602, 8, 'Liam', 'Reeve brings a sincerity to Superman that no one has matched since', null);  # 319602 Superman 1978
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (319613, 7, 'Liam', 'General Zod is an effective villain and the battles feel consequential', null);  # 319613 Superman II 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (328272, 6, 'Liam', 'Spielberg keeps it gentle but the concept deserved bolder execution', null);  # 328272 Terminal, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335336, 8, 'Liam', 'Brosnan brings a sleekness that suits the updated cold war premise', null);  # 335336 Tomorrow Never Dies 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (368418, 6, 'Liam', 'Brosnan is fine but the villain and plot are forgettable', null);  # 368418 World Is Not Enough 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (370017, 5, 'Liam', 'all spectacle and no character, the action wears thin quickly', null);  # 370017 XXX 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (309634, 7, 'Liam', 'Andrews is extraordinary and the songs are genuinely timeless', null);  # 309634 Sound of Music 1965
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (133401, 9, 'Liam', 'Travolta and Newton-John have chemistry that makes every song feel alive', null);  # 133401 Grease 1978
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (264158, 4, 'Liam', 'a charming concept that never takes any creative risks', null);  # 264158 Princess Diaries 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (187191, 6, 'Liam', 'Witherspoon is charismatic but the film coasts on her alone', null);  # 187191 Legally Blonde 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (108760, 5, 'Liam', 'the CGI looks cheap and the characters have no depth', null);  # 108760 Fantastic Four 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (363780, 2, 'Liam', 'the humor relies entirely on a premise that wears out in five minutes', null);  # 363780 White Chicks 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30647, 8, 'Liam', 'Verhoeven balances eroticism and thriller tension with confidence', null);  # 30647 Basic Instinct 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (289666, 8, 'Liam', 'smarter than it looks on the surface, the parody is actually well-crafted', null);  # 289666 Scary Movie 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (79716, 7, 'Liam', 'the visual scale is impressive even if the plot is thin', null);  # 79716 Day After Tomorrow 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (104699, 8, 'Liam', 'ridiculous premise executed with enough self-awareness to be genuinely funny', null);  # 104699 Eurotrip 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194123, 8, 'Liam', 'Sandler in a team sports setting works better than expected', null);  # 194123 Longest Yard, The 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (41849, 5, 'Liam', 'beautiful locations cannot compensate for the flat characterization', null);  # 41849 Blue Lagoon 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (248878, 5, 'Liam', 'the twin swap premise has been done better elsewhere', null);  # 248878 Parent Trap 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (195300, 7, 'Liam', 'the ensemble format gives each storyline just enough space', null);  # 195300 Love Actually 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (128350, 8, 'Liam', 'self-aware and surprisingly honest about its own genre conventions', null);  # 128350 Girl Next Door 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56373, 6, 'Liam', 'a warm family film that plays it too safe to be memorable', null);  # 56373 Casper 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (337167, 10, 'Liam', 'Woody and Buzz form one of animation greatest odd-couple friendships', null);  # 337167 Toy Story 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (337168, 9, 'Liam', 'the museum heist sequence and Zurg subplot elevate the original', null);  # 337168 Toy Story 2 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (199255, 8, 'Liam', 'the fish-out-of-water premise is simple and the comedic timing is sharp', null);  # 199255 Madagascar 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (55727, 8, 'Liam', 'Lightning McQueen arc from arrogance to humility is genuinely earned', null);  # 55727 Cars 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (359297, 7, 'Liam', 'Spielberg recreates Martian terror with real visual conviction', null);  # 359297 War of the Worlds 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312151, 7, 'Liam', 'entertaining sequel that adds imagination without losing the original charm', null);  # 312151 Spy Kids 2 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312152, 6, 'Liam', 'the 3D gimmick was fun in theatres but the story thins out noticeably', null);  # 312152 Spy Kids 3D 2003
