insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (276085, 10, 'GiliBarak', 'This movie is so upsetting and it really shocks your soul.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (289109, 10, 'GiliBarak', 'A brutal, unforgettable war picture; the opening Omaha Beach sequence is legendary.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (330388, 8, 'GiliBarak', 'A meditative, visually stunning meditation on war.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300230, 10, 'GiliBarak', 'I love this sequel. The funny songs make it a joy to watch.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300229, 7, 'GiliBarak', 'A very funny movie that makes fun of old stories in a cool way.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30959, 8, 'GiliBarak', 'The best way to show how Batman started. It feels real.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (207992, 9, 'GiliBarak', 'The techno music fits the digital world and action perfectly.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (18960, 9, 'GiliBarak', 'A hallucinatory descent into the heart of Vietnam.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (333856, 8, 'GiliBarak', 'A very sad love story. The moving flute music made me sad.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210511, 8, 'GiliBarak', 'The story moves backwards and it is very smart and unique.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (112290, 8, 'GiliBarak', 'A wild movie with a big surprise that makes you think.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (267038, 10, 'GiliBarak', 'The retro songs fit the cool vibe of the movie perfectly, most iconic Tarantino film.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131780, 9, 'GiliBarak', 'A great look at mob life. The period songs fit the era well.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (257459, 8, 'GiliBarak', 'Raw and unflinching combat through a young soldier''''s eyes.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (290070, 10, 'GiliBarak', 'A very sad story. The violin music is truly heartbreaking.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (337166, 9, 'GiliBarak', 'A classic that I loved as a kid and still enjoy today.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10830, 8, 'GiliBarak', 'A scary space movie. The silence makes it feel very lonely.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (141544, 9, 'GiliBarak', 'The diner scene alone is worth the whole movie.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10920, 8, 'GiliBarak', 'Action at its best and more exciting than the first one.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (297838, 10, 'GiliBarak', 'A beautiful story about having a real friend in prison.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (40199, 7, 'GiliBarak', 'The dark synth music fits this future city vibe perfectly.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46169, 9, 'GiliBarak', 'Big battles and a strong story about fighting for freedom.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335835, 8, 'GiliBarak', 'Fast planes and cool rock songs that make you feel the speed.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (326155, 7, 'GiliBarak', 'A dark story about a lonely man. The city feels very dirty.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159172, 9, 'GiliBarak', 'The adventure music and the jokes make this a perfect movie.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (271095, 8, 'GiliBarak', 'The trumpet theme is famous and makes scenes feel exciting.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313478, 9, 'GiliBarak', 'A great sequel with a big secret and iconic hero music.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313479, 8, 'GiliBarak', 'A satisfying ending to the original story with a lot of heart.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (49696, 9, 'GiliBarak', 'The whistling music in the desert makes this feel so cool.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188507, 8, 'GiliBarak', 'The saxophone music really fits the cool cop vibe of the eighties.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188509, 8, 'GiliBarak', 'A great action sequel that keeps the same high energy.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (301540, 10, 'GiliBarak', 'Hopkins is hypnotic; the tension never lets up.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139657, 7, 'GiliBarak', 'The magical music theme makes you feel like you are there.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (137655, 8, 'GiliBarak', 'The simple piano notes are so scary and iconic for horror.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139655, 8, 'GiliBarak', 'My favorite in the series. The style and the music are cool.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (191246, 10, 'GiliBarak', 'The opening song is one of the best moments in any cartoon.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (319602, 8, 'GiliBarak', 'The classic hero music makes you believe he can really fly.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (97727, 9, 'GiliBarak', 'A beautiful but sad story. The pretty music fits it well.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30955, 8, 'GiliBarak', 'A dark and cool Batman. The music by Danny Elfman is great.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (291698, 9, 'GiliBarak', 'A grim, relentless thriller with a devastating finale.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311038, 9, 'GiliBarak', 'The best Spider-Man movie. It shows the hard hero life.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130128, 9, 'GiliBarak', 'The classic slow music makes the whole story feel grand.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (348944, 9, 'GiliBarak', 'Twisty, stylish, and the ending still surprises on rewatches.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215876, 8, 'GiliBarak', 'A cool spy movie with a theme song that everyone knows.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256632, 9, 'GiliBarak', 'The pirate music is fun and makes the adventure better.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (129185, 10, 'GiliBarak', 'Epic scale, great score, and a career-defining performance.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (123435, 9, 'GiliBarak', 'A clever movie that keeps you guessing. Very tense and cool.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56304, 9, 'GiliBarak', 'A fast look at the bad side of Vegas with a cool soundtrack.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (96593, 9, 'GiliBarak', 'Spielberg at his most tender; still magical.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (82967, 9, 'GiliBarak', 'Scorsese''''s Boston crime epic; an ending nobody saw coming.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (65811, 10, 'GiliBarak', 'The five music notes are so famous and work perfectly.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (254986, 10, 'GiliBarak', 'The piano songs are beautiful and make the story sad.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (26844, 10, 'GiliBarak', 'A near-perfect blockbuster with wit and heart.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (186439, 10, 'GiliBarak', 'The desert theme music is grand and sounds amazing.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (121538, 9, 'GiliBarak', 'The rhythmic songs in the army scenes feel strong.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (70959, 8, 'GiliBarak', 'A dark but sweet story. The songs fit the style well.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (74259, 8, 'GiliBarak', 'A funny take on old movies. The music is high energy.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (106790, 9, 'GiliBarak', 'The slow violin soundtrack is beautiful and very sad.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (66194, 8, 'GiliBarak', 'A smart and funny look at school life. The songs are great.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (644, 8, 'GiliBarak', 'A fresh and fun version of an old story with good music.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313059, 9, 'GiliBarak', 'The friendship drama that defines coming-of-age.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (67395, 9, 'GiliBarak', 'The gospel songs make the story feel very emotional.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (299073, 9, 'GiliBarak', 'The weird high noises in the music make this movie creepy.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (62076, 9, 'GiliBarak', 'A perfect neo-noir with one of the great endings.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313459, 9, 'GiliBarak', 'The Imperial March is so cool and very scary for a movie.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (70248, 8, 'GiliBarak', 'Paranoia done with surgical precision.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (303564, 9, 'GiliBarak', 'A ghost story that earns its twist.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311040, 5, 'GiliBarak', 'Too many bad guys and the story felt a bit messy to me.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30952, 2, 'GiliBarak', 'This was just a bad movie. It felt like a joke gone wrong.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238073, 5, 'GiliBarak', 'It was okay but felt a bit too messy compared to the first.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (220805, 5, 'GiliBarak', 'Lots of action and shooting but the story was very simple.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188511, 6, 'GiliBarak', 'Still okay but there was too much going on in the story.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (149287, 6, 'GiliBarak', 'A different take on Peter Pan. It was a nice family movie.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (379290, 8, 'GiliBarak', 'A cool old Batman cartoon. It sounds just like the 60s.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (33179, 8, 'GiliBarak', 'Weird, wonderful, and hilariously unsettling.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (134672, 9, 'GiliBarak', 'Sweet, existential, and quietly profound.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (337830, 9, 'GiliBarak', 'Kinetic, ugly, funny — the 90s on film.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (113506, 9, 'GiliBarak', 'A very pretty movie about dreams and the Peter Pan creator.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (123849, 9, 'GiliBarak', 'The old city sounds and music make it feel very real.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185628, 9, 'GiliBarak', 'The Japanese flute music makes the battles look epic.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (220276, 9, 'GiliBarak', 'The songs are amazing. It is a very pretty movie to see.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280270, 10, 'GiliBarak', 'The trumpet music in the training is very famous and good.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (359297, 9, 'GiliBarak', 'The scary horn sound in the movie is very terrifying.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (372233, 8, 'GiliBarak', 'Bond in Japan. The soundtrack is actually very pretty.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (406411, 8, 'GiliBarak', 'The war sounds in the cartoons are very well done.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (1390, 7, 'GiliBarak', 'Spielberg''''s loud, chaotic WWII comedy.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (1038, 9, 'GiliBarak', 'The 80s songs are amazing in this very fun comedy.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (1121, 8, 'GiliBarak', 'The epic Vangelis music is just incredible to hear.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280281, 9, 'GiliBarak', 'The trumpet theme is still so strong and good here.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280282, 8, 'GiliBarak', 'The Eye of the Tiger song is just perfect for this.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (124554, 8, 'GiliBarak', 'Quiet sci-fi with big ideas about fate and choice.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311037, 8, 'GiliBarak', 'A good start for Spider-Man. It felt just like the comics.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (160524, 8, 'GiliBarak', 'A tense thriller where the sun never goes down. Cool.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (328277, 10, 'GiliBarak', 'Action filmmaking at its absolute peak.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (209158, 9, 'GiliBarak', 'A raw story about guys in a rough city. Good acting.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (328285, 9, 'GiliBarak', 'Lean, mean, and genre-defining.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (34104, 8, 'GiliBarak', 'A sweet and odd story about love. It has heart.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (304862, 8, 'GiliBarak', 'A dark scary story. The music makes it feel spooky.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (59578, 7, 'GiliBarak', 'A colorful candy factory. The songs are fun for kids.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139650, 8, 'GiliBarak', 'Darker and more exciting. The magic world looks great.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (350424, 7, 'GiliBarak', 'A strange story about dreams. The songs are very moody.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (86274, 10, 'GiliBarak', 'The template every action movie since has tried to copy.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238695, 9, 'GiliBarak', 'Mike Judge''''s workplace comedy that only gets funnier.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120506, 8, 'GiliBarak', 'A dark mystery set in old London. Very tense vibe.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (247579, 8, 'GiliBarak', 'A tense thriller in one house. The sound design is good.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (69812, 7, 'GiliBarak', 'A fun movie about secret plots and mystery. Exciting.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (181766, 8, 'GiliBarak', 'A very pretty movie that takes its time to tell the story.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185704, 8, 'GiliBarak', 'A bold story that really makes you think about things.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (328272, 8, 'GiliBarak', 'A nice story about a man stuck in an airport. Sweet.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (318388, 8, 'GiliBarak', 'A fast road movie with a lot of soul and heart.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (183873, 8, 'GiliBarak', 'A nice magic story from long ago. The vibe was good.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311428, 8, 'GiliBarak', 'A funny story with a lot of charm. The music is light.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (114955, 8, 'GiliBarak', 'A good story about growing up. It has a summer feeling.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (235615, 8, 'GiliBarak', 'A serious look at a family. The dialogue is well written.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (31715, 8, 'GiliBarak', 'A sad and beautiful story about friends over years.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (308025, 8, 'GiliBarak', 'A cool look for the city. It has a very tense feeling.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210739, 9, 'GiliBarak', 'Fun with cool aliens. The music makes it high energy.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (158999, 8, 'GiliBarak', 'A huge movie about aliens. The action is very big.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (14477, 8, 'GiliBarak', 'A tough and important story. The acting is powerful.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (330670, 8, 'GiliBarak', 'A real story with great acting. It feels grounded.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (118980, 8, 'GiliBarak', 'A sweet story with stars. The music is very nice.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (208245, 8, 'GiliBarak', 'A fast and fun western trip. The music is upbeat.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (379327, 9, 'GiliBarak', 'A classic adventure with very bright and fun colors.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311036, 7, 'GiliBarak', 'A cool hero cartoon. I liked the funny sound effects.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (18979, 9, 'GiliBarak', 'A gripping true story told with real craft.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (370017, 8, 'GiliBarak', 'High energy action. The rock music is very loud.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (158927, 9, 'GiliBarak', 'Superhero family drama that works on every level.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (113504, 9, 'GiliBarak', 'Gorgeous, funny, and surprisingly moving.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218415, 9, 'GiliBarak', 'Pixar at its most charming and inventive.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194874, 9, 'GiliBarak', 'Quiet, melancholy, and wonderfully acted.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (267165, 8, 'GiliBarak', 'Sandler in a role no one expected; it works.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (13789, 8, 'GiliBarak', 'Suburban disquiet captured with unusual clarity.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (222194, 9, 'GiliBarak', 'Lynch at his most hypnotic and baffling.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (32712, 9, 'GiliBarak', 'A whole romance in one walking conversation.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (32713, 9, 'GiliBarak', 'Even better than the original; real-time romance.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (35522, 8, 'GiliBarak', 'Eddie Murphy''''s charm carries a sharp action-comedy.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (239851, 9, 'GiliBarak', 'Shocking, stylish Korean revenge thriller.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300945, 8, 'GiliBarak', 'Wine country, midlife, and a genuinely human script.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (270971, 9, 'GiliBarak', 'De Niro committing to the role like few actors ever have.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (13978, 9, 'GiliBarak', 'Powerful, painful, and still relevant.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (37178, 9, 'GiliBarak', 'Shaggy, quotable, endlessly rewatchable.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (104338, 9, 'GiliBarak', 'Romance told backwards and sideways; emotionally brutal.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194818, 8, 'GiliBarak', 'Lynch noir that refuses to explain itself.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (306032, 9, 'GiliBarak', 'Fast, funny British crime caper with a killer ensemble.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (193253, 9, 'GiliBarak', 'Ritchie''''s debut; stylish crime comedy.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (276217, 10, 'GiliBarak', 'A warehouse, a heist gone wrong, and a soundtrack to die for.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176711, 9, 'GiliBarak', 'Pure Tarantino spectacle.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176712, 9, 'GiliBarak', 'The quieter, richer half of the story.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (7842, 9, 'GiliBarak', 'A wild night in the city. The jazz is cool.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (77701, 8, 'GiliBarak', 'Lars von Trier at his most emotionally ruthless.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (109093, 10, 'GiliBarak', 'Darkly funny, quietly devastating Coen classic.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280305, 5, 'GiliBarak', 'Not a great one. The music was okay though.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (41988, 9, 'GiliBarak', 'Lynch at his most unsettling and visually striking.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (271339, 8, 'GiliBarak', 'Coen brothers comedy at its warmest.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (299846, 8, 'GiliBarak', 'Altman weaving stories into a kaleidoscopic portrait.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (99075, 8, 'GiliBarak', 'Quiet, clinical, devastating.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218345, 8, 'GiliBarak', 'Charlize Theron disappears into the role.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (90772, 8, 'GiliBarak', 'Weird, dreamy, and instantly iconic.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (14942, 9, 'GiliBarak', 'Intersecting tragedies told with raw energy.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56044, 10, 'GiliBarak', 'Still the most romantic movie ever made.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (64729, 10, 'GiliBarak', 'The film that invented modern cinema.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (352639, 10, 'GiliBarak', 'Hitchcock''''s most hypnotic and haunting masterpiece.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (266574, 10, 'GiliBarak', 'The shower scene is only the beginning.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (235062, 9, 'GiliBarak', 'Hitchcock''''s perfect chase thriller.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (273543, 9, 'GiliBarak', 'A one-room thriller that never stops tightening.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (307913, 9, 'GiliBarak', 'Still the funniest film of its era.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (302696, 10, 'GiliBarak', 'A musical where every number is a showstopper.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130129, 10, 'GiliBarak', 'Expands and deepens the original in every way.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (367073, 10, 'GiliBarak', 'The original spectacle; still mesmerizing.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (1711, 10, 'GiliBarak', 'A cosmic trip nothing else has matched.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (92616, 10, 'GiliBarak', 'Kubrick''''s darkest, funniest satire.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (241347, 10, 'GiliBarak', 'Nicholson at the peak of his powers.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (165961, 10, 'GiliBarak', 'The original summer blockbuster, still terrifying.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (42056, 9, 'GiliBarak', 'A musical chase film with unbeatable energy.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (264146, 10, 'GiliBarak', 'Fairy-tale perfection from start to finish.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131885, 9, 'GiliBarak', 'The 80s adventure that lives on in every kid''''s memory.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (111442, 9, 'GiliBarak', 'The most charming truancy ever filmed.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46322, 9, 'GiliBarak', 'John Hughes at his sharpest.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (80583, 9, 'GiliBarak', 'Williams turns the teacher drama into something unforgettable.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (271192, 8, 'GiliBarak', 'Brother-road-movie with one of Hoffman''''s best performances.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (362808, 9, 'GiliBarak', 'The romantic comedy template every other tries to copy.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (117874, 9, 'GiliBarak', 'Sentimental in the best way; Hanks carries everything.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (77728, 8, 'GiliBarak', 'Sweeping revisionist western.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (271915, 9, 'GiliBarak', 'Kurosawa''''s devastating late masterpiece.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (371844, 9, 'GiliBarak', 'Kurosawa invents the lone-gunslinger archetype.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (241141, 9, 'GiliBarak', 'Leone''''s sprawling gangster epic.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (198435, 9, 'GiliBarak', 'Fritz Lang''''s serial-killer thriller still shocks.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (212097, 9, 'GiliBarak', 'Silent sci-fi that invented the genre.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312963, 9, 'GiliBarak', 'Tarkovsky''''s slow, haunting journey.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (253440, 9, 'GiliBarak', 'Bergman''''s most unsettling psychological study.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (202537, 9, 'GiliBarak', 'The noir that set the template for every detective film after.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (92573, 8, 'GiliBarak', 'The Bond film that started it all.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130953, 9, 'GiliBarak', 'Peak Connery-era Bond.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120574, 9, 'GiliBarak', 'Bond at his most cold-war spiky.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159175, 8, 'GiliBarak', 'Darker, weirder Indy sequel.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (309634, 9, 'GiliBarak', 'A musical landslide you can hum in your sleep.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (361688, 9, 'GiliBarak', 'Musical romance with some of the best dance ever filmed.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (223867, 8, 'GiliBarak', 'Stage-to-screen perfection.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (250861, 8, 'GiliBarak', 'Scott''''s portrait of war''''s most complicated general.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (7678, 8, 'GiliBarak', 'Bogart and Hepburn at their best.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139652, 8, 'GiliBarak', 'A grand tournament spectacle that raises the stakes and transitions the story into a more mature era.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256631, 8, 'GiliBarak', 'An energetic and fun sequel that manages to capture the same spirit as the original film.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238072, 8, 'GiliBarak', 'A stylish, breezy, and incredibly cool heist movie that is pure entertainment from start to finish.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56871, 9, 'GiliBarak', 'A charming and fast-paced true story about identity and pursuit that is perfectly acted.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312150, 7, 'GiliBarak', 'A fun and imaginative family spy movie that was full of gadgets and childhood wonder.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (33492, 8, 'GiliBarak', 'A gentle, atmospheric, and beautifully filmed European romance centered around food and connection.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (257744, 8, 'GiliBarak', 'A compelling ensemble drama that weaves together multiple stories of love and loss with sincerity.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (12744, 7, 'GiliBarak', 'A gentle and sentimental Spielberg story that focuses on the emotional side of memory and loss.', null);
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10702, 8, 'GiliBarak', 'A sincere and empowering look at a woman rebuilding her life on her own terms with grit and grace.', null);
