insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (644,8,'orizehavi-tech','A surprisingly sharp and clever high school adaptation of classic Shakespeare.',NULL); # 644 10 Things I Hate About You 1999
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (847,8,'orizehavi-tech','The sketchy art style perfectly fits this fun, fast-paced London rescue mission.',NULL); # 847 101 Dalmatians 1996
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (1029,8,'orizehavi-tech','Blends supernatural elements with romance seamlessly, creating a truly unique atmosphere.',NULL); # 1029 13 Erotic Ghosts 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (1711,10,'orizehavi-tech','Pioneered realistic space travel in cinema. The silence of space is used to terrifying effect.',NULL); # 1711 2001: A Space Odyssey 1968
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (2000,9,'orizehavi-tech','Revitalized the zombie genre completely by introducing terrifying, fast-moving infected.',NULL); # 2000 28 Days Later... 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (3638,8,'orizehavi-tech','Fast-paced, brightly colored, and heavily carried by its gospel-inspired musical numbers.',NULL); # 3638 A&E Biography: Charles Atlas - Modern Day Hercules 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (3825,7,'orizehavi-tech','Visually lush and features beautiful music, despite taking major historical liberties.',NULL); # 3825 A&E Biography: Pocahontas - Her True Story 1995
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (3891,9,'orizehavi-tech','A high-octane thrill ride featuring some of the best practical explosions of the decade.',NULL); # 3891 A&E Biography: The Rockefellers 1994
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (3896,8,'orizehavi-tech','A very sweet, funny, and incredibly well-crafted coming-of-age movie.',NULL); # 3896 A&E Biography: Theodore Roosevelt - Roughrider to Rushmore 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (5573,8,'orizehavi-tech','Peak 90s physical comedy. Ridiculous, over-the-top, and endlessly quotable.',NULL); # 5573 Ace Ventura: Pet Detective 1994
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (6954,8,'orizehavi-tech','The kinetic animation of moving through the jungle is matched perfectly by the percussion.',NULL); # 6954 Adventures of Chinese Tarzan, The 1940
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (6955,8,'orizehavi-tech','Defines the classic fairy tale aesthetic with elegant design and charm.',NULL); # 6955 Adventures of Cinderella's Daughter, The 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (7048,6,'orizehavi-tech','Cheesy and scientifically ridiculous, but the lava flows are visually entertaining.',NULL); # 7048 Adventures of Mary-Kate & Ashley: The Case of the Volcano Mystery, The 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (7132,8,'orizehavi-tech','Jim Carrey is an absolute cartoon character come to life in this hilarious comedy.',NULL); # 7132 Adventures of the Masked Phantom, The 1939
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (7929,9,'orizehavi-tech','A mind-bending, unpredictable puzzle that constantly pulls the rug out from under you.',NULL); # 7929 After the Game 1970
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (9023,8,'orizehavi-tech','A highly patriotic 90s action film that uses its claustrophobic setting perfectly.',NULL); # 9023 Air Force One 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (9125,9,'orizehavi-tech','A relentless barrage of visual gags and wordplay that never gives you a chance to breathe.',NULL); # 9125 Airplane! 1980
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (9795,9,'orizehavi-tech','The manic energy of the Genie elevates this classic to completely untocuhable heights.',NULL); # 9795 Aladdin 1992
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (10830,9,'orizehavi-tech','The ultimate haunted house movie set in space. The chest-burster scene is unforgettable.',NULL); # 10830 Alien 1979
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (10920,10,'orizehavi-tech','Shifts from horror to high-octane military action without losing a drop of tension.',NULL); # 10920 Aliens 1986
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (11022,8,'orizehavi-tech','A haunting and incredibly bleak true story that tests the absolute limits of human endurance.',NULL); # 11022 Alive 1993
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (12937,9,'orizehavi-tech','A vibrant, almost rock-and-roll approach to classical music history and bitter rivalry.',NULL); # 12937 Amadeus 1984
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (13789,9,'orizehavi-tech','A beautiful, melancholic masterpiece highlighting the quiet desperation of suburban life.',NULL); # 13789 American Beauty 1999
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (13978,9,'orizehavi-tech','A blistering, uncomfortable look at the roots of racism and the cycle of violence.',NULL); # 13978 American History X 1998
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (15196,9,'orizehavi-tech','Balances epic battle sequences with a very powerful story about honor and identity.',NULL); # 15196 Amulanga 1987
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (16006,9,'orizehavi-tech','A brilliant and highly satirical take on sensationalist news media and local broadcasting.',NULL); # 16006 Anchorman: The Legend of Ron Burgundy 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (18441,7,'orizehavi-tech','A slightly cynical, visually interesting take on conformity within an insect colony.',NULL); # 18441 Antz 1998
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (18544,8,'orizehavi-tech','Hyper-kinetic editing and aggressive sound design capture the brutal reality of football.',NULL); # 18544 Any Given Sunday 1999
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (18979,9,'orizehavi-tech','Turns complex orbital mechanics and engineering crises into an absolute nail-biter.',NULL); # 18979 Apollo 13 1995
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (19054,6,'orizehavi-tech','The narrative is secondary to the incredible vocal performances on the soundtrack.',NULL); # 19054 Appaneun bodyguard 1995
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (19067,9,'orizehavi-tech','The pacing is absolutely relentless in this perfectly crafted manhunt.',NULL); # 19067 Apparitions fugitives, Les 1904
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (20218,7,'orizehavi-tech','A very sweet, music-filled adventure that feels incredibly cozy and lighthearted.',NULL); # 20218 Aristocats, The 1970
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (20368,7,'orizehavi-tech','Melodramatic and loud, but undeniably effective at delivering massive destruction.',NULL); # 20368 Armageddon 1923
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (23339,8,'orizehavi-tech','The sound design alone makes the storms feel incredibly terrifying and real.',NULL); # 23339 Atomic Twister 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (24430,8,'orizehavi-tech','A colorful, completely ridiculous spoof that nails the aesthetics of 60s spy movies.',NULL); # 24430 Austin Powers: International Man of Mystery 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (26844,9,'orizehavi-tech','A flawless script that turns a simple time travel concept into a hilarious adventure.',NULL); # 26844 Back to the Future 1985
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (27132,8,'orizehavi-tech','Stylish, loud, and incredibly fast-paced, defining the modern buddy-cop formula.',NULL); # 27132 Bad Bad Boys 1974
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (27171,4,'orizehavi-tech','An overly long, bloated sequel that prioritizes explosions over character development.',NULL); # 27171 Bad Boys II 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (30647,8,'orizehavi-tech','A stylish, highly controversial thriller that thrives on manipulation and deceit.',NULL); # 30647 Basic Instinct 1992
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (30952,2,'orizehavi-tech','A neon-soaked disaster with painful dialogue and bizarre costume choices.',NULL); # 30952 Batman & Robin 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (30955,8,'orizehavi-tech','The dark, gothic architecture of Gotham is the real star of this classic adaptation.',NULL); # 30955 Batman 1989
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (30967,7,'orizehavi-tech','A surprisingly dark and ambitious superhero sequel under the guise of an action blockbuster.',NULL); # 30967 Batman Returns 1992
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (31183,8,'orizehavi-tech','Taps into early internet paranoia with a fun, fast-paced identity theft plot.',NULL); # 31183 Battle of the Network Stars 1976
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (32166,10,'orizehavi-tech','A flawless, magical romance that truly earns its classic status.',NULL); # 32166 Beauty and the Beast 1903
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (35523,7,'orizehavi-tech','A fast-paced follow-up that maintains the comedy but leans heavier into explosions.',NULL); # 35523 Beverly Hills Cop II 1987
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (35768,8,'orizehavi-tech','Features some fantastic set pieces even if it lacks the complete magic of the original.',NULL); # 35768 Beyond the Lost World: The Alien Conspiracy III 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (37178,9,'orizehavi-tech','A surreal, weed-fueled noir mystery that is entirely driven by bizarre character interactions.',NULL); # 37178 Big Lebowski, The 1998
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (39551,10,'orizehavi-tech','A visceral, documentary-style descent into the absolute chaos of modern urban warfare.',NULL); # 39551 Black Hawk Down 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (40187,8,'orizehavi-tech','A slick, stylized vampire hunter film that secretly laid the groundwork for modern Marvel.',NULL); # 40187 Blade 1998
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (40199,9,'orizehavi-tech','A visually breathtaking dive into what it means to be human in a dirty, neon future.',NULL); # 40199 Blade Runner 1982
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (41037,8,'orizehavi-tech','A gripping thriller fueled by pure desperation and intense negotiations.',NULL); # 41037 Blonde Ransom 1945
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (41409,8,'orizehavi-tech','The ultimate tournament fighting movie, completely carried by its incredible choreography.',NULL); # 41409 Bloodsport 1988
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (41739,7,'orizehavi-tech','A solid, gritty look at the corrupt underbelly of college athletic recruitment.',NULL); # 41739 Blue Chips 1994
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (42983,8,'orizehavi-tech','A high-energy critique of toxic finance bro culture and illegal stock manipulation.',NULL); # 42983 Boiler Room 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (44450,9,'orizehavi-tech','A harrowing, powerful, and deeply emotional look at the aftermath of war.',NULL); # 44450 Born on the Fourth of July 1989
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (46877,8,'orizehavi-tech','A highly relatable, funny, and deeply British take on modern dating struggles.',NULL); # 46877 Bridget Jones's Diary 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (48792,9,'orizehavi-tech','A scathing, visceral attack on consumerism and modern masculinity with a jaw-dropping twist.',NULL); # 48792 Buena Vista Fight Club 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (48950,8,'orizehavi-tech','A charming, miniature epic that uses its unique perspective to great comedic effect.',NULL); # 48950 Bug's Life, A 1998
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (50760,10,'orizehavi-tech','An emotionally exhausting and perfectly executed finale to the greatest fantasy epic.',NULL); # 50760 Buttsizer 3: Return of the King of Rears 1995
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (56304,9,'orizehavi-tech','A sweeping, violent epic detailing the meticulously organized mechanics of Vegas corruption.',NULL); # 56304 Casino 1995
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (56871,9,'orizehavi-tech','A breezy, incredibly fun chase movie that thrives on the charm of its lead con artist.',NULL); # 56871 Catch Me If You Can 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (58250,10,'orizehavi-tech','A masterclass in non-linear narrative, packed with the sharpest dialogue of the 90s.',NULL); # 58250 Cesk Pulp Fiction a Blair Witch 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (59470,8,'orizehavi-tech','An inspiring, synth-driven sports drama that focuses heavily on faith and determination.',NULL); # 59470 Chariots of Fire 1981
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (61291,8,'orizehavi-tech','A brilliantly executed claymation homage to classic POW escape films.',NULL); # 61291 Chicken Run 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (65501,8,'orizehavi-tech','A tense, slow-burn intelligence thriller filled with bureaucratic backstabbing.',NULL); # 65501 Clear and Present Danger 1994
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (65627,8,'orizehavi-tech','The dizzying heights and practical climbing stunts make this a very effective thriller.',NULL); # 65627 Cliffhanger 1993
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (65764,9,'orizehavi-tech','A bizarre, highly disturbing exploration of free will and behavioral conditioning in a dystopia.',NULL); # 65764 Clockwork Orange, A 1971
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (68940,8,'orizehavi-tech','Completely absurd premise held together by highly entertaining and chaotic set pieces.',NULL); # 68940 Con Air 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (70576,8,'orizehavi-tech','A highly effective serial killer procedural that uses the psychology of past killers well.',NULL); # 70576 Copycat Bat, The 1967
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (72430,8,'orizehavi-tech','Basically Die Hard on a battleship, and it works surprisingly well.',NULL); # 72430 Crack USA: County Under Siege 1989
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (73436,8,'orizehavi-tech','A masterclass in claustrophobic tension and the terrifying protocol of nuclear launch codes.',NULL); # 73436 Crimson Tide 1995
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (73913,8,'orizehavi-tech','A cold, calculating look at the casino floor from the perspective of a detached dealer.',NULL); # 73913 Croupier 1998
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (78530,7,'orizehavi-tech','Builds tension nicely before unleashing some very impressive practical volcano effects.',NULL); # 78530 Dante's Peak 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (78787,7,'orizehavi-tech','A bizarre, highly original sci-fi concept with excellent visual design and dark humor.',NULL); # 78787 Dark City 1950
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (79716,7,'orizehavi-tech','The scientific accuracy is questionable, but it delivers massive, enjoyable disaster set pieces.',NULL); # 79716 Day After Tomorrow, The 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (80354,8,'orizehavi-tech','Captures the essence of childhood imagination and adventurous escapism perfectly.',NULL); # 80354 De-as fi Peter Pan 1991
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (81776,7,'orizehavi-tech','Takes a slightly more thoughtful and grounded approach to the disaster formula.',NULL); # 81776 Deep Impact 1998
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (81954,6,'orizehavi-tech','A wildly ambitious post-apocalyptic setting that struggles slightly with its runtime.',NULL); # 81954 Deep Waterworld 1995
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (86274,9,'orizehavi-tech','An ordinary cop in an extraordinary situation makes for the tightest action script ever written.',NULL); # 86274 Die Hard 1988
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (87280,8,'orizehavi-tech','The choreography and soundtrack carry this classic romance beautifully.',NULL); # 87280 Dirty Dancing 1987
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (90771,9,'orizehavi-tech','A masterclass in tension, showing the severe psychological toll of deep undercover work.',NULL); # 90771 Donnie Brasco 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (90772,8,'orizehavi-tech','A moody, complex dive into teenage angst wrapped in a strange time-travel narrative.',NULL); # 90772 Donnie Darko 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (91763,8,'orizehavi-tech','A smart and highly satisfying thriller revolving around legal loopholes and revenge.',NULL); # 91763 Double Jeopardy 1955
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (93024,8,'orizehavi-tech','A gritty, melancholic survival story that is far deeper than its explosive sequels.',NULL); # 93024 Drawing First Blood 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (94958,9,'orizehavi-tech','A gripping, intense courtroom drama tackling incredibly heavy and uncomfortable themes.',NULL); # 94958 Duke Nukem: Time to Kill 1998
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (96590,8,'orizehavi-tech','A brilliant suburban sci-fi that touches the heart. The bicycle scene is pure magic.',NULL); # 96590 E.T. and Friends: Magical Movie Visitors 1982
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (97727,8,'orizehavi-tech','A beautifully tragic gothic fairytale with incredible makeup and a stunning Danny Elfman score.',NULL); # 97727 Edward Scissorhands 1990
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (100138,10,'orizehavi-tech','A bleak, character-driven sequel featuring the most shocking reveal in pop culture.',NULL); # 100138 Empire Strikes Back, The 1985
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (100447,9,'orizehavi-tech','A brilliant and highly unique fantasy that uses practical effects and amazing costume design.',NULL); # 100447 En no labyrinth 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (101055,8,'orizehavi-tech','A raw depiction of sniper warfare that focuses on patience, deception, and geometry.',NULL); # 101055 Enemy at the Gates 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (101462,8,'orizehavi-tech','A fascinating historical look at the obsessive world of code-breaking during wartime.',NULL); # 101462 Enigma 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (101700,9,'orizehavi-tech','A flawless martial arts classic that completely defined the genre for decades.',NULL); # 101700 Enter the Dragon 1973
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (102108,9,'orizehavi-tech','A perfect swashbuckling adventure with a brilliant mix of pirate lore and comedy.',NULL); # 102108 Epic at Sea: The Making of 'Pirates of the Caribbean: The Curse of the Black Pearl', An 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (104338,9,'orizehavi-tech','A visually inventive and emotionally crushing exploration of memory and heartbreak.',NULL); # 104338 Eternal Sunshine of the Spotless Mind 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (105723,8,'orizehavi-tech','A highly tense hijacking scenario that keeps the suspense tight throughout.',NULL); # 105723 Executive Decision 1996
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (106217,10,'orizehavi-tech','A rare sequel that surpasses its predecessor. The liquid metal effects still look incredible.',NULL); # 106217 Exterminator 2 1984
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (107166,8,'orizehavi-tech','A bizarre concept executed with incredible style and non-stop ridiculous action.',NULL); # 107166 Face/Off 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (109608,8,'orizehavi-tech','An intensely uncomfortable and gripping look at obsession and extreme consequence.',NULL); # 109608 Fatal Attraction 1987
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (111442,9,'orizehavi-tech','An iconic high school comedy that captures the pure chaos and fun of cutting class.',NULL); # 111442 Ferris Bueller's Day Off 1986
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (111813,9,'orizehavi-tech','The courtroom scenes are explosive, anchored by phenomenal, razor-sharp dialogue.',NULL); # 111813 Few Good Men, A 1992
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (113504,9,'orizehavi-tech','A visually stunning underwater road-trip that deals heavily with letting go of fear.',NULL); # 113504 Finding Nemo 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (115106,7,'orizehavi-tech','A highly energetic dance movie that relies heavily on its iconic musical sequences.',NULL); # 115106 Flashdance 1983
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (118393,8,'orizehavi-tech','A sharp, episodic romantic comedy that nails the awkwardness of social gatherings.',NULL); # 118393 Four Weddings and a Funeral 1994
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (122658,8,'orizehavi-tech','A gritty exploration of the extreme psychological abuse involved in military training.',NULL); # 122658 G.I. Jane 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (124554,9,'orizehavi-tech','A wildly ambitious, beautifully shot science fiction epic with a surprisingly emotional core.',NULL); # 124554 Gattaca 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (129185,9,'orizehavi-tech','Epic scope and tragic betrayal fuel this incredibly engaging revenge story set in Rome.',NULL); # 129185 Gladiator 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (129369,9,'orizehavi-tech','A dark, foul-mouthed masterclass in writing that exposes the desperation of salesmen.',NULL); # 129369 Glengarry Glen Ross 1992
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (130128,10,'orizehavi-tech','An operatic, sprawling tragedy that defines the entire organized crime genre.',NULL); # 130128 Godfather, The 1972
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (130708,8,'orizehavi-tech','The animation holds up remarkably well, securing its place as a historical milestone.',NULL); # 130708 Golden Anniversary of Snow White and the Seven Dwarfs 1987
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (131223,7,'orizehavi-tech','Fast cars and a slick soundtrack make this a very easy and fun watch.',NULL); # 131223 Gone in 60 Seconds 1974
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (131665,9,'orizehavi-tech','A deeply moving script exploring trauma, defense mechanisms, and unlocking true potential.',NULL); # 131665 Good Will Hunting 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (131780,10,'orizehavi-tech','The frantic editing and killer soundtrack plunge you directly into the mafia lifestyle.',NULL); # 131780 Goodfellas 1990
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (133725,10,'orizehavi-tech','The benchmark for adventure cinema. Packed with traps, treasure, and non-stop pacing.',NULL); # 133725 Great Movie Stunts: Raiders of the Lost Ark 1981
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (134672,9,'orizehavi-tech','Forces you to experience the crushing reality of a time loop. Philosophically brilliant.',NULL); # 134672 Groundhog Day 1993
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (139169,7,'orizehavi-tech','A highly stylized manhunt featuring some incredibly creative practical stunts.',NULL); # 139169 Hard Target 1993
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (139655,9,'orizehavi-tech','A fantastic shift to a darker, more mature tone with brilliant time travel mechanics.',NULL); # 139655 Harry Potter and the Prisoner of Azkaban 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (139657,8,'orizehavi-tech','Captures the childish wonder of discovering magic for the first time flawlessly.',NULL); # 139657 Harry Potter and the Sorcerer's Stone 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (140783,8,'orizehavi-tech','A powerful exploration of the intense exploitation surrounding young sports prodigies.',NULL); # 140783 He Got Game 1998
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (149156,8,'orizehavi-tech','A tense, slow-burn legal thriller that unravels a massive corporate conspiracy.',NULL); # 149156 Honor of the Firm, The 1912
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (149388,9,'orizehavi-tech','The ultimate sports underdog movie that focuses entirely on fundamentals and teamwork.',NULL); # 149388 Hoosiers 1986
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (155634,8,'orizehavi-tech','A highly atmospheric whodunit with a genuinely surprising and clever psychological twist.',NULL); # 155634 Identity 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (158999,8,'orizehavi-tech','The global destruction sequences are iconic. Pure popcorn entertainment.',NULL); # 158999 Independence Day 1996
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (161481,10,'orizehavi-tech','The harrowing beach landing sequence alone cements this as a cinematic achievement.',NULL); # 161481 Into the Breach: 'Saving Private Ryan' 1998
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (164238,8,'orizehavi-tech','A masterclass in atmospheric horror that relies on pure dread rather than cheap jump scares.',NULL); # 164238 J.R.R. Tolkien: The Origin of the Rings 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (166917,8,'orizehavi-tech','Sharp writing and genuine emotional stakes elevate this sports agency drama.',NULL); # 166917 Jerry Maguire 1996
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (169393,8,'orizehavi-tech','A laid-back, jazzy journey through the forest with incredibly memorable characters.',NULL); # 169393 Journey in the Jungle Book 1994
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (170522,8,'orizehavi-tech','A chaotic, wildly entertaining board game adventure with fantastic practical effects.',NULL); # 170522 Jumanji 1995
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (173930,9,'orizehavi-tech','The ultimate underdog martial arts story with a fantastic mentor dynamic.',NULL); # 173930 Karate Kid 1967
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (176711,7,'orizehavi-tech','A visually stunning revenge story that remains an incredible technical achievement.',NULL); # 176711 Kill Bill: Vol. 1 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (182955,9,'orizehavi-tech','A brilliant, tightly wound neo-noir mystery exploring police corruption in the 1950s.',NULL); # 182955 L.A. Confidential 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (188507,8,'orizehavi-tech','The chemistry between a loose cannon and a veteran cop set the standard for the genre.',NULL); # 188507 Lethal Weapon 1987
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (188511,7,'orizehavi-tech','Starts to show its age, but the core dynamic between the leads remains fun.',NULL); # 188511 Lethal Weapon 4 1998
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (190869,8,'orizehavi-tech','A wonderfully weird animated film about finding family in the most unlikely of places.',NULL); # 190869 Lilo & Stitch 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (192013,9,'orizehavi-tech','Kickstarted a whole new era of animation with timeless, perfect musical numbers.',NULL); # 192013 Little Mermaid Animated Storybook 1996
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (193253,8,'orizehavi-tech','A wonderfully stylized, fast-talking British crime caper filled with unforgettable characters.',NULL); # 193253 Lock, Stock and Two Smoking Barrels 1998
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (194204,9,'orizehavi-tech','A masterful psychological horror that slowly builds dread and tension to a breaking point.',NULL); # 194204 Look What's Happened to Rosemary's Baby 1976
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (194497,10,'orizehavi-tech','Perfectly establishes the massive scale of Middle-earth and the emotional core of the journey.',NULL); # 194497 Lord of the Rings: The Fellowship of the Ring, The 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (194502,9,'orizehavi-tech','The sheer scale of the Rohan battles makes this a gripping middle chapter.',NULL); # 194502 Lord of the Rings: The Two Towers, The 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (195300,9,'orizehavi-tech','Weaves together a dozen storylines into a warm, genuinely funny holiday classic.',NULL); # 195300 Love Actually 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (201516,9,'orizehavi-tech','The bullet-time effects completely rewrote the rules of action cinema.',NULL); # 201516 Making 'The Matrix' 1999
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (201733,8,'orizehavi-tech','A masterclass in confined-space tension, lighting, and incredibly dynamic camera work.',NULL); # 201733 Making of 'Panic Room', The 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (201754,8,'orizehavi-tech','The artistic styling and the terrifying villain make this a standout fantasy.',NULL); # 201754 Making of 'Sleeping Beauty', The 1996
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (201822,9,'orizehavi-tech','Revolutionized 3D animation while delivering a sharply written script about jealousy.',NULL); # 201822 Making of 'Toy Story', The 1995
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (207390,8,'orizehavi-tech','A historically meticulous and gripping portrayal of naval warfare and strategy.',NULL); # 207390 Master and Commander: The Far Side of the World 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (207989,6,'orizehavi-tech','The highway chase is phenomenal, but the philosophical dialogue is exhausting.',NULL); # 207989 Matrix Reloaded, The 2003
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (208245,8,'orizehavi-tech','A highly entertaining western comedy built entirely around poker bluffs and charm.',NULL); # 208245 Maverick 1994
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (209133,8,'orizehavi-tech','A razor-sharp takedown of high school cliques and toxic teenage social dynamics.',NULL); # 209133 Mean Girls 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (210509,9,'orizehavi-tech','Forces the audience into the shoes of an amnesiac. The reverse storytelling is genius.',NULL); # 210509 Memento 1967
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (210739,8,'orizehavi-tech','A crisp, fast-paced comedy that treats extraterrestrial bureaucracy with great wit.',NULL); # 210739 Men in Black 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (210741,5,'orizehavi-tech','A loud, flashy, and ultimately hollow spectacle that abandons the charm of the original.',NULL); # 210741 Men in Black II 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (214755,8,'orizehavi-tech','The interface design and precrime concepts make this a fascinating futuristic mystery.',NULL); # 214755 Minority Report 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (215346,9,'orizehavi-tech','A horrifyingly grounded psychological thriller about the darkest side of fandom.',NULL); # 215346 Misery 1990
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (215876,8,'orizehavi-tech','The Langley vault infiltration is a masterclass in silent, sweat-inducing suspense.',NULL); # 215876 Mission: Impossible 1996
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (218415,9,'orizehavi-tech','Turns childhood fears into a brilliant corporate satire with huge amounts of heart.',NULL); # 218415 Monsters, Inc. 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (238072,9,'orizehavi-tech','A breezy, stylish heist film that oozes cool from every single character.',NULL); # 238072 Ocean's Eleven 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (238695,9,'orizehavi-tech','A painfully accurate, hilarious takedown of corporate bureaucracy and soul-crushing cubicles.',NULL); # 238695 Office Space 1999
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (245008,8,'orizehavi-tech','A surprisingly funny and sweet teen comedy built around the strange culture of snowboarding.',NULL); # 245008 Out Cold 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (245275,8,'orizehavi-tech','A terrifying look at viral contagion and the extreme measures taken by the military.',NULL); # 245275 Outbreak 1995
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (251979,8,'orizehavi-tech','Keeps the paranoia high as it dives into dark political assassinations and cover-ups.',NULL); # 251979 Pelican Brief, The 1993
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (254943,8,'orizehavi-tech','A frantic, black-and-white dive into paranoia and the obsessive search for mathematical patterns.',NULL); # 254943 Pi 1998
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (258860,9,'orizehavi-tech','Adrenaline-fueled action perfectly blended with surfing culture and a tight bank heist plot.',NULL); # 258860 Point Break 1991
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (262645,9,'orizehavi-tech','An invisible enemy in the jungle builds incredible dread before the explosive finale.',NULL); # 262645 Predator 1987
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (271192,8,'orizehavi-tech','A very sensitive and moving cross-country journey about brotherhood and patience.',NULL); # 271192 Rain Man 1988
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (274589,8,'orizehavi-tech','Escalates the action and the banter, delivering a rare comedy sequel that works.',NULL); # 274589 Reel Comedy: Rush Hour 2 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (274594,8,'orizehavi-tech','A boundary-pushing gross-out comedy that still manages to maintain a very sweet core.',NULL); # 274594 Reel Comedy: Something About Mary 1998
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (275453,9,'orizehavi-tech','An incredibly uplifting story about breaking down racial barriers through high school football.',NULL); # 275453 Remember the Titans 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (279420,8,'orizehavi-tech','A beautifully shot, grim mobster tale exploring themes of fathers, sons, and vengeance.',NULL); # 279420 Road to Perdition 2002
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (280270,9,'orizehavi-tech','A gritty, deeply moving underdog story that is much more about character than boxing.',NULL); # 280270 Rocky 1976
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (280282,8,'orizehavi-tech','Leans into the spectacle and delivers a highly entertaining, crowd-pleasing bout.',NULL); # 280282 Rocky III 1982
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (280478,7,'orizehavi-tech','A dark, fascinating exploration of the intense risks associated with unregulated stock markets.',NULL); # 280478 Rogue Trader 1999
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (281334,8,'orizehavi-tech','A sharp, realistic thriller focusing on mercenary logistics and precise car chases.',NULL); # 281334 Ronin 1998
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (282452,9,'orizehavi-tech','The definitive poker movie, showcasing the underground grind of Texas Hold em.',NULL); # 282452 Rounders 1998
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (289558,9,'orizehavi-tech','An unapologetic, violently explosive look at the destructive nature of unchecked ambition.',NULL); # 289558 Scarface 1983
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (289666,6,'orizehavi-tech','Relies entirely on crude humor and shock value that loses its appeal very quickly.',NULL); # 289666 Scary Movie 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (290070,10,'orizehavi-tech','A monumental achievement in historical drama. The black-and-white cinematography is devastating.',NULL); # 290070 Schindler's List 1993
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (291221,8,'orizehavi-tech','A brilliant, self-aware horror film that dissects all the classic tropes of the slasher genre.',NULL); # 291221 Scream 1996
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (297382,8,'orizehavi-tech','A very fun blending of classic western tropes and martial arts choreography.',NULL); # 297382 Shanghai Noon 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (297838,9,'orizehavi-tech','A quiet, powerful testament to the triumph of the human spirit in the darkest places.',NULL); # 297838 Shawshank Redemption, The 1994
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (300229,9,'orizehavi-tech','A hilarious deconstruction of fairy tales packed with jokes for both kids and adults.',NULL); # 300229 Shrek 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (306051,8,'orizehavi-tech','An early tech thriller focusing on cryptography, data manipulation, and corporate espionage.',NULL); # 306051 Sneakers 1992
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (310184,8,'orizehavi-tech','A loving, incredibly silly spoof of space operas that holds up surprisingly well.',NULL); # 310184 Spaceballs 1987
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (310726,8,'orizehavi-tech','A brilliant high-concept premise that literally never slows down.',NULL); # 310726 Speed 1994
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (311038,9,'orizehavi-tech','Perfectly captures the painful struggle between a personal life and superhero duties.',NULL); # 311038 Spider-Man 2 2004
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (312138,8,'orizehavi-tech','A stylish espionage thriller focused on extraction tactics and agency politics.',NULL); # 312138 Spy Game 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (313059,9,'orizehavi-tech','A touching, beautifully nostalgic adventure about the fleeting innocence of childhood friendships.',NULL); # 313059 Stand by Me 1986
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (313474,4,'orizehavi-tech','The visual effects are decent, but the political trade disputes put me to sleep.',NULL); # 313474 Star Wars: Episode I - The Phantom Menace 1999
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (313601,8,'orizehavi-tech','A fun mix of Egyptian mythology and sci-fi that successfully launched a massive franchise.',NULL); # 313601 Stargate 1994
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (333393,7,'orizehavi-tech','A fun sci-fi action blend that uses its time-travel mechanics for great fight scenes.',NULL); # 333393 Timecop 1994
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (333856,9,'orizehavi-tech','A sweeping historical drama that successfully balances epic romance and sheer disaster spectacle.',NULL); # 333856 Titanic 1997
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (335245,8,'orizehavi-tech','A highly stylized western that delivers iconic shootouts and infinitely quotable dialogue.',NULL); # 335245 Tombstone 1993
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (335834,8,'orizehavi-tech','A high-energy, unapologetic love letter to fighter pilots and 80s music.',NULL); # 335834 Top Gun 1955
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (336458,7,'orizehavi-tech','A hyper-violent, deeply weird trip to Mars that relies heavily on practical gore.',NULL); # 336458 Total Recall 1990
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (337404,9,'orizehavi-tech','A sprawling, interconnected narrative exploring the devastating impact of the drug trade.',NULL); # 337404 Traffic 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (337814,9,'orizehavi-tech','A tense, claustrophobic ride through corrupt policing anchored by a powerhouse lead performance.',NULL); # 337814 Training Day 2001
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (340799,9,'orizehavi-tech','A brilliant, explosive blend of domestic comedy and high-stakes espionage.',NULL); # 340799 True Lies 1994
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (340901,9,'orizehavi-tech','A deeply unsettling prediction of reality TV culture wrapped in a touching personal drama.',NULL); # 340901 Truman Show, The 1998
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (345690,8,'orizehavi-tech','A grounded, melancholic look at the superhero genre before cinematic universes existed.',NULL); # 345690 Unbreakable 2000
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (358708,9,'orizehavi-tech','A definitive, cold-blooded examination of 80s corporate greed and insider trading.',NULL); # 358708 Wall Street 1987
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (362808,8,'orizehavi-tech','The dialogue shines in this iconic, slow-burn romantic comedy spanning over a decade.',NULL); # 362808 When Harry Met Sally... 1989
insert into personal_movies_ranking (`movie_id`,`recommendation`,`suggested_by`,`justification`,`comment`) VALUES (375827,8,'orizehavi-tech','An excellent meta-comedy that perfectly breaks down the absurdity of the modeling industry.',NULL); # 375827 Zoolander 2001