insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (644, 10, 'talroup', 'Patrick''s grand-gesture confidence and Kat''s sharp wit make this my ideal teen rom-com', null); # 644 10 Things I Hate About You 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (263360, 10, 'talroup', 'Vivian''s humor and Beverly Hills fairy-tale makeover give the romance an irresistible pull', null); # 263360 Pretty Woman 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (151616, 10, 'talroup', 'A fake-dating challenge should feel silly; the Hudson-McConaughey chemistry makes it work perfectly', null); # 151616 How to Lose a Guy in 10 Days 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (66194, 10, 'talroup', 'Cher''s matchmaking, fashion, and self-aware attitude make the teen comedy feel endlessly fun', null); # 66194 Clueless 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300229, 10, 'talroup', 'The ogre-princess twist is funny, romantic, and oddly sweet all at once', null); # 300229 Shrek 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (337166, 10, 'talroup', 'Woody and Buzz moving from jealousy to friendship without losing the jokes is exactly what I love', null); # 337166 Toy Story 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (1038, 9, 'talroup', 'Jenna''s second chance at adulthood is sweet, funny, and full of feel-good romantic energy', null); # 1038 13 Going On 30 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (200864, 9, 'talroup', 'A maid mistaken for a socialite is pure rom-com fantasy, and Jennifer Lopez sells every moment', null); # 200864 Maid in Manhattan 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (283410, 9, 'talroup', 'Roberts and Gere turn commitment fears into easy, warm romance in the best way', null); # 283410 Runaway Bride 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46878, 9, 'talroup', 'Bridget''s diary, awkward dates, and messy confidence make the romance feel funny and personal', null); # 46878 Bridget Jones: The Edge of Reason 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (264157, 9, 'talroup', 'Genovia, royal rules, and Anne Hathaway''s charm make this sequel light, girly, and comforting', null); # 264157 Princess Diaries 2: Royal Engagement, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (190869, 9, 'talroup', 'Lilo and Stitch''s chosen-family bond gives the Disney chaos a surprisingly sweet center', null); # 190869 Lilo & Stitch 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300230, 9, 'talroup', 'Meeting Fiona''s parents adds more family comedy and romance than I expected from a sequel', null); # 300230 Shrek 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (62460, 9, 'talroup', 'A chocolate shop changing a conservative village is exactly the kind of cozy romance I enjoy', null); # 62460 Chocolat 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (220276, 9, 'talroup', 'The huge musical numbers make the tragic romance colorful and fun enough to love', null); # 220276 Moulin Rouge! 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (34104, 9, 'talroup', 'Depp''s Buster Keaton-style sweetness turns the odd couple premise into something genuinely tender', null); # 34104 Benny & Joon 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (59578, 9, 'talroup', 'Wonka''s factory rooms are bizarre and candy-colored, so the fantasy stays playful instead of gloomy', null); # 59578 Charlie and the Chocolate Factory 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (96593, 9, 'talroup', 'Elliott hiding his alien friend at home gives the sci-fi story a gentle, warm family feeling', null); # 96593 E.T. the Extra-Terrestrial 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (328272, 9, 'talroup', 'Being trapped in an airport could be dull, but Tom Hanks makes every scene kind and human', null); # 328272 Terminal, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (333856, 9, 'talroup', 'Jack and Rose keep the disaster movie rooted in a romance I can actually care about', null); # 333856 Titanic 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (149287, 8, 'talroup', 'A grown-up Peter Pan could be too sad; Robin Williams keeps it nostalgic and soft-hearted', null); # 149287 Hook 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131885, 8, 'talroup', 'Mikey''s treasure hunt and the noisy kid group give this adventure messy, happy energy', null); # 131885 Goonies, The 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (113506, 8, 'talroup', 'The Neverland imagination and gentle father-children angle keep the drama from feeling too sad', null); # 113506 Finding Neverland 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139657, 8, 'talroup', 'Arriving at Hogwarts, choosing houses, and meeting the trio makes this pure magical comfort', null); # 139657 Harry Potter and the Sorcerer's Stone 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139650, 8, 'talroup', 'The flying car and secret-chamber mystery are darker, yet Hogwarts still feels inviting', null); # 139650 Harry Potter and the Chamber of Secrets 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139655, 8, 'talroup', 'Moodier than the first two, but the time-turner story and warmer friendships keep me invested', null); # 139655 Harry Potter and the Prisoner of Azkaban 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139652, 8, 'talroup', 'Dragons, the Yule Ball, and school rivalry make the tournament chapter big but still accessible', null); # 139652 Harry Potter and the Goblet of Fire 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139654, 7, 'talroup', 'Umbridge and the rebellion are interesting, but this chapter loses some of the cozy Hogwarts magic', null); # 139654 Harry Potter and the Order of the Phoenix 2007
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139653, 7, 'talroup', 'Romantic jealousy and awkward teenage moments soften a plot that is otherwise getting darker', null); # 139653 Harry Potter and the Half-Blood Prince 2008
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256632, 8, 'talroup', 'Jack Sparrow turns piracy into something funny, stylish, and much less serious than expected', null); # 256632 Pirates of the Caribbean: The Curse of the Black Pearl 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256631, 8, 'talroup', 'Elizabeth and Will give the louder sequel enough romance to stay fun throughout', null); # 256631 Pirates of the Caribbean 2 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238072, 8, 'talroup', 'The heist feels sunny and stylish instead of tense or violent, which is exactly right for me', null); # 238072 Ocean's Eleven 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238073, 7, 'talroup', 'Still has movie-star charm, although the story feels more smug than breezy this time', null); # 238073 Ocean's Twelve 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56871, 8, 'talroup', 'The fake-pilot chase gives the film a playful rhythm instead of a heavy crime mood', null); # 56871 Catch Me If You Can 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210739, 8, 'talroup', 'Will Smith''s delivery makes the alien suits-and-gadgets world feel quick and mainstream', null); # 210739 Men in Black 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312150, 8, 'talroup', 'Kid heroes, spy gadgets, and bright colors make the whole thing feel silly in the right way', null); # 312150 Spy Kids 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312151, 7, 'talroup', 'Still cute and family-friendly, though the island adventure is less surprising than the first film', null); # 312151 Spy Kids 2: Island of Lost Dreams 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312152, 7, 'talroup', 'A video-game spy mission is ridiculous, which is basically why it stays harmless and fun', null); # 312152 Spy Kids 3-D: Game Over 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (170721, 8, 'talroup', 'Songs, animals, and a simple jungle adventure make this bright enough for an easy watch', null); # 170721 Jungle Book 2, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (291495, 7, 'talroup', 'Meaner than my usual holiday pick; Bill Murray eventually finds just enough heart', null); # 291495 Scrooged 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311428, 8, 'talroup', 'A mermaid-in-New-York romance is silly, but Tom Hanks makes it genuinely sweet', null); # 311428 Splash 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (31715, 8, 'talroup', 'Bette Midler''s music and the long female friendship make the drama warmer than its sadder moments', null); # 31715 Beaches 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (33492, 8, 'talroup', 'Food, kitchen routine, and quiet attraction give this European romance a very gentle charm', null); # 33492 Bella Martha 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (74259, 7, 'talroup', 'Strange retro camp, but Depp''s performance keeps the weirdness playful rather than off-putting', null); # 74259 Cry-Baby 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (97727, 7, 'talroup', 'Edward''s innocence against the perfect suburb is strange, romantic, and beautifully sad', null); # 97727 Edward Scissorhands 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (257744, 8, 'talroup', 'The ensemble structure gives several little love stories instead of one heavy drama to follow', null); # 257744 Playing by Heart 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (118980, 7, 'talroup', 'A diner romance with two adults slowly choosing vulnerability; grounded and quietly moving', null); # 118980 Frankie and Johnny 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (12744, 7, 'talroup', 'Old-fashioned, but the ghostly love story has a soft Spielberg glow I appreciate', null); # 12744 Always 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10702, 7, 'talroup', 'Alice rebuilding her life gives the drama warmth I did not expect from a Scorsese film', null); # 10702 Alice Doesn't Live Here Anymore 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (208245, 7, 'talroup', 'Poker-table tricks and Foster-Gibson banter keep the western closer to comedy than grit', null); # 208245 Maverick 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280270, 7, 'talroup', 'The Adrian romance gives the boxing story a tender center I connect with', null); # 280270 Rocky 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280281, 6, 'talroup', 'Rocky and Adrian are still sweet together, even when the sequel leans into pressure', null); # 280281 Rocky II 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280282, 6, 'talroup', 'The training energy is fun; the emotional beats already feel more formulaic here', null); # 280282 Rocky III 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280284, 5, 'talroup', 'Big spectacle and music, but missing the personal sweetness I liked from the first one', null); # 280284 Rocky IV 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280305, 4, 'talroup', 'Feels less like hope and more like a tired extension of a franchise that already peaked', null); # 280305 Rocky V 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (65811, 7, 'talroup', 'The lights-in-the-sky mystery feels curious and hopeful instead of frightening', null); # 65811 Close Encounters of the Third Kind 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (158999, 7, 'talroup', 'Massive destruction would usually push me away, but Will Smith keeps it popcorn-fun', null); # 158999 Independence Day 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335835, 7, 'talroup', 'Basically glossy confidence, beach volleyball, and a small romantic pull — easy to enjoy', null); # 335835 Top Gun 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (319602, 7, 'talroup', 'Christopher Reeve''s sincerity is hard not to root for; the tone stays genuinely bright', null); # 319602 Superman 1978
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (319613, 6, 'talroup', 'Still friendly, although the romance no longer feels as magical as the original', null); # 319613 Superman II 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311037, 8, 'talroup', 'Peter trying to balance Mary Jane and hero life gives the action a sweet emotional center', null); # 311037 Spider-Man 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311038, 8, 'talroup', 'The train sequence is intense, but Peter and Mary Jane keep the sequel genuinely emotional', null); # 311038 Spider-Man 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311040, 6, 'talroup', 'Too many villains and too much internal drama, so the romance gets a little lost', null); # 311040 Spider-Man 3 2007
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30965, 6, 'talroup', 'Silly and neon-colored, which makes it more watchable than the darker chapters in the series', null); # 30965 Batman Forever 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30955, 5, 'talroup', 'Burton''s Gotham is visually memorable; I just do not find it fun or comforting to watch', null); # 30955 Batman 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30959, 5, 'talroup', 'Bruce Wayne is built well here, yet the serious tone is not what I want for a relaxed movie night', null); # 30959 Batman Begins 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30952, 4, 'talroup', 'Camp, ice puns, and chaos, but not enough real charm to balance out the mess', null); # 30952 Batman & Robin 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30976, 6, 'talroup', 'Visually elegant with a tragic romance at its core, which keeps it more serious than I expected', null); # 30976 Batman: Mask of the Phantasm 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30961, 6, 'talroup', 'The future-Gotham concept is cool, though the mood here is much darker and less cheerful than the series', null); # 30961 Batman Beyond: Return of the Joker (2000/I) 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (381392, 7, 'talroup', 'The futuristic setting gives the whole series a sleek, accessible energy I enjoy', null); # 381392 Batman Beyond 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (379290, 6, 'talroup', 'Old-school and simple, nostalgic enough to be light even if not very exciting', null); # 379290 Adventures of Batman, The 1969
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (142491, 6, 'talroup', 'Hellboy''s dry humor helps, but the monster-world darkness keeps it only mid-level for me', null); # 142491 Hellboy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (142492, 6, 'talroup', 'Imaginative creatures, though I miss a lighter romantic or genuinely comic mood', null); # 142492 Hellboy 2 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300233, 7, 'talroup', 'A short fairy-tale attraction that gives quick silliness without asking too much of me', null); # 300233 Shrek 4-D 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (170875, 5, 'talroup', 'Odd comic energy; I would not remember it, but it passes the time harmlessly', null); # 170875 Junk Drawer 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (391006, 8, 'talroup', 'Diner nostalgia, simple jokes, and cheerful comfort — genuinely my kind of TV', null); # 391006 Happy Days 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (390691, 8, 'talroup', 'Exactly the kind of warm family sitcom I would leave on casually any evening', null); # 390691 Growing Pains 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (395271, 8, 'talroup', 'Laverne and Shirley''s friendship gives the sitcom its lively, cheerful personality', null); # 395271 Laverne & Shirley 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (398232, 8, 'talroup', 'Robin Williams''s alien sweetness makes the comedy feel goofy and genuinely affectionate', null); # 398232 Mork & Mindy 1978
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (398571, 7, 'talroup', 'Murphy Brown has confidence and bite, more witty than cozy but still enjoyable', null); # 398571 Murphy Brown 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (400853, 8, 'talroup', 'The family messiness feels relatable, and Ron Howard keeps it warm throughout', null); # 400853 Parenthood 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (379931, 7, 'talroup', 'Each episode feels imaginative without becoming emotionally demanding or heavy', null); # 379931 Amazing Stories 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (379327, 7, 'talroup', 'The heroism is simple and upbeat in a pleasantly old-fashioned way', null); # 379327 Adventures of Robin Hood, The 1955
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (379331, 6, 'talroup', 'Clever enough to appreciate, even if mystery is not my happiest genre', null); # 379331 Adventures of Sherlock Holmes, The 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (405119, 6, 'talroup', 'Some comfort value here, though the mood stays a bit distant for my taste', null); # 405119 Sherlock Holmes 1951
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (372733, 6, 'talroup', 'A cute concept, yet it never quite becomes a personal favorite for me', null); # 372733 Young Sherlock Holmes 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (1121, 5, 'talroup', 'Grand historical exploration that impresses without becoming something I would choose to relax with', null); # 1121 1492: Conquest of Paradise 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (1390, 5, 'talroup', 'Comic chaos and big energy, only not the kind that actually feels cozy or comfortable', null); # 1390 1941 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (7842, 5, 'talroup', 'One clever Manhattan night turned into anxiety; definitely not my kind of evening mood', null); # 7842 After Hours 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (8183, 5, 'talroup', 'A restrained society romance should appeal to me, yet this one ends up emotionally muted', null); # 8183 Age of Innocence, The 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (20253, 5, 'talroup', 'Quirky personality throughout; I admire it more than I actually enjoy watching it', null); # 20253 Arizona Dream 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (21213, 5, 'talroup', 'The childlike longing touches me, but the ending leaves me melancholic rather than uplifted', null); # 21213 Artificial Intelligence: AI 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (22651, 3, 'talroup', 'Marriage thriller meets alien paranoia — way too cold and suspicious for my taste', null); # 22651 Astronaut's Wife, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (25192, 5, 'talroup', 'Strong filmmaking, but the Howard Hughes biopic feels long and dutiful rather than enjoyable', null); # 25192 Aviator, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30686, 3, 'talroup', 'DiCaprio is committed, but the addiction spiral is simply too bleak for me to sit through', null); # 30686 Basketball Diaries, The 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (32707, 4, 'talroup', 'I respect the artistic portrait, yet it carries more pain than I want from a film', null); # 32707 Before Night Falls 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (39551, 1, 'talroup', 'The exact combat intensity I actively avoid when choosing what to watch', null); # 39551 Black Hawk Down 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (40199, 4, 'talroup', 'The neon future is beautiful to look at; the pervasive loneliness makes it hard for me', null); # 40199 Blade Runner 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (41518, 3, 'talroup', 'Depp is magnetic here, but the drug-crime rise-and-fall story drains rather than engages me', null); # 41518 Blow 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46169, 4, 'talroup', 'There is romance and heroism here, yet the battles overpower the uplifting parts', null); # 46169 Braveheart 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (54209, 2, 'talroup', 'Turning family safety into a prolonged thriller mood is something I would actively avoid', null); # 54209 Cape Fear 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56304, 3, 'talroup', 'Starts glamorous, then the crime world becomes exhausting rather than entertaining', null); # 56304 Casino 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (61751, 3, 'talroup', 'Gripping and visually strong, but not something I would ever call an enjoyable watch', null); # 61751 Children of Men, The 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (67395, 4, 'talroup', 'It matters emotionally, although it asks for a level of heaviness I find difficult', null); # 67395 Color Purple, The 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (69812, 4, 'talroup', 'Interesting stars in an interesting premise; paranoid romance is still not relaxing enough', null); # 69812 Conspiracy Theory 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (73574, 3, 'talroup', 'Goofy horror-comedy, which makes it less awful but still not my kind of thing', null); # 73574 Critters 3 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (85871, 6, 'talroup', 'Connery gives Bond real charisma; this entry still feels uneven and dated overall', null); # 85871 Diamonds Are Forever 1971
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (86263, 5, 'talroup', 'The ice-palace spectacle is fun, but the charm gets buried under too much excess', null); # 86263 Die Another Day 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (92573, 5, 'talroup', 'Iconic in a film-history way, but not a film I would naturally reach for on a Friday night', null); # 92573 Dr. No 1962
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (117314, 5, 'talroup', 'Polished chases throughout, but the romance and humor barely land for me', null); # 117314 For Your Eyes Only 1981
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120574, 5, 'talroup', 'Smooth spy cinema, only too old-toned and slow-paced for my personal taste', null); # 120574 From Russia with Love 1963
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130945, 6, 'talroup', 'The glossy, Pierce Brosnan-charming version of Bond I can actually enjoy in moderation', null); # 130945 GoldenEye 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130953, 6, 'talroup', 'Gadgets, a famous villain, and undeniable style, even if Bond is not really my genre', null); # 130953 Goldfinger 1964
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (189403, 4, 'talroup', 'Dalton''s revenge-driven version feels harsher than the playful spy mood I usually want', null); # 189403 Licence to Kill 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (192514, 5, 'talroup', 'Has music and swagger, but the story feels uneven and does not stick with me', null); # 192514 Live and Let Die 1973
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (192702, 5, 'talroup', 'Dalton''s seriousness gives the role focus, at the cost of any real warmth', null); # 192702 Living Daylights, The 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (203649, 5, 'talroup', 'A kitschy golden-gun villain is enough to watch once, not enough to actually love', null); # 203649 Man with the Golden Gun, The 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218808, 5, 'talroup', 'So absurdly space-spy that it becomes mildly watchable, almost despite itself', null); # 218808 Moonraker 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (240521, 5, 'talroup', 'The marriage storyline adds emotion, though the pacing keeps me at a distance', null); # 240521 On Her Majesty's Secret Service 1969
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312170, 6, 'talroup', 'Roger Moore''s lighter tone makes this feel like a more playful and accessible spy adventure', null); # 312170 Spy Who Loved Me, The 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (332065, 5, 'talroup', 'Connery''s charm is the main appeal, but the underwater pacing drags badly for me', null); # 332065 Thunderball 1965
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (354178, 4, 'talroup', 'Feels like the Bond formula running out of sparkle — not even the villain helps', null); # 354178 View to a Kill, A 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (368418, 5, 'talroup', 'Polished Brosnan Bond without much lasting romance or fun to actually remember', null); # 368418 World Is Not Enough, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (372233, 5, 'talroup', 'The retro volcano lair is fun, but the whole thing still feels very dated', null); # 372233 You Only Live Twice 1967
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215876, 6, 'talroup', 'The famous vault scene is tense and polished, but the film is more sleek than warm', null); # 215876 Mission: Impossible 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215879, 5, 'talroup', 'Cares more about slow-motion action sequences than actual personality or connection', null); # 215879 Mission: Impossible II 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215880, 6, 'talroup', 'Cruise brings real urgency, though the stakes stay a bit too intense for me to relax into', null); # 215880 Mission: Impossible III 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (109421, 6, 'talroup', 'Glossy and energetic street-racing world, even if I do not personally connect with the crew', null); # 109421 Fast and the Furious, The 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (370017, 5, 'talroup', 'All extreme-sports attitude; I find the flashiness more shallow than actually fun', null); # 370017 XXX 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188507, 5, 'talroup', 'Riggs and Murtaugh have genuine banter, though the rough police action is not my comfort zone', null); # 188507 Lethal Weapon 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188509, 5, 'talroup', 'The partner chemistry still works, even when the action feels familiar and repetitive', null); # 188509 Lethal Weapon 2 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188510, 4, 'talroup', 'By the third one, the formula feels more repetitive than anything else', null); # 188510 Lethal Weapon 3 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188511, 4, 'talroup', 'Busy and loud, with too little warmth to balance any of it out', null); # 188511 Lethal Weapon 4 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (220805, 7, 'talroup', 'Married spies fighting and flirting is exactly why this action film stays fun', null); # 220805 Mr. and Mrs. Smith 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (340652, 5, 'talroup', 'Movie-star glamour throughout, but the war epic mood feels too solemn for me', null); # 340652 Troy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (359297, 4, 'talroup', 'A strong family survival angle at first, but then the panic simply overwhelms me', null); # 359297 War of the Worlds 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256839, 3, 'talroup', 'All darkness, creatures, and survival tension — not my kind of night at all', null); # 256839 Pitch Black 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10830, 1, 'talroup', 'Being trapped on that spaceship is far too frightening for me to enjoy as entertainment', null); # 10830 Alien 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10920, 3, 'talroup', 'More action and momentum, yet I still feel stuck in nonstop tension throughout', null); # 10920 Aliens 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (240327, 1, 'talroup', 'A demonic-child premise is completely wrong for any positive movie mood of mine', null); # 240327 Omen, The 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (259826, 2, 'talroup', 'May be iconic, but a haunted-house experience is just not something I would ever choose', null); # 259826 Poltergeist 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (304862, 3, 'talroup', 'Gorgeous gothic fog and visual style, though the murder mystery leaves me gloomy', null); # 304862 Sleepy Hollow 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (350189, 3, 'talroup', 'Stylish in its own way, yet the vampire-anime world feels cold and joyless to me', null); # 350189 Vampire Hunter D 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (350424, 4, 'talroup', 'Romance on paper, but the mind-bending structure frustrates more than it satisfies', null); # 350424 Vanilla Sky 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (233058, 3, 'talroup', 'Too occult, cold, and joyless, genuinely the opposite of why I watch films', null); # 233058 Ninth Gate, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (292671, 3, 'talroup', 'Depp gives a strong performance, but the isolated-writer thriller feels sour throughout', null); # 292671 Secret Window 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (247579, 3, 'talroup', 'Brilliant use of the house as a location; I still experience the whole thing as stress rather than fun', null); # 247579 Panic Room 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210511, 2, 'talroup', 'The reverse-order puzzle is undeniably clever, but I never relax into it for a single scene', null); # 210511 Memento 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (123435, 3, 'talroup', 'Intriguing premise, but the sustained manipulation feels genuinely unpleasant to sit through', null); # 123435 Game, The 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (112290, 1, 'talroup', 'The cult energy, aggression, and cynicism are the complete opposite of what I look for', null); # 112290 Fight Club 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (291698, 1, 'talroup', 'Gripping as a thriller, but the ending makes it a firm no for me every single time', null); # 291698 Se7en 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (326155, 1, 'talroup', 'Travis''s loneliness and isolation are too oppressive for me to experience as a movie', null); # 326155 Taxi Driver 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (270971, 2, 'talroup', 'Watching anger and self-destruction repeat on screen is genuinely not enjoyable for me', null); # 270971 Raging Bull 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131780, 3, 'talroup', 'Expertly made, but the gangster world is too brutal and relentless for my taste', null); # 131780 Goodfellas 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (267038, 3, 'talroup', 'Real style and quotable dialogue, but none of the warmth or romance I actually look for', null); # 267038 Pulp Fiction 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (276217, 1, 'talroup', 'Stuck in a tense warehouse with people I have no desire to spend time with', null); # 276217 Reservoir Dogs 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176711, 2, 'talroup', 'The yellow-suit iconography is unforgettable, but the revenge violence dominates everything else', null); # 176711 Kill Bill: Vol. 1 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176712, 3, 'talroup', 'Slows down and talks more, yet revenge still sets the entire mood throughout', null); # 176712 Kill Bill: Vol. 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (289109, 1, 'talroup', 'The overwhelming war realism loses me completely, however important the film is', null); # 289109 Saving Private Ryan 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (290070, 1, 'talroup', 'Important cinema that I cannot rate as enjoyable — it simply asks too much of me', null); # 290070 Schindler's List 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (165961, 4, 'talroup', 'Iconic suspense, but I mostly feel anxious waiting for the next attack rather than thrilled', null); # 165961 Jaws 1975
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (94741, 3, 'talroup', 'Turning one truck into a prolonged nightmare is clever, but not a pleasant experience', null); # 94741 Duel (1971/I) 1971
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (308057, 2, 'talroup', 'Stays firmly in the gloomy supernatural lane I usually avoid without hesitation', null); # 308057 Something Evil 1972
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (288493, 2, 'talroup', 'Old-school Dracula horror has its audience, but that audience is definitely not me', null); # 288493 Satanic Rites of Dracula, The 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (49854, 3, 'talroup', 'The mock-documentary concept is unusual, though the mystery feels more odd than enjoyable', null); # 49854 Buried Secret of M. Night Shyamalan, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (164572, 4, 'talroup', 'Pam Grier gives the role presence, but the crime conversations still feel rough for my taste', null); # 164572 Jackie Brown 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (209158, 3, 'talroup', 'Raw and restless with none of the lightness I want from a film I am choosing freely', null); # 209158 Mean Streets 1973
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120506, 3, 'talroup', 'Real atmosphere, but the Victorian murder setting is much too grim for me', null); # 120506 From Hell 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (47130, 3, 'talroup', 'A night-shift ambulance world I would not revisit even if someone asked nicely', null); # 47130 Bringing Out the Dead 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (160524, 4, 'talroup', 'Strong acting and craft throughout, but the sleepless detective mood feels cold and draining', null); # 160524 Insomnia 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (214755, 5, 'talroup', 'A smart future-crime hook, yet the relentless chase mood is never light enough for me', null); # 214755 Minority Report 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (129185, 5, 'talroup', 'Heart comes through Maximus, though the arena-and-empire story still weighs heavily', null); # 129185 Gladiator 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (123849, 3, 'talroup', 'Grand and well acted, but the violent immigrant-gang world turns me away quickly', null); # 123849 Gangs of New York 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185628, 4, 'talroup', 'Beautiful to look at from start to finish, while the war story stays too solemn', null); # 185628 Last Samurai, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159172, 7, 'talroup', 'Indy''s father-son banter with Sean Connery makes the adventure warmer and genuinely funnier', null); # 159172 Indiana Jones and the Last Crusade 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159175, 5, 'talroup', 'Mine-cart excitement is fun, though the darker temple material is less my thing', null); # 159175 Indiana Jones and the Temple of Doom 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (271095, 7, 'talroup', 'Treasure-hunt energy, humor, and Harrison Ford at his most charismatic and fun', null); # 271095 Raiders of the Lost Ark 1981
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194497, 8, 'talroup', 'The Shire and the fellowship friendship make the fantasy feel magical rather than cold', null); # 194497 Lord of the Rings: The Fellowship of the Ring, The 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194502, 7, 'talroup', 'Helm''s Deep is impressive, even if the war focus makes this chapter noticeably heavier', null); # 194502 Lord of the Rings: The Two Towers, The 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194500, 7, 'talroup', 'Moving in a big emotional way, though the scale is almost too much to process comfortably', null); # 194500 Lord of the Rings: The Return of the King, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313474, 6, 'talroup', 'The podrace and colorful alien worlds are genuinely fun; the story itself is uneven', null); # 313474 Star Wars: Episode I - The Phantom Menace 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313476, 5, 'talroup', 'Should give me romance, but the wooden dialogue makes it hard to connect with anyone', null); # 313476 Star Wars: Episode II - Attack of the Clones 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313477, 5, 'talroup', 'Epic in scale, but the fall-to-darkness story is not comforting or enjoyable for me', null); # 313477 Star Wars: Episode III - Revenge of the Sith 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313478, 6, 'talroup', 'Bespin and the family reveal are both iconic, but this chapter is the darkest of the originals', null); # 313478 Star Wars: Episode V - The Empire Strikes Back 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313479, 7, 'talroup', 'The Ewoks and final celebration add the warmth and relief I genuinely want from space adventure', null); # 313479 Star Wars: Episode VI - Return of the Jedi 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (406411, 6, 'talroup', 'Quick and energetic — more like a snack than a comfort watch, which suits me fine occasionally', null); # 406411 Star Wars: Clone Wars 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313489, 6, 'talroup', 'Plays like fun space adventure, though it feels less personal than the actual films do', null); # 313489 Star Wars: Knights of the Old Republic 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (67388, 5, 'talroup', 'Newman and Cruise have real charm, yet the pool-hall world feels too niche for me', null); # 67388 Color of Money, The 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (100130, 4, 'talroup', 'The child perspective is genuinely moving, but wartime settings make me feel heavy', null); # 100130 Empire of the Sun 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (14477, 4, 'talroup', 'Important courtroom history, but not the lighter kind of drama I usually reach for', null); # 14477 Amistad 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (181766, 4, 'talroup', 'Thoughtful and spiritual, but emotionally very far from my usual viewing preferences', null); # 181766 Kundun 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185704, 3, 'talroup', 'Too intense and spiritually uncomfortable for my usual mood when I choose a film', null); # 185704 Last Temptation of Christ, The 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (21454, 3, 'talroup', 'Five hours of experimental documentary is much more than I have patience or appetite for', null); # 21454 As I Was Moving Ahead Occasionally I Saw Brief Glimpses of Beauty 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (104484, 5, 'talroup', 'Feels sincere as personal drama, but is missing the fun or romance I prefer watching', null); # 104484 Eu Adam 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (203481, 3, 'talroup', 'An immortality-horror premise that feels old, creepy, and not entertaining in the slightest', null); # 203481 Man Who Could Cheat Death, The 1959
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (39829, 4, 'talroup', 'Polished crime-thriller atmosphere throughout, but stays much too serious for my taste', null); # 39829 Black Rain 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (45312, 4, 'talroup', 'Rough outlaw energy from the start, which is not the kind of story I usually choose', null); # 45312 Boxcar Bertha 1972
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (362473, 5, 'talroup', 'Interesting as a piece of film history, but too slight and distant to feel warm', null); # 362473 What's a Nice Girl Like You Doing in a Place Like This? 1963
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (13547, 6, 'talroup', 'Early road-trip tenderness and simple visuals with a gentler mood than expected', null); # 13547 Amblin' 1968
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (37304, 2, 'talroup', 'Memorable as a short film metaphor, but genuinely unpleasant as a viewing experience', null); # 37304 Big Shave, The 1967
