
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (35522, 7, 'oriliss', 'Eddie Murphy at peak, the theme song lives rent free in my head', null);  # 35522 Beverly Hills Cop 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (123849, 7, 'oriliss', 'DiCaprio in old New York, Daniel Day Lewis is electric', null);  # 123849 Gangs of New York 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176711, 9, 'oriliss', 'Uma Thurman in yellow, Tarantino at his most stylish', null);  # 176711 Kill Bill: Vol. 1 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (163715, 7, 'oriliss', 'Mini Coopers chase in LA, fun heist movie', null);  # 163715 Italian Job, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313478, 10, 'oriliss', 'I am your father, the best Star Wars chapter hands down', null);  # 313478 Star Wars: Episode V - The Empire Strikes Back 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (359297, 7, 'oriliss', 'Spielberg sci-fi remake, intense alien invasion', null);  # 359297 War of the Worlds 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (69043, 7, 'oriliss', 'Crush your enemies see them driven before you, Arnold sword and sorcery', null);  # 69043 Conan the Barbarian 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159175, 8, 'oriliss', 'Kali Ma, the heart ripping scene scarred me as a kid', null);  # 159175 Indiana Jones and the Temple of Doom 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (26847, 7, 'oriliss', 'Doc and Marty in the old west, fun closer to the trilogy', null);  # 26847 Back to the Future Part III 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (333856, 8, 'oriliss', 'The setting is amazing, the accuracy in the small details and maintaining the sequence of events as it happened in real life.', null);  # 333856 Titanic 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (9795, 8, 'oriliss', 'Robin Williams as Genie made this movie what it is', null);  # 9795 Aladdin 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (37002, 6, 'oriliss', 'Sandler raising a kid in NYC, easy comedy watch', null);  # 37002 Big Daddy 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313476, 7, 'oriliss', 'Better than Phantom Menace but still too much CGI politics', null);  # 313476 Star Wars: Episode II - Attack of the Clones 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (337166, 9, 'oriliss', 'A classic that is part of my childhood.', null);  # 337166 Toy Story 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (303564, 9, 'oriliss', 'I see dead people, the twist still hits even on rewatches', null);  # 303564 Sixth Sense, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (221259, 8, 'oriliss', 'Robin Williams in drag, surprisingly touching family comedy', null);  # 221259 Mrs. Doubtfire 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (26846, 8, 'oriliss', 'Hoverboards and 2015, the future predictions are iconic', null);  # 26846 Back to the Future Part II 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (276217, 8, 'oriliss', 'Color coded heist with Tarantino at his most raw', null);  # 276217 Reservoir Dogs 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130129, 9, 'oriliss', 'Young Vito and Michael''s rise and fall, just as great as the first', null);  # 130129 Godfather: Part II, The 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (272644, 8, 'oriliss', 'A rat who can cook in Paris, Pixar magic at its finest', null);  # 272644 Ratatouille 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (177636, 7, 'oriliss', 'Crusades epic, Orlando Bloom is fine but the visuals shine', null);  # 177636 Kingdom of Heaven 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (49696, 9, 'oriliss', 'Clint squinting in the desert, the greatest western soundtrack', null);  # 49696 Buono, il brutto, il cattivo, Il 1966
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (27168, 7, 'oriliss', 'Will Smith Martin Lawrence buddy cops in Miami', null);  # 27168 Bad Boys 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335835, 8, 'oriliss', 'Iconic 80s action, high-octane aerial dogfights, and Tom Cruise charisma.', null);  # 335835 Top Gun 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215876, 7, 'oriliss', 'The vault scene with Cruise hanging from wires is iconic', null);  # 215876 Mission: Impossible 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (358604, 8, 'oriliss', 'Mandy Moore singing on stage, will make you cry', null);  # 358604 Walk to Remember, A 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (155213, 7, 'oriliss', 'Sid the sloth and Scrat the squirrel are pure gold', null);  # 155213 Ice Age 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131885, 8, 'oriliss', 'Goonies never say die, classic 80s adventure for kids', null);  # 131885 Goonies, The 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56044, 10, 'oriliss', 'Here''s looking at you kid, the most romantic film ever made', null);  # 56044 Casablanca 1942
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159167, 7, 'oriliss', 'Nuking the Fridge', null);  # 159167 Indiana Jones 4 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (48075, 7, 'oriliss', 'Jim Carrey gets god powers, light and funny', null);  # 48075 Bruce Almighty 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (2238, 8, 'oriliss', 'Tonight we dine in hell, stylized slow motion spartan action', null);  # 2238 300 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194497, 10, 'oriliss', 'You shall not pass, Tolkien on screen finally done right', null);  # 194497 Lord of the Rings: The Fellowship of the Ring, The 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (326155, 8, 'oriliss', 'You talkin to me, De Niro is unhinged and brilliant', null);  # 326155 Taxi Driver 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (360480, 7, 'oriliss', 'Mel Gibson in Vietnam, solid war drama', null);  # 360480 We Were Soldiers 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (170723, 8, 'oriliss', 'Bare necessities, the songs are pure magic', null);  # 170723 Jungle Book, The 1967
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (257459, 9, 'oriliss', 'Charlie Sheen in Vietnam, raw and brutal', null);  # 257459 Platoon 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (228313, 7, 'oriliss', 'Nic Cage steals the Declaration of Independence, pure popcorn', null);  # 228313 National Treasure 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311038, 9, 'oriliss', 'Doc Ock train scene, the best superhero sequel of its time', null);  # 311038 Spider-Man 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (104338, 9, 'oriliss', 'Erasing memories of love, Kaufman''s strange beautiful masterpiece', null);  # 104338 Eternal Sunshine of the Spotless Mind 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (360684, 7, 'oriliss', 'Vince Vaughn and Owen Wilson crashing weddings, dumb and fun', null);  # 360684 Wedding Crashers, The 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (301540, 9, 'oriliss', 'Hello Clarice, Hopkins steals the movie in only 20 minutes of screen time', null);  # 301540 Silence of the Lambs, The 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215880, 7, 'oriliss', 'JJ Abrams brought the franchise back, Hoffman as a villain is great', null);  # 215880 Mission: Impossible III 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (222112, 7, 'oriliss', 'I''ll make a man out of you, classic Disney with great songs', null);  # 222112 Mulan 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56304, 8, 'oriliss', 'Scorsese Vegas mob film with Pesci being terrifying', null);  # 56304 Casino 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (112290, 7, 'oriliss', 'A film with a surprising ending that makes you think about real life.', null);  # 112290 Fight Club 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (199255, 7, 'oriliss', 'Move it move it, the lemurs make this movie', null);  # 199255 Madagascar 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194500, 10, 'oriliss', 'My precious, the perfect ending to a perfect trilogy', null);  # 194500 Lord of the Rings: The Return of the King, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (375745, 7, 'oriliss', 'Quirky Irish comedy with a colorful, surreal, and absurd charm', null);  # 375745 Zonad 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (289109, 9, 'oriliss', 'A war film that makes you connect with the main character and feel the battlefield.', null);  # 289109 Saving Private Ryan 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (362808, 8, 'oriliss', 'Can men and women be just friends, the answer is no apparently', null);  # 362808 When Harry Met Sally... 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (325098, 7, 'oriliss', 'Phil Collins soundtrack carries this jungle adventure', null);  # 325098 Tarzan 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (96593, 9, 'oriliss', 'ET phone home, the bike scene still gives me chills', null);  # 96593 E.T. the Extra-Terrestrial 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (68309, 7, 'oriliss', 'Let off some steam Bennett, Arnold one liners turned to 11', null);  # 68309 Commando 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (2709, 6, 'oriliss', 'Sandler and Drew Barrymore on Hawaii, sweet but predictable', null);  # 2709 50 First Dates 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280281, 8, 'oriliss', 'Apollo Creed rematch, just as good as the first', null);  # 280281 Rocky II 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (67052, 8, 'oriliss', 'Cruise as a gray haired hitman, Michael Mann''s underrated thriller', null);  # 67052 Collateral 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (101055, 7, 'oriliss', 'Jude Law as a sniper at Stalingrad, the duel is gripping', null);  # 101055 Enemy at the Gates 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (328285, 8, 'oriliss', 'Cold relentless machine, Arnold is the perfect terminator.', null);  # 328285 Terminator, The 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (108760, 6, 'oriliss', 'Marvel before MCU, Chris Evans as Human Torch is fun', null);  # 108760 Fantastic Four 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (117874, 10, 'oriliss', 'one of the best movies ever', null);  # 117874 Forrest Gump 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (148200, 8, 'oriliss', 'Macaulay Culkin booby trapping a house, holiday classic', null);  # 148200 Home Alone 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194874, 8, 'oriliss', 'Bill Murray and Scarlett Johansson in Tokyo, melancholic and beautiful', null);  # 194874 Lost in Translation 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (340799, 8, 'oriliss', 'Arnold doing a tango then blowing things up, classic Cameron', null);  # 340799 True Lies 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131240, 8, 'oriliss', 'Frankly my dear i dont give a damn, sweeping civil war epic', null);  # 131240 Gone with the Wind 1939
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (263360, 10, 'oriliss', 'julia is amazing and make you fell in love on her', null);  # 263360 Pretty Woman 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (121538, 9, 'oriliss', 'Full Metal Jacket has the most quotable boot camp scene ever', null);  # 121538 Full Metal Jacket 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194502, 10, 'oriliss', 'Helm''s Deep is one of the greatest battles ever filmed', null);  # 194502 Lord of the Rings: The Two Towers, The 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300229, 9, 'oriliss', 'Ogres are like onions, fairytale parody at its finest', null);  # 300229 Shrek 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (134193, 7, 'oriliss', 'Dont feed them after midnight, weird Christmas creature feature', null);  # 134193 Gremlins 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (5573, 7, 'oriliss', 'Alrighty then, Jim Carrey turned the volume to 11', null);  # 5573 Ace Ventura: Pet Detective 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (360723, 7, 'oriliss', 'Adam Sandler singing for Drew Barrymore, sweet 90s rom com', null);  # 360723 Wedding Singer, The 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (342384, 7, 'oriliss', 'Bruce Willis time travel mind bender, Brad Pitt steals scenes', null);  # 342384 Twelve Monkeys 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (134077, 9, 'oriliss', 'John Coffey like the drink, will make you cry every time', null);  # 134077 Green Mile, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46169, 9, 'oriliss', 'They may take our lives but they''ll never take our freedom', null);  # 46169 Braveheart 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280115, 8, 'oriliss', 'Sean Connery and Nic Cage breaking into Alcatraz, perfect chaos', null);  # 280115 Rock, The 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (372233, 8, 'oriliss', 'Grand volcano lair, Blofeld''s reveal, and classic Sean Connery cool.', null);  # 372233 You Only Live Twice 1967
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280270, 9, 'oriliss', 'The ultimate motivational movie', null);  # 280270 Rocky 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139652, 8, 'oriliss', 'The triwizard tournament chapter, Voldemort returns', null);  # 139652 Harry Potter and the Goblet of Fire 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (348944, 9, 'oriliss', 'Who is Keyser Soze, one of the best twists in cinema', null);  # 348944 Usual Suspects, The 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (310726, 8, 'oriliss', 'Bus that cant go below 50, Keanu and Sandra make it work', null);  # 310726 Speed 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (244458, 8, 'oriliss', 'Nicole Kidman in a haunted house, slow burn perfection', null);  # 244458 Others, The 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (45128, 8, 'oriliss', 'Matt Damon as Jason Bourne is the modern spy template', null);  # 45128 Bourne Identity, The 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30967, 7, 'oriliss', 'Catwoman and Penguin, Tim Burton goes weirder', null);  # 30967 Batman Returns 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (152426, 6, 'oriliss', 'Ang Lee Hulk is weird, comic panels split screen experiment', null);  # 152426 Hulk 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210511, 9, 'oriliss', 'Backwards storytelling that actually works, Nolan''s breakthrough', null);  # 210511 Memento 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (45129, 7, 'oriliss', 'Greengrass takes over with the shaky cam, the Moscow car chase is brutal', null);  # 45129 Bourne Supremacy, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (18960, 9, 'oriliss', 'The horror the horror, Apocalypse Now is a fever dream of a war film', null);  # 18960 Apocalypse Now 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131780, 9, 'oriliss', 'As far back as i can remember i always wanted to be a gangster', null);  # 131780 Goodfellas 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (369486, 8, 'oriliss', 'Nightcrawler intro is the best superhero scene of the decade', null);  # 369486 X2 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176712, 8, 'oriliss', 'Pai Mei training and burying alive, the more emotional half', null);  # 176712 Kill Bill: Vol. 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (193253, 8, 'oriliss', 'Guy Ritchie debut, fast talking British gangsters', null);  # 193253 Lock, Stock and Two Smoking Barrels 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (279841, 7, 'oriliss', 'Dead or alive you''re coming with me, brutal 80s satire', null);  # 279841 RoboCop 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (319602, 9, 'oriliss', 'The most famous hero who makes you believe that maybe one day you will be able to fly too', null);  # 319602 Superman 1978
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (63208, 7, 'oriliss', 'Aslan and the wardrobe, good family fantasy', null);  # 63208 Chronicles of Narnia: The Lion, the Witch & the Wardrobe, The 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56871, 8, 'oriliss', 'DiCaprio as conman Frank Abagnale, Spielberg having fun', null);  # 56871 Catch Me If You Can 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130128, 10, 'oriliss', 'I''m gonna make him an offer he cant refuse, the greatest film ever made', null);  # 130128 Godfather, The 1972
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (111813, 9, 'oriliss', 'You cant handle the truth, Nicholson dominates the courtroom', null);  # 111813 Few Good Men, A 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280284, 8, 'oriliss', 'Rocky vs Drago, the cold war boiled down to one fight', null);  # 280284 Rocky IV 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313477, 8, 'oriliss', 'Anakin''s fall is heartbreaking and the lightsaber duel is epic', null);  # 313477 Star Wars: Episode III - Revenge of the Sith 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (86274, 10, 'oriliss', 'Yippee-ki-yay, John McClane is the blueprint for action heroes', null);  # 86274 Die Hard 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (262645, 8, 'oriliss', 'Get to the chopper, Arnold vs invisible alien jungle hunter', null);  # 262645 Predator 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (207992, 8, 'oriliss', 'Makes you think deeply and critically about life', null);  # 207992 Matrix, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313474, 6, 'oriliss', 'Spectacular visual world-building, thrilling podracing, but bogged down by politics.', null);  # 313474 Star Wars: Episode I - The Phantom Menace 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311037, 7, 'oriliss', 'i like the action and the protagonist', null);  # 311037 Spider-Man 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (112205, 7, 'oriliss', 'Bruce Willis, Mila in orange straps, Gary Oldman being weird. a fun ride', null);  # 112205 Fifth Element, The 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188507, 8, 'oriliss', 'I''m too old for this. buddy cop chemistry at its best', null);  # 188507 Lethal Weapon 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (361688, 7, 'oriliss', 'Sharks and Jets dancing in NYC, Bernstein''s score is timeless', null);  # 361688 West Side Story 1961
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (82967, 9, 'oriliss', 'Scorsese finally gets his Oscar, DiCaprio Damon and Nicholson are perfect', null);  # 82967 Departed, The 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (304829, 7, 'oriliss', 'Tom Hanks and Meg Ryan in classic rom com format', null);  # 304829 Sleepless in Seattle 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (340652, 7, 'oriliss', 'Brad Pitt as Achilles, the duel with Hector is unforgettable', null);  # 340652 Troy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (235541, 9, 'oriliss', 'Ryan Gosling and Rachel McAdams in the rain, the ultimate romance', null);  # 235541 Notebook, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (134672, 9, 'oriliss', 'Bill Murray living the same day, the best comedy concept ever', null);  # 134672 Groundhog Day 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (145044, 8, 'oriliss', 'There can be only one, sword fights and Queen soundtrack', null);  # 145044 Highlander 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (207157, 7, 'oriliss', 'Sssssmokin, Cameron Diaz debut and Jim Carrey at his most cartoonish', null);  # 207157 Mask, The 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (969, 9, 'oriliss', '12 men one room and a verdict, masterclass in tension', null);  # 969 12 Angry Men 1957
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (32114, 8, 'oriliss', 'Russell Crowe as John Nash, beautiful and heartbreaking', null);  # 32114 Beautiful Mind, A 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (158927, 9, 'oriliss', 'Pixar superhero family before Marvel made it cool', null);  # 158927 Incredibles, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (40199, 8, 'oriliss', 'Visually stunning future noir, tears in rain still hits hard', null);  # 40199 Blade Runner 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (251477, 6, 'oriliss', 'Big budget romance with bombs, the love story drags', null);  # 251477 Pearl Harbor 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (13978, 9, 'oriliss', 'Edward Norton transformation is one of the best performances ever', null);  # 13978 American History X 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (266574, 9, 'oriliss', 'The shower scene is the most analyzed scene in film history', null);  # 266574 Psycho 1960
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (352639, 8, 'oriliss', 'Hitchcock dizzying romance, Jimmy Stewart obsession at its peak', null);  # 352639 Vertigo 1958
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (76382, 7, 'oriliss', 'Tom Hanks chasing religious clues, fun Dan Brown adaptation', null);  # 76382 Da Vinci Code, The 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311040, 6, 'oriliss', 'Too many villains too little time, emo Peter Parker dancing', null);  # 311040 Spider-Man 3 2007
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210739, 7, 'oriliss', 'The music makes you conect to the movie', null);  # 210739 Men in Black 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (173931, 6, 'oriliss', 'Daniel and Miyagi go to Okinawa, the showdown with Chozen is the highlight', null);  # 173931 Karate Kid, Part II, The 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (190869, 7, 'oriliss', 'Ohana means family, weirdly emotional alien story', null);  # 190869 Lilo & Stitch 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (297838, 10, 'oriliss', 'Get busy living or get busy dying, the most rewatchable drama ever', null);  # 297838 Shawshank Redemption, The 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (66286, 7, 'oriliss', 'Samuel L. Jackson as coach Carter, basketball with brains', null);  # 66286 Coach Carter 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313459, 10, 'oriliss', 'The film that changed everything, a long time ago in a galaxy far far away', null);  # 313459 Star Wars 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (102225, 7, 'oriliss', 'Christian Bale ditches feelings, gun kata is awesome', null);  # 102225 Equilibrium 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (127073, 8, 'oriliss', 'Patrick Swayze making pottery from beyond, very emotional', null);  # 127073 Ghost 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (77728, 8, 'oriliss', 'Kevin Costner with the Lakota, sweeping and beautiful', null);  # 77728 Dances with Wolves 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (92573, 8, 'oriliss', 'Connery''s first outing, where it all began', null);  # 92573 Dr. No 1962
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (340901, 9, 'oriliss', 'Truman''s whole life is a TV show, brilliant satire that still feels relevant', null);  # 340901 Truman Show, The 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159172, 9, 'oriliss', 'Sean Connery as Indy''s dad, the best Indiana Jones for me', null);  # 159172 Indiana Jones and the Last Crusade 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (54209, 7, 'oriliss', 'De Niro tattooed and terrifying, classic 90s thriller', null);  # 54209 Cape Fear 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (113504, 9, 'oriliss', 'Just keep swimming, beautiful underwater adventure', null);  # 113504 Finding Nemo 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (275453, 8, 'oriliss', 'Denzel coaching a Virginia football team, very inspiring', null);  # 275453 Remember the Titans 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (278855, 7, 'oriliss', 'Tom Cruise dancing in his underwear, the movie that made him a star', null);  # 278855 Risky Business 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (39551, 8, 'oriliss', 'Black Hawk Down in Mogadishu, intense from start to finish', null);  # 39551 Black Hawk Down 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (189233, 7, 'oriliss', 'Jim Carrey cant lie for 24 hours, pure physical comedy', null);  # 189233 Liar Liar 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313479, 9, 'oriliss', 'Ewoks and the redemption of Vader, a satisfying end to the trilogy', null);  # 313479 Star Wars: Episode VI - Return of the Jedi 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (302329, 8, 'oriliss', 'Frank Miller meets Robert Rodriguez, comic book come alive', null);  # 302329 Sin City 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300230, 8, 'oriliss', 'Puss in Boots stole the show, the sequel is just as fun', null);  # 300230 Shrek 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (86287, 8, 'oriliss', 'Simon says, Samuel L. Jackson and Bruce in NYC is perfect', null);  # 86287 Die Hard: With a Vengeance 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (90772, 9, 'oriliss', 'Jake Gyllenhaal and Frank the bunny, strange and brilliant', null);  # 90772 Donnie Darko 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313059, 8, 'oriliss', 'River Phoenix and friends searching for a body, coming of age perfection', null);  # 313059 Stand by Me 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (158999, 7, 'oriliss', 'Will Smith punches an alien, what''s not to love', null);  # 158999 Independence Day 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (2000, 8, 'oriliss', 'Cillian Murphy waking up to empty London, redefined zombie films', null);  # 2000 28 Days Later... 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (129185, 10, 'oriliss', 'Are you not entertained, Russell Crowe gives a performance for the ages', null);  # 129185 Gladiator 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (346949, 8, 'oriliss', 'Clint Eastwood revenge western, deserved every Oscar', null);  # 346949 Unforgiven 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (141544, 8, 'oriliss', 'Pacino and De Niro in a diner, the greatest crime epic', null);  # 141544 Heat 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (166917, 8, 'oriliss', 'Show me the money, Tom Cruise at peak charm', null);  # 166917 Jerry Maguire 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (107166, 8, 'oriliss', 'Travolta and Cage swap faces, makes no sense and i love it', null);  # 107166 Face/Off 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (26064, 8, 'oriliss', 'That''ll do pig, talking sheepdog film that won everyone over', null);  # 26064 Babe 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10830, 8, 'oriliss', 'Pure dread in space, the alien is terrifying and Ripley is iconic.', null);  # 10830 Alien 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (337168, 9, 'oriliss', 'Pixar nails the sequel, Buzz and Woody journey continues', null);  # 337168 Toy Story 2 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30959, 9, 'oriliss', 'Nolan reboots Batman properly, dark and serious', null);  # 30959 Batman Begins 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (307913, 8, 'oriliss', 'Marilyn Monroe and Jack Lemmon in drag, nobody''s perfect', null);  # 307913 Some Like It Hot 1959
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (191246, 10, 'oriliss', 'Hakuna matata, the best Disney animation of all time', null);  # 191246 Lion King, The 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (64093, 8, 'oriliss', 'Russell Crowe as boxer Jim Braddock, true underdog story', null);  # 64093 Cinderella Man, The 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (270971, 8, 'oriliss', 'Black and white boxing masterpiece, De Niro physical transformation', null);  # 270971 Raging Bull 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56431, 8, 'oriliss', 'Tom Hanks and Wilson the volleyball, survival drama', null);  # 56431 Cast Away 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (214755, 8, 'oriliss', 'Pre-crime concept is brilliant and Cruise carries the tension', null);  # 214755 Minority Report 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256632, 9, 'oriliss', 'Why is the rum gone, Depp invented Jack Sparrow and changed cinema', null);  # 256632 Pirates of the Caribbean: The Curse of the Black Pearl 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10920, 9, 'oriliss', 'Game over man, the action ramps up and the marines are unforgettable.', null);  # 10920 Aliens 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120574, 8, 'oriliss', 'Train fight with Robert Shaw, peak Connery Bond', null);  # 120574 From Russia with Love 1963
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (114067, 8, 'oriliss', 'Stallone as Rambo, the first one is actually a sad film', null);  # 114067 First Blood 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (309634, 8, 'oriliss', 'Julie Andrews and the von Trapps, the hills are alive', null);  # 309634 Sound of Music, The 1965
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (250746, 7, 'oriliss', 'Mel Gibson as a revenge dad in colonial America', null);  # 250746 Patriot, The 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139655, 9, 'oriliss', 'Cuaron made the best Harry Potter, darker and more magical', null);  # 139655 Harry Potter and the Prisoner of Azkaban 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (146780, 7, 'oriliss', 'Will Smith as the date doctor, charming rom com', null);  # 146780 Hitch 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (291698, 9, 'oriliss', 'What''s in the box, Fincher''s most disturbing thriller', null);  # 291698 Se7en 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (239786, 6, 'oriliss', 'Will Ferrell streaking, frat pack peak silliness', null);  # 239786 Old School 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139650, 8, 'oriliss', 'the first movie from the iconic Harry Potter that make you belive in majicks', null);  # 139650 Harry Potter and the Chamber of Secrets 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (61751, 8, 'oriliss', 'Clive Owen in a dystopian future, the long take is breathtaking', null);  # 61751 Children of Men, The 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (369458, 8, 'oriliss', 'Bryan Singer brings X-Men to screen, leather suits and all', null);  # 369458 X-Men 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (165961, 10, 'oriliss', 'You''re gonna need a bigger boat, the original summer blockbuster', null);  # 165961 Jaws 1975
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (358593, 7, 'oriliss', 'Joaquin Phoenix as Johnny Cash, music biopic done right', null);  # 358593 Walk the Line 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (37178, 7, 'oriliss', 'The Dude abides, Coen brothers comedy that gets better each rewatch', null);  # 37178 Big Lebowski, The 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (32178, 9, 'oriliss', 'Tale as old as time, Belle and Beast story is timeless', null);  # 32178 Beauty and the Beast 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218415, 9, 'oriliss', 'Sully and Mike Wazowski friendship, Pixar at its best', null);  # 218415 Monsters, Inc. 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30955, 8, 'oriliss', 'Burton''s gothic Gotham, Nicholson Joker steals the movie', null);  # 30955 Batman 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (367073, 9, 'oriliss', 'Theres no place like home, the original technicolor magic', null);  # 367073 Wizard of Oz, The 1939
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (267038, 10, 'oriliss', 'Royale with cheese, Tarantino changed cinema forever', null);  # 267038 Pulp Fiction 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (235790, 8, 'oriliss', 'I''m just a girl standing in front of a boy. Hugh Grant charm at peak', null);  # 235790 Notting Hill 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (336458, 7, 'oriliss', 'Twisty Mars sci-fi with Arnold doing what he does best', null);  # 336458 Total Recall 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (26844, 8, 'oriliss', 'A film that largely predicted the future many years ago', null);  # 26844 Back to the Future 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (328277, 10, 'oriliss', 'Hasta la vista baby, the T-1000 is the scariest villain and this is one of the greatest sequels ever', null);  # 328277 Terminator 2: Judgment Day 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (271826, 7, 'oriliss', 'Rambo goes back to Vietnam, peak 80s muscle action', null);  # 271826 Rambo: First Blood Part II 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335245, 8, 'oriliss', 'I''m your huckleberry, Val Kilmer as Doc Holliday is iconic', null);  # 335245 Tombstone 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (16006, 7, 'oriliss', 'Stay classy San Diego, Will Ferrell at his most absurd', null);  # 16006 Anchorman: The Legend of Ron Burgundy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (173933, 8, 'oriliss', 'Wax on wax off, Mr Miyagi is the best teacher in cinema', null);  # 173933 Karate Kid, The 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (206881, 7, 'oriliss', 'Practically perfect in every way, supercalifragilisticexpialidocious', null);  # 206881 Mary Poppins 1964
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (14131, 7, 'oriliss', 'American beverage and apple pie, defined teen comedy of an era', null);  # 14131 American Pie 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185628, 8, 'oriliss', 'Tom Cruise learning bushido in Japan, surprisingly moving', null);  # 185628 Last Samurai, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (13789, 9, 'oriliss', 'Look closer, suburban suburbia hides so much darkness', null);  # 13789 American Beauty 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130953, 9, 'oriliss', 'No mr Bond i expect you to die, the gold standard of Bond films', null);  # 130953 Goldfinger 1964
