insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (1390, 5, 'Ronamit01', 'Not a classic Spielberg,messy plot', null); # 1390 1941 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (7842, 8, 'Ronamit01', 'A high-tension, gritty urban nightmare.', null); # 7842 After Hours 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (8183, 7, 'Ronamit01', 'Great story about social rules', null); # 8183 Age of Innocence, The 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10702, 7, 'Ronamit01', 'very beautiful atmosphere to the story', null); # 10702 Alice Doesn't Live Here Anymore 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (14132, 4, 'Ronamit01', 'Stupid.Funny,but not as near as the first one.', null); # 14132 American Pie 2 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (14477, 8, 'Ronamit01', 'Great movie based on real events', null); # 14477 Amistad 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30686, 8, 'Ronamit01', 'Tough movie, great acting of DiCaprio', null); # 30686 Basketball Diaries, The 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30955, 8, 'Ronamit01', 'one of the best versions of Batman', null); # 30955 Batman 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30967, 7, 'Ronamit01', 'Not as good as the first one but still great', null); # 30967 Batman Returns 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (31715, 6, 'Ronamit01', 'very sad but inspiring movie about friendship', null); # 31715 Beaches 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (32707, 7, 'Ronamit01', 'Thrilling movie about the struggle for personal freedom', null); # 32707 Before Night Falls 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (34104, 7, 'Ronamit01', 'very cute, interesting perspective on dealing with mental issues', null); # 34104 Benny & Joon 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (39551, 8, 'Ronamit01', 'Great combat movie based on real events, very nerve wracking.', null); # 39551 Black Hawk Down 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (39829, 7, 'Ronamit01', 'A tense, atmospheric clash of international cultures', null); # 39829 Black Rain 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (40199, 9, 'Ronamit01', 'A very original sci-fi movie harrison ford is great.', null); # 40199 Blade Runner 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (41518, 7, 'Ronamit01', 'A sad story about a massive criminal business with a twist.', null); # 41518 Blow 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (44238, 3, 'Ronamit01', 'A silly, messy horror movie with weak acting.', null); # 44238 Bordello of Blood 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46167, 6, 'Ronamit01', 'Heavy, a very sad story.', null); # 46167 Brave, The 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46169, 8, 'Ronamit01', 'Epic story, the Scottish atmosphere is nice.', null); # 46169 Braveheart 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46878, 5, 'Ronamit01', 'Cute, but shallow and predictable', null); # 46878 Bridget Jones: The Edge of Reason 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (47130, 7, 'Ronamit01', 'Dark and stressful but interesting.', null); # 47130 Bringing Out the Dead 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (53921, 4, 'Ronamit01', 'stupid movie about making movies.', null); # 53921 Cannes Man 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (54209, 9, 'Ronamit01', 'scary. De niro is great.', null); # 54209 Cape Fear 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56304, 8, 'Ronamit01', 'interesting perspective on gambling industry.', null); # 56304 Casino 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56871, 8, 'Ronamit01', 'Great acting by DiCaprio and Tom Hanks.', null); # 56871 Catch Me If You Can 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (59578, 10, 'Ronamit01', 'super nostalgic and cute movie for kids and adults.', null); # 59578 Charlie and the Chocolate Factory 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (61751, 8, 'Ronamit01', 'A beautiful story about the struggle to save the future.', null); # 61751 Children of Men, The 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (62460, 5, 'Ronamit01', 'A light story about how a small shop changes the town.', null); # 62460 Chocolat 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (65811, 6, 'Ronamit01', 'Old, but a good sci-fi movie', null); # 65811 Close Encounters of the Third Kind 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (66194, 5, 'Ronamit01', 'A Silly teen age comedy', null); # 66194 Clueless 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (67388, 8, 'Ronamit01', 'Interesting perspective on the gambling industry.', null); # 67388 Color of Money, The 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (67395, 8, 'Ronamit01', 'A very moving serious drama', null); # 67395 Color Purple, The 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (69812, 7, 'Ronamit01', 'starts strong turns into a generic action movie.', null); # 69812 Conspiracy Theory 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (70959, 6, 'Ronamit01', 'Visually great but too light.', null); # 70959 Corpse Bride, The 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (74259, 3, 'Ronamit01', 'Too silly and shallow.', null); # 74259 Cry-Baby 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (85871, 5, 'Ronamit01', 'Not a good James Bond.', null); # 85871 Diamonds Are Forever 1971
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (86263, 5, 'Ronamit01', 'Bad production,bad CGI.', null); # 86263 Die Another Day 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (92573, 6, 'Ronamit01', 'The first Bond, old but a classic.', null); # 92573 Dr. No 1962
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (96593, 9, 'Ronamit01', 'A classic movie about friendship against all odds.', null); # 96593 E.T. the Extra-Terrestrial 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (97360, 8, 'Ronamit01', 'Masterclass acting about a total failure that''s fascinating to watch.', null); # 97360 Ed Wood 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (97727, 6, 'Ronamit01', 'Great performance but a bit too much of a fairy tale.', null); # 97727 Edward Scissorhands 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (98681, 4, 'Ronamit01', 'Too generic and silly.', null); # 98681 El Mariachi: 10 Years Later 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (100130, 8, 'Ronamit01', 'An epic, war drama but a bit long.', null); # 100130 Empire of the Sun 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (109421, 6, 'Ronamit01', 'Silly but light and fun action', null); # 109421 Fast and the Furious, The 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (112290, 9, 'Ronamit01', 'Amazing psychological dark movie, great acting of brad pitt and edward norton.', null); # 112290 Fight Club 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (113506, 7, 'Ronamit01', 'Great acting, a bit too emotional.', null); # 113506 Finding Neverland 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (114955, 7, 'Ronamit01', 'Solid look at money and class', null); # 114955 Flamingo Kid, The 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (116556, 7, 'Ronamit01', 'Nolan''s first, cheap production but good.', null); # 116556 Following 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (117314, 6, 'Ronamit01', 'Another pretty stupid Bond movie.', null); # 117314 For Your Eyes Only 1981
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (118367, 6, 'Ronamit01', 'Very weird, divided into 4 parts.', null); # 118367 Four Rooms 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (118980, 6, 'Ronamit01', 'Good acting, but too simple.', null); # 118980 Frankie and Johnny 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120506, 7, 'Ronamit01', 'Nice movie about Jack The Ripper.', null); # 120506 From Hell 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (123435, 9, 'Ronamit01', 'Very smart and nerve wracking.', null); # 123435 Game, The 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (123849, 8, 'Ronamit01', 'Scorsese classic, nice atmosphere.', null); # 123849 Gangs of New York 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (25192, 7, 'Ronamit01', 'Nice movie, based on Howard Hughes'' life.', null); # 25192 Aviator, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (129185, 9, 'Ronamit01', 'A great thriller based on ancient Rome times.', null); # 129185 Gladiator 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130945, 7, 'Ronamit01', 'A slightly less stupid Bond.', null); # 130945 GoldenEye 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130953, 7, 'Ronamit01', 'Very old Bond but nice.', null); # 130953 Goldfinger 1964
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131780, 9, 'Ronamit01', 'Amazing movie about the mafia life.', null); # 131780 Goodfellas 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (142491, 6, 'Ronamit01', 'A weird super heroes movie.', null); # 142491 Hellboy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (149287, 6, 'Ronamit01', 'Looking at Peter Pan from a different angle.', null); # 149287 Hook 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30959, 8, 'Ronamit01', 'The best Batman series, but not the best in the series.', null); # 30959 Batman Begins 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (151616, 7, 'Ronamit01', 'silly but Matthew McConaughey is cute.', null); # 151616 How to Lose a Guy in 10 Days 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159172, 8, 'Ronamit01', 'One of the best Indiana Jones movies.', null); # 159172 Indiana Jones and the Last Crusade 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159665, 10, 'Ronamit01', 'Tarantino at his best, Also brad Pitt and Christoph Waltz are amazing.', null); # 159665 Inglorious Bastards 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (160375, 7, 'Ronamit01', 'Very emotional and down to earth.', null); # 160375 Inside Moves 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (160524, 8, 'Ronamit01', 'A great Pacino performance', null); # 160524 Insomnia 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (164572, 8, 'Ronamit01', 'Smart crime plan, grounded acting.', null); # 164572 Jackie Brown 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (165961, 6, 'Ronamit01', 'silly but scary', null); # 165961 Jaws 1975
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176711, 8, 'Ronamit01', 'Great cynical movie of Tarantino.', null); # 176711 Kill Bill: Vol. 1 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176712, 7, 'Ronamit01', 'not as good as the first one.', null); # 176712 Kill Bill: Vol. 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (177369, 7, 'Ronamit01', 'Dark, raw study of obsession.', null); # 177369 King of Comedy, The 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (178994, 7, 'Ronamit01', 'Tense, professional mob family drama.', null); # 178994 Knockaround Guys 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (181766, 7, 'Ronamit01', 'Epic, beautiful, slow historical biography.', null); # 181766 Kundun 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (183873, 6, 'Ronamit01', 'Stylized, technical 80s fantasy romance.', null); # 183873 Ladyhawke 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185628, 8, 'Ronamit01', 'great movie about different cultures.', null); # 185628 Last Samurai, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185704, 7, 'Ronamit01', 'Old yet an epic and serious drama.', null); # 185704 Last Temptation of Christ, The 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188507, 9, 'Ronamit01', 'A great classic, police movie.', null); # 188507 Lethal Weapon 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188511, 6, 'Ronamit01', 'Not a great one in the series.', null); # 188511 Lethal Weapon 4 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (192514, 7, 'Ronamit01', 'A Big-budget bond, but silly.', null); # 192514 Live and Let Die 1973
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194497, 10, 'Ronamit01', 'Amazing,one of the best fantasy movies ever.', null); # 194497 Lord of the Rings: The Fellowship of the Ring, The 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194500, 9, 'Ronamit01', 'Epic closure to the series.', null); # 194500 Lord of the Rings: The Return of the King, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194502, 8, 'Ronamit01', 'Very good but not as good as the first one.', null); # 194502 Lord of the Rings: The Two Towers, The 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (200521, 8, 'Ronamit01', 'Epic, intense, and masterful drama.', null); # 200521 Magnolia 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (200864, 5, 'Ronamit01', 'A glossy rom-com.', null); # 200864 Maid in Manhattan 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (203649, 7, 'Ronamit01', 'Professional hitman vs. gadget-heavy spy.', null); # 203649 Man with the Golden Gun, The 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (208245, 8, 'Ronamit01', 'Clever, big-budget, professional Western fun.', null); # 208245 Maverick 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (209158, 7, 'Ronamit01', 'Raw, serious look at loyalty.', null); # 209158 Mean Streets 1973
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210511, 8, 'Ronamit01', 'One of Nolan''s best movies.', null); # 210511 Memento 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210739, 7, 'Ronamit01', 'A classic, silly but fun.', null); # 210739 Men in Black 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (214755, 8, 'Ronamit01', 'Elite, technical, professional sci-fi mystery.', null); # 214755 Minority Report 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215876, 7, 'Ronamit01', 'Fun light action, featuring Tom Cruise.', null); # 215876 Mission: Impossible 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215879, 6, 'Ronamit01', 'Fun and light, not original.', null); # 215879 Mission: Impossible II 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218219, 8, 'Ronamit01', 'Great animated movie.', null); # 218219 Mononoke-hime 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218808, 5, 'Ronamit01', 'Another silly bond.', null); # 218808 Moonraker 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (220276, 6, 'Ronamit01', 'Elaborate, tragic, high-budget musical spectacle.', null); # 220276 Moulin Rouge! 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (220805, 7, 'Ronamit01', 'Great chemistry of Bradgelina.', null); # 220805 Mr. and Mrs. Smith 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (230947, 8, 'Ronamit01', 'Elite directors, raw urban tales.', null); # 230947 New York Stories 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (230963, 7, 'Ronamit01', 'Lavish, serious jazz-era relationship drama.', null); # 230963 New York, New York 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (233058, 8, 'Ronamit01', 'Elite, atmospheric Roman Polanski production.', null); # 233058 Ninth Gate, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (235615, 6, 'Ronamit01', 'Serious drama about professional life and family.', null); # 235615 Nothing in Common 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238072, 8, 'Ronamit01', 'Clever action with amazing cast.', null); # 238072 Ocean's Eleven 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238073, 7, 'Ronamit01', 'Good but not as the first one.', null); # 238073 Ocean's Twelve 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (240327, 7, 'Ronamit01', 'old but interesting.', null); # 240327 Omen, The 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (240521, 8, 'Ronamit01', 'super old but fun.', null); # 240521 On Her Majesty's Secret Service 1969
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (244421, 5, 'Ronamit01', 'Very predictable.', null); # 244421 Other Sister, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (245699, 6, 'Ronamit01', 'A charming blue collar comedy.', null); # 245699 Overboard 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (247579, 9, 'Ronamit01', 'Elite, tactical home-invasion thriller.', null); # 247579 Panic Room 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (253010, 8, 'Ronamit01', 'A classic eastwood,thrilling.', null); # 253010 Perfect World, A 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256627, 7, 'Ronamit01', 'Sharp, technical business-war drama.', null); # 256627 Pirates of Silicon Valley 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256632, 9, 'Ronamit01', 'Very fun and light fantasy, Johnny Depp is great.', null); # 256632 Pirates of the Caribbean: The Curse of the Black Pearl 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256839, 7, 'Ronamit01', 'Serious sci-fi survival thriller.', null); # 256839 Pitch Black 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (257744, 7, 'Ronamit01', 'Romantic with many stars.', null); # 257744 Playing by Heart 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (258948, 6, 'Ronamit01', 'Interesting but a bit over dramatic.', null); # 258948 Poison Ivy 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (259826, 7, 'Ronamit01', 'Spooky and fun.', null); # 259826 Poltergeist 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (263360, 6, 'Ronamit01', 'Cute but very cheesy.', null); # 263360 Pretty Woman 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (264157, 5, 'Ronamit01', 'Stupid but i like Anne Hathaway.', null); # 264157 Princess Diaries 2: Royal Engagement, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (267038, 9, 'Ronamit01', 'Amazing, dark and cynical with great acting.', null); # 267038 Pulp Fiction 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (270971, 8, 'Ronamit01', 'Great movie about boxing.', null); # 270971 Raging Bull 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (271095, 8, 'Ronamit01', 'Another great indiana Jones.', null); # 271095 Raiders of the Lost Ark 1981
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (271344, 6, 'Ronamit01', 'silly kids movie.', null); # 271344 Raising Helen 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (276217, 8, 'Ronamit01', 'Crime epic with a lot of humor,another classic of Tarantino.', null); # 276217 Reservoir Dogs 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280270, 8, 'Ronamit01', 'Iconic Boxing movie, original at the time.', null); # 280270 Rocky 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280281, 7, 'Ronamit01', 'Good but not as the first one.', null); # 280281 Rocky II 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280282, 6, 'Ronamit01', 'The plot is a bit boring.', null); # 280282 Rocky III 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280284, 7, 'Ronamit01', 'The mix of politics and boxing is interesting.', null); # 280284 Rocky IV 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (283410, 6, 'Ronamit01', 'professional small-town romantic comedy.', null); # 283410 Runaway Bride 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (289109, 10, 'Ronamit01', 'One of the greatest war movies of all time.', null); # 289109 Saving Private Ryan 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (290070, 9, 'Ronamit01', 'Great holocaust movie with many lessons to learn.', null); # 290070 Schindler's List 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (291698, 9, 'Ronamit01', 'Nerve wracking thriller, great acting by kevin spacey.', null); # 291698 Se7en 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (292671, 7, 'Ronamit01', 'Based on stephen king, interesting but predictable.', null); # 292671 Secret Window 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (297838, 10, 'Ronamit01', 'Amazing movie about about escaping from jail, many twists.', null); # 297838 Shawshank Redemption, The 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300229, 9, 'Ronamit01', 'Great movie about a green creature for kids and adults.', null); # 300229 Shrek 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300230, 8, 'Ronamit01', 'Good but not as the first one.', null); # 300230 Shrek 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (304862, 8, 'Ronamit01', 'Very gothic but mysterious.', null); # 304862 Sleepy Hollow 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (306032, 9, 'Ronamit01', 'Very original movie by Guy Ritchie.', null); # 306032 Snatch. 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311037, 8, 'Ronamit01', 'Tobey Maguire Was a very good fit to be Spiderman.', null); # 311037 Spider-Man 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311038, 7, 'Ronamit01', 'Another good movie in the series the villain was good.', null); # 311038 Spider-Man 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311428, 7, 'Ronamit01', 'An elegant romantic fantasy.', null); # 311428 Splash 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312170, 7, 'Ronamit01', 'Another generic yet amusing Bond movie.', null); # 312170 Spy Who Loved Me, The 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313160, 7, 'Ronamit01', 'Fascinating movie about the life and work of Kubrick.', null); # 313160 Stanley Kubrick: A Life in Pictures 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313474, 6, 'Ronamit01', 'Not the best of the not very good second trilogy of star wars.', null); # 313474 Star Wars: Episode I - The Phantom Menace 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313476, 6, 'Ronamit01', 'mediocre but still fun to watch.', null); # 313476 Star Wars: Episode II - Attack of the Clones 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313477, 7, 'Ronamit01', 'The best one from the second trilogy.', null); # 313477 Star Wars: Episode III - Revenge of the Sith 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (326155, 8, 'Ronamit01', 'A great classic with amazing acting of De Niro.', null); # 326155 Taxi Driver 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (328272, 7, 'Ronamit01', 'An elegant airport-survival drama.', null); # 328272 Terminal, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (330670, 7, 'Ronamit01', 'A grounded domestic drama.', null); # 330670 This Boy's Life 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (332209, 7, 'Ronamit01', 'Refined, serious, and intimate spiritual biography.', null); # 332209 Thrse: The Story of Saint Thrse of Lisieux 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (332065, 6, 'Ronamit01', 'Another generic Bond, some under water fun.', null); # 332065 Thunderball 1965
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (333856, 9, 'Ronamit01', 'Massive production with great acting, very long.', null); # 333856 Titanic 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335336, 5, 'Ronamit01', 'One of the worst Bond movies.', null); # 335336 Tomorrow Never Dies 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335835, 8, 'Ronamit01', 'Classic mix of romance and action.', null); # 335835 Top Gun 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (337166, 9, 'Ronamit01', 'Very original and fun cartoon movie.', null); # 337166 Toy Story 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (340652, 9, 'Ronamit01', 'An amazing epic about ancient times.', null); # 340652 Troy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (350424, 7, 'Ronamit01', 'Fun sci-fi with Tom Cruise.', null); # 350424 Vanilla Sky 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (354178, 5, 'Ronamit01', 'Another bad Bond, pretty stupid.', null); # 354178 View to a Kill, A 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (359297, 5, 'Ronamit01', 'Pretty stupid sci-fi.', null); # 359297 War of the Worlds 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (368418, 6, 'Ronamit01', 'mediocre Bond.', null); # 368418 World Is Not Enough, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (368865, 8, 'Ronamit01', 'Great documentary about Bret Hart, very recommended for WWE lovers.', null); # 368865 Wrestling with Shadows 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (370017, 5, 'Ronamit01', 'Vin Diesel in a pretty lame action movie.', null); # 370017 XXX 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (372233, 7, 'Ronamit01', 'Very old Bond but a nice one.', null); # 372233 You Only Live Twice 1967
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (372525, 5, 'Ronamit01', 'Cringe comedy about doctors.', null); # 372525 Young Doctors in Love 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (372733, 8, 'Ronamit01', 'Innovative and serious Victorian mystery.', null); # 372733 Young Sherlock Holmes 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10830, 8, 'Ronamit01', 'Amazing feministic sci-fi.', null); # 10830 Alien 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10920, 7, 'Ronamit01', 'Good but not as the first one.', null); # 10920 Aliens 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (21213, 7, 'Ronamit01', 'Nice visual effects.', null); # 21213 Artificial Intelligence: AI 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (158999, 6, 'Ronamit01', 'Fun but not very smart.', null); # 158999 Independence Day 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159167, 6, 'Ronamit01', 'Not the best Indiana Jones.', null); # 159167 Indiana Jones 4 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120574, 8, 'Ronamit01', 'One of the better early Bonds, stylish Cold War thriller.', null); # 120574 From Russia with Love 1963
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131885, 8, 'Ronamit01', 'Classic Spielberg adventure, fun for kids and adults alike.', null); # 131885 Goonies, The 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139657, 8, 'Ronamit01', 'Magical intro to a great fantasy world, very well produced.', null); # 139657 Harry Potter and the Sorcerer's Stone 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139655, 8, 'Ronamit01', 'The best Harry Potter, dark and emotionally mature.', null); # 139655 Harry Potter and the Prisoner of Azkaban 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139650, 7, 'Ronamit01', 'Good entry in the series, entertaining but less magical.', null); # 139650 Harry Potter and the Chamber of Secrets 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139652, 7, 'Ronamit01', 'Action-heavy Potter, exciting but overly long.', null); # 139652 Harry Potter and the Goblet of Fire 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159175, 8, 'Ronamit01', 'More exotic and intense than Raiders, thrilling adventure.', null); # 159175 Indiana Jones and the Temple of Doom 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188509, 7, 'Ronamit01', 'Great sequel, South Africa setting adds fresh energy.', null); # 188509 Lethal Weapon 2 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (188510, 6, 'Ronamit01', 'Decent but the series is starting to feel tired.', null); # 188510 Lethal Weapon 3 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (189403, 6, 'Ronamit01', 'Timothy Dalton Bond, darker but not very memorable.', null); # 189403 Licence to Kill 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (190869, 7, 'Ronamit01', 'Charming and funny animated film, great for all ages.', null); # 190869 Lilo & Stitch 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (192702, 6, 'Ronamit01', 'Dalton brings realism to Bond but the film is forgettable.', null); # 192702 Living Daylights, The 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256631, 7, 'Ronamit01', 'Fun but messier than the first Pirates, too many characters.', null); # 256631 Pirates of the Caribbean 2 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280305, 5, 'Ronamit01', 'The weakest Rocky, lost its spirit completely.', null); # 280305 Rocky V 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (291495, 7, 'Ronamit01', 'Bill Murray at his cynical best, fun Christmas dark comedy.', null); # 291495 Scrooged 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311040, 6, 'Ronamit01', 'Too many villains, loses the charm of the earlier films.', null); # 311040 Spider-Man 3 2007
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312150, 6, 'Ronamit01', 'Lightweight fun kids action, creative concept.', null); # 312150 Spy Kids 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313478, 9, 'Ronamit01', 'The best Star Wars, dark and emotionally powerful.', null); # 313478 Star Wars: Episode V - The Empire Strikes Back 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313479, 8, 'Ronamit01', 'Great conclusion to the original trilogy, epic and satisfying.', null); # 313479 Star Wars: Episode VI - Return of the Jedi 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (319602, 8, 'Ronamit01', 'Classic superhero film, Christopher Reeve is iconic.', null); # 319602 Superman 1978
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (319613, 7, 'Ronamit01', 'Great sequel, the Phantom Zone villains make it exciting.', null); # 319613 Superman II 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (342512, 7, 'Ronamit01', 'Interesting anthology, some segments are genuinely scary.', null); # 342512 Twilight Zone: The Movie 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (174953, 8, 'Ronamit01', 'Stunning Miyazaki epic, gorgeous visuals and deep themes.', null); # 174953 Kaze no tani no Naushika 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30965, 5, 'Ronamit01', 'Too campy, Jim Carrey is fun but the film is a mess.', null); # 30965 Batman Forever 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30952, 3, 'Ronamit01', 'One of the worst superhero movies, embarrassingly bad.', null); # 30952 Batman & Robin 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30976, 7, 'Ronamit01', 'Excellent animated Batman, better than most live-action entries.', null); # 30976 Batman: Mask of the Phantasm 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (94741, 8, 'Ronamit01', 'Spielberg tension at its purest, riveting from start to finish.', null); # 94741 Duel 1971
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (270628, 7, 'Ronamit01', 'Emotional Richard Donner film about childhood trauma, Tom Hanks narrates.', null); # 270628 Radio Flyer 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (336445, 7, 'Ronamit01', 'Intense and raw, DiCaprio gives a brave early performance.', null); # 336445 Total Eclipse 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215880, 7, 'Ronamit01', 'More polished and action-packed than the earlier entries.', null); # 215880 Mission: Impossible III 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (20253, 7, 'Ronamit01', 'Quirky surreal drama, Depp at his most unpredictable.', null); # 20253 Arizona Dream 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30961, 7, 'Ronamit01', 'Great animated continuation of Batman Beyond, dark and fun.', null); # 30961 Batman Beyond: Return of the Joker 2000
