insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (310726, 8, 'roni88882-ctrl', 'non-stop adrenaline from start to finish', null); # 310726 Speed 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (9023, 8, 'roni88882-ctrl', 'Harrison Ford saves the day aboard his own plane', null); # 9023 Air Force One 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (303564, 9, 'roni88882-ctrl', 'twist ending I never saw coming', null); # 303564 Sixth Sense, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (345690, 2, 'roni88882-ctrl', 'interesting concept but slow and underwhelming', null); # 345690 Unbreakable 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (301391, 4, 'roni88882-ctrl', 'genuinely creepy atmosphere throughout', null); # 301391 Signs 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (134077, 9, 'roni88882-ctrl', 'Michael Clarke Duncan broke my heart', null); # 134077 Green Mile, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (337830, 9, 'roni88882-ctrl', 'a raw and honest portrait of addiction', null); # 337830 Trainspotting 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (239851, 9, 'roni88882-ctrl', 'nothing prepares you for the ending', null); # 239851 Oldboy 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (220171, 8, 'roni88882-ctrl', 'beautiful road trip across South America', null); # 220171 Motorcycle Diaries, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (282696, 8, 'roni88882-ctrl', 'perfectly crafted deadpan family comedy', null); # 282696 Royal Tenenbaums, The 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (283739, 8, 'roni88882-ctrl', 'Bill Murray at his understated best', null); # 283739 Rushmore 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (232425, 9, 'roni88882-ctrl', 'Tim Burton magic in every single frame', null); # 232425 Nightmare Before Christmas, The 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (362808, 9, 'roni88882-ctrl', 'best romantic comedy ever made', null); # 362808 When Harry Met Sally... 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (17760, 9, 'roni88882-ctrl', 'Woody Allen reinvented the love story', null); # 17760 Annie Hall 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (73303, 9, 'roni88882-ctrl', 'darkest and deepest Allen film by far', null); # 73303 Crimes and Misdemeanors 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (97727, 9, 'roni88882-ctrl', 'heartbreaking fairytale about being different', null); # 97727 Edward Scissorhands 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (304829, 8, 'roni88882-ctrl', 'Tom Hanks and Meg Ryan are perfect together', null); # 304829 Sleepless in Seattle 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46322, 9, 'roni88882-ctrl', 'defined an entire generation of teenagers', null); # 46322 Breakfast Club, The 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (369458, 8, 'roni88882-ctrl', 'smart and emotional superhero cinema', null); # 369458 X-Men 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30967, 8, 'roni88882-ctrl', 'Michelle Pfeiffer stole the entire film', null); # 30967 Batman Returns 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (142491, 7, 'roni88882-ctrl', 'Ron Perlman was born to play this role', null); # 142491 Hellboy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (61156, 8, 'roni88882-ctrl', 'all that jazz - slick and entertaining', null); # 61156 Chicago 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (209133, 8, 'roni88882-ctrl', 'so fetch - Tina Fey at her sharpest', null); # 209133 Mean Girls 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (187191, 1, 'roni88882-ctrl', 'annoying and shallow - not as smart as it thinks it is', null); # 187191 Legally Blonde 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (336458, 8, 'roni88882-ctrl', 'paranoid and fun - is any of it real', null); # 336458 Total Recall 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (27168, 7, 'roni88882-ctrl', 'Will Smith and Lawrence have great chemistry', null); # 27168 Bad Boys 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210739, 9, 'roni88882-ctrl', 'Will Smith and Tommy Lee Jones are perfect', null); # 210739 Men in Black 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (158999, 8, 'roni88882-ctrl', 'that speech still gives me chills', null); # 158999 Independence Day 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (342685, 7, 'roni88882-ctrl', 'fun disaster movie done right', null); # 342685 Twister 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (68940, 7, 'roni88882-ctrl', 'Nicolas Cage at his most absurdly wonderful', null); # 68940 Con Air 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (107166, 8, 'roni88882-ctrl', 'John Woo action opera at peak craziness', null); # 107166 Face/Off 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215876, 8, 'roni88882-ctrl', 'Langley heist scene is cinema perfection', null); # 215876 Mission: Impossible 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (340652, 7, 'roni88882-ctrl', 'Brad Pitt as Achilles is magnetic', null); # 340652 Troy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311038, 9, 'roni88882-ctrl', 'best Marvel film of its generation', null); # 311038 Spider-Man 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (375827, 8, 'roni88882-ctrl', 'Blue Steel is funnier every single time', null); # 375827 Zoolander 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (189233, 8, 'roni88882-ctrl', 'Jim Carrey at peak physical comedy', null); # 189233 Liar Liar 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (330057, 8, 'roni88882-ctrl', 'somehow gross and charming at once', null); # 330057 There\'s Something About Mary 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (182955, 9, 'roni88882-ctrl', 'perfect neo-noir from start to finish', null); # 182955 L.A. Confidential 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (20371, 5, 'roni88882-ctrl', 'dumb fun with a surprisingly emotional ending', null); # 20371 Armageddon 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (323813, 8, 'roni88882-ctrl', 'Matt Damon is quietly terrifying', null); # 323813 Talented Mr. Ripley, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185628, 8, 'roni88882-ctrl', 'Ken Watanabe deserved the Oscar', null); # 185628 Last Samurai, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (262645, 8, 'roni88882-ctrl', 'Schwarzenegger vs alien - pure genre gold', null); # 262645 Predator 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (279841, 8, 'roni88882-ctrl', 'smarter satire than it looks', null); # 279841 RoboCop 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (127073, 8, 'roni88882-ctrl', 'the pottery scene is forever iconic', null); # 127073 Ghost 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (346949, 10, 'roni88882-ctrl', 'the definitive Western and a masterpiece', null); # 346949 Unforgiven 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (77728, 9, 'roni88882-ctrl', 'earned every one of its seven Oscars', null); # 77728 Dances with Wolves 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (26064, 9, 'roni88882-ctrl', 'that will do Pig - perfection', null); # 26064 Babe 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (99164, 9, 'roni88882-ctrl', 'Will Ferrell makes Christmas magic', null); # 99164 Elf 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (14131, 8, 'roni88882-ctrl', 'funniest teen comedy of the 90s', null); # 14131 American Pie 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (302329, 8, 'roni88882-ctrl', 'visually unlike anything before it', null); # 302329 Sin City 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (146780, 8, 'roni88882-ctrl', 'Will Smith\'s funniest and warmest film', null); # 146780 Hitch 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (70468, 8, 'roni88882-ctrl', 'Stallone\'s best dramatic performance ever', null); # 70468 Cop Land 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280284, 8, 'roni88882-ctrl', 'Rocky vs Drago - Cold War cinema', null); # 280284 Rocky IV 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (114067, 9, 'roni88882-ctrl', 'serious and moving story about veterans', null); # 114067 First Blood 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10920, 10, 'roni88882-ctrl', 'James Cameron perfected the action sequel', null); # 10920 Aliens 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (328281, 6, 'roni88882-ctrl', 'the dark ending redeems it somewhat', null); # 328281 Terminator 3: Rise of the Machines 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (68309, 8, 'roni88882-ctrl', 'Schwarzenegger saving his daughter in style', null); # 68309 Commando 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (283543, 8, 'roni88882-ctrl', 'prescient satire of reality television', null); # 283543 Running Man, The 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (102341, 7, 'roni88882-ctrl', 'stylish and entertaining 90s Schwarzenegger', null); # 102341 Eraser 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30965, 6, 'roni88882-ctrl', 'Jim Carrey makes it watchable', null); # 30965 Batman Forever 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30952, 3, 'roni88882-ctrl', 'ice to meet you - unwatchably bad', null); # 30952 Batman & Robin 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (319613, 8, 'roni88882-ctrl', 'Zod vs Superman is everything', null); # 319613 Superman II 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (207157, 9, 'roni88882-ctrl', 'Jim Carrey fully unleashed - pure joy', null); # 207157 Mask, The 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (79044, 7, 'roni88882-ctrl', 'early Raimi ingenuity before the budgets came', null); # 79044 Darkman 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (54209, 8, 'roni88882-ctrl', 'De Niro is terrifyingly good as Cady', null); # 54209 Cape Fear 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (334212, 10, 'roni88882-ctrl', 'Atticus Finch is cinema\'s moral compass', null); # 334212 To Kill a Mockingbird 1962
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (15936, 9, 'roni88882-ctrl', 'the best courtroom film ever made', null); # 15936 Anatomy of a Murder 1959
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (366987, 9, 'roni88882-ctrl', 'Agatha Christie\'s greatest twist on screen', null); # 366987 Witness for the Prosecution 1957
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159706, 9, 'roni88882-ctrl', 'Tracy vs March - unmissable', null); # 159706 Inherit the Wind 1960
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (169942, 10, 'roni88882-ctrl', 'essential and devastating historical cinema', null); # 169942 Judgment at Nuremberg 1961
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (180705, 9, 'roni88882-ctrl', 'Hoffman and Streep at their very best', null); # 180705 Kramer vs. Kramer 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (243276, 9, 'roni88882-ctrl', 'quietly devastating portrait of family grief', null); # 243276 Ordinary People 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (254654, 9, 'roni88882-ctrl', 'Hepburn Grant Stewart - comedy perfection', null); # 254654 Philadelphia Story, The 1940
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (80583, 9, 'roni88882-ctrl', 'carpe diem - Robin Williams at his best', null); # 80583 Dead Poets Society 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (166917, 8, 'roni88882-ctrl', 'you had me at hello - still works', null); # 166917 Jerry Maguire 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (250514, 7, 'roni88882-ctrl', 'Robin Williams is genuinely moving here', null); # 250514 Patch Adams 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (362188, 7, 'roni88882-ctrl', 'visually stunning and emotionally ambitious', null); # 362188 What Dreams May Come 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (281937, 9, 'roni88882-ctrl', 'slow dread masterpiece - Mia Farrow is perfect', null); # 281937 Rosemary\'s Baby 1968
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (273585, 9, 'roni88882-ctrl', 'Hitchcock\'s gothic romance is lush and tense', null); # 273585 Rebecca 1940
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (235676, 9, 'roni88882-ctrl', 'Cary Grant and Bergman are unforgettable', null); # 235676 Notorious 1946
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (281546, 8, 'roni88882-ctrl', 'Hitchcock\'s real-time murder party experiment', null); # 281546 Rope 1948
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (316323, 9, 'roni88882-ctrl', 'criss-cross - perfectly structured thriller', null); # 316323 Strangers on a Train 1951
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (206255, 7, 'roni88882-ctrl', 'flawed but fascinating Hitchcock', null); # 206255 Marnie 1964
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (190046, 8, 'roni88882-ctrl', 'Bill Murray\'s melancholy is infectious', null); # 190046 Life Aquatic with Steve Zissou, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (227925, 10, 'roni88882-ctrl', 'nothing in cinema quite like this', null); # 227925 Nashville 1975
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (299846, 9, 'roni88882-ctrl', 'Altman\'s best - 22 characters and still coherent', null); # 299846 Short Cuts 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (208878, 9, 'roni88882-ctrl', 'the saddest and most beautiful Western', null); # 208878 McCabe & Mrs. Miller 1971
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (257689, 9, 'roni88882-ctrl', 'Hollywood satirizing itself at its finest', null); # 257689 Player, The 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194818, 8, 'roni88882-ctrl', 'Lynch at his most hypnotically unsettling', null); # 194818 Lost Highway 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (41988, 9, 'roni88882-ctrl', 'suburbia hiding horror - unforgettable', null); # 41988 Blue Velvet 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (365169, 7, 'roni88882-ctrl', 'Cage and Dern make the excess work', null); # 365169 Wild at Heart 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (102344, 7, 'roni88882-ctrl', 'the original midnight movie nightmare', null); # 102344 Eraserhead 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (41308, 8, 'roni88882-ctrl', 'Coen Brothers debut - already masterful', null); # 41308 Blood Simple. 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (152222, 8, 'roni88882-ctrl', 'gloriously stylized Coen Brothers comedy', null); # 152222 Hudsucker Proxy, The 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (271339, 9, 'roni88882-ctrl', 'Nicolas Cage at his anarchic peak', null); # 271339 Raising Arizona 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (303399, 8, 'roni88882-ctrl', 'Shaolin Soccer - absurd and brilliant', null); # 303399 Siu lam juk kau 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (298691, 9, 'roni88882-ctrl', 'House of Flying Daggers - breathtaking cinema', null); # 298691 Shi mian mai fu 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (371615, 9, 'roni88882-ctrl', 'Hero - color as storytelling language', null); # 371615 Ying xiong 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (47132, 9, 'roni88882-ctrl', 'peak screwball chaos with Hepburn and Grant', null); # 47132 Bringing Up Baby 1938
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (145961, 9, 'roni88882-ctrl', 'fastest dialogue ever recorded on film', null); # 145961 His Girl Friday 1940
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (349550, 9, 'roni88882-ctrl', 'Chevy Chase at his absolute funniest', null); # 349550 Vacation 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (63134, 9, 'roni88882-ctrl', 'the definitive Christmas family comedy', null); # 63134 Christmas Vacation 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (351187, 7, 'roni88882-ctrl', 'Nick Papageorgio - classic moment', null); # 351187 Vegas Vacation 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (104681, 6, 'roni88882-ctrl', 'Griswolds terrorize Europe amusingly', null); # 104681 European Vacation 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (228313, 7, 'roni88882-ctrl', 'Nicolas Cage stealing the Declaration - why not', null); # 228313 National Treasure 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256630, 9, 'roni88882-ctrl', 'Captain Jack Sparrow is an instant icon', null); # 256630 Pirates of the Caribbean: The Curse of the Black Pearl 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256631, 7, 'roni88882-ctrl', 'Davy Jones is a great villain', null); # 256631 Pirates of the Caribbean 2 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280282, 8, 'roni88882-ctrl', 'Mr T and Hulk Hogan - peak entertainment', null); # 280282 Rocky III 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (340119, 10, 'roni88882-ctrl', 'Binoche processing grief - extraordinarily moving', null); # 340119 Trois couleurs: Bleu 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (340120, 10, 'roni88882-ctrl', 'Kieslowski\'s final film - a perfect ending', null); # 340120 Trois couleurs: Rouge 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (91912, 9, 'roni88882-ctrl', 'mysterious and visually ravishing', null); # 91912 Double vie de Vronique, La 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (192413, 8, 'roni88882-ctrl', 'Gillian Armstrong\'s warm and beautiful adaptation', null); # 192413 Little Women 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (250612, 10, 'roni88882-ctrl', 'Kubrick\'s angriest film - still relevant', null); # 250612 Paths of Glory 1957
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (358708, 9, 'roni88882-ctrl', 'greed is good - Michael Douglas at his best', null); # 358708 Wall Street 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335380, 10, 'roni88882-ctrl', 'pure childhood wonder - Miyazaki\'s magic', null); # 335380 Tonari no Totoro 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (150507, 10, 'roni88882-ctrl', 'most heartbreaking animated film ever made', null); # 150507 Hotaru no haka 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (140221, 9, 'roni88882-ctrl', 'Howl\'s Moving Castle - dreamlike and beautiful', null); # 140221 Hauru no ugoku shiro 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (174953, 9, 'roni88882-ctrl', 'Nausicaa - Miyazaki\'s eco-warrior masterpiece', null); # 174953 Kaze no tani no Naushika 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (184805, 9, 'roni88882-ctrl', 'Castle in the Sky - adventure and wonder', null); # 184805 Laputa 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (181996, 8, 'roni88882-ctrl', 'Porco Rosso - melancholy flying pig film', null); # 181996 Kurenai no buta 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (230151, 10, 'roni88882-ctrl', 'mad as hell - terrifyingly prophetic still', null); # 230151 Network 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (132525, 10, 'roni88882-ctrl', 'Mrs Robinson - defined a generation\'s confusion', null); # 132525 Graduate, The 1967
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (270008, 9, 'roni88882-ctrl', 'Redford\'s best film as director', null); # 270008 Quiz Show 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335799, 9, 'roni88882-ctrl', 'Hoffman in drag - funnier than it has any right', null); # 335799 Tootsie 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (89147, 9, 'roni88882-ctrl', 'Pacino at his most human and desperate', null); # 89147 Dog Day Afternoon 1975
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (66194, 9, 'roni88882-ctrl', 'as if - sharper than anyone expected', null); # 66194 Clueless 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (644, 8, 'roni88882-ctrl', 'Heath Ledger singing on the bleachers', null); # 644 10 Things I Hate About You 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (264146, 10, 'roni88882-ctrl', 'as you wish - inconceivably rewatchable', null); # 264146 Princess Bride, The 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (241141, 10, 'roni88882-ctrl', 'Leone\'s most ambitious and sprawling masterpiece', null); # 241141 Once Upon a Time in America 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (267165, 9, 'roni88882-ctrl', 'Adam Sandler\'s best film - surprisingly moving', null); # 267165 Punch-Drunk Love 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (245103, 9, 'roni88882-ctrl', 'Clooney and Lopez - coolest crime film of the 90s', null); # 245103 Out of Sight 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (80050, 9, 'roni88882-ctrl', 'alright alright alright - perfect summer film', null); # 80050 Dazed and Confused 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (358476, 8, 'roni88882-ctrl', 'philosophical dream logic - unlike anything else', null); # 358476 Waking Life 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (44450, 9, 'roni88882-ctrl', 'Cruise transforms completely - Oliver Stone at best', null); # 44450 Born on the Fourth of July 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (328301, 9, 'roni88882-ctrl', 'Shirley MacLaine won the Oscar and deserved it', null); # 328301 Terms of Endearment 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (191240, 10, 'roni88882-ctrl', 'O\'Toole vs Hepburn - greatest acting duel ever', null); # 191240 Lion in Winter, The 1968
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (33190, 9, 'roni88882-ctrl', 'Peter Sellers\' most devastating and quiet performance', null); # 33190 Being There 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (133574, 9, 'roni88882-ctrl', 'the greatest WWII ensemble film ever assembled', null); # 133574 Great Escape, The 1963
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (363300, 8, 'roni88882-ctrl', 'Burton and Eastwood in a Nazi fortress - thrilling', null); # 363300 Where Eagles Dare 1968
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (87323, 9, 'roni88882-ctrl', 'the original men-on-a-mission film', null); # 87323 Dirty Dozen, The 1967
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (167324, 9, 'roni88882-ctrl', 'three hours of conspiracy brilliance', null); # 167324 JFK 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218848, 9, 'roni88882-ctrl', 'Cher and Cage - unexpectedly deep and funny', null); # 218848 Moonstruck 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (294855, 9, 'roni88882-ctrl', 'Pacino as the whistleblower - urgent and vital', null); # 294855 Serpico 1973
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (233307, 8, 'roni88882-ctrl', 'Hopkins disappears completely into Nixon', null); # 233307 Nixon 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (11525, 9, 'roni88882-ctrl', 'the definitive political journalism film', null); # 11525 All the President\'s Men 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (68162, 8, 'roni88882-ctrl', 'Jane Fonda and Voight - honest Vietnam portrait', null); # 68162 Coming Home 1978
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (67395, 9, 'roni88882-ctrl', 'Whoopi Goldberg\'s most powerful performance', null); # 67395 Color Purple, The 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (21213, 7, 'roni88882-ctrl', 'Kubrick idea Spielberg execution - interesting', null); # 21213 Artificial Intelligence: AI 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (14477, 8, 'roni88882-ctrl', 'Djimon Hounsou is overwhelming in this', null); # 14477 Amistad 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (359297, 8, 'roni88882-ctrl', 'genuinely terrifying alien invasion film', null); # 359297 War of the Worlds 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (100130, 9, 'roni88882-ctrl', 'Christian Bale at 13 is astonishing', null); # 100130 Empire of the Sun 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (314935, 9, 'roni88882-ctrl', 'the perfect con - Redford and Newman again', null); # 314935 Sting, The 1973
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (119756, 9, 'roni88882-ctrl', 'greatest car chase ever filmed', null); # 119756 French Connection, The 1971
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (138444, 9, 'roni88882-ctrl', 'Allen at his most generous and warm', null); # 138444 Hannah and Her Sisters 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (204163, 9, 'roni88882-ctrl', 'the most beautiful love letter to New York', null); # 204163 Manhattan 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (204190, 8, 'roni88882-ctrl', 'Allen and Keaton reunited - effortless fun', null); # 204190 Manhattan Murder Mystery 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (153190, 8, 'roni88882-ctrl', 'shaky camera raw emotion - feels completely real', null); # 153190 Husbands and Wives 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (270622, 9, 'roni88882-ctrl', 'nostalgic and funny and genuinely moving', null); # 270622 Radio Days 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (228434, 8, 'roni88882-ctrl', 'Oliver Stone\'s most provocative and inventive work', null); # 228434 Natural Born Killers 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313583, 7, 'roni88882-ctrl', 'Allen\'s most honest and controversial self-portrait', null); # 313583 Stardust Memories 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (27486, 10, 'roni88882-ctrl', 'Malick\'s debut - Sheen and Spacek unforgettable', null); # 27486 Badlands 1973
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (80015, 10, 'roni88882-ctrl', 'the most visually beautiful American film ever made', null); # 80015 Days of Heaven 1978
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215346, 8, 'roni88882-ctrl', 'Kathy Bates is terrifyingly good - one of the best', null); # 215346 Misery 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (137655, 9, 'roni88882-ctrl', 'invented the slasher film - still effective', null); # 137655 Halloween 1978
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (291221, 8, 'roni88882-ctrl', 'meta horror that also delivers genuine scares', null); # 291221 Scream 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (40226, 7, 'roni88882-ctrl', 'that final basement scene haunted me for weeks', null); # 40226 Blair Witch Project, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (82451, 9, 'roni88882-ctrl', 'terrifying survival thriller - squeal like a pig', null); # 82451 Deliverance 1972
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (178813, 8, 'roni88882-ctrl', 'Jane Fonda\'s first Oscar - completely earned', null); # 178813 Klute 1971
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (207099, 9, 'roni88882-ctrl', 'Altman\'s anarchic anti-war comedy classic', null); # 207099 MASH 1970
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (310184, 8, 'roni88882-ctrl', 'may the Schwartz be with you - Mel Brooks gold', null); # 310184 Spaceballs 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (265288, 9, 'roni88882-ctrl', 'Zero Mostel and Wilder - comedy perfection', null); # 265288 Producers, The 1968
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (372551, 10, 'roni88882-ctrl', 'puttin on the Ritz - Mel Brooks at his peak', null); # 372551 Young Frankenstein 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (40472, 9, 'roni88882-ctrl', 'the funniest and bravest Western ever made', null); # 40472 Blazing Saddles 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (301669, 7, 'roni88882-ctrl', 'only silent film where Marcel Marceau speaks', null); # 301669 Silent Movie 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (144760, 7, 'roni88882-ctrl', 'loving and witty Hitchcock parody', null); # 144760 High Anxiety 1977
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (279755, 7, 'roni88882-ctrl', 'I can see his home from here - silly and fun', null); # 279755 Robin Hood: Men in Tights 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139543, 10, 'roni88882-ctrl', 'strangest and most beautiful love story in cinema', null); # 139543 Harold and Maude 1971
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (13963, 9, 'roni88882-ctrl', 'Lucas captured the last innocent American summer', null); # 13963 American Graffiti 1973
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (114618, 9, 'roni88882-ctrl', 'Nicholson\'s chicken salad scene is cinema history', null); # 114618 Five Easy Pieces 1970
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185537, 10, 'roni88882-ctrl', 'the saddest and most perfect portrait of small town America', null); # 185537 Last Picture Show, The 1971
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (248087, 8, 'roni88882-ctrl', 'John Houseman is terrifying as Professor Kingsfield', null); # 248087 Paper Chase, The 1973
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (240327, 8, 'roni88882-ctrl', 'it\'s all for you Damien - genuinely chilling', null); # 240327 Omen, The 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120116, 6, 'roni88882-ctrl', 'the twist ending launched a franchise', null); # 120116 Friday the 13th 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (278498, 8, 'roni88882-ctrl', 'Naomi Watts and seven days of dread', null); # 278498 Ring, The 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (232458, 8, 'roni88882-ctrl', 'killing you in dreams is the perfect horror concept', null); # 232458 Nightmare On Elm Street, A 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (259826, 8, 'roni88882-ctrl', 'they\'re here - still terrifying decades later', null); # 259826 Poltergeist 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (18828, 10, 'roni88882-ctrl', 'Billy Wilder\'s most human and perfect film', null); # 18828 Apartment, The 1960
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (162302, 8, 'roni88882-ctrl', 'Wilder and Lemmon - reliably wonderful together', null); # 162302 Irma la Douce 1963
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312934, 9, 'roni88882-ctrl', 'best WWII POW film with a great twist', null); # 312934 Stalag 17 1953
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (195702, 8, 'roni88882-ctrl', 'Hepburn and Wilder - elegant Parisian romance', null); # 195702 Love in the Afternoon 1957
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (5545, 9, 'roni88882-ctrl', 'Wilder\'s sharpest and most cynical film', null); # 5545 Ace in the Hole 1951
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (105280, 8, 'roni88882-ctrl', 'Allen\'s musical comedy - warm and surprising', null); # 105280 Everyone Says I Love You 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (81649, 8, 'roni88882-ctrl', 'Allen\'s most raw and confessional work', null); # 81649 Deconstructing Harry 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (321126, 8, 'roni88882-ctrl', 'Sean Penn as a jazz guitarist - surprisingly moving', null); # 321126 Sweet and Lowdown 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (284931, 8, 'roni88882-ctrl', 'Audrey Hepburn and Billy Wilder - pure charm', null); # 284931 Sabrina 1954
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (295403, 8, 'roni88882-ctrl', 'the subway grate scene is cinema history', null); # 295403 Seven Year Itch, The 1955
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (57654, 7, 'roni88882-ctrl', 'Allen examining fame and desire sharply', null); # 57654 Celebrity 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (38614, 9, 'roni88882-ctrl', 'inexplicable bird attacks - still unsettling', null); # 38614 Birds, The 1963
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (305390, 7, 'roni88882-ctrl', 'Allen\'s lightest and most enjoyable late comedy', null); # 305390 Small Time Crooks 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (147694, 7, 'roni88882-ctrl', 'psychosomatically blind director - sharp comic idea', null); # 147694 Hollywood Ending 2002
